### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by pzkpfwVI** [BTCTrader/broker-api-docs#1]
When I send this using Python 2.7 and requests:

https://www.btcturk.com/api/balance?X-Signature=86744642F1EE15C2E6F9EDD2960D6EAD3C5767B38D301D0E53EB064F75B274FA&X-PCK=55d8a5568466ad31149f0b95&X-Stamp=1441024485

I get this 401:

{u'message': u'Unauthorized - Invalid Public key', u'code': 401}

The public key is correct. 

What am I doing wrong? Please advise 

Note: API Key is read only

**Comment by hu53yin** [comment]
You must select money deposit/withdrawal option for your api key.

![image](https://cloud.githubusercontent.com/assets/316321/9581769/1922ee30-500a-11e5-9a4d-9d4394a0c9fb.png)

**Comment by emrekenci** [comment]
x-signature,  x-pck and x-stamp must be added to the request headers not sent as get request a parameter. Please see the sample implementations.
