### ISSUE TITLE
Golang Auth Problem

### ISSUE THREAD

**Issue by theduman** [BTCTrader/broker-api-docs#10]
Hi i keep getting 401 error. Here is my code for authentication. Im pretty sure i followed instructions correctly.
    
     func getAccountBalance() {
	    timeStamp := fmt.Sprint(int32(time.Now().Unix()))
	    signature := ComputeHmac256("myPublicAPIKEY"+timeStamp, "myAPISecret")
	    client := &http.Client{}
	    req, _ := http.NewRequest("GET", "https://www.btcturk.com/api/balance", nil)
	    req.Header.Set("X-PCK", "myPublicAPIKEY")
	    req.Header.Set("X-Stamp", timeStamp)
	    req.Header.Set("X-Signature", signature)

	    resp, _ := client.Do(req)
	    bodyBytes, _ := ioutil.ReadAll(resp.Body)
 	    bodyString := string(bodyBytes)
	    fmt.Println(bodyString)
    }

    func ComputeHmac256(message string, secret string) string {
        fmt.Println(message)
	    fmt.Println(secret)
	    key := []byte(secret)
	    h := hmac.New(sha256.New, key)
	    h.Write([]byte(message))
	    fmt.Println(hex.EncodeToString(h.Sum(nil)))
	    return hex.EncodeToString(h.Sum(nil))
    }

**Comment by BTCTraderAdmin** [comment]
Hi,
If you used your existed API keys before, then system record the nonce you sent and waits bigger number. Please create new api key and try again or send with exactly same nonce method.
