### ISSUE TITLE
Test sayfası açılmıyor

### ISSUE THREAD

**Issue by MaDeRkAn** [BTCTrader/broker-api-docs#101]
Merhaba https://btctrader-broker-btcturk.azurewebsites.net/ test sayfası açılmıyor. Serverı tekrar başlatırsanız sevinirim.

**Comment by BTCTraderAdmin** [comment]
Yeni test adres https://test.btcturk.com kullanabilirsiniz.

**Comment by ghost** [comment]
Yeni test sayfanız da açılmıyor!
