### ISSUE TITLE
Test sitesi kayıt hatası

### ISSUE THREAD

**Issue by MaDeRkAn** [BTCTrader/broker-api-docs#102]
https://test.btcturk.com/

Yeni test sitesinde kayıt sırasında sorun oluşuyor. Kayıt forumu post edildiğinde 500 dönüyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
