### ISSUE TITLE
API Auth

### ISSUE THREAD

**Issue by chmod777-R** [BTCTrader/broker-api-docs#104]

**Comment by insayd10** [comment]
my headers : 
`         "User-Agent": "User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1b3pre) Gecko/20081130 Minefield/3.1b3pre",
         'Content-Type': '*',
         "X-PCK": headers[0],
         "X-Stamp": headers[1],
         "X-Signature": headers[2]`
