### ISSUE TITLE
Get Balance, return 500, An error has occurred

### ISSUE THREAD

**Issue by choiking** [BTCTrader/broker-api-docs#105]
Merhaba！
"https://www.btcturk.com/api/balance" use this to get balance, return 500, An error has occurred.
"https://www.btcturk.com/api/openOrders?pairSymbol=BTCTRY" sucessfully return.

Everything else is the same, so there must be something wrong with balance API

**Comment by choiking** [comment]
Merhaba！
"https://www.btcturk.com/api/balance" use this to get balance, return 500, An error has occurred.
"https://www.btcturk.com/api/openOrders?pairSymbol=BTCTRY" sucessfully return.

Everything else is the same, so there must be something wrong with balance API

**Comment by choiking** [comment]
edit title

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
