### ISSUE TITLE
limit sell order precision hatasi

### ISSUE THREAD

**Issue by paddlesteamer** [BTCTrader/broker-api-docs#106]
{'PairSymbol': 'BTCTRY', 'Amount': '0', 'AmountPrecision': '25', 'Price': '22262', 'PricePrecision': '85', 'Total': '00', 'TotalPrecision': '0', 'TriggerPrice': '0', 'TriggerPricePrecision': '00', 'OrderMethod': 0, 'OrderType': 1, 'DenominatorPrecision': 2}

seklinde bir request gonderince 

{"id":"32888270","datetime":"2019-03-27T13:57:17.7041324Z","type":"Sell","price":22262.0,"amount":0.25,"pairsymbol":null}

yaniti aliyorum. Yalniz price'in 22262.85 olmasi gerekirken PricePrecision'da verdigim degeri onemsemeyerek 22262.0 olarak order aciyor. Bu da satmak istedigim fiyattan daha asagisina satmama sebep oluyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
