### ISSUE TITLE
XLM ticker degeri tek hane geliyor

### ISSUE THREAD

**Issue by ocengiz0** [BTCTrader/broker-api-docs#108]
Merhaba,

Ticker datasinda XLM degeri tek hane geliyor, 4 hane olarak guncelleyebilir misiniz?

**Comment by ghalacli** [comment]
Bu sorun bir an önce çözülürse sevinirim, bot hatalı işlem yapıyor bu durumdan dolayı.

**Comment by ocengiz0** [comment]
API'da guncelleme yapinca zahmet edip buraya da yazabilirseniz, biz de takip etmis oluruz.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
