### ISSUE TITLE
PHP Auth Problem "Unauthorized - Invalid Request"

### ISSUE THREAD

**Issue by ameydan** [BTCTrader/broker-api-docs#11]
I have getting 401 error;
`object(stdClass)#1 (2) { ["code"]=> int(401) ["message"]=> string(30) "Unauthorized - Invalid Request" }`

My script is below;

`<?php

$baseURL = 'https://www.btcturk.com/api/';

$PrivateKey = '****';
$APIKey = '(Public Key)';

$message=$APIKey.time();
$signatureBytes = hash_hmac('sha256', $message, base64_decode($privateKey), TRUE);
$signature=base64_encode($signatureBytes);

$url=$baseURL.'balance';
$nonce=time();
$headers=array(
'X-PCK: '.$APIKey,
'X-Stamp: '.$nonce,
'X-Signature: '.$signature
);

$ch=null;
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
$result=curl_exec($ch);
// echo var_dump(curl_getinfo($ch));
curl_close($ch);

$r=json_decode($result);

var_dump($r);

?>`

thanks

**Comment by BTCTraderAdmin** [comment]
You can check #3
