### ISSUE TITLE
Hesap Hareketlerinde XLM Alış-Satış Fiyatları noktadan sonra 2 hane görünüyor!

### ISSUE THREAD

**Issue by bbdundar** [BTCTrader/broker-api-docs#110]
XLM islem fiyatlarini noktadan sonra 4 haneye cikarmaniz yerinde oldu ancak web sitesinin diger yerlerinde de ayni degisikligi yapmaniz gerekiyor. Yapilan alim satim islemlerinin hangi fiyattan gerceklestigini goremiyoruz.

Diger alternatif /api/userTransactions uzun zamandir kullanilmaz halde. 

Lutfen bu basit degisiklikleri yapabilir misiniz? Tesekkurler.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
