### ISSUE TITLE
al sat işlemleri eskiye nazaran yavaşlık

### ISSUE THREAD

**Issue by Cagatay342** [BTCTrader/broker-api-docs#112]
satin alma işlemi satma işlemleri eskiden hızlıydı simdi nerdeyse 2 saniyeye yakın suruyor bilerek bi yavaslatılmamı var acaba ? (farkli internetlerde denedim)

**Comment by BTCTraderAdmin** [comment]
Bakım çalışması sebebiyle bir yaşanmış bir yavaşlık olabilir. Gerekli düzenlemeler giderilmiştir. Tekrar kontrol edebilirseniz memnun oluruz.
