### ISSUE TITLE
API hatalı bilgi veriyor

### ISSUE THREAD

**Issue by pzkpfwVI** [BTCTrader/broker-api-docs#113]
API yaklaşık yarım saatte bir bitcoin alım fiyatını olduğundan %9 yüksek gösteriyor.

**Comment by ghalacli** [comment]
Doğru

**Comment by BTCTraderAdmin** [comment]
Tekrar kontrol edebilir misiniz? Herhangi bir problem görünmüyor. Aynı problem ile karşılaşırsanız bir ekran görüntüsü ile tarafımıza bilgi verirseniz memnun oluruz.

**Comment by ghalacli** [comment]
Sorun devam ediyor, fiyat çok kısa süreli olarak yanlış gösteriyor yaklaşık %9 fazla yada %9 az gösteriyor normal fiyattan, çok kısa süreli olduğu için ekran görüntüsü almak zor. Çalıştırdığım bot bu durumdan dolayı hatalı al-sat işlemi yapıyor.

**Comment by ocengiz0** [comment]
yarim saatte bir problem oluyor fiyatlarda

**Comment by BTCTraderAdmin** [comment]
Tekrar kontrol etmenizi rica edeceğiz. Bir düzeltme daha yaptık. Bilgilendirmeniz için teşekkür ederiz.

**Comment by ghalacli** [comment]
Bitcoin alış fiyatını 31589 tl gösterdi demin
![image](https://user-images.githubusercontent.com/43678360/55940428-ca1fe780-5c48-11e9-8497-8eeb7eeb0ea2.png)

**Comment by pzkpfwVI** [comment]
Bir süredir düzeldi gibi. API'nin her verisi doğru mu bilmiyorum ama bir süredir doğru gibi görünüyor, en azından eskisi kadar çok oranda hatalı değil.

![image](https://user-images.githubusercontent.com/8700952/56081745-45d08e80-5e19-11e9-9ccd-0db98563190e.png)

**Comment by BTCTraderAdmin** [comment]
Gerekli güncellemeler yapılmıştır. Sorunun giderilmiş olması gerekiyor. Kontrol edebilirsiniz. Teşekkürler.
