### ISSUE TITLE
./api/userTransactions?offset=OFFSET&limit=LIMIT&sort=SORT Parameters NOT WORKING 

### ISSUE THREAD

**Issue by sukru77** [BTCTrader/broker-api-docs#114]
offset, limit, and sort parameters are NOT working. This api always returns the last 25 transaction items no matter what you pass to these 3 parameters. Seems like parameters are ignored! Please fix this so we can retrieve ALL trade history using api with the parameters.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
