### ISSUE TITLE
Eksik marketler

### ISSUE THREAD

**Issue by ocengiz0** [BTCTrader/broker-api-docs#115]
https://www.btcturk.com/api/ticker servisinde BTC market hic yok, USDT marketinde eksik var.

**Comment by onurgozupek** [comment]
Merhaba, yeni işlem çiftleri sadece BtcTurk | PRO’da olduğu için bu API yeni çiftleri göstermiyor. https://api.btcturk.com/api adresini kullanabilirsiniz. Dokümanı https://github.com/BTCTrader/broker-api-docs/blob/master/README-beta.md

**Comment by sukru77** [comment]
Onur bey, Bu gönderdiğiniz yeni api linkine baktım.

Kullanmayi deniyorum ama Unauthorized error u alıyorum nedense.

Asagidaki kullandigim java kodu: nerde hata yapiyorum acaba?

public static final String PUBLIC_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
public static final String PRIVATE_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
public static final String URL = "https://api.btcturk.com/api/v1/users/transactions/trade?type=buy&type=sell&symbol=btc&symbol=try&symbol=usdt&symbol=ltc&symbol=eth&symbol=xrp&symbol=xlm";

public static void main(String[] args) throws NoSuchAlgorithmException, InvalidKeyException, IOException {
    Mac sha256_hmac = Mac.getInstance("HmacSHA256");;
    SecretKeySpec secret_key = new SecretKeySpec(Base64.decodeBase64(PRIVATE_KEY.getBytes(StandardCharsets.UTF_8)), "HmacSHA256");
    sha256_hmac.init(secret_key);

    String nonce = String.valueOf(System.currentTimeMillis());
    String signature = Base64.encodeBase64String(sha256_hmac.doFinal((PUBLIC_KEY + nonce).getBytes(StandardCharsets.UTF_8)));

    String json = Request.Get(URL).
            addHeader("Accept", "application/json").
            addHeader("X-PCK", PUBLIC_KEY).
            addHeader("X-Stamp", nonce).
            addHeader("X-Signature", signature).
            execute().returnContent().asString();
    System.out.println(json);
}

—————

Exception in thread "main" org.apache.http.client.HttpResponseException: Unauthorized
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
	at org.apache.http.client.fluent.Response.handleResponse(Response.java:90)
	at org.apache.http.client.fluent.Response.returnContent(Response.java:97)
	at TestBTCTurkApi.main(TestBTCTurkApi.java:35)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
