### ISSUE TITLE
XLM/TRY al/sat emri api üzerinden ondalık bölümü 4 haneli olarak verilemiyor!

### ISSUE THREAD

**Issue by digitallartist** [BTCTrader/broker-api-docs#117]
Site üzerinden  ondalık 4 haneli olacak şekilde al/sat emri verilebiliyor
ama Api üzerinden ondalık bölümü 4 haneli olarak yazıldığında işlem gerçekleşmiyor ve herhangi bir hata mesajı alınamıyor!

**Comment by onurgozupek** [comment]
POST değerlerine 'DenominatorPrecision': 4 ekleyip deneyebilir misiniz?
