### ISSUE TITLE
API api/v1/users/transactions dan Unauthorized mesaji alıyorum

### ISSUE THREAD

**Issue by sukru77** [BTCTrader/broker-api-docs#118]
https://api.btcturk.com/api/v1/users/transactions/trade?type=buy&type=sell&symbol=btc&symbol=try&symbol=usdt

bu yeni API nedense hep 401 - Unauthorized mesajı donduruyor. bir turlu sonuc alamıyorum. 

eski api (https://www.btcturk.com/api/) ile sorunsuz bağlanıyorum.

**Comment by onurgozupek** [comment]
Kullanıcı hareketleri sorgusu kimlik doğrulama (authentication) gerektirmektedir. Her işlemlden önce kimlik doğrulaması yaparak deneyebilir misiniz?

**Comment by sukru77** [comment]
Kimlik dogrulama nasil olacak?. Zaten api key kullanarak GET request gonderiyorum.

**Comment by onurgozupek** [comment]
POST sorgusu gönderirken yaptığınız kimlik doğrulaması gibi. Örnek:

            $message = $this->apiKey.time();
            $signatureBytes = hash_hmac('sha256', $message, base64_decode($this->apiSecret), true);
            $signature = base64_encode($signatureBytes);
            $nonce = time();
            $headers = array(
                'X-PCK: '.$this->apiKey,
                'X-Stamp: '.$nonce,
                'X-Signature: '.$signature,
                'Cache-Control: no-cache',
                'Content-Type: application/json',
            );


curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

**Comment by sukru77** [comment]
Aynen o sekilde headers ekliyorum zaten. yazılım java ile ama ayni sekilde calisiyor. ve zaten eski api ile calisiyor sorunsuz.

**Comment by onurgozupek** [comment]
Veriyi gönderirken array olarak mı yoksa jSON olarak mı gönderiyorsunuz?

**Comment by sukru77** [comment]
` String nonce = String.valueOf(System.currentTimeMillis());
        String signature = Base64.encodeBase64String(sha256_hmac.doFinal((url + nonce).getBytes(StandardCharsets.UTF_8)));
        HttpGet httpGet = new HttpGet(url);
        httpGet.addHeader(ACCEPT, "application/json");
        httpGet.addHeader(CONTENT_TYPE, "application/x-www-form-urlencoded");
        httpGet.addHeader("X-PCK", PUBLIC_KEY);
        httpGet.addHeader("X-Stamp", nonce);
        httpGet.addHeader("X-Signature", signature);`

**Comment by sukru77** [comment]
String nonce = String.valueOf(System.currentTimeMillis());
        String signature = Base64.encodeBase64String(sha256_hmac.doFinal((url + nonce).getBytes(StandardCharsets.UTF_8)));
        HttpGet httpGet = new HttpGet(url);
        httpGet.addHeader(ACCEPT, "application/json");
        httpGet.addHeader(CONTENT_TYPE, "application/x-www-form-urlencoded");
        httpGet.addHeader("X-PCK", PUBLIC_KEY);
        httpGet.addHeader("X-Stamp", nonce);
        httpGet.addHeader("X-Signature", signature);

bu sekilde gönderiyorum

**Comment by sukru77** [comment]
Sizin gönderdiğiniz gibi Cache-Control ve Content-Type i da değiştirdim ama farkeden bir şey olmadı.
401 - Unautorized error geliyor.

**Comment by onurgozupek** [comment]
httpGet.addHeader(CONTENT_TYPE, "application/x-www-form-urlencoded");
yerine

 httpGet.addHeader(CONTENT_TYPE, "application/json"); dener misiniz?

Bir de doğrulama gerektiren diğer methodlar (v1/order) çalışıyor mu?

**Comment by sukru77** [comment]
o sekilde değiştirdim olmadı. 
ilk basta "/api/v1/users/balances" calisiyordu sadece. geri kalan api larin hepsinde Unauthorized mesajı geliyordu.

**Comment by sukru77** [comment]
su an denedigim url = "https://api.btcturk.com/api/v1/users/transactions/trade?type=buy&type=sell&symbol=btc&symbol=try&symbol=usdt"

**Comment by sukru77** [comment]
biraz daha detaylı bilgi istersen, gelen cevap şöyle:

JSON: {"success":true,"message":"Unauthorized - Invalid Public key","code":1037}

Failed to send GET request to: https://api.btcturk.com/api/v1/users/transactions/trade?type=buy&type=sell&symbol=btc&symbol=try&symbol=usdt, Code: 401, Reason: Unauthorized, Protocol: HTTP/1.1

**Comment by onurgozupek** [comment]
Sanıyorum, API'de /usertransactions Endpoint'inde bir sorun var. Kontrol ettiriyorum.

**Comment by sukru77** [comment]
https://github.com/BTCTrader/broker-api-docs/blob/master/README-beta.md

bu link deki api lardan sadece "/api/v1/users/balances" düzgün calisiyor. geri kalan butun api lari denedim hepsi ayni hatayı veriyor.

hatta .../api/v1/users/transactions/crypto ve .../api/v1/users/transactions/fiat sizin dokuman da POST olarak yazilmis, onların GET olması lazım.

**Comment by onurgozupek** [comment]
Merhaba, yazılım ekibi ile görüştüm. Şu anki API için Btcturk.com'da oluşturulmuş API erişim yetkileri, API v1 için uygun değilmiş. Önümüzdeki hafta içerisinde bir güncelleme yayınlanacak ve API anahtarlarının yenilenmesi talep edilecek. Yeni API anahtarları ile hem Btcturk.com hem de BtcTurk | PRO için V1'in tüm fonksiyonlarını kullanabileceksiniz.

**Comment by sukru77** [comment]
Hadi bakalım. Heyecanla bekliyoruz.

**Comment by sukru77** [comment]
bir soru daha, 

su an order book okumak icin "https://www.btcturk.com/api/orderbook?pairSymbol=BTCTRY" adresini kullanıyorum. her 100 ms de okumaya calisiyorum. saniyede 10 defa,  ama durmadan rate limit error u aliyorum (The allowed number of requests has been exceeded)

API v2 "https://api.btcturk.com/api/v2/orderbook?pairSymbol=BTCTRY"  dan order book lari ceksem ayni sorunu yasarmiyim? 

hangisinin alt yapısı daha saglam?

**Comment by onurgozupek** [comment]
Merhaba, bu konuya cevap vermeyi atlamışım.

1. BtcTurk | PRO'da API Erişimi sayfası açıldı. https://pro.btcturk.com/hesap-ayarlari/api-erisimi adresinden yeni API için API anahtarı alabilirsiniz.

2. v2 ile sadece doğrulama yapılmadan erişime açık (public) uç noktalarına (ticker, OHLC) ulaşabiliyorsunuz. Diğer tüm işlemleri v1 ile yapabilirsiniz. Ancak v2 için Oauth2 doğrulaması ile mobil uygulamada yapabildiğiniz tüm işlemleri yapabileceksiniz. Oauth2 doğrulama arayüzümüz tamamlandıktan sonra v2'yi geliştiricilere açacağız. O zamana kadar tüm alım satım, bakiye sorgulama işlemlerini v1 ile gerçekleştirebilirsiniz.
