### ISSUE TITLE
https://api.btcturk.com/api/v2/ticker fiyatlar iki hane geliyor

### ISSUE THREAD

**Issue by ocengiz0** [BTCTrader/broker-api-docs#119]
Merhaba,
https://api.btcturk.com/api/v2/ticker API XRP ve XLM USDT market fiyatlari iki hane geliyor.

Duzeltmenizi rica ederim

**Comment by onurgozupek** [comment]
Merhaba, yazılım ekibine bilgi verdim. Bildirim için teşekkür ederiz.

**Comment by onurgozupek** [comment]
Merhaba, konu hakkında yazılım ekibinden aldığım bilgiye göre Ticker'da rakamlar formatlı olarak gelmediği için XRP ve XLM için BTC ve USDT işlem çiftlerinde, noktadan sonraki sıfır rakamları Ticker'a yansımıyormuş. Örneğin, XLM/USDT fiyatı 0.0800 olduğunda Ticker'da 0.08 ya da XRP/USDT fiyatı 0.4500 olduğunda 0.45 olarak görünüyor.

**Comment by ocengiz0** [comment]
Merhaba, bence verilen bilgi dogru degil, ticker ve tahtanin ekran goruntulerini gorebilirsiniz.
XRP icin tickerdan donen data "ask": 0.42
Fakat ilgili satis fiyati 0.4230
<img width="1079" alt="Screenshot 2019-05-21 at 11 21 43" src="https://user-images.githubusercontent.com/27735895/58079986-f2412580-7bba-11e9-9c25-489097b2be7b.png">
<img width="391" alt="Screenshot 2019-05-21 at 11 21 25" src="https://user-images.githubusercontent.com/27735895/58079988-f2412580-7bba-11e9-83bf-28b4835ecb16.png">

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
