### ISSUE TITLE
Python authentication 

### ISSUE THREAD

**Issue by emir350z** [BTCTrader/broker-api-docs#12]
I get authentication error 401 - Unauthorized:  Invalid Request. I have tried to translate the codes to python. Can you guys spot what I am missing?

```
    def returnBalances(self):

        headers = {
            "X-PCK": self.APIKey ,
            "X-Stamp": str(int(time.time())) ,
            "X-Signature": str(self.authSignature)
        }

        try:
            ret = urllib2.urlopen(urllib2.Request('https://www.btcturk.com/api/balance', headers=headers))
        except urllib2.HTTPError as e:
            print e.code
            print e.read()
        return  json.loads(ret.read())

    def authSignature(self):
        unixTime = int(time.time())
        data = self.APIKey + str(unixTime)

        return base64.b64encode(hmac(base64.b64decode(self.Secret), data, hashlib.sha256).digest().encode('base64')[:-1])
```

**Comment by emir350z** [comment]
Fuck me, this line should have been
```
"X-Signature": str(self.authSignature)

"X-Signature": str(self.authSignature())  
```
I'm not deleting the issue, maybe someone trying to use the API via python can use it.

**Comment by oxanero** [comment]
I'm getting this error **<    
self.inner.update(msg)
TypeError: Unicode-objects must be encoded before hashing>**
in line 
**<   lv_signature = hmac.new(base64.b64decode(self.private_key), data, hashlib.sha256)>**
for the below code:
   **def authSignature(self):
        unixTime = int(time.time())
        data = str(self.api_key + str(unixTime))
        lv_signature = hmac.new(base64.b64decode(self.private_key), data, hashlib.sha256)
        signature = base64.b64encode(lv_signature.digest().encode('base64')[:-1])
        return signature**
Could you please help me to solve this issue :(
