### ISSUE TITLE
506 Please try again later

### ISSUE THREAD

**Issue by emrahtopcu** [BTCTrader/broker-api-docs#120]
Merhaba, dün gece 23 den beri tüm isteklere bu hatayı dönüyor.
Ayrıca 'https://www.btcturk.com/api/Balance' bu endpoint'e istek gönderince bir hata oluşmuştur diye garip bir hata alıyorum, url'yi chroma yazıp enter'e basınca birkaç saniye sonra beni sitenin advanced alım satım sayfasına yönlendiriyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
