### ISSUE TITLE
Balance dan dönen try_available yanlış bakiye dönüyor.

### ISSUE THREAD

**Issue by emrahtopcu** [BTCTrader/broker-api-docs#127]
Balance ile çektiğim bakiye bilgisinde try_available 10.95 tl fazla gösteriyor, emir giremiyorum.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
