### ISSUE TITLE
503 hatasi

### ISSUE THREAD

**Issue by welett** [BTCTrader/broker-api-docs#129]
Merhaba,

Dunden beri tum API calllar 503 hatasi donuyor. Yaklasik bir yildir calisiyordu bunlar.
Browser uzerinden order book sorunsuz calisiyor ama.

Bir problem mi var?

**Comment by welett** [comment]
Bununla ilgili: API call'lara once bir HTML donuyor gibi gorunuyor sizin server. Nasil cozebiliriz?

**Comment by onurgozupek** [comment]
Merhaba, sunucunuz yurtdışında ya da normalde fazla istek gönderiyor olabilir mi?

**Comment by welett** [comment]
Merhaba,

Sunucu yurt disinda evet. Her 10 saniyede 10 istek civari yolluyor

**Comment by onurgozupek** [comment]
destek@btcturk.com adresine sunucunuzun IP adresini gönderebilir misiniz? Kontrol edelim.

**Comment by welett** [comment]
Yolladim, tesekkurler. Bu arada hazir kontrol edecekseniz, bazi API istekleri her 2-3 istekte bir HTML donuyor ilk calismaya basladigindan beri.

**Comment by onurgozupek** [comment]
Tamam kontrol edelim. Ayrıca https://api.btcturk.com/api/ adresini kullanıyor musunuz? Eğer kullanmıyorsanız, daha hızlı, yeni komutlarla desteklenen yeni API’ı kullanmanızı tavsiye ederiz. Dokümanı: https://github.com/BTCTrader/broker-api-docs/blob/master/README-beta.md

**Comment by welett** [comment]
Tesekkurler, yeni API'den haberim yoktu, bakalim. Bu arada withdraw da eklerseniz bir ara super olur -)
