### ISSUE TITLE
INTERNAL_ERROR hatası

### ISSUE THREAD

**Issue by progahmet** [BTCTrader/broker-api-docs#130]
Merhaba,
beta olan apideki servis sürekli hata veriyor;
https://api.btcturk.com/api/v2/ticker/currency?symbol=USDT

Sebebi ne olabilir acaba, hata:

success | false
message | "INTERNAL_ERROR"
code | 500

**Comment by onurgozupek** [comment]
Hata düzeltildi. Tekrar deneyebilir misiniz?

**Comment by progahmet** [comment]
Teşekkür ederim, düzelmiş.
