### ISSUE TITLE
Emir girilemedi. Lütfen tekrar deneyiniz ve hata tekrar ederse bize ulaşınız.

### ISSUE THREAD

**Issue by progahmet** [BTCTrader/broker-api-docs#131]
Merhaba, 

api üzerinden al satlarda aşağıdaki şekilde hata alıyorum. 3 kere denedim aynı.

{"error":{"code":500,"message":"Emir girilemedi. Lütfen tekrar deneyiniz ve hata tekrar ederse bize ulaşınız."}}

Bu sorun ne zaman olur, bu sorun olunca ne yapmak gerekir? Sorunun sebebi nedir,

**Comment by onurgozupek** [comment]
Merhaba, biraz detaylı bilgi alabilir miyiz? Emir isteğini nasıl gönderdiniz? Daha önce başarılı emir girişi yapmış mıydınız? Hangi API adresini kullanıyorsunuz.

**Comment by progahmet** [comment]
https://www.btcturk.com/api/exchange
Evet daha önceden al emirleri yaptım, daha önceden bazı hatalar alıyordum ama onlarda genelde bakiye yanlış, limit yok gibi uyarılar veriyordu. Bunda ise direk hata oluştu devam ederse bize ulaşın yazdığı için yazdım size. Bir hesaplama hatası yok. 

İstek parametreleri ektedir.

![istek](https://user-images.githubusercontent.com/52503087/61169327-9369ae00-a564-11e9-8827-d2687f2f8f2e.jpg)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
