### ISSUE TITLE
Cancel Order

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#132]
Kaldırdığım emrin verilerini gösteren bir servis var mı?

https://www.btcturk.com/api/cancelOrder bu servisi kullanıyorum.

https://api.btcturk.com/api/v1/order bu servis çalışıyor mu ? verileri gösteriyor mu ?
DELETE .../api/v1/order?id=1
Params:
id: order ID
Result:
{
  "success": true,
  "message": "string",
  "code": "",
  "data": {
  }
}

**Comment by BTCTraderAdmin** [comment]
Merhaba, 

https://api.btcturk.com/api/v1/order endpoint POST, DELETE taleplerinize cevap vermektedir. POST yeni emir girişi, DELETE ise mevcut emrinizi iptal etmek için kullanılmaktadır. Anladığım kadarı ile siz iptal etmiş olduğunuz emirleri görmek istiyorsunuz. 

https://api.btcturk.com/api/v1/openOrders endpoint adresi ile tüm açık emirlerinizi görebilirken, 

https://api-pro.btcturk.com/api/v2/allOrders?pairSymbol=BTCTRY endpoint adresi size aşağıdaki gibi bir model dönecektir. Burada pairSymbol parametleri gönderimi gerekmektedir. Buradan status karşılığındaki Canceled iptal etilmiş emrinizdir.
Ek olarak type değeri sell veya buy olmakta, emrininiz yönünü belirtmektedir.

{
      "id": 111111,
      "price": "73159.00",
      "amount": "0.15",
      "quantity": "0.15",
      "stopPrice": "0",
      "pairSymbol": "BTCTRY",
      "pairSymbolNormalized": "BTC_TRY",
      "type": "sell",
      "method": "limit",
      "orderClientId": "1111111",
      "time": 1562793070477,
      "updateTime": 1562796398823,
      "**status**": "**Canceled**",
      "leftAmount": "0.1500000000000000"
}

Umarım faydalı olur. Kolay gelsin.

**Comment by akrepfatih** [comment]
Yapmak istediğim, emri kaldırırken id , adet ve fiyatın bana geri dönmesi ( id ve fiyatı zaten biliyoruz ama kalan adedi bilmediğimizden dolayı varlıklarımız tekrar kontrol etmek durumunda kalıyoruz.)
Örneğin :
Alış emri giriyoruz xcoin fiyat = 20 000 adet = 10
bu emirden 3 tanesini sattığımızda emri kaldırırken kalan adedi bilmediğimizden xcoin den kaç tane aldık ve paramızın ne kadarı geri geldiğini bilemiyoruz.
Bu durumda ya varlıklarımızı kontrol ederek ya da emir geçmişimizi kontrol ederek yeni emir girmek durumunda kalıyoruz.
Halbuki mantıklı olan
Alış emri gir 20 000 * 10 = 200 000 kasadan düş
Emri kaldır dönen veri id = 123456789 fiyat = 20 000 adet = 7
7 * 20 000 = 140 000 kasaya ekle
10 - 7 = 3 xcoin ekle
Yapmak istediğim tam olarak bu. Umarım şimdi anlatabilmişimdir.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
