### ISSUE TITLE
Wallet guncellenmiyor

### ISSUE THREAD

**Issue by afaslan** [BTCTrader/broker-api-docs#133]
27 Temmuz 2019 tarihinden itibaren bir wallet hatasi mevcut. Soyle ki:

Api ile bir alim ya da satim islemi yaptiktan sonra wallet'e bazen sonuc yansimiyor ya da parcali yansiyor. 

Ornegin: 1000 USDt aldim hesabimdan 5600 TRY civarinda TRY eksiliyor ve eklenmesi gereken 1000 USDt eklenmiyor. Aradan 7-8 saat gectikten sonra durum kendiliginden duzeliyor. Yani yapilan trade islemi yarim olarak wallet'e yansiyor. Bu durum o zaman diliminde sanki 1000 USDt kaybedilmis ve yok olmus izlenimi veriyor. 

Cozum: Her islemden sonra beklenildigi gibi wallet tam olarak guncellenirse ve site ile ayni olursa sorun cozulecektir. 

Bu durum 27 Temmuz 2019 tarihinden once olmuyordu.

**Comment by onurgozupek** [comment]
Normalde API tarafında, emir gerçekleştikten sonra tekrar bakiye sorgulaması yaptığınızda, bakiyeniz anlık olarak güncellenir. Gönderdiğiniz her sorguda, API güncel veriler ile cevap verir. Ancak sistem güncellemesine denk gelmiş ya da API ile ilgili bir erişim problemi yaşamış olabilirsiniz.

Bu nedenle konuyla ilgili biraz daha detaylı bilgi alabilir miyiz?

* Hangi API ile işlem yapıyorsunuz? (btcturk.com/api ya da api.btcturk.com/api)
* Sorunla ne zaman karşılaştınız? (Belirli bir zaman dilimi var mı?)
* Problem halen devam ediyor mu?

**Comment by afaslan** [comment]
Bu durum sitede de oluyor. Bakiye sitede de guncellenmedigi oluyor. Genel yapida bakiyenin bazen 1 saati askin sure guncellenmedigi oluyor. 
Dolayisiyla API sorunu olmadigini anliyorum. Bu yuzden bu istegi kapatiyorum. 
Tesekkurler.
