### ISSUE TITLE
https://api.btcturk.com/ (Requires Authentication) hepsi hata veriyor.

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#134]
Hata kodunu aşağıda paylaşıyorum.
{"success":true,"message":"Unauthorized - Invalid Nonce","code":1037}

**Comment by onurgozupek** [comment]
Üyelik işlemleri için her sorgudan önce API KEY ve API SECRET bilgileri ile doğrulama yapmanız gerekiyor. Sorgu yaparken, bir önceki sorgunun NONCE değerinden farklı (tercihen her sorguda artan) bir değer göndermelisiniz. Ayrıca, API için sorgu limitlerini aşmadığınızdan da emin olun.

**Comment by akrepfatih** [comment]
Kod da hata olduğunu sanmıyorum. İsterseniz birde siz bakın.
public void m_btcturk_varliklarim()
{
string s_btcturk_varliklarimsonuc = m_btcturk_varliklarim_istek("api/v1/users/balances");
Debug.WriteLine("Sonuç : " + s_btcturk_varliklarimsonuc);
}

public string m_btcturk_varliklarim_istek(string adres)
{
string sonuc;
using (var client = new HttpClient())
{
var unixTimestamp = DateTime.UtcNow.Ticks;
string message = AnaForm.s_apipublic + unixTimestamp;
using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(AnaForm.s_apiprivate)))
{
byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
string signature = Convert.ToBase64String(signatureBytes);
client.DefaultRequestHeaders.Add("X-PCK", AnaForm.s_apipublic);
client.DefaultRequestHeaders.Add("X-Stamp", unixTimestamp.ToString());
client.DefaultRequestHeaders.Add("X-Signature", signature);
client.BaseAddress = new Uri("https://api.btcturk.com/");
}
using (var sorgu = client.GetAsync(adres))
{
sonuc = sorgu.Result.Content.ReadAsStringAsync().Result;
}
}
return sonuc;
}

**Comment by onurgozupek** [comment]
Kontrol için Ticker'daki Timestamp ile sunucunuzdaki Timestamp'i karşılaştırabilir misiniz? https://api.btcturk.com/api/v2/ticker?symbol=BTCTRY (Değerleri https://www.epochconverter.com adresinden saat:dakika:saniyeye çevirebilirsiniz)

Ayrıca, API 13 haneli Timestamp kullanıyor. Kodunuzdaki Timestamp'in 13 haneli olduğundan da emin olun. (Değilse 1000 ile çarpabilirsiniz)

Eğer bunları kontrol ettikten sonra yine aynı hatayı alıyorsanız, yeni bir API Key ve API Secret üreterek yeni bilgiler ile deneme yapabilir misiniz? Yine sonuç alamazsanız, destek@btcturk.com adresine sistemde kayıtlı e-posta adresinizden "API Nonce hatası" konulu bir e-posta gönderebilirseniz, kontrol sağlayabiliriz.

**Comment by akrepfatih** [comment]
13 haneye çıkardıktan sonra sorun çözüldü.
Çalışan kodu aşağıda veriyorum
TimeSpan t = (DateTime.UtcNow - new DateTime(1970, 1, 1));
long unixTimestamp = (long)t.TotalMilliseconds;
