### ISSUE TITLE
test.btcturk.com kayıt onay maili gelmiyor

### ISSUE THREAD

**Issue by valamorgon** [BTCTrader/broker-api-docs#135]
test.btcturk.com kayıt onay maili gelmiyor, canlı destek ekibiniz beni github'a yönlendirdi. Yardımcı olur musunuz?

**Comment by onurgozupek** [comment]
Merhaba, bu adresi ne amaçla kullanmak istiyorsunuz? BtcTurk'ü denemek için mi üyelik oluşturmaya çalışıyorsunuz?

**Comment by valamorgon** [comment]
Merhaba, api denemeleri yapmak istiyorum. Entegrasyonum tamamlanana kadar kullanmayı planlıyorum.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
