### ISSUE TITLE
API isteklerinde Invalid Signature hatası

### ISSUE THREAD

**Issue by necmicolak** [BTCTrader/broker-api-docs#136]
Örnek olarak 8 değeri döngüye sokuyorum her döngü sonuna 0.01 saniye bekleme süresi koyuyorum mesela ilk 4 döngü çalışıyor ancak son 4 döngüde Invalid signature hatası geliyor. 
Yada 6 tanesi  çalışıyor 7.cisinde hata 8.si çalışıyor.

Bu hatalar dışında işlem geçmişinde de trade idsi hep aynı çıkıyor gerçek trade idsi görünmüyor.

**Comment by onurgozupek** [comment]
Merhaba hangi API uç noktasını kullanıyorsunuz ( btcturk.com/api ya da api.btcturk.com/api/v1 )

İmza hataları genelde zaman farkından kaynaklanıyor. Her sorgudan önce kimlik doğruma yapmak gerekiyor ve bunu yapabilmek için sunucunuzun zaman damgası (timestamp) ile API sunucusunun zaman damgası birbirine yakın olmak zorunda.

API'da 13 karakterli zaman damgası kullanıyoruz. Zaman damganızın 10 mu 13 karakter mi olduğunu kontrol edebilir misiniz? (10 karakterse 1000 ile çarparak 13 karaktere çıkartabilirsiniz.)

Zaman damgasını ve her sorgudan önce kimlik doğrulaması yapıp yapmadığınızı kontrol ettikten sonra deneyebilir misiniz?

**Comment by necmicolak** [comment]
> Merhaba hangi API uç noktasını kullanıyorsunuz ( btcturk.com/api ya da api.btcturk.com/api/v1 )
> 
> İmza hataları genelde zaman farkından kaynaklanıyor. Her sorgudan önce kimlik doğruma yapmak gerekiyor ve bunu yapabilmek için sunucunuzun zaman damgası (timestamp) ile API sunucusunun zaman damgası birbirine yakın olmak zorunda.
> 
> API'da 13 karakterli zaman damgası kullanıyoruz. Zaman damganızın 10 mu 13 karakter mi olduğunu kontrol edebilir misiniz? (10 karakterse 1000 ile çarparak 13 karaktere çıkartabilirsiniz.)
> 
> Zaman damgasını ve her sorgudan önce kimlik doğrulaması yapıp yapmadığınızı kontrol ettikten sonra deneyebilir misiniz?

API için dediğiniz yöntemi deneyeceğim.
Ancak daha büyük bir problem olan User Transactions kısmı sürekli aynı idyi döndürüyor. Normalde trade idsi olması gerekmiyor mu ?

**Comment by onurgozupek** [comment]
Gerçekleşen emirlerinizi siteden kontrol ettiniz mi? Aynı tarih aralığında kaç emir görünüyor? API sorgusundan kaç emir dönüyor? btcturk.com/api kullanıyorsanız OFFSET ve LIMIT değerlerini kontrol edin. Güncel liste için OFFSET 0 (sıfır), LIMIT 1'den büyük olmalı. 

api.btcturk.com/api kullanıyorsanız type ve symbol girdiğinizden emin olun. startDate girmezseniz, son 30 günlük işlem dökümünü alırsınız. (Kontrol etmek için endDate'i 1 gün artırarak girmeyi deneyin)

**Comment by necmicolak** [comment]
> Gerçekleşen emirlerinizi siteden kontrol ettiniz mi? Aynı tarih aralığında kaç emir görünüyor? API sorgusundan kaç emir dönüyor? btcturk.com/api kullanıyorsanız OFFSET ve LIMIT değerlerini kontrol edin. Güncel liste için OFFSET 0 (sıfır), LIMIT 1'den büyük olmalı.
> 
> api.btcturk.com/api kullanıyorsanız type ve symbol girdiğinizden emin olun. startDate girmezseniz, son 30 günlük işlem dökümünü alırsınız. (Kontrol etmek için endDate'i 1 gün artırarak girmeyi deneyin)
Bahsetmek istediğim kısım şu aslında :

```
[
  {
    "id":"123456",
    "date":"2015-08-11T11:40:17.278",
    "operation":"buy",
    "amount":1.9449023,
    "currency":"TRY",
    "price":734.52,
	"funds":10,
	"fee" : 0.005,
	"tax" : 0.18
  },
  {
    "id":"123456",
    "date":"2015-08-11T11:40:17.325",
    "operation":"commission",
    "amount":0.0,
    "currency":"TRY",
    "price":0.0,
	"funds":10,
	"fee" : 0.005,
	"tax" : 0.18
  },
  {
    "id":"123456",
    "date":"2015-08-11T11:44:10.162",
    "operation":"sell",
    "amount":-2.18674928,
    "currency":"BTC",
    "price":737.71,
	"funds":10,
	"fee" : 0.005,
	"tax" : 0.18
  },
  {
    "id":"123456",
    "date":"2015-08-11T11:44:10.209",
    "operation":"commission",
    "amount":0.0,
    "currency":"BTC",
    "price":0.0,
	"funds":10,
	"fee" : 0.005,
	"tax" : 0.18
  }
]

bu örnek çıktıdaki "id" kısmında hep aynı değer mevcut noramlde bu kısımda gerçekleşen işlemin idsini döndürmesi gerekmiyor mu?
```

**Comment by onurgozupek** [comment]
O "örnek" çıktı olduğu için ID'ler gerçek değerleri yansıtmıyor. Siz kimlik doğrulama yaptıktan sonra sorgu gönderdiğinizde, hesabınıza ait işlem dökümünü alabilirsiniz. (Bu arada, hangi API'ı kullandığınız belirtirseniz daha detaylı bilgi verebilirim)

**Comment by necmicolak** [comment]
> O "örnek" çıktı olduğu için ID'ler gerçek değerleri yansıtmıyor. Siz kimlik doğrulama yaptıktan sonra sorgu gönderdiğinizde, hesabınıza ait işlem dökümünü alabilirsiniz. (Bu arada, hangi API'ı kullandığınız belirtirseniz daha detaylı bilgi verebilirim)

`Array
(
    [0] => Array
        (
            [id] => 59946
            [date] => 2019-08-09T15:40:06.933
            [operation] => withdrawal
            [currency] => TRY
            [funds] => 2197.1108132878
            [amount] => -6035.14
            [fee] => -3
            [tax] => -0.54
            [price] => 0
        )

    [1] => Array
        (
            [id] => 59946
            [date] => 2019-08-09T15:32:25.523
            [operation] => trade
            [currency] => XRP
            [funds] => 8235.7908132878
            [amount] => -3657.6622
            [fee] => -12.786318722194
            [tax] => -2.3015373699949
            [price] => 1.65
        )

    [2] => Array
        (
            [id] => 59946
            [date] => 2019-08-09T15:31:25.487
            [operation] => deposit
            [currency] => XRP
            [funds] => 3919.412282
            [amount] => 3657.662183
            [fee] => 0
            [tax] => 0
            [price] => 0
        )

    [3] => Array
        (
            [id] => 59946
            [date] => 2019-08-09T09:06:05.493
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => 0.00233686
            [fee] => -0.059174046242024
            [tax] => -0.010651328323564
            [price] => 11952
        )

    [4] => Array
        (
            [id] => 59946
            [date] => 2019-08-08T20:49:40.02
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.00120991
            [fee] => -0.029735075319664
            [tax] => -0.0053523135575395
            [price] => 11600
        )

    [5] => Array
        (
            [id] => 59946
            [date] => 2019-08-08T14:22:49.057
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.000624
            [fee] => -0.009475806884544
            [tax] => -0.0017056452392179
            [price] => 11946
        )

    [6] => Array
        (
            [id] => 59946
            [date] => 2019-08-08T14:22:49.057
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.00052
            [fee] => -0.00785750575064
            [tax] => -0.0014143510351152
            [price] => 11887
        )

    [7] => Array
        (
            [id] => 59946
            [date] => 2019-08-08T07:40:50.037
            [operation] => trade
            [currency] => BTC
            [funds] => 2215.7360393799
            [amount] => -0.00046031
            [fee] => -0.063719775037238
            [tax] => -0.011469559506703
            [price] => 65338
        )

    [8] => Array
        (
            [id] => 59946
            [date] => 2019-08-08T07:40:01.317
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.00687923
            [fee] => -0.17203904305407
            [tax] => -0.030967027749733
            [price] => 11804
        )

    [9] => Array
        (
            [id] => 59946
            [date] => 2019-08-08T01:22:29.437
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => 0.00052
            [fee] => -0.01321923686512
            [tax] => -0.0023794626357216
            [price] => 11999
        )

    [10] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T17:24:09.76
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.00052
            [fee] => -0.00799301417824
            [tax] => -0.0014387425520832
            [price] => 12092
        )

    [11] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T17:19:35.717
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => 0.00052
            [fee] => -0.007965251476
            [tax] => -0.00143374526568
            [price] => 12050
        )

    [12] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T17:19:35.717
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => 0.000624
            [fee] => -0.0095583017712
            [tax] => -0.001720494318816
            [price] => 12050
        )

    [13] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T17:05:32.52
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.000208
            [fee] => -0.005310609999552
            [tax] => -0.0009559097999194
            [price] => 12051
        )

    [14] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T17:05:32.203
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.00052
            [fee] => -0.01327652499888
            [tax] => -0.0023897744997984
            [price] => 12051
        )

    [15] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T17:05:32.203
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.000312
            [fee] => -0.007965914999328
            [tax] => -0.001433864699879
            [price] => 12051
        )

    [16] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T17:05:31.513
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => 0.00052
            [fee] => -0.0133525419456
            [tax] => -0.002403457550208
            [price] => 12120
        )

    [17] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T16:56:10.68
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => 0.00052
            [fee] => -0.00799764129528
            [tax] => -0.0014395754331504
            [price] => 12099
        )

    [18] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T16:53:03.167
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => 0.000624
            [fee] => -0.01601644016544
            [tax] => -0.0028829592297792
            [price] => 12115
        )

    [19] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T16:37:37.527
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.000312
            [fee] => -0.0079983048288
            [tax] => -0.001439694869184
            [price] => 12100
        )

    [20] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T16:37:37.527
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.000208
            [fee] => -0.0053322032192
            [tax] => -0.000959796579456
            [price] => 12100
        )

    [21] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T16:37:36.98
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.00052
            [fee] => -0.013330508048
            [tax] => -0.00239949144864
            [price] => 12100
        )

    [22] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T16:37:36.98
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => -0.000416
            [fee] => -0.0106644064384
            [tax] => -0.001919593158912
            [price] => 12100
        )

    [23] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T16:36:48.027
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => 0.000728
            [fee] => -0.018692016351008
            [tax] => -0.0033645629431814
            [price] => 12119
        )

    [24] => Array
        (
            [id] => 59946
            [date] => 2019-08-07T16:36:47.353
            [operation] => trade
            [currency] => BTC
            [funds] => 0
            [amount] => 0.00052
            [fee] => -0.01335144025072
            [tax] => -0.0024032592451296
            [price] => 12119
        )

)`

bu şekilde tüm idler aynı çıktı veriyor. bu kullanıcının çıktısı

**Comment by onurgozupek** [comment]
https://github.com/BTCTrader/broker-api-docs/blob/master/README-beta.md adresindeki dokümanı kullanarak https://api.btcturk.com/api/ adresini kullanarak denemeniz mümkün mü?

**Comment by necmicolak** [comment]
> https://github.com/BTCTrader/broker-api-docs/blob/master/README-beta.md adresindeki dokümanı kullanarak https://api.btcturk.com/api/ adresini kullanarak denemeniz mümkün mü?

https://api.btcturk.com/api/users/transactions/trade - BOS sayfa geliyor
https://api.btcturk.com/api/v2/users/transactions/trade - BOS sayfa geliyor
https://api.btcturk.com/api/v1/users/transactions/trade  - Bu kisimda geliyor ancak hata mesajı geliyor
Hata mesajı 
`Array
(
    [success] => 1
    [message] => Unauthorized - Invalid Request
    [code] => 1037
)
`

bu şekilde oluyor
(Not : Parametreleri giriyorum ancak genede aynı. Parametresiz yazma sebebim daha temiz görünsün diye)

İlginiz için teşekkür ederim.

**Comment by onurgozupek** [comment]
Merhaba, talebiniz üzerine hesabınız kontrol edilerek tarafınıza bildirim yapılmıştır.
