### ISSUE TITLE
V1 ile uyumlu yeni Api Anahtarları

### ISSUE THREAD

**Issue by burakgezer** [BTCTrader/broker-api-docs#137]
Merhaba,

https://github.com/BTCTrader/broker-api-docs/issues/118#issuecomment-493478676

Bahsedilen yeni api anahtarlarını ne zaman alabileceğiz ?

**Comment by onurgozupek** [comment]
Merhaba, BtcTurk | PRO üzerinden v1 ve v2 uyumlu API anahtarı oluşturmak için çalışmalar devam ediyor. Yakında, BtcTurk | PRO hesabınızdan farklı izin (bakiye sorgula, emir sorgula, emir gir, kriptopara yatır, çek vb.) seçenekleriyle API anahtarı oluşturabileceksiniz.

**Comment by BTCTraderAdmin** [comment]
Merhaba,

Eski siteden(btcturk.com) üzerinden aldığınız anahtarları yeni api için de
kullanabilirsiniz. Yalnızca pro.btcturk.com sitesinde api anahtarı
oluşturmak için yeni menu yapmadık. Yakında o da gelecek ancak dediğim gibi
btcturk.com ile oluşturduğunuz api anahtarınızı yeni pro api ile birlikte
kullanabilirsiniz. Sorun yaşarsanız lütfen müşteri hizmetlerimize ulaşın.

**Comment by m4rked0ne** [comment]
V1 private sorguları balance sorgusu dışında hala çalışmıyor. Az önce yeni bir tane oluşturup bir kez daha denedim. V2 public sorgularda problem yaşamadım hiç.
Dönen cevap:
'{"success":true,"message":"Unauthorized - Invalid Public key","code":1037}'

**Comment by onurgozupek** [comment]
Merhaba, sistemde kayıtlı e-posta hesabınızdan destek@btcturk.com adresine API anahtarıyla ilgili bir e-posta gönderebilir misiniz? Hesabınızı ve API anahtarınızın yetkilerini kontrol edelim.

**Comment by onurgozupek** [comment]
> V1 private sorguları balance sorgusu dışında hala çalışmıyor. Az önce yeni bir tane oluşturup bir kez daha denedim. V2 public sorgularda problem yaşamadım hiç.
> Dönen cevap:
> '{"success":true,"message":"Unauthorized - Invalid Public key","code":1037}'

Merhaba, sorun hala devam ediyor mu? Destek ekibiyle iletişime geçmiş miydiniz?

**Comment by m4rked0ne** [comment]
Merhaba, destek ekibi hesabimda guncelleme yapti ve cozuldu.

**Comment by saimgokkoyun** [comment]
eski ve yeni siteden oluşturduğum API anahtarları ile yaptığım sorgular;

{'success': True, 'message': 'Unauthorized - Invalid Request', 'code': 1037}

yanıtını dönüyor, yardımcı olabilir misiniz?

**Comment by onurgozupek** [comment]
Muhtemelen authentication bilgisini göndermiyorsunuz. Şu konuya bakabilir misiniz? 

https://github.com/BTCTrader/broker-api-docs/issues/178#issuecomment-593089973

**Comment by yusufmendes** [comment]
Wireshark ile giden tcp paketlerine bakıyorum ve request header kısmında authentication bilgilerini görüyorum.Timestampi kasıtlı bir şekilde yanlış gönderdiğimde invalid nonce hatası alıyorum,yani authentication bilgileri sizin api servisine gönderiliyor

**Comment by yusufmendes** [comment]
#178 (comment) daki kodun birebir aynısını çalıştırıyorum ve aynı hatayı alıyorum

**Comment by onurgozupek** [comment]
https://github.com/BTCTrader/broker-api-docs/issues/193#issuecomment-607776740 API anahtarınızı yeniden almayı deneyin

**Comment by yusufmendes** [comment]
IP anahtarını(0.0.0.0) sildim ve hata düzeldi.Teşekkür ederim.Fakat şu an ip filtresi olmadığı için güvenlik sıkıntısı oluşma ihtimali var.IP kısmına 0.0.0.0 değil de kendi IP adresimi eklemeye çalıştığımda da invalid IP hatası verdi sistem.Ama şimdilik yoluma böyle devam ediyorum,kolay gelsin
