### ISSUE TITLE
C# https://www.btcturk.com/api/exchange XLMTRY

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#138]
Fiyat olarak girdiğim değer 0.3822 emir noktadan sonra 4 hane olarak giriliyor siteden baktığımda emirlerimin fiyatı normal.
Fakat sizden dönen sonuç noktadan sonra 2 hane olarak dönüyor.

{"id":"62986824","datetime":"2019-08-21T23:59:35.1531988Z","type":"Buy","price":0.38,"amount":7000.0,"pairsymbol":null}

string s_emirgir_sonuc = m_btcturk_emrigir("api/exchange", "XLMTRY", "4", "0", s_a1_t, s_a1_k, s_f1_t, s_f1_k);//0 al 1 sat

string f = s_emirgir_sonuc;
m_yazilar("\\btcturk_xlm_alis_1.txt", f);

        public string m_btcturk_emrigir(string adres, string symbol, string precision, string alsat, string adett, string adetk, string fiyatt, string fiyatk)
        {
            string sonuc;

            using (var client = new HttpClient())
            {
                var unixTimestamp = DateTime.UtcNow.Ticks;
                string message = AnaForm.s_apipublic + unixTimestamp;
                using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(AnaForm.s_apiprivate)))
                {
                    byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
                    string signature = Convert.ToBase64String(signatureBytes);
                    client.DefaultRequestHeaders.Add("X-PCK", AnaForm.s_apipublic);
                    client.DefaultRequestHeaders.Add("X-Stamp", unixTimestamp.ToString());
                    client.DefaultRequestHeaders.Add("X-Signature", signature);
                    client.BaseAddress = new Uri("https://www.btcturk.com/");
                }

                IEnumerable<KeyValuePair<string, string>> sorulacaklar = new List<KeyValuePair<string, string>>()
                {
                    new KeyValuePair<string, string>("totalPrecision", "60"),
                    new KeyValuePair<string, string>("amount", adett),
                    new KeyValuePair<string, string>("amountPrecision", adetk),
                    new KeyValuePair<string, string>("price", fiyatt),
                    new KeyValuePair<string, string>("pricePrecision", fiyatk),
                    new KeyValuePair<string, string>("orderMethod", "0"),
                    new KeyValuePair<string, string>("orderType", alsat),/* 0 Alış 1 Satış */
                    new KeyValuePair<string, string>("triggerPrice", "0"),
                    new KeyValuePair<string, string>("triggerPricePrecision", "00"),
                    new KeyValuePair<string, string>("DenominatorPrecision", precision),
                    new KeyValuePair<string, string>("PairSymbol", symbol),
                };
                HttpContent sorgu = new FormUrlEncodedContent(sorulacaklar);

                using (var response = client.PostAsync(adres, sorgu))
                {
                    sonuc = response.Result.Content.ReadAsStringAsync().Result;
                }
            }
            return sonuc;
        }

**Comment by onurgozupek** [comment]
Merhaba, API'dan dönen çıktıda XLMTRY işlem çifti için küsürat hanesi 2 basamak görünüyor. Ancak işlemler, sorgunuzdaki gibi 4 haneli fiyat üzerinden gerçekleşiyor. (Hesap dökümünüzden kontrol edebilirsiniz) Yazılım ekibi API'da gerekli düzeltmeyi yaptı. Yayınlanacak ilk sürümde hata düzeltilecek. Bilgilerinize.

**Comment by akrepfatih** [comment]
Sorun sadece API de de değil https://www.btcturk.com hesap hareketlerinden baktığımda da aynı sorun var. Fakat https://pro.btcturk.com dan baktığımda sorun yok.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
