### ISSUE TITLE
Trades endpoint - Buy or Sell?

### ISSUE THREAD

**Issue by blckx** [BTCTrader/broker-api-docs#139]
How can I understand if a trade record is buy or sell?
Endpoint: https://www.btcturk.com/api/trades?pairSymbol=BTCTRY

**Comment by BTCTraderAdmin** [comment]
Please use api.btcturk.com for your requests.
Endpoint: https://api.btcturk.com/api/v2/trades?pairSymbol=BTCTRY
You will find the side buy/sell.
