### ISSUE TITLE
Withdraw

### ISSUE THREAD

**Issue by alikopasa** [BTCTrader/broker-api-docs#141]
Merhabalar,

Withdraw requesti için örnek gönderebilirmisiniz rica etsem?

iyi çalışmalar

**Comment by onurgozupek** [comment]
Merhaba, API V1 için Withdraw desteklenmiyor. V2 için ise OAuth2 ile geçici token alınması gerekiyor. Bu entegrasyon henüz kullanıcıların erişimine açılmadı. API V2 için Withdraw kullanıcıların erişimine açıldığında size ayrıca bilgilendirme yapalım.

**Comment by iamsasan** [comment]
Hi @onurgozupek 
Is it possible to tell when it is accessible ? It's really useful.
Thanks for considering my request.

**Comment by yusufmendes** [comment]
@onurgozupek  @BTCTraderAdmin  merhabalar withdraw api konusunda bir gelişme varmı acaba.Kullanıcı taleplerine ve bu apiyle ilgili açılan issue lara baktığımda yaklaşık 3 4 yıldır bu talep askıda bekliyor gibi.Piyasadaki top 10 exhange sitelerinin hepsi bu apiyi kullanıcılara sağlıyprken BTCTurk gibi türkiyenin en yüksek hacimli exchange firmasının halen bu yeteneğinin olmaması açıkçası çok üzücü.
Kolay gelsin

**Comment by serensoner** [comment]
Merhabalar @onurgozupek , bu konuyla ilgili guncel bir bilgilendirme yapar misiniz acaba?

**Comment by onurgozupek** [comment]
Destek ekibine ulaşabilir misiniz? Henüz genel erişime açılmadı anak talep eden kullanıcılar için withdraw yetkisi verilebiliyor.
