### ISSUE TITLE
yeni APIde balance sorgusunda invalid nonce mesaji

### ISSUE THREAD

**Issue by welett** [BTCTrader/broker-api-docs#142]
Merhaba,

Eski APIde balance sorgusu sorunsuz calisirken yeni APIden (yalnizca URLyi degistiriyorum) invalid nonce mesaji geliyor. Yardiminizi rica ederim

**Comment by onurgozupek** [comment]
Merhaba, hesabınızın kontrolü için destek@btcturk.com adresine sistemde kayıtlı e-posta hesabınızdan API kontrol talebi başlığıyla e-posta gönderebilir misiniz? Dilerseniz Canlı Destek'ten de yazabilirsiniz.

**Comment by onurgozupek** [comment]
Merhaba, sunucunuzun zaman (time()) çıktısını https://api-pro.btcturk.com/api/v2/server/time adresindeki zaman çıktısıyla eşleştirebilir misiniz?

Ayrıca, web sunucunuzda time() çıktısı 10 karakter uzunluğundaysa 1000 ile çarpıp (milisaniyeye çevirip) tekrar deneyebilir misiniz?

**Comment by dreamci** [comment]
Aynı hatayı ben de alıyorum. Server time ile eşleşen bir nonce gönderiyorum. 

Örneğin "v1/users/transactions/trade?type=buy&type=sell&symbol=btc&symbol=try" sorgusu çalışıyor aynı bilgilerle fakat order çalışmıyor.

https://github.com/BTCTrader/broker-api-docs/issues/137 Bu linkteki arkadaşın sorununu sizin hesabında güncelleme yapmanız çözmüş. Aynı şekilde mail attım destek emailine onlar da buraya yönlendiriyor.

Site yarım yamalak açıldı çok zaman kaybettirdi bize

**Comment by onurgozupek** [comment]
Merhaba, hesabınızı kontrol edip bilgi vereceğiz.

**Comment by onurgozupek** [comment]
Merhaba, PRO API için şu an API key oluşturma arayüzü henüz yayına alınmadığı için BtcTurk üzerinde oluşturulmuş API anahtarı ile PRO API'deki tüm işlemleri yapamıyorsunuz. Destek ekibine ilettiğiniz mesaja istinaden gerekli güncelleme yapıldı. Şu an geçerli olan API anahtarınızla deneme yapabilir misiniz? API anahtarınızı siler ya da yeni anahtar oluşturursanız, tekrar iletişime geçmeniz gerekecek. Çünkü BtcTurk üzerinde oluşturulan anahtarlar PRO ile uyumlu değil. Deneme yaptıktan sonra eğer sorun yaşarsanız bilgi verirseniz kontrol edebiliriz. (Bu arada, ek bilgi olarak Destek ekibimiz API ile ilgili konularda destek vermiyor ve gelen talepleri yazılım ekibi tarafından yönetilen Github sayfamıza yönlendiriyor. Ancak yazılım ekibi de kullanıcı bilgilerinize ulaşamadığı için hesabınızın kontrol edilebilmesi için Destek ekibimize ulaşmanız gerekiyor. Aradaki gecikme bundan kaynaklanıyor. Bilgilerinize.)
