### ISSUE TITLE
invalid Public key hatası code:1037

### ISSUE THREAD

**Issue by screenman06** [BTCTrader/broker-api-docs#143]
Merhaba bu hatayı almaya başladım balance sorgusu ve işlem geçmişimi alabiliyorum ama alış ve satış işlemlerini yaparken bu sorunla karşılaşıyorum.

**Comment by hanilozmen** [comment]
> Merhaba bu hatayı almaya başladım balance sorgusu ve işlem geçmişimi alabiliyorum ama alış ve satış işlemlerini yaparken bu sorunla karşılaşıyorum.

Aynı sorunu yaşıyorum, nedeni nedir?
