### ISSUE TITLE
Unauthorized - Invalid Nonce

### ISSUE THREAD

**Issue by ermanertas** [BTCTrader/broker-api-docs#147]
Merhaba,
Authentication gerekli sorgularda aşağıdaki hatayı alıyorum
'{"success":true,"message":"Unauthorized - Invalid Nonce","code":1037}'

aşağıdaki adresi deniyorum.
'https://api.btcturk.com/api/v1/users/balances'

headers'ı aşağıdaki gibi oluşturuyorum 
                stamp = int(time.time())*1000
                data = "{}{}".format(self.public_key, stamp).encode('utf-8')
                private_key = base64.b64decode(self.private_key)
                signature = hmac.new(private_key, data, hashlib.sha256).digest()

                headers= {
                    "X-PCK": self.public_key,
                    "X-Stamp": str(stamp),
                    "X-Signature": str(base64.b64encode(signature)) }

**Comment by onurgozupek** [comment]
Merhaba, hesabınızın kontrolü için sistemde kayıtlı e-posta adresinizle [destek@btcturk.com](mailto:destek@btcturk.com?subject=API%20Kontrol%20Talebi) adresine API Kontrolü başlığıyla bir e-posta gönderebilir misiniz? Dilerseniz [buraya tıklayarak](https://twitter.com/messages/compose?recipient_id=984317248507695104&text=API%20kontrol%20talebi%20için%20e-posta%20adresim:%20) Twitter üzerinden de iletişime geçebilirsiniz.

**Comment by onurgozupek** [comment]
Aynı API anahtarı ile tekrar deneyebilir misiniz?

**Comment by ermanertas** [comment]
Merhaba, denedim, '{"success":true,"message":"Unauthorized - Invalid Request","code":1037}' bu hatayı alıyorum.

**Comment by onurgozupek** [comment]
Aynı sorguyu https://**api-pro**.btcturk.com/api/v1/balances ile deneyebilir misiniz?

**Comment by ermanertas** [comment]
Merhaba, yine aynı hatayı veriyor '{"success":true,"message":"Unauthorized - Invalid Request","code":1037}' olarak. Benim request kısmında bir hata olabilir mi atladığım headers'a eklemem gereken veya başka birşey?

**Comment by onurgozupek** [comment]
Headers bölümünü;

`headers= {
                "X-PCK": self.public_key,
                "X-Stamp": str(stamp),
                "X-Signature": str(base64.b64encode(signature)),
                " Content-Type": application/json }
`
olarak düzeltip deneyebilir misiniz?

**Comment by ermanertas** [comment]
Merhaba,

Problemi şöyle çözdüm. Headers'ta signature'yi verirken byte'dan tekrar str'ye çevirince sonuç veriyor. 

            headers= {
                "X-PCK": self.public_key,
                "X-Stamp": str(stamp),
                "X-Signature": str(base64.b64encode(signature).decode('utf-8')) }
