### ISSUE TITLE
Yeni api - v1/order alım satım 415 hatası

### ISSUE THREAD

**Issue by fabrimob** [BTCTrader/broker-api-docs#148]
Merhaba,

fetch_balance i basarili sekilde yapiyorum , ancak buy sell islemlerinde hata donuyor. Dolayisiyla authenticationda bir sikinti oldugunu dusunmuyorum.

https://api.btcturk.com/api/v1/order endpointi, 415 Unsupported Media Type donuyor surekli , body yi encode edip-etmeyip her turlu denedim, header 'Content-Type' i denedim(application/x-www-form-urlencoded, application/json) sonuc basarisiz. 

Ayrintilari asagida da gorebilirsiniz:

headerlar: {'User-Agent': 'Mozilla/5.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '/', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded', 'X-PCK': 'hidden', 'X-Stamp': '1869351613821', 'X-Signature': 'hidden', 'Content-Length': '118'}

body: '{"quantity": 0.00087, "price": 0, "stopPrice": 0, "orderMethod": "market", "orderType": "buy", "pairSymbol": "BTCTRY"}'

url: 'https://api.btcturk.com/api/v1/order'

Yardiminizi rica ediyorum

**Comment by onurgozupek** [comment]
Merhaba, 
```

stamp = int(time.time())*1000
data = "{}{}".format(self.public_key, stamp).encode('utf-8')
private_key = base64.b64decode(self.private_key)
signature = hmac.new(private_key, data, hashlib.sha256).digest()

headers= {
                "X-PCK": self.public_key,
                "X-Stamp": str(stamp),
                "X-Signature": str(base64.b64encode(signature).decode('utf-8')) 
}
```

kodu ile deneyebilir misiniz?

Ayrıca API anahtarınızı https://pro.btcturk.com/hesap-ayarlari/api adresinden aldığınızdan emin olun. Btcturk.com'dan alınan API anahtarları V1 ile uyumlu değildir.

**Comment by onurgozupek** [comment]
Merhaba, python istemcilerinin erişim yetkileri ile ilgili bir güncelleme yayınlandı. Tekrar deneyebilir misiniz?

**Comment by fabrimob** [comment]
Selamlar, asagida gerekli herseyi bulabilirsiniz, bircok yol denedim surekli 415 aliyorum.  Sikinti nedir yardimci olabilir misiniz?  fetch_balance basarili . submit order surekli 415 hatasi aliyor. Pro api keylerle de denedim yeni yarattigim, durum degismedi

```
    def sell_order(self, symbol, amount):
        try:
            auth = self.__sign(headers=self.__post_headers())
            self.__create_order(auth, "sell", symbol, amount)
        except:
            return None

    def buy_order(self, symbol, amount):
        try:
            auth = self.__sign(headers=self.__post_headers())
            self.__create_order(auth, "buy", symbol, amount)
        except:
            return None

    def __create_order(self, auth, order_type, symbol, amount):
        params = {
            "quantity": amount,
            "price": 0,
            "stopPrice": 0,
            "orderMethod": "market",
            "orderType": order_type,
            "pairSymbol": symbol
        }
        response = requests.post(BtcTurk.__api["order"], data=params, headers=auth.get('headers'), verify=True)

    def __millis(self):
        return int(time.time() * 1000) + self.time_diff

    def __set_time_diff(self):
        try:
            self.time_diff = 0
            response = requests.get('https://api-pro.btcturk.com/api/v2/server/time', headers=self.__get_headers())
            self.time_diff = response.json()['serverTime'] - self.__millis()
        except:
            self.time_diff = 0

    def __sign(self, headers={}, params={}):
        nonce = str(self.__millis())
        secret = base64.b64decode(self.__secret)
        message = "{}{}".format(self.__api_key, nonce).encode('utf-8')
        signature = self.hmac(secret, message, hashlib.sha256, 'binary')

        headers['X-PCK'] = self.__api_key
        headers['X-Stamp'] = nonce
        headers['X-Signature'] = str(base64.b64encode(signature).decode('utf-8'))
        return {'headers': headers, 'params': params}

    def __post_headers(self, headers={}):
        #headers['Cache-Control'] = 'no-cache; no-store; max-age=0; must-revalidate'
        #headers['Content-Type'] = 'application/x-www-form-urlencoded; charset=utf-8'
        return headers

    def hmac(secret, request, algorithm=hashlib.sha256, digest='hex'):
        h = hmac.new(secret, request, algorithm)
        if digest == 'hex':
            return h.hexdigest()
        elif digest == 'base64':
            return base64.b64encode(h.digest())
        return h.digest()
```

Kodun cagrilis sekliyle ilgili bir kac deneme:
btcturk.buy_order("BTCTRY", 100)
btcturk.buy_order("BTCTRY", 0.0021)

**Comment by onurgozupek** [comment]
Merhaba, API dokümanlarımızı güncelliyoruz. Yeni dokümanlarda örnekler ve sonuçlar daha detaylı anlatılacak. Bilgilendirme için teşekkür ederiz.

**Comment by murataggurbuz** [comment]
url="https://api.btcturk.com/api/v1/order"

    public_key='hidden'
    private_key='hidden'
    private_key = base64.b64decode(private_key)
    stamp = str(int(time.time())*1000)
    data = "{}{}".format(public_key, stamp).encode('utf-8')
    signature = hmac.new(private_key, data, hashlib.sha256).digest()
    signature = base64.b64encode(signature)
    headers={"X-PCK": public_key,"X-Stamp": stamp,"X-Signature": signature}

    params={"quantity": 0.1,"price": 0,"stopPrice": 0, "newOrderClientId":"", "orderMethod":"market", "orderType":"sell", "pairSymbol":"ETHUSDT"}
    data={}

    resp = requests.post(url=url, headers=headers, params=params, data=data)
    print resp

İyi günler,
0.1 ETH/USDT satış emri verebilmek için Python'da yukarıdaki şekilde kodu oluşturdum. Kodu çalıştırdığımda Server dan sürekli 415 hatası dönüyor. Nerede hata yaptığımı bir türlü bulamadım. Python'da api üzerinden al / sat emri açabilmem konusunda yardımcı olabilir misiniz? Saygılarımla,

Not: 
url="https://api.btcturk.com/api/v1/users/balances" adresinden, 
resp = requests.get(url=url, headers=headers, params=params, data=data) komutu ile Balance bilgilerini başarılı şekilde alabiliyorum. Dolayısıyla headers ların oluşturulmasında bir sıkıntı olmadığını düşünüyorum.

**Comment by onurgozupek** [comment]
https://github.com/BTCTrader/broker-api-docs/issues/159#issuecomment-558664638
