### ISSUE TITLE
Unauthorized - Invalid Nonce

### ISSUE THREAD

**Issue by Burak45** [BTCTrader/broker-api-docs#149]
Merhaba ,
object(stdClass)#2 (3) { ["success"]=> bool(true) ["message"]=> string(28) "Unauthorized - Invalid Nonce" ["code"]=> int(1037) }

şeklinde hata almaktayım 

  $message = $this->apiKey.time();
            $signatureBytes = hash_hmac('sha256', $message, base64_decode($this->apiSecret), true);
            $signature = base64_encode($signatureBytes);
            $nonce = time();
            $headers = array(
                'X-PCK: '.$this->apiKey,
                'X-Stamp: '.$nonce,
                'X-Signature: '.$signature,
            );

kodunu kullanıyorum nerede hata yapıyorum acaba 
not: birden fazla hesaptan ve api ile denedim hepsinde aynı hata geliyor karşıma 
Teşekkürler,
İyi Çalışmalar

**Comment by onurgozupek** [comment]
Merhaba, zamanı time()*1000 ile milisaniyeye çevirip deneyebilir misiniz?

Ayrıca, PRO için https://pro.btcturk.com/hesap-ayarlari/api sayfasından yeni API anahtarı alarak deneyebilir misiniz? Daha önce Btcturk.com'dan aldığınız API anahtarları yeni API ile uyumlu değil.
