### ISSUE TITLE
yeni tasarım yeni altyapı

### ISSUE THREAD

**Issue by ahmedahmedo** [BTCTrader/broker-api-docs#15]
Ethereum eklendikten ve yeni tasarımla yeni altyapıya geçildikten sonra apinin bazı linkleri çalışmaz oldu. balance ve ticket gibi bazı bilgilere ulaşılabiliyorken, openorder gibi bazı linkler uçmuş durumda.
dokümanın güncellenmesi gerekiyor.

**Comment by gurcankavakci** [comment]
Destek ekibine durumu sorduğumda 

"API geçici süreliğine hizmet vermemektedir.Güncelleme çalışmalarımız tüm hızıyla devam etmektedir.
Bilginize." 

şeklinde cevap aldım.

**Comment by erhan** [comment]
Selamlar API'de güncelleme yapıp yeni versiyona geçicek misiniz? Yoksa şu an ki halinden devam mı ediliyor?

**Comment by BTCTraderAdmin** [comment]
Çoklu para birimine geçtiğimiz için API üzerinde de değişiklikler var. Bu
hafta Salı gününe kadar bu dökümanları güncellemeye çalışıp API kullanımına
açacağız.
