### ISSUE TITLE
502:Emir girilemedi. Bu işlem için kullanılabilir bakiyeniz yeterli değildir.

### ISSUE THREAD

**Issue by celal206** [BTCTrader/broker-api-docs#150]
Site üzerinden limit emir verme esnasında sorun olmuyor fakat api ile aynı emri vermeye çalışınca böyle bir hata ile karşılaşıyorum.

**Comment by onurgozupek** [comment]
Emir vermeden önce kullanılabilir bakiyenizi kontrol ediyor musunuz?

Bakiyenizin %100'ü ile emir vermeyi denediğinizde komisyon hesaplaması nedeniyle hata alıyor olabilirsiniz. Bakiyenizin ufak bir bölümüyle deneme yapabilir misiniz?

Emir girerken kullandığınız sorguyu paylaşabilmeniz mümkün mü?

**Comment by celal206** [comment]
Evet, kontrol ediyorum, bakiyemdeki miktardan daha küçük miktarlar ile emir vermeye çalıştığımda da aynı sorunla karşılaştım. Komisyon oranlarını da dahil edip kullandığım programımda da aynı sorun gerçekleşti. Kullandığım programda sadece emir veilecek miktar(bakiyede kalan miktar) 10 TL değerinden daha fazlaysa emir veriyor, bu yüzden çok düşük miktara indiğinde emir verilmiyor. Kullandığım programın gerekli kısımları şu şekilde(python'da yazıldı):
patm: Emir verilecek fiyat
ptk: Tampon Oranı
 BASE_URL = "https://www.btcturk.com/api/"

    def __init__(self, public_key=None, private_key=None):
        self.public_key = public_key
        self.private_key = private_key

    def _headers(self, protection):
        if protection:
            if self.public_key and self.private_key:
                stamp = str(int(time.time()))
                data = "{}{}".format(self.public_key, stamp).encode('utf-8')
                private_key = base64.b64decode(self.private_key)
                signature = hmac.new(private_key, data, hashlib.sha256).digest()

                return {
                    "X-PCK": self.public_key,
                    "X-Stamp": stamp,
                    "X-Signature": base64.b64encode(signature)
                }
            else:
                raise ValueError("You must set your public and private key for this method.")
        return {}

    def _make_request(self, method="GET", path="", params={}, data={}, protection=True):
        resp = None
        url = requests.compat.urljoin(self.BASE_URL, path)
        headers = self._headers(protection)
        headers["user-agent"] = "Mozilla/5.0"
        if method == "GET":
            resp = requests.get(url=url, headers=headers, params=params, data=data)
        elif method == "POST":
            resp = requests.post(url=url, headers=headers, params=params, data=data)
        return resp.json()

    def _make_order(self, pair_symbol, order_method, order_type, total, total_precision, amount, amount_precision, price,
                    price_precision, trigger_price, trigger_price_precision):
        data = {
            "PairSymbol": pair_symbol,
            "OrderMethod": order_method,
            "OrderType": order_type,
            "Total": total,
            "TotalPrecision": total_precision,
            "Amount": amount,
            "AmountPrecision": amount_precision,
            "Price": price,
            "PricePrecision": price_precision,
            "TriggerPrice": trigger_price,
            "TriggerPricePrecision": trigger_price_precision,
            "DenominatorPrecision": 2
        }
        return self._make_request(method="POST", path="exchange", data=data)
    def get_balances(self):
        """
        Get the authenticated account's balance
        :returns: API response
        """
        return self._make_request(method="GET", path="balance")
    def limit_buy(self, pair_symbol, total, total_precision, price, price_precision):
        """
        Send in a new limit buy order
        :param str pair_symbol: currency symbol pair (BTCTRY, ETHTRY, XRPTRY)
        :param int total: The total amount you will spend with this order. You will buy from different prices until your order is filled as described above
        :param str total_precision: Precision of the total (.001)
        :param int price: Price field will be ignored for market orders. Market orders get filled with different prices until your order is completely filled.
        :param str price_precision: Precision of the price (.001)
        :returns: API response
        """
        return self._make_order(pair_symbol=pair_symbol, order_method=0, order_type=0, total="0",
                                total_precision="00", amount=total, amount_precision=total_precision, price=price,
                                price_precision=price_precision, trigger_price="0", trigger_price_precision="0")

    def limit_sell(self, pair_symbol, total, total_precision, price, price_precision):
        """
        Send in a new limit sell order
        :param str pair_symbol: currency symbol pair (BTCTRY, ETHTRY, XRPTRY)
        :param int total: The total amount you will spend with this order. You will buy from different prices until your order is filled as described above
        :param str total_precision: Precision of the total (.001)
        :param int price: Price field will be ignored for market orders. Market orders get filled with different prices until your order is completely filled.
        :param str price_precision: Precision of the price (.001)
        :returns: API response
        """
        return self._make_order(pair_symbol=pair_symbol, order_method=0, order_type=1, total="0", total_precision="00",
                                amount=total, amount_precision=total_precision, price=price,
                                price_precision=price_precision, trigger_price="0", trigger_price_precision="00")
    def durum():
        try:
            df = client.get_balances()
            ltc_balance= df['ltc_balance']
            try_balance = df['try_balance']
            ltc_reserved = df['ltc_reserved']
            try_reserved = df['try_reserved']
            ltc_available = df['ltc_available']
            try_available = df['try_available']
            emir = client.get_open_orders(sym)
            return ltc_balance, try_balance, ltc_reserved, try_reserved, ltc_available, try_available
       except:
            pass
    def emir1():
         ltc_balance, try_balance, ltc_reserved, try_reserved, ltc_available, try_available = durum()
         tam = math.modf(ltc_available)
         patmtam = math.modf(patm*ptk)
         o = client.limit_sell(sym,int(tam[1]),int(tam[0]*100) , int(patmtam[1]) ,int(patmtam[0]*100))
    def emir2():
        ltc_balance, try_balance, ltc_reserved, try_reserved, ltc_available, try_available = durum()
        tam = math.modf(try_available/patm)
        patmtam = math.modf(patm/ptk)
        o = client.limit_buy(sym,int(tam[1]),int(tam[0]*100) , int(patmtam[1]) ,int(patmtam[0]*100))

**Comment by emreacar** [comment]
Merhaba, Aynı problemi ben de yaşıyorum. Destek üzerinden ekran görüntülerini ilettim. Ancak sonuç nafile. 

Kendi tarafımda problem olup olmadığını bir kenara bırakalım, Kullanılabilir bakiyemi BTC Masaüstü arayüzü üzerinden kontrol ettiğimde bakiye olduğunu görebiliyorum. Yine masaüstü arayüzünden satış emri vermek istediğimde kullanılabilir bakiyeniz yok mesajı dönüyor. Aynı hatayı API üzerinden de alıyorum. Fakat mobil uygulama ile piyasa satış emri vermek istediğimde işlemi gerçekleştiriyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
