### ISSUE TITLE
28 Saattir Invalid Nonce

### ISSUE THREAD

**Issue by m4rked0ne** [BTCTrader/broker-api-docs#152]
Merhaba,

Geçtiğimiz gün boyunca V1 sorgularında invalid nonce hatası alıyorum. BTCTurk Pro'dan yeni bir api key oluşturup onunla da denedim fakat aynı problem devam ediyor.
{"success":true,"message":"Unauthorized - Invalid Nonce","code":1037}

Nonce'u gönderdiğim header. (Python)

------------------------------------------------------------------------------------
headers["X-PCK"] = self.api_key
unixStamp = str(int(time.time() * 1000))
headers["X-Stamp"] = unixStamp
data = "{}{}".format(self.api_key,
    unixStamp,)

private_key = base64.b64decode(self.private_key)

signature = hmac.new(private_key, data.encode('utf-8'), hashlib.sha256).digest()
headers["X-Signature"] = base64.b64encode(signature)
headers["Content-Type"] = "application/x-www-form-urlencoded"

---------------------------------------------------------------------------------------

**Comment by onurgozupek** [comment]
Merhaba,

` headers["Content-Type"] = "application/x-www-form-urlencoded"`
kısmını
` headers["Content-Type"] = "application/json"`
olarak değiştirip yeniden deneyebilir misiniz?

**Comment by m4rked0ne** [comment]
Merhaba,

Değişikliği yaptım fakat sonuç aynı. 7/24 çalışan bir kod bu. 28 saat önce başladı bu sıkıntı.

**Comment by m4rked0ne** [comment]
Hata başlamasına rağmen birkaç saat boyunca sorgu gönderdiğim için bir kısıtlama olmuş olabilir mi?

**Comment by onurgozupek** [comment]
Sunucu zamanınızı API zamanı ile karşılaştırır mısınız?

https://api.btcturk.com/api/v2/server/time

**Comment by m4rked0ne** [comment]
>>> print(requests.get('https://api.btcturk.com/api/v2/server/time').json()['serverTime'], time.time()*1000)
1571044814448 1571044805518.2732
>>>

**Comment by m4rked0ne** [comment]
8 saniyelik bir fark gözüküyor aşağı yukarı.

**Comment by m4rked0ne** [comment]
Kendi saatimi server saatinin 1 saniye kadar önüne koyunca çözüldü sorun. Aradaki fark 28 saat önce sabah saat 8 de kendiliğinden nasıl değişti bilmiyorum.
