### ISSUE TITLE
401 - Unauthorized - Invalid Public key hatası

### ISSUE THREAD

**Issue by coolmoto** [BTCTrader/broker-api-docs#154]
https://pro.btcturk.com/hesap-ayarlari/api den oluşturduğum api keyler hiç bir endpoint ile çalışmıyor , 401 - Unauthorized - Invalid Public key hatası veriyor. 

www.btcturk.com üzerinden oluşturduğum API key'ler /api/v1/users/balances, /api/v1/users/transactions/trade endpointleri için çalışıyor fakat /api/v1/allOrders ve /api/v1/openOrders endpointleri için çalışmıyor, 401 - Unauthorized - Invalid Public key hatası veriyor. 

Kodu https://api-dev.btcturk.com "d6fad679-cac4-4408-bd13-f6e639617207" "TR4ZtbVx2oBNC2KO44R2ETCpA8qZ3JCF" api key secretleri ile test ettiğimde hatasız cevap geliyor. 

Konu ile ilgili yardımcı olabilirseniz memnum olurum.

**Comment by onurgozupek** [comment]
BtcTurk | PRO API'ı kullanmak için https://pro.btcturk.com/hesap-ayarlari/api-erisimi (Hesap > API Erişimi) adresinden yeni api anahtarı oluşturabilir https://api.btcturk.com/api adresini baseUrl olarak kullanabilirsiniz. (Örn Ticker için https://api.btcturk.com/api/v2/ticker?pairSymbol=BTCTRY metoduyla sorgu gönderebilirsiniz. Açık emirler için https://api.btcturk.com/api/v1/openOrders?pairSymbol=BTCTRY metodunu kullanabilirsiniz. Ancak tüm kullanıcı işlemlerinden önce doğrulama gereklidir.

**Comment by sukru77** [comment]
Ayni sorunu bende yasiyorum. Ve bahsettigin URL leri kullaniyorum. Fakat eski api key ile userTransactions v1 dan cekebiliyorum.

**Comment by coolmoto** [comment]
"Hesap > API Erişimi" https://pro.btcturk.com/hesap-ayarlari/api adresine yönlendiriyor. https://pro.btcturk.com/hesap-ayarlari/api-erisimi adresinden 404 hatası alıyorum. 

Yeni arayüzden oluşturduğum API keyleri kabul etmiyor. Eski arayüzden oluşturduğum anahtarlarla kullanıcı balance'ını ve kullanıcı trade'lerini çekebiliyrum fakat açık emirler "Unauthorized - Invalid Public" hatası veriyor. 

Aynı sorun  https://api-dev.btcturk.com için de geçerli. "d6fad679-cac4-4408-bd13-f6e639617207" "TR4ZtbVx2oBNC2KO44R2ETCpA8qZ3JCF" anahtarları ile kullanıcı balance'ı ve trade işlemleri geliyor. Fakat açık emirler (https://api-dev.btcturk.com/api/v1/openOrders?pairSymbol=BTCTR) 401 - Unauthorized - Invalid Public key hatası veriyor.

Signature'ı üreten kodda hata olsaydı kullanıcı balance'ı ve kullanıcı trade işlemleri de çalışmazdı diye düşünüyorum. Signature üretimi açısından bu endpoint'ler arasından bir fark olmaması gerekiyor.

**Comment by coolmoto** [comment]
Sorun şu şekilde düzeldi; yeni arayüzden ( https://pro.btcturk.com/hesap-ayarlari/api) IP sınırlandırılması yapılmadan api key tanımlanırsa oluşturulan api keyler çalışıyor. Sanırım API endpointleri cloudflare yüzünden client IP'sini doğru alamıyor. 

Eski arayüzde de IP kısıtlaması oluşturuyordum ama girilen IP kısıtlmasının etkin olmadığını fark ettim. Bu nedenler eski arayüzden oluşturulan api keyler bazı end pointlerle çalışıyor. Bunun nedeni de eski arayüzden api key tanımlanırsa [ "UserBalance", "OpenOrders", "BuyOrder", "UserTransactions", "CancelOrder", "SellOrder", "MoneyDepositWithdrawal"] permissionları ile oluşturuyor. Yeni arayüz ise ["Exchange", "UserBalance", "UserTransactions"] permission'lari ile oluşturuyor. Sanırım https://api-dev.btcturk.com/api/v1/openOrders endpoint'ı yeni arayüz tarafından oluşturulan permissionları istiyor. Umarım diğer arkadaşlara bu bilgiler yardımcı olur.

**Comment by SaitamaTechno** [comment]
Yeni gelen olursa, özetleyim:
IP ler ile ilgili sorun var ve ben ipv4 adresimi yazdıgımda hata aldım ama ipv6 adresimi yazdıgımda düzeldi. ipv6 adresinizi kullanın api key oluştururken.
