### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by emrahtopcu** [BTCTrader/broker-api-docs#155]
Merhaba, private endpoint lerin bazılarında '401 Unauthorized' hatası alıyorum.

Hata aldığım request örneği:
{Method: GET, RequestUri: 'https://api.btcturk.com/api/v1/openOrders?pairSymbol=BTCTRY', Version: 1.1, Content: <null>, Headers:
{
  X-PCK: .........................
  X-Stamp: 1572861466289
  X-Signature: HtstmUhHeRbSViyt29dy0sQ+EChR4EMn3ZT6oQrm8Co=
  Accept: application/json
}}

Başarılı request örneği:
{Method: GET, RequestUri: 'https://api.btcturk.com/api/v1/users/transactions/trade?skip=0&pageLength=25&sort=desc', Version: 1.1, Content: <null>, Headers:
{
  X-PCK: .........................
  X-Stamp: 1572861610108
  X-Signature: aE55lomzWlL6+p5QXqbsNMSkEer9wurD1D4ntpvDW2c=
  Accept: application/json
  User-Agent: C#
  User-Agent: App
}}

Hatalı request e ait response :
{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: keep-alive
  Strict-Transport-Security: max-age=15724800; includeSubDomains
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Pragma: no-cache
  Vary: Origin
  Vary: Access-Control-Request-Method
  Vary: Access-Control-Request-Headers
  Access-Control-Allow-Credentials: true
  Access-Control-Expose-Headers: X-Content-Type-Options, X-Frame-Options, X-XSS-Protection, Date, Transfer-Encoding, Vary
  x-content-type-options: nosniff
  x-frame-options: DENY
  x-xss-protection: 1; mode=block
  X-Rate-Limit-Limit: 1s
  X-Rate-Limit-Remaining: 9
  X-Rate-Limit-Reset: 2019-11-04T10:04:27.5452885Z
  CF-Cache-Status: DYNAMIC
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  CF-RAY: 5305c389ce2aa7f2-IST
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  Date: Mon, 04 Nov 2019 10:04:26 GMT
  Set-Cookie: __cfduid=d8cfddb24b535c1421ae95f02d94d56401572861866; expires=Tue, 03-Nov-20 10:04:26 GMT; path=/; domain=.btcturk.com; HttpOnly
  Server: cloudflare
  WWW-Authenticate: Bearer
  Content-Length: 0
}}

Şimdilik sadece açık emirler, hesap hareketleri(al/sat) ve hesap bakiyelerinde denedim. Sadece hesap hareketleri başarılı oluyor.

Api'yi pro sitesinden oluşturdum, api kaydında yazan yetkiler: Al Sat, Kullanıcı Bakiyesi, Kullanıcı Hareketleri.

Yardımcı olmanızı rica ediyorum, iyi çalışmalar.

**Comment by onurgozupek** [comment]
Merhaba, sorgudan önce doğrulama gerçekleştirilemediği durumlarda API'dan 401 - Unauthorized hatası dönmektedir. Xstamp değerinin API sunucusunun timestamp'i ile aynı olup olmadığını kontrol edebilir misiniz? (Sunucunuz yurtdışındaysa, ABD ve Avrupa ülkelerinde saatler 1 saat geri alındı, bu nedenle zaman dilimi nedeniyle hata alabilirsiniz)

**Comment by emrahtopcu** [comment]
Talep ettiğiniz gibi sunucu'dan zaman bilgisini alıp, bu zaman bilgisi ile istek gönderdim. Örnek kod ve sunucudan dönen yanıt aşşağıdadır.

//Create HttpClient and add json content format to default headers.
      var client = new HttpClient();
      client.DefaultRequestHeaders.Accept.Clear();
      client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

      //Create request for server time sync
      var requestMessageServerTime = new HttpRequestMessage(HttpMethod.Get, "https://api.btcturk.com/api/v2/server/time");

      //Get current time before sending request
      var clientTime = DateTime.Now;
      var clientTimeInTicks = clientTime.Ticks;

      //Send
      HttpResponseMessage responseServerTime = await client.SendAsync(requestMessageServerTime);

      //get json server time from response
      var jsonString = await responseServerTime.Content.ReadAsStringAsync();
      var serverTime = Newtonsoft.Json.JsonConvert.DeserializeObject(jsonString) as dynamic;


      //create authantication header parameters using servertime
      long nonce = Convert.ToInt64(serverTime.serverTime);
      string message = _ClientKey + nonce;
      string signature;
      using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(_ClientSecret)))
      {
        byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
        signature = Convert.ToBase64String(signatureBytes);
      }

      //create actual request for account balance and set authantication headers
      var requestMessage = new HttpRequestMessage(HttpMethod.Get, "https://api.btcturk.com/api/v2/users/balances");
      requestMessage.Headers.Add("X-PCK", _ClientKey);
      requestMessage.Headers.Add("X-Stamp", nonce.ToString());
      requestMessage.Headers.Add("X-Signature", signature);

      //send
      HttpResponseMessage response = await client.SendAsync(requestMessage);


Client ve sunucu zaman bilgileri:
clientTime = 5.11.2019 06:22:25
clientTimeInTicks = 1572934945962
serverTime = 1572934946370

Client istek detayı:
{Method: GET, RequestUri: 'https://api.btcturk.com/api/v2/users/balances', Version: 1.1, Content: <null>, Headers:
{
  X-PCK: ...........................................................
  X-Stamp: 1572934946370
  X-Signature: M1b1SfNJyTBFKZbCI0NuJbYBy4N/r3jBiCThzJZC40M=
  Accept: application/json
}}

Sunucudan dönen yanıt:
{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: keep-alive
  Strict-Transport-Security: max-age=15724800; includeSubDomains
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Pragma: no-cache
  Vary: Origin
  Vary: Access-Control-Request-Method
  Vary: Access-Control-Request-Headers
  Access-Control-Allow-Credentials: true
  Access-Control-Expose-Headers: X-Content-Type-Options, X-Frame-Options, X-XSS-Protection, Date, Transfer-Encoding, Vary
  x-content-type-options: nosniff
  x-frame-options: DENY
  x-xss-protection: 1; mode=block
  X-Rate-Limit-Limit: 1s
  X-Rate-Limit-Remaining: 9
  X-Rate-Limit-Reset: 2019-11-05T06:22:27.6599080Z
  CF-Cache-Status: DYNAMIC
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  CF-RAY: 530cbbb87d52b035-IST
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  Date: Tue, 05 Nov 2019 06:22:26 GMT
  Server: cloudflare
  WWW-Authenticate: Bearer
  Content-Length: 0
}}

X-Stamp parametresini istek göndermeden hemen önce sunucudan almama rağmen aynı hatayı alıyorum.

**Comment by emrahtopcu** [comment]
Merhaba, son yazdığım cevabı inceleme şansınız oldumu ?

**Comment by onurgozupek** [comment]
Merhaba, bakiye sorgusunu /v1/ üzerinden denemeniz gerekiyor.
