### ISSUE TITLE
allorders response data

### ISSUE THREAD

**Issue by idrispendisbey** [BTCTrader/broker-api-docs#156]
/api/v1/allOrders? endpointini kullanarak aldığım datalarda "quantity", "amount" ve "leftAmount" öğreleri var. Amount ve quantity nin tam olarak ayrımı nedir? Çoğunda bu değerler aynı olmasına rağmen, birbirlerinden farklı olduğu orderlar görüyorum. Örnek: 

{'id': 81501803, 'price': '9123.00', 'amount': '0.056669955058643', 'quantity': '0', 'stopPrice': '0', 'pairSymbol': 'BTCUSDT', 'pairSymbolNormalized': 'BTC_USDT', 'type': 'buy', 'method': 'market', 'orderClientId': 'advanced', 'time': 1572594990453, 'updateTime': 1572594990607, 'status': 'Closed', 'leftAmount': '0.0000000000000000'}

**Comment by onurgozupek** [comment]
/allOrders uçnoktasından tamamlanmış ve iptal edilmiş emirleri sorgulayabilirsiniz. Amount değeri emir verilen miktarı gösteriyor. LeftAmount ise, emrin eşleşmeyen kısmını gösteriyor. Emrinizin bir kısmı eşleştikten sonra iptal ettiyseniz, gerçekleşmeyen kısmı LeftAmount'tan takip edebilirsiniz.

Quantity ise, önyüzde market emirlerde, toplam tutarı hesaplamak için kullanılıyor. Ancak API emirlerinde hesaplamayı siz yaptığınız için amount değeri ile aynı sonucu verecektir.
