### ISSUE TITLE
endpoint karmaşası hakkında

### ISSUE THREAD

**Issue by abduramann** [BTCTrader/broker-api-docs#157]
Birkaç sorum olacaktı.
1- Yazdığım uygulamada api.btcturk mu yoksa api-pro.btcturk mu kullanmalıyım? Farkları var mı? Pratikte bir farka rastlamadım.
2- Temel olarak sıkıntım şu: orderları cancel edemiyorum, id ne verirsem vereyim hep ORDER CANNOT BE CANCELED hatası alıyorum. Uyduruk sayı versem de böyle. v1/order endpoint'ini kullanıyorum. v2 private endpointlerini kullanamıyorum, unauthorized hatası alıyorum. API keylerini pro.btcturk.com adresinden oluşturmuştum.
3- Yine benzer şekilde v1/allOrders'a orderId verince boş order listesi geliyor. v2/allOrders var mı?Kullanamadığım için bilemiyorum.

**Comment by onurgozupek** [comment]
Merhaba,

1- BtcTurk | PRO için hazırlanan https://api.btcturk.com/api adresini kullanmalısınız. (www.btcturk.com/api adresi yakında kapanacak)

BtcTurk | PRO için hazırlanan API ile kripto/kripto işlem çiftlerinde alım satım yapabilir, NEO, EOS gibi BtcTurk'te yer almayan kriptoparalarla işlem yapabilirsiniz. BtcTurk | PRO API, önceki API ile kıyaslanınca, daha gelişmiş ve daha özelleştirilmiştir.

2- Emir silmek için göndereceğiniz sorguyu POST değil DELETE olarak göndermelisiniz.

3- Tüm emirlerinizi şu an sadece V1 üzerinden sorgulayabilirsiniz. Ancak işlem çifti belirlemeniz gerekiyor. https://api.btcturk.com/api/v1/allOrders?pairSymbol=BTCTRY kullanabilirsiniz.

**Comment by abduramann** [comment]
Hızlı cevap için teşekkürler. 

1- Emir silmede DELETE gönderiyorum, python biliyorsanız request.delete kullanıyorum zaten ama ona rağmen alıyorum aynı hatayı.

2- allOrders ilgili sıkıntı şu. pair gönderiyorum fakat yanında dokümanda yazdığı üzere orderId gönderdiğimde order listesi boş geliyor. orderId çalışmadığı için son 1000 order'ı alıp ordan istediğim id'li order'ı buluyorum şimdilik fakat takdir edersiniz güvenilir bir çözüm değil bu. çünkü aradığım order son 1000 içinde olmayabilir, page page dolaşmam lazım ama kaç page olduğunu bilmiyorum ve bu şekilde aramak güzel bir çözüm de değil.

Teşekkürler.

**Comment by abduramann** [comment]
Detaylandırırsam;

DELETE ile gönderdiğim istek bu: {'id': '89302965'}
Gelen cevap bu: {'success': False, 'message': 'ORDER_COULD_NOT_BE_CANCELED', 'code': 1050}

**Comment by abduramann** [comment]
Tüm requst ve response'i yazdırayım. bad request alıyorum ama neden?

< DELETE /api/v1/order HTTP/1.1
< Host: api.btcturk.com
< user-agent: Mozilla/5.0
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< X-PCK: Silindi
< X-Stamp: Silindi
< X-Signature: Silindi
< Content-Type: application/json
< Content-Length: 16
< 
< {"id": 89307591}
> HTTP/1.1 400 Bad Request
> Date: Tue, 26 Nov 2019 10:31:43 GMT
> Content-Type: application/json; charset=utf-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Set-Cookie: __cfduid=d0a950d96fd1f40ab28635919c78251ed1574764303; expires=Thu, 26-Dec-19 10:31:43 GMT; path=/; domain=.btcturk.com; HttpOnly
> Strict-Transport-Security: max-age=15724800; includeSubDomains
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> Pragma: no-cache
> Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
> Access-Control-Allow-Credentials: true
> Access-Control-Expose-Headers: X-Content-Type-Options, X-Frame-Options, X-XSS-Protection, Date, Transfer-Encoding, Vary
> x-content-type-options: nosniff
> x-frame-options: DENY
> x-xss-protection: 1; mode=block
> api-supported-versions: 1.0, 2.0
> X-Rate-Limit-Limit: 1s
> X-Rate-Limit-Remaining: 49
> X-Rate-Limit-Reset: 2019-11-26T10:31:44.8709775Z
> CF-Cache-Status: DYNAMIC
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Server: cloudflare
> CF-RAY: 53bb31c2f8f2c837-AMS

**Comment by onurgozupek** [comment]
```
import json

url = 'https://api.btcturk.com/api/v1/order'
payload = {'id': 'BURAYA_ORDER_ID_GELMELI'}
headers = {'Accept': 'application/json', 'Content-Type': 'application/json'}

r = requests.delete(url, data=json.dumps(payload), headers=headers)
print(r.json())
```

kodunu deneyebilir misiniz?

**Comment by abduramann** [comment]
Sizin kodu çalıştırınca public çalıştığı için aşağıdaki hatayı alıyorum:
{'success': True, 'message': 'Unauthorized - Invalid Public key', 'code': 1037}

sizin kodu private'a çevirince ise yine yukarıdaki hatayı alıyorum: {'success': False, 'message': 'ORDER_COULD_NOT_BE_CANCELED', 'code': 1050}

**Comment by abduramann** [comment]
sizin php'de istemciniz var, yanlış görmediysem. Oradaki delete çalışıyorsa requestin raw halini gönderebilir misiniz?

**Comment by abduramann** [comment]
Sorunu buldum, dokuman hatalı imiş. DELETE'de parametreyi body'a değil url'a eklemek gerekiyormuş. Sizin php kodunda doğrusu var. Dün gece nasıl gözümden kaçmış? :)

**Comment by abduramann** [comment]
Diğerleri için yazayım,order id **data** ile değil, **params** ile json'a dönüştürülmeden gönderilmesi gerekiyor.

import json

url = 'https://api.btcturk.com/api/v1/order'
payload = {'id': 'BURAYA_ORDER_ID_GELMELI'}
headers = {'Accept': 'application/json', 'Content-Type': 'application/json'}

r = requests.delete(url, **params=payload**, headers=headers)
print(r.json())

**Comment by onurgozupek** [comment]
PHP ile emir iptal kod örneği: 
```php
$nonce = time()*1000;
$message = API_KEY.$nonce;
$signatureBytes = hash_hmac('sha256', $message, base64_decode(API_SECRET), true);
$signature = base64_encode($signatureBytes);
$headers = array(
    'X-PCK: '.API_KEY,
    'X-Stamp: '.$nonce,
    'X-Signature: '.$signature,
    'Cache-Control: no-cache',
    'Content-Type: application/json'
);

$post_data = '{"id": BURAYA_ORDER_ID_GELECEK}';
$url = 'https://api.btcturk.com/api/v1/order';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);   
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
if ($postMethod == 3) {
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE'); 
}
$result = curl_exec($ch);
if (curl_errno($ch)) {
    print_r(curl_error($ch));
} else {
$answer = json_decode($result);
echo 'Sonuç:<pre>';
print_r($answer);
echo '</pre>';
}
```

**Comment by abduramann** [comment]
Aynı anda yazdık :) sorunu çözdüm, yukarıda yazdım.  Teşekkürler.

**Comment by onurgozupek** [comment]
Rica ederim. İyi günler.
