### ISSUE TITLE
BTCTurk Python Api Alım Satım Hatası Hk.

### ISSUE THREAD

**Issue by murataggurbuz** [BTCTrader/broker-api-docs#159]
url="https://api.btcturk.com/api/v1/order"

public_key='hidden'
private_key='hidden'
private_key = base64.b64decode(private_key)
stamp = str(int(time.time())*1000)
data = "{}{}".format(public_key, stamp).encode('utf-8')
signature = hmac.new(private_key, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers={"X-PCK": public_key,"X-Stamp": stamp,"X-Signature": signature}

params={"quantity": 0.1,"price": 0,"stopPrice": 0, "newOrderClientId":"", "orderMethod":"market", "orderType":"sell", "pairSymbol":"ETHUSDT"}
data={}

resp = requests.post(url=url, headers=headers, params=params, data=data)
print resp

İyi günler,
0.1 ETH/USDT satış emri verebilmek için Python'da yukarıdaki şekilde kodu oluşturdum. Kodu çalıştırdığımda Server dan sürekli 415 hatası dönüyor. Nerede hata yaptığımı bir türlü bulamadım. Python'da api üzerinden al / sat emri açabilmem konusunda yardımcı olabilir misiniz? Saygılarımla,

Not:
url="https://api.btcturk.com/api/v1/users/balances" adresinden,
resp = requests.get(url=url, headers=headers, params=params, data=data) komutu ile Balance bilgilerini başarılı şekilde alabiliyorum. Dolayısıyla headers ların oluşturulmasında bir sıkıntı olmadığını düşünüyorum.

**Comment by onurgozupek** [comment]
Çalışan Python kod örneği:

```python
import base64, time, hmac, hashlib, requests, json
from requests_toolbelt.utils import dump

url="https://api.btcturk.com/api/v1/order"

public_key='API_KEY'
private_key='API_SECRET'
private_key = base64.b64decode(private_key)
stamp = str(int(time.time())*1000)
data = "{}{}".format(public_key, stamp).encode('utf-8')
signature = hmac.new(private_key, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers={"X-PCK": public_key,"X-Stamp": stamp,"X-Signature": signature, "Content-Type":"application/json"}

params={"quantity": 0.0005,"price": 0,"stopPrice": 0, "newOrderClientId":"", "orderMethod":"market", "orderType":"sell", "pairSymbol":"BTCUSDT"}

resp = requests.post(url=url, headers=headers, json=params)
result = dump.dump_all(resp)
print(result.decode('utf-8'))
```

**Comment by murataggurbuz** [comment]
Hızlı cevabınız ve yardımınız için çok teşekkür ederim.
