### ISSUE TITLE
telefon uygulaması sorunu

### ISSUE THREAD

**Issue by GitHubYou** [BTCTrader/broker-api-docs#16]
güncellemeden sonra telefon uygulaması hiç açılmadı. açılır açılmaz kapanıyor, "hata oluştu" mesajı çıkıyor.
madem henüz etherium işlemleri yapılmayacak. bari play store'a eski versiyonu geri yükleyin de app'i rahatça kullanalım

**Comment by BTCTraderAdmin** [comment]
Önümüzdeki hafta Salı Çarşamba günü güncellenecek uygulama. Biraz daha
vakit rica ediyoruz.

**Comment by byazici** [comment]
Merhaba,

iOS Uygulaması bende hata **hatalı çalışıyor:**


![btcturk-issue-16](https://user-images.githubusercontent.com/20735567/32093345-9b96a39a-bb04-11e7-991f-f71d2df17d70.jpg)

**Comment by BTCTraderAdmin** [comment]
Merhaba,

Eğer QRcode ile giriş yapıyorsanız, çıkış yapıp kodu yenileyin düzelir.
Eski none ile yeni nonce arasındaki fartktan dolayı böyle bir hata
alıyoruz.

**Comment by byazici** [comment]
Çalıştı teşekkürler.  :thumbsup:

**Comment by ufukOzarslan** [comment]
Android lollipop sürümlerinde açılışta hata veriyor, rapor gönder kısmı çıkıyor ve çalışmıyor. Bu konuda app ihtiyaç gibi. Bilginize.
