### ISSUE TITLE
Internal Error ve arada bir gerçekleşen Unathorized error

### ISSUE THREAD

**Issue by abduramann** [BTCTrader/broker-api-docs#160]
Merhaba,

Uygulamamda yaklaşık 200 ms'de bir v1/openOrders isteği yapıyorum. Arada bir Unathorized hatası alıyorum. Kodu mümkün olduğunca fail-safe yazdığım için bir süre bekleyip, isteği tekrarlıyorum, sıkıntı ortadan kalkıyor. Uygulamamı çok engellemiyor ama bilginiz olsun. Bitmart'ta da benzeri sıkıntı yaşadığım için hazırlıklıydım ve belki REST yapılarda sık periyodik talepler sıkıntı oluşturuyor olabilir. Bilginiz olsun diye yazdım.

İlgili örnek log mesajı:
2019-11-27 11:00:40,383 UTC+3 [Thread-3    ] [ERROR]  {'success': True, 'message': 'Unauthorized - Invalid Nonce', 'code': 1037}

Diğer husus, bugün ilk defa karşılaştığım bir durum. Sunucu çalışma mı vardı yoksa rate limitlere falan mı takıldım? Fail-safe kodum bunu halledememiş :) çünkü maximum recursion hatası oluşmuş. Onun logu da aşağıda.

2019-11-27 12:02:26,048 UTC+3 [Thread-3    ] [ERROR]  {'success': False, 'message': 'INTERNAL_ERROR', 'code': 500}

**Comment by onurgozupek** [comment]
Her sorguda yeni bir nonce değeri göndermeniz ve 2 sorgunun nonce değerinin birbirinden farklı olması gerekiyor.

Saniyede 1 adet bakiyeleri çekebileceğiniz 100 tekrarlı sorgu örneği:
``` python
import base64, time, hmac, hashlib, requests, json
from requests_toolbelt.utils import dump
from time import gmtime, strftime

url="https://api.btcturk.com/api/v1/users/balances"
public_key='API_KEY'
private_key='API_SECRET'
private_key = base64.b64decode(private_key)

a = 1
while True:
    stamp = str(int(time.time())*1000)
    data = "{}{}".format(public_key, stamp).encode('utf-8')
    signature = hmac.new(private_key, data, hashlib.sha256).digest()
    signature = base64.b64encode(signature)
    headers={"X-PCK": public_key,"X-Stamp": stamp,"X-Signature": signature, "Content-Type":"application/json"}

    params={}
    resp = requests.get(url=url, headers=headers, json=params)
    result = resp.json()
    print('\n %s %s\n' %(a , strftime("%Y-%m-%d %H:%M:%S", gmtime())))
    print(result)
    a += 1
    if a == 100:
        break
```

**Comment by abduramann** [comment]
Aslında her sorguda nonce değeri değişiyor fakat zaman kısa olduğu için programda ufak zaman kaymaları oluyor olabilir, şimdilik çok problem olmuyor ama diğeri (internal server) konusunda yorumunuz var mı? sizin bakım çalışmanızdan veya arızadan ötürü ise problem değil fakat benim bir hatam varsa düzeltsem iyi olur, çünkü uygulamamı işlevsiz hâle getiriyor. Teşekkürler.

**Comment by onurgozupek** [comment]
500 - Internal Error, sunucu kaynaklı hatalarda alabileceğiniz bir hata mesajı. Anlık bir sorun yaşanmış olabilir. Sistemde kayıtlı e-posta adresinizden destek@btcturk.com adresine GithubIssue#160 kodunu içeren bir e-posta gönderebilirseniz ilgili saatlerdeki sistem kayıtlarını inceleyip bilgi verebiliriz.

**Comment by abduramann** [comment]
Size göndermeden önce inceledim, hata sık tekrarlamıyormuş, yanlış error handling yaptığım için maximum recursion'a takılıyormuşum. Sorunu çözdüm, teşekkürler.
