### ISSUE TITLE
testnet yükleme

### ISSUE THREAD

**Issue by atakavci** [BTCTrader/broker-api-docs#162]
Merhaba ,

test ortamında web sayfası ve API üzerinden coin yada tl yüklemek için ne yapmam gerektiğini bulamadım.
https://github.com/BTCTrader/broker-api-docs/blob/master/README-pro.md
adresinde TESTNET kullanımı ile ilgili ifadeler ve bu linkler var;
[BTCTurk Test] (https://pro-dev.btcturk.com/) to create your test API keys.
[BTCTurk Test API] (https://api-dev.btcturk.com/)

Ancak TESTNET i test platformunda bulamıyorum. sanal para yükleme ve işlem yapma adımlarında yardımcı olabilecek var mı?

**Comment by onurgozupek** [comment]
Merhaba, testnet için yükleme talebinizi Testnet için kaydolduğunuz eposta adresiyle birlikte  destek@btcturk.com adresine gönderirseniz hesabınıza Bitcoin ve TL tanımlanabilir.

**Comment by atakavci** [comment]
çok teşekkürler Onur Bey.

**Comment by demirhancosku** [comment]
@onurgozupek 15 Şubat 2020'de #347978 numaralı destek talebiyle Tether ya da Try cinsinden deposit talebi oluşturdum fakat hala işleme alınmadı.

TestNet ortamında hesap oluştururken belirli bir miktarın otomatik olarak yüklenmesi geliştiricilerin günlerce deposit için beklemesinin önüne geçecektir.

**Comment by onurgozupek** [comment]
Merhaba, hesabınızı kontrol eder misiniz? Yükleme yapılmış. Geliştirme sitesi, sürekli değiştiği için adresler otomatik oluşmuyor. Bu nedenle adres oluşturup talepte bulunmanız gerekiyor.

**Comment by demirhancosku** [comment]
> Merhaba, hesabınızı kontrol eder misiniz? Yükleme yapılmış. Geliştirme sitesi, sürekli değiştiği için adresler otomatik oluşmuyor. Bu nedenle adres oluşturup talepte bulunmanız gerekiyor.

Şimdi kontrol ettiğimde yükenmiş olduğunu gördüm, ilgi ve alakanız için teşekkürler.

**Comment by aktasr** [comment]
@onurgozupek Onur bey Merhaba,
Bu sayfada vermiş olduğunuz bilgiler eşliğinde 03.03.2021 tarihinde testnet hesabıma bakiye yüklenmesi için talep oluşturdum fakat henüz hesabıma bir yükleme işlemi gerçekleşmedi. 
Destek ekibinden gelen mailde talebimin ilgili ekibe iletildiği belirtiliyor fakat üzerinden geçen zamana rağmen hesapta değişiklik göremedim. 
Talep numarası: 1748444

Uyguladığım adımlarda bir hata olma durumuna karşı, süreç hakkında bilgilendirebilirseniz sevinirim.

Teşekkürler,

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
