### ISSUE TITLE
Order status response in order submission request

### ISSUE THREAD

**Issue by iamsasan** [BTCTrader/broker-api-docs#164]
Hi. In most exchanges such as binance and coinbase whenever new order has been submit order status will return in response for continues approaches. for example they response FILLED,OPEN,PARTIALLY_FILLED.

But in your highTech exchange doesn't provide this opportunity. as a result developers have to send new request for old submitted order ('/api/v1/allOrders'). This way need a lots of time.

Is it possible for you to add this useful status in order submission ?

**Comment by onurgozupek** [comment]
Hi, if you are not placing a market order, our order matcher starts matching orders "after" they have been inserted. Which means, first you need to insert order successfully then it's being placed. Even if you are placing an order higher than best bid or lower than best ask your order has to inserted to the order book. So, you can send request to /api/v1/allOrders after placing your order for the status of your order.

**Comment by iamsasan** [comment]
Hi @onurgozupek 
Thanks for your explanation.But my issue is about market taker orders. For example : 
My order is buying 1 BTC for 7430.
Best sell of order book is 7420.

So with this situation I am market taker. When I place my order in your matching orders engine you can send status "FILLED" immediately in your response.

This status in place order request prevent second request for order status.

for more please have a brief look at binance API in below link: 
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade

Best regards

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
