### ISSUE TITLE
ETH_BTC ticker all values (ask,bid...) are 0.0

### ISSUE THREAD

**Issue by alialparslan** [BTCTrader/broker-api-docs#166]
https://api.btcturk.com/api/v2/ticker?pairSymbol=ETH_BTC
`{"data":[{"pair":"ETHBTC","pairNormalized":"ETH_BTC","timestamp":1579996808957.0,"last":0.0,"high":0.0,"low":0.0,"bid":0.0,"ask":0.0,"open":0.0,"volume":0.0,"average":0.0,"daily":0.0,"dailyPercent":0.0,"denominatorSymbol":"BTC","numeratorSymbol":"ETH","order":0}],"success":true,"message":null,"code":0}`

**Comment by alialparslan** [comment]
I don't know why i closed this issue. This happened and you should be aware of it.
Despite success attribute is true, api returned 0 for all values. I don't know how long this persisted but probably this is happening time to time.

**Comment by alialparslan** [comment]
Also some pairs are missing from ticker (when called without any parameter) time to time.

**Comment by onurgozupek** [comment]
If any pair is missing from ticker, this means that pair didn't have trades in last 24h.

**Comment by onurgozupek** [comment]
I have double checked it the development team. If you request ticker without pairSymbol, you will get all results with trades in last 24h. If no trades for a pair, it won't be listed on all tickers. But if you request ticker with a pairSymbol, you'll get zero values if there are no trades in last 24h.

**Comment by alialparslan** [comment]
Thanks.
