### ISSUE TITLE
Test Api için coin yükleme

### ISSUE THREAD

**Issue by pheaselegen** [BTCTrader/broker-api-docs#167]
Merhaba #162 'de destek@btcturk.com'a mail atarsak test coinlerinin yükleneceği söyleniyordu. Maile cevap olarak:
_**Yardım masası olarak BTCTurk API ile ilgili teknik programlama desteği vermemekteyiz. Eğer programcı iseniz API yardım sayfamızdaki BTCTrader Github sayfasındaki linki kullanarak teknik ekibimizden Github üzerinden destek isteyebilirsiniz.**_
geldi. Yardımcı olursanız sevinirim.

**Comment by onurgozupek** [comment]
Merhaba, sanıyorum talebinizi yazılım desteği olarak algılamışlar. Talebinizle ilgili açılan destek talebini yanıtlayıp, test sistemine bakiye yüklenmesini istediğinizi, talebinizi Github'dan da paylaştığınızı iletebilir misiniz? Test sistemine kayıt olduğunuz e-posta adresinizi de iletin lütfen. Test sistemiyle destek ekibi değil yazılım ekibi ilgileniyor. Ancak yükleme talebinizi destek ekibine iletmeniz gerekiyor. Talebinizi ayrıca takip edeceğim...

**Comment by pheaselegen** [comment]
Mesajınız için teşekkürler. Şöyle bir cevap geldi.

*Merhaba *** Bey,*


*İletmiş olduğunuz bilgi için teşekkür ederiz. Talebiniz yazılım ekibimize
iletilmiştir. *

*İyi günler dileriz. *

**Comment by onurgozupek** [comment]
Merhaba, yüklemeniz yapılmış. Kontrol edebilir misiniz?

**Comment by pheaselegen** [comment]
Onur Bey mesajınız ve takibiniz için teşekkürler. Bana şöyle bir mesaj
gönderdiler.

*Test hesabınızın Yatırma sayfalarına  (BTC,ETH gibi)  giriş sağlamanızı
rica ederiz.*
*Kripto para adres oluşumu sonrası bakiyeniz yüklenecektir.*

Yatırma sayfasına geldiğimde "*Adres oluşturulamadı.*" hatası alıyorum ve
bakiye yüklenmiyor.

onurgozupek <notifications@github.com>, 27 Oca 2020 Pzt, 14:34 tarihinde
şunu yazdı:

**Comment by onurgozupek** [comment]
Litecoin ve Tether bakiyeleriniz yüklendi. Bu bakiyelerle Bitcoin alabilirsiniz. Yazılım ekibi adres hatasını kontrol ediyor. (Test sürümünde bu tarz hatalar görülebiliyor)

**Comment by pheaselegen** [comment]
Yüklendi. Teşekkürler, iyi çalışmalar...

onurgozupek <notifications@github.com>, 27 Oca 2020 Pzt, 18:16 tarihinde
şunu yazdı:
