### ISSUE TITLE
CCXT Library code deprecated

### ISSUE THREAD

**Issue by sadiuysal** [BTCTrader/broker-api-docs#168]
Hey, I wanted to use your API via CCXT library but i am getting errors. I deep down into code and found out that your CCXT library code (ccxt/btcturk.py) written according to your deprecated old API ticker. I started to change some part of it but it seems it is gonna take my time to fix this. I thought you may want to help me solving this issue since CCXT library is widely used global library by many crypto programs. I attached old file(btcturk.py) for your convenience. Thanks for your attention.
[btcturk.py.zip](https://github.com/BTCTrader/broker-api-docs/files/4124161/btcturk.py.zip)

**Comment by onurgozupek** [comment]
Hello, we will review the Python code you've sent and check the CCXT library as well.

**Comment by sadiuysal** [comment]
Thanks a lot, I am waiting for it.
