### ISSUE TITLE
yeni api alım satım emri girme

### ISSUE THREAD

**Issue by ahmedahmedo** [BTCTrader/broker-api-docs#169]
eski api'de alım satım yaparken OrderMethod=0 yapınca limit emir tipinden alım satım yapabiliyorduk. yeni api'de ise orderMethod "enum" formatında girdi istiyor. 
orderMethod: (enum) { "limit", "market" , "stopLimit" or "stopMarket"} 
derken post yaparken limit emir için
orderMethod=0'mı yazmam gerekiyor.

proglamlamaya biraz yabancıyım.
php ile eski versiyonda çalışan kodu yeni versiyona uyarlamaya çalışıyorum. bir tek emir girerken 'enum' denen kavramı tam anlayamadım.

**Comment by onurgozupek** [comment]
Yeni API’da limit, market, stop_market veya stop_limit değerlerini string (tırnak içinde) göndermelisiniz.

**Comment by ahmedahmedo** [comment]
eski api'de kullandığım php postu kabaca şöyle;
` curl_setopt($ch, CURLOPT_POSTFIELDS, 'OrderMethod=0&OrderType=0&totalPrecision=00&amountPrecision=1'&&pricePrecision=99&triggerPrice=0&triggerPricePrecision=00&DenominatorPrecision=2&price=1&amount=1&PairSymbol=ETHTRY');
`
yani gerekli parametreleri yazıp eşittir işaretini koyarak ilgili rakamı koyuyordum. (misal orderMethod=0 olursa limit order yapıyordu.

yeni api'de kullandığım php kodu ise şöyle;
`        curl_setopt($ch, CURLOPT_POSTFIELDS, "quantity=1&price=1&orderMethod=limit&orderType=buy&pairSymbol=ETHTRY");
`
yeni api'de misal pairSymbol parametresini string olarak istiyor ve oraya ETHTRY yazıyorum lakin orderType ve orderMethod'a parametre "enum" denen şekilde istiyor ve  "buy" ile "limit" girince şöyle bir hata çıkıyor
` Array
(
    [data] => Array
        (
            [] => Array
                (
                    [0] => Unexpected character encountered while parsing value: q. Path '', line 0, position 0.
                )

        )

    [success] => 
    [message] => INVALID_REQUEST
    [code] => 1
) `

ayrıca eski Api'nin php ile kodlanmış bir örneği var, yeni api için de benzer bir çalışma yapılabilir mi acaba?

**Comment by resulcaglayan** [comment]
Yeni api için php kodunuzu şu şekilde güncelleyip deneyin.

parse_str('quantity=1&price=1&orderMethod=limit&orderType=buy&pairSymbol=ETHTRY', $parsed);
curl_setopt($ch, CURLOPT_POSTFIELDS, $parsed);

**Comment by ahmedahmedo** [comment]
> Yeni api için php kodunuzu şu şekilde güncelleyip deneyin.
> 
> parse_str('quantity=1&price=1&orderMethod=limit&orderType=buy&pairSymbol=ETHTRY', $parsed);
> curl_setopt($ch, CURLOPT_POSTFIELDS, $parsed);

maalesef yine olmuyor. bu defa da şöyle bir hata çıkıyor. 

[![image](https://i.hizliresim.com/Z5rj00.png)](https://hizliresim.com/Z5rj00)

benim satın alma eylemi için kullandığım fonksiyon şöyle.
bir yerlerde yanlış yapıyorum ama bulamıyorum bir türlü

[![image](https://i.hizliresim.com/nbv94a.png)](https://hizliresim.com/nbv94a)

yeni api'nin tüm fonksiyonlarını kullanabiliyorum. balanca, order book, order cancel vs. hepsi oluyor ama emir girmeyi bir türlü yapamadım. eski api'de oluyordu ama yeni api'ye bir türlü uyarlamadım. 

yapmak istediğim aslında çok basit. php kodu ile belirlediğim tutarda belirlediğim miktarda Eth alım emrini girecek bir fonksiyon yazmak.

**Comment by onurgozupek** [comment]
Merhaba, PHP kodu için https://github.com/onurgozupek/btcturkpro örnek kodlarına gözatabilirsiniz. BtcTurk | PRO API dokümantasyonunun C#, Python ve PHP örnekleri içeren yeni versiyonu önümüzdeki hafta yayınlanacak.

**Comment by resulcaglayan** [comment]
> yapmak istediğim aslında çok basit. php kodu ile belirlediğim tutarda belirlediğim miktarda Eth alım emrini girecek bir fonksiyon yazmak.

Senin vermiş olduğun parametreleri kullandığımda şu hatayı veriyor: {"success":false,"message":"FAILED_MIN_TOTAL_AMOUNT","code":1123}

Kullandığım kodlar şöyle;
`		function curl($url, $headers, $post=0, $params='') {
		    $ch = curl_init();
		    curl_setopt($ch, CURLOPT_URL, $url);
		    curl_setopt($ch, CURLOPT_PORT, 443);
		    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS, $params);
		    curl_setopt($ch, CURLOPT_POST, $post);
		    curl_setopt($ch, CURLOPT_TIMEOUT, 30);
		    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		    $result = curl_exec($ch);
		    curl_close($ch);
		    return $result;		
		}

		$apiKey = "******";
		$apiSecret = "*******";
		$message = $apiKey.(time()*1000);
		$signatureBytes = hash_hmac('sha256', $message, base64_decode($apiSecret), true);
		$signature = base64_encode($signatureBytes);
		$nonce = time()*1000;
		$headers = array(
		  'X-PCK: '.$apiKey,
		  'X-Stamp: '.$nonce,
		  'X-Signature: '.$signature,
		  'Content-Type: application/json',
		);
		$params = array(
			'quantity' => 1, 
			'price' => 1, 
			'orderMethod' => 'limit', 
			'orderType' => 'buy', 
			'pairSymbol' => 'ETHTRY', 
		);
		$buyer = curl("https://api.btcturk.com/api/v1/order", $headers, 1, json_encode($params));
		print_r($buyer);`

**Comment by resulcaglayan** [comment]
> 
> 
> Merhaba, PHP kodu için https://github.com/onurgozupek/btcturkpro örnek kodlarına gözatabilirsiniz. BtcTurk | PRO API dokümantasyonunun C#, Python ve PHP örnekleri içeren yeni versiyonu önümüzdeki hafta yayınlanacak.

Onur hocam market alış ve market satış kodlarıda paylaşırsanız faydalı olacaktır. Ör: BTCTRY 0.01 buy/sel gibi

**Comment by onurgozupek** [comment]
@resulcaglayan kodunuzu "acilen" günceller misin? API anahtarlarınızı paylaşmışsınız!

**Comment by bedri** [comment]
@resulcaglayan api key ve secret'ınızı değiştiriniz!!!

**Comment by resulcaglayan** [comment]
Geçersiz anahtarlar mevcut. Hassasiyet için teşekkürler :)

**Comment by ahmedahmedo** [comment]
> Merhaba, PHP kodu için https://github.com/onurgozupek/btcturkpro örnek kodlarına gözatabilirsiniz. BtcTurk | PRO API dokümantasyonunun C#, Python ve PHP örnekleri içeren yeni versiyonu önümüzdeki hafta yayınlanacak.

örnek kodu kendi sistemime uyarladım. teşekkürler.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
