### ISSUE TITLE
invalid model hatası

### ISSUE THREAD

**Issue by ahmedahmedo** [BTCTrader/broker-api-docs#17]
alış veya satış emri verdiğimde şöyle bir hata alıyorum 

[code] => 400
[message] => Emir girilemedi. Lütfen tekrar deneyiniz ve hata tekrar ederse bize ulaşınız. Hata kodu: Invalid model

yetkilendirme yapılmış bir şekilde(balance bilgileri görünüyor) post olarak .../api/exchange adresine 
OrderMethod
OrderType
Price
Amount
PairSymbol

bilgilerini post ediyorum. 
eksik girdiğim bir bilgi var mı acaba.

**Comment by ozanyurt** [comment]
Invalid model hatası biraz sığ bir hata olmuş. Mesajların iyileştirilmesi ile ilgili çalışmaya başladık. Şu anda modelin istediği bütün parametreleri aşağı yazıyorum. Bunları gönderirseniz sorunsuz çalışması gerekli. Önerilerinizi de bekliyoruz her zamanki gibi.

("total", "104"),
("totalPrecision", "60"),
("amount", "0"),
("amountPrecision", "005"),
("price", "20799"),
("pricePrecision", "95"),
("orderMethod", "1"),
("orderType", "0"),
("triggerPrice", "0"),
("triggerPricePrecision", "00"),
("DenominatorPrecision", "2"),
("PairSymbol", "BTCTRY")

Bu parametleri eksiksiz göndermeyi dener misimiz?

**Comment by ahmedahmedo** [comment]
Verdiğiniz değerler market Order için sanırım. Limit Order için bu kadar parametreye gerek var mı acaba?

**Comment by ozanyurt** [comment]
Evet validation bütün alanları istiyor maalesef. Onda düzeltmeler yapıp dökümanı güncelleyeceğiz. Şimdilik aşağıda her tip için parametleri yazıyorum. Yani emir tiplerine göre parametlerin bazılarını sıfır ya da boş gönderiyoruz.

**Market - Alış**
``` new KeyValuePair<string, string>("total", "104"),
                    new KeyValuePair<string, string>("totalPrecision", "60"),
                    new KeyValuePair<string, string>("amount", "0"),
                    new KeyValuePair<string, string>("amountPrecision", "005"),
                    new KeyValuePair<string, string>("price", "20799"),
                    new KeyValuePair<string, string>("pricePrecision", "95"),
                    new KeyValuePair<string, string>("orderMethod", "1"),
                    new KeyValuePair<string, string>("orderType", "0"),
                    new KeyValuePair<string, string>("triggerPrice", "0"),
                    new KeyValuePair<string, string>("triggerPricePrecision", "00"),
                    new KeyValuePair<string, string>("DenominatorPrecision", "2"),
                    new KeyValuePair<string, string>("PairSymbol", "BTCTRY"),
```

**Market - Satış**
``` new KeyValuePair<string, string>("total", "104"),
                    new KeyValuePair<string, string>("totalPrecision", "60"),
                    new KeyValuePair<string, string>("amount", "0"),
                    new KeyValuePair<string, string>("amountPrecision", "005"),
                    new KeyValuePair<string, string>("price", "20799"),
                    new KeyValuePair<string, string>("pricePrecision", "95"),
                    new KeyValuePair<string, string>("orderMethod", "1"),
                    new KeyValuePair<string, string>("orderType", "1"),
                    new KeyValuePair<string, string>("triggerPrice", "0"),
                    new KeyValuePair<string, string>("triggerPricePrecision", "00"),
                    new KeyValuePair<string, string>("DenominatorPrecision", "2"),
                    new KeyValuePair<string, string>("PairSymbol", "BTCTRY"), 
```

**Limit - Alış**
``` new KeyValuePair<string, string>("total", "104"),
                    new KeyValuePair<string, string>("totalPrecision", "60"),
                    new KeyValuePair<string, string>("amount", "0"),
                    new KeyValuePair<string, string>("amountPrecision", "005"),
                    new KeyValuePair<string, string>("price", "20799"),
                    new KeyValuePair<string, string>("pricePrecision", "95"),
                    new KeyValuePair<string, string>("orderMethod", "0"),
                    new KeyValuePair<string, string>("orderType", "0"),
                    new KeyValuePair<string, string>("triggerPrice", "0"),
                    new KeyValuePair<string, string>("triggerPricePrecision", "00"),
                    new KeyValuePair<string, string>("DenominatorPrecision", "2"),
                    new KeyValuePair<string, string>("PairSymbol", "BTCTRY"),
```

**Limit - Satış**
``` new KeyValuePair<string, string>("total", "104"),
                    new KeyValuePair<string, string>("totalPrecision", "60"),
                    new KeyValuePair<string, string>("amount", "0"),
                    new KeyValuePair<string, string>("amountPrecision", "005"),
                    new KeyValuePair<string, string>("price", "20799"),
                    new KeyValuePair<string, string>("pricePrecision", "95"),
                    new KeyValuePair<string, string>("orderMethod", "3"),
                    new KeyValuePair<string, string>("orderType", "1"),
                    new KeyValuePair<string, string>("triggerPrice", "20650"),
                    new KeyValuePair<string, string>("triggerPricePrecision", "00"),
                    new KeyValuePair<string, string>("DenominatorPrecision", "2"),
                    new KeyValuePair<string, string>("PairSymbol", "BTCTRY"),
```

**Comment by ahmedahmedo** [comment]
- son örneğiniz sanırım Stop market order örneği olması lazım, limit - satış yazmışsınız.
- limit alış ve satışta 'amount' değerini 0 göndermek mantıksız olmaz mı, hangi miktarda alıp satacağız.
-cancelOrder da order id'i post ederek emri iptal edebiliyorum. ama sell ve buy işleminde post olarak ne yazarsam yazayım aynı hata dönüyor. 

hatanın sebebi post edilen değerlerden ziyade başka bir uyumsuzluktan kaynaklanıyor olsa gerek.

**Comment by BTCTraderAdmin** [comment]
Kullandığınız kodları ve parametreleri gönderebilir misiniz? Bir inceleyelim

**Comment by ahmedahmedo** [comment]
$message=$APIKey.time();
$signatureBytes = hash_hmac('sha256', $message, base64_decode($privateKey), TRUE);
$signature=base64_encode($signatureBytes);
function authGetsell($uri, $price, $amount) {
        $url=$GLOBALS['baseURL'].$uri;
        $nonce=time();
        $headers=array(
                'X-PCK: '.$GLOBALS['APIKey'],
                'X-Stamp: '.$nonce,
                'X-Signature: '.$GLOBALS['signature']
        );
        $ch=null;
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($ch, CURLOPT_POSTFIELDS, 'OrderMethod=1&
                                              OrderType=1&
                                              totalPrecision=0&
                                              amountPrecision=0&
                                              pricePrecision=0&
                                              triggerPrice=0&
                                              triggerPricePrecision=0&
                                              DenominatorPrecision=0&
                                              price='.$price.'&
                                              amount='.$amount.'&
                                              PairSymbol=BTCTRY');


        $result=curl_exec($ch);
        curl_close($ch);
        return json_decode($result, true);
}


- fonksiyona uri, amount ve price değerlerini gönderip çalıştırıyorum. cancel yaparken aynı fonksiyona id gönderip çalıştırınca iptal işlemi oluyor.

**Comment by nepnesomao** [comment]
Precision parametrelerini default olarak 00 vermeniz gerekiyor. DenominatorPrecision parametresini de default 2 olarak gönderiniz.

**Comment by ahmedahmedo** [comment]
parametreleri değiştirdim hala aynı hatayı veriyor.
balance, openorder, cancelorder vs. tüm fonksiyonlar çalışırken sadece alış satış yapamıyorum.
parametrelere mahmut dahi yazsam aynı hatayı alıyorum :)

**Comment by yunusseemre** [comment]
limit buy işlemi için girdiğim parametreler şu şekilde 

 params = [NSMutableDictionary dictionaryWithDictionary: @{
                                                                      @"Amount":[order.amount stringValue],
                                                                       @"Price":[order.price stringValue],
                                                                       @"PairSymbol":@"BTCTRY",
                                                                       @"total":@"",
                                                                       @"totalPrecision":@"00",
                                                                       @"pricePrecision":@"00",
                                                                       @"amountPrecision":@"00000000",
                                                                       @"triggerPricePrecision":@"00",
                                                                       @"triggerPrice":@"0",
                                                                       @"orderMethod":@"0",
                                                                       @"orderType":@"0",
                                                                       @"DenominatorPrecision":@"2",
                                                                       @"NumeratorPrecision":@"8"} ];

fakat ayni hatayı almaktayım:
    code=400 
  emir girilemedi..Lütfen tekrar deneyiniz ve hata tekrar ederse bize ulaşın.Hata kodu:"Invalid model"

**Comment by ahmedahmedo** [comment]
alış veya satış girerken değerleri şöyle girmeniz gerekiyor sanırım;
misal 1.05 miktarında 23.5000 tl fiyattan alış emri vermek istiyorsunuz.
amount :1
amountPrecision :05
price : 23500
girmeniz gerek.

**Comment by erdenertamer** [comment]
Merhaba,

Parametreleri tam olarak belirttiğiniz şekilde girdiğimde 'code': 400 hatası alıyorum. 

Limit satış için verdiğim parametreler aşağıdaki gibi.

{'total': 104, 'totalPrecision': 60, 'amount': 0, 'amountPrecision': 5, 'Price': 30000, 'pricePrecision': 0, 'orderMethod': 0, 'orderType': 0, 'triggerPrice': 0, 'triggerPricePrecision': 00, 'DenominatorPrecision': 2, 'PairSymbol': 'BTCTRY'}

Hata detayı: 'message': 'Emir girilemedi. Lütfen tekrar deneyiniz ve hata tekrar ederse bize ulaşınız. Hata kodu: Invalid model'

Yardımlarınız bekliyorum.

Teşekkürler,

**Comment by nepnesomao** [comment]
{'total': 104, 'totalPrecision': 60, 'amount': 0, 'amountPrecision': 50000000, 'Price': 30000, 'pricePrecision': 00, 'orderMethod': 0, 'orderType': 0, 'triggerPrice': 0, 'triggerPricePrecision': 00, 'DenominatorPrecision': 2, 'PairSymbol': 'BTCTRY'}

Şeklinde gönderiniz.

**Comment by erdenertamer** [comment]
Aşağıdaki structureda sorun var mıdır? Aynı hatayı precision parametrelerini değiştirsem de alıyorum.

https://www.btcturk.com/api/exchange 
{
'total': 104, 
'totalPrecision': 60, 
'amount': 0, 
'amountPrecision': 50000000, 
'Price': 20000, 
'pricePrecision': 10, 
'orderMethod': 0, 
'orderType': 1, 
'triggerPrice': 0, 
'triggerPricePrecision': 00, 
'DenominatorPrecision': 2, 
'PairSymbol': 'BTCTRY'
} 
{
'X-PCK': '0bbf0310-17b9-41e9-8a49-54e645114gef', 
'X-Stamp': '1509641022', 
'X-Signature': 'I9pCSKDg7YJTDSG4/M3AxCtkzeSVtjUT4f2X/hJO01o='
}

Teşekkürler,

**Comment by alipolatbtc** [comment]
Çalışan Örnekler : 

Limit Sell  : 

QString strPost = "totalPrecision=60&Amount=0&amountPrecision=001&price=50000&pricePrecision=51&orderMethod=0&orderType=1&triggerPrice=0&triggerPricePrecision=00&DenominatorPrecision=2&PairSymbol=BTCTRY";

Cevap :  

{"id":"363165","datetime":"2017-11-03T00:16:18.3092298Z","type":"Sell","price":50000.51,"amount":0.001,"pairsymbol":null}

--------------------------------------------

Limit Buy

QString strPost = "totalPrecision=60&Amount=0&amountPrecision=1&price=20000&pricePrecision=95&orderMethod=0&orderType=0&triggerPrice=0&triggerPricePrecision=00&DenominatorPrecision=2&PairSymbol=BTCTRY";

Cevap : 

{"id":"363122","datetime":"2017-11-03T00:11:43.2921448Z","type":"Buy","price":20000.95,"amount":0.1,"pairsymbol":null}

---------------------------------------------

*** NOT : ozanyurt 'un verdiği Limit Sell örneğinde hata var. 
new KeyValuePair<string, string>("orderMethod", "3"), deki değer 3 değil 0 olmalı.

**Comment by nepnesomao** [comment]
new KeyValuePair<string, string>("orderMethod", "3") orderMethod 3 değerinin karşılığı "Stop Limit" tir

**Comment by oxygen32** [comment]
alış satış emirlerini post etmek için herşeyi alipolatbtc  gönderisine göre yapmama rağmen al emirlerinde sıkıntı yaşıyorum limit order yerine market order fiyatından alış yapıyor. Aynı sorun sell limit orderda yok mesela.
buy limit order 
data={'totalPrecision': 60, 'amount': 0, 'amountPrecision': 1,
                                       'Price': 20000, 'pricePrecision': 95, 'orderMethod': 0,
                                       'orderType': 0, 'triggerPrice': 0, 'triggerPricePrecision': 00,
                                       'DenominatorPrecision': 2, 'PairSymbol': 'BTCTRY'}

sell limit order 
data={'totalPrecision': 60, 'amount': 0, 'amountPrecision': 001,
                                       'Price': 50000, 'pricePrecision': 51, 'orderMethod': 0,
                                       'orderType': 1, 'triggerPrice': 0, 'triggerPricePrecision': 00,
                                       'DenominatorPrecision': 2, 'PairSymbol': 'BTCTRY'}

[{u'price': 50000.51, u'id': u'608491', u'amount': 0.001, u'datetime': u'2017-11-13T00:52:14.937', u'type': u'SellBtc', u'pairsymbol': u'BTCTRY'}]

**Comment by kadirgunhiz** [comment]
## **Emir girilemedi. Minimum emir toplamının altında emir girdiniz.**
Api ile **alış** yapmaya çalıştığımda böyle bir hata ile karşılaşıyorum? Neden böyle bir hata veriyor sizce? Post Methodum;

> totalPrecision=60&amount=0&amountPrecision=0050&price=29790&pricePrecision=00&orderMethod=1&orderType=0&triggerPrice=0&triggerPricePrecision=00&DenominatorPrecision=2&PairSymbol=BTCTRY

**Comment by silenca** [comment]
## Emir girilemedi. Lütfen tekrar deneyiniz ve hata tekrar ederse bize ulaşınız. Hata kodu: Invalid model

Dear support, please help me to understand what is the problem with my market order. 

Request:
POST /api/exchange HTTP/1.1\r\nX-PCK: *****\r\nX-Stamp: 1518627397\r\nX-Signature: DDQsWir/nZIrpsvDX1zJcsZNifNSKWMrg+fa5AT6L/s=\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 122\r\nHost: www.btcturk.com\r\nConnection: close\r\n\r\nPrice=0&PricePrecision=0&Amount=0&AmountPrecision=0&Total=0&TotalPrecision=001&PairSymbol=BTCTRY&OrderMethod=1&OrderType=1

Response:
{ error:
  { code: 400,
    message: 'Emir girilemedi. Lütfen tekrar deneyiniz ve hata tekrar ederse bize ulaşınız. Hata kodu: Invalid model' } }

**Comment by suleymanbyzt** [comment]
Merhaba,

Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
