### ISSUE TITLE
Limit Satınalma

### ISSUE THREAD

**Issue by Foxalo** [BTCTrader/broker-api-docs#171]
Merhabalar,
Limit satın alma kısmında FAILED_LIMIT_ORDER hatası alıyorum nedendir acaba?
XLM'den USDT Satmaya çalışıyorum.

**Comment by onurgozupek** [comment]
Merhaba, muhtemelen parametrelerden birini eksik ya da hatalı gönderiyorsunuz. /api/v1/order uç noktasına gönderdiğiniz parametreleri kontrol edebilir misiniz?

pairSymbol => "XLMUSDT", quantity => "1000", price => "0.0712", orderMethod => "limit", orderType => "buy", stopPrice => 0

Ayrıca emrinizin toplam değerinin ( quantity * price ) 5USDT'den büyük olup olmadığını da kontrol edin lütfen.

**Comment by Foxalo** [comment]
Teşekkürler.
