### ISSUE TITLE
Submit Order'da ORDER_METHOD_NOT_SUPPORTED hatası

### ISSUE THREAD

**Issue by outlier-1** [BTCTrader/broker-api-docs#173]
Merhaba, market order' ı yapmak için oluşturduğum bir fonksiyonda dökümantasyonda belirtilen 
'orderMethod' parametresini 'market' yaparsam 400 Response code ve ORDER_METHOD_NOT_SUPPORTED mesajı alıyorum. 

Dökümantasyonda order method'larda  { "limit", "market" , "stopLimit" or "stopMarket"} enumlarının desteklendiği yazıyor. Diğer method enumları için böyle bir hata almıyorum fakat orderMethod'u 'market' yapınca dediğim hatayı alıyorum.

Örnek teşkil etmesi açısından parametreler:

params = {'quantity': 100,  'newOrderClientId': 'random uuid',
                  'orderMethod': 'market', 'orderType': 'sell', 'pairSymbol': 'XLM_USDT'}

Aldığım Http Response: 

b'{"success":false,"message":"ORDER_METHOD_NOT_SUPPORTED","code":1134}'

Bu konuda API'dan kaynaklı bir sıkıntı varsa çözebilir misiniz? Dökümantasyonda sıkıntı olabilir diye 'Market', 'MARKET' gibi parametreler de denedim fakat fayda etmedi.

İyi çalışmalar dilerim

**Comment by onurgozupek** [comment]
Piyasa emri tüm kripto/kripto işlem çiftlerinde kullanılamıyor. Hangi emir tiplerinin kullanılabileceğini https://api.btcturk.com/api/v2/server/exchangeinfo uçnoktasından kontrol edebilirsiniz. XLMUSDT işlem çiftinde sadece **limit** ve **stop_limit** emir gönderebilirsiniz.

**Comment by outlier-1** [comment]
Cevabınız için teşekkürler.
