### ISSUE TITLE
30 günlük hacim'e api vasıtasıyla ulaşmak mümkün mü?

### ISSUE THREAD

**Issue by ahmedahmedo** [BTCTrader/broker-api-docs#174]
30 günlük hacim'e api vasıtasıyla ulaşmak mümkün mü?

**Comment by ocinbat** [comment]
Merhaba,

Aşağıdaki request son 30 günlük BTCTRY işlem çiftindeki trade bilgilerini dönüyor.

`https://api.btcturk.com/api/v2/ohlc?pairSymbol=BTCTRY&last=30`

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
