### ISSUE TITLE
V2 Price scale Api dokumani ile https://api.btcturk.com/api/v2/server/exchangeinfo  adresinden gelen veriler tutarli degil!

### ISSUE THREAD

**Issue by afaslan** [BTCTrader/broker-api-docs#176]
BTC/TRY , ETH/TRY gibi bazi paritelerde ondalikli kismin hassasiyeti 

https://api.btcturk.com/api/v2/server/exchangeinfo 

linkinden elde  edilen bilgiyle tutarli degil. 
Ornegin: BTC/TRY precision=2 gelirken gercekte bu deger api tarafindan 0 dan baska kabul edilmiyor. . Ve bu bilgi api dokumaninda dogru girilmis. Ama yukardaki link ile bu degerleri yazilim ile alip api'de kullaninca, api hata veriyor. 

**Dokumandaki** bilgi: Gercekte calsiyor:
![image](https://user-images.githubusercontent.com/10774895/75150398-53cb8d00-5715-11ea-9e82-d99d2b229cfd.png)

**https://api.btcturk.com/api/v2/server/exchangeinfo** linkinde elde edilen degerler: Calismiyor.
![image](https://user-images.githubusercontent.com/10774895/75150486-86758580-5715-11ea-8950-27c9bbbdf539.png)

Api dokumani ile https://api.btcturk.com/api/v2/server/exchangeinfo  adresinden gelen veriler tutarli olmali.

**Comment by onurgozupek** [comment]
Merhaba, https://api.btcturk.com/api/v2/server/exchangeinfo uçnoktasında hasFraction değişkeni kullanabilirsiniz. hasFraction false ise, denominator değeri sadece formatlama için kullanılıyor (örn. 1,500.00 veya 59,580,00 gibi) , fiyat girerken kullanamıyorsunuz. hasFraction true ise denominatorScale kullanılabiliyor. (Örn. 178,12 veya 1,87 gibi)
