### ISSUE TITLE
Market buy order FAILED_INVALID_QUANTITY_SCALE hatasi veriyor

### ISSUE THREAD

**Issue by afaslan** [BTCTrader/broker-api-docs#177]
Hatanin olusturulma sekli: 

BTC_TRY paritesinde 0.001 miktarlik market satis yapiyorum:
----------------------------------------------------------------------
Gonderilen parametreler: {"quantity":0.001,"price":59000,"newOrderClientId":"test","orderMethod":"market","orderType":"sell","pairSymbol":"BTCTRY"}
Sonuc: **Basarili**

BTC_TRY paritesinde 0.001 miktarlik market alis yapiyorum:
----------------------------------------------------------------------
Gonderilen parametreler: {"quantity":0.001,"price":59000,"newOrderClientId":"test","orderMethod":"market","orderType":"buy","pairSymbol":"BTCTRY"}
Sonuc: **1127: FAILED_INVALID_QUANTITY_SCALE**

**0.001 BTC_TRY satis yapilabilirken alis yapilamiyor.**

**Comment by onurgozupek** [comment]
Piyasa emri ile ödemek istediğiniz tutarı göndermelisiniz. Miktar gönderdiğinizde hata verecektir

**Comment by afaslan** [comment]
Diger borsalarda quantity her zaman miktari ifade ediyor. V2 de bu duzeltilmistir diye dusunmustum. 
Herkes kodlarini buna gore yazdigi icin degismesin boyle kalsin lutfen.
Yanliz V3 yapilirken bu durum duzeltirlirse iyi olacaktir.
