### ISSUE TITLE
ohlcdata Servisi Eski Bir Tarihi Gösteriyor

### ISSUE THREAD

**Issue by byazici** [BTCTrader/broker-api-docs#18]
Merhaba,

https://www.btcturk.com/api/ohlcdata?last=1
ile çağırdığımda;
```
{
Time: "2017-10-07T00:00:00",
Open: 15446.51,
High: 15600,
Low: 15350.86,
Close: 15420,
Volume: 52.74146484,
Average: 15514.78,
DailyChangeAmount: -0.17,
DailyChangePercentage: -26.51
}
```
Sonucunu alıyorum. Neden güncel tarih gelmiyor? 
Bende cache sorunu mu var diye postman ile de çağırdım güncel bilgiler gelmiyor.

**Comment by byazici** [comment]
Test ettim çalışıyor. Teşekkürler.

**Comment by byazici** [comment]
Şu an yine eski bir tarihi gösteriyor! Bu hata neden kaynaklanıyor?

**Comment by suleymanbyzt** [comment]
Merhaba,

Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
