### ISSUE TITLE
"message":"Unauthorized - Invalid Request","code":1037 error

### ISSUE THREAD

**Issue by bayvehbi** [BTCTrader/broker-api-docs#180]
Merhaba
Yeni apiye python ile bağlanmaya çalışıyorum fakat "{"success":true,"message":"Unauthorized - Invalid Request","code":1037}" şeklinde bir cevap alıyorum. Kullandığım kod aşağıdaki gibidir.

`import base64
import hashlib
import hmac
import requests
import json
apiKey = ""
apiSecret = ""

timeurl = "https://api.btcturk.com/api/v2/server/time"
timey = json.loads(requests.get(url=timeurl).text)
stamp = str(timey["serverTime"])
base_url = "https://api.btcturk.com"
endpoint = "/api/v1/openOrders"
url = base_url + endpoint
pair_symbol = "BTCTRY"
apiSecret = base64.b64decode(apiSecret)
print(stamp)
data = "{}{}".format(apiKey, stamp).encode('utf-8')
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": str(base64.b64encode(signature).decode('utf-8')), "Content-Type": "application/json"}
params = {"pairSymbol": pair_symbol}
resp = requests.get(url=url, headers=headers, params=params, data=data)

print(resp.content)`

**Comment by onurgozupek** [comment]
Şu kodu deneyebilir misiniz? (Zamanı API sunucusundan anlık alamıyor olabilirsiniz. Kendi sunucunuzdaki zaman değerini kullanabilirsiniz)

```python
import base64
import hmac
import hashlib
import requests
import json
import time
import time

def authenticate():
    public_key = API_KEY
    private_key = API_SECRET
    private_key = base64.b64decode(private_key)
    stamp = str(int(time.time())*1000)
    data = "{}{}".format(public_key , stamp).encode('utf-8')
    signature = hmac.new(private_key , data , hashlib.sha256).digest()
    signature = base64.b64encode(signature)
    headers = {"X-PCK":public_key , "X-Stamp":stamp , "X-Signature":signature , "Content-Type":"application/json"}
    return headers

pairSymbol = "BTCTRY"
url = "https://api.btcturk.com/api/v1/openOrders"
params = { "pairSymbol" : pairSymbol }
resp = requests.get(url=url , headers=authenticate() , params=params)
result = resp.json()
print(result)

```

**Comment by onurgozupek** [comment]
Kendi kodunuzda HMAC doğrulamayı şu şekilde düzeltirseniz, işlem yapabilirsiniz.

```python
import base64
import hashlib
import hmac
import requests
import json

apiKey = API_KEY
apiSecret = API_SECRET

timeurl = "https://api.btcturk.com/api/v2/server/time"
timey = json.loads(requests.get(url=timeurl).text)
stamp = str(timey["serverTime"])
base_url = "https://api.btcturk.com"
endpoint = "/api/v1/openOrders"
url = base_url + endpoint
pair_symbol = "BTCTRY"
apiSecret = base64.b64decode(apiSecret)
data = "{}{}".format(apiKey , stamp).encode('utf-8')
signature = hmac.new(apiSecret , data , hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK":apiKey , "X-Stamp":stamp , "X-Signature":signature , "Content-Type":"application/json"}
params = {"pairSymbol": pair_symbol}
resp = requests.get(url=url, headers=headers, params=params, data=data)
print(resp.content)
```

**Comment by bayvehbi** [comment]
söylediğiniz gibi sorun çözüldü teşekkürler
