### ISSUE TITLE
FAILED_ORDER_WITH_OPEN_ORDERS

### ISSUE THREAD

**Issue by emrahtopcu** [BTCTrader/broker-api-docs#181]
Merhaba, limit sell göderirken böyle bir hata alıyorum.

result = {{
  "success": false,
  "message": "FAILED_ORDER_WITH_OPEN_ORDERS",
  "code": 1122
}}

birde bu hata mesajları ile ilgili bir döküman varmıdır ?

İyi çalışmalar.

**Comment by onurgozupek** [comment]
Bakiyenizden fazla tutarda satış emri giriyorsunuz (veya önceki emriniz iptal olmadığı için satmaya çalıştığınız tutar blokeli)

Açık emirlerinizi ve serbest bakiyelerinizi kontrol edebilir misiniz?
