### ISSUE TITLE
StatusCode: 401, ReasonPhrase: 'Unauthorized'

### ISSUE THREAD

**Issue by alsanf** [BTCTrader/broker-api-docs#182]
Merhaba,
btcturk pro'dan aldigim api anahtari ile v1 servisleri kullanamiyormuyuz? btcturk'de de api anahtari alacagim menu kaldirilmis sanirim.
asagidaki kod blogu ile  authentication bilgisi gonderiyorum.

                if (requiresAuthentication)
                {
                    client.DefaultRequestHeaders.Add("X-PCK", _publicKey);
                    var stamp = GetStamp();
                    client.DefaultRequestHeaders.Add("X-Stamp", stamp.ToString(CultureInfo.InvariantCulture));
                    var signature = GetSignature(stamp);
                    client.DefaultRequestHeaders.Add("X-Signature", signature);
                    //client.DefaultRequestHeaders.TryAddWithoutValidation( "Content-Type", "application/json" );
                }

**Comment by onurgozupek** [comment]
Daha önce BtcTurk.com'dan API anahtarı oluşturduysanız, BtcTurk | PRO için kullanabilirsiniz veya BtcTurk | PRO'da Hesap > API Erişimi sayfasından yeni API anahtarı oluşturabilirsiniz.

hmac doğrulamayı yaparken timestamp verisinin milisaniye (13 karakter) olduğundan ve sunucu saatinin API sunucusu saatiyle aynı olduğundan emin olun. (Sunucu saatini https://api.btcturk.com/api/v2/server/time veya https://api.btcturk.com/api/v2/server/exchangeinfo uçnoktasından kontrol edebilirsiniz)

**Comment by alsanf** [comment]
sorun stamp uretme seklindeymis.
asagidaki sekilde uretince sorun duzeldi.
tesekkurler.

var stamp = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeMilliSeconds();
