### ISSUE TITLE
yurtdışı IP'den request yapınca 403 hatası veriyor.

### ISSUE THREAD

**Issue by satoshin-akamoto** [BTCTrader/broker-api-docs#184]
API erişiminizin IP kısıtlaması var mı? Türkiye IP adresi ile çalışmakta, ancak yurt dışı IP requestleri 403 hatası geri dönmekte.

Kullandığım kod:
```
def authenticate():
    public_key = API_KEY
    private_key = API_SECRET
    private_key = base64.b64decode(private_key)
    stamp = str(int(time.time())*1000)
    data = "{}{}".format(public_key , stamp).encode('utf-8')
    signature = hmac.new(private_key , data , hashlib.sha256).digest()
    signature = base64.b64encode(signature)
    headers = {"X-PCK":public_key , "X-Stamp":stamp , "X-Signature":signature , "Content-Type":"application/json"}
    return headers


url = "https://api.btcturk.com/api/v1/users/balances"

resp = requests.get(url=url , headers=authenticate())
data = resp.json()

print(data)
```

Hata mesajında 
"access denied | api.btcturk.com used Cloudflare to restrict access"

Dökümanda belirtilen req/100ms limitini aşmadım. Ancak Cloudflare'nin daha sınırlı bir limiti olabilir.
Bu durumda API dokümanına Cloudflare request limitlerini koymak daha uygun olabilir.

İyi çalışmalar dilerim.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
