### ISSUE TITLE
Web sitem için kripto para ile ürün alım satım programı lazım.

### ISSUE THREAD

**Issue by Aksaksaksaks** [BTCTrader/broker-api-docs#185]
Bir adet ticari web sitem var. Bunun için xrp ile alışveriş yapılabilecek, ilerleyen zamanlarda başka kripto paraların da konulabileceği bir API'ye ihtiyacım var. Bunun için bir kaç site buldum fakat güven vermediler. Yardımcı olabilir misiniz?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
