### ISSUE TITLE
authentication sorunu

### ISSUE THREAD

**Issue by alsanf** [BTCTrader/broker-api-docs#186]
gözlemlediğim kadari ile son iki gundur zaman zaman farkli farkli servislerde(işlem listesi, account bilgileri okuma vs) 401.authentication hatalari aliyorum. sistemsel bir sorunmu var?

**Comment by alsanf** [comment]
401.authentication sorunu devam ediyor. genel bir sorun olup olmadigini ogrenebilir miyim?

**Comment by ocinbat** [comment]
Merhaba @firstcylon 

Hangi api versiyonunu kullanıyorsunuz?

v1 HMAC ile mi authentication yapıyorsunuz yoksa v2 OAuth ile mi?

**Comment by alsanf** [comment]
https://github.com/BTCTrader/broker-api-docs/issues/183

yukaridaki linkte acikladigim sekilde yapiyorum ..

**Comment by firstcylon** [comment]
yaklasik 00:30 itibari ile hicbir degisiklik yapmadan sorun duzeldi.
sisteminizde bir calisma mi var? yoksa benim kodlarim mi sorunlu ...

**Comment by alsanf** [comment]
sorun sistem saatindeki farktan kaynaklaniyormus.
ilginiz icin tesekkurler ..
