### ISSUE TITLE
Kullanılabilir bakiye hatası

### ISSUE THREAD

**Issue by emrahtopcu** [BTCTrader/broker-api-docs#187]
Merhaba, bağzı alım satım işlemlerinden sonra kullanılabilir bakiye güncellenmiyor. Satış işleminden gerçekleştikten sonra tl bakiye değişmiyor veya alış işlemi gerçekleştikten sonra btc bakiye değişmiyor. 
Herhangi bir miktarda alış veya satış emri girildikten sonra bakiyeler düzeliyor. Bu durum bir süredir devam ediyor. 

Birde bir süre önce belirttiğim v2 api den komisyon oranını hangi endpoint den alacağız ?

İyi çalışmalar.

**Comment by ocinbat** [comment]
Merhaba Emrah,

Alım/satım ve bakiyeni görüntülemek için kullandığın endpointleri belirtebilirsen daha detaylı inceleyebiliriz. Bunları sormamın nedeni sistemde bu operasyonları yapabileceğin farklı versiyonda endpointler olması ve hepsinin farklı kullanıcı isteklerine göre farklı davranması. Hangisinde sorun yaşadığını anlarsak daha hızlı çözüme gidebiliriz.

**Comment by emrahtopcu** [comment]
Kullandığım endpoint: 'api/v1/users/balances'. buradan dönen cevapta index 0 da TRY bakiye bilgileri var. Bu bilgiler içerisinde 'free' alanı bazen güncellemiyor. Yani diyelimki tüö bakiye ile BTC aldım ve 'free' alanı 0. Aldığım btc yi sattıktan sonra tutar güncellenmiyor, alım işlemindeki bakiye ne ise o kalıyor. Bu çok sık olmaya başladı ayrıca şimdiye kadar sadece bir defa btc bakiyede de aynı şey oldu, index 1 de BTC bakiye bilgisi var orada da gene 'free' alanı da güncellemedi. Bu durum yeni bir order girene kadar düzelmiyor.

Public işlemlerin tümünde v1, private işlemlerin tümünde ise v2 kullanıyorum.

İyi çalışmalar.

**Comment by ocinbat** [comment]
Merhaba,

V2 üzerinde sana özel komisyon oranlarını `api/v2/account/commissions` endpointinden alabilirsin.

Bakiye güncellenmeme problemin için araştırmalarımız devam ediyor. Bu tarz hataları çözebilmek için aynı sorunu bizim tarafta test ortamlarımızda tekrar yaratabilmemiz gerekiyor, bu da biraz zaman alıyor. Ama üzerinde çalıştığımızı bilmeni isterim.

**Comment by efecini** [comment]
> Merhaba,
> 
> V2 üzerinde sana özel komisyon oranlarını `api/v2/account/commissions` endpointinden alabilirsin.
> 
> Bakiye güncellenmeme problemin için araştırmalarımız devam ediyor. Bu tarz hataları çözebilmek için aynı sorunu bizim tarafta test ortamlarımızda tekrar yaratabilmemiz gerekiyor, bu da biraz zaman alıyor. Ama üzerinde çalıştığımızı bilmeni isterim.

Merhaba, komisyonları almak için hala bu endpoint(api/v2/account/commissions) geçerli midir? Yoksa başka bir endpoint mi var?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
