### ISSUE TITLE
FAILED_INVALID_PRICE_SCALE Hatası

### ISSUE THREAD

**Issue by akaykilicoglu** [BTCTrader/broker-api-docs#188]
Merhabalar, 

api/v1/order  endpoint üzerinden emir girmeye çalışırken FAILED_INVALID_PRICE_SCALE hatası alıyorum. Ve sürekli vermiyor hatayı aynı değerler ile bazen emir girişi yapabiliyorum bazen yapamıyorum bu konu ile ilgili inceleme yapabilirmisiniz ?

Return :400 Bad Request: [{"success":false,"message":"FAILED_INVALID_PRICE_SCALE","code":1126}]

**Comment by yucelalbar** [comment]
Merhaba,

Bu durum ile ben de karşılaşıyorum. Problemin nedenini saptayabildiniz mi?
