### ISSUE TITLE
User Transactions sadece en son yapılan 200 işlemi gösteriyor

### ISSUE THREAD

**Issue by ahmedahmedo** [BTCTrader/broker-api-docs#189]
api dokümanında son 30 günü gösterdiği yazmasına rağmen sadece son 200 işlemi gösteriyor.

**Comment by ocinbat** [comment]
Merhaba,

Güvenlik ekibimizce bir endpoitten dönebilecek item limitleri belirlendi. Bu bağlamda bazı endpointlerimizde maximum dönebilecek item sayısı kısıtlaması var. Dokümantasyonun güncel olmaması konusunda düzenleme yapacağız. Bununla birlikte bu ihtiyacın olan verinin sana sayfalı dönebilmesi için bir geliştirme yapabilir miyiz bunu da araştırıp tekrar dönüş yapacağım.

**Comment by ahmedahmedo** [comment]
User Transactions'ları kullanarak günlük bazda hacim bilgime ulaşmak istiyorum. kısıtlama dolaysıyla ilgili veriye ulaşmak sıkıntılı. web sayfasında 30 günlük toplam hacim var. gün gün hacim bilgisine ulaşma imkanı olsa faydalı olur.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
