### ISSUE TITLE
ID'ye göre Open Orders

### ISSUE THREAD

**Issue by aydinhus** [BTCTrader/broker-api-docs#190]
Merhaba,

İşlem çifti yerine direkt olarak ID üzerinden Order durumunu sorgulamak mümkün mü? - Gelen cevaptan order ID ye göre aramak yerine -

Ayrıca Partial (matched partially) durumunda ne kadarlık kısmın gerçekleştiğini sorgulamak mümkün mü?
Dokümantasyonda göremedim.

**Comment by onurgozupek** [comment]
allOrders uçnoktasından orderId ile sorgulama yapabilirsiniz. Matched Partially için "eşleşen kısmı" direkt gelmiyor. Ancak bulabilmek için "amount" değerinden "leftAmount" değerini çıkarabilirsiniz.

**Comment by aydinhus** [comment]
Teşekkürler yanıtlarınız için.
