### ISSUE TITLE
Yurt disindan erisim sikintisi Cloudflare

### ISSUE THREAD

**Issue by Cagatay342** [BTCTrader/broker-api-docs#191]
Merhaba bu yaklasik olarak her ay bir kere tekrarlaniyor kendi kendine belli bir sure sonra duzeliyor.2 yildir duzeltemedim.c# ApiClientV1 i kullaniyorum.Aldigim hata (ayni esnada yurticinden bir bilgisayarla sorunsuz calisiyor.)

{StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: close
  X-Frame-Options: SAMEORIGIN
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  CF-RAY: 57bb251b8eac7e91-MUC
  Cache-Control: no-cache
  Date: Sun, 29 Mar 2020 17:00:03 GMT
  Set-Cookie: *************************; expires=Tue, 28-Apr-20 17:00:03 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax
  Server: cloudflare
  Content-Type: text/html; charset=UTF-8
}}

**Comment by ocinbat** [comment]
Çağatay merhaba,

Biz gün içerisinde onlarca kere yayındaki servisimize güncelleme geçiyoruz. Normal şartlarda bu süreci son kullanıcının hissetmeyeceği şekilde yapmaya çalışıyoruz ama bazen teknik aksaklıkların birkaçı bir araya gelerek bu olumsuz durumu oluşturabiliyor. 

Bu hatayı aldığın zamana dair detaylı logların mevcut mudur?
Ve eğer mümkünse gönderdiğin istedğin Path ve Host değerlerini de tam olarak iletebilir misin?

**Comment by Cagatay342** [comment]
Host 
https://api.btcturk.com

Path
api/v1/users/transactions/trade?type=buy&type=sell&symbol=TRY&symbol=BTC&startDate=1580666563803&endDate=1585850563804

path 2
api/v1/users/balances

iki ornek veriyim de hepsi ayni. Baska bir  yardimci olacak bilgi var midir ?

**Comment by Cagatay342** [comment]
bu hatanin sizden kaynaklandigini sanmiyorum cloudflare ile alakali ama yillardi her ay oluyor bu sikinti.Bir suru sey denedim yok.Kendi kendine duzeliyor

**Comment by ocinbat** [comment]
Çağatay selam,

Ara ara yurt dışı kaynaklı saldırılar alıyoruz. Bu nedenle geçici süreliğine yurt dışından gelen bağlantıları limitleyebiliyoruz. Şu anda da onlardan birine takılmış olabilirsin.

**Comment by Cagatay342** [comment]
https://community.cloudflare.com/t/community-tip-fixing-error-503-service-unavailable-service-temporarily-unavailable/44438 
tam da onla alakali bisey bulmustum . :)

**Comment by Cagatay342** [comment]
ne yapmam gerekir peki . yapilabilecek bisey varmi.ip im sabit belki salliyorum suan ama whitelist e falan ekleme yoktur heralde

**Comment by ocinbat** [comment]
Müşteri hizmetleri üzerinden bize ulaşırsan ip'ni whitelist'e alabiliriz. :)

**Comment by Cagatay342** [comment]
Aa super cok tessekkurler hemen ulasiyorum.

**Comment by pzkpfwVI** [comment]
E peki ben ne yapacagim benim ip'im sabit degil

**Comment by ocinbat** [comment]
Merhaba,

Bu sürekli yaşanılan bir durum değil. Sadece güvenlik ekibimizin uygun gördüğü durumlarda geçici olarak uyguladığımız bir kısıtlama. Şu an için sorun bulunmuyor.

**Comment by ynussahn** [comment]
Merhaba,

Birden fazla IP bildirmem durumunda hepsini whiteliste eklemeniz mümkün müdür?

**Comment by erdenertamer** [comment]
Merhaba,

Ayni sorunu ben de yasiyorum uzun suredir ve birden fazla ip kullanabiliyorum. Cozum olarak birden fazla ip’yi whitelist edebilir misiniz?

**Comment by oxanero** [comment]
Merhaba,
Benim de bugunlerde yaklasık 2-3 gündür bu hatayı alıyorum. VPN vs  ile de denedim sonuca ulaşamadım nasıl yapmalıyım acaba?

İyi Çalışmalar,

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
