### ISSUE TITLE
v2 api

### ISSUE THREAD

**Issue by alsanf** [BTCTrader/broker-api-docs#192]
ApiExampleV2 kodlarinizda token alimi icin asagidaki gibi bir kod var:

            var username = configuration["username"];
            var password = configuration["password"];
            var resourceUrl = configuration["resourceUrl"];
            var authenticationUrl = configuration["authenticationUrl"];

            var authentication = new Authentication(username, password, authenticationUrl);

            var tokenResponse = authentication.GetTokenResponse().Result;

buradaki username/password btcturk.com 'a login olurken kullandigimiz kullanici adi ve parola mi? private ve public keylerimiz ile v2 api kullanmamizin bir yolu yok mu?
ve authenticationUrl olarak ne kullanmamiz gerekiyor?

**Comment by ocinbat** [comment]
Merhaba,

Şu an için v2 api'yi kullanabilmenizin bir yolu yok maalesef.
V1 ile giriş yapabilmek için de pro.btcturk.com'a giriş yapıp Hesap > API Erişimi menüsünden API key oluşturmanız gerekiyor.

Daha fazla ayrıntı için: https://docs.btcturk.com/#authentication

**Comment by alsanf** [comment]
Merhaba,
v1 api üzerinden sipariş verebiliyorum zaten. fakat bazen order objesi'nin null return edilmesi seklinde bir sorun yasiyorum. bu sekilde bir bug kaydiniz varmi? ornegin son olarak 31.03.2020 tarihinde bu sekilde bir sorun yasadim. isterseniz incelemeniz icin bu son ornege ait detay paylasabilirim.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
