### ISSUE TITLE
X-Signature Invalid Public Key code:401

### ISSUE THREAD

**Issue by yusufmendes** [BTCTrader/broker-api-docs#193]
Merhaba

Api ile bağlanmaya çalıştığım zaman "code":401,"message":"Unauthorized - Invalid Public key" hatası alıyorum. 
signature oluşturma kodum aşağıdaki gibidir.Ayrıca withdrawal/deposit apiniz yok gibi duruyor ya da ben bulamadım.Yardımcı olabilirseniz sevinirim .Benzer issue ların olduğunu gördüm fakat sorunumu çözemedim.Aşağıdaki fonksiyonun ürettiği objeyi request header kısmına ekliyorum ve sunucu timestampi ile benm makinemin timestampi arasında bir fark da bulunmamaktadır

```
function createAuthenticationHeadersForBTCTurk() {
    let nonce = Date.now();
    let message = btcTurkPublicApi + nonce;
    let signature = crypto
        .createHmac("sha256", btcTurkPrivateKey)
        .update(message)
        .digest("base64");
    return {
        "X-PCK": btcTurkPublicApi,
        "X-Stamp": nonce,
        "X-Signature": signature,
        "Content-Type": "application/json"
    }
}
```

**Comment by yusufmendes** [comment]
Api Dökümantasyonunuzda verdiğiniz örenk Python kodunu da işletiyorum fakat aynı hatayı alıyorum.
```
apiKey = "???"
apiSecret = "???"
apiSecret = base64.b64decode(apiSecret)
stamp = str(int(time.time()) * 1000)
data = "{}{}".format(apiKey, stamp).encode('utf-8')
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
url = "https://api.btcturk.com/api/v1/users/balances"
headers = {
    "X-PCK": apiKey,
    "X-Stamp": str(stamp),
    "X-Signature": str(base64.b64encode(signature).decode('utf-8')),
    "Content-Type": "application/json"
}
request_btcturk = requests.get(url, headers=headers)
print("test")
```

**Comment by onurgozupek** [comment]
Merhaba, yolunuz doğru ancak kodunuz eksik. Tam, çalışan kod şu şekilde:

```python
import base64
import hmac
import hashlib
import requests
import json
import time
apiKey = "API_KEY"
apiSecret = "API_SECRET"
apiSecret = base64.b64decode(apiSecret)
stamp = str(int(time.time())*1000)
data = "{}{}".format(apiKey , stamp).encode('utf-8')
signature = hmac.new(apiSecret , data , hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK":apiKey , "X-Stamp":stamp , "X-Signature":signature , "Content-Type":"application/json"}

url = "https://api.btcturk.com/api/v1/users/balances"
resp = requests.get(url=url , headers=headers)
result = resp.json()
print(json.dumps(result , indent=2))
```

**Comment by yusufmendes** [comment]
Merhaba kodun son kısmındaki print("test") deneme amaçlı yazıldı.sizin de benm de yazdığım kodun response unu print ettiğimde şu hatayı alıyorum 
```
{
  "success": true,
  "message": "Unauthorized - Invalid Public key",
  "code": 1037
}
```

**Comment by yusufmendes** [comment]
requestin aynısını postman ile de atıyorum aynı hatayı alıyorum.Pro üzerinden api key tanımladım ve tüm yetkileri de verdim.Ip kısmına 0.0.0.0 yazıp şimdilik tüm IP lere izin verdim ama yine de 
{
  "success": true,
  "message": "Unauthorized - Invalid Public key",
  "code": 1037
} 
hatasını alıyorum
Hesabımı kontol edebilrmisiniz yüksek ihtimal sistemde bir sıkıntı var gibi görünüyor.Teşekkürler

**Comment by onurgozupek** [comment]
API anahtarını oluştururken IP alanını boş bırakıp, yeni bir API anahtarıyla dener misiniz? Yukarıda paylaştığım kodu test edip gönderdim. BtcTurk PRO'dan IP sınırlaması olmadan, tüm yetkileri açık bir API anahtarı alıp deneyebilirsiniz.

**Comment by yusufmendes** [comment]
IP anahtarını(0.0.0.0) sildim ve hata düzeldi.Teşekkür ederim.Fakat şu an ip filtresi olmadığı için güvenlik sıkıntısı oluşma ihtimali var.IP kısmına 0.0.0.0 değil de kendi IP adresimi eklemeye çalıştığımda da invalid IP hatası verdi sistem.Ama şimdilik yoluma böyle devam ediyorum,kolay gelsin

**Comment by yusufmendes** [comment]
Yorumlarımı ilişkili olan diğer issue üzerinden yapıyormusum kusura bakmayın kolay gelsin
