### ISSUE TITLE
HTTP 1020 hatası

### ISSUE THREAD

**Issue by AtakanErdem1971** [BTCTrader/broker-api-docs#195]
29 Mart 2020'den bu yana Emir Defteri okuma taleplerimiz için 1020 kodlu hatayı alıyoruz. Limit parametresi için API dokümanında belirtildiği şekilde 100 ile 1000 arasında değerler vermemize rağmen durum değişmedi. Yardımcı olabilirseniz çok seviniriz.

**Comment by ocinbat** [comment]
Merhaba Atakan, 1020 hatası bizim firewall kurallarımızdan birine takıldığına işaret ediyor. Konu ile ilgili olarak araştırma yapabilmemiz adına müşteri hizmetleri ekibimiz ile iletişime geçip, Cloudflare üzerinden 1020 hatası aldığını, istek gönderdiğin ülkeyi ve IP adresini iletebilirsen daha detaylı bir inceleme yapabiliriz.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
