### ISSUE TITLE
fiyat ondalık sorunu

### ISSUE THREAD

**Issue by yunusseemre** [BTCTrader/broker-api-docs#197]
limit alım emri için gönderdiğim talepte fiyatın küsuratını iletemiyorum.
Örneğin:  
fiyat=14.15
miktar=16.17
olarak alım emri gönderiyorum şu şekilde 
{
    Amount = 16;
    DenominatorPrecision = 2;
    NumeratorPrecision = 2;
    PairSymbol = LINKTRY;
    Price = 14;
    amountPrecision = 17;
    orderMethod = 0;
    orderType = 0;
    pricePrecision = 15;
    total = 0;
    totalPrecision = 00;
    triggerPrice = 0;
    triggerPricePrecision = 00;
}

fakat sonuc olarak gelen cevap ise fiyat 14 olarak gözüküyor 
response:
{
    amount = "16.17";
    datetime = "2020-04-09T14:00:26.0731025Z";
    id = 193707637;
    pairsymbol = "<null>";
    price = 14;
    type = Buy;
}

**Comment by onurgozupek** [comment]
Muhtemelen değerleri integer (tamsayı) olarak gönderiyorsunuz. string olarak "tırnak içinde" göndermeyi deneyin. (Bir de her işlem çiftinde küsüratlı fiyat yok. Örn BTC/TRY, ETH/TRY bunlara da dikkat edin lütfen)

Bu arada, BtcTurk API ile işlem yapamazsınız artık. BtcTurk | PRO API dokümanlarına da https://docs.btcturk.com adresinden ulaşabilirsiniz. Kod örnekleri de ekledik)

**Comment by yunusseemre** [comment]
XRP/TRY ve LTC/TRY parametrelerinde gönderdiğimde sorunsuz çalışıyor.
Fakat LINK/TRY parametresinde böyle bir sorun ile karşılaşıyorum

**Comment by ocinbat** [comment]
Merhaba, https://api.btcturk.com/api/v1/order üzerinden mi işlem yapıyorsunuz?

**Comment by yunusseemre** [comment]
Merhaba  bu adres üzerinden işlem yapıyorum : https://west.btcturk.com/api/Exchange
miktar değerini gönderirken herhangi bir sıkıntı yok virgülden sonraki kısım normal iletiliyor, fakat fiyat değerinde XRP ve LTC parametrelerinin dışındakilerde DASH,ATOM,LINK...  fiyat değerinin virgülden sonraki kısmını gönderemiyorum.

**Comment by ocinbat** [comment]
Bu adreste sunulan api'ye artık destek vermiyoruz. İşlemlerinizi https://api.btcturk.com/ üzerinden yapmalısınız.  https://docs.btcturk.com adresinden ilgili dokümantasyona ulaşabilirsiniz.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
