### ISSUE TITLE
Market emri için gerçekleşen fiyat bilgisi nasıl alınır?

### ISSUE THREAD

**Issue by umitk** [BTCTrader/broker-api-docs#199]
Merhaba, Market emri için gerçekleşen fiyat bilgisini nasıl alabilirim? Emir sonrası dönen cevap içinde "price" kısmı 0.0 olarak dönüyor. Eğer bu bilgi dönmüyorsa doğru yöntem işlem sonrası ".../api/v1/allOrders" ile sorgulamak mıdır?

Market emri sonrası dönen cevap:

`{
  "data": {
    "id": 198008190,
    "quantity": "0.0002",
    "price": "0",
    "stopPrice": "0",
    "newOrderClientId": "BtcTurk Python API Test",
    "type": "sell",
    "method": "market",
    "pairSymbol": "BTCUSDT",
    "pairSymbolNormalized": "BTC_USDT",
    "datetime": 1586777264180
  },
  "success": true,
  "message": "OK",
  "code": 0
}`

**Comment by onurgozupek** [comment]
/order uçnoktasının görevi emri iletmek. Sonucunu /allOrders (veya openOrders) uçnoktalarından sorgulayabilirsiniz.

**Comment by umitk** [comment]
Hızlı cevap için teşekkürler. Market emrim ile allOrders kayıtlarını nasıl eşleştirebilirim. Emir sonucunda dönen "id" alanı ile allOrders sonuçlarında bulunan "id" alanları eşleşmiyor. Tek eşleşen emir sonucunda bulunan "datetime" ile allOrders sonucunda bulunan "timestamp" alanı. Bu iki alana göre mi eşleştirme yapmalıyım?

Emir sonucu:
`{
  "data": {
    "id": 197988577,
    "quantity": "0.0002",
    "price": "7280",
    "stopPrice": "0",
    "newOrderClientId": "1586691103716",
    "type": "buy",
    "method": "limit",
    "pairSymbol": "BTCUSDT",
    "pairSymbolNormalized": "BTC_USDT",
    "datetime": 1586775549873
  },
  "success": true,
  "message": "OK",
  "code": 0
}`

allOrders sonucu:
`{
      "price": "6710",
      "numeratorSymbol": "BTC",
      "denominatorSymbol": "USDT",
      "orderType": "buy",
      "id": 24412239,
      "timestamp": 1586775368873,
      "amount": "0.00020000",
      "fee": "0",
      "tax": "0"
    }`

**Comment by SelcukCode** [comment]
@onurgozupek Bey soruyu hızlı okumuş olabilir. @umitk /api/v1/users/transactions/trade uç noktasını kullanın.
