### ISSUE TITLE
Problem with Authentication in JAVA

### ISSUE THREAD

**Issue by dante-deo** [BTCTrader/broker-api-docs#2]
Hi there,
I can consume the methods with JAVA which does not require authentication (ie. "ticker").
However, the attached piece of code returns error code 401 for "balance" method.
Any help will be granted,
Best.

[Balance.txt](https://github.com/BTCTrader/broker-api-docs/files/118857/Balance.txt)

**Comment by mohamedfarrag** [comment]
You should receive the reason beside the status code. Could you please print out the response ? it should be like "Unauthorized - Invalid Public key" , "Unauthorized - Invalid Nonce" ,..etc

**Comment by dante-deo** [comment]
HTTP/1.1 401 Unauthorized
That is the whole response. There is nothing similar to your suggestions..

**Comment by mohamedfarrag** [comment]
Could you please change this line :
`byte[] secretKey = apiPrivateKey.getBytes("UTF-8");`

to be :
`byte[] secretKey = javax.xml.bind.DatatypeConverter.parseBase64Binary(apiPrivateKey);`

**Comment by dante-deo** [comment]
Apperently Mohamed,
I have insisted on and walked around so much with the current code that I had a blindness.
My bad, qed..
