### ISSUE TITLE
FAİLED_INVALID_QUANTİTY_SCALE code:1127 hatası alıyorum

### ISSUE THREAD

**Issue by onurerenarpaci** [BTCTrader/broker-api-docs#200]
Bu hatayı alıyorum. Yardımcı olabilir misiniz? Pairs Scale (Quantity/Price) diye bir tablo var dökümanda onunla mı alakalı? Bu tablo ne anlama geliyor?

**Comment by akildemir** [comment]
aynı hatayı ben de alıyorum. Bulabildiniz mi bi çözüm şimdiye kadar? Paylaşırsanız sevinirim.

**Comment by onurgozupek** [comment]
Invalid Quantity Scale hatası noktadan sonraki hane sayısının hatalı gönderimiyle ilgili. Quantity (veya amount) değerini https://api.btcturk.com/api/v2/server/exchangeinfo 'dan gelen numeratorScale değerine uygun şekilde formatlarsanız sorunu aşabilirsiniz.

**Comment by fatihkutuk** [comment]
Aynı hatayı bende alıyorum, bir bot yazmaya çalışıyorum ve aşağıdaki parametreleri gönderdim

{"quantity":0.00236856,"price":150,"newOrderClientId":"test","orderMethod":"market","orderType":"buy","pairSymbol":"BTCTRY"}

aldığım sonuç ise şu ;
{
  "httpStatusCode": 400,
  "data": null,
  "success": false,
  "message": "FAILED_INVALID_QUANTITY_SCALE",
  "code": 1127
}

numertorScale paramtresine baktım 8 diyor yani onda da bir sorun görünmüyor peki neden hata alıyorum

**Comment by fatihkutuk** [comment]
Arkadaşlar çözümü yazıyorum, 
"quantaty" paramteresini bende alcağım btc miktarı olarak düşünmüşştüm ama yanılmışım.
"quantaty" paramatresi harcayacağınız miktar oluyor.
 btc alacaksanız bu harcayacağınız tl,
btc satacaksanız bu satacağınız btc miktarı oluyor.

Örneğin Burada:
{"quantity":100,"newOrderClientId":"test","orderMethod":"market","orderType":"buy","pairSymbol":"BTCTRY"}

100 TL lik btc alma isteği atıyorsunuz

Örneğin Burada 
{"quantity":0.00314177,"newOrderClientId":"test","orderMethod":"market","orderType":"sell","pairSymbol":"BTCTRY"}

0.00314177 miktarında btc satmış oluyorsunuz kolay gelsin.

**Comment by ekremus** [comment]
Selamlar, bunun bence düzeltilmesi gerekli. @ocinbat @BTCTraderAdmin @fatihkutuk 

Çünkü
1- Diğer bütün borsalarda* BTC/USDT şeklindeki bir pair için, quantity BTC üzerinden hesaplanır. 
2- BUY ve SELL komutlarında quantitiy farklı şekilde hesaplanamaz. ya BTC üzerinden ya da USDT üzerinden hesaplanmalıdır.
3- LIMIT ORDER'da BUY ve SELL için quantity BTC üzerinden hesaplanırken, MARKET ORDER'da sadece BUY emri USDT quantity'si üzerinden hesaplanamaz. Bu tutarsızlık yaratıyor.

**Comment by write4alive** [comment]
Aynı hatayı alıyorum, çözüm için teşekkürler fakat bu durumun fixlenmesi gerekli lütfen.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
