### ISSUE TITLE
api uzerinden alim/satim emirlerinde sorun

### ISSUE THREAD

**Issue by alsanf** [BTCTrader/broker-api-docs#201]
Merhaba,
api üzerinden alim/satim emri verirken sorun yasiyorum.
http ok donuyor servis, ama emir bekleyen emirlerin arasinda gözükmüyor.
api üzerinde son 3 emirin 3unde de ayni sorun oldu, ve finansal olarak zarar goruyorum bu durumdan. yardimci olabilir misiniz?

**Comment by ocinbat** [comment]
Merhaba,
Kullandığınız endpointleri de ekleyebilir misiniz?

**Comment by alsanf** [comment]
donen header bu sekilde;
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Vary: Origin
  Vary: Access-Control-Request-Method
  Vary: Access-Control-Request-Headers
  pragma: no-cache
  access-control-allow-credentials: true
  access-control-expose-headers: X-Content-Type-Options, X-Frame-Options, X-XSS-Protection, Date, Transfer-Encoding, Vary
  strict-transport-security: max-age=31536000; includeSubDomains; preload
  x-content-type-options: nosniff
  x-frame-options: DENY
  x-xss-protection: 1; mode=block
  api-supported-versions: 1.0, 2.0
  CF-Cache-Status: DYNAMIC
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  CF-RAY: 584c23120cbba7b6-IST
  cf-request-id: 0223743f480000a7b6e8a43200000001
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  Date: Thu, 16 Apr 2020 07:19:15 GMT
  Set-Cookie: __cfduid=d24a81b8e9d8ee68c74840d16fd3069ed1587021555; expires=Sat, 16-May-20 07:19:15 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax
  Server: cloudflare
  Content-Type: application/json; charset=utf-8
}

**Comment by alsanf** [comment]
api/v1/order uzerinden emir veriyorum.
bu bilgiler yeterli mi inceleme icin?

**Comment by ocinbat** [comment]
Bekleyen emirleri nereden çekiyorsunuz?

**Comment by alsanf** [comment]
btcturk pro'dan kendim girip bakiyorum ve emir orada yok .
bakiyemde hic emir vermemisim gibi duruyor.
bakiyem arkada blokeleniyor mu diye dusunup kendim manuel emir vemeyi denedim ve verebildim.

**Comment by ocinbat** [comment]
"api/v1/order" üzerinden emir veriyorsunuz, başarılı dönüş alıorsunuz ve emir herhangi bir şekilde sistemde görünmüyor. Bakiyeniz de yerinde. İlerleyen bir zaman diliminde düzelme de olmuyor, sanki hiç istek göndermemişsiniz gibi. Doğru mu anlıyorum?

**Comment by alsanf** [comment]
Evet, dogrudur bu sekilde. api uzerinden  verdigim son 3 emirimin 3unde de ayni durum olustu.
diger ikisinin header'lari yok ama tarih ve saatlerini, alim satim miktar ve tutarlarini paylasabilirim.
sorun yasadiktan sonra donen header'i loglamaya basladim ve son emirn headerini detayli inceleme icin yukarida paylastim.  header inceleme icin yeterli mi?

**Comment by ocinbat** [comment]
Dönen response kodu ve body'i de loglayabilirseniz daha detaylı inceleyebiliriz.

**Comment by ocinbat** [comment]
Bir de bana giriş yaparken kullandığınız e-posta adresini omer.cinbat@btctrader.com'a e-posta olarak gönderirseniz daha detaylı bir geçmiş incelemesi yapabilirim.

**Comment by alsanf** [comment]
response tam olarak asagidaki sekilde.
e-posta adresimi gonderiyorum belirttiginiz mail adresine.

StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Vary: Origin
  Vary: Access-Control-Request-Method
  Vary: Access-Control-Request-Headers
  pragma: no-cache
  access-control-allow-credentials: true
  access-control-expose-headers: X-Content-Type-Options, X-Frame-Options, X-XSS-Protection, Date, Transfer-Encoding, Vary
  strict-transport-security: max-age=31536000; includeSubDomains; preload
  x-content-type-options: nosniff
  x-frame-options: DENY
  x-xss-protection: 1; mode=block
  api-supported-versions: 1.0, 2.0
  CF-Cache-Status: DYNAMIC
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  CF-RAY: 584c23120cbba7b6-IST
  cf-request-id: 0223743f480000a7b6e8a43200000001
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  Date: Thu, 16 Apr 2020 07:19:15 GMT
  Set-Cookie: __cfduid=d24a81b8e9d8ee68c74840d16fd3069ed1587021555; expires=Sat, 16-May-20 07:19:15 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax
  Server: cloudflare
  Content-Type: application/json; charset=utf-8
}

**Comment by ocinbat** [comment]
Response bodysini de görebilirsem daha faydalı olabilirim.

**Comment by alsanf** [comment]
malesef body yok elimde, onuda loglarima ekleyecegim ..

**Comment by ocinbat** [comment]
Şu anda anormal bir durum göremiyorum size ait emirlerde. Son 7 gün içerisinde gönderdiğiniz emir ekleme isteklerinin sadece 1 tanesinde bakiye yetersiz hatası almışsınız. Bunun dışında 3 isteğiniz başarılı olarak gerçekleşmiş. Dilerseniz siz body'i de ekleyin, dönen mesaj ile daha anlamlı bir çıkarım yapabiliriz. Body'de success alanı var. Dönüş değerinin true olması gerekiyor. Aksi taktirde herhangi bir nedenden dolayı emriniz gerçekleşmemiş olabilir. Bu alanı kontrol ediyor musunuz?

**Comment by alsanf** [comment]
bu sabah sorun yasadigim emirin tutar ve adet bilgilerini mail ile paylastim sizinle.
o emri son 7 gunun emirleri icinde gorebiliyormusunuz?

**Comment by ocinbat** [comment]
Evet, döndüm size.

**Comment by firstcylon** [comment]
Merhaba tekrar,
yine ayni sorunu yasadim.
header ve body asagidaki sekilde.
order'in success olmamasi durumunda 200ms araliklarla 3kere emri yeniden girmeyi denedim 3 denemede de ayni hata dondu.
bu emri verdigim esnada herhangi bir acik emir yoktu.


04:41:29,749 [INFO ] [4] BtcTurkHelper.PlaceOrder - btcturk info: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Vary: Origin
  Vary: Access-Control-Request-Method
  Vary: Access-Control-Request-Headers
  pragma: no-cache
  access-control-allow-credentials: true
  access-control-expose-headers: X-Content-Type-Options, X-Frame-Options, X-XSS-Protection, Date, Transfer-Encoding, Vary
  strict-transport-security: max-age=31536000; includeSubDomains; preload
  x-content-type-options: nosniff
  x-frame-options: DENY
  x-xss-protection: 1; mode=block
  api-supported-versions: 1.0, 2.0
  CF-Cache-Status: DYNAMIC
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  CF-RAY: 5883e1ef7e30a834-IST
  cf-request-id: 02464b89ad0000a8347d051200000001
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  Date: Thu, 23 Apr 2020 01:41:30 GMT
  Set-Cookie: __cfduid=dcaa8dc60f66262c9ad360168c82734741587606090; expires=Sat, 23-May-20 01:41:30 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax
  Server: cloudflare
  Content-Type: application/json; charset=utf-8
}
04:41:29,778 [INFO ] [4] BtcTurkHelper.PlaceOrder - content: {"success":false,"message":"FAILED_ORDER_WITH_OPEN_ORDERS","code":1122}

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
