### ISSUE TITLE
Unsupported Media Type

### ISSUE THREAD

**Issue by skyberk** [BTCTrader/broker-api-docs#202]
Merhabalar mevcut usdt ile btc almayı deniyorum fakat 415 hata kodu döndürmektedir.

https://docs.btcturk.com/#submit-order

Request

Url : https://api.btcturk.com/api/v1/order
Method : Post
Headers : X-PCK, X-Stamp,X-Signature, User-Agent

Body olarak json ve querystring şeklinde iki farklı şekilde göndermeyi denedim örnek json body requestim.

{"quantity":10.0,"orderType":"buy","pairSymbol":"BTCUSDT","orderMethod":"market"}

**Comment by skyberk** [comment]
Bu sorunu content-type ekleyerek çözdüm. orderMethod limit için çalışmaktadır. Fakat market için quantity yerine eklememiz gereken miktar için property ismini dökümantasyonda bulamadım ?

**Comment by onurgozupek** [comment]
Merhaba, piyasa alış emri verirken "quantity" değişkeninde ödeyeceğiniz birimi (BTC_USDT işlem çiftinde USDT) miktar olarak göndermelisiniz. Örneğin 100USDT'lik BTC almak istiyorsanız:
```python
{"pairSymbol":"BTCUSDT", "quantity":"100", "orderMethod":"market", "orderType":"buy", "stopPrice":"0"}
```
şeklinde sorgu gönderebilirsiniz.

Örneğin 0.001BTC satmak istiyorsanız

```python
{"pairSymbol":"BTCUSDT", "quantity":"0.001", "orderMethod":"market", "orderType":"sell", "stopPrice":"0"}
```
şeklinde sorgu gönderebilirsiniz
