### ISSUE TITLE
432 OrderBookDifference'da transaction type

### ISSUE THREAD

**Issue by ErrorEater** [BTCTrader/broker-api-docs#204]
Web soket dokümantasyonunda "OrderBookDifference" için "PS" olarak belirtilmiş olsa da gelen verilerden "CP" olması muhtemel işlem tipi ile ilgili bazı alanların net açıklanmamış olması sebebiyle bir kaç sorum var.

> PS: Orders are transaction type. 0: Updated, 1: New added, 3: Deleted

```
{
    "CP": 1,
    "P": "6921",
    "A": "0.48889195"
},
{
    "CP": 3,
    "P": "7199",
    "A": "0.39422757"
}
```

"A" ile belirtilen miktarlar sunucu tarafında yapılan toplama çıkarma işlemleri sonucu o kademenin son halini mi gösteriyor yoksa ilgili kademeye gelen bir işlem tipinin (yeni emir, var olan emri güncelleme veya var olan emri silme) o kademede var olan birçok miktar dışında sadece "A" miktarlık bir kısmını etkilediğini mi gösteriyor?

Mesela şu 3 durum için bu "A" miktarını nasıl algılamalıyız?

**"CP": 3 durumu için:**
a) Burada "A" değeri ilgili fiyat seviyesinden ne kadar miktar silindiğini mi gösteriyor?
b) Burada "A" değeri ilgili fiyat seviyesinin silme işlemi sonucu son halini mi gösteriyor?
c) Son gelen "A" miktardaki bir emirle o seviyenin tamamen silindiğini mi gösteriyor?

**"CP": 1 durumu için:**
a) Burada "A" değeri ilgili fiyat seviyesine ne kadar miktar eklendiğini mi gösteriyor?
b) Burada "A" değeri ilgili fiyat seviyesinin yeni emir ekleme işlemi sonucu son halini mi gösteriyor?
c) Bu "CP": 1 emri geldiğinde o seviyede daha önce bir veri olmadığını mı düşünmeliyiz yoksa var olan o seviyedeki veriye ekleme yapmak gerektiğini mi?

**"CP": 0 durumu için:**
Yukarıdaki durumlara benzer olarak, "A" değeri ilgili seviyenin sunucudaki son halini mi gösteriyor?Yani buradaki değeri kendi tarafımızdaki ilgili kademe için gelen veri şeklinde mi güncellemeliyiz?

**Comment by mhelvacikoylu** [comment]
**CP**'nin değeri ne olursa olsun **A** her zaman için son değeri gösterir. Örneğin **7200** fiyat için **A** değeri **0.5** iken, aynı fiyata **0.3** miktarında yeni bir emir daha eklendiğinde **CP** değeri **0 (updated)** ve **A** değeri **0.8** olarak gelir.

**Comment by ErrorEater** [comment]
> **CP**'nin değeri ne olursa olsun **A** her zaman için son değeri gösterir.

Bu durumda **"CP": 3 (delete)** durumu için **"A"**; o kademeden emir silme sonucu kalan miktarı mı gösterir yoksa **"A"** değerine bakmaksızın o kademenin tamamen silinmesi gerektiğini mi?

**Comment by mhelvacikoylu** [comment]
Tamamen silinmesi gerekiyor. O fiyatta daha önceden A miktar varmış ve bu satır iptal olmuş anlamındadır. İsterseniz değerini elinizdeki son A değeri ile sağlama yapmak için kullanabilirsiniz.
