### ISSUE TITLE
TickSize - MinPrice ilişkisi ve BTCTRY tickSize hatası

### ISSUE THREAD

**Issue by ErrorEater** [BTCTrader/broker-api-docs#205]
Genelde TickSize, girilecek emirdeki en düşük fiyat değişimi belirtir.
https://api.btcturk.com/api/v2/server/exchangeinfo

Yukarıdaki adrestenn BTCTRY çifti için dönen veride "tickSize": "10" olarak belirtilmiş.
Yani emir verirken 10 TL'den küçük artışlarda fiyat giremiyor olmam gerekir fakat gerçekte böyle değil, "minPrice": "1" dikkate alınıyor görünüyor.
Bu durumda bu "tickSize" değerinin anlamı nedir? Ne için kullanılır?

```
"filters": [
  {
	"filterType": "PRICE_FILTER",
	"minPrice": "1",
	"maxPrice": "100000000000",
	"tickSize": "10",
	"minExchangeValue": "9.9",
	"minAmount": null,
	"maxAmount": null
  }
]
```

Diğer yandan ETHBTC çifti için "tickSize": "0.00001" olarak belirtilmiş ve emirlerde gerçekten de en düşük fiyat değişiminin bu kadar olduğu görülüyor.

```
"filters": [
  {
	"filterType": "PRICE_FILTER",
	"minPrice": "0.0001",
	"maxPrice": "100000000000",
	"tickSize": "0.00001",
	"minExchangeValue": "0.00095",
	"minAmount": null,
	"maxAmount": null
  }
]
```

Sonuç:
BTCTRY çifti için "tickSize": "1" olarak düzeltilmelidir.

**Comment by mhelvacikoylu** [comment]
![image](https://user-images.githubusercontent.com/21208762/79983991-39155a80-84b1-11ea-816b-5db82cbdc8a0.png)

**tickSize** değeri yalnızca web ve mobil uygulama üzerinden fiyatın yanındaki aşağı ve yukarı oklarda fiyatın kaçar kaçar artıp azalacağını belirtir. Birim fiyat veya minimum fiyat değişimi anlamına gelmez.

**Comment by ErrorEater** [comment]
> ![image](https://user-images.githubusercontent.com/21208762/79983991-39155a80-84b1-11ea-816b-5db82cbdc8a0.png)
> 
> **tickSize** değeri yalnızca web ve mobil uygulama üzerinden fiyatın yanındaki aşağı ve yukarı oklarda fiyatın kaçar kaçar artıp azalacağını belirtir. Birim fiyat veya minimum fiyat değişimi anlamına gelmez.

Bu durumda şunu açıklar mısınız?
Bir çift için emir gönderirken en düşük fiyat artım miktarı hangi değerce gösteriliyor?

Mesela, BTCTRY için en düşük  artım miktarını **minPrice** yani 1 TL kabul edersek, ETHBTC'de de **0.0001** kabul etmeliyiz ancak UI'da siz onun 1/10'u kadar yani **"tickSize": "0.00001"** kadar değişime izin veriyorsunuz. Bu durumda ben emir gönderirken hangi değeri baz almalıyım?
İlk söylediğiniz geçerli ise tickSize'ı dikkate almalıyım ama BTCTRY'de 10TL'nin altında 1TL değişimli emirler gönderilebiliyor.

**Comment by mhelvacikoylu** [comment]
tickSize, minPrice gibi değişkenler yalnızca kullanıcı deneyimini arttırmak için UI tarafında kullanılmak üzere hazırlanmış değişkenlerdir. Siz API'a bağlanarak request atıyorsanız dikkate almanız gereken tek değişken **minExchangeValue** değişkenidir.

(miktar * fiyat) - komisyon oranı >= minExchangeValue

olması yeterlidir. Bu sebeple minExchangeValue 10 değil 9.9'dur (komisyon hesabı için bırakılmış yaklaşık aralık). Ayrıca virgülden sonra gönderebileceğiniz basamak sayısı symbol'ün **numeratorScale** değişkeninde belirtilmiştir.

**Comment by ErrorEater** [comment]
> (miktar * fiyat) - komisyon oranı >= minExchangeValue
> 
> olması yeterlidir. Bu sebeple minExchangeValue 10 değil 9.9'dur (komisyon hesabı için bırakılmış yaklaşık aralık). Ayrıca virgülden sonra gönderebileceğiniz basamak sayısı symbol'ün **numeratorScale** değişkeninde belirtilmiştir.

Market order gönderdiğimi düşünelim. Market orderda fiyat belli değil sadece miktar belli. İşlem Ancak işlem gerçekleştiğinde emrimin ortalama ne fiyattan gerçekleştiğini öğrenebileceğim. Bu durumda yukarıdaki hesabınızı nasıl kullanacağım?

BTCTRY için **numeratorScale** 8 yani minimum 0.00000001 BTC'lik emir gönderebilmeliyim.
0.00000001 BTC'mi sat diye market order gönderdiğimde satacak mıdır?

Benim bilmek istediğim şu;
Tahtada 49026 TL'den bir alım emri var, ben 49026.01 TL'den al emri girebilir miyim? Yoksa en iyi ihtimalle 49027 TL mi girebilirim? **En düşük fiyat değişimini nereden öğreneceğim** eğer tickSize bunu belirtmiyorsa.

**Comment by mhelvacikoylu** [comment]
**Market emir girerken fiyatınızı karşı yöndeki en iyi fiyat olarak hesaplayabilirsiniz.** Market alış giriyorsanız en iyi satış, market satış giriyorsanız en iyi alış sizin formüldeki fiyat değeriniz olacak.

**Minimum emir göndermeler precision değerlerinden farklıdır.** Her parite için farklı minimum emir tutarı olabilir. Bu değer de minExchangeValue ile kontrol edilir. Precision değerleri aynı olsa bile. **numeratorScale** yalnızca virgülden sonra kaç basamak olduğunu belirtir. Emir girme işlemine özel bir durum değildir.

**En düşük miktar değişimi** (fiyat değişiminden kastınız) ise numeratorScale'dir. örneğin BTCTRY için en düşük **miktar** değişimi
10 ^ -8 = 0.00000001
değeridir.

En düşük fiyat değişimi denominatorScale'dir. Bu değeri sizin göndermenize gerek yoktur.

**Comment by ErrorEater** [comment]
> (miktar * fiyat) - komisyon oranı >= minExchangeValue

Şu anki en iyi ask fiyatı 49026 TL olsun.
Ben de 0.1 BTC'yi 49026.01 TL'den satışa koymak istiyorum.
Bakıyorum formülünüz sağlanıyor mu;
(0,1 x 49026.01) - 0 >= 9.9
4902.601 - 0 >= 9.9 evet koşulu sağlıyor.
Bu durumda  49026.01 TL'den satış emri girebileceğim, doğru mu?

**Comment by mhelvacikoylu** [comment]
Satış emri girecekseniz en iyi alışı kullanmalısınız. Tahtadaki **karşı yönlü** emir ile kontrol etmeniz gerekiyor.

**Comment by ErrorEater** [comment]
> Satış emri girecekseniz en iyi alışı kullanmalısınız. Tahtadaki **karşı yönlü** emir ile kontrol etmeniz gerekiyor.

Beni anlamıyorsunuz, ihtiyacım olmayan bilgiler veriyorsunuz.
Şu alttaki kısmı dikkatlice okur musunuz.

1) Tahtada 49026 TL'de bekleyen satış emri (ASK fiyatlı) var. Ondan daha iyi fiyat vermek istiyorum.
2) 49026.01 TL'lik satış emri (ASK fiyatlı) verebiliyor muyum?

**Comment by mhelvacikoylu** [comment]
BTCTRY tahtası, websitesinde de görebileceğiniz üzere denominator scale değeri 0 olarak işlenmektedir. 49026'ya değil 49025 veya 49027'ye emir girebilirsiniz.

**Comment by ErrorEater** [comment]
> BTCTRY tahtası, websitesinde de görebileceğiniz üzere denominator scale değeri 0 olarak işlenmektedir. 49026'ya değil 49025 veya 49027'ye emir girebilirsiniz.

Peki ben bunu nerden bileceğim?

İlk mesajımdaki enstrüman bilgisi çektiğim adresinizde bu bilginin yer alması gerekiyor. Standart olarak tickSize bunu belirtir ama sizde o değer başka amaçlar için kullanılıyor.
Bu enstrüman listenizde bu bilgiyi belirtmeniz gerekiyor ki API'ye göndereceğimiz fiyatları min değişime yuvarlayabilelim.

**Comment by onurgozupek** [comment]
Mehmet, 49026.01'e değil demek istemiş. 49026TL olarak emir verebilirsiniz ama BTC/TRY için kuruşlu emir veremezsiniz.

Bunun için https://api.btcturk.com/api/v2/server/exchangeinfo adresinden hasFraction değerine bakmalısınız. hasFraction false ise noktadan sonra hane gönderemezsiniz. True ise denominatorScale kadar haneli küsürat girebilirsiniz.

**Comment by ErrorEater** [comment]
> Bunun için https://api.btcturk.com/api/v2/server/exchangeinfo adresinden hasFraction değerine bakmalısınız. hasFraction false ise noktadan sonra hane gönderemezsiniz. True ise denominatorScale kadar haneli küsürat girebilirsiniz.

İşte ihtiyacım olan bilgi. Teşekkür ederim.

**Comment by ErrorEater** [comment]
> Bunun için https://api.btcturk.com/api/v2/server/exchangeinfo adresinden hasFraction değerine bakmalısınız. hasFraction false ise noktadan sonra hane gönderemezsiniz. True ise denominatorScale kadar haneli küsürat girebilirsiniz.

Bu şekilde yapılsa bile hala min. değişim miktarı eksik!
BTCTRY için hasFraction = False tamam fakat hala izin verilen min. değişim miktarı belirsiz. Siz onu kafadan 1 kabul ediyorsunuz. **Neden yazılı olmayan bir sınır yokken öyle kabul edilmeli?** Neden 2, 5, 10 değil de 1?
minPrice = 1 ama o sadece en düşük değeri belirtiyor artışın/azalışın kaç olacağını değil.

Sonuç:
tickSize'ı standart kullanımına çevirip BTCTRY için 1 yaparsanız sorun kalmaz. hasFraction'a gerek yok.
UI'daki kullanım için de denominatorStepSize/stepSize gibi bir isimlendirme yapabilirsiniz.

**Comment by yunusseemre** [comment]
> Mehmet, 49026.01'e değil demek istemiş. 49026TL olarak emir verebilirsiniz ama BTC/TRY için kuruşlu emir veremezsiniz.
> 
> 
> 
> Bunun için https://api.btcturk.com/api/v2/server/exchangeinfo adresinden hasFraction değerine bakmalısınız. hasFraction false ise noktadan sonra hane gönderemezsiniz. True ise denominatorScale kadar haneli küsürat girebilirsiniz.


ETH_USDT de sıkıntı var gibi 

Has fraction değeri false dönüyor 


{"id":20,"name":"ETHUSDT","nameNormalized":"ETH_USDT","status":"TRADING","numerator":"ETH","denominator":"USDT","numeratorScale":8,"denominatorScale":1,"hasFraction":false,"filters":

**Comment by onurgozupek** [comment]
Güncelleme yayınlandı. Kontrol edebilir misiniz?

**Comment by ErrorEater** [comment]
> Güncelleme yayınlandı. Kontrol edebilir misiniz?

**"ETHUSDT"** için:
```
"denominatorScale": 1, "hasFraction": true,
"minPrice": "0.01"
```
Bu tanıma göre en düşük fiyat 0.01 olmamalı, 0.1 olmalı. 

**"XRPUSDT"** için:
```
"denominatorScale": 4, "hasFraction": true,
"minPrice": "0.00001"
```

Bu tanıma göre en düşük fiyat 0.00001 olmamalı, 0.0001 olmalı.

Tüm enstrümanları kontrol etmedim!

```
{
  "id": 20,
  "name": "ETHUSDT",
  "nameNormalized": "ETH_USDT",
  "status": "TRADING",
  "numerator": "ETH",
  "denominator": "USDT",
  "numeratorScale": 8,
  "denominatorScale": 1,
  "hasFraction": true,
  "filters": [
    {
      "filterType": "PRICE_FILTER",
      "minPrice": "0.01",
      "maxPrice": "100000000000",
      "tickSize": "0.1",
      "minExchangeValue": "4.91",
      "minAmount": null,
      "maxAmount": null
    }
  ],
  "orderMethods": [
    "LIMIT",
    "STOP_LIMIT"
  ],
  "displayFormat": "#,##0.0"
},
{
  "id": 21,
  "name": "XRPUSDT",
  "nameNormalized": "XRP_USDT",
  "status": "TRADING",
  "numerator": "XRP",
  "denominator": "USDT",
  "numeratorScale": 4,
  "denominatorScale": 4,
  "hasFraction": true,
  "filters": [
    {
      "filterType": "PRICE_FILTER",
      "minPrice": "0.00001",
      "maxPrice": "100000000000",
      "tickSize": "0.0001",
      "minExchangeValue": "4.91",
      "minAmount": null,
      "maxAmount": null
    }
  ],
  "orderMethods": [
    "LIMIT",
    "STOP_LIMIT"
  ],
  "displayFormat": "#,##0.0000"
}
```

**Comment by yunusseemre** [comment]
> Güncelleme yayınlandı. Kontrol edebilir misiniz?

"BTCTRY"

{"id":1,"name":"BTCTRY","nameNormalized":"BTC_TRY","status":"TRADING","numerator":"BTC","denominator":"TRY","numeratorScale":8,"denominatorScale":2,"hasFraction":false,

"ETHTRY" 

{"id":3,"name":"ETHTRY","nameNormalized":"ETH_TRY","status":"TRADING","numerator":"ETH","denominator":"TRY","numeratorScale":8,"denominatorScale":2,"hasFraction":false,

denominatorScale değerlerinin 0 olması gerekmez mi ?

**Comment by onurgozupek** [comment]
> denominatorScale değerlerinin 0 olması gerekmez mi ?

Biraz yukarıda bu sorunuzun cevabı var: https://github.com/BTCTrader/broker-api-docs/issues/205#issuecomment-617843758

**Comment by yunusseemre** [comment]
> > denominatorScale değerlerinin 0 olması gerekmez mi ?
> 
> Biraz yukarıda bu sorunuzun cevabı var: [#205 (comment)](https://github.com/BTCTrader/broker-api-docs/issues/205#issuecomment-617843758)

BTCUSDT parametresinde de hasFraction:false fiyatın virgülden sonrası olmadığı için denominatorScale değeri 0.

BTCTRY ve ETHTRY de durumun öyle olması gerektiğini düşünmüştüm

**Comment by onurgozupek** [comment]
denominatorScale noktadan sonra kaç hane olabileceğinin bilgisini veriyor. hasFraction ise fiyatın küsüratlı mı yoksa tam sayı mı olduğunu belirliyor. hasFraction: false ise fiyat küsüratlı değildir. Bu durumda denominatorScale geçersiz kılınıyor. hasFraction: true ise fiyat küsüratlıdır ve bu durumda denominatorScale değeri geçerli oluyor.

**Comment by ErrorEater** [comment]
> denominatorScale noktadan sonra kaç hane olabileceğinin bilgisini veriyor. hasFraction ise fiyatın küsüratlı mı yoksa tam sayı mı olduğunu belirliyor. hasFraction: false ise fiyat küsüratlı değildir. Bu durumda denominatorScale geçersiz kılınıyor. hasFraction: true ise fiyat küsüratlıdır ve bu durumda denominatorScale değeri geçerli oluyor.

**"ETHUSDT"**
"denominatorScale": 1,
"hasFraction": true,
"minPrice": "0.01"

Girebileceğim fiyat virgülden sonra 1 hane iken "minPrice" neden "0.01"? "minPrice"'ın gerçekte bir kullanım alanı var mı, herhangi bir hesaplamada?
"minPrice" böyle bir çok yerde hatalı. Fiyat hesaplamaları "minPrice" hanesini dikkate alarak yapıyoruz fakat minPrice'ın kendisi hatalı ve gereksiz fixlemeler yapmak zorunda kalıyoruz.
Lütfen isimlendirmede standartlara uyumlu kalın, belirttiğiniz değerlerde kullanımı olmayan değerleri listeden çıkartın.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
