### ISSUE TITLE
api uzerinden alim/satimda sorun 

### ISSUE THREAD

**Issue by alsanf** [BTCTrader/broker-api-docs#207]
Merhaba tekrar,
api uzerinden alimda yine sorun yasadim.
header ve body asagidaki sekilde.
order'in success olmamasi durumunda 200ms araliklarla 3kere emri yeniden girmeyi denedim 3 denemede de ayni hatayi aldim.
bu emri verdigim esnada herhangi bir acik emrim veya hesabimda bloke yoktu. 
hesabimin uygunlugunu teyit etmek icin asagidaki denemelerden yaklasik 15dk sonra bir emir denemesi daha yaptim, onda sorun olmadi ve sorunun hesabindan kaynaklanmadigini teyit ettim.

```
04:41:29,749 [INFO ] - btcturk info: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Vary: Origin
  Vary: Access-Control-Request-Method
  Vary: Access-Control-Request-Headers
  pragma: no-cache
  access-control-allow-credentials: true
  access-control-expose-headers: X-Content-Type-Options, X-Frame-Options, X-XSS-Protection, Date, Transfer-Encoding, Vary
  strict-transport-security: max-age=31536000; includeSubDomains; preload
  x-content-type-options: nosniff
  x-frame-options: DENY
  x-xss-protection: 1; mode=block
  api-supported-versions: 1.0, 2.0
  CF-Cache-Status: DYNAMIC
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  CF-RAY: 5883e1ef7e30a834-IST
  cf-request-id: 02464b89ad0000a8347d051200000001
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  Date: Thu, 23 Apr 2020 01:41:30 GMT
  Set-Cookie: __cfduid=dcaa8dc60f66262c9ad360168c82734741587606090; expires=Sat, 23-May-20 01:41:30 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax
  Server: cloudflare
  Content-Type: application/json; charset=utf-8
}

04:41:29,778 [INFO ] - content: {"success":false,"message":"FAILED_ORDER_WITH_OPEN_ORDERS","code":1122}
```

**Comment by alsanf** [comment]
merhaba,
sorun icin btcturk sitesi ile mail araciligi bir gorusmem oldu.
sorunun mevcut bakiyemin tumunu kullanmaya calisacak sekilde emir vermemden kaynaklanabilecegini ilettiler.
ben komisyonu olmasi gereken yuzde ile hesaplayarak mevcut bakiyem ile ne kadar alim yapabilecegimi hesapliyorken, bunun yerine bu hesapta komisyonu max deger uzerinden kullanmam gerektigini paylastilar. 
bu sekilde yapip takip ediyor olacagim.
benzer sorun yasayan veya yasayacak arkadaslar icin paylasmak istedim.

**Comment by nutcracker9999** [comment]
Ben de zaman zaman (ama her zaman değil) satış emirleri gerçekleşmiyordu. Bunu ben de bir kontrol edeyim. Bilgi için çok teşekkürler. Problem bundan kaynaklanıyor olabilir.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
