### ISSUE TITLE
Trade yön bilgisi

### ISSUE THREAD

**Issue by ErrorEater** [BTCTrader/broker-api-docs#208]
Trade kanalından gelen verilerde ilgili trade işlemine ait yön bilgisi yer almıyor.
Kullanıcı arayüzünde de renklendirmelerin bir önceki değere bağlı olarak yapıldığı, gerçek bir yön bilgisi vermediği görülüyor.
Bu veriyi eklemek gibi bir planınız var mı?

**Comment by ErrorEater** [comment]
27.04.2020 gece yarısı itibariyle sanırım yön bilgisi artık geliyor.
Satış yönü için Amount negatif olarak belirtilmiş görünüyor.
Teşekkürler.

**Comment by mhelvacikoylu** [comment]
Yön bilgisi için pozitif negatif kontrolü yerine yeni eklenen S değişkenine (0 veya 1 olma durumu) bakarak kontrol edin

**Comment by ErrorEater** [comment]
0: Buy order kaynaklı işlem
1: Sell order kaynaklı işlem
olarak mı değerlendirilmeli?

**Comment by mhelvacikoylu** [comment]
Evet. S: 0 için buy, S: 1 için sell
