### ISSUE TITLE
API üzerinden emir gönderiminde sorun yaşıyoruz.

### ISSUE THREAD

**Issue by bt-cs** [BTCTrader/broker-api-docs#209]
Ortalama dün akşamdan beri api üzerinden gönderilen emirlerde bir dengesizlik durumu var. Önceden bir problem yoktu fakat dün akşamdan itibaren bu tip sorunlar olmaya başladı.

**Comment by ErrorEater** [comment]
Böyle geniş soru sorarak alacağınız cevap da ona benzer işinize yaramayacak bir cevap olur.
Detay verirseniz sorununuz daha anlaşılır olur.
Ne veri gönderdiğinizi, ne cevap aldığınızı en azından yazarsanız bir yardım eden çıkabilir.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
