### ISSUE TITLE
Account Balance endpoint returns HTML instead of JSON

### ISSUE THREAD

**Issue by mbaytas** [BTCTrader/broker-api-docs#21]
Requests to the Account Balance endpoint (https://www.btcturk.com/api/balance) get an HTML response instead of JSON.

Code issuing request (in Google Apps Script / JavaScript):

    var ts = Date.now().toString();
    var url = "https://www.btcturk.com/api/balance";
    
    // Create and encrypt signature
    var plaintext = API_KEY + ts;
    var signature = Utilities.base64Encode(
        (Utilities.computeHmacSha256Signature(plaintext, API_SECRET));

    // Build and make request
    var options = {
        'method': 'GET',
        'headers' : {
            'X-PCK': BTCTURK_API_KEY,
            'X-Stamp': ts,
            'X-Signature': signature
        }
    };
  
    var responseJson = UrlFetchApp.fetch(url, options); 
    return responseJson.toString();

The response:

    <!DOCTYPE html>
    <html xmlns=""http://www.w3.org/1999/xhtml"">
    <head>
        <script type=""text/javascript"">
            window.location.href = window.location.protocol + '//' + window.location.host;
        </script>
    </head>
    <body>
        <div>Sitemizi kullanabilmeniz için kullandığınız tarayıcı ayarlarında Javascript'ı aktifleştirip siteyi yenileyiniz.</div>
    </body>
    </html>

**Comment by hanifidemirel** [comment]
Ben de aynı sorunu yaşıyorum. İlgilenen yok heralde artık kodla

**Comment by nepnesomao** [comment]
Gönderdiğiniz Google App Script kodunu denedik.  Google App Script tarafında çözüm bulamadık.

Örnek olması açısından C# ve PHP kodunu paylaşıyorum;
using (var client = new HttpClient())
{
	var unixTimestamp = DateTime.UtcNow.Ticks;
	
     string message = API_KEY + unixTimestamp;

    using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(API_SECRET)))
    {
        byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
        string signature = Convert.ToBase64String(signatureBytes);

        client.DefaultRequestHeaders.Add("X-PCK", API_KEY);
        client.DefaultRequestHeaders.Add("X-Stamp", unixTimestamp.ToString());
        client.DefaultRequestHeaders.Add("X-Signature", signature);
        client.BaseAddress = new Uri("https://www.btcturk.com/");

    }
	
    using (var response = client.GetAsync("api/balance"))
    {
        if (response != null)
        {
            var response = response.Result.Content.ReadAsStringAsync().Result;           
        }
    }
} 

$message=$APIKey.time();
$signatureBytes = hash_hmac('sha256', $message, base64_decode($privateKey), TRUE);
$signature=base64_encode($signatureBytes);
function authGetsell($uri, $price, $amount) {
$url=$GLOBALS['baseURL'].$uri;
$nonce=time();
$headers=array(
'X-PCK: '.$GLOBALS['APIKey'],
'X-Stamp: '.$nonce,
'X-Signature: '.$GLOBALS['signature']
);
$ch=null;
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
$result=curl_exec($ch);
 curl_close($ch);
return json_decode($result, true);

**Comment by hanifidemirel** [comment]
Python da urllib modulunu kullanıyorum. Orada da sıkıntılı

**Comment by mss1451** [comment]
Sürekli hata döndürüyor ve 200 OK dönse bile JSON yerine HTML alıyorum.
500 Internal Server Error
403 Forbidden Error
Request limit exceeded
Verdiğiniz kodun aynısını denedim ama yine olmuyor. C# ve Java ile denedim ve her ayrıntıyı kontrol ettim üstelik belki bloke olmuştur diye IP de değiştirip durdum ama hala sonuç yok. Bu kadar eziyetli olması hayal kırıklığı yaşattı açıkçası.

**Comment by suleymanbyzt** [comment]
Merhaba,

Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
