### ISSUE TITLE
24 SAATTİR INTERNAL_ERROR 500

### ISSUE THREAD

**Issue by gringo06** [BTCTrader/broker-api-docs#210]
Merhaba yaklaşık 24 saattir ALL ORDER sorgusunda ınternal error 500 hatası alıyorum. V1 diğer tüm sorguları çalışıyor. Http client .Timeout düşüyor. Timeout süresini kaldırınca yaklaşık 8 sanıye sonra bazen internal error cok nadiren data gönderiyor. iyi çalışmalar.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
