### ISSUE TITLE
hasFraction false olan çiftlerden  (StopPrice ) order input sorunu

### ISSUE THREAD

**Issue by gringo06** [BTCTrader/broker-api-docs#211]
public class OrderInput
    {
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal StopPrice { get; set; }
        public string NewOrderClientId { get; set; }
        public OrderMethod OrderMethod { get; set; }
        public OrderType OrderType { get; set; }
        public string PairSymbol { get; set; }
    }
Yukarda oluşan order input nesnesinde hasFraction false olan(BTC ve ETH) için StopPrice decimal veri hata döndürüyor. String, double yada int olunca kabul ediyor. Bu da bizim input dongülerimizde farklı nesne ve  hasFraction kontrolü yapmamıza sebeb oluyor. Sadece STOP_MARKET ve STOP_LİMİT emirlerinde decimal veri kabul etmiyor.(virgülsüz, kesirsiz hasFraction olmadan yolladığımız halde,  ). Mesala market alış emirlerinde decimal veriyi kabul ederken sadece StopPrice emirlerinde  karşılaşıyoruz bu sorunla . Diğer tüm alış satış modellerinde yukardaki class  içindeki değer tipleri onay alıyor. Bu konu hakkında StopPrice emirleri için decimal veriyi de kabul edebilecek(kesirsiz decimal veri) bir çalışma yapabilirmisiniz. Ya da sizlerin öneriniz nedir. Çok teşekkürler.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
