### ISSUE TITLE
Emirleri listeye eklemiyor 

### ISSUE THREAD

**Issue by Cagatay342** [BTCTrader/broker-api-docs#212]
Merhaba belki sorun daha fazladir devam ediyor ama suan hizlandiginda farkettim .Sisteme sorunsuz emir giriyorum web sitesinde gozukuyor acik emirlerde fakat emir listesine eklmeiyor en iyi teklif bende olmasina ragmen kotu tekliflerden islem yapiyor.24 unde 100 lerce emir girdim fakat sistemde emir gecmisimden sorgulama yaptigimda hicbir emir listelemiyor.
<img width="1680" alt="Screen Shot 2020-04-29 at 21 09 31" src="https://user-images.githubusercontent.com/5398334/80635380-7b680a00-8a64-11ea-9621-e6ba975e75a1.png">
<img width="1680" alt="Screen Shot 2020-04-29 at 21 10 00" src="https://user-images.githubusercontent.com/5398334/80635391-7efb9100-8a64-11ea-9762-3f1299e8abcd.png">
<img width="1680" alt="Screen Shot 2020-04-29 at 21 24 23" src="https://user-images.githubusercontent.com/5398334/80635395-7f942780-8a64-11ea-82a3-b8eb1bb891b3.png">

**Comment by Cagatay342** [comment]
@BTCTraderAdmin Omer Cinbat beyi buraya ekleyemedim

**Comment by Cagatay342** [comment]
@ocinbat hocam yetis :)

**Comment by alsanf** [comment]
edge'den emir girisi yapiyorsaniz, popup'lar engelleniyor olabilir. normalde emir girisi sonrasi bir confirmasyon dialog'unun gelmesi gerekiyor bildigim kadari ile.
baska bir browser ile deneyebilirsiniz.
