### ISSUE TITLE
Kullanıcı güncel komisyon oranları için adres?

### ISSUE THREAD

**Issue by ErrorEater** [BTCTrader/broker-api-docs#213]
O anki kullanıcı komisyon oranlarını (maker & taker) alabileceğimiz bir adres var mı?

**Comment by ErrorEater** [comment]
Galiba buradan ama dokümantasyonda herhangi bir bilgi yok.
https://api.btcturk.com/api/v2/account/commissions

Bu adres v2 olduğu için yeni authentication mekanizması ile ilgili bilgi gerekiyor fakat hiç bir yerde bir bilgi bulunmuyor.
v1'de kullanıcının komisyon bilgisine ulaşmanın bir yolu var mı?

**Comment by ErrorEater** [comment]
Yukarıdaki adresten API yoluyla komisyon bilgisi almak isteyenler veya v2'yi kullanmak isteyenler için geçici çözüm;
Normal web üzerinden login olurken F12 Network sekmesinden;
https://api.btcturk.com/api/v2/token
adresinden dönen **access_token** verisini ve veriyi aldığınız zaman bilgisi, **now + expires_in=3600** süresini saklayın.
3600 saniyelik süre = 1 saat boyunca bu token ile işlem yapabilirsiniz.

İşlem yapmak demek request header'a;
**Authorization: Bearer eyJhbGciOiJ.....**
şeklinde tokenı ekleyerek talepleri göndermek demek.

Ancak süre aşımı olursa yani 1 saat içinde tokenı refresh etmemişseniz tekrar login olup geçerli bir token almanız gerekecek. Biraz gereksiz bir iş API kullananlar için. v1'deki imzalama mekanizması daha uygun API için.

Benzer şekilde kullanıcı adı ve şifre ile login olarak token almayı sağlayacak **code** değerini almak da mümkün ama SMS doğrulama gibi engeller var. Belki Google Authenticator ile girişe çevirip kod üretme de otomatize edilebilir ama o kısmı denemediğimden login kısmını atlayıp 1 kere token aldıktan sonra sürekli canlı tutarak işlem yapmak daha kestirme görünüyor şimdilik.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
