### ISSUE TITLE
V1 api için 401-Unauthorized Hatası (Örnek Kod' un kendisinde)

### ISSUE THREAD

**Issue by ahomag** [BTCTrader/broker-api-docs#214]
Merhabalar, 
broker-api-csharp-v2 örnek projeyi indirerek APIExampleV1 projesinde ki json dosyasında gerekli alanları doldurdum. Ip adresi kısıtlaması vermedim yani boş bırakarak api key oluşturdum. 
Projeyi çalıştırdığımda proje içinde ki servislerden Çalışanlar (GetTicker,GetOrderBook,GetLastTrades,GetDailyOhlc)
Ancak (GetBalances, GetUserTrades, GetUserFiatTransactions, GetUserCryptoTransactions ) prosedürleri ise çalışmıyor. 
Geri dönüş mesaajı olarak Code:401, Message: "Unauthorized" alıyorum. Success :false olarak görünüyor. Bazı arkadaşlar Success : true ve Mesaj kısmında ise "Unauthorized" den sonra ekstra bir yazı olduğunu belirtmişler ancak ben sadece "Unauthorized" mesajı alıyorum. 
C# örnek proje üzerinde test yapıyorum ve canlı bağlantıdayım. 
Nereleri kontrol edebilirim ? 
Teşekkürler.

**Comment by outlier-1** [comment]
> Ip adresi kısıtlaması vermedim yani boş bırakarak api key oluşturdum.

Merhaba, api key oluşturma işlemi kara liste değil de beyaz liste mantığıyla çalışıyor, oraya verdiğiniz ip kısıtlanmıyor. Yalnızca oraya verdiğiniz ip üzerinden api'ya erişebiliyorsunuz. Eğer api key oluştururken dediğiniz gibi bir ip vermeyip boş bıraktıysanız o api anahtarıyla dediğiniz işlemlerde unauthorized hatası almanız doğal.

API anahtarı oluştururken bağlantıyı kullanacağınız ip adresini vererek oluşturup gerekli izinleri verdikten sonra yukarıdaki işlemleri tekrar deneyin.

**Comment by ahomag** [comment]
@outlier-1 cevap için teşekkürler. Ancak ip adresi vererek' de denemiştim. Bu bilgiyi yazmadım çünkü daha önceki post' larda buna benzer bir durum oluşmuş, hatayı alan arkadaşa ise ip adresi alanını boş bırakarak işlem yapması önerilmiş. İlk olarak apiyi denereken ip adesi vererek denedim ama yine aynı problem ile karşılaştım. Aklıma sadece kablonet internet sağlayıcısı kullandığım ve bana gösterdiği ip adresi ile gerçek ip adresimin aynı olmama durumu geliyor ama onu nasıl tespit ederim bilemiyorum. 
Başka bir çözüm öneriniz var mıdır ?
teşekkürler.

**Comment by mrakblt** [comment]
Merhabalar, umarım konuyu kirletmiyorumdur. @ahomag' in bahsettiği unauthorized ve `success: true` v2 api'sinde yanlış key girerek submit order yapmak istediğimde alıyorum buradaki success'in true olması hakkında bilgisi olan varsa paylaşabilir mi?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
