### ISSUE TITLE
All Orders sadece "closed" sonuçları getiriyor

### ISSUE THREAD

**Issue by ermanertas** [BTCTrader/broker-api-docs#215]
normalde partial, untouched, canceled getiriyordu, bugün max 50 adet ve sadece closed sonuçları getirmeye başladı, bir kısıtlama mı geldi?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
