### ISSUE TITLE
Unofficial API v2

### ISSUE THREAD

**Issue by ErrorEater** [BTCTrader/broker-api-docs#216]
Öncelikle, yetersiz dokümantasyon ve düşük ilgili destek ekibi nedeniyle API v2, adı olan ama cismi olmayan bir hayalet durumunda görünüyor.
Bu halde iken birilerinin bir şeyler yapmasını aylarca beklemektense oturup birkaç saatte, ihtiyacı olanların da faydasına olabileceğini düşündüğüm benim de ihtiyacımı karşılayan API v2 çalışmasını web işleyişini tersine mühendislik ile çözümleyerek elde ettim.
İhtiyacı olanlara faydalı olmasını dilerim.

Bu API'de en zahmetli kısım **"access_token"** almaktır çünkü tüm işleyiş bu tokenın varlığına bağlıdır ve bir kaç adımdan oluşmaktadır.
API v1'de böyle sürekli token almaya/yenilemeye gerek yoktur ve bence **"access_token"** BtcTurk için robot yazmak isteyenlere gereksiz uğraş bindirmektedir.

**1) Login adımı.**
BtcTurk'e web sayfasından login olurken kullandığınız email adresinizi ve şifrenizi aşağıdaki adrese gönderin.

```
HttpMethod.Post, "https://sso.btcturk.com/login", "application/x-www-form-urlencoded"
{
	{"Username", username},
	{"Password", password},
}
```

**2) Tek kullanımlık şifre ile girişi onaylama adımı.**

Bu aşamada hesabınızı SMS şifresi ile girme yönteminden zaman bazlı tek kullanımlık şifre üreteci ile girme yöntemine çevirmiş olmanız gerekiyor.
Bunun amacı, SMS bekleyip elle gelen kodu girmek yerine zaman bazlı tek kullanımlık şifre üretici ile hızlıca gerekli şifreyi üretip bir sonraki adıma geçmektir.

Hesap ayarlarınızdan, Authenticator'a geçiş yaparken ekranda çıkan QR kodun sağındaki "Elle girmek için" alanında yazan **sarı renkli kodu** kaydedin.
Eğer daha önceden Authenticator'a geçiş yaptıysanız ve QR kodunu kaydettiyseniz onun içeriğini okutun ve **"secret"** ile belirtilen kodu kaydedin.
Bu kod, Authenticator'da tek kullanımlık şifreyi üretmek için gereken **"secret key"** dir.

Aşağıdaki adresten işinizi görecek authenticatorı indirebilirsiniz.
https://www.nuget.org/packages/GoogleAuthenticator/

Ürettiğiniz pin kodunu aşağıdaki adrese gönderin.

```
HttpMethod.Post, "https://sso.btcturk.com/login/otp-authenticator", "application/x-www-form-urlencoded"
{
	{"AuthCode", pin}
}
```

Başarılı cevap durumunda HTTP 302 ile yönlendirilen adres "code" verisini içerecektir. Bu veri **"access_token"** almak için gereklidir.

https://pro.btcturk.com/?code=9e80a711af33f46298a3d7f971eca1b7e97767a564c022f0e44689ecc3c122a21&scope=openid%20offline_access&state=tr-TR,Dark,Basic&session_state=118sJe4V1nfhcJPc22fF8KQxnjUIw6idG1811FTCls.111bc07fcae8721172221ef93441250

**3) Access token alma adımı.**
Aşağıdaki adrese, önceki adımda yönlendirilen adresle gelen **"code"** verisini yine aşağıdaki diğer verilerle beraber **"json"** olarak gönderin.
Önceki adımların verileri **"form-urlencoded"** olarak gönderilmelidir!

```
HttpMethod.Post, "/api/v2/token", "application/json"
{
	{"code", code},
	{"client_id", "btcturk"},
	{"scope", "openid offline_access"},
	{"state", "tr-TR"},
	{"redirect_uri", "https://pro.btcturk.com"},
}
```

Dönen cevapta API v2'deki tüm ihtiyacınız olan işlemleri yapacağınız **"access_token"** verisini bulacaksınız.
İlgili API v2 işlemi yapmak için bu tokeni request header'a şu şekilde eklemeniz yeterlidir.
Authorization: Bearer eyJhbGciO...

**4) Access token yenileme.**
Süresi dolmak üzere olan ama henüz süresi dolmamış mevcut **"access_token"**'ınızı yenileyerek tekrardan login olmadan işlemlerinizi yapmaya devam edebilirsiniz.
Bunun için; mevcut **"access_token"**'ınızı request header'a ekleyip önceki adımda gelen **"refresh_token"** verisiyle beraber talebi gönderip yeni **"access_token"**'ınızı alabilirsiniz.

```
Authorization: Bearer eyJhbGciO...
HttpMethod.Post, "api/v2/token/refresh", "application/json"
{
	{"token", refreshToken}
}
```

**5) Bazı API v2 adresleri.**

Her seferinde **"access_token"**'ınızın request header'a eklenmesi gerekmektedir.
Authorization: Bearer eyJhbGciO...

https://api.btcturk.com/api/v2/account/commissions
https://api.btcturk.com/api/v2/account/balances
https://api.btcturk.com/api/v2/openOrders?pairSymbol=BTCTRY

**6) WebSocket ile login** olabilmeniz için "access_token"'ı "." noktalardan bölüp elde edeceğiniz 3 veriden 2. veriyi Base64 decode edip, içerisinden "sub" ile belirtilen "id" (user id) ve "email" ile belirtilen "username" verilerini alın. Bunlar WebSocket ile login olmada gereken verilerdir.

`[111,{"type":111,"id":123456,"token":"eyJhbGciO...","username":"xxx@hotmail.com"}]`

**SON**

**Comment by onurgozupek** [comment]
Merhaba, API v2 şu an tüm özellikleriyle son kullanıcıya açık olmadığı için API v2 ile ilgili dokümantasyon henüz hazır değil. Sizin de belirttiğiniz gibi henüz Authentication yapabileceğiniz bir arayüz ya da uçnoktası yok. (Bu nedenle kendi kendinize tarayıcınızın veri deposundan token alıp onu kullanmaya çalışıyorsunuz) API v2 kullanıcıların erişimi için hazır olduğunda dokümanları yayınlanacak. Şimdilik BtcTurk | PRO API v1 üzerinden işlem yapabilirsiniz.

**Comment by ErrorEater** [comment]
> (Bu nedenle kendi kendinize tarayıcınızın veri deposundan token alıp onu kullanmaya çalışıyorsunuz)

Yazdıklarımı okumadığınız için bu cevabınız normal.
Tam tersine email, password ile nasıl token oluşturulduğunu anlatıyorum.

**Comment by umitk** [comment]
Merhaba, çalışma için çok teşekkürler. Güzel doküman olmuş :)

**Comment by yemreak** [comment]
@aliveli186  Merhabalar, **4. adımdaki Access token yenileme** kısmında istenileni yapmama rağmen aşağıdaki hatayı almaktayım.

> _Ek olarak: Komisyon miktarlarını alma gibi `access_token` isteyen işlemlerde sorun yok, verilerim doğrudur_

**Yaptıklarım:**

```py
url = f"{API_BASE}/api/v2/token/refresh"
session.headers.update({"authorization": f"{token_type} {access_token}", "content-type": "application/json"})
response = session.post(url, data={"token": refresh_token})
pprint(response.json())
```
**Sonuç:**

```python
{'code': 500, 'message': 'INTERNAL_ERROR', 'success': False}
```

**Comment by umitk** [comment]
@aliveli186 @YEmreAk
Merhaba, 1. Adımı geçebiliyor musunuz? Ben bir süredir cloudflare takıldığım için daha ilk adımda 503 hatası alıyorum.

**Comment by yemreak** [comment]
Merhabalar,

Ben `access_token` bilgisini manuel olarak, tarayıcı üzerinde geliştirici araçlarında yer alan `Application` `Storage` `Local Storage` içerisinde yer alan `btcUser`, değişkeninden aldım. Otomatik olarak alma işlemine tokeni kullanabildiğimden emin olduktan sonra bakacağım.
@umitk

**Comment by alikurt87** [comment]
@aliveli186 emeğine sağlık

**Comment by yemreak** [comment]
Merhabalar @alikurt87 bey, eğer anlatılanı başarılı bir şekilde yapabildiyseniz yukarıdaki soruma çözümünüz var mıdır acaba?

**Comment by alikurt87** [comment]
> Merhabalar @alikurt87 bey, eğer anlatılanı başarılı bir şekilde yapabildiyseniz yukarıdaki soruma çözümünüz var mıdır acaba?

iyi akşamlar @yedhrab, BTCtürk websocket ile Auth giriş yaptım ama bir sonraki data sorgularımda , istediğim datayı alamadım,Çok zaman harcadım,BTCtürk ün az döküman ile ilerleyemedim, BTCtürk ile  websocket kullanmaktan vazgeçtim. Sebebi zayıf döküman,github soru cevap,istediğin cevap yok,saçma  cevaplar neyse  ,bir çok trade/site kendi kütüphanesini sunuyor bir çok dilde, Bence farklı global sştelere yönelebilirsin, BTCtürk daha sonra ...

**Comment by yemreak** [comment]
@alikurt87 Teşekkür ederim açıklamanız için

**Comment by cantaylancapraz** [comment]
@aliveli186 Buradaki yöntem birden 503 almaya başladı, genel bir sorun gördünüz mü siz?

**Comment by SelcukCode** [comment]
@aliveli186 Bey, v2'nin v1'e nazaran bir avantajı varsa kullanıp test etmek isterim. Token alma süreci haricinde deneyimlerinizi artı, eksi yönler şeklinde paylaşabilir misiniz?

Şimdiden teşekkürler.

**Comment by ErrorEater** [comment]
> @aliveli186 Bey, v2'nin v1'e nazaran bir avantajı varsa kullanıp test etmek isterim. Token alma süreci haricinde deneyimlerinizi artı, eksi yönler şeklinde paylaşabilir misiniz?

1 seneyi geçti BtcTurk API'sine bakmadım, kullanmadım. Bu makaleyi yazdıktan sonra bazı değişiklikler olduğunu gördüm fakat üzerine düşmedim o nedenle buradaki sorulara cevap veremiyorum.

v2 BtcTurk'ün web sitesinin kullandığı API olduğu için ve v1'de komisyon ve bakiyeleri görme imkanı olmadığı için v2 daha işe yarardı benim için.

**Comment by vhdmsm** [comment]
This is really bad that we can't login to websocket auth using public key! and still no way to obtain access_token from API!

**Comment by UmutDP** [comment]
Merhaba hocam iyi günler. Mevcut login sistemine göre token nasıl alabilirim. Yardımcı olabilir misiniz?

**Comment by ocinbat** [comment]
BtcTurk'ün son kullanıcıya sunduğu API endpointleri aşağıdaki dokümantasyonda listeleniyor.
Burada olmayan endpointlerin herhangi bir anda değiştirilebileceğini varsayarak bunlar dışındakiler kullanmamanızı öneriyoruz.
Dokümantasyonda kullanıcı adı ve şifre olmadan nasıl authentication yapacağınız örnek kodlarla anlatılıyor.

https://docs.btcturk.com/

Linkindeki dokümantasyondan destek alabilirsiniz.
