### ISSUE TITLE
453 OrderUpdate

### ISSUE THREAD

**Issue by ErrorEater** [BTCTrader/broker-api-docs#217]
453 OrderUpdate hangi durumda geliyor tam olarak?
API'de emir güncelleme komutu yok görünüyor, bu durumda bu mesajın gelmesine neden olan koşul nedir?

**Comment by mhelvacikoylu** [comment]
Herhangi bir cihazdan açık olan emrinizi editlediğinizde diğer bağlı cihazlarınızın da bu durumdan anlık haberdar olması için gönderilir.

**Comment by ErrorEater** [comment]
> Herhangi bir cihazdan açık olan emrinizi editlediğinizde diğer bağlı cihazlarınızın da bu durumdan anlık haberdar olması için gönderilir.

1) API v1'de gönderilen orderı editleme mümkün mü?
2) Bir emir editlendiğinde order book'taki işlem görme sırasını kaybeder mi?
3) Order book çalışma mantığınızda işlem görme sırası ilk gelen emir ilk işlem görür şeklinde mi yoksa hacmi yüksek olan emir ilk işlem görür şeklinde mi?

**Comment by mhelvacikoylu** [comment]
1. Mümkün. Emir nereden girilirse girilsin edtilenebilir. Tabi Api v1'de editleme yok. Editleme işlemini v2 ile yapmanız gerekiyor.
2. Kaybeder. Editlendiğinde sanki emir editlediğiniz anda girilmiş gibi işlem görür.
3. İşlem görme sırası en iyi fiyattır. Eğer ki fiyatlar aynı ise ilk giren ilk çıkar (FIFO)

**Comment by ErrorEater** [comment]
> 2. Kaybeder. Editlendiğinde sanki emir editlediğiniz anda girilmiş gibi işlem görür.

Bu şekilde yapıyorsanız hatalı yapıyorsunuz (finansal standartlara göre). Çünkü emir güncellemenin mantığı execution sırasını kaybetmeden miktarı değiştirebilmektir yoksa sizde olduğu gibi cancel edip yeniden emir girmekten bir farkı olmaz güncellemenin.
Sizin aklınızdaki güncelleme mantığı kullanıcının UI'da 2 işlem yapmadan 1 işlemle değişiklik yapması ama finansal sistemlerde emri güncelleme mantığı bu değil. Bilginize.

**Comment by mhelvacikoylu** [comment]
BtcTurk'te emir değişikliğinde yalnızca emir fiyatı değiştirilir. Emir fiyatı değiştirilmesi durumunda da önceliği kaybedersiniz. Aynı kural borsa istanbul için de geçerlidir. Buradan görebilirsiniz.

https://www.borsaistanbul.com/urunler-ve-piyasalar/piyasalar/borclanma-araclari-piyasasi/kesin-alim-satim-pazari/emir-kurallari

**Comment by ErrorEater** [comment]
> BtcTurk'te emir değişikliğinde yalnızca emir fiyatı değiştirilir. Emir fiyatı değiştirilmesi durumunda da önceliği kaybedersiniz. Aynı kural borsa istanbul için de geçerlidir. Buradan görebilirsiniz.

Önceki mesajımdaki hatalı yapıyorsunuz kısmını geri çekiyorum çünkü sadece fiyat değiştirmeye izin verdiğinizi bilmiyordum, almak/satmak istenen miktarın değiştirildiğini düşünmüştüm çünkü miktar değişiminde execution sırası genelde kaybedilmez.


> https://www.borsaistanbul.com/urunler-ve-piyasalar/piyasalar/borclanma-araclari-piyasasi/kesin-alim-satim-pazari/emir-kurallari

> Emrin fiyatındaki/getirisindeki değişiklik, nominal tutarındaki artış ve işlem hesap sahibinin değişimi zaman önceliğinin kaybedilmesine neden olurken, temsilci referansı değişimi ve nominal tutarın azaltılması emrin önceliğinin kaybedilmesi sonucunu doğurmaz.

Bu gönderdiğiniz açıklama; fiyat veya getiride (fiyat x miktar) değişiklik eğer artışa sebep oluyorsa execution sırasının kaybedildiğini ancak azalışa sebep oluyorsa execution sırasının kaybedilmediğini söylüyor.
Sizde buradaki artış veya azalış kriterini dikkate alma söz konusu değil, her türlü değişiklik execution sırasının kaybedilmesi ile sonuçlanıyor diye anlıyorum.

**Diğer bir soru:**
Eğer girilen emir parçalı gerçekleşmişse kalan miktar için güncelleme emri verilebiliyor mu?

**Comment by mhelvacikoylu** [comment]
Verilebiliyor. Kalan miktarın da fiyatını editleyebiliyorsunuz.

**Comment by canerd7u** [comment]
> 1. Mümkün. Emir nereden girilirse girilsin edtilenebilir. Tabi Api v1'de editleme yok. Editleme işlemini v2 ile yapmanız gerekiyor.

@mhelvacikoylu 

Order güncellemek için v2 yi nasıl kullanacağız. Bu konu ile ilgili herhangi bir doküman bulunmuyor ?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
