### ISSUE TITLE
Request Limit Problemi

### ISSUE THREAD

**Issue by outlier-1** [BTCTrader/broker-api-docs#218]
Merhaba, aylardır kullandığım sistemde son 2 saattir btcturk api'ye istek atmakta problem yaşıyorum.

API'n bana döndüğü mesaj şu şekilde: 
`{\n"success": false,\n"message": "Too many requests",\n"code": 429\n}`

Son yaptığım ölçümde Synchronised bir şekilde her 0.5 saniyede bir request atarken  40.saniyede 69. isteğimin sonucunda bu hatayı tekrar aldım. 

API dökümantasyonunda ticker dışındaki fonksiyonlarda 100 ms'de 1 istek sınırı görünüyor. Test yaptığım şartlarda bu hatayı almamam gerektiğini düşünüyorum.

Problem neden olabilir? API'n kendisi ile ilgili bir problem mi var ya da request limitleriniz mi değişti?

Yardımcı olabilirseniz çok sevinirim.

İyi çalışmalar

Ekleme: Request atarken kullandığım endpoint /orderbook endpointi.

**Comment by ocinbat** [comment]
Merhaba,

Evet request limitlerimizde bir güncelleme yapıldı. Ekiplerimiz dokümantasyon üzerinde güncelleme için çalışıyorlar.

Kolay gelsin.

Sent from my iPhone

On 1 May 2020, at 21:45, Ömer Miraç Baydemir <notifications@github.com> wrote:

﻿

Merhaba, aylardır kullandığım sistemde son 2 saattir btcturk api'ye istek atmakta problem yaşıyorum.

API'n bana döndüğü mesaj şu şekilde:
{\n"success": false,\n"message": "Too many requests",\n"code": 429\n}
Son yaptığım ölçümde Synchronised bir şekilde her 0.5 saniyede bir request atarken 40.saniyede 69. isteğimin sonucunda bu hatayı tekrar aldım.

API dökümantasyonunda ticker dışındaki fonksiyonlarda 100 ms'de 1 istek sınırı görünüyor. Test yaptığım şartlarda bu hatayı almamam gerektiğini düşünüyorum.

Problem neden olabilir? API'n kendisi ile ilgili bir problem mi var ya da request limitleriniz mi değişti?

Yardımcı olabilirseniz çok sevinirim.

İyi çalışmalar

**Comment by outlier-1** [comment]
Tamamdır takipteyim, cevabınız için teşekkürler

**Comment by ErrorEater** [comment]
> Son yaptığım ölçümde Synchronised bir şekilde her 0.5 saniyede bir request atarken 40.saniyede 69. isteğimin sonucunda bu hatayı tekrar aldım.

Bu şekilde sürekli belli aralıklarla sorgulamak yerine mümkünse web soket ile bağlanın. Sunucu her değişiklik olduğunda size verileri iletir. Limite takılma derdiniz olmaz.

**Comment by outlier-1** [comment]
Hem websocket hem de direk http ile 2 ayrı yerden çalışmamak için bu şekilde kullanıyordum. 
Malum websockette authentication gerektiren işlemler için access token gerekiyor. 
O tokeni oluşturma hizmetini de henüz canlıya almadılar sanırım birkaç ay önce aramış ama dökümantasyonlarda bununla ilgili bir şey bulamamıştım.

**Comment by outlier-1** [comment]
> > Son yaptığım ölçümde Synchronised bir şekilde her 0.5 saniyede bir request atarken 40.saniyede 69. isteğimin sonucunda bu hatayı tekrar aldım.
> 
> Bu şekilde sürekli belli aralıklarla sorgulamak yerine mümkünse web soket ile bağlanın. Sunucu her değişiklik olduğunda size verileri iletir. Limite takılma derdiniz olmaz.

Hem websocket hem de direk http ile 2 ayrı yerden çalışmamak için bu şekilde kullanıyordum.
Malum websockette authentication gerektiren işlemler için access token gerekiyor.
O tokeni oluşturma hizmetini de henüz canlıya almadılar sanırım birkaç ay önce aramış ama dökümantasyonlarda bununla ilgili bir şey bulamamıştım.

**Comment by ErrorEater** [comment]
> Hem websocket hem de direk http ile 2 ayrı yerden çalışmamak için bu şekilde kullanıyordum.
> Malum websockette authentication gerektiren işlemler için access token gerekiyor.
> O tokeni oluşturma hizmetini de henüz canlıya almadılar sanırım birkaç ay önce aramış ama dökümantasyonlarda bununla ilgili bir şey bulamamıştım.

Alttaki linkte email ve şifre ile nasıl **"access_token"** alındığını adım adım anlattım.
Ben web soketi öyle kullanıyorum şuan.

**[Unofficial API v2](https://github.com/BTCTrader/broker-api-docs/issues/216)**
https://github.com/BTCTrader/broker-api-docs/issues/216

**Comment by outlier-1** [comment]
Faydalı görünüyor, çok teşekkürler.

> Alttaki linkte email ve şifre ile nasıl **"access_token"** alındığını adım adım anlattım.
> Ben web soketi öyle kullanıyorum şuan.
> 
> **[Unofficial API v2](https://github.com/BTCTrader/broker-api-docs/issues/216)**
> #216

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
