### ISSUE TITLE
Api BTC ve ETH withdraw

### ISSUE THREAD

**Issue by ophiafagus** [BTCTrader/broker-api-docs#22]
Merhabalar;

Sitede api key oluştururken withdraw seçeneği olup olmaması soruluyor. Burdan hareketle withdraw özellğinin olduğunu varsayıyorum ama documentation'da withdraw fonksiyonunu bulamadım. Nasıl api key ile btc ve eth çekme işlemi yapabilirim yardımcı olabilir misiniz?

Teşekkürler

**Comment by nepnesomao** [comment]
Deposit ve withdrawal işlemleri sadece mobil uygulamalarımız üzerinden yapılmaktadır.

**Comment by ophiafagus** [comment]
Mobil uygulamanızı indirdim ama BTC ve ETH withdrawal işlemi yok?

**Comment by rapublik** [comment]
api üzerinden günlük/aylık  yatırma/çekme kalan limitlerine ve aylık toplam işlem hacmini nasıl çekebilirim?

**Comment by BTCTraderAdmin** [comment]
Şu an için malesef bu metodun API desteği yok. Ama öneri olarak alıp en
kısa zamanda eklemeye çalışalım.

**Comment by ophiafagus** [comment]
BTC ve ETH çekme konusunda yorumunuzu alabilir miyiz?

Bu konunun öneri olarak alınıp en kısa zamanda eklenmeye çalışılması mümkün mü?

**Comment by BTCTraderAdmin** [comment]
Elbette. Mobil uygulamaya kısa zamanda ekleyeceğiz ancak api için bir
güvenlik incelemesi yapmamız gerekiyor.

**Comment by serensoner** [comment]
Merhaba,

Mobil uygulamaya eklerken ayni zamanda api erisimine de acik hale getirmeniz mumkun mudur?

**Comment by serensoner** [comment]
merhaba,

bu konuda gelisme var mi acaba?

**Comment by serensoner** [comment]
Tejrar sorayim, bu konuda bir gelişme var mı?

**Comment by eraysaltik** [comment]
Ben de sorayım bir gelisme var mi acaba?

**Comment by suleymanbyzt** [comment]
Merhaba,

Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
