### ISSUE TITLE
APİ Dökümantasyonu türkçe yayınlansın !!

### ISSUE THREAD

**Issue by casimkarayilan** [BTCTrader/broker-api-docs#221]
Api dökümantasyonunun türkçe olarak yayınlanmasını istiyorum.

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
