### ISSUE TITLE
451 OrderInsert, 452 OrderDelete, 453 OrderUpdate emri tanımlayan yeterli bilgi döndürmüyor

### ISSUE THREAD

**Issue by ErrorEater** [BTCTrader/broker-api-docs#222]
Web Socket'te, **451 OrderInsert**, **452 OrderDelete**, **453 OrderUpdate** mesajlarlarında REST API ile gönderilen emir sonrası gelen cevaplarda hangi emrin bilgisi olduğuna dair net bir bilgi yer almıyor.

Mesela yeni emir verildiğinde gelen **451 OrderInsert** verisinde **"newOrderClientId"** bilgisi yok, dolayısıyla hangi emrin cevabı olduğu belirsiz.
Diyeceksiniz ki REST API'den dönen cevapta o bilgi var. Var ama web soketten gelen verinin REST API sonucundan önce bana ulaşmayacağının garantisini verebilir misiniz? Böyle bir durumda web soket verisi bana ulaştığında onu herhangi bir emirle ilişkilendiremem çünkü daha REST API cevabı bana ulaşmamış olacak.
Benzer şekilde 452, 453 emirlerini verirken de bir **"clientId"** belirtebilmeliyim ki hangi emrin cevabı olduğunu anlayabileyim. Aynı orderId'ye peş peşe 2 tane güncelleme talebi iletsem gelen cevabın hangi emrin cevabı olduğu belli olmayacak.

Ayrıca her cevapta emrin durumunu değiştiren her işlemin zaman bilgisi de gelmeli.

**Comment by SelcukCode** [comment]
Tam yeni bir issue açacaktım ki çok önceden açılmış olduğunu fark ettim. Ayrıca issue'lar arasında yorum olarak da farkedip isteyenlerin olduğunu gördüm. Örnek: https://github.com/BTCTrader/broker-api-docs/issues/353#issuecomment-778743282 Teknik ekip en azından bu issue altında bu sorunu görür ve düzeltir umarım. Açtığım issue'yu da tekrar olmaması açısından bu stream altına bırakıyorum.

### WebSocket 451 mesajına "clientId" eklenmesi talebi

441 Mesajı ile aynı şekilde 451 mesajına da "clientId" bilgisini ekler misiniz?

Emir verdiğimizde REST sorgusunun response'u gelmeden WebSocket'ten yanıt alabiliyoruz. Haliyle henüz elimizde REST'ten gelen OrderId bilgisi olmadığından WebSocket 451 mesajındaki id(yani OrderId) ile karşılaştırma yapamıyoruz. 

@BTCTraderAdmin @mhelvacikoylu @ocinbat @onurgozupek

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
