### ISSUE TITLE
"PARTIAL" emirler emir geçmişinde görünmüyor.

### ISSUE THREAD

**Issue by umitk** [BTCTrader/broker-api-docs#224]
Merhaba, "PARTIAL" yani kısmi tamamlanıp sonra iptal edilen emirlerim "/api/v1/allOrders" uç noktasının sorgu sonucunda dönmüyor. Aynı sorun web sitesi üzerinde de geçerli. "Alım-Satım" ekranlarında partial emirler görünürken, "Emir Geçmişim" ekranında yapılan sorgularda görünmüyor. Bu benim için önemli bir sorun haline dönüştü. Yardımcı olabilirseniz çok sevinirim.

Özetle:
- v1 için, "/api/v1/users/transactions/trade" uç noktası tüm emirleri gösterirken, "/api/v1/allOrders" uç noktası sadece "CLOSED" olanları gösteriyor. "PARTIAL" emirler listelenmiyor.
- v2 için, "/api/v2/account/transactions/trade/" uç noktası tüm geçmiş emirlerimi gösterirken, "api/v2/account/advanced-order-history" uç noktası sadece "CLOSED" tipindeki emirleri gösteriyor. "PARTIAL" emirler listelenmiyor.

**Comment by ocinbat** [comment]
Merhaba,

/api/v1/allOrders ile ilgili düzeltmeyi kısa bir süre içinde yayına alacağız. 

Emir Geçmişim ekranı, yani api/v2/account/advanced-order-history için daha uzun soluklu planlarımız var. Bu konuda da güncellemeyi ilerleyen zamanlarda alabileceksiniz.

**Comment by ocinbat** [comment]
/allOrders artık her statüdeki emri dönüyor. Kontrol edebilir misiniz?

**Comment by gringo06** [comment]
Bütün emirler şu anda geliyor ancak başka bir sorun var... /allOrders  server dan cevap alırken çok uzun zaman geçiyor, /users/transactions/ da 100ms sürerken /allOrders da bu süre 8 saniye kadar cevap gelmesi bekleniyor.Bu  sorgunun daha kısa zamanda yanıtlanması gerekmiyor mu?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
