### ISSUE TITLE
Kablo Net Üzerinden Api' ye erişim Sağlanamıyor mu ?

### ISSUE THREAD

**Issue by ahomag** [BTCTrader/broker-api-docs#225]
Kablonet kullanıcısıyım ip adresini yazarak api kodu aldım ama yetki problemi alıyor ve bakiye kontrolü yapamıyorum. arkadaşın (Turkcell superbox ) interneti ile denedim sorunsuz api çalıştı. Kod' değişikliği yapmadan.
Ne olabilir sorun almadım ?

**Comment by ocinbat** [comment]
Merhaba,

Başarısız durumla aldığınız cevabı, response body ve headerları ile bize iletebilir misiniz?

**Comment by ahomag** [comment]
Merhaba, Kablo net ile görüştüm. 100' lü bir IP ataması yapmışlar dolayısı ile modem' den alınan IP adresi ve dış IP adreslerim birbirlerinden farklı olmuş. 100 lü IPden çıkınca sorunum çözüldü.
