### ISSUE TITLE
cancel order success sonucu

### ISSUE THREAD

**Issue by yunusseemre** [BTCTrader/broker-api-docs#226]
url="https://api.btcturk.com/api/v1/order?id=ORDER_ID"
Linkine cancel order için talep gönderidiğim zaman şu sonucu alıyorum:
{
    code = 0;
    message = SUCCEEDED;
    success = 1;
}

ardından iptal edilen orderId numarasını tekrar gönderdiğimde aynı sonucu alıyorum: 
{
    code = 0;
    message = SUCCEEDED;
    success = 1;
}

Deneme amaçlı rastgele herhangi  bir order ID gönderdiğimde:
      "https://api.btcturk.com/api/v1/order?id=123"
ve herhangi bir açık işlem olmadığı halde yine başarılı diye sonuç dönüyor

Eski api de benzer bir durumda order bulunamadı (604-no order match your request) diye bir hata kodu dönüyordu.

İptali gerçekleşmiş veya olmayan bir işlemin tekrar iptal talebinde bulunduğumuzda başarılı gerçekleşti diye sonuç göndermesi normal mi?

**Comment by ocinbat** [comment]
Merhaba,

Bu davranış bir dizayn kararı. HTTP DELETE idempotent davranır. Daha fazla bilgi için aşağıdaki makaleden bilgi alabilirsin. 

https://developer.mozilla.org/en-US/docs/Glossary/Idempotent

**Comment by aliveli186** [comment]
> Bu davranış bir dizayn kararı. HTTP DELETE idempotent davranır. Daha fazla bilgi için aşağıdaki makaleden bilgi alabilirsin.

Kullanıcı finansal bir işlem yapıyor ve sonucunu alamıyor çünkü HTTP RCF'ye bağlı kalmak tercih edilmiş.
Finansal işlemlerde her talebin bir cevabı olur ve kullanıcı ona göre yeni karar alır. Siz kullanıcıyı karar alamaz durumda bırakıyorsunuz bir HTTP standardına bağlı kalmayı tercih ederek.

API'den DELETE ile emri iptal etme komutu gönderdiğimizde bazen web socket tarafından herhangi bir bilgi gelmiyor ilgili işlemle ilgili ve emir askıda kalabiliyor.
Eğer HTTP kısmına sadık kalınmak zorundaysa, böyle durumlar için en azından web socket kanalından bir cevap dönmeli. "Cancel Rejected" gibi bir mesaj.
