### ISSUE TITLE
Verilen emrin sonuç fiyatı bilgisi kaybı.

### ISSUE THREAD

**Issue by EUA** [BTCTrader/broker-api-docs#227]
API da şöyle bir eksiklik fark ettim.
Bir kaç emir verdik diyelim.
Bu emirlerin hangisinin ne fiyattan sonuçlandığının bilgisini bulamıyoruz.

- All Orders ile emrimizi bulabiliyoruz. Ama bu emin sonuçlanan fiyat bilgisi dönen veride yok.
- User Transactions ile emirlerimizin sonuçlarını bulabiliyoruz ama hangi emirlerimize ait olduğu bilgisi yok. Dönen ID de order_id yok, onun yerine trade_id bulunuyor.

Bu yüzden verilen herhangi bir emrin hangi fiyattan işlem gördüğünün bilgisi tam olarak bulunamıyor.
Ancak zaman göz önüne alınarak bir oranda kestirim yapılabilir ama sonuçta kesin bir bilgi sağlamaz.

All Orders'a kapatılan emrin hangi fiyattan kapatıldığının yada UserTransactions dan dönen bilginin içinde order_id nin de eklenmesi gerekiyor diye düşünüyorum.

**Comment by sukru77** [comment]
Ayni problemi bende yasiyorum. Bunu cozmek icin matching engine yazdim. User trades den gelen verileri order lara match ediyor. Simdilik bu isimi goruyor. 

API dan gelen veriler order id ile beraber gelmesi isimizi cok kolaylastiracak.

**Comment by brkr** [comment]
Ayni sorunu bende yasiyorum. bununla ilgili bir gelisme var mi ?

**Comment by umitk** [comment]
Bu sorunu ben de yaşıyorum. Gelişme var mı?

**Comment by onurgozupek** [comment]
Merhaba, mesaja geç cevap verdiğimiz için özür dilerim. API tarafında değişiklik yapılması için görüştüm.

Alım satım işlem sonuçlarına order ID eklenmesi mümkün. /v1/users/transactions/trade uç noktasına yapacağınız sorgulara orderID eklendiğiniz, bu orderID'leri /allOrders uçnoktasından gelen yanıtlarla eşleştirebilirsin.

orderID ile sorgu için de görüştüm. Yeni bir uçnoktası hazırlanması için talepte bulundum. Hazır olduğunda dokümanlara ekleyip ayrıca buradan da bilgi vereceğim.

**Comment by EUA** [comment]
Evet /allOrders de gelen yanıtlarda emrimizi bulabiliyoruz ama bu bilgide **gerçekleşen fiyat bilgisi** yok. Verdiğimiz emrin fiyat bilgisi var. Burada önemli olan nokta, örneğin markete karşı yaptığımız satışda gerçekleşme fiyatını görebilmek.
Teşekkürler.

**Comment by AsimCanALKAN** [comment]
Sorun hala çözülmemiş sanırım çünkü ben orderID ile request ettiğimde bana bütün hepsini dönüyor bu da sistemde gecikmeye sebeb oluyor anladığım kadarıyla gözle görülür değil tabi ki ama orderID endpoitini eklendi mi? Yoksa dönen sonucun içinden mi eşleştirmeliyim? Neden bu allOrders kısmına eklenmiyor bu kadar zor olmamalı bu çözüm gerçekten kullanıcılara zorluk çıkarıyorsunuz ve kaç aydır çözülmemiş bir durum!

**Comment by efecini** [comment]
@AsimCanALKAN @EUA problem çözüldü mü acaba? Bilginiz var mı?

**Comment by EUA** [comment]
Çözülse burayı çözüldü yapıp kapatırlardı sanırım @efecini

**Comment by ocinbat** [comment]
/v1/users/transactions/trade endpointine query olarak orderId gönderebilirsiniz. Geliştirmeyi tamamladık dokümantasyon güncellemesi yakında çıkar. orderId gönderdiğiniz koşullarda diğer filtreleme parametrelerini kullanamayacaksınız. Yani ya tarihe göre ya da orderId ye göre arama yaptırabilirsiniz. Örnek istek /v1/users/transactions/trade?orderId=12345

**Comment by ozgun77** [comment]
Geliştirme dökümantasyona eklenmiştir. Response örneği de güncellendi, servis response'unda orderId'yi görebilirsiniz.
