### ISSUE TITLE
Api' nin android versiyonu

### ISSUE THREAD

**Issue by ahomag** [BTCTrader/broker-api-docs#228]
Merhaba, api' yi android java üzerinde kullanabilir miyiz ? 
Aşağıda ki function' ın android versiyonunu alabilir miyiz ?

private string GetSignature(long stamp)
        {
            string signature = null;
            try
            {
                var data = $"{_publicKey}{stamp}";
                using (var hmac = new HMACSHA256(Convert.FromBase64String(_privateKey)))
                {
                    var signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(data));
                    signature = Convert.ToBase64String(signatureBytes);
                }
            }
            catch (Exception e)
            {
                //Debug.WriteLine("Exception occured in GetSignature method. The likely cause is a private or public key in wrong format. Exception:" + e.Message);
            }

            return signature;
        }

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
