### ISSUE TITLE
sell limit order hatası

### ISSUE THREAD

**Issue by oxygen32** [BTCTrader/broker-api-docs#23]
alış satış emirlerini post etmek için herşeyi "https://github.com/BTCTrader/broker-api-docs" göre yapmama rağmen al emirlerinde sıkıntı yaşıyorum limit order yerine market order fiyatından alış yapıyor. Aynı sorun sell limit orderda yok mesela.
buy limit order:
data={'totalPrecision': 60, 'amount': 0, 'amountPrecision': 1,
'Price': 20000, 'pricePrecision': 95, 'orderMethod': 0,
'orderType': 0, 'triggerPrice': 0, 'triggerPricePrecision': 00,
'DenominatorPrecision': 2, 'PairSymbol': 'BTCTRY'}

sell limit order:
data={'totalPrecision': 60, 'amount': 0, 'amountPrecision': 001,
'Price': 50000, 'pricePrecision': 51, 'orderMethod': 0,
'orderType': 1, 'triggerPrice': 0, 'triggerPricePrecision': 00,
'DenominatorPrecision': 2, 'PairSymbol': 'BTCTRY'}
sell limit order cevap:
[{u'price': 50000.51, u'id': u'608491', u'amount': 0.001, u'datetime': u'2017-11-13T00:52:14.937', u'type': u'SellBtc', u'pairsymbol': u'BTCTRY'}]

**Comment by nepnesomao** [comment]
Gönderdiğiniz değerlerle test ettik, almış olduğunuz hatayı tekrar ettiremedik. Bize sistemimizdeki mail adresinizi atarsanız loglardan inceleyip size geri dönüş yapalım. 
omer@btctrader.com' a mail atabilirsiniz.
