### ISSUE TITLE
 APIClient.ApiClientV1 GetUserTrades yavaslik problemi 

### ISSUE THREAD

**Issue by Cagatay342** [BTCTrader/broker-api-docs#230]
Merhaba bu fonksyionu geriye maks 200 deger donsede tarih araligini buyuttugunuz surece yavasliyor geri donus

**Comment by Cagatay342** [comment]
Kullandiginiz database i bilmiorum ama top 200 aldiktan sonra cikan sonuca tarih kriterini verirseniz burasi duzelir

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
