### ISSUE TITLE
apide bazen calismama sorunu

### ISSUE THREAD

**Issue by muhammedyildz** [BTCTrader/broker-api-docs#231]
{
  "success": true,
  "message": "Unauthorized - Invalid Nonce",
  "code": 1037
}

account balance bazen calisiyor bazen bunu soyluyor

**Comment by m4rked0ne** [comment]
Bilgisayarınızın saati ile btcturk sorgularından dönen saatin farkına bakın. Özellikle elektrikler gittiğinde bazen bilgisayar otomatik olarak kendi saatini birkaç saniye de olsa kaydırabiliyor. Aradaki fark birkaç saniyenin altında değilse aynı problemi ben de yaşıyorum.

**Comment by muhammedyildz** [comment]
aynen dediginiz gibiymis tesekkur ederim

**Comment by yemreak** [comment]
Çözümü nedir acaba? @m4rked0ne @muhammedyildz

**Comment by m4rked0ne** [comment]
Server saati ile bilgisayarınızın saat farkını birkaç saniyenin altına düşürmeniz gerek. Bilgisayar otomatik yapmıyorsa elinizle değiştirebilirsiniz. Python için saat farkını görebileceğiniz kodu paylaşıyorum (bu fark milisaniye cinsinden):

import requests, time
print(requests.get('https://api.btcturk.com/api/v2/server/time').json()['serverTime']- time.time()*1000)

**Comment by yedhrab** [comment]
Her istek attığımda bu farkı eklemem mi lazım, bu ping eklemez mi bana?

**Comment by yemreak** [comment]
👷‍♂️ Tek seferlik zaman farkını değişkene kaydeden bir yapı kurdum.

- ➕ Her istek atımındaki `timestamp` değerine `_time_offset` değerini ekliyorum
- 👨‍🔬 100 istekli kontrol yaptım bir sorun çıkmadı. 

```py

def get_server_time():
    requests.get('https://api.btcturk.com/api/v2/server/time').json()

latencies = []
for _ in range(10):  # İsteğe bağlı artırılabilir
    initial_time = time.time()
    get_server_time()
    latencies.append(time.time() - initial_time)
latency = sum(latencies) / len(latencies)
timestamp = datetime.timestamp(datetime.now(timezone.utc))
_time_offset= get_server_time()["serverTime"] / 1000 - timestamp + latency / 2
```

> 💡 Fikir oluşturması adına paylaşıldı

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
