### ISSUE TITLE
open orders ile submit ordersin farki nedir acaba

### ISSUE THREAD

**Issue by muhammedyildz** [BTCTrader/broker-api-docs#234]

**Comment by onurgozupek** [comment]
openOrders, verdiğiniz emirlerden henüz eşleşmemiş olanları (açıkta bekleyen emirleri) listeler. submit Order (order) ise emrinizi iletmek (emir vermek) için kullanılır.

Piyasa (market) emir türünü kullanıyorsanız openOrders boş döner çünkü emirleriniz emir anında eşleşir.

Stop Piyasa (stopmarket) emir verdiğinizde tetikleme fiyatına ulaşana kadar emir açıkta bekleyeceği için openOrders uçnoktasından emirlerinizi listeleyebilirsiniz.
