### ISSUE TITLE
"ORDER_COULD_NOT_BE_CANCELED" vs "NO_ORDER_MATCHES_YOUR_REQUEST"

### ISSUE THREAD

**Issue by ErrorEater** [BTCTrader/broker-api-docs#236]
1050: "**ORDER_COULD_NOT_BE_CANCELED**"
ve
1051: "**NO_ORDER_MATCHES_YOUR_REQUEST**"

iki cevap arasındaki fark nedir?

**Comment by ocinbat** [comment]
ORDER_COULD_NOT_BE_CANCELED => Gönderdiğiniz order iptal edilebilecek bir statüde değil.
NO_ORDER_MATCHES_YOUR_REQUEST => Gönderdiğiniz order bulunamadı.

**Comment by ErrorEater** [comment]
> ORDER_COULD_NOT_BE_CANCELED => Gönderdiğiniz order iptal edilebilecek bir statüde değil.
> NO_ORDER_MATCHES_YOUR_REQUEST => Gönderdiğiniz order bulunamadı.

Biraz daha açar mısınız, çünkü DELETE ve PUT işlemleri için karışıklık bulunuyor.
Şöyle ki;

ORDER_COULD_NOT_BE_CANCELED: İptal edilememe (DELETE) sebebi ne? Daha önceden işlem görüp tamamlandığı için mi?
Mesela gönderdiğim bir emrin gerçekleştiğini düşünelim. O OrderId'ye iptal komutu gönderdiğimde ORDER_COULD_NOT_BE_CANCELED cevabı geliyor.
Ama order zaten **artık aktif olmadığı için** NO_ORDER_MATCHES_YOUR_REQUEST dönmesi gerekiyor ki o OrderId'nin takibini kendi tarafımda yapmayayım. ORDER_COULD_NOT_BE_CANCELED cevabı bana ilgili OrderId artık tahtada mı değil mi bilgisini vermiyor, **tekrar mı denemeliyim yoksa ilgili emir gerçekleştiği için o işlemi tamamlandı mı algılamalıyım karar veremiyorum.**

**ORDER_COULD_NOT_BE_CANCELED döndüğünde ne anlamalıyım? Şu an için mi iptal edilemiyor ve bir süre sonra iptal edilebilir mi olacak, yoksa bu OrderId'ye air bir emir yok olarak mı algılamalıyım?**

Gerçekleşen emir için emir güncelleme komutu gönderdiğimde ise tam olması gereken cevap geliyor: NO_ORDER_MATCHES_YOUR_REQUEST **_(ORDER_COULD_NOT_BE_UPDATED gibi bir cevap gelmiyor, cevap çok net bilgi veriyor, o OrderId'ye ait güncellenebilecek bir emir yok. Fakat diğer cevapta belirsizlik var.)_**
Bu durumda ilgili emrin OrderId'sinin artık tahtada işlem görmediğini anlayıp takibini bırakıyorum fakat DELETE orderda ORDER_COULD_NOT_BE_CANCELED döndüğü için uyumsuzluk oluşuyor, belirsizlik yaratıyor.

Eğer DELETE emri için ORDER_COULD_NOT_BE_CANCELED ile PUT emri için NO_ORDER_MATCHES_YOUR_REQUEST cevapları emir artık tahtada olmadığı için dönüyorsa bunların aynı sebebin farklı ifade edilişleri olduğunu düşünmek doğrudur diyebilir miyiz?

**Comment by ocinbat** [comment]
ORDER_COULD_NOT_BE_CANCELED aldığınız durumlarda order statüsünü açık emirlerinizi çekerek kontrol edebilirsiniz.

**Comment by ErrorEater** [comment]
> ORDER_COULD_NOT_BE_CANCELED aldığınız durumlarda order statüsünü açık emirlerinizi çekerek kontrol edebilirsiniz.

**Sonlanmış (satış emri ise tamamı satışmış olan) yani artık tahtada işlem görmeyen bir emrime DELETE gönderdiğimde ORDER_COULD_NOT_BE_CANCELED cevabını alıyorum. 
Aynı emrim için UPDATE gönderdiğimde NO_ORDER_MATCHES_YOUR_REQUEST cevabını alıyorum. Ayni durum için 2 farklı cevap!**

İkisi aynı durumu işaret ediyor fakat DELETE ile dönen cevap belirsizlik içeriyor. Emir şu an için mi iptal edilemiyor, 10 sn sonra denediğimde iptal edilebilecek mi acaba gibi kesin olmayan bir durum yaratıyor. Açık emirleri her seferinde kontrol etmem gereksiz bir iş olur, sizin şüpheye yer bırakmayacak bir cevap göndererek başka adımlarla doğrulama yapmaya gerek vermemeniz lazım!

Şu an kodları görmediğiniz için net cevap veremediğinizi anlıyorum o nedenle DELETE için dönen ORDER_COULD_NOT_BE_CANCELED ve PUT/UPDATE için dönen NO_ORDER_MATCHES_YOUR_REQUEST cevaplarının emrin artık tahtada işlem görmemesi neticesinde geldiğini, aynı durumun farklı ifadeleri olduğunu kabul ediyorum.
Yanlış ise lütfen belirtin.

**Comment by ocinbat** [comment]
Merhaba,

API dokümantasyonumuzda order için PUT/UPDATE endpointine dair bir açıklama bulunmuyor. Bu endpointlerin döndüğü cevaplar kesin değil, değişebilir. api/v2/orders/:id PUT'u kullanmamalısınız, gelecek bir tarihte kaldırılabilir de. ORDER_COULD_NOT_BE_CANCELED cevabını aldığınızda o order iptal edilemiyor demektir. Şu anda iptal edilemiyor gibi bir senaryomuz yok. O anlık bir işlemi yapmakta sorun yaşıyorsak onunla ilgili olarak 500 hata koduyla bir internal server error almanız gerekiyor.

**Comment by ErrorEater** [comment]
> Merhaba,
> 
> API dokümantasyonumuzda order için PUT/UPDATE endpointine dair bir açıklama bulunmuyor. Bu endpointlerin döndüğü cevaplar kesin değil, değişebilir. api/v2/orders/:id PUT'u kullanmamalısınız, gelecek bir tarihte kaldırılabilir de. ORDER_COULD_NOT_BE_CANCELED cevabını aldığınızda o order iptal edilemiyor demektir. Şu anda iptal edilemiyor gibi bir senaryomuz yok. O anlık bir işlemi yapmakta sorun yaşıyorsak onunla ilgili olarak 500 hata koduyla bir internal server error almanız gerekiyor.

v2 API'yi kullanıyorum, DELETE için önceden her zaman SUCCESS dönerken artık daha belirgin cevaplar döndüğünü görüyorum, API official olmadığı değişiklik olabileceğini biliyorum, takip ediyorum sürekli.
Evet dediğiniz gibi HTTP 500 hatası gelen durumlar da oluyor fakat bu durum "400 Bad Request" durumu, yani sizin tarafınızda kararın doğru verildiği bir durum.
Aslında HTTP 500 için ORDER_COULD_NOT_BE_CANCELED göndermeniz doğru olur. Oradaki belirsizlik işlemin o an için yapılamadığını ama daha sonra yapılabileceğinin bilgisini veriyor.

Bu durumda ben, 2 ifadenin de aynı sebepten, emrin artık tahtada olmamasından kaynaklandığını düşünerek hareket edeceğim.

**Comment by akildemir** [comment]
@ocinbat merak edilen konu şu emir neden iptal edilemiyor? Açık emirleri çektiğimizde status kısmında zaten 2 seçenek var. Ya "dokunulmadı", ya da "kısmen eşleştirildi". En azından dökümantasyonda yazan bunlar. Dokunulmadı durumunda iptal edilebildiğini biliyoruz yani "kısmen eşleştirildi" durumunda mı iptal edilemiyor?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
