### ISSUE TITLE
Websocket 40 Saniyede bir Connection Kapatıyor

### ISSUE THREAD

**Issue by polatbilek** [BTCTrader/broker-api-docs#237]
Merhabalar,
Websocket üzerinden yaptığım tüm bağlantılar 40 saniye sonra kapanıyor, sebebi nedir? Tam olarak 40 saniye sürüyor açık kalması.

**Comment by ErrorEater** [comment]
Evet arada kapatma oluyor ama 40 saniye çok kısa.
Hatırladığım kadarıyla test web socket adresinde oluyordu bu durum. Gerçek adresi deneyin oradaki kesilmeler daha uzun sürelerde bazen saatler sonra oluyor.

Eğer test adresinden (wss://ws-feed-sandbox.btctrader.com) bağlıysanız live adresini (**wss://ws-feed-pro.btcturk.com**) deneyin, büyük ihtimal sorununuz çözülür.

**Comment by polatbilek** [comment]
wss://ws-feed-pro.btcturk.com buradan bağlanıyorum zaten. Tam olarak 40 saniye ve sabit, hep 40.
IP ban gibi durumları da düşünüp farklı adreslerden denedim yine aynı.

**Comment by polatbilek** [comment]
Websocket bağlantıları authentication istiyor mu? Trade ve order book çekiyorum, public olduklarını düşünüp authenticate etmiyorum hiç. Genelde public sunulduğundan öyledir herhalde diye düşünüp çektim direkt. Bununla alakalı olabilir mi?

**Comment by ErrorEater** [comment]
> Websocket bağlantıları authentication istiyor mu? Trade ve order book çekiyorum, public olduklarını düşünüp authenticate etmiyorum hiç. Genelde public sunulduğundan öyledir herhalde diye düşünüp çektim direkt. Bununla alakalı olabilir mi?

Public uçlar oldukları için haklısınız authenticationa gerek olmamalı ama benzer bir sorunu yaşadığımı hatırlıyorum ve authenticate ederek bağlanıyorum web socket'e. Şu an böyle bir sorunum yok ama yine de arada bir kesiliyor, server çat diye kapatıyor bazen, WS protokolündeki gibi anlaşmalı kapatma yapmıyor.

Şurda web socket'ten nasıl auth. edeceğinizi anlattım, ben o şekilde bağlanıyorum. Bir bakın.
https://github.com/BTCTrader/broker-api-docs/issues/216#issue-610443424

**Comment by onurgozupek** [comment]
Websocket bağlantısı yaptıktan sonra bir kanala abone oluyor musunuz? Abone olmuyorsanız, websocket bağlantısı 60 saniye içerisinde kesilir. Abone olduğunuzda, abone olduğunuz kanaldan veri akışı gerçekleştiği sürece bağlantı aktif kalmaya devam edecektir.

**Comment by polatbilek** [comment]
@onurgozupek gereken cevabı verdi. Teşekkürler.

**Comment by polatbilek** [comment]
@onurgozupek ben yanlış anlamış olabilir miyim diye sorayım istedim. Abone (subscribe) oluyorum, fakat tanımlama (authenticate) yapmıyor api key ile. Subscribe'ı kastetiyseniz evet oluyorum ve ona rağmen bu problem var.

**Comment by yemreak** [comment]
Merhabalar,

- Aynı sorunu ben de yaşıyordum. 
- Kanallara abone olmama ve verileri almama rağmen 44s de bir bağlantı kopması oluyor yeniden bağlanıp, yeniden abone oluyorum tekrardan kopma oluyor ve döngü bu şeklide ilerliyordu

Çözümü:

- `ping_interval=None` ile websocket bağlantısını başlatmalıyız 
- Yani bağlantıyı kurarken `websockets.connect(config.WS_BTCTURK_URL, ssl=True, ping_interval=None)` şeklinde başlatmalıyız.

> Detaylı bilgi için stackoverflow üzerindeki linke bakabilirsin [👪 1006 Connection closed abnormally error with python 3.7 websockets](https://stackoverflow.com/a/58993145/9770490)

**Comment by polatbilek** [comment]
@yedhrab ın cevabı sorunu çözdü. Görünüşe göre BTCTURK pong mesajı göndermiyor. Websocket bağlantısı kuranlar ping yollamamalılar. @onurgozupek bununla ilgilenecektir sanırım, yoksa kimse bağlantı mı düştü yoksa BTCTURK'te al-sat hareketliliği mi yok ayrımını yapamayacaktır.
