### ISSUE TITLE
Api den tek order hakkında bilgi istemede sorun

### ISSUE THREAD

**Issue by canerd7u** [BTCTrader/broker-api-docs#238]
Merhaba api de bulunan All Orders methodunu kullanarak bir order id sinin detayları almaya çalışıyorum. Sadece order id si hakkında bilgi vermesi için limit olarak 1 gönderiyorum. Ancak orderId olarak belirtilen parametreye sahip olduğum herhangi bir order id sini gönderdiğimde doğru bilgileri vermiyor.

**Comment by onurgozupek** [comment]
Konu hakkında yazılım ekibi ile görüştüm. Yeni uç noktası eklenmesi gerekiyor. Ayrıca bilgi vereceğim.

https://github.com/BTCTrader/broker-api-docs/issues/227#issuecomment-642521591

**Comment by canerd7u** [comment]
api v2 ne zaman kullanılabilir olur acaba ? Açık orderlarımızın hepsini kapatmak için tek tek tüm order id lerini sisteme göndermek zorunda kalıyoruz. Bu durumda sistem **Internal Server Error** hatası veriyor. Tüm orderların kapatılması için ayrıca Yeni bir uç noktası oluşturulmalı. Aynı zamanda bu uç noktasına symbol ve side filtreleride eklenirse güzel olur.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
