### ISSUE TITLE
Verilen emrin sonuç fiyatı bilgisi kaybı. #227

### ISSUE THREAD

**Issue by brkr** [BTCTrader/broker-api-docs#239]
#227 no lu issue yu gundeme getirmek istiyorum. Bir gelisme var mi? Verilen emirin ne kadarlik kismi gerceklesti bulamiyoruz?

Umarim cevap verirsiniz

**Comment by onurgozupek** [comment]
https://github.com/BTCTrader/broker-api-docs/issues/227#issuecomment-642521591
