### ISSUE TITLE
İptal Edilen Emrin Takip Edilememesi

### ISSUE THREAD

**Issue by byazici** [BTCTrader/broker-api-docs#24]
Merhaba,

Emir durumlarını sorgularken, openOrders'da yer almayan emirler gerçekleşmiştir diye varsayıyorum. Bu da web sitesinden manuel iptal edilmiş emri de gerçekleşmiş olarak görmeme neden olabiliyor.

Bir emrin "order ID" siyle sorarak açık mı, iptal mi, rlz mi olduğunu anlayabileceğim bir servis/yöntem var mıdır?

Teşekkürler.

**Comment by nepnesomao** [comment]
Şu an için böyle bir servisimiz mevcut değil
