### ISSUE TITLE
Eksi hesap bilgisi alıyorum

### ISSUE THREAD

**Issue by onurerenarpaci** [BTCTrader/broker-api-docs#240]
Api eksi 1.12 tetherimin olduğunu söylüyor. Sitede ise pozitif 1.12 tetherim var olarak gözüküyor ama daire grafiğinde bu para gözükmüyor. Aşşağıda api den aldığım çıktı vardır.

"{"data":[{"asset":"TRY","assetname":"Türk Lirası","balance":"0.8276996632592091","locked":"0","free":"0.8276996632592091","orderFund":"0","requestFund":"0","precision":2},{"asset":"BTC","assetname":"Bitcoin","balance":"0.0641479885833932","locked":"0","free":"0.0641479885833932","orderFund":"0","requestFund":"0","precision":8},{"asset":"ETH","assetname":"Ethereum","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":8},{"asset":"XRP","assetname":"Ripple","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":4},{"asset":"LTC","assetname":"Litecoin","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":8},{"asset":"USDT","assetname":"Tether","balance":"-1.12826071","locked":"0","free":"-1.12826071","orderFund":"0","requestFund":"0","precision":2},{"asset":"XLM","assetname":"Stellar","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":4},{"asset":"NEO","assetname":"Neo","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":4},{"asset":"EOS","assetname":"Eos","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":4},{"asset":"DASH","assetname":"Dash","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":8},{"asset":"LINK","assetname":"ChainLink","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":4},{"asset":"ATOM","assetname":"Cosmos","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":6},{"asset":"XTZ","assetname":"Tezos","balance":"0","locked":"0","free":"0","orderFund":"0","requestFund":"0","precision":6}],"success":true,"message":null,"code":0}"

Bu ciddi bir sorun acilen düzeltebilir ve ileride benzer bir problem yaşayıp yaşamayacağım hakkında bilgilendirirseniz sevinirim.

**Comment by onurgozupek** [comment]
Hesabınızın kontrol edilebilmesi için bu metni destek@btcturk.com'a e-posta ile gönderebilir misiniz?
