### ISSUE TITLE
Yanlış Hesap Bilgisi

### ISSUE THREAD

**Issue by emrahtopcu** [BTCTrader/broker-api-docs#241]
users/balances ile aldığım hesap bilgisinde:
1.free alanı son yaptığım satış işleminin tutarı ile beraber geliyor. Yani tam olmasada yaklaşık iki katı geliyor.
2.Herhangi bir açık emrim olmamasına rağmen orderFund alanı negatif ve son işlem tutarı kadar geliyor.
3.locked alanı da orderFund  alanı ile aynı geliyor.

Bilmem alakası varmıdır ama openOrders dan aldığım açık emirlerde type alanında 'Sell' değerini 'sell' yapmışsınız. 

İyi çalışmalar.

**Comment by onurgozupek** [comment]
Hesabınızın kontrol edilebilmesi için bu metni destek@btcturk.com adresine gönderebilir misiniz?

**Comment by onurgozupek** [comment]
> Bilmem alakası varmıdır ama openOrders dan aldığım açık emirlerde type alanında 'Sell' değerini 'sell' yapmışsınız.

Bu bilgiyi de kontrol ettiriyorum.

Edit: openOrders, type değerlerini lowercase (tümü küçük harf) olacak şekilde dönüyor. Yani bir sorun yok. Aynı şekilde allOrders ve transactions uç noktalarında da küçük harfle geliyor.

**Comment by emrahtopcu** [comment]
İlginize teşekkür ederim onur bey, gereken mail'i gönderdim. Sorun halen devam etmekte. Bu sefer de negatif değil eksik bakiye geldi. Kodumu buna göre de güncelledim. Şimdilik programım çalışıyor. Umarım biranönce çözülür. İyi çalışmalar.

**Comment by emrahtopcu** [comment]
> > Bilmem alakası varmıdır ama openOrders dan aldığım açık emirlerde type alanında 'Sell' değerini 'sell' yapmışsınız.
> 
> Bu bilgiyi de kontrol ettiriyorum.
> 
> Edit: openOrders, type değerlerini lowercase (tümü küçük harf) olacak şekilde dönüyor. Yani bir sorun yok. Aynı şekilde allOrders ve transactions uç noktalarında da küçük harfle geliyor.

İlginize teşekkür ederim onur bey, gereken mail'i gönderdim. Sorun halen devam etmekte. Bu sefer de negatif değil eksik bakiye geldi. Kodumu buna göre de güncelledim. Şimdilik programım çalışıyor. Umarım biranönce çözülür. İyi çalışmalar.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
