### ISSUE TITLE
c++ client 401  Unauthorized - Invalid Request Error

### ISSUE THREAD

**Issue by akildemir** [BTCTrader/broker-api-docs#242]
merabalar, btcturk api icin c++ client geliştiriyorum ama private endpointlerde sorun yaşıyorum. 401  Unauthorized - Invalid Request hatası alıyorum  sürekli. İlgili diğer konulara baktım invalid signature gönderildiğinde döndürülen bi hata olduğu kanısına vardım ama signature hazırlarken kullandığım fonksiyonları(HMAC256, decode/encode64 ) online kaynaklardan da teyit ettim. Şu an neyi yanlış yaptığımla alakalı pek bi fikrim yok. signature hazırlarken kullandığım fonksiyon:

````
std::string BturkClient::getUserSignature(){
    
    chrono::milliseconds stamp = chrono::duration_cast<chrono::milliseconds>(chrono::system_clock::now().time_since_epoch());
    auto stamp_str = std::to_string(stamp.count());
    auto data = this->apiKey + stamp_str;
    auto signature = HMAC256(data, decode64(this->secretKey));
    signature = encode64(signature);    return signature;
}
````

burade kullanılan helper fonksiyonlarının uygulamaları:

````
std::string HMAC256(std::string data, std::string key)
{
    std::stringstream ss;
    HMAC_CTX *ctx = HMAC_CTX_new();
    unsigned int  len;
    unsigned char out[EVP_MAX_MD_SIZE];
    HMAC_Init_ex(ctx, key.c_str(), key.length(), EVP_sha256(), NULL);
    HMAC_Update(ctx, (unsigned char*)data.c_str(), data.length());
    HMAC_Final(ctx, out, &len);
    HMAC_CTX_free(ctx);
    for (unsigned int i = 0;  i < len;  i++)
    {
        ss << std::setw(2) << std::setfill('0') << std::hex << static_cast<int> (out[i]);
    }
    return ss.str();
}

std::string decode64(const std::string &val) {
    using namespace boost::archive::iterators;
    using It = transform_width<binary_from_base64<std::string::const_iterator>, 8, 6>;
    return boost::algorithm::trim_right_copy_if(std::string(It(std::begin(val)), It(std::end(val))), [](char c) {
        return c == '\0';
    });
}

std::string encode64(const std::string &val) {
    using namespace boost::archive::iterators;
    using It = base64_from_binary<transform_width<std::string::const_iterator, 6, 8>>;
    auto tmp = std::string(It(std::begin(val)), It(std::end(val)));
    return tmp.append((3 - val.size() % 3) % 3, '=');
}
````
Neyi yanlış yaptığımla ilgili bi fikri olan varsa bilgilendirirse sevinirim.

**Comment by emrahtopcu** [comment]
İşine yararmı bilmiyorum ama c# çalışan kodum. nonce için gereken milisaniye yi sunucudan alıyorum. Bu arada hatalı response larda da sunucu cevap dönüyor. response.content içinde hata ile ilgili detay bilgi bulabilirsin. Kolay gelsin.

`_ServerTimeSyncTimer = new System.Timers.Timer(2500);
      _ServerTimeSyncTimer.Elapsed += ServerTimeSyncTimer_Elapsed;
      _ServerTimeSyncTimer.Start();

private async void ServerTimeSyncTimer_Elapsed(object sender, System.Timers.ElapsedEventArgs e)
    {
      try
      {
        _ServerTimeSyncTimer.Stop();
        var serverTime = await ServerTime();
        lock (_serverTimeLock)
          _serverTime = serverTime;
      }
      catch (Exception)
      {
      }
      finally
      {
        _ServerTimeSyncTimer.Start();
      }
    }

public async Task<long> ServerTime()
    {
      var raw = await AsyncPublicCall("server/time");
      return Convert.ToInt64(raw.serverTime);
    }

var nonce = _serverTime.Value;
      var message = _ClientKey + nonce;
      var signature = getHash(Convert.FromBase64String(_ClientSecret), Encoding.UTF8.GetBytes(message));

      var requestMessage = new HttpRequestMessage(HttpMethod.Post, url);
      requestMessage.Headers.Add("X-PCK", _ClientKey);
      requestMessage.Headers.Add("X-Stamp", nonce.ToString());
      requestMessage.Headers.Add("X-Signature", signature);

private string getHash(byte[] keyByte, byte[] messageBytes)
    {
      using (var hmacsha256 = new HMACSHA256(keyByte))
      {
        return Convert.ToBase64String(hmacsha256.ComputeHash(messageBytes));
      }
    }`

**Comment by akildemir** [comment]
@emrahtopcu cevap için teşekkürler. Ben de bir sürü c# ve python kodundan takip ettim zaten. Hatalı nonce gönderdiğimde invalid nonce hatası alıyorum direk o yüzden nonce da bi hata olduğunu sanmıyorum. "Unauthorized - Invalid Request" dönderilen cevapın mesaj kısmında yazıyor zaten başka bi şey yazmıyor. utf8 encodingde bi hata olabilir diye düşündüm ama signature ve datanın işlemle kondamadan önce geçerli bi utf8 stringi olduğunuda doğruluyorum bi utf kütüphanesi aracılığıyla.

**Comment by onurgozupek** [comment]
C# örnekleri için https://github.com/BTCTrader/broker-api-csharp-v2/tree/master/APIExampleV1 örnek kodunu indirip deneyebilirsiniz. Invalid nonce hataları büyük çoğunlukla timestamp farkından; invalid Request'ler ise hatalı komut ya da kodlama (encoding) hatasından kaynaklanıyor. https://docs.btcturk.com adresindeki örneklere göz atabilirsiniz.

**Comment by akildemir** [comment]
@onurgozupek  cevapınız için teşekkürler. Görünüşe göre sıkıntı hmac fonksiyonundaymış. Ben hmac hex versiyonu kullanıyordum ama düz string versiyonu kullanılmalıymış. Sıkıntı çözüldü. Asıl Olması gereken hmac256 fonksiyonu:

````
std::string HMAC256(std::string key, std::string msg)
{
    unsigned char hash[32];

    HMAC_CTX *hmac = HMAC_CTX_new();
    HMAC_CTX_reset(hmac);
    HMAC_Init_ex(hmac, &key[0], key.length(), EVP_sha256(), NULL);
    HMAC_Update(hmac, ( unsigned char* )&msg[0], msg.length());
    unsigned int len = 32;
    HMAC_Final(hmac, hash, &len);
    HMAC_CTX_free(hmac);

    std::stringstream ss;
    ss << std::setfill('0');
    for (int i = 0; i < len; i++)
    {
        ss  << hash[i];
    }

    return (ss.str());
}
````
Kapatıyorum konuyu.
