### ISSUE TITLE
Kullanılabilir Bakiye Hatası

### ISSUE THREAD

**Issue by emrecg** [BTCTrader/broker-api-docs#243]
Yaklaşık 2-3 gündür yoğun bir şekilde api sorgularımda balance uç noktasında kullanılabilir bakiyeler yanlış geldiğinden dolayı sürekli hata veriyor ve canlı destekle iletişime geçtiğimde hesabınızı güncelleştirdim diyip sorunumu hallediyorlar. Fakat tahmin edebileceğiniz üzere programın başında veya hesabın başında durmuyorum farkedebildiğim zamanlar oluyor edemediğim zamandada örnek veriyorum yüksekten btc aldığı için ticaretin devam etmesi için düşükten satmak zorunda kalıyorum ve dolayısıyla zarar ediyorum. Kullanılabilir bakiyelerin gözden geçirilmesi kanaatindeyim.

**Comment by MaDeRkAn** [comment]
Evet bakiyeler yanlış geliyor.
Hiç bir emrim yada çekme isteğim olmamasına rağmen.

Locked - geliyor.

Free'de Balance - Locked olduğu için. Balance'ımdam büyük geliyor.

**Comment by canerd7u** [comment]
+1

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
