### ISSUE TITLE
Websocket orderbook 

### ISSUE THREAD

**Issue by aydinhus** [BTCTrader/broker-api-docs#244]
Merhaba,

Websocket ile orderbook'u izlediğimde sanki güncellemeleri diff geldiğinde değil de periyodik olarak gönderiyor, yaklaşık 1sn aralıklarla data alıyorum. 

Belirli süre izleyip ortalamasını aldığımda da dakikada 60 adet veri gelmiş görünüyor, 

"type": "151",
"channel": "orderbook",

Bu konuda bir gözlemi olan var mı acaba?

**Comment by mhelvacikoylu** [comment]
Değişimler saniyede bir gönderilir. diff kanalı bile olsa 1 saniye içindeki değişimler saniyede bir gönderilir.

**Comment by aydinhus** [comment]
Yanıt için teşekkürler ancak saniyede bir gelmesi az değil mi, genellikle gördüğüm diff direkt yansıtılıyor eğer değişiklik yoksa saniyede bir yine de update gönderiliyor. Zaten şu an saniyede restapi üzerinden de sorgu yapabiliyoruz ki öncesinde limitler düşürülmemişken restapiden daha sık güncelleme alınabiliyordu.

Bu konuda bir iyileştirme planı var mı?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
