### ISSUE TITLE
❗ Birden fazla çift için tek istek ile OrderBook değerlerini almak

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#245]
- Orderbook alırken sadece tek çift için alınmakta
- Birden fazla para çifti ile uğraşırken birden fazla istek atmamız gerekmekte bu da istek sayımızı artırmakta
- `.../api/v2/orderbook?pairSymbol=BTC_TRY&pairSymbol=BTC_USDT&limit=100` gibi bir URL yapısı ile birden fazla orderbook alacağımız yapı kurulamaz mı?

**Comment by onurgozupek** [comment]
Merhaba, aynı anda birden fazla işlem çiftinde avantajlı olan tarafa emir vermeyi planlıyorsanız, mantıklı bir öneri. Ancak emir verirken yine ayrı ayrı emir verecekseniz. Bu da yine sorgu sayınızı  artıracak.

OrderBook'u API'dan sorgulamak yerine Websocket'i kullanırsanız, sorgulama limitlerinden etkilenmeden emir defterlerini sorgulayabilirsiniz.

**Comment by yemreak** [comment]
- Peki, ticker işleminden son ask ve bid emirlerinin **miktarlarını da** alma şansımız yok mu?
- Bazı emirler işlem yapamayacak kadar küçük miktarda olmakta
- Emirleri yapmaya çalıştığımızda hata almaktayız

> 🤕 Ticker ile direkt olarak emir veremiyoruz, tekrardan orderBook isteği yapmak zorundayız

**Comment by onurgozupek** [comment]
Ticker sadece fiyat bilgisini dönmek için tasarlandı. En iyi alış veya satışın miktarını verse bile yine yeterli olmayacaktır. Eğer emir miktarlarını dikkate alarak emir verecekseniz, orderBook'tan ya da web socket'ten örneğin en iyi 10 emri çekip, almak ya da satmak istediğiniz tutarlara denk gelecek fiyatları hesaplamanız gerekiyor.

Örneğin siz 61.000TL'den 3 BTC'lik emir vermek istiyorsunuz ama 61.001TL'deki emir 0.001BTC. Kalan 2.999 BTC toplama ulaşmak için ya fiyatı artıracaksınız ya da baştan, 3BTC'yi alabilmek için fiyatı kaça çıkarmanız gerektiğini hesaplayıp, fiyatı ona göre belirleyeceksiniz. Bu işlem için emir defterini her saniyede bir sorgulamanızın size bir avantajı olmayacak. Ancak, hareketli piyasada emir defterini sorguladıktan sonra 3 BTC'lik emri karşılayacak fiyatı hesaplayıp tek sorgu ile 3 BTC alım gerçekleştirmeniz size avantaj sağlayacaktır.

(Bu sadece öneri tabi ki. Bu şekilde uygulamak zorunda değilsiniz. Belki sizin aklınıza daha pratik bir yol gelebilir.)

**Comment by yemreak** [comment]
Onur bey, öncelikle hızlı dönüşünüzden dolayı çok teşekkür ederim :)

- Web socket ile birden fazla OrderBook değerlerini aynı anda dinleyebiliyor muyuz?
- Hem BTC_TRY hem de LINK_TRY emirlerini aynı anda alabilme imkanım var mı?
- 23:30:15.324 de BTC_TRY emirleri alınmış ise LINK_TRY emirleri de 23:30:15.5'i geçmeyecek şekilde alınabiliyor mu? (Özetle düşük gecikmeli kabul)

> Ek olarak Web Socket için pythonda bu işlem için örnek kod paylaşımı veya kütüphane var mı acaba?

**Comment by onurgozupek** [comment]
Merhaba, websocket ile aynı anda birden fazla kanala bağlanabilirsiniz.

Python örneğini umitk rumuzlu kullanıcı paylaşmıştı: https://github.com/BTCTrader/broker-api-docs/issues/219#issuecomment-622988826
