### ISSUE TITLE
Yeni Emir Oluştururken "Bad Request" Hatası

### ISSUE THREAD

**Issue by ucemm** [BTCTrader/broker-api-docs#246]
İyi günler,

Bugün daha önceden bir problem yaşamadığım "api/v1/order" çıkış noktası bağlantısından sürekli olarak "Bad Request" hatası almaktayım. 

"api/v1/users/balances", "api/v1/users/transactions/trade" ve "api/v1/allOrders" çıkışlarında bir problem yaşamıyorum.

Problemin kaynağı nedir acaba? Geçici bir aksaklık mı yaşanıyor?

**Comment by umutklc** [comment]
Merhabalar, ben de benzer sorun yasıyorum acaba siz bir cozum bulabildiniz mi yoksa sorununuz devam ediyor mu?
