### ISSUE TITLE
Balance sorunu 

### ISSUE THREAD

**Issue by digitallartist** [BTCTrader/broker-api-docs#247]
Son dönemlerde yoğunlukla balance kontrol ve zaman zaman da order verilmesi sırasında hatalar alıyorum.
Şuan da da Balance kontrol yaptığımda sonuç NULL olarak dönüyor.
Frekans sorunu olabilir diye uzun bir süre api üzerinden işlem yapmayıp sadece balance kontrol yaptım ama hala sonuç NULL olarak dönüyor

**Comment by ocinbat** [comment]
Merhaba,

API'dan aldığınız cevabı Host, Header, Response Code ve Response Body şeklinde bize iletebilirseniz size yardımcı olabiliriz.

**Comment by digitallartist** [comment]
object(stdClass)#25 (3) {
  ["success"]=>
  bool(true)
  ["message"]=>
  string(28) "Unauthorized - Invalid Nonce"
  ["code"]=>
  int(1037)
}

**Comment by digitallartist** [comment]
Sunucunun saat ve zaman dilimi ayarlarını değiştirince düzeldi. Teşekkürler.
