### ISSUE TITLE
🔔 Emir tamamlandığında bildirim almak | Websocket

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#249]
- 🔔 Veriğimiz emir tamamlandığında bize bildiri veren bir websocket hizmetiniz olacak mı?
- 💁‍♂️ Bu sayede emir tamamlandığı vakit, kaynaklarımızla hemen başka işlemler yapabiliriz

> 🤔 Ek olarak: orderbook işlemlerinde değiştiğinde değil saniyede bir veriler gelmekte, burada düzeltme yapılmayacak mı?

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
