### ISSUE TITLE
Alım ve Satım Post olarak neleri göndermem gerekiyor?

### ISSUE THREAD

**Issue by kadirgunhiz** [BTCTrader/broker-api-docs#25]
Merhaba,

`function authPost($uri) {
			$url=$GLOBALS['baseURL'].$uri;
			$nonce=time();
			$headers=array(
					'X-PCK: '.$GLOBALS['APIKey'],
					'X-Stamp: '.$nonce,
					'X-Signature: '.$GLOBALS['signature']
			);
			
			$post = "OrderMethod=1&OrderType=1";
			$ch=null;
			$ch = curl_init($url);
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
			curl_setopt($ch, CURLOPT_POST, true);
			curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
			$result=curl_exec($ch);
			curl_close($ch);
			return json_decode($result);
	}`

Fonksiyonunu kullarak alış ve satış yapmaya çalışıyorum fakat **alış ve satış** yaparken hangi parametreleri göndermem gerekiyor ekstra, döküman üzerinden anlayamadım. Yardımcı olursanız sevinirim.

**Comment by nepnesomao** [comment]
```
curl_setopt($ch, CURLOPT_POSTFIELDS, 'OrderMethod=1&'.
                                              'OrderType=1&'.
                                              'totalPrecision=00&'.
                                              'amountPrecision=01&'.
                                              'pricePrecision=00&'.
                                              'triggerPrice=0&'.
                                              'triggerPricePrecision=00&'.
                                              'DenominatorPrecision=2&'.
                                              'price='1000.'&'.
                                              'amount='0'&'.
                                              'PairSymbol=BTCTRY');
```
OrderType 0 Alım, 1 Satış, OrderMethod 0 = Limit, 1 = Market, 2 = Stop Limit ve 3 = Stop Market

Precision olarak geçen parametreler ise gireceğiniz fiyat/miktar da '.' dan sonrasıdır.

**Comment by kadirgunhiz** [comment]
Anlık kur üzerinden btc alacak isem;
`amount ve amountPrecision a alacağım BTC miktarını price ve pricePrecision miktarınıda anlık BTC kuruna göre yapmalıyım o halde değil mi ? AyrıcaOrderType  0 OrderMethod 1 olması gerekiyor? `

**Comment by nepnesomao** [comment]
Örnek siz piyasa fiyatından 0.001 BTC almak istiyorsunuz, piyasa fiyatımız da 30,744.00 TL olsun. parametreler şöyle olmalı;
```
amount = 0,
amountPrecision = 001,
price = 30744,
pricePrecision = 00,
triggerPrice = 0,
triggerPricePrecision=00,
total = 30,
totalPrecision = 00
DenominatorPrecision = 2,
PairSymbol = BTCTRY,
OrderMethod = 1,
OrderType = 0,
```

**Comment by kadirgunhiz** [comment]
Anladım sağolun satarken de sadece satacağımız btc rakamını, btc kurunu, order type ı değiştirerek yapabilirim. Teşekkürler.
