### ISSUE TITLE
Sürekli 400 alıyorum

### ISSUE THREAD

**Issue by mmterkc** [BTCTrader/broker-api-docs#253]
Merhaba python kullanıcısıyım ve https://docs.btcturk.com/#submit-order burdaki örneği yapmama rağmen 400 hatası alıyorum. Varlığıma vs bakabiliyorum. https://docs.btcturk.com/#submit-order  adresindeki kodlar güncelmidir ? "/api/v1/order" kullanımda mı

**Comment by onurgozupek** [comment]
Merhaba, sorunu anlamamız için biraz daha detay verebilir misiniz?

Dokümanlarda yer alan Python kodunu kopyalayıp, sadece API bilgilerimi girerek deneme yaptım ve işlem başarıyla sonuçlandı.

Sunucunuzun zamanı ile API sunucusunun zamanı birbirine yakın mı
Emir vermeye çalıştığınız işlem çiftine bakiyeniz yeterli mi?
IP adresiniz yurtdışı mı, yurt içi mi?
Sadece emir girişinde mi hata alıyorsunuz? Örneğin bakiye sorgulamayı denediniz mi?

**Comment by mmterkc** [comment]
import time, base64, hmac, hashlib, requests, json,threading

apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
apiSecret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
base = "https://api.btcturk.com"
method = "/api/v1/order"
uri = base + method

apiSecret = base64.b64decode(apiSecret)
stamp = str(int(time.time()) * 1000)
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type": "application/json"}
params = {"quantity": 1, "price": 0.08798, "stopPrice": 0,
          "newOrderClientId": "BtcTurk Python API Test", "orderMethod": "limit", "orderType": "buy",
          "pairSymbol": "XLMUSDT"}
result = requests.post(url=uri, headers=headers, json=params)

if result.status_code == requests.codes.ok:
    result = result.json()
    print(result)
else:
    print(result.status_code)

**Comment by mmterkc** [comment]
apikey ve secrete yerine koyup denediğimde hata alıyorum şimdi denemek için denediğim kod

**Comment by mmterkc** [comment]
bakiye sordulamada hata almıyorum bakiyemi görebiliyorum

**Comment by onurgozupek** [comment]
Minimum emir tutarının altında kalıyorsunuz. Aynı sorguda tutarı 55 XLM olarak deneyin.

**Comment by mmterkc** [comment]
Merhaba denediğimde tekrar aynı hatayı alıyorum

**Comment by onurgozupek** [comment]
```python
import time, base64, hmac, hashlib, requests, json

base = "https://api.btcturk.com"
method = "/api/v1/order"
uri = base+method

apiKey = "xxx"
apiSecret = "xxx"
apiSecret = base64.b64decode(apiSecret)

stamp = str(int(time.time())*1000)
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type" : "application/json"}

params={"quantity": 60.00,"price": 0.088,"stopPrice": 0, "newOrderClientId":"BtcTurk Python API Test", "orderMethod":"limit", "orderType":"buy", "pairSymbol":"XLM_USDT"}

result = requests.post(url=uri, headers=headers, json=params)
result = result.json()
print(json.dumps(result, indent=2))
```
Sonuç:
`{
  "httpStatusCode": 200,
  "data": {
    "id": 3466xxxxx,
    "quantity": "60.0",
    "price": "0.08800",
    "stopPrice": "0",
    "newOrderClientId": "BtcTurk Python API Test",
    "type": "buy",
    "method": "limit",
    "pairSymbol": "XLMUSDT",
    "pairSymbolNormalized": "XLM_USDT",
    "datetime": 15947272xxxxx
  },
  "success": true,
  "message": "SUCCESS",
  "code": 0
}`

**Comment by mmterkc** [comment]
tamam teşekkürler başka ağlarla deneyeyim

**Comment by fatihkutuk** [comment]
Burada buy parametresi verildiğinde yanıldığınız yer şurası qantity parametresi sizin Ödeme biriminiz cinsinden kaç adet ödeme yapacağınızdır. Yani ödeme cinsiniz try ise kaç liralık alım yapacağınz ile ilgilidir. Gönderdiğiniz kod  tllik alışveriş yapmak isteğinde bulunuyor hata alıyorsunuz. bu arada almak istediğiniz coin için gereken scale parametresi olarak ne istiyorsa  python da round fonksiyonu ile buna scale etmenizde gerekir. https://docs.btcturk.com/#errors adresinde pair Scale bölümünden coinler için scale parametrelerini görebilirsiniz

**Comment by fatihkutuk** [comment]
++
Siz  1 "USDT'lik"  "XLM" alma isteğinde bulunuyorsunuz. Burada belirttiğim scale paramatresi quantitiy için ve price için yine 
e tekabül ediyor.   
Aşağıda çalışan kodun örneğini bırakıyorum.
Not: Aşağıda ki işlem market işlemidir limit işlemi için gereken parametreleri değiştirmeyi unutmayun

import time, base64, hmac, hashlib, requests, json,threading

apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
apiSecret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
base = "https://api.btcturk.com"
method = "/api/v1/order"
uri = base + method

apiSecret = base64.b64decode(apiSecret)
stamp = str(int(time.time()) * 1000)
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)https://guides.github.com/features/mastering-markdown/
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type": "application/json"}
params={"quantity": round(60,4),"newOrderClientId":"BtcTurk Python API Test", "orderMethod":"market", "orderType":"buy", "pairSymbol":"XRP_TRY"}

result = requests.post(url=uri, headers=headers, json=params)

if result.status_code == requests.codes.ok:
result = result.json()
print(result)
else:
print(result.status_code)

**Comment by onurgozupek** [comment]
> Burada buy parametresi verildiğinde yanıldığınız yer şurası qantity parametresi sizin Ödeme biriminiz cinsinden kaç adet ödeme yapacağınızdır. Yani ödeme cinsiniz try ise kaç liralık alım yapacağınz ile ilgilidir. Gönderdiğiniz kod tllik alışveriş yapmak isteğinde bulunuyor hata alıyorsunuz. bu arada almak istediğiniz coin için gereken scale parametresi olarak ne istiyorsa python da round fonksiyonu ile buna scale etmenizde gerekir. https://docs.btcturk.com/#errors adresinde pair Scale bölümünden coinler için scale parametrelerini görebilirsiniz

bu söylediğiniz piyasa emrinde geçerli. Limit emirlerde quantity parametresi almak veya satmak istediğiniz miktarı belirtir. Bu nedenle ne kadar alacağınızı hesaplayıp emir iletmelisiniz. (Ya da bakiyenizden eminseniz adet x fiyat < toplam kullanılabilir bakiye olmalıdır.)

**Comment by fatihkutuk** [comment]
Bu yüzden "Not: Aşağıda ki işlem market işlemidir limit işlemi için gereken parametreleri değiştirmeyi unutmayun" şu açıklamayı ekledim. market veya limit emrinin ne olduğunu bilmeden ilk girdiğimde aynı hataları almıştım. Arkaşımızın belki benim gibi olabileceğini düşündüm.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
