### ISSUE TITLE
Son 10 exchange datasını getirme

### ISSUE THREAD

**Issue by fatihkutuk** [BTCTrader/broker-api-docs#254]
Merhaba, herhangi bir coin için son x kadar exchange datasını nasıl alırım, gereken parametreleri bulamadım

**Comment by onurgozupek** [comment]
Son 30 alım satım işlemini trades uç noktasından alabilirsiniz. Örneğin BTC/USDT:

https://api.btcturk.com/api/v2/trades?pairSymbol=BTC_USDT

Doküman:
https://docs.btcturk.com/#trades

**Comment by fatihkutuk** [comment]
Çok teşekkürler

**Comment by fatihkutuk** [comment]
2. Bir soru biline indikatörler için hesaplanmış değerleri apiniz aracılığıyla alabiliyor muyuz ? Örneğin RSI indikatörü için apiniz bir response üretiyor mu üretiyorsa nereye nasıl bir istek atmalıyız ? Üretmiyorsa belirli tarihler arasında en yüksek kapanışları alabileceğimiz yada belirli tarihler arasında ki gün kapanışlarını nerden alabiliriz. Şimdiden teşekkürler

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
