### ISSUE TITLE
İndikatörler İçin Response var mı

### ISSUE THREAD

**Issue by fatihkutuk** [BTCTrader/broker-api-docs#255]
Herhangi bir borsa indikatörü için örneğin RSI apinizden doğrudan çıktı alabiliyor muyuz?

**Comment by onurgozupek** [comment]
Indikatörleri kullanabilmek için fiyat verilerini mumlar halinde alabilirsiniz. (BtcTurk indikatör sunmuyor sadece indikatörlerde kullanılmak üzere fiyat verisi sunuyor.)

Örneğin BTCTRY:
https://graph-api.btcturk.com/v1/klines/history?symbol=BTCTRY&resolution=XX&from=YY&to=ZZ

XX: 5,15,30,60,240,1D,1W,1Y
YY: Başlangıç timestamp'i (saniye olarak 10 hane)
ZZ: Bitiş timestamp'i (saniye olarak 10 hane)
symbol için BtcTurk | PRO'daki tüm işlem çiftlerini kullanabilirsiniz.

**Comment by fatihkutuk** [comment]
Doğrudan son x gün gibi bir parametre verip alamıyoruz anladığım kadarıyla aralığı kendimiz veriyoruz

**Comment by onurgozupek** [comment]
Tarih aralığı ve mum sürelerini verirseniz istediğiniz günü, saati, dakikayı alabilirsiniz.

**Comment by fatihkutuk** [comment]
tekrar merhaba responsta dönen "v" dizisindeki veriler mi bizim açılış kapanış değerlerimiz oluyor ?
bana belirli tarihler arasındaki kapanış ve açılış değerleri lazım

**Comment by onurgozupek** [comment]
t: timestamp (mum başlangıç zaman damgası)
h: high (mum en yüksek fiyat)
o: open (açılış fiyatı)
l: low (mum en düşük fiyat)
c: close (mum kapanış fiyatı)
v: volume (mum hacmi)

(Bu terimleri bilmeden grafikleri yorumlamanız, dolayısıyla indikatörleri doğru kullanmanız mümkün değil)

**Comment by fatihkutuk** [comment]
Bu işlerde  haftalık bir mazim bile olmadı daha. Öğrenmey çalışıyortuz

> t: timestamp (mum başlangıç zaman damgası)
> h: high (mum en yüksek fiyat)
> o: open (açılış fiyatı)
> l: low (mum en düşük fiyat)
> c: close (mum kapanış fiyatı)
> v: volume (mum hacmi)
> 
> (Bu terimleri bilmeden grafikleri yorumlamanız, dolayısıyla indikatörleri doğru kullanmanız mümkün değil)

Bu işlerde 2 haftalık bir mazim bile olmadı daha. Öğrenmeye çalışıyoruz sora sora.

**Comment by fatihkutuk** [comment]
> t: timestamp (mum başlangıç zaman damgası)
> h: high (mum en yüksek fiyat)
> o: open (açılış fiyatı)
> l: low (mum en düşük fiyat)
> c: close (mum kapanış fiyatı)
> v: volume (mum hacmi)
> 
> (Bu terimleri bilmeden grafikleri yorumlamanız, dolayısıyla indikatörleri doğru kullanmanız mümkün değil)

Bu işlerde 2 haftalık bir mazim bile olmadı daha. Öğrenmeye çalışıyoruz

**Comment by gvardal** [comment]
Bende RSI analizi üzerinde çalışıyorum, api üzerinden 14 günlük 60  dakikalık kapanış verisini alıyorum excel üzerinde hesaplama yaptığımda hesapladığım RSI ile site üzerinde gösterilen RSI arasında ciddi fark var, acaba nerde hata yapıyorum

**Comment by ramazansh** [comment]
Merhaba herkese  ben burda yeniyim  sorular saçma olsa da anlayışla karşılamanızı dilerim öğrenmeye çalışıyorum   bana  LİNKUSDT   ATR si
average true range API alamaya  çalışıyorum   nerden alaçagımıda bilimiyorum yardımcı  olursanız  sevinirim

**Comment by MasherCoder** [comment]
Merhabalar,
14 günlük 15-30-60 dakikalık farklı farklı hesaplamama rağmen sitede bulunan RSI değeri ile API den çekilerek hesaplanan RSI değerinde büyük farklılıklar var!
Bunun sebebi nedir?

**Comment by suleymanbyzt** [comment]
Merhaba @ramazansh,

OHLC Data için [buraya](https://docs.btcturk.com/public-endpoints/ohcl-data) tıklayarak dökümanımızı inceleyebilirsiniz.

Verileri kullanarak, kullanmak istediğiniz indikatör için response alabilirsiniz. BtcTurk olarak API aracılığı ile indikatör hizmeti sunmamaktayız.
