### ISSUE TITLE
REQUEST: All USDT pairs should have market order type.

### ISSUE THREAD

**Issue by akildemir** [BTCTrader/broker-api-docs#256]
I don't understand why only BTCUSDT pair has the market order type but not all the rest of the USDT pairs. Is this a business decision or technical decision? Because I have only seen this in BTCTURK. All the other exchanges that I have used has all the order types available to all pairs.  It makes harder for end user to trade like that. Both in terms of API usage and regular website usage. If the user just want to buy quickly from whatever the market price and willing to walk to order book, why can't he/she? I think this is an important must-have feature for all pairs. 

NOTE: This is a request, not an issue with the platform.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
