### ISSUE TITLE
401 hatası

### ISSUE THREAD

**Issue by mmterkc** [BTCTrader/broker-api-docs#257]
Merhaba hiçbir sıkıntı yokken biranda 401 hatası almaya başladım tekrar api key oluşturup , gerekli yerleri değiştirip denediğimde sonuç aynı. Bir sıkıntı mı var api erişiminde ?

**Comment by mmterkc** [comment]
base = "https://api.btcturk.com"
    method = "/api/v1/users/balances"
    uri = base + method
    apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    apiSecret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    apiSecret = base64.b64decode(apiSecret)
    stamp = str(int(time.time()) * 1000)
    data = "{}{}".format(apiKey, stamp).encode("utf-8")
    signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
    signature = base64.b64encode(signature)
    headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type": "application/json"}
    result = requests.get(url=uri, headers=headers)

örneğin bu kodda alıyorum

**Comment by onurgozupek** [comment]
401 hatalarının genel nedeni sunucu zamanı ile API sunucusu zamanı arasında farktan kaynaklanıyor. Sunucunuzun zamanını API sunucusu zamanına yakın olduğunu kontrol edebilir misiniz? (Not: API sunucusu UTC zaman diliminde çalışıyor. Eğer kodunuz zaman dilimi ayarlaması yapmıyorsa, saat farkı nedeniyle nonce değeri geçersiz olacağı için 401 hatası alırsınız) 

Sunucu zamanını https://api.btcturk.com/api/v2/server/time uçnoktasından kontrol edebilirsiniz

**Comment by mmterkc** [comment]
Merhaba dediğinizi yaptım zaman dilimimi utcye çevirrdim ama sınuç aynı. 
Kod:
import time, base64, hmac, hashlib, requests, json,threading,datetime
from datetime import timezone

base = "https://api.btcturk.com"
method = "/api/v1/users/balances"
uri = base + method
apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
apiSecret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
apiSecret = base64.b64decode(apiSecret)
a=(datetime.datetime.now(timezone.utc))
a=datetime.datetime.timestamp(a)
stamp = str((int( a* 1000)))
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type": "application/json"}
result = requests.get(url=uri, headers=headers)
print (result)

**Comment by mmterkc** [comment]
Önerdiğiniz kod varsa onuda deneyebilirim. Ama dediğim sıkıntısız çalışıyordu. Biranda 401 almaya başladım.

**Comment by onurgozupek** [comment]
> Merhaba dediğinizi yaptım zaman dilimimi utcye çevirrdim ama sınuç aynı.
> Kod:
> import time, base64, hmac, hashlib, requests, json,threading,datetime
> from datetime import timezone
> 
> base = "https://api.btcturk.com"
> method = "/api/v1/users/balances"
> uri = base + method
> apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
> apiSecret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
> apiSecret = base64.b64decode(apiSecret)
> a=(datetime.datetime.now(timezone.utc))
> a=datetime.datetime.timestamp(a)
> stamp = str((int( a* 1000)))
> data = "{}{}".format(apiKey, stamp).encode("utf-8")
> signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
> signature = base64.b64encode(signature)
> headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type": "application/json"}
> result = requests.get(url=uri, headers=headers)
> print (result)

Bu kod çalışıyor, az önce denedim. destek@btcturk.com'a mail atarsanız, hesabınızı kontrol edelim.
