### ISSUE TITLE
🐞 OrderBook verileri için güncel değer gelmiyor

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#259]
-   API'ye istek attığımızda güncel verileri vermiyor sanki 1s'de bir güncellenen websocket kanalından değer döndürüyor
- WebSocket kanalının 1s'de bir değişmesi yerine değişim olduğunda yenilenmesi gerekmez mi? piyasayı takip edemiyoruz
- Emirler her değiştiğinde veya anlık onlarak değerlerini alabileceğim bir yöntem yok mu?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
