### ISSUE TITLE
ticker servisi eski veriyi gösteriyor

### ISSUE THREAD

**Issue by bulbul-ismail** [BTCTrader/broker-api-docs#26]
Ticker servisi üzerinden verileri güncellerken bir süre sonra sürekli eski veriyi döndürmeye başlıyor. Ticker servisini kullanmak için authorization gerekli mi?

**Comment by nepnesomao** [comment]
Ticker servisi için authorization gerekli değil.

**Comment by bulbul-ismail** [comment]
#20 kodlu sorun hala devam ediyor. Yardımcı olursanız sevinirim.

**Comment by rozaydin** [comment]
Selamlar, bu konu için bir gelişme var mı ?

**Comment by hasangursoy** [comment]
API servisi ile kimse ilgilenmiyor herhalde. Timestamp'a bakılırsa 2-3 saat öncesinin verisini gösteriyor. Aslında düzeltseniz site trafiğiniz için iyi olur. Güncel kuru almak için sitenizi parse etmeyelim :)

**Comment by hasangursoy** [comment]
Bu arada https://www.btcturk.com/api/ticker?v=12 şeklinde parametre eklenilince önbelleklemenin aşıldığını farkettim. Bu şekilde anlık data alınabilir. Saat güncelmiş, GMTye göre görünüyor.

**Comment by mdegis** [comment]
@BTCTraderAdmin bu konu ile ilgili bir gelisme var mi?

**Comment by bulbul-ismail** [comment]
Merhabalar, http protokolunuzde User-Agent tanimlamasi yaparsaniz ticker servisi sorunsuz calismakta.
Iyi calismalar
