### ISSUE TITLE
✨ Ticker WebSocket kanalında verilen son emirlerin kaynakları hakkında bilgi neden yok?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#260]
- Binance Websocket üzerinde olduğu gibi neden bu ticker websocket içerisinde verilen son emirlerin kaynaklarını belirten değer yok?

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
