### ISSUE TITLE
FAILED_ORDER_WITH_OPEN_ORDERS hatasi

### ISSUE THREAD

**Issue by ocengiz0** [BTCTrader/broker-api-docs#261]
Merhaba
API ile yapilan islemlerin bazilarindan "FAILED_ORDER_WITH_OPEN_ORDERS" seklinde hata geliyor.
Bu hata kodu API dokumantasyonunda yok ve zarar islemleri oluyor
Hatanin aciklamasini ve nasil onlem almamiz gerektigi konusunda bilgi edinmek istiyorum.

Acik emir varken yeni emir girelemez seklinde bir kural mi geldi mevcut versiyona?

**Comment by ocinbat** [comment]
Selamlar,

Bu hata, mevcutta emriniz varken fakat kalan bakiyeniz yeni emir girmek için yeterli olmadığında dönülüyor.

Sent from my iPhone

On 2 Aug 2020, at 15:03, Oğuzhan Cengiz <notifications@github.com> wrote:

﻿

Merhaba
API ile yapilan islemlerin bazilarindan "FAILED_ORDER_WITH_OPEN_ORDERS" seklinde hata geliyor.
Bu hata kodu API dokumantasyonunda yok ve zarar islemleri oluyor
Hatanin aciklamasini ve nasil onlem almamiz gerektigi konusunda bilgi edinmek istiyorum.

Acik emir varken yeni emir girelemez seklinde bir kural mi geldi mevcut versiyona?

**Comment by ocengiz0** [comment]
Selam @ocinbat, 

tesekkurler hizli cevap icin, her emir oncesi balance kontrolu yapiyorm free olan balance gore isleme devam ediyorum.

Ek olarak bahsettigin hata icin BALANCE_NOT_ENOUGH_WITHOUT_OPEN_ORDERS hatasi donmuyor mu?

**Comment by pyromus** [comment]
bakiye ile alakası yok bu gıcık problem beni de çok ugraştırdı. market emri açarken 10 TL şeklinde açabiliyorken limit emri açarken btc türünde yani 0.00012345 şeklinde lot miktarı gönderilmesi lazım o zaman oluyor.

**Comment by ocengiz0** [comment]
Evet deneye deneye buldum ben de, yine de tesekkurler @pyromus

**Comment by akildemir** [comment]
Yetersiz bakiye olunca da bu hata dönüyor sanırım. Çünkü bu günden itibaren btcturk crypto/crypto çiftlerinden de komisyon almaya başladı ve artık hesabımda ki tüm parayı direk kullanmaya çalıştığımda da bu hatayı almaya başladım, komisyon ücretini çıkarmadığım için.

**Comment by ocengiz0** [comment]
Ben bu hatadan sonra butun islemlerde quantityden fee kadar duserek cozumu bulmustum

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
