### ISSUE TITLE
Verilen emrin ne kadarlık kısmı gerçekleşti ? !!!!!!

### ISSUE THREAD

**Issue by brkr** [BTCTrader/broker-api-docs#262]
Api V1 üzernden bir emir açtık diyelim bu emirin belirli bir miktarı gerçekleşmiş olsun. İlgili emiri **Cancel** edip yeni bir emir oluşturmak istiyorum.
API V1 de **Partial**  olan bir emirin ne kadarlık kısmı gerçeklesti nasıl bulabilirim? 
API V2'de bu bilgiyi alabiliyoruz.

Daha öncedende bununla ilgili issue açılmıştı fakat bir bilgi ve gelişme göremedim.

**Comment by ocinbat** [comment]
Merhaba,

Api/v1 üzerinde de openOrders endpointi üzerinde leftAmount alanında o emrin ne kadarının kaldığı bilgisi geliyor. Bu bilgi yeter li midir?

**Comment by brkr** [comment]
Evet tesekkurler
