### ISSUE TITLE
OHCL Data dakikalık yada saniyelik periyotta veri çekmek

### ISSUE THREAD

**Issue by mmterkc** [BTCTrader/broker-api-docs#263]
Merhaba, OHCL Datadan dakikalık yada saniyelik veri çekebiliyor muyuz ? Yada başka bir yol var mıdır high low ve close datalarını alabileceğim bir yol ?

**Comment by ocinbat** [comment]
https://graph-api-dev.btcturk.com/swagger/index.html

Buradan klines endpointlerine bakabilirsin.

Resolution değerini 1 olarak verirsen dakikalık data alabilirsin.

**Comment by mmterkc** [comment]
Merhaba cevabınız için teşekkür ederim örnek bir sorgu yazabilir misiniz ? Dakikalık veriye bakmak için

**Comment by mmterkc** [comment]
Tekrar merhaba, response olarak {
  "s": null,
  "t": [],
  "h": [],
  "o": [],
  "l": [],
  "c": [],
  "v": []
}
değerini alıyorum.

**Comment by ocinbat** [comment]
https://graph-api.btcturk.com/v1/klines/history?symbol=BTCTRY&resolution=1&from=1596312346&to=1596612546
