### ISSUE TITLE
ohlcdata da veri hatasi

### ISSUE THREAD

**Issue by alikopasa** [BTCTrader/broker-api-docs#27]
merhabalar,

DailyChangeAmount ile DailyChangePercentage datalari hatali gelmekte.

`"DailyChangeAmount":3.06,"DailyChangePercentage":1260.0`

**Comment by pseudozach** [comment]
Hala DailyChangePercentage yanlış veri geliyor, düzeltebilir misiniz?

`[{"Time":"2017-12-28T00:00:00","Open":61100.0,"High":62999.0,"Low":58700.0,"Close":60840.0,"Volume":161.45320882,"Average":60539.31,"DailyChangeAmount":-0.43,"DailyChangePercentage":-260.0},{"Time":"2017-12-27T00:00:00","Open":65010.01,"High":67049.0,"Low":58558.0,"Close":61020.0,"Volume":611.12288200,"Average":63727.54,"DailyChangeAmount":-6.14,"DailyChangePercentage":-3990.01},{"Time":"2017-12-26T00:00:00","Open":60256.0,"High":66887.0,"Low":60120.0,"Close":65349.0,"Volume":567.13765653,"Average":64131.49,"DailyChangeAmount":8.45,"DailyChangePercentage":5093.0},{"Time":"2017-12-25T00:00:00","Open":61697.0,"High":64198.0,"Low":60150.0,"Close":61100.0,"Volume":432.57442378,"Average":61972.66,"DailyChangeAmount":-0.97,"DailyChangePercentage":-597.0},{"Time":"2017-12-24T00:00:00","Open":67200.0,"High":68488.0,"Low":59500.0,"Close":61697.0,"Volume":737.39893043,"Average":63325.38,"DailyChangeAmount":-8.19,"DailyChangePercentage":-5503.0},{"Time":"2017-12-23T00:00:00","Open":62510.1,"High":70000.1,"Low":61001.0,"Close":67000.99,"Volume":825.02770948,"Average":65809.45,"DailyChangeAmount":7.18,"DailyChangePercentage":4490.89},{"Time":"2017-12-22T00:00:00","Open":68778.99,"High":71640.0,"Low":51011.0,"Close":62510.1,"Volume":1763.82961504,"Average":63084.13,"DailyChangeAmount":-9.11,"DailyChangePercentage":-6268.89},{"Time":"2017-12-21T00:00:00","Open":74509.0,"High":77220.0,"Low":67100.0,"Close":68780.0,"Volume":995.56758350,"Average":72278.72,"DailyChangeAmount":-7.69,"DailyChangePercentage":-5729.0},{"Time":"2017-12-20T00:00:00","Open":77850.0,"High":78000.0,"Low":65000.0,"Close":74748.99,"Volume":1168.41766479,"Average":74588.12,"DailyChangeAmount":-3.98,"DailyChangePercentage":-3101.01}]`

**Comment by alikopasa** [comment]
konu hala devam ediyor buraya bakılıyor mu acaba?

**Comment by suleymanbyzt** [comment]
Merhaba,

Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
