### ISSUE TITLE
Websocket Oturum Açma

### ISSUE THREAD

**Issue by emin-karadag** [BTCTrader/broker-api-docs#270]
Merhabalar,
Bir C# projesi geliştiriyorum.
Websocket üzerinden bağlantı yapmak istiyorum ancak bunu oturum açarak yapmak istiyorum.
Dokümanda bu konu ile ilgili herhangi bir bilgiye rastlamadım.
Yardımcı olur musunuz?

**Comment by pyromus** [comment]
bende merak ediyorum. websocket de login olup order status bilgilerime ulaşabilirsem çok güzel olur. hele bir de websocket üzerinden emir açıp kapatma özelliği de eklerseniz bomba olur.

**Comment by mhelvacikoylu** [comment]
@emin-karadag 
Login olmak için websocket üzerinden 111 kodlu login mesajını göndermeniz gerekiyor. Cevap olarak 112 kodlu başarılı login result mesajını aldığınızı teyit etmeniz gerekebilir. Login olduktan sonra dökümantasyondaki P kodlu mesajları almaya başlarsınız.

Websocket mesajlarına [buradan](https://docs.btcturk.com/#models) ulaşabilirsiniz.
111 kodlu mesajı gönderirken dökümantasyonda yer alan ID değişkenini göndermenize gerek yoktur. Token, btcturk pro'da kullanılan JWT token olmalıdır. Token'in nasıl alınacağı gibi konular https://github.com/BTCTrader/broker-api-docs/issues/274 Id'li issue'da anlatılmıştır.

@pyromus 
Websocket bağlantısı üzerinden emirleriniz eşleştiğinde bilgilendirilirsiniz. Ancak emirlerin statuslerini sorgulama veya emir ekleme, iptal etme gibi özellikler malesef mevcut değildir.

**Comment by emin-karadag** [comment]
@mhelvacikoylu bilgilendirme için teşekkür ederim. Ayrıca Websocket üzerinden emirlerin gerçekleştiğini görebiliyor olmamız gerçekten harika.

Kafama takılan bir konu oldu. Yukarıdaki mesajınızda 111 kodlu mesajı gönderirken ID değerini göndermenize gerek yok dediniz. Oysaki doküman (https://docs.btcturk.com/#models) aynı şeyi söylemiyor. "Must be sent" olarak ifade edilmiş ID alanı.

Ayrıca 111 kodlu mesajı gönderirken "app", "platform" gibi değerleri göndermemize gerek yok sanırım. 
Eğer dediğiniz gibi "ID" değerini göndermemize gerek yoksa "type", "username" ve "token" göndermemiz yeterli olur mu?

**Comment by mhelvacikoylu** [comment]
ID değeri daha önceden gönderilmesi zorunlu alandı. Ancak sonradan zorunluluk kaldırıldı. Dökümantasyon henüz güncellenmedi. app ve platform gibi bilgiler istatistik amaçlıdır. Yalnızca type, username ve token göndermeniz yeterli olacaktır.

**Comment by emin-karadag** [comment]
Merhaba @mhelvacikoylu 

Github'taki örnek projeye websocet üzerinden oturum açma ve sipariş dinleme ile ilgili örnek eklemeniz mümkün mü acaba?

Ya da buradan da paylaşabilirsiniz. Bu hem benim hem de bu konuda çalışmalar yapacak diğer yazılımcı arkadaşlar için faydalı olacaktır.

Şimdiden teşekkürlerimi sunarım 😊

**Comment by mhelvacikoylu** [comment]
Öncelikle botunuzu yaptığınız programlama dilinde bir websocket kütüphanesi bulmanız gerekiyor. Örneğin javacript'te WebSocket sınıfı mevcut, python'da websockets'i import edebilirsiniz.

Bağlantı kurulduktan sonra websocket üzerinden string veri gönderip alıyorsunuz. Gönderdiğiniz ve aldığınız veri formatı şu şekilde olmalıdır:

2 elemanlı array, 1. elemanı integer mesajı tipi, 2. eleman mesajın json serialized içeriği
[type_id, mesaj_modeli]

Örneğin
[111, {type: 111, token: 'jwt token' }]

Tüm mesaj tiplerini btcturk docs sayfasında bulabilirsiniz

**Comment by emin-karadag** [comment]
Çok teşekkürler @mhelvacikoylu . Örneklemeniz sayesinde 111 kodlu isteği gönderip 112 kodlu başarılı sonucu aldım. 👍 

Ufak bir sorum daha olacaktı. Benzer şekilde **İptal Edilen Siparişlere** abone olmak istediğimi varsayalım.  Bu durumda iptal edilen her sipariş için soketten dinleme yapacağım. 

API dokümanına göre 452 numaralı istek göndermem gerekecek. Yukarıda 2 elemanlı diziden bahsettiniz. Bu durumda iptal edilen siparişler için nasıl bir mesaj göndermek gerek.

`[452]` veya  `[452, {}]` veya `[452, {type: 452 }]` ??

Peki 111 kodu ile giriş yaptıktan sonra, kullanıcı ile ilgili diğer özel dinlemeler için token göndermeye gerek yok değil mi?

**Comment by meo1** [comment]
BTCTurk dokümantasyonu WebSocket ile oturum açmak için yetersiz. Nerden Token ve ID alınıyor, nasıl refresh ediliyor hiç bir yerde doğru düzgün belirtilmemiş. Burada bazı sorulara cevap verilmiş ama yeterli değil, bu BTCTurk'ün bir politikası mı yoksa çalışanlarının bir yetersizliği mi?

**Comment by ocinbat** [comment]
Merhaba, websocket ile oturum açıp authenticated kanallardan veri almanız public olarak desteklenmiyor. İleride bu durumda bir değişiklik olduğunda dokümantasyonu güncelleyeceğiz.

Sent from my iPhone

On 8 May 2021, at 11:54, meo1 ***@***.***> wrote:

﻿

BTCTurk dokümantasyonu WebSocket ile oturum açmak için yetersiz. Nerden Token ve ID alınıyor, nasıl refresh ediliyor hiç bir yerde doğru düzgün belirtilmemiş. Burada bazı sorulara cevap verilmiş ama yeterli değil, bu BTCTurk'ün bir politikası mı yoksa çalışanlarının bir yetersizliği mi?

**Comment by meo1** [comment]
Tam anlayamadım, Private olarak alalım o zaman? Ben python ile bilgi çekiyorum api keylerim mevcut niye websocket ile bağlanıp aynı bilgileri çekemiyorum?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
