### ISSUE TITLE
Submit Order, islem gerceklesti mi?

### ISSUE THREAD

**Issue by ekremus** [BTCTrader/broker-api-docs#271]
Merhaba,
Submit order ile, Limit işlemi yaptığımda gelen cevap şu şekilde oluyor:

`{
  "httpStatusCode": 200,
  "data": {
    "id": 431292405,
    "quantity": "15",
    "price": "0.8000",
    "stopPrice": "0",
    "newOrderClientId": "BtcTurk Python API Test",
    "type": "buy",
    "method": "limit",
    "pairSymbol": "XLMTRY",
    "pairSymbolNormalized": "XLM_TRY",
    "datetime": 1597867103932
  },f
  "success": true,
  "message": "SUCCESS",
  "code": 0 `

Sorun su ki, ben bu işlemin open orders'a düşüp düşmediğini ya da gerçekten işlemin gerçekleştiğini nasıl anlarım? Yardımcı olabilir misiniz?

Saygilar.

**Comment by onurgozupek** [comment]
Order uçnoktadı sadece emir iletmek için kullanılır. Sonucunu openOrders veya Trades uçnoktasından sorgulayabilirsiniz.

**Comment by ekremus** [comment]
Super hizli cevabiniz icin cok tesekkur ederim. Binance da gelen cevap icerisinde, verilen emir; islem mi gordu yoksa emir defterine mi dustu diye bir geri bildirim oldugu icin sormak istedim. 
Iyi calismalar.
