### ISSUE TITLE
Cancel all orders ?

### ISSUE THREAD

**Issue by ekremus** [BTCTrader/broker-api-docs#272]
Merhaba,

Butun verilen acik emirleri iptal etmenin bir yolu var mi acaba? BTC_TRY icin acilmis butun emirleri iptal etmek icin ne yapilabilir?

Saygilar.

**Comment by yemreak** [comment]
Bütün açık emirleri alıp, onların id değerleri ile hepsini tek tek iptal edebilirsiniz .

```py
for openOrder in get_openOrders():
    if openOrder.pair_normalized == "BTC_TRY":
        cancel_order(openOrder.id)
```

**Comment by ekremus** [comment]
saol. teşekkürler deneyeceğim 👍

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
