### ISSUE TITLE
Websocket uzerinden trade kanali uzerinde 421 modeli gonderilmiyor

### ISSUE THREAD

**Issue by mehmeta** [BTCTrader/broker-api-docs#273]
Merhaba,

https://docs.btcturk.com/ adresinde "Channel, Event and Model" basligi altindaki tanimlara gore trade kanalina subscription mesaji gonderdigimde bu mesaji onayladigini dusundugum su cevabi aliyorum:
```
{'type': 100, 'id': 0, 'ok': True, 'message': 'join|trade:ETHTRY'}
```
Ve hemen akabinde, API 421 (TradeList) modeli gonderiyor, buraya kadar hersey cok guzel. Ama daha sonra yeni emirler match edildikce 422 TradeSingle mesajlarinin gelmesini bekliyorum ama ayni kanaldan baska mesaj gelmiyor maalesef. 

API'in production'daki su anda davranisi mi bu sekilde yoksa benim tarafimda bir hata mi var?

Sorumun ozu su aslinda, order book'u websocket uzerinden 1sn'den daha hizli bir sekilde guncellemenin bir yolu var mi? 431 (OrderBookFull) ve 432(OrderBookDifference) mesajlari en fazla 1sn siklikla geliyor maalesef. 

Tesekkurler.

**Comment by mhelvacikoylu** [comment]
Merhaba,

Kanal subscription işlemi doğru görünüyor. 421 mesajını alıyorsanız 422 mesajlarını da alabilirsiniz. Bunun için yapmanız gereken ekstra bir şey yok.

Trade mesajları üzerinden orderbook'un güncel halini belirlemeye çalıştığınız için sorma ihtiyacı duydum, emir girişi ve iptali sonucunda 422 mesaj beklemiyorsunuz değil mi? emir defterinin güncel hali genel olarak order insert ve cancel işlemleri ile belirlenir. Trade işlemleri bunun küçük bir bölümünü oluşturur. Her saniye birçok order insert - cancel olmasına rağmen trade işlemi bazen birkaç dakikada bir bile olabilir. Testlerinizde 422 'nin gelip gelmediğinden emin olmak için en az birkaç dakika boyunca trade kanalından gelen mesajları takip edin.

**Comment by mehmeta** [comment]
Anladim, cok tesekkurler!
