### ISSUE TITLE
111 UserLogin mesaji icin gereken token'i uretmek

### ISSUE THREAD

**Issue by mehmeta** [BTCTrader/broker-api-docs#274]
Merhaba, websocket baglantisi uzerinden belli bir hesaba spesifik olan event stream'ini (451-orderınsert, 452 orderdelete modelleri gibi) alabilmek icin token argumanini ("The current token value of the user from SSO" olarak belirtilen) gondermek gerekiyor. Bu token'i programatik olarak nereden alabiliriz? Sorgulayarak alabilecegimiz bir private http endpoint var mi mesela?

Tesekkurler!

**Comment by mhelvacikoylu** [comment]
Merhaba,

Token'i alabilmek için SSO üzerinden TFA'yı geçmeniz gerekiyor. Bu yüzden malesef token'i programatik olarak alamazsınız. Ancak token'i bir defa aldıktan sonra, programatik olarak refresh edebilirsiniz.

**Comment by mehmeta** [comment]
Tesekkurler cevabiniz icin. 

1. Token'i almak icin onerilen yontem nedir? Su anda sadece site onyuzune login olduktan sonra chrome inspector ile 111 ws mesajini inceleyerek alabiliyorum, bunun disinda bir yol yok sanirim?
2. Token'i bahsettiginiz uzere programatik olarak nasil refresh edebilirim?

**Comment by mhelvacikoylu** [comment]
Eğer tokeni yalnızca websocket bağlantısı için kullanacaksanız websocket tek aktif tcp bağlantısı üzerinde olduğundan bir defa login olmanız yeterlidir. Token refresh edip tekrar tekrar 111 login'i göndermenize gerek yoktur.

Eğer token'ı başka endpoint için de kullanacaksanız tokeni local storage'deki btcUser değerinden alabilirsiniz. Aynı yerde refresh token değerini de bulacaksınız. Token yenilemek için token/refresh endpointine { token: 'refresh token değeri' } JSON objesini POST etmeniz gerekiyor. Her refresh sonrası response'da size yeni bir refresh token değeri dönecektir. Bir sonraki token refresh'de bu gelen değeri kullanmanız gerekiyor.

**Comment by mehmeta** [comment]
Refresh token'i buldum ama token/refresh endpoint'inin tam adresi ve gereken payload'un tanimi nedir? Sanirim oauth flow'unun bir parcasi bu oyle degil mi?

**Comment by mhelvacikoylu** [comment]
/api/v2/token/refresh

Örnek bir request'in nasıl atıldığını görmek için pro sitede 1 saatlik tokeniniz süresinin dolmasına yakın bu istek atılır. o request'i inceleyebilirsiniz.

**Comment by pyromus** [comment]
merhaba söylediğiniz adresden token alamıyorum. 
https://api.btcturk.com/api/v2/token/refresh

adres mi yanlış  curl ile api_key ve secret ile authanication yaptıktan sonra deniyorum böyle olması lazım. degilse örnek kod verir misiniz.

**Comment by emin-karadag** [comment]
@mehmeta rica etsem websocket üzerinden nasıl login olduğunuz benim le paylaşabilir misiniz?

**Comment by mehmeta** [comment]
@emin-karadag https://docs.btcturk.com/?python#models adresinde tanimlandigi sekilde 111 UserLogin mesajini gonderiyorum, token'i da sitenin onyuzunun websocket baglantilari uzerinden gonderdigi mesajlari inceleyerek bulabilirsiniz.

@mhelvacikoylu yardimlariniz icin tesekkurler!
