### ISSUE TITLE
Komisyonlarda iyileşme olmayacak mı?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#275]
- Piyasa yapıcı ve alıcı arasındaki fark çok fazla değil mi, özellikle TRY'ın son adımında 8 kat fark var
- Yüksek hacimler için daha düşük komisyon olması gerekmez mi? TRY için de iyileştirme olmayacak mı?

> Ek olarak API üzerinden kendi işlem hacmimizi nasıl alabiliriz?

**Comment by EUA** [comment]
Abuk subuk bir hal aldı valla. En azından 100 ve 150 milyon gibi basamaklar koymaları lazım...
Şimdi bir de çekim işlemlerine ücretlendirme getiriyorlar...

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
