### ISSUE TITLE
ÖNEMLİ !!! Ya websocket disconnect olmasın ya da api ile token üretilsin

### ISSUE THREAD

**Issue by pyromus** [BTCTrader/broker-api-docs#276]
Merhaba 3-5 gündür artık bu sorun beni deli etmeye başladı. çok güzel bir api yapmışsınız en önemli kısmını yapmamışsınız. websocket de login olmazsa 40 saniye sonra disconnect oluyor. websocket login olmak için token lazım. haydaaaa api key ve secret var onu kullanalım olmaz mı ? olmaz. illa token lazım. tokeni nasıl buluyoruz. btcturk e giriyoruz. firebug dan localstorage de btcUser değişkenindeki veriyi elle alıyoruz.  o da kalıcı degil ki. saatte bir yenilemek lazım. ee o zaman nerde kaldı bunun otomatikliği. niye kod yazıyoruz. websocket baglantısı kopunca herşey sıfırlanıyor. emirlerim kayboluyor. sistemim bozuluyor bu konuya acil bir cözüm bulmanız lazım. çok güzel bir bina tasarlıyorsunuz kapısı yok. api den bir giriş sağlarsanız çok iyi olur. websocket stabil çalışırsa işlem hacminiz daha da artıcaktır. insanlar işlem yapamıyor ki.

**Comment by mhelvacikoylu** [comment]
Merhaba,

Websocket'in disconnect olması ile ilgili yaptığım testlerde herhangi bir hata bulamadım. Siz de https://www.websocket.org/echo.html adresinden wss://ws-feed-pro.btcturk.com adresine bağlanıp belirli bir süre bekleyerek disconnect olup olmadığını kontrol edebilirsiniz. Ayrıca pro.btcturk.com üzerinde devtools'u açarak network kısmından websocket bağlantısının kopup kopmadığını da kontrol edebilirsiniz. Ben bu kontrollerde herhangi bir bağlantı kopma gözlemleyemedim.

Websocket'in 40-60 gibi bir sürede disconnect olması sunucu tarafından gelen ping mesajlarına pong cevapları dönülmemesinden kaynaklanıyor olabilir. Normalde bu işlemi kullandığınız kütüphanenin otomatik yapması beklenir. Websocket bağlantısını hangi dil ve hangi kütüphaneyi kullanarak yapıyorsunuz? Disconnect olmanızın nedeni bu ise belirli aralıklarla (15 saniyede bir gibi) sunucuya kısa string bir mesaj göndermeyi (örneğin "a") deneyebilirsiniz. Bu mesaj sunucunun, bağlantınızın aktif ve canlı olduğunu anlamasını sağlayacak, sizi disconnect olmaktan kurtaracaktır.

**Comment by pyromus** [comment]
mhelvacikoylu   boş bir şekilde websocket baglantı kurup beklediğinizde disconnect etmiyor olabilir ama order cancel , order send gibi komutlar yolladıgımızda hele bir de hata alıyorsak websocket direk kopuyor kopmakla kalmıyor. websocket herşeyi die() komutu atıyor sistem komple duruyor. 

ayrıca mhelvacikoylu siz yetkili birine benziyorsunuz gerekli kişilere ulaşıp token almayı kolay bir hale getirmesini saglayabilir misiniz. gerçekten baglantı kopuyor. ekran görüntüsü de atayım isterseniz. ama mevzu işin saglıklı bir şekilde çalışmasında yoksa chrome extension yaparım yine btcturk üzerindeki sockete baglanırım veriyi alırım ama bu seferde lag oluşuyor veriyi oradan oraya yönlendire yönlendire zaman kaybediliyor.  websocket ping pong olayını deniycem sonucu size bildircem.

**Comment by mhelvacikoylu** [comment]
Merhaba,

Order Insert ve Cancel gibi komutları siz gönderemezsiniz. Böyle bir mesaj göndermeye çalıştığınızda websocket hatalı bir paket gönderdiğinizi ve veri bütünlüğünde bir kayıp olduğunu düşünerek bağlantıyı sonlandırır. Order Insert ve Cancel paketleri sunucu tarafından size gönderilir. Bu mesajları şu şekilde kullanabilirsiniz; örneğin 3 farklı cihazdan bağlısınız, 1 nolu cihazdan emir girdiğinizde 2 ve 3 nolu cihazlarınız Order Insert mesajı ile bilgilendirilir. Botunuzda bu mesajları kullanmak, siteden yaptığınız manuel bir işlem sonrası botunuzun hızlı bir şekilde sync olması gibi bir yarar sağlayabilir.

Token konusuna gelince, API v2 JWT token ile çalışıyor. Bu token'ın alınması da sso.btcturk.com üzerinden yapılıyor. Bot kullanıcılarının v2 token yönetimindeki sıkıntılarının farkındayız ancak bununla ilgili çözümün ne zaman yayına alınacağı hakkında bir tarih söylemek şu an için mümkün değil.

**Comment by emin-karadag** [comment]
@pyromus rica etsem websocket ile nasıl login olduğunuz benimle de paylaşabilir misiniz acaba?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
