### ISSUE TITLE
Referans kodu ile komisyondan kazanma özelliği gelecek mi?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#277]
Binance gibi büyük borsalarda referans kodu ile komisyondan kazanma durumu söz konusu. Sizlerde de artan komisyon oranlarından dolayı referans sistemi getirilmesi, komisyonların göze batmasını engelleyecektir.

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
