### ISSUE TITLE
Websocket orderbook'lar için 1s'de bir veri göndermek piyasayı takip etmek için verimsiz

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#278]
- Artan kullanıcı sayısı ve işlem hacminden dolay, artık saniyede yapılan işlem sayısı daha fazla
- İşlem sayısı fazla olunca aldığımız verilerin güncel olmama sorunu ile karşı karşıyayız
- Emir defterlerini daha güncel takip edebileceğimiz bir yöntem yok mu?
- Ticker içerisine **sadece son emir** hakkında Price ve Quantity bilgilerini ekleyemez misiniz? (_Binance_ gibi platformlarda bu mevcut)

## [Binance Ticker](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#symbol-order-book-ticker)

```xml
GET /api/v3/ticker/bookTicker
```

```json
[
  {
    "symbol": "LTCBTC",
    "bidPrice": "4.00000000",
    "bidQty": "431.00000000",
    "askPrice": "4.00000200",
    "askQty": "9.00000000"
  },
  {
    "symbol": "ETHBTC",
    "bidPrice": "0.07946700",
    "bidQty": "9.00000000",
    "askPrice": "100000.00000000",
    "askQty": "1000.00000000"
  }
]
```

**Comment by yemreak** [comment]
- Hacminiz ve kullanıcı sayınız arttıkça daha da fazla sorunlar oluşmaya başladı, ticker ile miktar verisi neden döndürmüyorsunuz?
- Websocket verileriniz 1s içerisinde yenileniyor ve aradaki tüm işlemler gecikmeli geliyor
- Söz konusu para olduğu için ciddiye almanızı, en azından mantıklı bir sebep ile dönüş yapmanızı bekliyorum
@BTCTraderAdmin @mhelvacikoylu @ocinbat @onurgozupek

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
