### ISSUE TITLE
User Transactions Parametreleri kabul etmiyor

### ISSUE THREAD

**Issue by MuratTopcu** [BTCTrader/broker-api-docs#28]
Hep aynı sonucu dönüyor, id alanındada hep tek id var. Hangi adrese istek yaptığım ve sonucunda hangi id ve tarihleri döndüğü bilgisini resimden görebilirsiniz.

![ekran alintisi](https://user-images.githubusercontent.com/2551727/33475312-03ba6182-d68f-11e7-989f-960c7a8e117b.PNG)

**Comment by byazici** [comment]
Şimdi gördüm. Ben de benzer bir issue açtım. Özellikle "id" nin ilgili emrin id'sine ait olması gerekmez mi? Bence ufak bir hata var. Bakılsa çözülecek.

**Comment by nepnesomao** [comment]
Evet "user transactions" ile ilgili çalışmalarımız var en kısa zaman da api' yi güncelleyeceğiz.
