### ISSUE TITLE
BtcTurk API limit buy/sell order FAILED_INVALID_PRICE_SCALE hatası

### ISSUE THREAD

**Issue by yucelalbar** [BTCTrader/broker-api-docs#280]
Merhaba,

Uygulama üzerinden BtcTurk API'sini kullanarak yapmış olduğum limit buy/sell operasyonlarına aşağıdaki şekilde hata almaya başladım:

POST https://api.btcturk.com/api/v1/order 400 Bad Request {"httpStatusCode":400,"data":null,"success":false,"message":"FAILED_INVALID_PRICE_SCALE","code":1126}

Bunun nedeni nedir?

**Comment by emin-karadag** [comment]
Göndermiş olduğunuz fiyatı kontrol ediniz. 
Örneğin BTCUSDT için konuşalım:
11289 dolar fiyattan limit emir gönderirseniz kabul edilir ancak 11289.7 dolar gibi bir emir gönderirseniz kabul edilmez.
Bu örnek üzerinden hareketle istek gönderdiğiniz kripto para işlem çifti için nasıl bir fiyat gönderdiğiniz kontrol etmenizi öneririm.

**Comment by aydinhus** [comment]
Merhaba,

Gönderilen küsüratların uyumsuzluğundan kaynaklanıyor. denominatorScale değerine göre ayarlanmalı.

https://api.btcturk.com/api/v2/server/exchangeinfo

**Comment by yucelalbar** [comment]
Yardımlarınız için teşekkürler @emin-karadag @aydinhus
