### ISSUE TITLE
Sipariş ID'sine Göre Sipariş Bilgisini Getirme

### ISSUE THREAD

**Issue by emin-karadag** [BTCTrader/broker-api-docs#281]
Merhabalar,
https://docs.btcturk.com/ adresinden incelediğim kadarıyla daha önce gönderdiğim bir siparişin Id'sine göre o sipariş bilgisini getiren herhangi bir endpoint bulamadım.

Amacım, elimdeki sipariş Id'sine göre o siparişi ve durumunu görüntülemek. Sipariş açıkta bekliyor mu, gerçekleşti mi, kapandı mı, yoksa iptal mi edildi gibi bilgilere ihtiyacım var?

Bu ihtiyacımı giderecek bir çözüm öneriniz var mıydı acaba?

**Comment by aydinhus** [comment]
Merhaba,
Benzer bir sorum olmuştu ihtiyacını görebilir belki;
#190

**Comment by emin-karadag** [comment]
@aydinhus çok teşekkür ederim, çok naziksiniz.
Peki, siz bu çözümü denediniz mi, oluyor mu?
Hatırladığım kadarıyla **allOrders** uç noktasına bir sipariş ID'si verildiğinde o sipariş ID'si ve ondan büyük olanlar da dahil olmak üzere bir çok sonuç getiriyordu.

Tabii bu yöntem de iş görür ama gelen sonuç üzerinde tekrar bi arama yapmak lazım. Oysaki direk ID'ye göre bir sorgu yapabilseydim bu harika olurdu.

Bu bağlamda eğer sizin bu konuda bir çözümünüz olduysa paylaşabilir misiniz? :)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
