### ISSUE TITLE
UserOrderMatch(441) modeli dokumantasyonda belirtilen alanlarin hepsini dondurmuyor

### ISSUE THREAD

**Issue by mehmeta** [BTCTrader/broker-api-docs#283]
Merhaba, 

Websocket uzerinden gonderilen UserOrderMatch modeli sadece asagidaki formatta geliyor:

```
[441, {'type': 441, 'id': <id>, 'user': <userid>, 'isBid': true, 'method': 0, 'pair': 46, 'symbol': 'LINKUSDT', 'amount': '1.2000000000', 'price': '9.9900000000', 'clientId': 'advanced'}]
```

[Dokumantasyonda](https://docs.btcturk.com/?python#models) ise 

numTotal, numleft,denomTotal ve denomLeft olmak uzere 4 ekstra alan belirtilmis, bu alanlarin da 441 mesaji icinde dondurulmesi icin yapabilecegim ekstra bir sey var mi yoksa sadece dokumantasyonda mi yanlis belirtilmis?

Tesekkurler!

**Comment by yemreak** [comment]
Merhabalar, bu modeli almak için nasıl bir mesaj göndermeliyim? Yardımcı olabilir misiniz #293

**Comment by mhelvacikoylu** [comment]
Merhaba,

Bu mesajı almak için websocket üzerinden oturum açmanız yeterlidir. SSO üzerinden aldığınız JWT token'ı login websocket 111 kodlu login pakediyle gönderdikten sonra (başarılı şekilde oturum açtığınıza ait 112 kodlu cevabı almanız gerekiyor) hesabınıza ait eşleşen emirlerin mesajlarını otomatik olarak almaya başlarsınız. Bunun için ekstra bir kanala girmenize gerek yoktur, oturum açmış olmanız yeterlidir.

**Comment by mehmeta** [comment]
@mhelvacikoylu Merhaba,

441 modeli uzerinde yukaridaki bahsettigim 4 alan olmadan, match isleminin oturum acmis kullanici icin maker ya da taker olarak islem gordugunu belirlemenin bir yolu su an icin yok, dogru mudur? Bu durumda gonderilen bir emir icin BTCTurk'un aldigi komisyonu kesin olarak belirlemek sadece User Transactions endpoint'i (/api/v1/users/transactions/trade) ile mumkun, oyle degil mi?

Tesekurler.

**Comment by gcoban** [comment]
@mhelvacikoylu Merhaba,

Yukarıda mehmeta problemden bahsetmiş. 441 içerisinde gelen method'u gerçekleşen işlem tipi olarak dönemez misiniz? Şu an order limit olarak girilmişse her zaman 0 dönüyor. Bunun yerine limit olarak girmiş olsak bile, market işlemi olarak gerçekleşmiş ise 1 dönülemez mi? Ya bu amaçla model'e farklı bir alan eklenebilir mi?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
