### ISSUE TITLE
Emir oluşturma  yada emir iptal API  Key lerini nasıl ala bilirim

### ISSUE THREAD

**Issue by ramazansh** [BTCTrader/broker-api-docs#285]
yardımcı olursanız  sevinirim   verilen api keyle  sadece  al /sat

**Comment by yemreak** [comment]
Hesabınızla giriş yaptıktan sonra bu alan üzerinden [IP adresiniz](https://www.google.com/search?q=whats+my+ip) ile alabilirisiniz
- https://pro.btcturk.com/hesap/api-erisimi

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
