### ISSUE TITLE
En güncel veri kanalı hangisi API / WebSocket ?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#286]
WebSocket verileri her saniye yenilendiğinden güncel olmaz diye düşünüyordum ama sanırım API daha da eski veriler taşıyormuş. Bu konuda bilgi verebilir misiniz?

- WebSocket mi API endpoint aracılığıyla alınan veriler mi daha güncel?
- API verileri sunucudaki WebSocket verilerinden mi alınmakta
- API ile OrderBook almak istediğim zaman her durumda WebSocket OrderBook feed'inden daha eski veriler gelmekte, güncel olan WebSocket verileri mi?

> Ne zaman WebSocket verilerini anlık olarak paylaşacaksınız?

**Comment by yemreak** [comment]
@ocinbat @onurgozupek

**Comment by ocinbat** [comment]
@yedhrab merhaba,

Websocket tarafından aldığınız OrderBook verileri en güncel olanıdır. Emir, tahta, trade hareketleri anlık olarak hem bizim api'larımıza hem de socket'e bağlı tüm clientlara gönderiliyor. Dolayısıyla api'den önce veriyi almak isterseniz websocket kullanmanız gerekli.
