### ISSUE TITLE
Server ın durması / Python uygulaması ile sorgulanan bid / ask değerleri vb.. sabit kalması

### ISSUE THREAD

**Issue by newcoder777** [BTCTrader/broker-api-docs#287]
Merhaba, 
Api  ile sorgulanan bid / ask değerleri vb.. değerlerin sabit kalması , bu sebepten,  gelen değerler ile telefon uygulamasında görülen değerlerin örtüşmemesi, 
Buna bağlı olarak, otomatik alım satan yapan programın yanlış alım satım yapması 
Örneğin ( 28.09.2020 pazar günü öğleden sonra saatlerde sıkıntı var idi ) 
Kontrol edilmesini, ve böyle durumlarda uygulama kullanıcısı olarak ne yapabileceğimizi, yani verilerin güncel olduğuna nasıl güvenebileceğimizi  öğrenmek istiyorum. 
Örneğin Api referansıında, "Public Endpoints" örneği güncellenip, server hatası durumlarında mesaj üretmeli belki. 
Teşekkürler 

NOT

**Comment by ocinbat** [comment]
Merhaba, ticker endpointlerinde gelen timestamp alanı epoch unix timestampin milisaniye karşılığıdır. Aldığınız cevabın güncelliğini bu değere göre kontrol edebilirsiniz.

Sent from my iPhone

On 29 Sep 2020, at 14:10, newcoder777 <notifications@github.com> wrote:

﻿

Merhaba,
Api ile sorgulanan bid / ask değerleri vb.. değerlerin sabit kalması , bu sebepten, gelen değerler ile telefon uygulamasında görülen değerlerin örtüşmemesi,
Buna bağlı olarak, otomatik alım satan yapan programın yanlış alım satım yapması
Örneğin ( 28.09.2020 pazar günü öğleden sonra saatlerde sıkıntı var idi )
Kontrol edilmesini, ve böyle durumlarda uygulama kullanıcısı olarak ne yapabileceğimizi, yani verilerin güncel olduğuna nasıl güvenebileceğimizi öğrenmek istiyorum.
Örneğin Api referansıında, "Public Endpoints" örneği güncellenip, server hatası durumlarında mesaj üretmeli belki.
Teşekkürler

NOT

**Comment by newcoder777** [comment]
Teşekkürler cevap için, 
Anladığım kadarı ile server da problem yaşanabiliyor ve bu kullanıcı tarafından fark edilmeli ( üstte belirttiğiniz timestamp yolu ile ) ve otomatik alım satım durdurulmalı, doğru mudur? 
Eğer böyle ise, bu btctürk hizmetini direkt olarak aşırı olumsuz olarak etkileyip kullanıcıların doğru veri ile alım ve satımlarını engelleyen bir etken. Fark etmeyen kullanıcılar açısından daha da sıkıntılı bir durum. 
Kabul edilebilir bir durum değil açıkçası. 
Ne dersiniz?

**Comment by ocinbat** [comment]
Teknik problemlerden ötürü sisteme erişilememe durumunda endpointlerden bu şekilde anlamlı veriler alamayabilirsiniz. 500, 503, 522 hata kodlu yanıtlar alıyorsanız sunucularımızda bir sorun vardır demektir. Benim size önerdiğim aldığınız verinin güncelliğini nasıl kontrol edebileceğiniz. Her ticker, her işlem çifti için emir defteri her an işlem görmüyor. Bu nedenle bazılarında gelen timestamp değerleri diğerlerine göre geri olabilir. Bunu aktarmaya çalıştım.

Sent from my iPhone

On 29 Sep 2020, at 16:03, newcoder777 <notifications@github.com> wrote:

﻿

Teşekkürler cevap için,
Anladığım kadarı ile server da problem yaşanabiliyor ve bu kullanıcı tarafından fark edilmeli ( üstte belirttiğiniz timestamp yolu ile ) ve otomatik alım satım durdurulmalı, doğru mudur?
Eğer böyle ise, bu btctürk hizmetini direkt olarak aşırı olumsuz olarak etkileyip kullanıcıların doğru veri ile alım ve satımlarını engelleyen bir etken. Fark etmeyen kullanıcılar açısından daha da sıkıntılı bir durum.
Kabul edilebilir bir durum değil açıkçası.
Ne dersiniz?

**Comment by newcoder777** [comment]
Teşekkürler
