### ISSUE TITLE
Rest API ile alınan OrderBook değerleri güncel değil

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#288]
Merhabalar,

- Rest API ile ticker isteğinden sonra OrderBook değerlerini alınca Ticker güncel ama OrderBook güncel değil
- Yani Rest API ile aldığım OrderBook değerleri, web sitesi üzerindeki değerler ile örtüşmüyor
- WebSocket verileri ile kıyasladığım zaman, WebSocket verilerini daha doğru geliyor lakin 1s de bir yenileniyor
- Tam olarak istediğim andaki emir defterlerini nasıl alabilirim?

> Ek rica: Ticker ile emir defterindeki son alış ve satış emrinin fiyatına ek olarak miktarı da gösterilirse daha verimli olacaktır

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
