### ISSUE TITLE
OrderBook ile Veri Çekerken "Buy" Bazen Gelmiyor!

### ISSUE THREAD

**Issue by paradyo** [BTCTrader/broker-api-docs#289]
Merhaba,

OrderBook'dan veri çekerken sadece "Buy" olanları çekiyorum ancak belirli aralıklarla hiç "Buy" bulamıyor gelen datalarda. Sadece "Sell" ler oluyor. Bu yüzden error basıyor sistem. Ancak Tether (USDT) gibi bir para biriminde bu mümkün değil ki anlık olarak kontrol ettiğimde gayet güzel bir şekilde birçok "Buy" orderı görebiliyorum.

Sebebi nedir ve nasıl çözebilirim?

Teşekkürler.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
