### ISSUE TITLE
hmacsha256 şifreli mesaj oluşturma 

### ISSUE THREAD

**Issue by akildemir** [BTCTrader/broker-api-docs#29]
merhabalar,

ben btcturk api'ye bağlanmaya çalışıyorum ama kimlik doğrulama kısmında hmacsha256 sifreli mesaj istiyor. ben c dili ile yazıyorum api documentation kısmında nasıl yapılacağına dair örnek var ama c# ile gösterilmiş. bu şifrelemenin c dilinde yazılmış bi örneği var mı acaba? ya da siz verebilir misiniz bi örnek? teşekkürler

**Comment by nepnesomao** [comment]
https://gist.github.com/tsupo/112188 
Burada ki örneğe bakabilirsiniz.

**Comment by akildemir** [comment]
ayrıca sitenizde api key oluşturmaya çalışıyorum ama "bir hata oluştu lütfen destek birimine bildiriniz" diye hata alıyorum sürekli ve oluşturulan key de hiç bir izin gözükmüyor . destek birimine 3 defa mail attım ama cevapda gelmedi?

**Comment by suleymanbyzt** [comment]
Merhaba,

Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
