### ISSUE TITLE
Mevcut spariş düzenleme PUT cevap lütfen ......

### ISSUE THREAD

**Issue by ramazansh** [BTCTrader/broker-api-docs#290]
Merhaba benim meycut bir satış emrim var onu API aracılığıyla düzenlemek istiyorum bu konuda bir örnek cod güremedim varsa paylaşırmısınız paylaşırsanız sevinirim

**Comment by ocengiz0** [comment]
Merhabe, once cancel edip sonra ayni emri guncel haliyle girebilirsiniz. PUT endpointleri olmagisi icin su an baska yolu yok :)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
