### ISSUE TITLE
Authentication hatası

### ISSUE THREAD

**Issue by berketurker14** [BTCTrader/broker-api-docs#291]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject\btc.py", line 30, in <module>
    client.authenticate()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\btcturk_api\client.py", line 160, in authenticate
    raise BTCTurkAuthenticationError(response)
btcturk_api.exceptions.BTCTurkAuthenticationError: Authentication Error.
Server Response: Unauthorized - Invalid Nonce

Sunucudan api keyime rağmen unauthorized hatası alıyorum değişken isimlerini değiştirdiğim zaman kısa bir süre sunucu,taleplerimi onaylıyor ancak devamında tekrar aynı hatayla karşılaşıyorum.

Api aracılığıyla sunucuya minimum 2 saniyede bir (daha kısa süreli aralıklarda bir talep yok) alım satım veya fiyat bilgisi talebinde bulunuyorum.Çözüm için nasıl bir yol izlemem gerekir?

**Comment by onurgozupek** [comment]
Python kodunuzda doğrulama yaparken bir yerde hata yapıyorsunuz.

Api anahtarını oluştururken tüm yetkileri verdiğinizden emin olduktan sonra aşağıdaki örnek kodu deneyebilir misiniz:

```python
import base64
import hmac
import hashlib
import requests
import json
import urllib3
try:
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
except:
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    pass

def authenticate():
    public_key = API_ANAHTARINIZ
    private_key = API_SECRET_KODUNUZ
    private_key = base64.b64decode(private_key)
    stamp = str(int(time.time())*1000)
    data = "{}{}".format(public_key , stamp).encode('utf-8')
    signature = hmac.new(private_key , data , hashlib.sha256).digest()
    signature = base64.b64encode(signature)
    headers = {"X-PCK":public_key , "X-Stamp":stamp , "X-Signature":signature , "Content-Type":"application/json"}
    return headers


url = "https://api.btcturk.com/api/v1/users/balances"
params = {}
result = {}
resp = requests.get(url=url , headers=authenticate() , params=params)
data = resp.json()
if data["success"] is True:
    return json.dumps(data,indent=2)
else:
    return "Error: " + str(data["message"])
```

**Comment by berketurker14** [comment]
Aldığım hata yine aynı hocam
Error: Unauthorized - Invalid Nonce

**Comment by berketurker14** [comment]
Sunucu saatiyle aynı saat diliminde olmamak kaynaklı bir sorunmuş., çözdüm hocam teşekkür ederim.

**Comment by xauslu** [comment]
Nasıl çözdünüz paylaşabilir misiniz ? Ben de aynı sorunu yaşıyorum .

 Timestamp ı bu şekilde alıyorum ;

  var stamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();

  Header'a bu şekilde ekliyorum örnek classta olduğu gibi ;

  client.DefaultRequestHeaders.Add("X-Stamp", stamp.ToString(CultureInfo.InvariantCulture));

**Comment by xauslu** [comment]
Kodu bu şekilde değiştirerek çözdüm. 

var stamp = DateTimeOffset.UtcNow.ToUniversalTime().ToUnixTimeMilliseconds();

**Comment by ocinbat** [comment]
Merhaba,

Stamp için https://api.btcturk.com/api/v2/server/time endpointinden gelen serverTime alanını kullanabilirsiniz.
