### ISSUE TITLE
PUT API leri lütfen dükümantasyonda sadece  adı geciyor  kendisi yok

### ISSUE THREAD

**Issue by ramazansh** [BTCTrader/broker-api-docs#292]

**Comment by ramazansh** [comment]
https://ibb.co/hgBY0jh

**Comment by ocinbat** [comment]
Public olarak sunduğumuz PUT endpointimiz yok.
V1 dışında bulunan endpointler henüz olgunluğa erişmediği için kullanmanızı önermiyoruz. Belirli bir olgunluğa ulaştıklarında dokümantasyona ekleyeceğiz.
