### ISSUE TITLE
WebSocket ile Açık Emir Durumu Hakkında Bilgi Alma

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#293]
Merhabalar,

* WebSocket üzerinden giriş yapıp 112 mesajını aldım
* Saat başı refresh yapmam gerektiği söylenmekte ama nasıl yapacağıma dair döküman bulamadım, yardımcı olur musunuz?
* Giriş yaptıktan sonra açık olan ve / veya olacak emirlerimin durumları hakkında aşağıdakiler gibi bilgi almak için göndermem gereken mesaj nedir?
  * Emir tamamlandığında
  * Emrin bir kısmı geçtiğinde
  * Emrin geçen miktarı
* UserOrderMatch mesajını gördüm ama bu mesajı almak için nasıl bir mesaj göndermem gerekmektedir gerekmektedir?
* Emri iptal ederken WebSocket mi yoksa Restfull API mi kullanmalıyım, WebSocket oluyorsa bunu nasıl yapabilirim?

Teşekkürler

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
