### ISSUE TITLE
invalid public key

### ISSUE THREAD

**Issue by yusufilker** [BTCTrader/broker-api-docs#294]
birkaç defa api key (IP sınırlamalı ve IP sınırlamasız) alarak denedim ancak hepsinde aynı hata geliyor:
{'success': False, 'message': 'Unauthorized - Invalid Public key', 'code': 1037}

ilgili header ı oluşturan kod (readme den alıntılandığı) gibi şu şekilde:

                apiSecret = base64.b64decode(self.private_key)
                stamp = str(int(time.time())*1000)
                data = "{}{}".format(self.public_key, stamp).encode('utf-8')
                signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
                signature = base64.b64encode(signature)

                headers= {
                    "X-PCK": self.public_key,
                    "X-Stamp": stamp,
                    "X-Signature": str(base64.b64encode(signature).decode('utf-8')),
                    "Content-Type": "application/json"
                    } 

not: api key gerektirmeyen sorgulamalar ticker vb. çalışıyor. 

server ile pc arasındaki zaman farkını tam olarak ölçemiyorum ancak 1 sn altında fark var, normalde ne kadar fark çalışır bilemiyorum.

**Comment by onurgozupek** [comment]
Invalid public key hatası genelde sunucunuzun zamanı ile API sunucusunun zamanı eşleşmediğinde olur. https://api.btcturk.com/api/v2/server/time uçnoktasından API sunucusunun zamanını kontrol edin.

Sorgu gönderdiğiniz uygulamada zaman diliminizi belirlerseniz sorunu aşabilirsiniz.

**Comment by yusufilker** [comment]
zaman dilimini de ekledim ancak aynı hatayı alıyorum:
{'success': False, 'message': 'Unauthorized - Invalid Public key', 'code': 1037}

Aşağıya kodu ekledim. En altta satır 49 da sizin api key leri deneyebilir misiniz?
[btcturk_2.zip](https://github.com/BTCTrader/broker-api-docs/files/5489348/btcturk_2.zip)

şimdiden teşekkürler

**Comment by onurgozupek** [comment]
```python
if self.public_key and self.private_key:
            apiSecret = base64.b64decode(self.private_key)
            pytz.timezone('Europe/Istanbul')
            stamp = str(int(time.time())*1000)
            data = "{}{}".format(self.public_key, stamp).encode('utf-8')
            signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
            signature = base64.b64encode(signature)

            headers= {
                "X-PCK": self.public_key,
                "X-Stamp": stamp,
                "X-Signature": signature,
                "Content-Type": "application/json"
                }
            return headers
````

2 hatanız var:

1. Header'da X-Signature'ı decode etmişsiniz
2. _headers fonksiyonunda return'ü unutmuşsunuz :) Fonksiyondan bir şey dönmediği için sorgu gönderirken header'ı göndermiyorsunuz.

**Comment by yusufilker** [comment]
Çok teşekkürler
