### ISSUE TITLE
GIRDIGINIZ EMIRLER KAYIT OLUYOR FAKAT EMIR LISTESINE EKLENMIYOR 2

### ISSUE THREAD

**Issue by Cagatay342** [BTCTrader/broker-api-docs#295]
Merhaba daha once de actıgım soruna bakılmadıgı ıcın 2. sini aciyorum (https://github.com/BTCTrader/broker-api-docs/issues/212)

mobilden,webden veya apiden girdigim emirler acik emirlerimde gozukuyor fakat emir listesine almıyorlar islemleri
![asset (1)](https://user-images.githubusercontent.com/5398334/98283068-288d8300-1fb0-11eb-9895-89f9f7db830b.png)
![asset (2)](https://user-images.githubusercontent.com/5398334/98283074-2a574680-1fb0-11eb-96c6-400b7d7dc153.png)
![asset (3)](https://user-images.githubusercontent.com/5398334/98283076-2b887380-1fb0-11eb-8f0b-2e87579af3a1.png)
![asset](https://user-images.githubusercontent.com/5398334/98283079-2c210a00-1fb0-11eb-99d4-884821cd91e0.png)

bunu ilettigimde bir sonuc alamadım bende gittim loglarıma alabildigim butun id leri ekledim umarım loglarınızdan bakarak bulup sonuclandırırsınız .Bugun 20:33 te gerceklesen ıslemlerde id leri ile birlikte assagida ki sekilde
![Capture](https://user-images.githubusercontent.com/5398334/98283307-8c17b080-1fb0-11eb-9ddf-98bd7623e698.PNG)
[BTCTURK PROBLEM.xlsx](https://github.com/BTCTrader/broker-api-docs/files/5496331/BTCTURK.PROBLEM.xlsx)

**Comment by ocinbat** [comment]
@Cagatay342 selamlar. Emirleri emir defterine sıralı olarak ekliyoruz, herkese eşit davranabilmek adına. Bugün 20:34'de çok fazla işlem oldu. Bu akşamki gibi yük olan durumlarda da bu işlemlerin emir defterine yansıması 10-15 saniye kadar gecikebiliyor. Sistemimizi sürekli iyileştirmeye çalışıyoruz. Bu konu ile ilgili olarak özel olarak çalışan bir ekibimiz var. Elimizden geleni yapacağız bu durumun tekrarlanmaması için.

**Comment by Cagatay342** [comment]
Hocam nisan ayinda acmisim ilk sorunu hala devam ettigine gore pek cozulecekmis gibi durmuyor .Esitlik degil aslinda sole dusunurseniz ben 125 binden satarken baska birisinin 126 binlik teklifi islem goruyorsa  alan kisiye 1000 lira fazladan harcatmis oluyorsunuz yavaslik yuzunden . Eger yogunluk api kaynakliysa apiden gelen emirlere 3 sn dr bir emir girme gibi birsey yapamaz misiniz ? . En azindan stabil yapi olur. Bu sorun hakkinda gonullu calisabilirim bende yazilimciyim iletisime gecerseniz sevinirim
