### ISSUE TITLE
Api işlemlerini Java da yapmak mümkün mü

### ISSUE THREAD

**Issue by uguraltinsoy** [BTCTrader/broker-api-docs#296]
Java için public api kullanabiliyorken private apiyi de kullanmak istiyorum ama bunun için bir dökümantasyonunuz bulunmuyor kendi araştırdığım kaynaklardan Çok birşey bulamadım **"signature"** de daha çok hata alıyorum.  **HmacSHA256**  encode işlemini  yapamadım yazılım ekibi yardımcı olursa çok sevinirim

**Comment by ocengiz0** [comment]
Merhaba @uguraltinsoy 
Ben C# ile asagidaki gibi cozuyorum, sen de ayni kodu Java'ya cevirip auth kismini halledebilirsin


            var client = new WebApiClient("https://api.btcturk.com/api/v2/server/time");
            var response = client.MakeRequest<dynamic>("", Method.GET);
            
            var nonce = response["serverTime"];

            string message = apiKey + nonce;
            using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(apiSecret)))
            {
                byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
                string signature = Convert.ToBase64String(signatureBytes);
                headers.Add("X-PCK", apiKey);
                headers.Add("X-Stamp", nonce.ToString());
                headers.Add("X-Signature", signature);
                headers.Add("Content-Type", "application/json");
            }

**Comment by uguraltinsoy** [comment]
> Merhaba @uguraltinsoy
> Ben C# ile asagidaki gibi cozuyorum, sen de ayni kodu Java'ya cevirip auth kismini halledebilirsin
> 
> ```
>         var client = new WebApiClient("https://api.btcturk.com/api/v2/server/time");
>         var response = client.MakeRequest<dynamic>("", Method.GET);
>         
>         var nonce = response["serverTime"];
> 
>         string message = apiKey + nonce;
>         using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(apiSecret)))
>         {
>             byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
>             string signature = Convert.ToBase64String(signatureBytes);
>             headers.Add("X-PCK", apiKey);
>             headers.Add("X-Stamp", nonce.ToString());
>             headers.Add("X-Signature", signature);
>             headers.Add("Content-Type", "application/json");
>         }
> ```

**Comment by uguraltinsoy** [comment]
> Merhaba @uguraltinsoy
> Ben C# ile asagidaki gibi cozuyorum, sen de ayni kodu Java'ya cevirip auth kismini halledebilirsin
> 
> ```
>         var client = new WebApiClient("https://api.btcturk.com/api/v2/server/time");
>         var response = client.MakeRequest<dynamic>("", Method.GET);
>         
>         var nonce = response["serverTime"];
> 
>         string message = apiKey + nonce;
>         using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(apiSecret)))
>         {
>             byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
>             string signature = Convert.ToBase64String(signatureBytes);
>             headers.Add("X-PCK", apiKey);
>             headers.Add("X-Stamp", nonce.ToString());
>             headers.Add("X-Signature", signature);
>             headers.Add("Content-Type", "application/json");
>         }
> ```

C# da kullanabiliyorum Javaya uyarladıgımda SHA256 da sıkıntı cıkıyor  Java ya da surdakiler gibi uyarladım 
https://www.jokecamp.com/blog/examples-of-creating-base64-hashes-using-hmac-sha256-in-different-languages/
https://stackoverflow.com/questions/32153318/httpclient-wont-import-in-android-studio
privet key ve public keyi zamanla birlikte şifreliyor sabit bi zaman yapıp programın döğru çalışıp çalışmadıgı test ettim 

Girdiğim private key bu düşün = "cGJsuu6z2CFQYGmM+kK4vAZFEtgRctv7"  ve bu zaman oldugunda  time = "1604998847535" 
C# da ve Python da bu şekilde signature çalışıyor
bana vermesi gereken  Signature cıktısı bu olmalı "/cq/s+YfCcsSXGV5R6Nh86w3sB7g+FNPQzNkNsWaDwM="  ve de veriyor

Javada bu durum farklı bana "pH361vaOgbjLhMS6DJPHEgw2o1zDSP1y5Mlg5GXEdBw=" bu cıktıyı veriyor signature hatalı oluyor o yuzden de

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
