### ISSUE TITLE
Arada çıkan hata mesajları

### ISSUE THREAD

**Issue by Ruselgun** [BTCTrader/broker-api-docs#297]
Merhabalar,
Github da  yayınladığınız (https://github.com/BTCTrader/broker-api-csharp-v2) programı vb.net ve .net framework e çevirip kullanıyorum. BTC ve ETH alım satımı hariç diğer bütün kriptoları izleyip, alım ve satım yapabiliyorum. Bunlarda result success olarak dönmüyor,  niye yapamıyorum onu da bilmiyorum, round işlemleri olması gerektiği gibi 8 ve 0 şeklinde, fikriniz varsa yardımcı olaursanız sevinirim. Ama sıkıntı şu; 24 saat 3 saniye aralıklarla izlerken arada alttaki hata mesajları çıkıyor. Neden olabilir. Yani 100 kere normal veri alıyor ama arada bunlar çıkıyor sonra yine normal olarak devam ediyor.

Token is unauthorized to do this action: [GET] /api/v1/users/balances. Please check your bearer token in request header.
Token is unauthorized to do this action: [GET] /api/v1/openOrders?pairSymbol=. Please check your bearer token in request header.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
