### ISSUE TITLE
PRICE_MUST_BE_LESS_THAN_MINPRICE hatası ne anlama geliyor acaba

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#298]
"NEO_BTC", "sell", 0.001050, 1.26925973
Mobil uygulamanız üzerinden emri verdiğimde kabul ediyor ama API üzerinden kabul etmiyor ve başlıktaki hatayı veriyor

**Comment by ocengiz0** [comment]
pairSymbol=LINK_BTC
quantity=5.8954
price=0.0008507
orderMethod=limit
orderType=sell

yukardaki bilgiler ile api uzerinden emir girmeye calsiiyorz ama PRICE_MUST_BE_LESS_THAN_MINPRICE hatasi geliyor, 

https://api.btcturk.com/api/v2/server/exchangeinfo
bu exchangeinfo apisinde belirtilen "minPrice": "0.01", gercegi yansitmiyor cunku borsa uzerinde islemler bu fiyat altinda devam ediyor, API uzerinden de islem yapabilmemiz icin ....
pairlerinde minPrice limitinin dusurulmesi gerekmekte

**Comment by yemreak** [comment]
Alt yapıdan kaynaklı bir hata imiş sanırım, şu an o hata gelmiyor

**Comment by yemreak** [comment]
Aynı hata devam etmekte

**Comment by ocengiz0** [comment]
XLM/BTC icin baslamisti duzeldi tekrar, guncelleme yapiyorlar sanirim

**Comment by ocengiz0** [comment]
hatayi duzelttiler @yedhrab

**Comment by ocinbat** [comment]
PRICE_MUST_BE_LESS_THAN_MINPRICE hatası sisteme eklenen yeni işlem çiftlerinde kullanıcıları korumak için geçici olarak eklediğimiz bir alt limitin altında bir fiyat ile işlem yapmaya çalıştığınızda karşılacağınız bir hatadır. Sorun çözüldüğü için kapatıyorum.

**Comment by ocengiz0** [comment]
Api ile koruyorsunuz ama normal webden isleme acik
