### ISSUE TITLE
UserTransactions servisinde ilgili emir numarası ihtiyacı

### ISSUE THREAD

**Issue by byazici** [BTCTrader/broker-api-docs#30]
Merhaba,
Önemli bir eksikten bahsetmek istiyorum.  Gerçekleşen bir emrin gerçekleşme fiyatını anlayamıyoruz (tek veya parçalı).  Bunun için "UserTransactions" servisine ilgili "orderID" kolonunu ekleyemez misiniz?

Emir verirken bir REF kodu alsanız onu direk basardınız o da olurdu. 
Bu konuda bir geliştirme yapabilir misiniz?

Teşekkürler.

**Comment by byazici** [comment]
"id" kolonu var ama o emrin ID bilgisini içermiyor. Hep sabit bir rakam geliyor.

**Comment by nepnesomao** [comment]
Evet "user transactions" ile ilgili çalışmalarımız var en kısa zaman da api' yi güncelleyeceğiz.
