### ISSUE TITLE
{'httpStatusCode': 400, 'data': None, 'success': False, 'message': 'PAIR_NOT_FOUND_ERROR', 'code': 1027}

### ISSUE THREAD

**Issue by muhammedyildz** [BTCTrader/broker-api-docs#300]
her zamanki kod bugun hata veriyor. "pairSymbol":"ATOMUSDT"

**Comment by ocinbat** [comment]
Merhaba, hangi endpoint?

Sent from my iPhone

On 13 Nov 2020, at 19:05, muhammedyildz <notifications@github.com> wrote:

﻿

her zamanki kod bugun hata veriyor. "pairSymbol":"ATOMUSDT"

**Comment by muhammedyildz** [comment]
buy order verirken

**Comment by ocinbat** [comment]
İlgileniyoruz. Buradan bilgi vereceğim. 👍🏻

Sent from my iPhone

On 13 Nov 2020, at 19:11, muhammedyildz <notifications@github.com> wrote:

﻿

buy order verirken

**Comment by muhammedyildz** [comment]
tesekkurler

**Comment by yucelalbar** [comment]
Merhaba @ocinbat , bu problem ile ilgili bir gelişme var mı? Dünden beri problem bende de mevcut. Api üzerinden al-sat yapamıyorum. Öte yandan Btcturk API'sini kullanan bazı arkadaşlarımda ise problem görülmedi.

**Comment by ocinbat** [comment]
Gönderdiğiniz json’ı buradan iletebilirseniz problemi anlamamıza yardımcı olacaktır.

Sent from my iPhone

On 14 Nov 2020, at 23:02, Yücel Albar <notifications@github.com> wrote:

﻿

Merhaba @ocinbat<https://github.com/ocinbat> , bu problem ile ilgili bir gelişme var mı? Dünden beri problem bende de mevcut. Api üzerinden al-sat yapamıyorum. Öte yandan Btcturk API'sini kullanan bazı arkadaşlarımda ise problem görülmedi.

**Comment by yucelalbar** [comment]
Tabi. Request ve response'u debug edip dün 84545 no'lu talepte paylaşmıştım. Ayrıca buradan da gönderiyorum.

**Comment by ocinbat** [comment]
Merhaba @yucelalbar @muhammedyildz,

omer.cinbat@btctrader.com mail adresine bu işlemi yapmak için kullandığınız kullanıcının e-posta adresini iletebilir misiniz?

**Comment by yucelalbar** [comment]
Merhaba @ocinbat ,

Mail ile ilettim.

**Comment by yucelalbar** [comment]
Merhaba @ocinbat ,

Problem ile ilgili bir güncelleme var mı acaba? Mail adresini kontrol edebildiniz mi? Problem, cloudflare'ın bloklaması nedeniyle oluşuyor olabilir mi?

**Comment by ocinbat** [comment]
Bu sorunla ilgili gerekli fix geçildi. Çözüldüğü için kapatıyorum.
