### ISSUE TITLE
Api son 2 gündür çok yavaş calışıyor!

### ISSUE THREAD

**Issue by lagosos** [BTCTrader/broker-api-docs#301]
Api 2-3 gündür aşırı yavaş calışıyor sonuclar hızlı bir şekilde dönmüyor

**Comment by ocinbat** [comment]
Merhaba @lagosos,

Bizim taraftan bakınca bir yavaşlama gözlemleyemiyoruz.
Hangi endpointlerde yavaşlama yaşadığınızı, tarih aralığınızı ve müşteri bilgilerinizi müşteri hizmetleri üzerinden paylaşırsanız arkadaşlarımız size yardımcı olacaktır.

**Comment by lagosos** [comment]
https://prnt.sc/vpcchz gene yavaşlama var emirleri botum takip edemio cron 2 saniyede bir calıştıgı için fazladan emir acıo o 2 saniye içinde işlem acamadıgı için. Saniye düşürmek zorunda kaldım yazık gercekden dünyanın parası kazanılıyor biraz yatırım yapılsa böyle sorunlar olmayacak.
