### ISSUE TITLE
Minimum Emir Tutarı

### ISSUE THREAD

**Issue by emin-karadag** [BTCTrader/broker-api-docs#302]
Merhaba BtcTürk sitesinde minimum emir tutarları aşağıdaki gibi listelenmiştir.
Örneğin buna göre BTCUSDT için minimum 1USDT, ETHUSDT için ise minimum 5USDT'lik işlem açmak gerekiyor.

![Ekran Alıntısı](https://user-images.githubusercontent.com/7556164/99187812-c7ad3a00-2769-11eb-84d3-6e5a0afdf90a.png)

Ancak API'den gelen Exchange bilgilerinde bir eksiklik var. Filters içerisindeki MinExchangeValue değeri her zaman web sitesinde gösterilen değerden farklı (https://api.btcturk.com/api/v2/server/exchangeInfo)

Örneğin aşağıdaki BTCUSDT için MinExchangeValue değeri 0.9 gösteriliyor. Oysa websitesinde 1 olarak belirtilmiş. Aynı şekilde manuel işlem açılmak istendiğinde de en az 1 dolar işlem açılabiliyor.

Bu konuda bir fikriniz var mı? Aradaki fark komisyon mu? Bunun tam hesaplaması için TickSize üzerinden mi yoksa başka şekilde mi bir hesap yapmak gerekiyor?

Teşekkürler.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
