### ISSUE TITLE
api nin tam dökümantasyonu var mı?

### ISSUE THREAD

**Issue by yusufilker** [BTCTrader/broker-api-docs#303]
"https://graph-api.btcturk.com/v1/klines/history"  gibi endpoint olduğunu bazı cevaplardan görüyorum.

bunların anlatıldığı bir döküman var mı? toplam kaç farklı api base url ve path var? bir bilen yardımcı olabilir mi?

Burada amacım dakikalık bilgi ile freqtrade veya backtrader ile entegrasyonu sağlamak. 

biraz karıştırdığımda "from" "to" olarak saniye istiyor ancak tam dakika başı olmazsa kabul etmiyor. from to keylerini  örneğin 60 dk lık veri için 05.00.00 gibi başına denk getirmek gerek. Burada server tarafında iyileştirme yapılamaz mı? verilen from to keyleri direkt eşlenmesi beklenmeyebilir. from dan büyük ilk periyot başı değer ile to dan küçük son değerler arasındaki veriler gönderilebilir. 

şimdi her periyot için saatleri ayarladık mı ona bakacağız. aşağıdaki kod talep anındaki saniyeyi   endDate = int(time.time())  ile aldığı için dakika saat başı olmadığı için veri çekemiyor...

```
    def fetch_ohlcv(self, symbol, timeframe='1m', startDate=None, endDate=None,  params={}):
        self.load_markets()
        market = self.market(symbol)

        if not startDate:
            last_30_days_timestamp = dt.datetime.timestamp(dt.datetime.today() - dt.timedelta(days=30))
            startDate = int(last_30_days_timestamp)

        if not endDate:
            endDate = int(time.time())
	
        request = {
            "symbol": market['info']['pair'],
            "resolution": timeframe,
            "from": startDate,
            "to": endDate,
        }
        response = self.publicGetKlinesHistory(self.extend(request, params))
        print(response)
        return self.parse_ohlcvs(response, market, timeframe, since, limit)
```

örneğin şu sorgu hata veriyor. 
https://graph-api.btcturk.com/v1/klines/history?symbol=BTCTRY&resolution=1&from=1602925320&to=1605603720

{
  "success": false,
  "message": "INVALID_RESOLUTION_FOR_TIME_INTERVAL",
  "code": "invalidResolutionForTimeInterval"
}

klines ile klines/history arasındaki fark nedir?

**Comment by emin-karadag** [comment]
Merhaba,
BtcTurk'ün tam API'si burada -> (https://docs.btcturk.com/#introduction)

**Comment by yusufilker** [comment]
ah keşke bu kadar basit olsa, orada zaten 2 hafta geçirdim,  hani nerde klines? klines/history dostum?

**Comment by nutcracker9999** [comment]
btcturk-api-client için ayrı bir dokümantasyon olması lazım... onun linki var mıdır?

**Comment by onurgozupek** [comment]
Graph API'da kline verileri için;

pairSymbol için BtcTurk | PRO'daki tüm işlem çiftleri (Örn BTCTRY veya BTC_TRY)

resolution için 1,5,15,30,60,240 (dakika), 1D (gün), 1W (hafta), 1Y (yıl) mum dilimlerini kullanabilirsiniz.

from: başlangıç zaman damgası (saniye)
to: bitiş zaman damgası (saniye)

Sorguyu dakikalık yapmak istiyorsanız, from - to aralığını daraltmanı gerekiyor. (Örn. 3 gün)

https://graph-api.btcturk.com/v1/klines/history?symbol=BTCTRY&resolution=1&from=1602925320&to=1603152000

**Comment by onurgozupek** [comment]
> btcturk-api-client için ayrı bir dokümantasyon olması lazım... onun linki var mıdır?

C# ile yazılmış örnekler de https://docs.btcturk.com adresinde.

Örnek kodları indirmeye ihtiyacınız varsa https://github.com/BTCTrader/broker-api-csharp (V1) ve https://github.com/BTCTrader/broker-api-csharp-v2 (V2) gözatabilirsiniz.

**Comment by nutcracker9999** [comment]
Python (pip install btcturk-api) için yazılmış örneklerin olacağı bir dokümantasyonu daha önce bir yerde görmüştüm. Aynı  https://docs.btcturk.com  formatında. Yanılıyor muyum acaba? Şimdi bulamıyorum.

**Comment by onurgozupek** [comment]
Doküman, BtcTurk API için hazırlanmışsa ve PRO için güncellenmemişse şu an çalışmıyordur. API Docs sayfasında Python örnekleri de var.

**Comment by nutcracker9999** [comment]
> Doküman, BtcTurk API için hazırlanmışsa ve PRO için güncellenmemişse şu an çalışmıyordur. API Docs sayfasında Python örnekleri de var.

API Docs Python bilgilerini çok kullanıyorum. Ben burada ( https://pypi.org/project/btcturk-api/ ) bulunan modulü install ettim. Onu kullanmak istiyordum bu sefer. Aynı python'daki "from binance.client import Client" modulü gibi. Kod yazarken bu daha kolay oluyor. BTCturk'ün böyle bir python modulü yok mu o zaman? Bilmem anlatabildim mi?

**Comment by onurgozupek** [comment]
BtcTurk tarafından yayınlanmış bir Python modülü yok. Ama API Class isterseniz, benim hazırladığım örnek koda göz atabilirsiniz. https://github.com/onurgozupek/btcturkpro-python

**Comment by nutcracker9999** [comment]
> BtcTurk tarafından yayınlanmış bir Python modülü yok. Ama API Class isterseniz, benim hazırladığım örnek koda göz atabilirsiniz. https://github.com/onurgozupek/btcturkpro-python

Çok teşekkürler bilgiler için. Bakarım sizin kodlara...
