### ISSUE TITLE
Çoklu Sipariş Silme

### ISSUE THREAD

**Issue by emin-karadag** [BTCTrader/broker-api-docs#304]
Merhabalar,
Btcturk sitesinde açık tüm siparişleri tek seferde silebiliyoruz. Ancak api üzerinden bunu yapamıyoruz anladığım kadarıyla. `cancelAll `gibi bir endpoint arıyorum aslında.
Gerçekten de yüzlerce siparişi, sipariş id üzerinden tek tek silmek zorunda mıyız?
Bilgisi olan yardımcı olursa sevinirim. :)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
