### ISSUE TITLE
JAVA da API Nasıl Kullanabilirim Signature Alamıyorum

### ISSUE THREAD

**Issue by uguraltinsoy** [BTCTrader/broker-api-docs#305]
## Java İçin Api Nasıl Kullanılır Yardım
Java için public api kullanabiliyorken private apiyi de kullanmak istiyorum ama bunun için bir dökümantasyonunuz bulunmuyor kendi araştırdığım kaynaklardan Çok birşey bulamadım "signature" de daha çok hata alıyorum. HmacSHA256 encode işlemini yapamadım yazılım ekibi yardımcı olursa çok sevinirim. C# ve Python da kullanabiliyorum Javaya uyarladıgımda SHA256 da sıkıntı cıkıyor Javaya da surdakiler gibi uyarladım

```
https://www.jokecamp.com/blog/examples-of-creating-base64-hashes-using-hmac-sha256-in-different-languages/
https://stackoverflow.com/questions/32153318/httpclient-wont-import-in-android-studio
```
privet key ve public keyi zamanla birlikte şifreliyor sabit bi zaman yapıp programın doğru çalışıp çalışmadıgı test ettim

Girdiğim private key bu  "cGJsuu6z2CFQYGmM+kK4vAZFEtgRctv7" ve bu zaman oldugunda time = "1604998847535"
C# da ve Python da bu şekilde signature çalışıyor
bana vermesi gereken Signature cıktısı bu olmalı "/cq/s+YfCcsSXGV5R6Nh86w3sB7g+FNPQzNkNsWaDwM=" ve de veriyor fakat Javada bu durum biraz daha farklı bana bu cıktıyı veriyor "WSJ31PWqyG-RZq-hx1HjgtB5UmUomXpScEjSoDhjlCI=" 

# Aşağıda C#, Python ve Java da nasıl Kullannığımı Gösteriyorum Anlayan bir Kişinin veya 11 günden beri iletişime geçmeye çalıştığım ve ilgilenmeyen  Btc Türk ekibi de denk gelir bakarsa Onlarında yardımını isterim

### Test Etmeniz için Kullanıdım Public Api Anahtarım ve private anahtarımı veriyorum (Sadece test için kullanabilirsiniz hesp erişimi yoktur)
```
Public Key "b734576e-c85c-49a2-8e2b-637f1eb6af21"
Private Key "cGJsuu6z2CFQYGmM+kK4vAZFEtgRctv7"
Time "1604998847535" (Test ederken bu zamanı kullanın Api mevcut timestamp ile çalışıyor ama sabit time ile surekli aynı cıktı alabilirsiniz)
```

### Python da kullanıdığım kod ve aldığım çıktı bu şekilde"/cq/s+YfCcsSXGV5R6Nh86w3sB7g+FNPQzNkNsWaDwM="

```
import time, base64, hmac, hashlib

apiKey = YOUR_API_PUBLIC_KEY
apiSecret = YOUR_API_SECRET
apiSecret = base64.b64decode(apiSecret)
#stamp = str(int(time.time())*1000)
stamp = str(1604998847535)
data = "{}{}".format(apiKey, stamp).encode('utf-8')
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
print(signature)
```

### C# da Kullandığım kod ve cıktım  bu şekilde "/cq/s+YfCcsSXGV5R6Nh86w3sB7g+FNPQzNkNsWaDwM="

```
private string GetSignature(long stamp)
        {
            string signature = null;
            try
            {
                var data = $"{apiKey}{stamp}";
                using (var hmac = new HMACSHA256(Convert.FromBase64String(apiSecret)))
                {
                    var signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(data));
                    signature = Convert.ToBase64String(signatureBytes);
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine("Exception occured in GetSignature method. The likely cause is a private or public key in wrong format. Exception:" + e.Message);
            }
            return signature;
        }
```

### Javada (Android) ise Bu şekilde Kullanıyorum ve cıktım  bu şekilde  "WSJ31PWqyG-RZq-hx1HjgtB5UmUomXpScEjSoDhjlCI="

```
 private static String publicKey = "b734576e-c85c-49a2-8e2b-637f1eb6af21";
 private static String privateKey = "cGJsuu6z2CFQYGmM+kK4vAZFEtgRctv7";
 private static String data = privateKey+time;

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
       
        System.out.println("Signature " + encode(data));
   }

public static String encode(String stamp) throws Exception {
        Mac sha256_HMAC = Mac.getInstance("HmacSHA256");
        SecretKeySpec secret_key = new SecretKeySpec(privateKey.getBytes("UTF-8"), "HmacSHA256");
        sha256_HMAC.init(secret_key);
        int flags = Base64.NO_WRAP | Base64.URL_SAFE;
        String hma = android.util.Base64.encodeToString(sha256_HMAC.doFinal(stamp.getBytes()),flags);
        return hma;
    }
```

**Comment by sonalp** [comment]
String publicApiKey = "b734576e-c85c-49a2-8e2b-637f1eb6af21";
		String privateApiKey = "cGJsuu6z2CFQYGmM+kK4vAZFEtgRctv7";


		long epochMilli = 1604998847535l;//Instant.now().toEpochMilli();
		try {

			byte[] hmacSha256 = calcHmacSha256(Base64.getDecoder().decode(privateApiKey),
					(publicApiKey + String.valueOf(epochMilli)).getBytes("UTF-8"));
			System.out.println(String.format("Hex: %032x", new BigInteger(1, hmacSha256)));
			String base64HmacSha256 = Base64.getEncoder().encodeToString(hmacSha256);
			System.out.println("Base64: " + base64HmacSha256);

			

		} catch (Exception e) {
			e.printStackTrace();

**Comment by uguraltinsoy** [comment]
Şu Şekilde Çözüm Buldum Malum BTC Türk ün ilgilendiği yok
```
private String getSignature(String unixTimeStamp) throws IOException, InvalidKeyException, NoSuchAlgorithmException, DecoderException {
        String data = Constants.API_PUBLIC_KEY + unixTimeStamp;
        Mac mac = Mac.getInstance("HmacSHA256");
        byte[] secretKey = DatatypeConverter.parseBase64Binary(Constants.API_PRIVATE_KEY);
        SecretKeySpec signingKey = new SecretKeySpec(secretKey, "HmacSHA256");
        mac.init(signingKey);
        byte[] bytes = data.getBytes("UTF-8");
        byte[] rawHmac = mac.doFinal(bytes);
        return Base64.encodeBytes(rawHmac);
    }
```
