### ISSUE TITLE
Restful yerine Tam WebSocket desteği

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#306]
Merhabalar,

Restful işlemlerinde `TooManyRequests` hatası çok sık gelmekte. Bundan dolayı websocket önerilmişti lakin websocket için gerekli destekler yok gibi. Aşağıdakileri WebSocket ile nasıl yapabilirim?

- Verdiğim emrin tamamlanma durumunda websocket üzerinden bildirim almak (kaynak kod örneği ya da psudo code örneği paylaşırsanız çok mutlu olurum 😊)
- WebSocket üzerinden emir verme veya iptal etme bu işlemler başarılı ile yapıldığında bildirim almak

Teşekkürler

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.

**Comment by usameozbek** [comment]
Merhabalar, 

Arkadaşın Kasım 2020'de açtığı talebi 2022'de mi değerlendirmeye aldınız ? Websocket üzerinden emir gönderebilme - cancel edebilme özelliğini bir çok müşteriniz talep ediyor. Eski açılan postlarda da bu talebi görebiliyorsunuz. Bu konu hakkındaki nihai fikirleriniz oluştuktan sonra en azından bu post üzerinden ilan edebilir misiniz ?
