### ISSUE TITLE
Orderbook verilerini web sürümündeki gibi güncel olacak şekilde yerel olarak tutmak

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#307]
Tüm orderbook verilerini güncel olarak yerel veri tabanımda tutmak için nasıl bir yol izlemeliyim, şu yol doğru mudur?

- API ile tüm orderbooklar için tek seferlik istek atmak

- Websocket ile her bir orderbook'a abone olmak
-  Orderbook verilerinin güncelliği ardışık CS değerleri ile kontrol etme, hepsinin CS değeri aynı olmalı?
- Onlardaki her veriyi yerel verilere eklemek

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
