### ISSUE TITLE
winerror 10061 no connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by aaydin-tr** [BTCTrader/broker-api-docs#308]
Api kullanımında aynı apikey ve secret ile iki farklı bilgisayardan Private endpointlere ulaşmaya çalıştığımda bir bilgisayardan sürekli 401 alıyorum diğerinde normal şekilde ulaşabiliyorum 401 aldığım bilgisayarda farklı internetlerde denedim fakat hala 401 alıyorum sorunu sebebi ne olabilir?

**Comment by ocinbat** [comment]
Bilgisayarın saati olması gerekenden farklı olabilir. api/v2/server/time endpointi ile kontrol edebilirsiniz.

Sent from my iPhone

On 27 Nov 2020, at 10:05, Abdurrahman Aydın <notifications@github.com> wrote:

﻿

Api kullanımında aynı apikey ve secret ile iki farklı bilgisayardan Private endpointlere ulaşmaya çalıştığımda bir bilgisayardan sürekli 401 alıyorum diğerinde normal şekilde ulaşabiliyorum 401 aldığım bilgisayarda farklı internetlerde denedim fakat hala 401 alıyorum sorunu sebebi ne olabilir?

**Comment by aaydin-tr** [comment]
Teşekkürler sorun sistem saati ile alakalı imiş.
