### ISSUE TITLE
/api/v1/users/transactions/trade döndüğü fee değeri neden 0?

### ISSUE THREAD

**Issue by gcoban** [BTCTrader/broker-api-docs#309]
Merhaba,

/api/v1/users/transactions/trade sorgusundan gelen bir kayıt aşağıda.

        {
            "price": "17050",
            "numeratorSymbol": "BTC",
            "denominatorSymbol": "USDT",
            "orderType": "buy",
            "orderId": 749764074,
            "id": 71225021,
            "timestamp": 1606509830790,
            "amount": "0.01673000",
            "fee": "0",
            "tax": "0"
        }

Burada fee ve tax neden 0? Bu kaydın hangi komisyon oranıyla işlendiğini ayrı sorgu atmadan nasıl anlayabiliriz? 
Aynı endpoint'in v2 versiyonunda fee ve tax doğru dönüyor fakat onda da orderId mevcut değil.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
