### ISSUE TITLE
Buy Order Limit sorunu

### ISSUE THREAD

**Issue by Mirsady** [BTCTrader/broker-api-docs#31]
**Sunucu cevabı:** {"error":{"code":400,"message":"Emir girilemedi. Lütfen tekrar deneyiniz ve hata tekrar ederse bize ulaşınız. Hata kodu: Invalid model"}}

**URI:** https://www.btcturk.com/api/exchange
**Params:** OrderMethod=0&OrderType=0&Price=1&PricePrecision=0&Amount=1&AmountPrecision=0&Total=1&TotalPrecision=0&PairSymbol=BTCTRY

**veya** 

**Params:** {'OrderMethod': 0,
        'OrderType': 0,
        'Price': 44444, 
        'PricePrecision': 0,
        'Amount': 1, 
        'AmountPrecision': 0,
        'Total': 1, 
        'TotalPrecision': 0,  
        'TriggerPrice': 0,
        'TriggerPricePrecision': 0,
        'PairSymbol': 'BTCTRY'}

**Comment by metdos** [comment]
Same problem!

**Comment by silenca** [comment]
Same problem!

**Comment by suleymanbyzt** [comment]
Merhaba,

Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
