### ISSUE TITLE
İlk kez karşılaştığım Rest Api Order Hatası

### ISSUE THREAD

**Issue by ekremus** [BTCTrader/broker-api-docs#310]
Merhaba, genelde sorunsuz çalışan scriptte arada böyle hata alıyorum. açıkçası sadece son 3-4 günde rastladım.. Öncesinde ya hiç olmadı ya da dikkat etmedim.
nedeni ne olabilir acaba?
```
ContentTypeError(RequestInfo(url=URL('https://api.btcturk.com/api/v1/order'), method='POST', headers=<CIMultiDictProxy('Host': 'api.btcturk.com', 'X-PCK': '6bd72a0b-1c92-42c0-a687-fa371d9a096b', 'X-Stamp': '1606322347000', 'X-Signature': 'ByTeRQE2mnEWKMtyidehR2Zf1VOSzNkhyN4qDPJt1xs=', 'Content-Type': 'application/json', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.6.2', 'Content-Length': '171')>, real_url=URL('https://api.btcturk.com/api/v1/order')), (), message='Attempt to decode JSON with unexpected mimetype: ', headers=<CIMultiDictProxy('Date': 'Thu, 26 Nov 2020 20:26:03 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dfb78e0a6f5760196ec35de86e091dc5b1606422362; expires=Sat, 26-Dec-20 20:26:02 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Content-Language': 'tr-TR', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'WWW-Authenticate': 'Bearer', 'WWW-Authenticate': 'Bearer', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-xss-protection': '1; mode=block', 'x-build-id': '15005', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'cf-client-ip': '3.127.221.177', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '06a7d512f30000ccf2579a2000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Set-Cookie': '__cf_bm=f7807d58f61a79dcca29268e14f853e55cb4ccdf-1606422363-1800-AQeMbuX8Rpzr8Z1SUR3JXHtaNZRad5u4bMRTOQ7mt3YZ; path=/; expires=Thu, 26-Nov-20 20:56:03 GMT; domain=.btcturk.com; HttpOnly; Secure; SameSite=None', 'Set-Cookie': '__cfruid=8fd4e6b9478c044e2888e4a410782c8b78f14689-1606422363; path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '5f865797f875ccf2-EWR')>)
```

**Comment by ekremus** [comment]
ilk defa ayın 26sında bu hatayı aldım.. 29unda 30unda ve bugün de arada bu hatayı almaktayım.
Sanırım Cloudflare yüzünden oluşuyor bu hatalar.. 

Hızlı bir çözüm üretmeniz gerekli. Ne yapamam gerekiyor ya da? Botum al dediğimde almazsa ya da sat dediğimde satmazsa zarar ederim. bu şekilde

`ContentTypeError(RequestInfo(url=URL('https://api.btcturk.com/api/v1/order'), method='POST', headers=<CIMultiDictProxy('Host': 'api.btcturk.com', 'X-PCK': '6bd82b3b-1c92-42c0-0000-fa171d9a096b', 'X-Stamp': '1606833935000', 'X-Signature': '/BKdbqpvJaj9SK+ncWaW4S/x+mbubebK/QVYEIagx1o=', 'Content-Type': 'application/json', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.6.2', 'Content-Length': '170')>, real_url=URL('https://api.btcturk.com/api/v1/order')), (), message='Attempt to decode JSON with unexpected mimetype: ', headers=<CIMultiDictProxy('Date': 'Tue, 01 Dec 2020 14:45:43 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d974fd812a644ae8c26f96058b8d849b21606833935; expires=Thu, 31-Dec-20 14:45:35 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Content-Language': 'tr-TR', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'WWW-Authenticate': 'Bearer', 'WWW-Authenticate': 'Bearer', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-xss-protection': '1; mode=block', 'x-build-id': '15083', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'cf-client-ip': '3.127.221.177', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '06c05d2cd2000097304dbf8000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Set-Cookie': '__cf_bm=c51296f10c6f9718f282314ae52e1a1b1a66a6e4-1606833943-1800-AQkU4UkhbxUq9DeXQuJEujs1LCx+Tvf+8+pEU/197pKL; path=/; expires=Tue, 01-Dec-20 15:15:43 GMT; domain=.btcturk.com; HttpOnly; Secure; SameSite=None', 'Set-Cookie': '__cfruid=74edc4fc09da7f1f7125ef9095b5fb6e51167333-1606833943; path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '5fad97c14bd19730-FRA')>)
***`

**Comment by ocinbat** [comment]
Aldığınız cevabı buraya yazabilir misiniz? Nasıl bir veri geliyor da parse edemiyorsanız görebilirsek daha hızlı yardımcı olabiliriz.

Sent from my iPhone

On 2 Dec 2020, at 09:55, ekremus <notifications@github.com> wrote:

﻿

ilk defa ayın 26sında bu hatayı aldım.. 29unda 30unda ve bugün de arada bu hatayı almaktayım.
Sanırım Cloudflare yüzünden oluşuyor bu hatalar..

Hızlı bir çözüm üretmeniz gerekli. Ne yapamam gerekiyor ya da? Botum al dediğimde almazsa ya da sat dediğimde satmazsa zarar ederim. bu şekilde

ContentTypeError(RequestInfo(url=URL('https://api.btcturk.com/api/v1/order'), method='POST', headers=<CIMultiDictProxy('Host': 'api.btcturk.com', 'X-PCK': '6bd82b3b-1c92-42c0-0000-fa171d9a096b', 'X-Stamp': '1606833935000', 'X-Signature': '/BKdbqpvJaj9SK+ncWaW4S/x+mbubebK/QVYEIagx1o=', 'Content-Type': 'application/json', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.6.2', 'Content-Length': '170')>, real_url=URL('https://api.btcturk.com/api/v1/order')), (), message='Attempt to decode JSON with unexpected mimetype: ', headers=<CIMultiDictProxy('Date': 'Tue, 01 Dec 2020 14:45:43 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d974fd812a644ae8c26f96058b8d849b21606833935; expires=Thu, 31-Dec-20 14:45:35 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Content-Language': 'tr-TR', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'WWW-Authenticate': 'Bearer', 'WWW-Authenticate': 'Bearer', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-xss-protection': '1; mode=block', 'x-build-id': '15083', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'cf-client-ip': '3.127.221.177', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '06c05d2cd2000097304dbf8000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Set-Cookie': '__cf_bm=c51296f10c6f9718f282314ae52e1a1b1a66a6e4-1606833943-1800-AQkU4UkhbxUq9DeXQuJEujs1LCx+Tvf+8+pEU/197pKL; path=/; expires=Tue, 01-Dec-20 15:15:43 GMT; domain=.btcturk.com; HttpOnly; Secure; SameSite=None', 'Set-Cookie': '__cfruid=74edc4fc09da7f1f7125ef9095b5fb6e51167333-1606833943; path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '5fad97c14bd19730-FRA')>) ***

**Comment by ekremus** [comment]
Anladığım kadarı ile;
Ben emir girdiğimde (request post) ,herhangi bir response alamadan bu hatayı alıyorum.
yardımcı olacaksa python async ve aiohttp ile request atıyorum. herhangi bir cevap gelmeden hata kodu alıyorum.

sanırım burası hata yapıyor:
`        async with session.post(url=self.base + method, headers=self.headers2(), json=params) as response:
            result = await response.json()


        try:
            print(f' Buy order at BTCTurk, Amount: {result["data"]["quantity"]}')


        except Exception as e:
            self.log_print(
                f'\n{str(datetime.now() + timedelta(hours=+3))}\nERROR: Buy order at BTCTurk, FAILED!!!\n{e}')
            self.log_print(f'result: {result}')`

ama dediğim gibi daha öncesinde böyle hata almıyordum. cludflare ne zaman eklediniz? ondan sonra olmuş olabilir?

bu arada kodu incelerseniz; try, except e girmeden hata alıyorum.

**Comment by ocinbat** [comment]
Cloudflare senelerdir sistemimizde kullanılıyor. Input output görmeden size yardımcı olamıyorum. Gönderdiğiniz ve aldığınız cevabı görebilmem lazım.

Sent from my iPhone

On 2 Dec 2020, at 11:01, ekremus <notifications@github.com> wrote:

﻿

Anladığım kadarı ile;
Ben emir girdiğimde (request post) ,herhangi bir response alamadan bu hatayı alıyorum.
yardımcı olacaksa python async ve aiohttp ile request atıyorum. herhangi bir cevap gelmeden hata kodu alıyorum.

sanırım burası hata yapıyor:
async with session.post(url=self.base + method, headers=self.headers2(), json=params) as response: result = await response.json() try: print(f' Buy order at BTCTurk, Amount: {result["data"]["quantity"]}') except Exception as e: self.log_print( f'\n{str(datetime.now() + timedelta(hours=+3))}\nERROR: Buy order at BTCTurk, FAILED!!!\n{e}') self.log_print(f'result: {result}')

ama dediğim gibi daha öncesinde böyle hata almıyordum. cludflare ne zaman eklediniz? ondan sonra olmuş olabilir?

**Comment by ekremus** [comment]
sorun arada devam ediyor. kaynağını bende bulamadım. Dün mesela 3 kere aynı hatayı aldım.

Acaba sizin docs'ta yazdığınız şuradan mı kaynaklanıyor olabilir? Aklınıza bir şey gelirse paylaşabilir misiniz?

For POST, PUT, and DELETE endpoints, the parameters may be sent as a query string or in the request body with content type `application/x-www-form-urlencoded`. You may mix parameters between both the query string and request body if you wish to do so.

```
ContentTypeError(RequestInfo(url=URL('**https://api.btcturk.com/api/v1/order**'), **method='POST'**, headers=<CIMultiDictProxy('Host': 'api.btcturk.com', 'X-PCK': '6bd3sd4e0b-1c92-42cz0-ad127-fa37121234fb', 'X-Stamp': '1607520672000', 'X-Signature': '2Iad0We9MkZasdkhZfR9+ePH13CJZ+Ea1421nQMJ/Eg=',
 'Content-Type': 'application/json', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.6.2', 'Content-Length': '170')>, 
real_url=URL('https://api.btcturk.com/api/v1/order')), (), 
**message='Attempt to decode JSON with unexpected mimetype: '**,
 headers=<CIMultiDictProxy('Date': 'Wed, 09 Dec 2020 13:31:17 GMT', 
'Content-Length': '0', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d583db01a3af9ee8e08dffd616601ffe91607520677; expires=Fri, 08-Jan-21 13:31:17 GMT; path=/; domain=.btcturk.com; 
HttpOnly; SameSite=Lax', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache',
 'Content-Language': 'tr-TR', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'WWW-Authenticate': 'Bearer', 'WWW-Authenticate': 'Bearer', 
'x-content-type-options': 'nosniff', 
'x-frame-options': 'DENY', 'x-xss-protection': '1; mode=block', 'x-build-id': '15216', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'cf-client-ip': '3.127.221.177', 
'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '06e94c07870000dfe31102f000000001',
 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Set-Cookie': '__cf_bm=354042080588ae42e0c49683033a959475be203a-1607520677-1800-AWccOAdZyE22LAJCQXk/E1oh8MXwiHpXd+Wv4dsA4rOP; 
path=/; expires=Wed, 09-Dec-20 14:01:17 GMT; domain=.btcturk.com; HttpOnly; Secure; SameSite=None', 'Set-Cookie': '__cfruid=70d5b0f24fe69d274f3d1f40d503c8b326ed8b48-1607520677; 
path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '5fef15ec0897dfe3-FRA')>)


```

**Comment by ekremus** [comment]
Ara ara bu hatayı alıyorum. aynı hatayı alan yok mu acaba hiç ?

**Comment by ekremus** [comment]
Merhaba,
Bu hatayı almıyorum, artık onun yerine:
`ConnectTimeout('')`
yazan bir hata alıyorum. Bir bilginiz var mı acaba?
