### ISSUE TITLE
Cloudflare Error 1020 Access denied

### ISSUE THREAD

**Issue by aaydin-tr** [BTCTrader/broker-api-docs#311]
Api erişime ne zamana açılacak? Belli bir tarih var mı?

**Comment by ocinbat** [comment]
Api erişime açık. Hangi adreste sorun yaşıyorsunuz?

Sent from my iPhone

On 2 Dec 2020, at 12:27, Abdurrahman Aydın <notifications@github.com> wrote:

﻿

Api erişime ne zamana açılacak? Belli bir tarih var mı?

**Comment by kchurilo** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/8331797/144651870-e03c202f-1fed-489b-982e-ec6d054d1f7f.png)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
