### ISSUE TITLE
BtcTurk REST API bazen varlıklarımı 0 olarak döndürüyor

### ISSUE THREAD

**Issue by akildemir** [BTCTrader/broker-api-docs#312]
her zaman olmuyor ama en azından 40% gibi büyük zaman diliminde varlılarımı sorguladığımda 0 cevabı alıyorum. Loglarımdan bi kaç satır;

```
[04:12:2020 16:32:07] Ask ORDER ERROR: FAILED_LIMIT_ORDER
[04:12:2020 16:32:07] USDT_BALANCE: 0.000000 ASSET_BALANCE: 0.00000000
```
Görüldüğü gibi önce satmaya çalışırken hata alıyorum çünkü miktar olarak 0 gönderiliyor Btcturk'e. Gönderilen bu miktar direk olarak rest apidan gelen sonuç. Tüm coinler için 0 döndürülüyor bu olduğu sırada sadece herhangi biri için değil. Daha önce de yanlış coin miktarı döndürüldüğüne dair  Btcturk destekten bi bug raporu göndermiştim zaten.

Bundan hariç bazen doldurulan emirlerimi sorguladığımda da çöp veri alıyorum. OrderType gibi alanlar bazen doğru olarak okunamıyor.  Umarım en kısa zamanda düzeltilirler. Baya zarara sebeb oluyorlar.

**Comment by ocinbat** [comment]
Hangi endpointi çağırıyorsunuz?
Request/response işetebilir misiniz?

Sent from my iPhone

On 4 Dec 2020, at 20:34, akildemir <notifications@github.com> wrote:

﻿

her zaman olmuyor ama en azından 40% gibi büyük zaman diliminde varlılarımı sorguladığımda 0 cevabı alıyorum. Loglarımdan bi kaç satır;

[04:12:2020 16:32:07] Ask ORDER ERROR: FAILED_LIMIT_ORDER
[04:12:2020 16:32:07] USDT_BALANCE: 0.000000 ASSET_BALANCE: 0.00000000


Görüldüğü gibi önce satmaya çalışırken hata alıyorum çünkü miktar olarak 0 gönderiliyor Btcturk'e. Gönderilen bu miktar direk olarak rest apidan gelen sonuç. Tüm coinler için 0 döndürülüyor bu olduğu sırada sadece herhangi biri için değil. Daha önce de yanlış coin miktarı döndürüldüğüne dair Btcturk destekten bi bug raporu göndermiştim zaten.

Bundan hariç bazen doldurulan emirlerimi sorguladığımda da çöp veri alıyorum. OrderType gibi alanlar bazen doğru olarak okunamıyor. Umarım en kısa zamanda düzeltilirler. Baya zarara sebeb oluyorlar.

**Comment by akildemir** [comment]
balance request için `/api/v1/users/balances`, doldurulan emirler için  `.../api/v1/users/transactions/trade?type=buy&type=sell&symbol=btc` bu endpoint.

**Comment by lagosos** [comment]
Bende yaşıyorum günde 1-2 defa 0 dönüyor o yuzden icerde ufak bi miktar bırakıyorum botun hata yapmaması için.

**Comment by akildemir** [comment]
@lagosos sadece balances endpointi olsa iyi, bi sure sonra normale donuyor zaten ama nerdeyse tum endpointler ara sira çöp veri dönduruyor. Transactions endpointi, websocket orderbook endpointi(bazen orderbook miktarinda ondalikli kesim 15 hane felan oluyor wn yuksek 8 olmasina ragmen) ve hatta limit order endpointi(bazen hatali order gonderildiginde, emirin neden hatali olduguna dair mesaj alani okunamiyor ya da bos)

Ben de biraktim o yuzden hatalari gidermeye calismiyorum artik onun yerine botun hata tolaransini yukseltiyorum ayni sekilde ama o da bi yere kadar sonucta her turlu apidan dondurulen veriye baglisin.

**Comment by lagosos** [comment]
> 
> 
> @lagosos sadece balances endpointi olsa iyi, bi sure sonra normale donuyor zaten ama nerdeyse tum endpointler ara sira çöp veri dönduruyor. Transactions endpointi, websocket orderbook endpointi(bazen orderbook miktarinda ondalikli kesim 15 hane felan oluyor wn yuksek 8 olmasina ragmen) ve hatta limit order endpointi(bazen hatali order gonderildiginde, emirin neden hatali olduguna dair mesaj alani okunamiyor ya da bos)
> 
> Ben de biraktim o yuzden hatalari gidermeye calismiyorum artik onun yerine botun hata tolaransini yukseltiyorum ayni sekilde ama o da bi yere kadar sonucta her turlu apidan dondurulen veriye baglisin.

Api deki sonuclara baglıyızda ondan daha buyuk bi sorun daha var emir işleme motorları calışmadıgı zaman en büyük zararları ozaman yazıyorum  bot kar görüp satıyor yada almaya calışiyor nafile ne alabiliosan ne sata biliosun büyük zararlar ettim bu sacmalık yüzünden heryerde yazılıyor bu sorun ama bi cözüm getiremediler kac yıldır.

**Comment by akildemir** [comment]
@lagosos kesinlikle o da var. Ben kendim için konuşuyorum hala BtcTurk'de olmamin tek sebebi islem hacmim dolayisiyla odedigim dusuk komisyon + codebasein buraya gore ayarlanmis olmasi. Zamanim pek yok baska bi yere transfer icin.

**Comment by lagosos** [comment]
TR de hem api hem yuksek hacim olan tek borsa şuanlık btcturk el mecbur bende kullanıyorum yerel olarak kullanabilecegim altarnetif yok paribu var ondada api yok. Haftalık ödediğim komisyon btcturke 10k üzerinde bugun gene fatura göndermişler 12k

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
