### ISSUE TITLE
Too many requests hatasi

### ISSUE THREAD

**Issue by ocengiz0** [BTCTrader/broker-api-docs#313]
https://api.btcturk.com/api/v2/server/time endpoint TSI ile saat 20'den soran TooManyRequests hatasi donmeye basladi

**Comment by ocengiz0** [comment]
Cloudflare Ray ID: 5fe0d5838c1ab63f

**Comment by umitk** [comment]
Benzeri sorunu ben de yaşıyorum. Sizde sorun çözüldü mü?

**Comment by ocengiz0** [comment]
evet kendi kendine cozuldu

**Comment by umitk** [comment]
Cevap için çok teşekkürler. Bende benzeri sorun cuma (18.12.2020) gününden beri devam ediyor. Çözülecekmiş gibi de durmuyor.

**Comment by ocengiz0** [comment]
Ben 50 request per min olacak sekilde throttling kurdum

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
