### ISSUE TITLE
BtcTurk

### ISSUE THREAD

**Issue by BoG4CH** [BTCTrader/broker-api-docs#314]
İyi Çalışmalar,
excele webden veri çekmek için API kullanımı nasıl olabilir?
youtube de, api ile başka bitcoin sitelerinden veri çekmeye örnek vermişler, ama açıkcası yazılım bilmediğim için headers kısmına ne yazacağımı bilemedim.
veri çekmek istediğim varlıklarım:
https://api.btcturk.com/api/v1/users/balances

Not: API kullanmadan https://api.btcturk.com/api/v2/ticker veri çekebiliyorum.

belki eklenebilecek bir macro ve button ile al sat da yaparım. tabi bir yol gösterirseniz.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
