### ISSUE TITLE
Websocket Order [451]

### ISSUE THREAD

**Issue by aderlicrazy** [BTCTrader/broker-api-docs#315]
Merhaba,

Websocket üzerinden orderınsert [451] methodu ile yeni emirleri bildiriyorsunuz, süper bir özellik teşekkürler.

Peki gönderdiğiniz veriler içinde userId gibi gereksiz bir veriyi gönderirken (kendi id'mi bana niye geri gönderiyorsunuz anlamış değilim), hayati derecede önemli olan emir, alış emri mi satış emri mi bilgisini niye göndermiyorsunuz?

Türkiyenin ilk dünyanın 4. borsası nasıl böyle bir hata yapar, gerçekten cevabınızı çok merak ediyorum...

**Comment by aderlicrazy** [comment]
`{"type":451,"pairId":31,"symbol":"XLMTRY","id":1070071398,"method":0,"userId":810613,"price":"2.256","amount":"8238","numLeft":"8238","denomLeft":"14349.4262994661312"}`

@ocinbat ilgilenir misiniz? 441 eventinde "**isBid**" verisi geliyor. Buna da eklemek çok zor olmasa gerek. Kulağımı tersten tutmak zorunda kalıyorum emrin yönünü anlamak için.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
