### ISSUE TITLE
{"success":false,"message":"INTERNAL_ERROR","code":500} 

### ISSUE THREAD

**Issue by DebuggerV1** [BTCTrader/broker-api-docs#317]
Api private endpointleriniz {"success":false,"message":"INTERNAL_ERROR","code":500}  hatası dönüyor. Desteğe soruyorum 15 gündür bir cevap alamadım. 500 hatasının sunucu taraflı olduğunu bilecek kadar anlamayan bir desteğiniz var.  Yardım eder misiniz artık?

**Comment by ocinbat** [comment]
Bana detay iletirseniz size yardımcı olayım?

Hangi endpoint?
Nasıl bir veri gönderiyorsunuz? Json verirseniz daha iyi olur. Headerları da eklerseniz daha iyi olur.
Sürekli mi arada mı alıyorsunuz?
Kullanıcınızın eposta adresini de ekleyerek bunları bana mail atarsanız size dönüş sağlarım.
omer.cinbat@btctrader.com

Sent from my iPhone

On 21 Dec 2020, at 17:44, DebuggerV1 <notifications@github.com> wrote:

﻿

Api private endpointleriniz {"success":false,"message":"INTERNAL_ERROR","code":500} hatası dönüyor. Desteğe soruyorum 15 gündür bir cevap alamadım. 500 hatasının sunucu taraflı olduğunu bilecek kadar anlamayan bir desteğiniz var. Yardım eder misiniz artık?

**Comment by DebuggerV1** [comment]
Selamlar,

Mail ile dönüş sağladım. 1 kere private apilerden cevap alabilmiştim. Ertesi gün birden cloudflare ekranı cıkmaya basladı api sayfasında. O günden beri erişemiyorum endpointlere.

**Comment by ocinbat** [comment]
Ne görüyorsunuz cloudflare ekranında?

Sent from my iPhone

On 22 Dec 2020, at 13:42, DebuggerV1 <notifications@github.com> wrote:

﻿

Selamlar,

Mail ile dönüş sağladım. 1 kere private apilerden cevap alabilmiştim. Ertesi gün birden cloudflare ekranı cıkmaya basladı api sayfasında. O günden beri erişemiyorum endpointlere.

**Comment by DebuggerV1** [comment]
Şu an cf ekranı gözükmüyor. Sadece welcome to BTCTurk API yazısı var. Bu problemi yaşadığımda cf ekranı vardı. Şu an sadece bu text var.

**Comment by MaDeRkAn** [comment]
Api'de cloudflare devreye giriyor. Bir agent paylaşılıp o agentlar cloudflare kurallarından bağımsız olabilir.
