### ISSUE TITLE
BUG | Exchange Info Scale sorunu

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#319]
Merhabalar,

Sisteminiz üzerinde https://api.btcturk.com/api/v2/server/exchangeInfo url değeri ile alınan bilgiler içerisinde yer alan `BTC_TRY`, `ETH_TRY`ve `DASH_USDT` için `numeratorScale` `denominatorScale` değerleri yanlış olup, aşağıdaki gibi güncellenmelidir.

```json
"BTC_TRY": "numeratorScale": 8, "denominatorScale": 0,
"ETH_TRY": "numeratorScale": 8, "denominatorScale": 0
"DASH_USDT": "numeratorScale": 2, "denominatorScale": 1,
```

Saygılarımla

**Comment by yemreak** [comment]
Zahmet edip de ilgilenen olacak mı acaba bu sorunla?

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
