### ISSUE TITLE
REST API Deposit/Withdrawals Sorunu

### ISSUE THREAD

**Issue by AsimCanALKAN** [BTCTrader/broker-api-docs#320]
Merhaba,
ben API ile transfer yapmak istiyorum ancak herhangi bir bilgi bulamadım. deposit/withdrawals endpointi için gerekli parametreler neler? API Dokumantasyonunu incelediğim zaman herhangi bir bilgi bulamadım. Bu konu hakkında bilgilendirme yapabilir misiniz? Ayrıca güvenlik dolayısı ile kapalı olan bir sistem olduğu söyleniyor bunu aktif hale getirmek için hangi yolları izlemeliyim?

Bir diğer sorum ise 'advanced-order-history' endpointinin kullanımı hakkında gönderdiğim requestlere yanıt alamıyorum, hatalı bir sonuç dönüyor. Hangi parametler gönderilmeli bu konu hakkında da API Dokumantasyonunda yeterli bir bilgi bulunmamakta konu hakkında bilgisi olan varsa yardımcı olursa sevinirim.

Teşekkürler.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
