### ISSUE TITLE
Matriks btcturk oto emir problemi

### ISSUE THREAD

**Issue by kl8080** [BTCTrader/broker-api-docs#321]
Merhaba matriks terminalimden btcturk hesabimdaki btc_usdt icin otomatik emir gonderimi yapmak istiyorum. Ancak devaminda “btcturk icin piyasa fiyatli emirlerde miktar alani; alis emirlerinde TL, satis emirlerinde Adet olarak girilmelidir” uyarisi cikiyor ben btc usd trade etmek istiyorum bu sekilde mumkun gozukmuyor yardiminizi rica ediyorum. Bir de alirken baska birsey satarken baska birsey teknik olarak mumkun degil bu konuda da bir gariplik var. mesela 5bin tl al die oto emir yazdim satarken hepsini satmak istiyorsam nasil adet yazabilirim?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
