### ISSUE TITLE
How i can get test credit for my developer account?

### ISSUE THREAD

**Issue by muhad37** [BTCTrader/broker-api-docs#323]
Hello dear, 
I want ask you how i can get test "credit, Balance, fund" for my developer account, 
i mean in this dashboard: 
https://pro-dev.btcturk.com/en

thanks

**Comment by muhad37** [comment]
Up...

**Comment by ocinbat** [comment]
Please consult to our customer support.

Sent from my iPhone

On 1 Jan 2021, at 19:33, muhad37 <notifications@github.com> wrote:

﻿

Up...
