### ISSUE TITLE
Maintenance | Bakım Önerisi

### ISSUE THREAD

**Issue by ekremus** [BTCTrader/broker-api-docs#324]
Merhaba,
bakıma gireceğiniz zaman websocket bağlantınızı kapatırsanız ya da fiyat bilgisi için sıfır gönderirseniz eğer, yazdığım script sayesinde bakımda olduğunu anlayıp işlem yapmaya çalışmam ve zarar etmem.

2020-12-30 04:25:37.198733
ERROR: Sell order at BTCTurk, FAILED!!!
'data'
result: {'success': False, 'message': 'SYSTEM_UNDER_MAINTENANCE', 'code': 'SYSTEM_UNDER_MAINTENANCE'}

iyi çalışmalar.

**Comment by ocinbat** [comment]
Bakım duyurularını sosyal medya hesaplarımızdan duyuruyoruz. Twitterdan bizi takip ederek bakımdan haberdar olabilirsiniz.

Sent from my iPhone

On 30 Dec 2020, at 10:37, ekremus <notifications@github.com> wrote:

﻿

Merhaba,
bakıma gireceğiniz zaman websocket bağlantınızı kapatırsanız ya da fiyat bilgisi için sıfır gönderirseniz eğer, yazdığım script sayesinde bakımda olduğunu anlayıp işlem yapmaya çalışmam ve zarar etmem.

2020-12-30 04:25:37.198733
ERROR: Sell order at BTCTurk, FAILED!!!
'data'
result: {'success': False, 'message': 'SYSTEM_UNDER_MAINTENANCE', 'code': 'SYSTEM_UNDER_MAINTENANCE'}

iyi çalışmalar.

**Comment by ekremus** [comment]
Sosyal medyayi pek takip edemiyorum. Ama twitter a bakarsaniz zaten gece saat 1-2arasi bakim olacak diye yazilmis fakat saat 4te ben islem yapamamisim.

Benim burada onermek istedigim cok basit. Binance’da da oldugu gibi. Bakim oldugu zaman websocket datalari da sifirlarsaniz cok daha efektif olabilir. 

Bakim oldugunda websocketten hic data gelmese. En azindan quantity ler gelmese, benim yazdigim bot istese de islem yapmaz.

tesekkurler.

**Comment by ekremus** [comment]
Bu aksam yine bakima girmissiniz. Alim satim Islemleri durdurulmasina ragmen websocket datasi durmadigi icin ben yine hatali islem yaptim. 

Bakima girince; Websocket datasi da dursa keske! Ya da mail gelse! Ya da bi tane telegram botunuz olsa twitterdaki paylasimlarin aynisini telegrama aktarsa. Boylece benim de haberim olurdu. 

Saygilar
