### ISSUE TITLE
Api v1 - Hatalı İstekte Empty Response Problemi

### ISSUE THREAD

**Issue by outlier-1** [BTCTrader/broker-api-docs#325]
Merhaba,

Bundan bir süre önce authentication gereken endpointlerde authentication başarısız olduğunda server neden başarısız olduğuyla ilgili bir mesaj dönerdi, Invalid Nonce veya Invalid Signature gibi. 

Api'niz için yazmış olduğum python client'inin kullanıcıları da authentication ile ilgili bir sıkıntı yaşadığında problemin nedenini anlayabiliyord. Fakat şuandaki testlerimde sunucu hatalı requestlerde empty response dönüyor. Bu da problemin kaynağı bulma konusunda sıkıntı yaratıyor.

Örnek teşkil etmesi açısından :
```
headers = {
    # request headers..         
 }
 url = "https://api.btcturk.com/api/v1/users/balances"
 response = requests.get(url, headers=headers)
 >>> response.status_code 
 >>> **401**
 >>> response.content
 >>> b''
```

Eskiden şu tarz bir cevap dönüyordu:
` ["success": False, "message": "Invalid Nonce"]`

Kullanıcı api key ile ilgili sıkıntılardan da 401 alıyor olabilir server time uyuşmazlığından da, eskiden server bunun nedenini json olarak "message" adı altında dönüyordu fakat şuan dönmüyor.

Bu konuda bir değişiklik mi oldu yoksa problem mi var bilemiyorum, bilgilendirirseniz sevinirim.

İyi çalışmalar

**Comment by ocinbat** [comment]
Selamlar, bu süreçlerde iyileştirmeler yaptık. Bu case gözden kaçmış olabilir. Kontrol edip gerekli düzenlemeleri yapacağız.

Sent from my iPhone

On 31 Dec 2020, at 15:04, Ömer Miraç Baydemir <notifications@github.com> wrote:

﻿

Merhaba,

Bundan bir süre önce authentication gereken endpointlerde authentication başarısız olduğunda server neden başarısız olduğuyla ilgili bir mesaj dönerdi, Invalid Nonce veya Invalid Signature gibi.

Api'niz için yazmış olduğum python client'inin kullanıcıları da authentication ile ilgili bir sıkıntı yaşadığında problemin nedenini anlayabiliyord. Fakat şuandaki testlerimde sunucu hatalı requestlerde empty response dönüyor. Bu da problemin kaynağı bulma konusunda sıkıntı yaratıyor.

Örnek teşkil etmesi açısından :

headers = {
    # request headers..
 }
 url = "https://api.btcturk.com/api/v1/users/balances"
 response = requests.get(url, headers=headers)
 >>> response.status_code
 >>> **401**
 >>> response.content
 >>> b''


Eskiden şu tarz bir cevap dönüyordu:
["success": False, "message": "Invalid Nonce"]

Kullanıcı api key ile ilgili sıkıntılardan da 401 alıyor olabilir server time uyuşmazlığından da, eskiden server bunun nedenini json olarak "message" adı altında dönüyordu fakat şuan dönmüyor.

Bu konuda bir değişiklik mi oldu yoksa problem mi var bilemiyorum, bilgilendirirseniz sevinirim.

İyi çalışmalar

**Comment by AsimCanALKAN** [comment]
Bu konu acilen çözülmeli 2 saat önce Authenticate olabiliyorken şu anda olamıyorum 401 alıyorum ve nedenini göremiyorum. Bundan önce herhangibir "invalid nonce" veya "api key" hatası almadım ama şu anda authenticate olamıyorum ve herhangi bir sebeb dönmüyor. @ocinbat  ne zaman sorunları çözmeye başlıcaksınız acaba? Veya IP banlama nedenleri ne olabilir aklıma şu anda o gelmeye başladı neden banlanır ve nasıl IP banı kaldırılır? Belki de sisteminiz IP mi banladı hiçbir yanlış bir işlem yapmama rağmen lütfen kontrol edin!

**Comment by ocinbat** [comment]
Tam olarak aldığınız response ve headerları gönderebilir misiniz?

Sent from my iPhone

On 10 Jan 2021, at 14:56, asimcanalkan <notifications@github.com> wrote:

﻿

Bu konu acilen çözülmeli 2 saat önce Authenticate olabiliyorken şu anda olamıyorum 401 alıyorum ve nedenini göremiyorum. Bundan önce herhangibir "invalid nonce" veya "api key" hatası almadım ama şu anda authenticate olamıyorum ve herhangi bir sebeb dönmüyor. @ocinbat<https://github.com/ocinbat> ne zaman sorunları çözmeye başlıcaksınız acaba? Veya IP banlama nedenleri ne olabilir aklıma şu anda o gelmeye başladı neden banlanır ve nasıl IP banı kaldırılır? Belki de sisteminiz IP mi banladı hiçbir yanlış bir işlem yapmama rağmen lütfen kontrol edin!

**Comment by AsimCanALKAN** [comment]
Sorun dün akşam saatlerinde çözüldü. Ancak response hala boş dönüyor o yüzden size response atma şansım yok. Zaten direk Authentication hatası dönüyordu status code = 401. Ancak düzeldi. Sadece önemli bir konu response b'' dönüyor bu düzelmeli

**Comment by AsimCanALKAN** [comment]
Merhaba,
Bu konu ile bağlantılı olabileceğini düşündüğüm için buraya bu sorunu comment olarak ekliyorum. @outlier-1 @ocinbat
Son günlerde LIMIT ORDER gönderdiğimde bana dönen bir cloudyflare html kodu var ve sistemimde giden orderın price, amount, id gibi değerlerini alamadığı için büyük bir sorun yaşıyorum (Gün içinde 3-4 kere oluyor gece olması manuel müdahaleyi de zorlaştırdığı için dengesizlik oluşuyor). Neden HTML response döner ki sistem? Üstüne üstlük bu yanıt döndüğünde ORDER isteğim gerçekleşmiş oluyor! Bu çok büyük bir sorun serverlarınızı kesinlikle gözden geçirmelisiniz.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
