### ISSUE TITLE
Çözülemeyen  <Response [401]>  Unauthorized hatası

### ISSUE THREAD

**Issue by UmutAlihan** [BTCTrader/broker-api-docs#327]
Merhabalar,
 
Documentation'da FAQ kısmında bulunan tüm olasılıkları denedim ve çözmeye çalıştım. API Erişim listesinde uygun yetkileri verdim. Time server ile sync olmak için Europe/London'a göre timestamp oluşturuyorum. Signature yazımını header içinde gerçekleştiriyorum. Ancak aşağıdaki gibi hata almaya devam ediyorum:

Yardımcı olabilir misiniz?

```python
base = "https://api.btcturk.com"
method = "/api/v1/users/balances"
uri = base+method

result = requests.get(url=uri, headers={
  "X-PCK": apiKey,
  "X-Stamp": str(int(datetime.datetime.timestamp(datetime.datetime.now(pytz.timezone('Europe/London')))*1000)),
  "X-Signature": str(base64.b64encode(base64.b64encode(hmac.new(base64.b64decode("*******"), "{}{}".format(apiKey, stamp).encode('utf-8'), hashlib.sha256).digest())).decode('utf-8')),
  "Content-Type": "application/json"
})
print(result)```

**Comment by xauslu** [comment]
Merhaba ben de birçok yöntem denedim fakat aynı hatayı alıyorum sürekli.

**Comment by write4alive** [comment]
Selamlar , 
windows saat tarih ayarlarını sync yapıp gönderin neden london olarak gönderiyorsunuz?

```
  def A_init():
        .......
        stamp = str(int(time.time())*1000)
        data = "{}{}".format(public_key, stamp).encode('utf-8')
        ......
        headers = {"X-PCK": public_key, "X-Stamp": stamp,
                   "X-Signature": signature, "Content-Type": "application/json"}
        return headers
```

**Comment by onurgozupek** [comment]
Tarih saat verisi UTC (veya GMT) olarak veriliyor, ancak siz scriptinizin başına timezone ekleyerek zaman farkını ortadan kaldırabilirsiniz.

**Comment by xauslu** [comment]
Yanıtlarınız için teşekkürler . Time zone dan kaynaklı hata alıyormusum dediğiniz gibi. 
Bu kod satırı ile düzeldi durum ;
var stamp = DateTimeOffset.UtcNow.ToUniversalTime().ToUnixTimeMilliseconds();

**Comment by UmutAlihan** [comment]
cok tesekkurler destekleriniz icin

**Comment by readak** [comment]
> Yanıtlarınız için teşekkürler . Time zone dan kaynaklı hata alıyormusum dediğiniz gibi.
> Bu kod satırı ile düzeldi durum ;
> var stamp = DateTimeOffset.UtcNow.ToUniversalTime().ToUnixTimeMilliseconds();

Benim de sorun devam ediyor HMAC256'dan olduğunu tahmin ediyorum kodlamanız visual'a benziyor giriş yaptırabildiyseniz eğer yardımcı olabilirmisiniz mail adresiniz varsa yazabilirmisiniz. teşekkürler
