### ISSUE TITLE
Immediately or Cancel (IoC) Desteği

### ISSUE THREAD

**Issue by isos81** [BTCTrader/broker-api-docs#329]
Merhaba. Binance'teki gibi IoC emir desteği vermeyi planlıyor musunuz? Veya IoC'yi sizin tarafta yapabileceğim bir yöntem var mı? 

Not: Emri gönder, dolmadıysa cancel edin (manüel IoC) walkaround'ı bizim işimize yaramıyor maalesef.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
