### ISSUE TITLE
test coin

### ISSUE THREAD

**Issue by muhammedkulak** [BTCTrader/broker-api-docs#33]
Merhaba, test için coin nasıl oluşturulur?

**Comment by mucahithy** [comment]
Merhaba bu sorunu nasıl çözdünüz acaba?

**Comment by ocinbat** [comment]
Müşteri hizmetlerini arayıp yardım alabilirsiniz.

Sent from my iPhone

On 22 Aug 2020, at 22:33, mucahithy <notifications@github.com> wrote:

﻿

Merhaba bu sorunu nasıl çözdünüz acaba?
