### ISSUE TITLE
Unauthorized - INTERNAL_ERROR

### ISSUE THREAD

**Issue by emrahtopcu** [BTCTrader/broker-api-docs#330]
Tüm private endpointlerde 'Unauthorized' veya 'INTERNAL_ERROR' hatalarını almaya başladım. Son 1 saattir bu şekilde.

**Comment by ocinbat** [comment]
Merhaba,

Sorun yaşadığınız dönemde sistem yoğunluğu nedeniyle bazı endpointlerde bu tarz sorunlar yaşayabiliyoruz.

**Comment by emrahtopcu** [comment]
İlginiz için teşekkür ederim.
