### ISSUE TITLE
Market Order Verirken ORDER_METHOD_NOT_SUPPORTED hatası

### ISSUE THREAD

**Issue by DebuggerV1** [BTCTrader/broker-api-docs#331]
Merhaba, 

Limit orderı verebiliyorum ama Market Order verirken api'den hata alıyorum. Gönderdiğim parametreler ektedir.
Sadece type'ı limit yaptığımda sorunsuz çalışıyor. Problem nedir bulamadım.

![Image Pasted at 2021-1-6 16-47](https://user-images.githubusercontent.com/51318148/103775400-0a3f1480-503f-11eb-8145-53aaa69533e3.png)

**Comment by DebuggerV1** [comment]
Hata mesajı su sekilde : POST https://api.btcturk.com/api/v1/order 400 Bad Request {"httpStatusCode":400,"data":null,"success":false,"message":"ORDER_METHOD_NOT_SUPPORTED","code":1134;

**Comment by ocinbat** [comment]
Merhaba,

Piyasa hareketliliği nedeniyle kullanıcılarımızın zarar etmesini engellemek için geçici olarak market emirleri kapatabiliyoruz. 

Fiyat çok hızlı inip çıkarken market emir girmek, kullanıcıların gördüğü fiyattan değil de çok farklı bir fiyattan alım ya da satım yapmasına neden olabiliyor. Bu nedenle böyle bir koruma önlemi alıyoruz.

**Comment by DebuggerV1** [comment]
İlginç bir yaklaşım olmuş. 
Toptan kapatmanız tüm işlevleri sekteye uğratıyor. 
Belli bir yüzde sınırı koymanız daha mantıklı değil mi?

**Comment by ocinbat** [comment]
Bazı kullanıcılar girerken, bazıları emir giremezse insanlara haksızlık yapmış olabiliriz. Market emirlerin doğası gereği onları engellemek kullanıcıların zarar etmesini önleyecek bir önlem. Limit emirlerde fiyatı siz belirlediğiniz için istediğiniz fiyattan alım yapabiliyorsunuz. Market güncel fiyat üzerinden miktar hesaplandığı için insanların istemedikleri sonuçlar doğabiliyor çok hızlı piyasada. 250.000 TL'den bitcoin satmak isteyen birisine 240.00 TL'den işlem yaptırırsak müşteri üzülebilir.

**Comment by ekremus** [comment]
> Bazı kullanıcılar girerken, bazıları emir giremezse insanlara haksızlık yapmış olabiliriz. Market emirlerin doğası gereği onları engellemek kullanıcıların zarar etmesini önleyecek bir önlem. Limit emirlerde fiyatı siz belirlediğiniz için istediğiniz fiyattan alım yapabiliyorsunuz. Market güncel fiyat üzerinden miktar hesaplandığı için insanların istemedikleri sonuçlar doğabiliyor çok hızlı piyasada. 250.000 TL'den bitcoin satmak isteyen birisine 240.00 TL'den işlem yaptırırsak müşteri üzülebilir.

selam, Bu benim alacağım bir risk ve benim programım bu şekilde çalışıyor.
Bence daha önemlisi, bu şekilde habersiz bir şekilde karar alıp uygulamanız büyük zararlara yol açmakta.. :/ Eğer önceden haber verseydiniz ona göre bir plan yapabilirdim. Hem hatanın nedenini öğrenmem 5 saatimi aldı hem de aldığım hatalar ile yeteri kadar zarara uğradım. teşekkürler.

**Comment by 0x21** [comment]
Geliştirdiğim strateji anlık oluşan hareketliliklerdeki bazı fırsatları değerlendiriyor ben o an ne fiyattan satılırsa veya alınırsa basacağım ben hocam bu nasıl bir fikir ya hangi parlak zekadan çıktı bu ? Adam emir giremezse haksızlık oluyormuş. Günlerce uyumuyorum ben o kod optimize çalışsın da diğerlerinden daha hızlı emir girsin diye siz aklınızı mı kaçırdınız bu nasıl bir önlem ya siz bu apiyle kendimize platformu kullanmak için arayüz yazdığımızı falan mı düşünüyorsunuz ?

**Comment by aligoren** [comment]
Bu tarz hatalarin ne oldugunu buradan ogrenmek istemeyiz ama. Ornek veriyorum bunlara dair aciklamalari API dokumantasyonuna ekleseniz biz sorunu kodlarimizda aramasak olmaz mi?

**Comment by 0x21** [comment]
BTCTURK api dökümantasyonu hala çöp kovasından hallice. Aklıma gelmişken not düşeyim.
