### ISSUE TITLE
TooManyRequest çok sık geliyor

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#332]
Sizlerin de sunucunuz yormayacağız ve bizlerinde hızlı işlem yapmasına olanak sağlayacak **tam fonksiyonel Websocket** yapısını ne zaman devreye sokacaksınız? WebSocket eksiklikleri şunlar:

- Emir verme, silme, güncelleme
- Kullanıcı kaynak kontrolü (btc, usdt gibi varlıklarımıza bakma)
- Açık emirleri alma, emrin tamamlanma durumunu kontrol etme
- Refresh token ve access token alma ve oturumu güncel tutma

> Ek olarak ws ile giriş yaptığımızda tamamlanan emirler hakkında bilgi alabiliyoruz ama girişi kalıcı yapmamız pek mümkün olmuyor, access ve refresh token bilgileri otomatik olarak nasıl alınabilir?

**Comment by AsimCanALKAN** [comment]
Kesinlikle bu sorunun çözülmesi gerekli ama aylardır hiçbir gelişme yok cevap veren bir ekip de yok karşımızda. Umarım çözülür bu  sorunun takipcisiyim ben de.

**Comment by EUA** [comment]
TooManyRequest hatası limitlere takılınıldığı için oluyormuş ama... O limitler nedir, nerede yazar bilen var mı?

**Comment by ocinbat** [comment]
https://docs.btcturk.com/#rate-limits

Sent from my iPhone

On 25 Mar 2021, at 20:02, Erdem U. Altinyurt ***@***.***> wrote:

﻿

TooManyRequest hatası limitlere takılınıldığı için oluyormuş ama... O limitler nedir, nerede yazar bilen var mı?

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
