### ISSUE TITLE
Nedeni ne olabilir? -ORDER_METHOD_NOT_SUPPORTED-

### ISSUE THREAD

**Issue by ekremus** [BTCTrader/broker-api-docs#333]
Merhabalar, 

Önceden hata almadığım ve kodda hiçbir değişiklik yapmadığım halde aşağıdaki hatayı aldım aniden bugün. (Dün akşam ve önceki günler sorunsuz çalışıyordu) 

Hata: {'httpStatusCode': 400, 'data': None, 'success': False, 'message': 'ORDER_METHOD_NOT_SUPPORTED', 'code': 1134}

Nedeni ne olabilir? Fikirlerinizi paylaşabilir misiniz?

Sevgiler.

**Comment by ekremus** [comment]
şöyle söyliyim, binlerce emir verdim sorunsuz çalışıyordu. Bu hatayı ilk defa bu sabah aldım. BTCUSDT Market emri verdiğimde bu hatayı alıyorum. Limit emri verince bu hata oluşmuyor.

**Comment by aydinhus** [comment]
#331

**Comment by ekremus** [comment]
> #331

teşekkür ederim.
