### ISSUE TITLE
Api kafayı yemiş durumda

### ISSUE THREAD

**Issue by lagosos** [BTCTrader/broker-api-docs#334]
Sürekli bakiyeleri yanlış gösteriyor alım satım yaptıkdan sonra bi bakıyorum bakiye 0.1 bi bakıyorum 0.05 sürekli yanlış rakamlar veriyor

**Comment by lagosos** [comment]
Hala sorun devam ediyor bakiye yanlış dönüyor sürekli daha bugune kadar sorun yokdu

**Comment by teodorkasap** [comment]
bir para birimine dair alım satım işlemlerini döndürürken, bazılarını göstermiyor

**Comment by lagosos** [comment]
Bot yaptık rahat ederiz die ama nerde btcturk'e guvenim kalmadı

**Comment by lagosos** [comment]
Alım satım gercekleşiyor 10 20dk sonra bakiyeler günceleniyor bot kafayı yemesinde napsın.

**Comment by teodorkasap** [comment]
işlemlerin bazıları döndürülmediği için ben de ortalama fiyat hesaplatamıyorum bota

**Comment by lagosos** [comment]
Komisyon olayıda sacma sapan kendi cıkarlarına göre kodlamışlar. Örnek olarak alışdaki emre kismi olarak 1000 lotun 1 tanesini alışdaki bi adama satıgınızdaki kalan 999 lotun hepsini piyasa alıcı olarak komisyonlandırıyor normalde 1 lotu piyasaya satıyorum  geri kalan 999 lotun ücretlendirmesini piyasa yapıcı olarak alması gerek. Ama btcturk bu şekilde yapmıyor hepsini emri iptal edene kadar piyasa alıcı olarak komisyonlandırıyor iki alıcıdan satıcıdanda piyasa alıcı komisyonu alınıyor haksız kazanc saglıyorsunuz.

**Comment by lagosos** [comment]
Bakiye güncelemekden acizsiniz sizin yüzünüzden fazladan yüksekden fazla mal almışım !!!

**Comment by EUA** [comment]
> Komisyon olayıda sacma sapan kendi cıkarlarına göre kodlamışlar. Örnek olarak alışdaki emre kismi olarak 1000 lotun 1 tanesini alışdaki bi adama satıgınızdaki kalan 999 lotun hepsini piyasa alıcı olarak komisyonlandırıyor normalde 1 lotu piyasaya satıyorum geri kalan 999 lotun ücretlendirmesini piyasa yapıcı olarak alması gerek. Ama btcturk bu şekilde yapmıyor hepsini emri iptal edene kadar piyasa alıcı olarak komisyonlandırıyor iki alıcıdan satıcıdanda piyasa alıcı komisyonu alınıyor haksız kazanc saglıyorsunuz.

Bu düpedüz hırsızlık.

**Comment by lagosos** [comment]
Gene bakiyeler yanlış dönmeye başladı. 02:22 16.01.2021 tarih.

**Comment by KebabLord** [comment]
10 ocak düşüşünün yaşandığı sırada site 3 kere çöktü, satış emirleri error verdi. Sitenin başarısız durumu insanları %8 zarara soktu.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
