### ISSUE TITLE
WebSocket Token Değeri Yenileme

### ISSUE THREAD

**Issue by AsimCanALKAN** [BTCTrader/broker-api-docs#335]
Merhaba Destek,
Websocket servisinizi kullanıyorum ancak bazen bağlandığım kanalda kopma oluyor (Login Modeli) kopma yaşandığı anda benim tekrardan işlem yapmam için tokeni yenilemem lazım ancak o sırada token de değişmiş oluyor ve v2/token/refresh sistemine de login olamadığım için bağlantıyı yenileyemiyorum. Kullandığım sistemden dolayı her 45 dkda bir tokeni yenile sistemini ekleyemiyorum. Artık şu token sorununu çözseniz biz de rahatlasak ve gönül rahatlığıyla Websocket kullanabilsek keşke.

**Comment by yemreak** [comment]
Şu anda token yenilemek için nasıl bir yöntem izliyorsunuz veya onun alternatifi olarak ne yapıyorsunuz?

**Comment by emreacar** [comment]
WebSocket tarafı tutarlı değil. Botu her başlattığımda BTC arayüzünden giriş yapıp token ve refresh token değerlerini localStorage üzerinden alıp bota kendim veriyorum. Her 45 dakika da bir refresh_token gönderip varolan token'ı yeniletiyorum. Ama botu kapatıp yeniden açtığım da aynı işlemi yeniden yapmam gerekiyor. Bunun koca bir saçmalık olduğunu sistemi kurgulayan arkadaşlar göremiyorlar mı anlamıyorum. API üzerinden işlem yaparken nasıl token değerini almamıza gerek yok signate üretip istek atabiliyorsak aynı şekilde websocket için de secret değerlerini kullanarak giriş yapabiliyor olmamız lazım.

**Comment by ocinbat** [comment]
Selamlar, kullandığınız websocket bizim arayüzleri geliştirmek için kullandığımız bir websocket. Buraya son kullanıcının programatik olarak erişmesi için henüz destek sağlamıyoruz. İş planlarımız arasında. Konu ile ilgili güncellemeleri dokümantasyonunuzdan takip edebilirsiniz.

Sent from my iPhone

On 14 May 2021, at 12:08, Emre Acar ***@***.***> wrote:

﻿

WebSocket tarafı tutarlı değil. Botu her başlattığımda BTC arayüzünden giriş yapıp token ve refresh token değerlerini localStorage üzerinden alıp bota kendim veriyorum. Her 45 dakika da bir refresh_token gönderip varolan token'ı yeniletiyorum. Ama botu kapatıp yeniden açtığım da aynı işlemi yeniden yapmam gerekiyor. Bunun koca bir saçmalık olduğunu sistemi kurgulayan arkadaşlar göremiyorlar mı anlamıyorum. API üzerinden işlem yaparken nasıl token değerini almamıza gerek yok signate üretip istek atabiliyorsak aynı şekilde websocket için de secret değerlerini kullanarak giriş yapabiliyor olmamız lazım.

**Comment by emreacar** [comment]
Merhaba, @ocinbat 

Bunu söylemeniz oldukça kötü oldu. Buradaki dokümanı da kendiniz için mi yayınladınız ? https://docs.btcturk.com/#websocket-feed

**Comment by ocinbat** [comment]
Dokümantasyonda eksiklikler / hatalar olabilir. Yakın zamanda buraya da bir güncelleme yapacağız. Bu bilgiyi gösterdiğiniz için ayrıca teşekkür ederiz. 👍🏻

Sent from my iPhone

On 14 May 2021, at 12:23, Emre Acar ***@***.***> wrote:

﻿

Merhaba, @ocinbat<https://github.com/ocinbat>

Bunu söylemeniz oldukça kötü oldu. Burada ki dokümanı da kendiniz için mi yayınladınız ? https://docs.btcturk.com/#websocket-feed

**Comment by yemreak** [comment]
Merhabalar @emreacar, refresh tokan verisi gönderirken `Internal_Server_Error` almaktayım, nasıl gönderdiğinizi detaylı bir şekilde aktarabilir misiniz? 

Benim kullandığım ve çalışmayan yapı:

```python
# Değişkenlerde yer alan bilgiler doğrudur, commission alma işleminde başarılı şekilde çalışmıştır
url = f"{API_BASE}/api/v2/token/refresh"
session.headers.update({"authorization": f"{token_type} {token}", "content-type": "application/json"})
response = session.post(url, data={"token": refresh_token})
```

**Comment by emreacar** [comment]
Merhaba @yedhrab 

Ben nodeJS üzerinde çalışıyorum, servise  token parametresine refresh token değerini ve aşağıda belirttiğim şekilde header parametrelerini geçip  post olarak gönderiyorum.
```

request.post('api/v2/token/refresh', {
  token: REFRESH_TOKEN
}, {
 headers: [
       'X-PCK': this.API_KEY,
       'X-Stamp': now.getTime().toString(),
       'X-Signature': this.createSignature(),
       Authorization: `Bearer ${this.API_TOKEN}`
  ]
}
```

**Comment by yemreak** [comment]
> Merhaba @yedhrab
> 
> Ben nodeJS üzerinde çalışıyorum, servise token parametresine refresh token değerini ve aşağıda belirttiğim şekilde header parametrelerini geçip post olarak gönderiyorum.
> 
> ```
> 
> request.post('api/v2/token/refresh', {
>   token: REFRESH_TOKEN
> }, {
>  headers: [
>        'X-PCK': this.API_KEY,
>        'X-Stamp': now.getTime().toString(),
>        'X-Signature': this.createSignature(),
>        Authorization: `Bearer ${this.API_TOKEN}`
>   ]
> }
> ```

Teşekkür ederim hızlı dönüşünüz için, deniyorum hemen

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
