### ISSUE TITLE
TRY bazlı çiftlerde emir girişinde BadRequest hatası (C# APIClientV1)

### ISSUE THREAD

**Issue by bymulker** [BTCTrader/broker-api-docs#336]
Merhaba,

Bir süredir BtcTurk API üzerinden ApiClientV1 kullanarak kendi emirlerimi gönderecek bir program yapıyorum. Bu kodda exchange infoyu indirecek yordam bulunmuyordu. Yazdım ve problemsiz çalışıyor. (isteyen olursa paylaşabilirim) Balance, Transaction ve Kripto tabanlı çiftlerde emir girişinde sorun yaşamıyorum. Ancak iş TRY tabanlı çiftlere gelince BadRequest alıyorum. Varlığımda 5 ethereum var, timestamp'i kontrol ettim, 13 haneli, server zamanı aşağıdaki gibi uyuşuyor görünüyor.
Teşekkürler

kod;
{"serverTime": 1610215353239}
1610215353239

https://api.btcturk.com/api/v2/server/time adresinden dönen ;
{"serverTime":1610215426997,"serverTime2":"2021-01-09T18:03:46.9965862+00:00"}

Kod ; 

 var limitSellOrder = new OrderInput
                {
                    Quantity = 0.1m,
                    Price = 7000,
                    StopPrice = 7100,
                    NewOrderClientId = "test",
                    OrderMethod = OrderMethod.StopLimit,
                    OrderType = OrderType.Sell,
                    PairSymbol = "ETHTRY"
                };

                ////Create New Order
                var orderOutput = client.CreateOrder(limitSellOrder);
` 
public async Task<ReturnModel<OrderOutput>> CreateOrder(OrderInput orderInput)
        {
            const string requestUrl = "api/v1/order"; 

            var response = await SendRequest(HttpVerbs.Post, requestUrl, orderInput, requiresAuthentication: true);

            var returnModel = response.ToReturnModel<OrderOutput>();

            return returnModel;
        }

private async Task<HttpResponseMessage> SendRequest(HttpVerbs action, string url, object inputModel = null, bool requiresAuthentication = false)
        {
            HttpResponseMessage response = null;

            using HttpClient client = new HttpClient { BaseAddress = new Uri(_resourceUrl), Timeout = TimeSpan.FromSeconds(100) };
            if (requiresAuthentication)
            {
                long stamp; //var stamp = GetStamp(client);
                using (HttpRequestMessage requestMessageServerTime = new HttpRequestMessage(HttpMethod.Get,
                        "https://api.btcturk.com/api/v2/server/time"))
                {
                    //Send
                    HttpResponseMessage responseServerTime = await client.SendAsync(requestMessageServerTime);

                    //get json server time from response
                    string jsonString = await responseServerTime.Content.ReadAsStringAsync();
                    dynamic serverTime = JsonConvert.DeserializeObject(jsonString) as dynamic;
                    stamp = Convert.ToInt64(serverTime.serverTime);
                }

                string stampStr = stamp.ToString(CultureInfo.InvariantCulture);
                string signature = GetSignature(stamp);

                client.DefaultRequestHeaders.Add("X-PCK", _publicKey);
                client.DefaultRequestHeaders.Add("X-Stamp", stampStr);
                client.DefaultRequestHeaders.Add("X-Signature", signature);
            }

            try
            {
                switch (action)
                {
                    case HttpVerbs.Post:
                        var postContent = inputModel.ToHttpContent();
                        response = await client.PostAsync(url, postContent);
                        break;
                    case HttpVerbs.Get:
                        response = await client.GetAsync(url);
                        break;
                    case HttpVerbs.Delete:
                        response = await client.DeleteAsync(url);
                        break;
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                response = null;
            }

            if (response == null)
            {
                Console.WriteLine("Cannot get response from server.");
                return null;
            }

            if (response.StatusCode == HttpStatusCode.Unauthorized)
            {
                Console.WriteLine($"Token is unauthorized to do this action: [{action.ToString().ToUpper()}] /{url}. Please check your bearer token in request header.");
            }

            return response;
        }`

**Comment by idmrbs** [comment]
Merhaba,
Aynı problemle karşılaşmaktayım. Problemi nasıl çözdünüz?
Teşekkürler.
