### ISSUE TITLE
DİKKAT: "Hesap Hareketlerim" sayfasında bakiye kısmı GİZLENMİŞ!

### ISSUE THREAD

**Issue by EUA** [BTCTrader/broker-api-docs#337]
Eskiden çekim yada yatırma işlemlerinde "kalan bakiye" gözükmekte idi.
Şimdi bir işlemden sonra hesapta ne kadar bakiye olduğu GİZLENMİŞ.
**Bunun sebebi nedir?**
Dahası bu kanunlara uygun mudur?
Herkesin dikkatli olmasını tavsiye ediyorum.

**Comment by ocinbat** [comment]
Merhaba Erdem bey,

Konu ile ilgili hata bildirimi yaptığınız için sağolun. Buradaki veriyi hesaplayan servisimizde bir sorun oluşmuş. Konu ile ilgileniyoruz. Çok yakın zamanda veriyi sitemizden tekrar görebilirsiniz. Ayrıca hata bildiriminiz için teşekkür ederiz.
