### ISSUE TITLE
BALANCE (BAKIYE) erişimi kaldırıldı mı ? 

### ISSUE THREAD

**Issue by cngzhn** [BTCTrader/broker-api-docs#338]
Çok lakayık bir API yönetim sistemine mevcutlar , 13 aydır dokunulmamış bir kod yapısı ve çalışmayan özellikler mevcut.

**Comment by ocinbat** [comment]
Selamlar, bu veriyi hesaplayan servisimizde geçici bir problem oluştu. Düzenlemelerden sonra geçmiş verilerinize de birkaç gün içinde erişebileceksiniz.

**Comment by cngzhn** [comment]
Anlık bakiyeyi alabilsek yeterli olurdu

13 Oca 2021 Çar, saat 22:38 tarihinde Ömer Cinbat <notifications@github.com>
şunu yazdı:

**Comment by agumustekin** [comment]
Bu sorun düzelmedi mi hala?
