### ISSUE TITLE
FAILED_INVALID_PRICE_SCALE

### ISSUE THREAD

**Issue by DebuggerV1** [BTCTrader/broker-api-docs#339]
Deminotar ve nominator değerlerine dikkat etmeme rağmen bu hatayı alıyorum. Bir stabilite problemi var. Aynı digit standartlarına sahip 3 emirden 1 ya da 2si çalışıyor, bazen de hataya bu hataya düşüyor. Hata log'u ektedir;

POST https://api.btcturk.com/api/v1/order 400 Bad Request {"httpStatusCode":400,"data":null,"success":false,"message":"FAILED_INVALID_PRICE_SCALE","code":1126} 

Verdiğim emir datası : 

board :  ETHTRY
price   : 11158.72
quantity :  0.12024069
side    : "buy"

Test etmek için price'ı  "11158" görnderdiğimde çalıştığı oluyor. Stabiliteyi sağlayamıyor sistem. Kaç gündür zarar ediyorum bu sebepten.

Bu konuda yardımınızı rica ediyorum.

**Comment by onurgozupek** [comment]
denominatorScale 2 olmasına rağmen hasFraction değeri false olduğu için sadece tamsayı fiyat girebilirsiniz. ETH/TRY işlem çiftinde fiyat 8622 8623 8624 gibi tam sayı olmalı.

hasFraction değerine dikkat edin.

**Comment by DebuggerV1** [comment]
Gerçekten ilginç şeyler görüyorum bu api kullanımında. Bu yaşadığım 3.sorun.

İlginize teşekkürler ama bunun yerine denominatorScale = 0 niye gönderilmediğini merak ediyorum.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
