### ISSUE TITLE
Websocket hatalı orderMatch mesajı gönderiyor!!!

### ISSUE THREAD

**Issue by umitk** [BTCTrader/broker-api-docs#341]
Merhaba,
Emir eşleşmesi sonrasında gelen 441(OrderMatch) mesajında doğru "amount" rakamı dönmüyor. Aşağıdaki örnekte 4800 adet limit emir göndermişim ama websocket'te 5700 adetlik işlem yapıldığı bilgisi geliyor. Sonrasında yaptığım yaptığım kontrollerde servislerden 4800 adet işlem yapıldığı bilgisi görülüyor. Ben 4800 adet emir vermeme rağmen 5700 adet'lik mesaj gelmesi ben ve birçok geliştirici için ölümcül bir hata. Lütfen acil ilgilenebilir misiniz?

Limit emir sonucu:
`{
   "httpStatusCode":200,
   "data":{
      "id":1048728402,
      "quantity":"4800.0000",
      "price":"0.2673",
      "stopPrice":"0",
      "newOrderClientId":"15566",
      "type":"buy",
      "method":"limit",
      "pairSymbol":"XRPUSDT",
      "pairSymbolNormalized":"XRP_USDT",
      "datetime":1610726704865
   },
   "success":true,
   "message":"SUCCESS",
   "code":0
}`

Websocket insert mesajı:
`[
   451,
   {
      "type":451,
      "pairId":21,
      "symbol":"XRPUSDT",
      "id":1048728402,
      "method":0,
      "userId":00000,
      "price":"0.2673",
      "amount":"4800",
      "numLeft":"4800",
      "denomLeft":"1283.2966079999999563"
   }
]`

Websocket order match mesajı:
`[
   441,
   {
      "type":441,
      "id":1048728402,
      "user":000000,
      "isBid":true,
      "method":0,
      "pair":21,
      "symbol":"XRPUSDT",
      "amount":"5700.0000000000",
      "price":"0.2673000000",
      "clientId":"15566"
   }
]`

**Comment by isos81** [comment]
@ocinbat Merhaba, bu hata ile ilgili bir gelişme var mı? Benzer sorunu ben de yaşıyorum ve ciddi olarak etkiliyor trade'imi.  Bu haliyle sisteme güvenemiyorum ve işlemlerimi durdurmak zorunda kaldım.

**Comment by ocinbat** [comment]
İnceliyoruz. 👍🏻

Sent from my iPhone

On 18 Jan 2021, at 11:39, isos81 <notifications@github.com> wrote:

﻿

@ocinbat<https://github.com/ocinbat> Merhaba, bu hata ile ilgili bir gelişme var mı? Benzer sorunu ben de yaşıyorum ve ciddi olarak etkiliyor trade'imi. Bu haliyle sisteme güvenemiyorum ve işlemlerimi durdurmak zorunda kaldım.

**Comment by aderlicrazy** [comment]
`[ 451, { "type":451, "pairId":21, "symbol":"XRPUSDT", "id":1048728402, "method":0, "userId":00000, "price":"0.2673", "amount":"4800", "numLeft":"4800", "denomLeft":"1283.2966079999999563" } ]`

Bu alış emri mi satış emri mi? Bu bilgi lazım olmuyor mu? Ya da nasıl çözüyorsunuz?

**Comment by isos81** [comment]
Merhaba @ocinbat, hala bir çözüm yok mu acaba? Sürekli açık veriyor sistemimiz.

**Comment by ocinbat** [comment]
İnceliyoruz.

Sent from my iPhone

On 26 Jan 2021, at 13:22, isos81 <notifications@github.com> wrote:

﻿

Merhaba @ocinbat<https://github.com/ocinbat>, hala bir çözüm yok mu acaba? Sürekli açık veriyor sistemimiz.

**Comment by umitk** [comment]
> `[ 451, { "type":451, "pairId":21, "symbol":"XRPUSDT", "id":1048728402, "method":0, "userId":00000, "price":"0.2673", "amount":"4800", "numLeft":"4800", "denomLeft":"1283.2966079999999563" } ]`
> 
> Bu alış emri mi satış emri mi? Bu bilgi lazım olmuyor mu? Ya da nasıl çözüyorsunuz?

Lazım olmaz mı, elbette lazım, önemli bilgi bence ama nedense gönderilmiyor. O yüzden gönderdiğim emirlerin detayını cache'de tutup daha ws isteği geldiğinde eşleştiriyorum.

**Comment by aderlicrazy** [comment]
> > `[ 451, { "type":451, "pairId":21, "symbol":"XRPUSDT", "id":1048728402, "method":0, "userId":00000, "price":"0.2673", "amount":"4800", "numLeft":"4800", "denomLeft":"1283.2966079999999563" } ]`
> > Bu alış emri mi satış emri mi? Bu bilgi lazım olmuyor mu? Ya da nasıl çözüyorsunuz?
> 
> Lazım olmaz mı, elbette lazım, önemli bilgi bence ama nedense gönderilmiyor. O yüzden gönderdiğim emirlerin detayını cache'de tutup daha ws isteği geldiğinde eşleştiriyorum.

Bunu ben de düşündüm ama bu sefer de 451 mesajında clientId gönderilmiyor. Eşleştirme yapamıyorum. Request'e cevap gelmeden websocketten bilgi gelmiş olabilir.

**Comment by ocinbat** [comment]
@aderlicrazy @umitk 451, 452, 453 mesajlarına orderType alanı eklendi. 0:BUY 1:SELL

**Comment by ocinbat** [comment]
@umitk fixlendi. OrderMatch bilgisi birden fazla emirle eşleşen emirler için gruplanıyor. 1'den fazla emrinizin de match olduğu senaryolarda bunları birleştiren hatalı bir kısım düzenlendi.
