### ISSUE TITLE
API OLUŞTURMA HATASI

### ISSUE THREAD

**Issue by ekremus** [BTCTrader/broker-api-docs#342]

**Comment by ekremus** [comment]
Kendiliğinden düzeldi

**Comment by ocinbat** [comment]
IP adresi alanına ayse yazmışsınız. Oraya api erişimi kuracağınız makinenin ip adresini yazmalısınız.

Sent from my iPhone

On 16 Jan 2021, at 21:58, ekremus <notifications@github.com> wrote:

﻿

Closed #342<https://github.com/BTCTrader/broker-api-docs/issues/342>.
