### ISSUE TITLE
Oauth V2 aktif mi?

### ISSUE THREAD

**Issue by serensoner** [BTCTrader/broker-api-docs#343]
Merhaba,

v2 api'ina authenticate ederek erismek mumkun mu?

**Comment by ocinbat** [comment]
Merhaba, henüz public erişime destek vermiyoruz v2 api için.

Sent from my iPhone

On 18 Jan 2021, at 01:04, serensoner <notifications@github.com> wrote:

﻿

Merhaba,

v2 api'ina authenticate ederek erismek mumkun mu?
