### ISSUE TITLE
Api doğru çalışmıyor

### ISSUE THREAD

**Issue by digitallartist** [BTCTrader/broker-api-docs#345]
Merhaba... Api doğru çalışmıyor...

Bağlantıyı geçerli api key ve secret ile yapsam da boş göndersem de hata almıyorum.

Cüzdan bilgisi NULL geliyor... Sipariş verdiiğimde hiç işlem yapmıyor.

Geçmiş siparişleri listele dediğimde alakasız başka bir listeyi gösteriyor.

**Comment by ocinbat** [comment]
Selamlar, detayları omer.cinbat@btctrader.com adresine mail ile iletebilir misiniz?

Kullanıcı adınız, kullandığınız apikey i ne zaman ürettiniz, geçmiş emirleri çektiğinizde alakasız veri geliyor dediğiniz veriyi de eklerseniz sevinirim.

Sent from my iPhone

On 23 Jan 2021, at 21:23, digitallartist <notifications@github.com> wrote:

﻿

Merhaba... Api doğru çalışmıyor...

Bağlantıyı geçerli api key ve secret ile yapsam da boş göndersem de hata almıyorum.

Cüzdan bilgisi NULL geliyor... Sipariş verdiiğimde hiç işlem yapmıyor.

Geçmiş siparişleri listele dediğimde alakasız başka bir listeyi gösteriyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
