### ISSUE TITLE
Yavaş gelen trade ler

### ISSUE THREAD

**Issue by UmutDP** [BTCTrader/broker-api-docs#347]
Trade sorgusu gönderdiğimde gelen tarih değerleriyle sitedeki tarih değerleri arasında 20 saniyeye yakın fark olmakta.
30 adet veriyi sürekli çekmeye çalıştığımdan olabilir diye düşündüm dökümantasyonda yazan şekilde son 5 tane veriyi çekmeye çalıştım fakat her seferinde yine 30 adet veri gelmekte. 
![issue](https://user-images.githubusercontent.com/33445932/106100648-bf03b780-614d-11eb-9f2f-209364c4c7b6.PNG)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
