### ISSUE TITLE
Bakiye sorunu

### ISSUE THREAD

**Issue by samemen** [BTCTrader/broker-api-docs#348]
Bakiyeler sürekli yanlış dönüyor  yada gecikmeli geliyor nası bi sistemdir bu?

**Comment by ninja342** [comment]
Evet ben de ayni sorunu yasiyorum kullanilabilir bakiye gec guncelleniyor. Satis emirlerim sisteme gecmiyor bu yuzden :(

**Comment by samemen** [comment]
Bi çok borsa kullanıyorum api olarak btcturk api'si kadar berbat bir sistem görmedim 2013 den beridir piyasadalar hala sorun yaşıyoruz hic geliştirme yapılmıyor.

**Comment by samemen** [comment]
Bakiyeler hesabıma yansımadıgı satışı yapamadım yukardan sanki transfer işlemi yapıyoruz  en basit bakiye güncelemekden aciz sistemleriniz. Ripple'deki ani yükseliş düşüşde zarar ettim sayenizde hakkımı helal etmiyorum.

**Comment by umitk** [comment]
Aynı sorunu ben de yaşıyorum. Cidden can sıkıcı bir durum!

**Comment by AsimCanALKAN** [comment]
Rezillik rezillik rezillik. Basit sorulara cevap veriyorlar ancak gerçek sorunları problemleri yanıtsız bırakan yetersiz bir destek söz konusu! 1 aydır responselarını çözmediler ne neden dönüyor ne bir şey ya html dönüyor ya da b'' başka bir şey yok. Bu son 1-2 haftadır da order submit ettiğimde 1 dkdan fazla yanıt dönmüyorlar ve order gitmiş oluyor yani ben ne ID ne Price alabiliyorum yanıttan.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
