### ISSUE TITLE
Excell'e API ile bakiye aktarımı sorunu

### ISSUE THREAD

**Issue by agumustekin** [BTCTrader/broker-api-docs#349]
Merhaba;

Excell'e coin fiyatlarını aktardım ve sorunsuz düzenli olarak güncelliyor.

Fakat anlık bakiyeyi bir türlü aktaramıyorum.

https://api.btcturk.com 'a Excell üzerinden API koduyla giriş yapamadım bir türlü. Bunu nasıl yapabileceğim konusunda yardımcı olur musunuz?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
