### ISSUE TITLE
PHP ile Alış/Satış Emri verirken hata alıyorum

### ISSUE THREAD

**Issue by zulfumehmet** [BTCTrader/broker-api-docs#351]
İyi günler,
Aşağıdaki yöntemle elimdeki tüm tetheri satmak istediğimde:
$post_data = "{ 'quantity' : '52.245855', 'price' : '7', 'stopPrice' : 0, newOrderClientId: 'BtcTurk API PHPClient', 'orderMethod':'limit', 'orderType':'sell', 'pairSymbol':'USDT_TRY' }";

FAILED_INVALID_QUANTITY_SCALE
hatasını alıyorum,

method olarak market seçtiğimde satış yapıyor, benim yapmak istediğim şu

örneğin ben elimdeki tüm tetheri 7.105 tl den satışa çıkartmak istiyorum price ye küsürat girdiğimde de aynı hata ile karşılaşıyorum, elimdeki tüm tetheri nasıl satarım yada TL tümüyle nasıl tether alabilrim.

**Comment by onurgozupek** [comment]
Bunu yapabilmek için önce hesaplama yapıp sonra emir iletmelisiniz.

Örneğin hesabınızdaki 100TL ile Tether almak için önce bakiyenizi alın, sonra almak istediğiniz fiyatı bu bakiyeye bölün ancak komisyonu da dikkate alın.

$amount = number_format((100 / 7.105) * (1-(18/10000)),2)

Burada;
100 = TL bakiyeniz
7.105 = Tether fiyatınız
18/10000 komisyon oranınız (hesaplamayı Piyasa Alıcı komisyonu üzerinden yaparsanız, işlemin hesaplama nedeniyle reddedilme riskini azaltmış olursunuz. Piyasa yapıcıdan hesap yapacaksanız oranı artırın. Örneğin 10/10000 yerine 11/10000 gibi)

number_format içinde 2 de https://api.btcturk.com/api/v2/server/exchangeInfo numeratorScale değeri

**Comment by zulfumehmet** [comment]
@onurgozupek teşekkürler verdiğiniz bilgi için,
$post_data = "{ 'quantity' : '".$amount."', 'price' : '7', 'stopPrice' : 0, newOrderClientId: 'BtcTurk API PHPClient', 'orderMethod':'limit', 'orderType':'sell', 'pairSymbol':'USDT_TRY' }";
Bu şekilde deneyeceğim, peki piyasa yapıcı yada piyasa alıcı işlemini nasıl yapaacağım.

**Comment by onurgozupek** [comment]
emir göndermeden önce emir defterini çekip emir defterindeki en iyi alış fiyatından düşük veya en iyi satış fiyatından yüksek emir girerseniz, o emir piyasa yapıcı olarak (daha düşük komisyonla) emir defterine eklenir.

**Comment by zulfumehmet** [comment]
@onurgozupek tamam teşekkürler, söylediklerinizi deneyeceğim, yani ben price kısmına 7.105 girebiliyorum doğru mudur? geçen btc türk danışma ekibine yazdım, bana küsüratı ve komisyon otomatik hesaplandığını söylemişlerdi.

**Comment by onurgozupek** [comment]
Arayüzde (web/mobil) otomatik hesaplanıyor ancak API tarafında hesaplamayı kullanıcının yapması gerekiyor.

Price kısmına değer girebilirsiniz. Ama önce orderbook'u çekip (veya Websocket'le bağlanıp) en iyi alış satış emirlerini kontrol ederseniz, daha doğru fiyat girebilirsiniz.

**Comment by zulfumehmet** [comment]
Evet aynen son alış satış emirlerini çekiyorum, son 10 değerin ortalamasından satış yapıyorum. Çok teşkkürler, son birşey daha soracağım izninizle, ordermethod olarak hangisini girmem lazım ve  enumi, limit, market, stoplimit bunların farkları nelerdir

**Comment by zulfumehmet** [comment]
Evet zaten son 10 işlemin değerlerini çekip ortalama değerden alış/satış gerçekleştiriyorum. 
Birde kafa takılan birşeyler var;
orderMethod da bulunan enum, limit, market ve stoplimit değerlerin ne gibifarkları vardır.

**Comment by onurgozupek** [comment]
enum değer değil değişkenin sadece yanda belirtilen değerleri alabilieceğini gösteriyor.

Emir verirken market, limit, stopLimit, stopMarket emir gönderebilirsiniz.

Ancak hangi emir tiplerinin açık olduğunu https://api.btcturk.com/api/v2/server/exchangeInfo adresinden sorgulamanızda fayda var. Örneğin BTC işlem çiftlerinde market ve stopMarket emri yok ve piyasa hareketlerine bağlı olarak kimi zaman piyasa emirleri kapatılabiliyor.

**Comment by zulfumehmet** [comment]
@onurgozupek ayrıntılı bilgilerininiz için çok teşekkür ediyorum, örneğin 100 tlmi 7.105 tl dentether alacağım, 
quantity' : 'komisyonlu alabileceğim tether adedi xx,xx şeklinde', 'price' : 'alacağım toplam tutarı mı  mı yazacağım yoksa adet fiyatınımı yani 100 tl mi yazacağım yada alış emri olan 7.105 mu yazmam lazım'

**Comment by onurgozupek** [comment]
Burada açıkladığım gibi adedi hesaplayıp almak istediğiniz adedi girmelisiniz https://github.com/BTCTrader/broker-api-docs/issues/351#issuecomment-776728616

price kısmında almak istediğiniz fiyat olmalı.

**Comment by zulfumehmet** [comment]
Almak istediğim birim fiyat yani 7.105 doğru mudur?

**Comment by onurgozupek** [comment]
Evet

**Comment by zulfumehmet** [comment]
Sabrınız ve bilgilerinizi paylaştığınız için teşekkür ediyorum, iyi çalışmalar dilerim. Bilgileri test ettikten sonra size geri dönüş sağlayacağım. Kolay gelsin.

**Comment by zulfumehmet** [comment]
@onurgozupek teşekkürler onur bey; işlemleri dediğiniz gibi gerçekleştirince sorunlarım çözüldü, iyi çalışmalar dilerim.

**Comment by onurgozupek** [comment]
Rica ederim. Kolay gelsin...
