### ISSUE TITLE
WaitingForActivation

### ISSUE THREAD

**Issue by akiplikciler** [BTCTrader/broker-api-docs#352]
API ile bakiye sorgulama, order girme gibi işlemler yapmak istiyorum. 
Ancak WaitingForActivation  mesajı dönüyor.
API key'in onaylanması nasıl saglanıyor?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
