### ISSUE TITLE
1 DKdan fazla yanıt dönmeyen sistem ve sıfır Order bilgisi

### ISSUE THREAD

**Issue by AsimCanALKAN** [BTCTrader/broker-api-docs#353]
Bakım yapıyorsunuz ancak sanırım daha çok bozuyorsunuz. Son 1 haftadır çalışan sistemimde Order gönderdiğimde ara ara 1dkdan fazla cevap dönmeyen saçma sisteminiz orderı yerleştiriyor mu yerleştirmiyor mu belli değil rezillik!!!! Buraya 3-4 tane response (HTML dönüyor, sorunun nedenini dönmüyor, boş dönüyor b'' vs vs vs yaklaşık 7-8 borsanın apisini kullanıyorum tek sorun yaşadığım sisteme siz sahipsiniz)  için konu açtım dünyanın en iyi 4.borsası(!)nın çok çalışan ekibi hiçbir şekilde yardımda veya çözümde bulunmadı ve hala bir değişiklik söz konusu yok.

**Comment by ocinbat** [comment]
Selamlar, yaşadığınız problemle ilgili detay verebilirseniz yardımcı olmaya çalışabiliriz. Hangi tarihte hangi endpointe nasıl bir request body gönderdiğinizi, response olarak aldığınız cevabı header ve body şeklinde iletebilirseniz takip edebiliriz.

Sent from my iPhone

On 13 Feb 2021, at 15:20, asimcanalkan <notifications@github.com> wrote:

﻿

Bakım yapıyorsunuz ancak sanırım daha çok bozuyorsunuz. Son 1 haftadır çalışan sistemimde Order gönderdiğimde ara ara 1dkdan fazla cevap dönmeyen saçma sisteminiz orderı yerleştiriyor mu yerleştirmiyor mu belli değil rezillik!!!! Buraya 3-4 tane response (HTML dönüyor, sorunun nedenini dönmüyor, boş dönüyor b'' vs vs vs yaklaşık 7-8 borsanın apisini kullanıyorum tek sorun yaşadığım sisteme siz sahipsiniz) için konu açtım dünyanın en iyi 4.borsası(!)nın çok çalışan ekibi hiçbir şekilde yardımda veya çözümde bulunmadı ve hala bir değişiklik söz konusu yok.

**Comment by AsimCanALKAN** [comment]
Ömer Bey merhaba,
Restart ettiğim için size header gösterme imkanım tabi ki yok. Ancak response dönmüyor zaten sisteminiz ilk durum için. İkinci durum için 5xx lü bir hata mevcut oluyor. Üçüncü durum zaten bence facia bir durum.

Order gönderdiğim için kullandığım **Endpoint**: [/api/v1/order ](#)method:POST
Yaklaşık son 1 haftadır ara ara bu durumla karşılaşıyorum. (En son 13.02.2021 20.00-20:10 arasında 5 kere aldım)

**Endpoint**: [/api/v1/order ](#)method:POST

**Durum**: Order endpointine POST request ettiğimde aslında order yerleştiriliyor ancak bana herhangi bir yanıt dönmüyor yani elimde response yok. Siz yanıt dönmediğiniz için de benim sistemim timeouta düşürüyor zaten 120 sn timeout değerine sahibim.
Zaman: Belirli bir zaman şu an kayıtlı değil ama ara ara bu durumu yaşıyorum ve sistemin dengesi şaşıyor önemli bir konu.

***********************************************************************************************************************************
Ayrıca bugün sıkça (günlük işlem oranım gayet yüksek ancak gün içinde ortalama 10 - 15 kere order gönderirken hatalar ile karşılaşıyorum.) gelmeye başlayan bir başka hata durumu: internal error responseu dönüyor.

**Enpoint**: /api/v1/order method:POST

**Response**: b'{"success":false,"message":"INTERNAL_ERROR","code":"INTERNAL_ERROR"}'

*********************************************************************************************************************

Bir diğer konu ise dönen HTML Response sorunu bunula ilgili 3 tane konu açtım herhangi bir yanıt yok.

**Durum**: Order gönderirken dönen response CloudFlare HTML kodu oluyor. 

 **Endpoint**: [/api/v1/order ](#) method:POST  

**Response**:

`**'b'<!DOCTYPEhtml>\n<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 7]> <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 8]> <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->\n<head>\n\n\n<title>api.btcturk.com | 504: Gateway time-out</title>\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />\n\n\n</head>\n<body>\n<div id="cf-wrapper">\n\n \n\n <div id="cf-error-details" class="p-0">\n <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">\n <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">\n \n <span class="cf-error-type">Error</span>\n <span class="cf-error-code">504</span>\n </h1>\n <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 6143a6e6fc8fc785 &bull;</span>\n <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-01-19 21:30:34 UTC</span>\n <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Gateway time-out</h2>\n </header>\n \n <div class="my-8 bg-gradient-gray">\n <div class="w-240 lg:w-full mx-auto">\n <div class="clearfix md:px-8">\n \n<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n <div class="relative mb-10 md:m-0">\n <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>\n <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n </div>\n <span class="md:block w-full truncate">You</span>\n <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>\n <span class="leading-1.3 text-2xl text-green-success">Working</span>\n</div>\n\n<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n <div class="relative mb-10 md:m-0">\n <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>\n <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n </div>\n <span class="md:block w-full truncate">Amsterdam</span>\n <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>\n <span class="leading-1.3 text-2xl text-green-success">Working</span>\n</div>\n\n<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n <div class="relative mb-10 md:m-0">\n <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>\n <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n </div>\n <span class="md:block w-full truncate">api.btcturk.com</span>\n <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>\n <span class="leading-1.3 text-2xl text-red-error">Error</span>\n</div>\n\n </div>\n \n </div>\n </div>\n\n <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">\n <div class="clearfix">\n <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">\n <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>\n <p>The web server reported a gateway time-out error.</p>\n </div>\n \n <div class="w-1/2 md:w-full float-left leading-relaxed">\n <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>\n <p class="mb-6">Please try again in a few minutes.</p>\n </div>\n </div>\n \n </div>\n\n <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">\n <p class="text-13">\n <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6143a6e6fc8fc785</strong></span>\n <span class="cf-footer-separator sm:hidden">&bull;</span>\n <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 45.84.190.246</span>\n <span class="cf-footer-separator sm:hidden">&bull;</span>\n <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>\n \n </p>\n</div><!-- /.error-footer -->\n\n\n \n\n\n\n\n'`
`

**Comment by ocinbat** [comment]
Cloudflareden aldığınız html cloudflare bizden cevap alamadığında size iletilen cevap. Buradaki senaryo bizim tarafta yaşanan yoğunluktan dolayı hızlı cevap dönemememiz. Response bodysini okumadan response koduna bakarak işlem yapabilirsiniz. Aldığınız internal error ler de yine bizim taraftan kaynaklı sorunlar. Çok fazla emir verdiğinizde ya da emirleriniz eşleştiğinde concurrencyi tutmadığı durumlarda size direk hata dönmek yetine işlemi içeride birkaç kere deniyoruz. Bu denemeler başarısız kalırsa internal error olarak görebileceğiniz bir hata alabilirsiniz. 2 dakika timeout değerimiz yok. Cloudflarede bu değer 60 saniye. 60 saniyeden uzun süren bir response bekleme durumunuz varsa sizin network tarafında bir sorun oluyor olabilir. Bunun dışında aldığınız timeout durumlarında işlem bizim tarafta tamamlanmış olabilir. Bunu da açık emirlerinizi çekerek kontrol edebilirsiniz.

Sent from my iPhone

On 13 Feb 2021, at 18:17, asimcanalkan <notifications@github.com> wrote:

﻿

Ömer Bey merhaba,
Order gönderdiğim için kullandığım Endpoint: /api/v1/order method:POST
Yaklaşık son 1 haftadır ara ara bu durumla karşılaşıyorum.

Endpoint: /api/v1/order method:POST

Durum: Order endpointine POST request ettiğimde aslında order yerleştiriliyor ancak bana herhangi bir yanıt dönmüyor yani elimde response yok. Siz yanıt dönmediğiniz için de benim sistemim timeouta düşürüyor zaten 120 sn timeout değerine sahibim.
Zaman: Belirli bir zaman şu an kayıtlı değil ama ara ara bu durumu yaşıyorum ve sistemin dengesi şaşıyor önemli bir konu.

________________________________

Ayrıca bugün sıkça (günlük işlem oranım gayet yüksek ancak gün içinde ortalama 10 - 15 kere order gönderirken hatalar ile karşılaşıyorum.) gelmeye başlayan bir başka hata durumu: internal error responseu dönüyor.

Enpoint: /api/v1/order method:POST

Response: b'{"success":false,"message":"INTERNAL_ERROR","code":"INTERNAL_ERROR"}'

________________________________

Bir diğer konu ise dönen HTML Response sorunu bunula ilgili 3 tane konu açtım herhangi bir yanıt yok.

Durum: Order gönderirken dönen response CloudFlare HTML kodu oluyor.

Endpoint: /api/v1/order method:POST

Response:

**'b'<!DOCTYPEhtml>\n\n\n\n <html class="no-js" lang="en-US"> \n<head>\n\n\n<title>api.btcturk.com | 504: Gateway time-out</title>\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />\n\n\n</head>\n<body>\n<div id="cf-wrapper">\n\n \n\n <div id="cf-error-details" class="p-0">\n <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">\n <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">\n \n <span class="cf-error-type">Error</span>\n <span class="cf-error-code">504</span>\n </h1>\n <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 6143a6e6fc8fc785 &bull;</span>\n <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-01-19 21:30:34 UTC</span>\n <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Gateway time-out</h2>\n </header>\n \n <div class="my-8 bg-gradient-gray">\n <div class="w-240 lg:w-full mx-auto">\n <div class="clearfix md:px-8">\n \n<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n <div class="relative mb-10 md:m-0">\n <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>\n <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n </div>\n <span class="md:block w-full truncate">You</span>\n <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>\n <span class="leading-1.3 text-2xl text-green-success">Working</span>\n</div>\n\n<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n <div class="relative mb-10 md:m-0">\n <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>\n <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n </div>\n <span class="md:block w-full truncate">Amsterdam</span>\n <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>\n <span class="leading-1.3 text-2xl text-green-success">Working</span>\n</div>\n\n<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n <div class="relative mb-10 md:m-0">\n <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>\n <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n </div>\n <span class="md:block w-full truncate">api.btcturk.com</span>\n <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>\n <span class="leading-1.3 text-2xl text-red-error">Error</span>\n</div>\n\n </div>\n \n </div>\n </div>\n\n <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">\n <div class="clearfix">\n <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">\n <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>\n <p>The web server reported a gateway time-out error.</p>\n </div>\n \n <div class="w-1/2 md:w-full float-left leading-relaxed">\n <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>\n <p class="mb-6">Please try again in a few minutes.</p>\n </div>\n </div>\n \n </div>\n\n <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">\n <p class="text-13">\n <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6143a6e6fc8fc785</strong></span>\n <span class="cf-footer-separator sm:hidden">&bull;</span>\n <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 45.84.190.246</span>\n <span class="cf-footer-separator sm:hidden">&bull;</span>\n <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>\n \n </p>\n</div>\n\n\n \n\n\n\n\n'
`

**Comment by AsimCanALKAN** [comment]
Ömer Bey açık emir nedir? Benim orderım açık emirde beklemiyor Limitte olsa Market gibi davrancak şekilde gerçekleşiyor. Ben order gönderiyorum ve order gerçekleşiyor ben nerden bilebilirim o son orderın aslında benim gönderdiğim olup olmadığını elimde ID olmadan? Ben günde 1 order göndermiyorum hızlı çalışan bir sistemim var sizin limitleriniz dahilinde, bu sorunu sizin çözmeniz lazım ben neden oluyor diye sormuyorum ben çözüm istiyorum çünkü sistemim dengesiz kalıyor ve zarar yazıyor! Siz bu cevabınızda bir çözüm görüyor musunuz? Response dönemeyen sistem neden var? Bu işi yapan kaç tane farklı borsa var hiçbirinde bunu yaşamıyorum bir tek sizde problem var. Bu mu yani o bizden haber alamıyor biz kendi içimizde sorun yaşıyoruz vs vs bana şu anda hiçbir çözüm sunamadınız ve hataları almaya devam ediyorum! Timeout 60ta da düşmüyor haberiniz olsun yani :)) Ben kendim limit koydum. Network tarafında hiçbir sorun yok. İşte timeouta düşüyor ve işlem gerçekleşiyorsa siz bana response DÖNMEK ZORUNDASINIZ böyle bir saçmalık olamaz. Ben hem açık orderlarda hangi orderdı bulamam elimde ID olmadan hem de sizin hatalı sisteminiz yüzünden sistemi mi yavaşlatamam. Lütfen çözüm üretin.

**Comment by yucelalbar** [comment]
Merhaba @ocinbat,

Açılan issue ile bağlantılı olduğu için yaşadığım problemi belirtmek istedim. API üzerinden yapmış olduğum al-sat işlemlerinde oldukça fazla timeout problemi ile karşılaşıyorum. Api üzerinden yaptığım işlem timeout'a düşerken BtcTurk'te sonradan baktığımda işlem yapılmış oluyor. Dolayısıyla, kendi uygulamamda tuttuğum wallet bilgileri ile BtcTurk'teki arasında tutarsızlık meydana geliyor. 

Kullanmakta olduğum kütüphane ccxt ve default timeout süresi 10 sn. Açıkçası, 10 sn çokmuş diye düşünürken;  60 sn'lerden bahsediyorsunuz. Hızla büyüyen ve işlemlerin hızla arttığı bir platform için bu sürelerin oldukça fazla olduğunu düşünüyorum.

**Comment by aydinhus** [comment]
Timeout olayı gerçekten çok can sıkıcı, kendi içerisinde de tutarlılığı yok. Bir kısmı gerçekleşiyor, bir kısmı drop oluyor ama geri dönen bir mesaj yok. Gelen order eğer işleme alınamıyorsa bu kadar uzun zamanda, drop edip geri dönüş yapılmalı.

**Comment by AsimCanALKAN** [comment]
@aydinhus Kesinlikle katılıyorum eğer timeout olacaksa order drop edilmeli ve böylece zaman kaybetmiş olabiliriz ama en azından saçma bir dengesizlik ortaya çıkmaz.

**Comment by aderlicrazy** [comment]
@aydinhus @AsimCanALKAN timeout olacaksa drop edilmeli diye bir şey çok mümkün değil. Bir response'un önceden timeout'a düşeceğini bilmek teknik olarak mümkün değil. Btctürk ya sistemini hızlandıracak, ya da websocketten gönderdiği 451, 452 eventlerine 441'deki gibi orderClientID'yi ekleyecek ki biz emir sunucuya gitmeden önce verdiğimiz clientID'yi takip edip timeout'u göz ardı ederek emrin durumunu takip edelim.

**Comment by AsimCanALKAN** [comment]
@aderlicrazy doğru söylüyorsunuz ancak önceden düşeceğini değil ama düştüğünü bilebilir buna göre de aksiyon alınabilir. Websocket olayı da sıkıntılı token yenileyemediğim için bir kopmada sistem dağılıyor 1. kopuşun kontrolü zor 2. tekrar token alıp sistemi yeniden başlatmak zaman kaybı. ClientID durumu güzel çözüm ama sürdürülebilir değil timeouta düştüğünde hiçbir veri dönmüyorlar yani o veri de dönmeyecek

**Comment by aydinhus** [comment]
> @aydinhus @AsimCanALKAN timeout olacaksa drop edilmeli diye bir şey çok mümkün değil. Bir response'un önceden timeout'a düşeceğini bilmek teknik olarak mümkün değil. Btctürk ya sistemini hızlandıracak, ya da websocketten gönderdiği 451, 452 eventlerine 441'deki gibi orderClientID'yi ekleyecek ki biz emir sunucuya gitmeden önce verdiğimiz clientID'yi takip edip timeout'u göz ardı ederek emrin durumunu takip edelim.

Timeout'a uğrayacağı evet belli değil ancak benim attığım mesajın timestamp'i belli, içeride bunu çok uzun zaman sonra işleme alması doğru değil, bana yine cevap dönemesin o sorun değil en azından tutarsızlık olmasın. Eğer yoğunluk ya da bir tutarsızlık varsa bekleyen eskimiş orderların drop edilmesi daha mantıklı değil mi, @ocinbat içeride bir kaç kez deniyoruz demiş mesela.

**Comment by AsimCanALKAN** [comment]
> > @aydinhus @AsimCanALKAN timeout olacaksa drop edilmeli diye bir şey çok mümkün değil. Bir response'un önceden timeout'a düşeceğini bilmek teknik olarak mümkün değil. Btctürk ya sistemini hızlandıracak, ya da websocketten gönderdiği 451, 452 eventlerine 441'deki gibi orderClientID'yi ekleyecek ki biz emir sunucuya gitmeden önce verdiğimiz clientID'yi takip edip timeout'u göz ardı ederek emrin durumunu takip edelim.
> 
> Timeout'a uğrayacağı evet belli değil ancak benim attığım mesajın timestamp'i belli, içeride bunu çok uzun zaman sonra işleme alması doğru değil, bana yine cevap dönemesin o sorun değil en azından tutarsızlık olmasın. Eğer yoğunluk ya da bir tutarsızlık varsa bekleyen eskimiş orderların drop edilmesi daha mantıklı değil mi, @ocinbat içeride bir kaç kez deniyoruz demiş mesela.

@aydinhus  katılıyorum yani timeouta düştüğü belli eğer belliyse ona göre aksiyon almak gerekli.

**Comment by ekremus** [comment]
**Bence en büyük problem bu timeout hatası.** INTERNAL_ERROR öncelikli sorun değil çünkü sorun olduğu bir şekilde bildirilmiş oluyor. Timeout'a düştüğü zaman bazen işlem gerçekleşiyor, bazen gerçekleşmiyor! Bu tutarsızlık yaşadığım en büyük problem!

**Comment by SelcukCode** [comment]
> @aydinhus @AsimCanALKAN timeout olacaksa drop edilmeli diye bir şey çok mümkün değil. Bir response'un önceden timeout'a düşeceğini bilmek teknik olarak mümkün değil. Btctürk ya sistemini hızlandıracak, ya da websocketten gönderdiği 451, 452 eventlerine 441'deki gibi orderClientID'yi ekleyecek ki biz emir sunucuya gitmeden önce verdiğimiz clientID'yi takip edip timeout'u göz ardı ederek emrin durumunu takip edelim.

Güzel öneri. Kesinlikle clientId bilgileri gerekmekte.
