### ISSUE TITLE
"INVALID_DECIMAL_PATTERN" HATASI

### ISSUE THREAD

**Issue by ekremus** [BTCTrader/broker-api-docs#354]
Merhabalar,

Order verdiğimde aşağıdaki hatayı alıyorum.
` {'data': {'Price': ['INVALID_DECIMAL_PATTERN_^\\d{0,12}(\\.\\d{1,16})?$']}, 'success': False, 'message': 'INVALID_REQUEST', 'code': 1}`

Neden olduğu hakkında bilgi sağlarsanız sevinirim. 

Teşekkürler.

**Comment by ocinbat** [comment]
Gönderdiğiniz isteği de json olarak loglayıp gönderebilir misiniz?

Sent from my iPhone

On 13 Feb 2021, at 17:01, ekremus <notifications@github.com> wrote:

﻿

Merhabalar,

Order verdiğimde aşağıdaki hatayı alıyorum.
{'data': {'Price': ['INVALID_DECIMAL_PATTERN_^\\d{0,12}(\\.\\d{1,16})?$']}, 'success': False, 'message': 'INVALID_REQUEST', 'code': 1}

Neden olduğu hakkında bilgi sağlarsanız sevinirim.

Teşekkürler.

**Comment by ekremus** [comment]
şu an için sadece "ADABTC" pair ında problem oluyor. 
price için girdiğimiz data 0.0001'den küçükse bu hatayı veriyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
