### ISSUE TITLE
BadGateway ve Sunucu Tarafında hatalar

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#355]
Son bakım çalışmasından sonra sıklıkla BadGateway hatası gelmekte. Bu sorunlar sanırım sisteminiz üzerindeki alım satım işlemlerinin yoğun olduğu zamanlarda sıklıkla gerçekleşmekte.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
