### ISSUE TITLE
User Transactions API 0 Fee Sorunu

### ISSUE THREAD

**Issue by rasitsomuncu** [BTCTrader/broker-api-docs#357]
Merhaba, 

Bazı USDT işlemlerde (BTC/USDT, ETH/USDT alım satım gibi) fee alınmış olmasına rağmen fee ve tax servisten 0 olarak geliyor. 
"/api/v1/users/transactions/trade" servisini kullanıyorum.  

İnceleyebilir misiniz? 

Teşekkürler.

**Comment by ocinbat** [comment]
Selamlar,

Hesabınıza ait e-posta adresinizi bana e-posta ile iletebilir misiniz?
omer.cinbat@btctrader.com

**Comment by rasitsomuncu** [comment]
> Selamlar,
> 
> Hesabınıza ait e-posta adresinizi bana e-posta ile iletebilir misiniz?
> [omer.cinbat@btctrader.com](mailto:omer.cinbat@btctrader.com)

Selamlar,

Konu ile ilgili örnek response ile birlikte mail ilettik size.

Teşekkürler.

**Comment by ocinbat** [comment]
Ekip inceliyor. Dönüş yapacağız. 👍🏻

Sent from my iPhone

On 22 Feb 2021, at 20:51, rasitsomuncu <notifications@github.com> wrote:

﻿

Selamlar,

Hesabınıza ait e-posta adresinizi bana e-posta ile iletebilir misiniz?
omer.cinbat@btctrader.com<mailto:omer.cinbat@btctrader.com>

Selamlar,

Konu ile ilgili örnek response ile birlikte mail ilettik size.

Teşekkürler.

**Comment by rasitsomuncu** [comment]
Merhaba bir gelişme oldu mu? @ocinbat

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
