### ISSUE TITLE
FAILED_MARKET_ORDER Hatasi

### ISSUE THREAD

**Issue by burakalakus** [BTCTrader/broker-api-docs#358]
Yogun zamanlarda alim yapmaya calistigimda bu hata kodunu alıyorum. Ama uygulamadan gidip islem yaptigimda test icin sorun yaşamıyorum. Bu hatayı nasıl handle etmek gerekiyor?

**Comment by SelcukCode** [comment]
Kullandığım workaround'u yazayım. Ben bu hatayı aldığımda arkasından yeni emir giriyorum. Bu işi 5 defa ard arda yapıp halen emir gerçekleşmediyse 1sn bekle yeniden başa dön emir vermeye devam et şeklinde ilerliyorum.
