### ISSUE TITLE
LIMIT ORDER TIMEOUT SORUNU

### ISSUE THREAD

**Issue by AsimCanALKAN** [BTCTrader/broker-api-docs#359]
API servisinizi kullanarak Limit Order gönderiyorum ancak gönderdiğim limit orderları bile sisteminize yerleştiremiyorsunuz ve timeouta düşüyor. Market order değil limit order! Ve bu kadar hızlı bir piyasada 60 sn yanıt dönmüyorsunuz ve order yerleşti mi yerleşmedi mi belli değil. Üstüne açtığım bütün konulara ya yanıt vermediniz ya da bir yanıt verip gerisini boşverdiniz. Kendi kendinizi bitiriyorsunuz. Bu kadar önemli bir konuya hala çözüm bulamadınız bulmak için uğraşıyor musunuz çok merak ediyorum gerçekten. Şu sorunu yaşadığım tek borsasınız ya ekibinizi değiştirin ya da diğer büyük borsalarla anlaşma yapın bırakın sisteminizi onlar geliştirsin :)

**Comment by samemen** [comment]
2013 de acılmış bir sistemin gecen 8 sene içinde tecrübe kazanıp günümüze geldiğinde stabile calışması gerek hiç gelişme yapılmıyor. 
En kötüsü ise emir eşleme sorunu emir veriyorsunuz emir deftere düşmüyor. Normal günlerde zaten sorun olmaz önemli olan yukseliş düşüşlerde stabile olması. Yazılım ekibini yöneten adamlar 60 yaşında felan sanırım bu kadar geri kafalı bi sistem yok.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
