### ISSUE TITLE
"code":401,"message":"Unauthorized - Invalid Public key"

### ISSUE THREAD

**Issue by akildemir** [BTCTrader/broker-api-docs#36]
merhabalar ben api bağlanmaya çalıştığımda başlıkta yazılan geçersiz key  hatasını alıyorum sürekli yardımcı olabilir misiniz? teşekkürler

  `sprintf(X_PCK,"X-PCK:%s",MY_API_KEY);
  sprintf(X_STAMP,"X-STAMP:'%ld'",(unsigned long)time(NULL));
  sprintf(X_SIGNATURE,"X-SIGNATURE:%s",SIGNATURE);

  struct curl_slist *list = NULL;

  list=curl_slist_append(list,X_PCK);
  list=curl_slist_append(list,X_STAMP);
  list=curl_slist_append(list,X_SIGNATURE);  

  req=curl_easy_init();

  if(req)
  {

    curl_easy_setopt(req,CURLOPT_URL,"https://www.btcturk.com/api/balance");

    curl_easy_setopt(req, CURLOPT_HEADER,list);

    curl_easy_setopt(req, CURLOPT_WRITEDATA, response);

    res=curl_easy_perform(req);`

**Comment by nepnesomao** [comment]
`
$nonce= time();
$headers=array(
'X-PCK: '.$APIKey,
'X-Stamp: '.$nonce,
'X-Signature: '.$signature
);
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
`
