### ISSUE TITLE
İşlemlerde yoğunluk olan çiftler (pair) için API tarafında ek bilgi verin veya durdurun

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#360]
Son zamanlarda bazı işlem çiftlerinde (örn ADA_TRY) emir yoğunluğu yüzünden API üzerinden işlem yapılamamakta ve bu işlemler daha da çok sistemi yormaktadır. 
- Emir yoğunlu İşlem çiftinde API tarafına uyarıcı bir mesaj gönderemez misiniz?
- Veya transaction miktarı birim saniye içerisinde belirli bir miktarı aşınca o emir çifti için API işlemlerini uyarın websocket verilerini durdurun
- Yukarıdakiler ya da sizin yeni fikirleriniz doğrultusunda olacak şekilde bu soruna ne zaman bir çözüm bulunması planlanmakta?

Ucuza veya pahalı token satmak istendiğinde hep elimizde kalmakta

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
