### ISSUE TITLE
Abiler çalışmıyor mu?

### ISSUE THREAD

**Issue by zulfumehmet** [BTCTrader/broker-api-docs#361]
Varlıklarım ve alış satış işlemleri abileri çalışmıyor mu, Varlıklarım apisini php de çalıştırdığımda hiçbir veri gelmiyor, günlerdir çalışan api birden bire durdu, alış ve satış işlemlerinde de aynı şekilde beyaz ekran dönüyor, güvenlik kodlarını yeniledim, ip adresini tekrardan yetki verdim ama sonuç değişmedi.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
