### ISSUE TITLE
Withdrawal yapabilirmiyim?

### ISSUE THREAD

**Issue by samemen** [BTCTrader/broker-api-docs#362]
Merhaba withdrawal yapabilirmiyim api üzeriden ?

**Comment by umitk** [comment]
Merhaba, ekip daha net bir cevap verebilir ama bildiğimiz kadarıyla yapılamıyor.

**Comment by samemen** [comment]
Cevap vericek kimse yokmu ?

**Comment by ocinbat** [comment]
Hayır, api üzerinden withdrawal yapılamıyor.
