### ISSUE TITLE
Market Alışında FAILED_INVALID_QUANTITY_SCALE Hatası

### ISSUE THREAD

**Issue by MustafaSP** [BTCTrader/broker-api-docs#363]
İyi günler.Api ile yaptığım market satışlarında herhangi bir hata almıyorum.Fakat alış işlemi yapmaya kalkıştığımda FAILED_INVALID_QUANTITY_SCALE hatası alıyorum(Program_2).Diğer issue larda önerilen adet ve değeri çarpmayı denedim(Program_1) fakat hata devam ediyor.

Yardımlarınız  için teşekkürler.

-----------------------------------------------------------------------------------
PROGRAM_1=
import time, base64, hmac, hashlib, requests, json

base = "https://api.btcturk.com"
method = "/api/v1/order"
uri = base+method

apiKey = "key1"
apiSecret = "key2"
apiSecret = base64.b64decode(apiSecret)

stamp = str(int(time.time())*1000)
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type" : "application/json"}
a=(0.015 * 13111)

print("a    "+str(a))

params={"quantity": a,"price": 13111, "newOrderClientId":"", "orderMethod":"market", "orderType":"buy", "pairSymbol":"ETH_TRY"}

result = requests.post(url=uri, headers=headers, json=params)
result = result.json()
print(json.dumps(result, indent=2))

ÇIKTI_1 =

a    196.665
{
  "httpStatusCode": 400,
  "data": null,
  "success": false,
  "message": "FAILED_INVALID_QUANTITY_SCALE",
  "code": 1127
}

-----------------------------------------------------------------------------------

PROGRAM_2 =

import time, base64, hmac, hashlib, requests, json

base = "https://api.btcturk.com"
method = "/api/v1/order"
uri = base+method

apiKey = "key_1"
apiSecret = "key_2"
apiSecret = base64.b64decode(apiSecret)

stamp = str(int(time.time())*1000)
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type" : "application/json"}

params={"quantity": 0.015,"price": 13111, "newOrderClientId":"", "orderMethod":"market", "orderType":"buy", "pairSymbol":"ETH_TRY"}

result = requests.post(url=uri, headers=headers, json=params)
result = result.json()
print(json.dumps(result, indent=2))

ÇIKTI_2 =

{
  "httpStatusCode": 400,
  "data": null,
  "success": false,
  "message": "FAILED_INVALID_QUANTITY_SCALE",
  "code": 1127
}

**Comment by mertakozcan** [comment]
Sorunun sebebi burada açıklanmış: https://github.com/outlier-1/btcturkapi-python/issues/15#issuecomment-730660529

Her zamanki BTCTürk saçmalıklarından bir tanesi daha. Market buy emri girmek istediğinizde gönderdiğiniz değeri quantity değil price olarak alıyor. Hatta web arayüzünden bakarsanız emir tipini piyasa seçince buy tarafında çıkan kutucuk quantity değil price bekliyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
