### ISSUE TITLE
Scale Problemleri

### ISSUE THREAD

**Issue by MustafaSP** [BTCTrader/broker-api-docs#364]
İyi günler,

Market satışlarında adeti doğrudan girmemiz problem oluşturmuyorken market alışlarında adet ile miktarı çarpmamız daha sonra hasfraction değerini de kontrol edip False ise sayıyı yuvarlamamız  eğer True olursa diğer işleme geçmemiz gerekiyor . Bu sefer nedense numeratorScale değeri değil de denominatorScale değerine uygun olarak basamakları formatlamanız gerekiyor.

Bunca öngörülemez durum doğru hesap yapmayı gerçekten güçleştirmekte . Örneğin kur 13110 iken siz 0.015 ETH_TRY almak isterseniz önce 13110*0.015 ile çarpmalı daha sonra hasfraction=False olduğundan çıkan 196.65 değerini 196 veya 197 'ye yuvarlamamız gerekiyor . Bu da kuracağımız sistemin miktarı düşürmesine veya arttırmasına neden olarak sistemin kararsızlaşmasına neden oluyor.

Çözüm olarak : basitçe market alışlarında da saf miktarın girilmesi metodunun kullanılması gerek geliştirici yükünü gerek işlem sayısının azaltılması gerekse server yükünün azaltılması açısından çok daha kullanışlı olacaktır.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
