### ISSUE TITLE
Token is unauthorized to do this action Sorunu

### ISSUE THREAD

**Issue by fatihkutuk** [BTCTrader/broker-api-docs#365]
Son Transaction veye Son trade işlemlerini görmek istediğimde bu hatayı alıyorum. Yardımcı olursanız sevinirim

Token is unauthorized to do this action: [GET] /api/v1/users/transactions/trade?type=buy&type=sell&symbol=try&symbol=xrp&startDate=1577836800000&endDate=1609459200000. Please check your bearer token in request header.

Kod:
                var configuration = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();

                var publicKey = configuration["publicKey"];
                var privateKey = configuration["privateKey"];
                var resourceUrl = configuration["resourceUrl"];
                var apiClientV1 = new ApiClientV1(publicKey, privateKey, resourceUrl);

                var startdate = new DateTime(2020, 10, 11);
                var endatet = new DateTime(2022, 11, 11);
                var userTrades = apiClientV1.GetUserTrades(new[] { "buy", "sell" }, new[] { "try", "xrp" }, startdate.ToUnixTime(), endatet.ToUnixTime());

                if (userTrades.Result.Success)
                {
                    foreach (var userTrade in userTrades.Result.Data)
                    {
                        Console.WriteLine(userTrade.Price);
                    }
                }

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
