### ISSUE TITLE
Orderbook sorunu 

### ISSUE THREAD

**Issue by samemen** [BTCTrader/broker-api-docs#366]
Ara ara  bu hatayı almaya başladım orderbook çekerken. Çok fazla istekde göndermiyorum bugun sorun olmaya başladı.
{ "success": false, "message": "Too many requests", "code": 429 }

**Comment by ocinbat** [comment]
Rate limitlerimize takılıyorsunuz. Bu hatayı aldığınızde dönen x-retry-after headerına göre işlem yapmaya devam edebilirsiniz.

Sent from my iPhone

On 21 Mar 2021, at 23:26, samemen ***@***.***> wrote:

﻿

Ara ara bu hatayı almaya başladım orderbook çekerken.
{ "success": false, "message": "Too many requests", "code": 429 }

**Comment by samemen** [comment]
50 adet proxy var elimde hepsinde aynı sonuc dönüyor. Düne kadar sorun yokdu dün akşamdam beri sürekli rate limite takılmış tüm ip adreslerim?

**Comment by samemen** [comment]
HTTP/1.1 429 Too Many Requests
Date: Mon, 22 Mar 2021 12:01:04 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Retry-After: 49
Cache-Control: no-cache
cf-request-id: 08fb6870f400004a671fa0b000000001
Set-Cookie: __cfduid=ddf468df467a07908c5f86ea2530708891616414464; expires=Wed, 21-Apr-21 12:01:04 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 633f436188bc4a67-FRA
