### ISSUE TITLE
Browser'da cors'a takilmak

### ISSUE THREAD

**Issue by nerkn** [BTCTrader/broker-api-docs#367]
yaptigim bir sayfada, browser da fetch ile o andaki kuru almak istiyorum
fetch('https://api.btcturk.com/api/v2/server/exchangeinfo',{ }).then(r=>r.text()).then(d=>console.log(d))

bu sekilde kullandigimda
`Access to fetch at 'https://api.btcturk.com/api/v2/server/exchangeinfo' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
?page_id=6&preview=true:118 GET https://api.btcturk.com/api/v2/server/exchangeinfo net::ERR_FAILED`
cors hatasi aliyorum.

no-cors seklinde gonderdigimde 
`fetch('https://api.btcturk.com/api/v2/server/exchangeinfo',{ mode: 'no-cors' }).then(r=>r.text()).then(d=>console.log(d))`
hic data gelmiyor, sanirim server preflight yapiyor.

su an kendi serverimden relay yaparak cozecegim ama browser'dan fetch ile nasil data alinabilecegini yardim dosyalarina ekleyebilir misiniz?

**Comment by ocinbat** [comment]
Selamlar,

Bu takıldığınız durum bizim bilinçli bir şekilde kurguladığımız bir senaryo.
Herhangi bir 3rd party firmanın bizim API'larımızı kendi önyüzlerine koyarak bize www.btcturk.com ya da pro.btcturk.com domainleri dışında sayfalardan istek atmasını engelliyoruz. Bu kullanıcılarımızın güvenliğini sağlamak için aldığımız bir önlem. 

CORS hakkında daha fazla bilgi için https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
