### ISSUE TITLE
Api V1 Windows Forms ile çalışmıyor

### ISSUE THREAD

**Issue by ekutuker** [BTCTrader/broker-api-docs#369]
Merhaba C# apisini kullanıyorum anlık olarak Console uygulaması ile çok rahat bir şekilde işlemlerimi gerçekleştirebiliyorum ancak maalesef Api V1 i Windows Forms tabanlı bir projeye attığımda ve çalıştırdığımda Form gözükmüyor. Bunu nasıl çözebilirim????

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
