### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by oxanero** [BTCTrader/broker-api-docs#37]
Selam ,

Python da aldıgım hata aşaıdaki gibidir nerede hata yapıyorum acaba yardım alabilrimiyim?
**Hata:**
self.inner.update(msg)
TypeError: Unicode-objects must be encoded before hashing>
**Satır**
< lv_signature = hmac.new(base64.b64decode(self.private_key), data, hashlib.sha256)>

**Kod Örneğim**
def authSignature(self):
unixTime = int(time.time())
data = str(self.api_key + str(unixTime))
lv_signature = hmac.new(base64.b64decode(self.private_key), data, hashlib.sha256)
signature = base64.b64encode(lv_signature.digest().encode('base64')[:-1])
return signature

Burayı aşamadığımdan ilerleyemiyorum :( yardımlarınızı rica ederim.

**Comment by nanonettr** [comment]
Selamlar,
Çalışan Python kod örneği;
```
dig = hmac.new(base64.b64decode("<PRIVATE_KEY>"), str("<API_KEY>"+"<TIME_STAMP>").encode("utf-8"), hashlib.sha256).digest()
signature = base64.b64encode(dig).decode()
```

**Comment by suleymanbyzt** [comment]
Merhaba,

Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
