### ISSUE TITLE
api authentication url bilgisi

### ISSUE THREAD

**Issue by ozbeyahmet90** [BTCTrader/broker-api-docs#370]
Order oluşturma işlemleri aşamasında hata almaktayım. Defalarca destek kaydı oluşturmama rağmen herhangi bir yanıt alamadım. V2 api üzerinden denemek istedim.  Bu seferde authentication url bilgisini hiç bir dokümanda bulamadım. Normal url i denedim fakat o da bir çözüm olmadı. Farklı bir sağlayıcıya geçmek istemiyorum. Bu konuda desteğinizi rica ederim.

Kolay gelsin.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
