### ISSUE TITLE
FAILED_ORDER_WITH_OPEN_ORDERS

### ISSUE THREAD

**Issue by angebot84** [BTCTrader/broker-api-docs#371]
Api den çok sıklıkla aldıgım bir response code u bu. Aslında bir çok emir de bu hatayı veriyor ama UNI_TRY de market order verebilirken, limit order veririken FAILED_ORDER_WITH_OPEN_ORDERS response u dönüyor (Bu sorun limit orderların nerdeyse bir çogunda var örnek olarak UNI_TRY pairini seçtim)

Gönderdigim parametreler:

**params={
"quantity": 250,
"price": 283,
"stopPrice": 0, 
"newOrderClientId":"BtcTurk Python API Test",
 "orderMethod":"LIMIT", 
"orderType":"buy", 
"pairSymbol":"UNI_TRY"
}**

Gelen respoınse aşagıdaki gibi dir:
{'httpStatusCode': 400,
 'data': None,
 'success': False,
 'message': 'FAILED_ORDER_WITH_OPEN_ORDERS',
 'code': 1122}

Exchange info daki bütün kurallara uyuyor gibi görünyor ama bu hatayı alıyorum, bunun sebebi nedir acaba?

**Comment by ocinbat** [comment]
Dönen hata işlemi yapmaya bakiyeniz olmadığını ve bu işlem çiftinden açık başka emriniz olduğunu söylüyor.

Sent from my iPhone

On 13 Apr 2021, at 11:35, angebot84 ***@***.***> wrote:

﻿

Api den çok sıklıkla aldıgım bir response code u bu. Aslında bir çok emir de bu hatayı veriyor ama UNI_TRY de market order verebilirken, limit order veririken FAILED_ORDER_WITH_OPEN_ORDERS response u dönüyor (Bu sorun limit orderların nerdeyse bir çogunda var örnek olarak UNI_TRY pairini seçtim)

Gönderdigim parametreler:

params={
"quantity": 250,
"price": 283,
"stopPrice": 0,
"newOrderClientId":"BtcTurk Python API Test",
"orderMethod":"LIMIT",
"orderType":"buy",
"pairSymbol":"UNI_TRY"
}

Gelen respoınse aşagıdaki gibi dir:
{'httpStatusCode': 400,
'data': None,
'success': False,
'message': 'FAILED_ORDER_WITH_OPEN_ORDERS',
'code': 1122}

Exchange info daki bütün kurallara uyuyor gibi görünyor ama bu hatayı alıyorum, bunun sebebi nedir acaba?

**Comment by angebot84** [comment]
Hic bir acik emrim yok, bu emri gercekkestirecek para fazlasiyla var ve bosta duruyor. Eger bu dediginiz dogru olsaydi market order gerceklesmezdi. Ayni emri market olarak verince cok guzel bir sekilde gerceklesiyor. Ancak limit order gerceklesmiyor.

**Comment by rasitsomuncu** [comment]
Selamlar, ben de sürekli aynı hatayı alıyorum ve üstteki arkadaşın bahsettiği gibi açık emir de yok bakiye de yeterli. Limit order için alıyorum ben de hatayı.

**Comment by canerd7u** [comment]
Merhaba,

Bende sürekli bu hatayı alıyorum. Sistemdeki tüm işlemleri loglamak zorunda kaldım bu hata yüzünden. En son ulaştığım sonuç Market emri girmişim bu hatayı almış ama Market emrimde gerçekleşmiş. Sisteminiz hem FAILED_ORDER_WITH_OPEN_ORDERS hatası veriyor hemde orderi giriyor. Kararlı bir yapıda çalışmıyor.

**Comment by emreacar** [comment]
Aynı Hata.... Hem v1 hem v2 endpoint için denedim sonuç değişmedi. 

```
Request {
  "newOrderClientId":"BTCTrader",
  "quantity":"2.24",
  "price":"86.04",
  "stopPrice":"85.95",
  "orderMethod":"stoplimit",
  "orderType":"buy",
  "pairSymbol":"EOSTRY"
}

Response {
  httpStatusCode: 400,
  data: null,
  success: false,
  message: 'FAILED_ORDER_WITH_OPEN_ORDERS',
  code: 1122
}
```

**Comment by mertakozcan** [comment]
Ben de aynı hatayı market sell emrinde alıyorum. Kullanılabilir bakiye kontrolü yaptıktan sonra emir girdiğim için bakiye sorunu olmaması gerekiyor. Son 1 haftaya kadar hiç böyle bir sorunla karşılaşmamıştım.

> Dönen hata işlemi yapmaya bakiyeniz olmadığını ve bu işlem çiftinden açık başka emriniz olduğunu söylüyor.

@ocinbat: Burada kural tam olarak nedir açıklık getirir misiniz? Kullanılabilir bakiye olduğu sürece açık emir olup olmaması bir şeyi etkiliyor mu?

**Comment by ocinbat** [comment]
@mertakozcan kural çok basit genel olarak. Emir girerken bakiyenizden düşeceğimiz tutar, toplam kullanılabilir bakiyenizden daha az olmalı. Toplam kullanılabilir bakiyeniz de toplam bakiyenizden açık emirlerinizin toplamı çıkartılarak bulunuyor. Bu tarz bir hatanın sebebi girilen emrin toplamının kullanılabilir bakiyenizden az olması olabilir ya da cüzdanınızda bir sorun olmuş olabilir. Müşteri hizmetlerine ulaşırsanız bakiyenizde bir sorun olup olmadığını kontrol edebilirler.

**Comment by mertakozcan** [comment]
@ocinbat https://docs.btcturk.com/#account-balance Buradan dönen response'ta `free` olarak belirtilen değeri kullanıyorum, dolayısıyla normal şartlarda bir sorun olmaması lazım. Yukarıdaki soruyu sormamın sebebi şu: bazı borsalar default olarak kullanılabilir bakiye olsa bile açık emir olduğu sürece yeni emir girmeye izin vermiyor. BTCTurk de mi böyle bir sisteme geçti diye şüphelendim.

**Comment by emreacar** [comment]
@mertakozcan şüphelerin hiç yersiz değil bence. Sistem stabil çalışmıyor bu apaçık ortada. Ben aynı problemi BTCTurk'ün web arayüzü üzerinden de yaparken zaman zaman bakiye hatası aldığım oluyor.

**Comment by rasitsomuncu** [comment]
Merhaba, ben bu sorunu satış miktarında da fee kadar düşerek çözdüm gibi. Yani 0.01 BTC'niz var, 0.01 BTC satacaksınız normalde izin vermesi gerekiyor, sonuçta fee'yi satış sonrasında ele geçen paradan düşüyor ama sistem nedense izin vermiyor gibi buna. Aşağıdaki gibi deneyebilirsiniz, umarım çözülür sizin de @emreacar @mertakozcan 

sell_order_amount = coin_balance / (1 + YOUR_FEE)

**Comment by mertakozcan** [comment]
@rasitsomuncu Buy yaparken dediğiniz hesaplamayı yapmak zorundayız ama sell yaparken hiçbir borsada böyle bir şeye ihtiyacım olmadı. Websitesini çok kullanmıyorum ama orada da böyle bir kısıtlama yok diye biliyorum. Eğer sebep gerçekten buysa API hatalı demektir, bunu çözmeleri gerekiyor.

**Comment by rasitsomuncu** [comment]
@mertakozcan Evet ben de diğer borsalarda hata almamama rağmen BtcTurk'te hata alıyordum sürekli. Bir de işin saçma tarafı, satış yaptıktan sonra o düştüğüm minik fee miktarı kalıyor wallet'ta, anlamsız bir kontrol olmuş oluyor. Umarım inceleyip çözerler.

**Comment by SelcukCode** [comment]
WebSocket'ten 441 UserOrderMatch verisini görür görmez yeni bir emir verdiğimde yaşıyorum ben de. Eğer 441 mesajını gör 150ms bekle ve emir ver dersem bir sorun çıkarmıyor.

"api/v1/users/transactions/trade?orderId={orderId}" ile kontrol ettiğim zaman sıkıntı yoktu. Çünkü zaten 150ms'den fazla zaman geçmiş oluyordu :) WebSocket ile sonuçlara daha hızlı erişebiliyorum ancak bu sefer de yeni emri gecikmeli vermek ironik oldu :(

@mhelvacikoylu Bey, bir yorum yapabilir misiniz?
