### ISSUE TITLE
FAILED_ORDER_WITH_OPEN_ORDERS hatası

### ISSUE THREAD

**Issue by canerd7u** [BTCTrader/broker-api-docs#372]
Merhaba,

Bende sürekli FAILED_ORDER_WITH_OPEN_ORDERS  hatası alıyorum. Sistemdeki tüm işlemleri loglamak zorunda kaldım bu hata yüzünden. En son ulaştığım sonuç Market emri girmişim bu hatayı almış ama Market emrimde gerçekleşmiş. Sisteminiz hem FAILED_ORDER_WITH_OPEN_ORDERS hatası veriyor hemde orderi giriyor. Kararlı bir yapıda çalışmıyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
