### ISSUE TITLE
PRICE_MUST_BE_LESS_THAN_MAXPRICE

### ISSUE THREAD

**Issue by ekremus** [BTCTrader/broker-api-docs#373]
Dün gece 30 kere aldığım hata. Nedeni nedir acaba? Normalde sorunsuz işlem yapıyorum fakat,

```
PAIR: MKRUSDT 
BUY | fiyat:3600.1 miktar:0.0259
BUY | fiyat:3600.1 miktar:0.0169
BUY | fiyat:3600.1 miktar:0.0187
BUY | fiyat:3600.1 miktar:0.1377
```

bu işlemler hata vermiş.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
