### ISSUE TITLE
Php de api sayfası boş dönüyor

### ISSUE THREAD

**Issue by zulfumehmet** [BTCTrader/broker-api-docs#374]
Php ile api çalıştırıyordum ama, bugün apiden hiç bir dönüş alamıyorum, hata kodu da vermiyor, api sistemde bir güncelleme mi mevcut, dün akşam çalışan api bugün çalışmıyor, public api ler çalışyıor ama private apiler (varlık bilgisi, satış emirleri gibi) hiç bir cevap vermiyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
