### ISSUE TITLE
Response [405] Hatasi

### ISSUE THREAD

**Issue by sgor84** [BTCTrader/broker-api-docs#375]
Merhaba,

Python da Al/Sat Emri göndermek istediğimde <Response [405]> hatası ile karşılayorum. Kullandığım kod aşağıda ki gibidir. 'pairSymbol': 'UNIUSDT' olarakta denedim ama hata çıktısı <Response [405]>.

apiKey ve apiSecret ile bakiye ve iş emirlerini sorguladım ve olumlu <Response [200]> çıktısı aldım.  Hesabımda kullanabilir ve satılabilir 6.63 UNI mevcut.

Sorunun kaynağı ile ilgili ya da UNIUSDT örnekli kod paylaşabilir misiniz? 

Kullandığım Örnek Kod:
----------------------------------------------------------------------------
import time, base64, hmac, hashlib, requests, json

base = "https://api.btcturk.com"
method = "/api/v1/order"
uri = base+method

apiKey = "YOUR_API_PUBLIC_KEY"
apiSecret = "YOUR_API_SECRET"
apiSecret = base64.b64decode(apiSecret)

stamp = str(int(time.time())*1000)
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type" : "application/json"}

params={'quantity': 5.24, 'price': 45.123, 'stopPrice': 0, 'newOrderClientId': 'BtcTurk Python API Test', 'orderMethod': 'LIMIT', 'orderType': 'buy', 'pairSymbol': 'UNI_USDT'}

result = requests.post(url=uri, headers=headers, json=params)
result = result.json()
print(json.dumps(result, indent=2))

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
