### ISSUE TITLE
Komisyon Bilgileri

### ISSUE THREAD

**Issue by mstfimi** [BTCTrader/broker-api-docs#376]
Merhaba, API aracılığıyla komisyon bilgilerimizi öğrenebileceğimiz private bir method var mıdır? Yoksa eklemeyi düşünüyor musunuz? Api üzerinden alış-satış işlemleri sonrası komisyon tutarları da düştükten sonraki miktarları hesaplamak için bu bilgiye ihtiyaç var. Toplam hacim bilgimizin olduğu bir method varsa o da olur. Oradan da komisyon yüzdelerine geçebiliriz ama tabii değişme ihtimaline karşı api'den direkt olarak komisyon miktarınız % şu kadar diye bir dönüş alabilirsek kullanışlı olacaktır.

@ocinbat hocam sanırım siz ilgileniyorsunuz. Bu konudaki yorumunuzu bekliyorum. İyi çalışmalar.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
