### ISSUE TITLE
Market Emirlerinde FAILED_MIN_TOTAL_AMOUNT Hatası hk.

### ISSUE THREAD

**Issue by emreacar** [BTCTrader/broker-api-docs#377]
Merhaba;

```
data: '{
     "newOrderClientId":"BTCTrader",
     "quantity":"1.82",
     "price":"93.07",
     "orderMethod":"market",
     "orderType":"buy",
     "pairSymbol":"EOSTRY"
}'
```

Yukarıda ki isteği ilettiğimde hesabımdaki kullanılabilir bakiye 170.43 TL

93.07 Piyasa fiyatından alım yapmak istediğimde response olarak FAILED_MIN_TOTAL_AMOUNT hatası alıyorum. 

Request'imde bulunan değerleri BTC arayüzü üzerinden limit emir olarak hesapladığımda 169.69TL bakiye harcanacağı hakkında bilgiyi görebiliyor ve emri verebiliyorum. Ancak API üzerinden verdiğimde hat alıyorum.

Dokümanlarınzıda FAILED_MIN_TOTAL_AMOUNT ile ilgili bir bilgi yok bunun yerine MIN_TOTAL ile ilgili bir açıklama var ama konuyla alakası olduğunu düşünmüyorum zira bakiyem minimum bakiyenin üzerinde.

**Comment by SelcukCode** [comment]
Market emirlerinde "price" kullanmayın, "quantity" kısmına ise sizin örneğiniz için 169.69 girin çalışacaktır.
