### ISSUE TITLE
server time boş html sayfa dönüyor

### ISSUE THREAD

**Issue by emrahtopcu** [BTCTrader/broker-api-docs#379]
sunucudan time bilgisi alamadığım için sync olamıyorum ve private endpointlerde sürekli unauthorized alıyorum.

https://api.btcturk.com/api/v2/server/time
response:
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-play-app" content="app-id=com.btcturk.pro">
    <meta name="apple-itunes-app" content="app-id=1471639720">
    <meta name="google-site-verification" content="tPiqb-MbuiDeormeAL5Z9TS-5UL11ePThlzPJTpCzgA" />
    <meta name="description" content="BtcTurk PRO ile profesyonelce Bitcoin ve kriptopara alın ve satın.">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <link rel="alternate" hreflang="tr" href="https://pro.btcturk.com">
    <link rel="alternate" hreflang="en" href="https://pro.btcturk.com/en">
    <script src="/assets/datafeeds/udf/dist/polyfills.js?v=9.1" type="text/javascript"></script>
    <script src="/assets/datafeeds/udf/dist/bundle.js?v=9.2" type="text/javascript"></script>
    <script src="/assets/nr.js?v=1.0.0" type="text/javascript"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-807541059"></script>
    <script src="/assets/gtag.js?v=1.0.0" type="text/javascript"></script>
    <script src="/assets/gtm.js?v=1.0.0" type="text/javascript"></script>
<link rel="stylesheet" href="styles.d7bc198f22778d225b1d.css"><script async src='/cdn-cgi/bm/cv/669835187/api.js'></script></head>
<body class="dark-mode">
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-54L33R8" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script src="/assets/site.js?v=9.4" type="text/javascript"></script>
    <app-root></app-root>
<script type="text/javascript" src="runtime.5910468e2e8512b36fe6.js"></script><script type="text/javascript" src="polyfills.10dec8137620bd536f80.js"></script><script type="text/javascript" src="scripts.59e847974dfa927ca719.js"></script><script type="text/javascript" src="vendor.f2c4d29d47b140063c0a.js"></script><script type="text/javascript" src="main.0447af2483f69351802a.js"></script><script type="text/javascript">(function(){window['__CF$cv$params']={r:'654d654c7ca8fd11',m:'d6b37dd8181a8ed657c4e4a000f866a017ac6c1e-1621931363-1800-AUfoHm2mkq476l+iuhAEKq5C6z7mzvdZW7My5qF1VojAfReuc5bRQjNXhkSel7faokaxFc4MsNj0Tg26s4BXc+1tmt/GPEY4UX0OF6eipN6mW3/3xtJ/lYbR96Sz3HlizF2sQdWTrc7rWit/QvmLiCDeClwAGzMAMHElQDs/mliq',s:[0x26c8222176,0xf5a148f96e],}})();</script></body>
</html>

**Comment by ocinbat** [comment]
Selamlar,

curl -v https://api.btcturk.com/api/v2/server/time çıktısını gönderebilir misiniz?

**Comment by emrahtopcu** [comment]
Selam, 'curl -v' nedir ?

**Comment by emrahtopcu** [comment]
Ömer bey, uygulama geliştirdiğim ortam .net c#.  Uygulamamda HttpClient ve HttpRequestMessage nesnelerini async kullanıyorum. uygulamamdan sürekli aynı html cevabı alıyorum. server/time için dökümanlarda herhangi bir ratelimit görmediğim için her 1000 milisaniyede bir istek gönderiyorum. Postman ile bu endpoint i denediğimde zaman zaman json zaman bilgisini alabiliyorum ancak genelde aynı html dönüyor. Herhangi bir browser dan denediğimde çoğunlukla json zaman bilgisi geliyor.

Umarım bu bilgiler yardımcı olur.

**Comment by emrahtopcu** [comment]
curl çıktısı:

*   Trying 104.20.166.102...
* TCP_NODELAY set
* Connected to api.btcturk.com (104.20.166.102) port 443 (#0)
* schannel: SSL/TLS connection with api.btcturk.com port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 186 bytes...
* schannel: sent initial handshake data: sent 186 bytes
* schannel: SSL/TLS connection with api.btcturk.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with api.btcturk.com port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 16
* schannel: encrypted data buffer: offset 16 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with api.btcturk.com port 443 (step 2/3)
* schannel: encrypted data got 2088
* schannel: encrypted data buffer: offset 2104 length 4096
* schannel: sending next handshake data: sending 93 bytes...
* schannel: SSL/TLS connection with api.btcturk.com port 443 (step 2/3)
* schannel: encrypted data got 258
* schannel: encrypted data buffer: offset 258 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with api.btcturk.com port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /api/v2/server/time HTTP/1.1
> Host: api.btcturk.com
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 7239
* schannel: encrypted data buffer: offset 7239 length 103424
* schannel: decrypted data length: 1369
* schannel: decrypted data added: 1369
* schannel: decrypted data cached: offset 1369 length 102400
* schannel: encrypted data length: 5841
* schannel: encrypted data cached: offset 5841 length 103424
* schannel: decrypted data length: 1369
* schannel: decrypted data added: 1369
* schannel: decrypted data cached: offset 2738 length 102400
* schannel: encrypted data length: 4443
* schannel: encrypted data cached: offset 4443 length 103424
* schannel: decrypted data length: 1369
* schannel: decrypted data added: 1369
* schannel: decrypted data cached: offset 4107 length 102400
* schannel: encrypted data length: 3045
* schannel: encrypted data cached: offset 3045 length 103424
* schannel: decrypted data length: 1369
* schannel: decrypted data added: 1369
* schannel: decrypted data cached: offset 5476 length 102400
* schannel: encrypted data length: 1647
* schannel: encrypted data cached: offset 1647 length 103424
* schannel: decrypted data length: 1369
* schannel: decrypted data added: 1369
* schannel: decrypted data cached: offset 6845 length 102400
* schannel: encrypted data length: 249
* schannel: encrypted data cached: offset 249 length 103424
* schannel: decrypted data length: 186
* schannel: decrypted data added: 186
* schannel: decrypted data cached: offset 7031 length 102400
* schannel: encrypted data length: 34
* schannel: encrypted data cached: offset 34 length 103424
* schannel: decrypted data length: 5
* schannel: decrypted data added: 5
* schannel: decrypted data cached: offset 7036 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 7036 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 7036
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 200 OK
< Date: Tue, 25 May 2021 14:27:50 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< Last-Modified: Tue, 25 May 2021 07:29:41 GMT
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Strict-Transport-Security: max-age=15768000; includeSubdomains; preload
< Referrer-Policy: no-referrer-when-downgrade
< Content-Security-Policy: default-src 'self' https://*.zdassets.com https://btcturkpro.zendesk.com wss://btcturkpro.zendesk.com wss://*.zopim.com; base-uri 'self'; script-src 'self' *.zoho.com *.zohopublic.com *.zohostatic.com *.zohocdn.com *.zohostatic.eu https://*.zdassets.com https://btcturkpro.zendesk.com wss://btcturkpro.zendesk.com wss://*.zopim.com 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://connect.facebook.net https://www.google-analytics.com https://js-agent.newrelic.com https://bam.eu01.nr-data.net https://tagmanager.google.com https://dyjgaef5vuq51.cloudfront.net https://dtzpfzv31buvf.cloudfront.net https://www.googleadservices.com https://*.doubleclick.net https://hcaptcha.com https://*.hcaptcha.com; ; img-src 'self' *.zoho.com *.zohopublic.com *.zohostatic.com *.zohocdn.com *.zohostatic.eu https://*.zdassets.com https://btcturkpro.zendesk.com https://btcturk.zendesk.com wss://btcturkpro.zendesk.com wss://*.zopim.com data: https://*.btcturk.com https://www.google-analytics.com https://www.facebook.com https://*.doubleclick.net https://ssl.gstatic.com https://www.gstatic.com https://dyjgaef5vuq51.cloudfront.net https://dtzpfzv31buvf.cloudfront.net https://v2assets.zopim.io https://*.zdusercontent.com https://www.google.com https://www.google.com.tr data:; style-src 'self' *.zoho.com *.zohopublic.com *.zohostatic.com *.zohocdn.com *.zohostatic.eu https://*.zdassets.com https://btcturkpro.zendesk.com wss://btcturkpro.zendesk.com wss://*.zopim.com 'unsafe-inline' https://fonts.googleapis.com https://tagmanager.google.com https://fonts.googleapis.com https://dyjgaef5vuq51.cloudfront.net https://dtzpfzv31buvf.cloudfront.net https://hcaptcha.com https://*.hcaptcha.com; font-src 'self' *.zoho.com *.zohopublic.com *.zohostatic.com *.zohocdn.com *.zohostatic.eu https://*.zdassets.com https://btcturkpro.zendesk.com wss://btcturkpro.zendesk.com wss://*.zopim.com data: https://fonts.gstatic.com https://dyjgaef5vuq51.cloudfront.net https://dtzpfzv31buvf.cloudfront.net; frame-src 'self' *.zoho.com *.zohopublic.com *.zohostatic.com *.zohocdn.com *.zohostatic.eu https://*.zdassets.com https://btcturkpro.zendesk.com wss://btcturkpro.zendesk.com wss://*.zopim.com https://btctrader.lon.netverify.com https://*.amani.ai https://*.btcturk.com https://dyjgaef5vuq51.cloudfront.net https://dtzpfzv31buvf.cloudfront.net https://*.doubleclick.net https://hcaptcha.com https://*.hcaptcha.com; frame-ancestors 'self'; form-action https://*.btcturk.com; connect-src 'self' *.zoho.com *.zohopublic.com *.zohostatic.com *.zohocdn.com *.zohostatic.eu https://*.zdassets.com https://btcturkpro.zendesk.com wss://btcturkpro.zendesk.com wss://*.zopim.com https://*.btcturk.com wss://*.btctrader.com wss://*.btcturk.com wss://*.zohopublic.com https://bam.eu01.nr-data.net https://www.google-analytics.com https://*.zopim.com https://hcaptcha.com https://*.hcaptcha.com ; media-src 'self' *.zoho.com *.zohopublic.com *.zohostatic.com *.zohocdn.com *.zohostatic.eu https://*.zdassets.com https://btcturkpro.zendesk.com wss://btcturkpro.zendesk.com wss://*.zopim.com https://dyjgaef5vuq51.cloudfront.net https://dtzpfzv31buvf.cloudfront.net; object-src 'none';
< Feature-Policy: accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; battery 'none'; camera 'self' https://btctrader.lon.netverify.com https://client.amani.ai https://tr3.amani.ai; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; execution-while-not-rendered 'none'; execution-while-out-of-viewport 'none'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; layout-animations 'none'; legacy-image-formats 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; navigation-override 'none'; oversized-images 'none'; payment 'none'; picture-in-picture 'none'; publickey-credentials 'none'; sync-xhr 'none'; usb 'none'; vr 'none'; wake-lock 'none'; xr-spatial-tracking 'none';
< Cache-Control: max-age=1800
< CF-Cache-Status: HIT
< Age: 3339
< cf-request-id: 0a4585cf3400001ccceebb6000000001
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 654f725ebd721ccc-BUD
<
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-play-app" content="app-id=com.btcturk.pro">
    <meta name="apple-itunes-app" content="app-id=1471639720">
    <meta name="google-site-verification" content="tPiqb-MbuiDeormeAL5Z9TS-5UL11ePThlzPJTpCzgA" />
    <meta name="description" content="BtcTurk PRO ile profesyonelce Bitcoin ve kriptopara alın ve satın.">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <link rel="alternate" hreflang="tr" href="https://pro.btcturk.com">
    <link rel="alternate" hreflang="en" href="https://pro.btcturk.com/en">
    <script src="/assets/datafeeds/udf/dist/polyfills.js?v=9.1" type="text/javascript"></script>
    <script src="/assets/datafeeds/udf/dist/bundle.js?v=9.2" type="text/javascript"></script>
    <script src="/assets/nr.js?v=1.0.0" type="text/javascript"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-807541059"></script>
    <script src="/assets/gtag.js?v=1.0.0" type="text/javascript"></script>
    <script src="/assets/gtm.js?v=1.0.0" type="text/javascript"></script>
<link rel="stylesheet" href="styles.d7bc198f22778d225b1d.css"><script async src='/cdn-cgi/bm/cv/669835187/api.js'></script></head>
<body class="dark-mode">
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-54L33R8" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script src="/assets/site.js?v=9.4" type="text/javascript"></script>
    <app-root></app-root>
<script type="text/javascript" src="runtime.5910468e2e8512b36fe6.js"></script><script type="text/javascript" src="polyfills.10dec8137620bd536f80.js"></script><script type="text/javascript" src="scripts.59e847974dfa927ca719.js"></script><script type="text/javascript" src="vendor.f2c4d29d47b140063c0a.js"></script><script type="text/javascript" src="main.0447af2483f69351802a.js"></script><script type="text/javascript">(function(){window['__CF$cv$params']={r:'654f725ebd721ccc',m:'066e61b4330fbf1ea0e169c1128b9534cdceb43e-1621952870-1800-AfgS0oIXGWqL4psZbGaQTxJr6lfCn09nr33ox42PRay+ClKzq6zv7bkNJGP2367GGBAvt0AIXhitYh6Rb6aw8MNqDpcobUKfdKCw+ON1BSYp0ocl7dCJXJTcsDFHyANksHl1vPW6tvZxrOoPF900okE=',s:[0x681cfa5952,0xdb2cda65ff],}})();</script></body>
</html>* Connection #0 to host api.btcturk.com left intact

**Comment by ocinbat** [comment]
Selamlar, şu anda durum nedir?

**Comment by emrahtopcu** [comment]
Son birkaç saattir takip ediyorum tekrarlanmadı. Çok teşekkür ederim.
