### ISSUE TITLE
appscript bağlantı sorunu

### ISSUE THREAD

**Issue by mreminkus** [BTCTrader/broker-api-docs#381]
Appscript üzerinden api bağlantısı yapmaya çalışıyorum ancak muhtemelen Auth ile ilgili sorun yaşıyorum . Aşağıdaki koda bakıp yanlış olan şeyi söyleyebilir misiniz?

function BtcturkOrder() {
//Btcturk api
var keyBtcturk = '-'; // Please input your key.
var secretBtcturk = '-'; // Please input your secret.
var url = "https://api.btcturk.com/api/v1/users/balances";
var timestamp = Number(new Date().getTime()).toFixed(0);

// Create and encrypt signature
var keyTimestamp = keyBtcturk + timestamp;
var signature = Utilities.base64Encode(
    (Utilities.computeHmacSha256Signature(keyTimestamp, Utilities.base64Encode(secretBtcturk))));

var headers = {'X-PCK': keyBtcturk,'X-Stamp': timestamp,'X-Signature': Utilities.base64Encode(signature)};
// Build and make request
var options = {
    'method' : 'GET',
    'contentType': 'application/json',
    'payload' : JSON.stringify(headers)
    };

var  data = UrlFetchApp.fetch(url, options); 
Logger.log(data.getContentText())

}

**Comment by onurgozupek** [comment]
Merhaba, eğer sunucunuz/bilgisayarınız UTC zaman diliminde değilse, scriptin başına zaman dilimi tanımlaması ekleyip tekrar deneyebilir misiniz? Bir de nonce değerinin (timestamp) 13 hane olduğundan emin olun lütfen...

**Comment by mreminkus** [comment]
timestamp ile ilgili bir sorun yok https://api.btcturk.com/api/v2/server/time   ile aynı timestamp geliyor.  Auth kısmında sorun yaşıyor olabilirim. Gelen hata kodu  Exception: Request failed for https://api.btcturk.com returned code 405

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
