### ISSUE TITLE
api serverlarının cografi lokasyonu

### ISSUE THREAD

**Issue by angebot84** [BTCTrader/broker-api-docs#382]
Merhaba, hızlı işlem yapabilmek adına https://api.btcturk.com un cografi lokasyonu nerede acaba? Hali hazırda order placementlar 200ms den daha kısa sürede gerçekleşmiyor ne yazık ki.

**Comment by ocinbat** [comment]
Amsterdam

Sent from my iPhone

On 27 May 2021, at 20:03, angebot84 ***@***.***> wrote:

﻿

Merhaba, hızlı işlem yapabilmek adına https://api.btcturk.com un cografi lokasyonu nerede acaba? Hali hazırda order placementlar 200ms den daha kısa sürede gerçekleşmiyor ne yazık ki.

**Comment by yemreak** [comment]
Merhabalar, @ocinbat @angebot84 
Benzer firmalar ile çalışırsak daha iyi performans alınabilir. Amsterdam lokasyonunda sunucu kiralamak için firma önerebilir misiniz?

**Comment by ocinbat** [comment]
Selamlar, kiralamak için öneri olarak bir fikir beyan edemiyorum. Bizim sunuculara lokasyon olarak yakında bir çözüm aramak için lokasyon bilgisi verebilirim. Sunucularımız hem Azure West Europe hem de Google Cloud Europe West’te bulunuyor. Aktif aktif 2 tarafta da çalışıyoruz ama isteklerin büyük bir kısmı Azure tarafına yönlendiriliyor.

Sent from my iPhone

On 28 May 2021, at 21:26, Yunus Emre ***@***.***> wrote:

﻿

Merhabalar, @ocinbat<https://github.com/ocinbat> @angebot84<https://github.com/angebot84>
Benzer firmalar ile çalışırsak daha iyi performans alınabilir. Hollanda üzerinde sunucu kiralamak için firma önerebilir misiniz?

**Comment by yemreak** [comment]
Teşekkür ederim
