### ISSUE TITLE
OAuth2 Endpoint

### ISSUE THREAD

**Issue by OzelTam** [BTCTrader/broker-api-docs#384]
Merhabalar, documentation'da requestlerin **OAuth2** ile yetkilendirilebileceği yazıyor ancak oauth endpointini malesef bulamadım. OAuth2 endpoint'i ve kullanıcı hesaplarına nasıl erişim sağlayabileceğim ile ilgili yardımcı olabilirseniz sevinirim.

![image](https://user-images.githubusercontent.com/72941200/120066740-84207a80-c080-11eb-8ef0-af13decc2f07.png)

**Comment by ocinbat** [comment]
https://sso.btcturk.com/.well-known/openid-configuration
