### ISSUE TITLE
ReadTimeOut, Son zamanlarda çok sık gelmekte 3s'yi geçmekte

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#385]
Son zamanlarda çok fazla bu hata gelmekte, 3s bile sürekli değişen bir sistemde çok fazla olmasına rağmen onu da aşan durumlar mevcut. Bunu için bir geliştirme yapmayacak mısınınız? en azından bilgi veya tavsiye verme zahmetinde bulunun lütfen.

Hata mesajı:
`HTTPSConnectionPool(host='api.btcturk.com', port=443): Read timed out. (read timeout=3)` 

Ek not: _`3s` içerisinde tahtadaki fiyat teklifleri değişiyor ve yazılım alımı / satımı gerçekleştiremiyor_

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
