### ISSUE TITLE
Sistem Bakımdayken ya da çöktüğünde

### ISSUE THREAD

**Issue by ekremus** [BTCTrader/broker-api-docs#386]
keşke bi endpointiniz olsa da sistem bakımda mı çöktü mü bize söylese. Websocket'leriniz sıfır dönse de olur. yanlış değer vermesin yeter.

**Comment by yuzgecoguz** [comment]
@ekremus katılıyorum...

**Comment by EUA** [comment]
Bence de ama. Anca tv reklamı üretiyorlar. Pek çalışmayı sevmiyorlar...

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
