### ISSUE TITLE
Socket Authentication

### ISSUE THREAD

**Issue by serkancantech** [BTCTrader/broker-api-docs#388]
Socket authentication'la ilgili dokümantasyonda bir bilgi bulunmuyor.  Dokümantasyonda gecen socket user login işlemi için gerekli UserId ve token bilgileri nereden alınmalıdır? v2/Userinfo endpointinden sorguladığımda da UserId diye birbilgi gelmiyor.

Socket kullanımlarına yönelik api benzeri bir örnek kodlar eklenebilir mi? Özellikle web socket authentication ile ilgili örnek bir kullanım örneği paylaşmanızı rica ederim.

**Comment by ocinbat** [comment]
Selamlar, socket altyapımızı değştiriyoruz. Yakın zamanda HMAC ile sockete login olabileceğiniz bir yöntem ekleyeceğiz. Dokümantasyonda takipte kalın lütfen.
