### ISSUE TITLE
Bug | ExchangeInfo min total amount uyumsuzluğu

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#389]
https://api.btcturk.com/api/v2/server/exchangeinfo üzerinden alınan veride TRY çifti işlemleri için `minTotalAmount` değeri `99.91` gözükmekte iken asıl değeri `100` olmaktadır. Bu uyumsuzluğu çözer misiniz

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
