### ISSUE TITLE
Not able to give buy order with JavaScript code

### ISSUE THREAD

**Issue by ialpay** [BTCTrader/broker-api-docs#39]
My code is not working. Console output is as following;({"code":401,"message":"Unauthorized - Invalid Request"})

I will appreciate if you can help me to correct the mistake. 

const request = require('request');
const sha256 = require('crypto-js/sha256');
const hmacSHA512 = require('crypto-js/hmac-sha512');
const Base64 = require('crypto-js/enc-base64');

var PublicKey = <Publick Key>;
var PrivateKey = <Private Key>;
var nonce = Math.floor(new Date() / 1000).toString();

const hashDigest = sha256(nonce + PublicKey);
const hmacDigest = Base64.stringify(hmacSHA512( hashDigest, PrivateKey));

const options = {
    url: 'https://www.btcturk.com/api/exchange',
    method: 'post',
    OrderMethod: 0,
    OrderType: 0,
    Price: 39000,
    Amount: 0.0001,
    PairSymbol: 'BTCTRY',

    headers: {
      'X-PCK': PublicKey,
      'X-Stamp': nonce.toString(),
      'X-Signature': hmacDigest,
  }
}
var req = request.post(options, function(error, response, body) {
    console.log(body);
});

**Comment by nepnesomao** [comment]
The "X-Stamp" value should be "YourPublicKey + nonce"

**Comment by nepnesomao** [comment]
Can you use hmacSHA512 to hmacSHA256

**Comment by ialpay** [comment]
Tried. Unfortunately, nothing changed.

**Comment by yusufmendes** [comment]
@onurgozupek hmac şifrelemesi pythonda ve javascriptte aynı parametrelerle çalıştırıldığında farklı sonuc veriyor bundan dolayı api server   **"Unauthorized - Invalid Request"**  hatası veriyor. Örnek kodların hepsi python üzerinden ve javascriptle hiç birşekilde api server a login olamıyoruz.Yardımcı olabilirmisiniz

**Comment by mhelvacikoylu** [comment]
can you try to use nonce as milliseconds instead of seconds?

use that code:
`var nonce = new Date().getTime().toString()`

instead of:
`var nonce = Math.floor(new Date() / 1000).toString()`

And try it with hmacSHA256

**Comment by yusufmendes** [comment]
@mhelvacikoylu  My code is following but I get same error **Unauthorized - Invalid Request**

    let nonce = new Date().getTime().toString()
    let message = btcTurkPublicApi + nonce;
    let signature = crypto
        .createHmac("sha256", btcTurkPrivateKey)
        .update(message)
        .digest("base64");
    return {
        'X-PCK': btcTurkPublicApi,
        'X-Stamp': nonce,
        'X-Signature': hashInBase64,
        'Content-Type': "application/json"
    }

**Comment by mhelvacikoylu** [comment]
at here
`.createHmac("sha256", btcTurkPrivateKey)`

your btcTurkPrivateKey is string or byte array? It should be byte array. If you have a base64 string, you should convert it to byte array buffer.

if node-types library imported to your project you can convert it easily with the code:
`.createHmac("sha256", new Buffer(btcTurkPrivateKey, "base64"))`

or you can do it with pure javascript with this way
https://stackoverflow.com/questions/21797299/convert-base64-string-to-arraybuffer/21797381

**Comment by yusufmendes** [comment]
@mhelvacikoylu  Hobaaa :D btcTurkPrivateKey  was string .thank you  for your help
