### ISSUE TITLE
411 Error Code dönüyor (order)

### ISSUE THREAD

**Issue by bozdemir84** [BTCTrader/broker-api-docs#391]
Aşağıdaki gibi order gönderiyorum ama hep 411 dönüyor. Araştırdım Content-Length Error olduğunu öğrendim. Request Header'a "Content-Length=0" ekleyip denedim ama yine aynı hatayı dönüyor. Nerede hata var acaba ?

Executing POST request at https://api.btcturk.com/api/v1/order/?quantity=0.0001&orderMethod=limit&orderType=buy&pairSymbol=BTCTRY&price=335000 
Request headers = {X-Stamp=1623841944803, Content-Length=0, Accept=application/json, X-Signature=gvXLbt5tuG49icRjGlSLsrIlRYBiFh6dIqasdWMV5pU=, X-PCK=d2cXXXX9-aXXc-4XX7-9XX6-3c0fXXXX9c00}

**Comment by ocinbat** [comment]
Parametreleri json body olarak gönderin.

`{
  "quantity": "string",
  "price": "string",
  "stopPrice": "string",
  "newOrderClientId": "string",
  "orderMethod": "limit",
  "orderType": "buy",
  "pairSymbol": "string"
}`
