### ISSUE TITLE
obdiff eventlerinde adım atlama...

### ISSUE THREAD

**Issue by EUA** [BTCTrader/broker-api-docs#392]
obdiff eventlerinde çok adım atlama oluyor.
Ard arda gönderilen iki ileti

```
[432,{"CS":2166303,"PS":"FILTRY","AO":[],"BO":[{"CP":1,"P":"583.35","A":"41.843"},{"CP":3,"P":"525.96","A":"9.4969"}],"channel":"obdiff","event":"FILTRY","type":432}]                                                                                                          

[432,{"CS":2166305,"PS":"FILTRY","AO":[],"BO":[{"CP":3,"P":"583.35","A":"41.843"},{"CP":3,"P":"583.2","A":"0.8566"},{"CP":1,"P":"525.96","A":"9.4969"},{"CP":1,"P":"525.9","A":"0.8689"}],"channel":"obdiff","event":"FILTRY","type":432}]    
```

Şimdi aradaki CS:2166302 bir sebepten mi bana ulaşmadı mı, yoksa o saniye işlem mi olmadı kesin olarak bilemiyoruz.
En azından bu alanda "önceki CS" belirtilse, yada her saniye boş da olsa CS yi arttırmak için ileti gönderilse, daha doğru olmaz mı?

Ayrıca orbdiff kanalının yenileme hızı da 1 sn çok düşük. En azından 100ms'e çıkartamaz mısınız?

**Comment by yemreak** [comment]
Şu işe ne zaman kayda değer bir cevap vereceksiniz? Emirlerin güncel değerlerini veremiyorsunuz ve API'ın asıl amacı da bu değil midir? Ciddiyet lütfen.

**Comment by SelcukCode** [comment]
> obdiff eventlerinde çok adım atlama oluyor. Ard arda gönderilen iki ileti
> 
> ```
> [432,{"CS":2166303,"PS":"FILTRY","AO":[],"BO":[{"CP":1,"P":"583.35","A":"41.843"},{"CP":3,"P":"525.96","A":"9.4969"}],"channel":"obdiff","event":"FILTRY","type":432}]                                                                                                          
> 
> [432,{"CS":2166305,"PS":"FILTRY","AO":[],"BO":[{"CP":3,"P":"583.35","A":"41.843"},{"CP":3,"P":"583.2","A":"0.8566"},{"CP":1,"P":"525.96","A":"9.4969"},{"CP":1,"P":"525.9","A":"0.8689"}],"channel":"obdiff","event":"FILTRY","type":432}]    
> ```
> 
> Şimdi aradaki CS:2166302 bir sebepten mi bana ulaşmadı mı, yoksa o saniye işlem mi olmadı kesin olarak bilemiyoruz. En azından bu alanda "önceki CS" belirtilse, yada her saniye boş da olsa CS yi arttırmak için ileti gönderilse, daha doğru olmaz mı?
> 
> Ayrıca orbdiff kanalının yenileme hızı da 1 sn çok düşük. En azından 100ms'e çıkartamaz mısınız?

Belki gözden kaçırmış olabilirsiniz diye yazmak istedim. obdiff eventlerinde 431 de dönüyorlar. Yani beklediğiniz veri [431,{"CS":2166302,...,"channel":"obdiff","event":"FILTRY","type":431}]  şeklinde gelmiş olabilir.

**Comment by suleymanbyzt** [comment]
Merhaba,

Eventler için adım atlama durumu ile ilgili gerekli bilgilerme #420 issues altında verilmiştir.
