### ISSUE TITLE
WebSocket ile başarılı bir şekilde 111 kodlu UserLogin işlemini gerçekleştiremiyorum.

### ISSUE THREAD

**Issue by efecini** [BTCTrader/broker-api-docs#394]
Merhaba. BtcTurk wss servisleri ile işlem yapmak istiyorum. Bunun için ilk olarak 111 kodlu UserLogin eventini gerçekleştirmek istiyorum. İlgili access token'ı Chrome Dev Tools>Application>Local Storage>btcUser objesinden aldım ve base 64 ile decode ettim(access token'ın dogru oldugunu, iki nokta arasındaki veriyi decode ettigimde gelen objenin doğruluğundan teyit edebiliriz).

Böylece elimde login için gerekli olan tüm bilgiler var : ID, username, token, app ve platform. Bu bilgilerle ilgili feed e bir sorgu yapıp, 111 kodlu mesajı gönderdiğimde, 112 kodlu bir response almayı beklerken **[991,{"type":991, "current":"5.1.0", "min":"2.3.0"}]** mesajı response olarak geliyor. Lütfen yardımcı olurmusunuz; websocket ile nasıl login olacağım? Source code'u incelemeniz için aşağıya bırakıyorum. Teşekkürler.

```
package main

import (
	"flag"
	"log"
	"net/url"

	"github.com/gorilla/websocket"
)

var addr = flag.String("addr", "ws-feed-pro.btcturk.com", "BtcTurk Websocket Feed")

func main() {

	u := url.URL{Scheme: "wss", Host: *addr, Path: "/"}
	log.Printf("connecting to %s", u.String())

	c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
	if err != nil {
		log.Fatal("Dial Error:", err)
	}
	log.Printf("cont after dial")
	message := []byte(`{
		111,
		"type":111,
		"ID":......, //SECRET
                "username":"....@gmail.com", //SECRET
		"token":"eyJu.....", //SECRET
		"app":"pro",
		"platform":"ios"}`)
	err = c.WriteMessage(websocket.TextMessage, message)
	if err != nil {
		log.Println("write:", err)
		return
	}
	for {
		messageType, p, err := c.ReadMessage()
		if err != nil {
			log.Println(err)
			return
		}
		log.Println(string(p))
		if err = c.WriteMessage(messageType, p); err != nil {
			log.Println(err)
			return
		}
	}
}
```

Gelen Response:
[991,{"type":991,"current":"5.1.0","min":"2.3.0"}]

**Comment by efecini** [comment]
@ocinbat, en sonki issuelarda websocket auth altyapı değişikliği yapılıyor yazmışsınız.
1. Bu updatei mi beklemeliyim websocketler ile işlem yapmak için sizce?
2. Herhangi bir deadline var mı bu değişiklik için?
Teşekkürler.

**Comment by efecini** [comment]
@yedhrab, @aliveli186, her türlü yardıma açığım bu arada 😃

**Comment by yemreak** [comment]
Öncelikle aldığınız `[991,{"type":991,"current":"5.1.0","min":"2.3.0"}]` verisi WS bağlantısı kurulduğunda gelmekte, onu görmezden gelin. 

Şu alttaki mesajı WS'e gönderin.
```python
message = [
                111, {
                    "type": 111,
                    "id": config.WS_USER_ID,
                    "token": config.WS_ACCESS_TOKEN,
                    "username": config.WS_USERNAME
                }
            ]
```

**Comment by efecini** [comment]
Tamamdır. Dokumentasyonda sanki 112 kodlu bir response gelmeli gibi birşey okumuştum da ondan kafam karıştı.
Teşekkürler @yedhrab
