### ISSUE TITLE
Getting part of orderbook

### ISSUE THREAD

**Issue by auhopu** [BTCTrader/broker-api-docs#4]
There is a way to set a limit on the amount of retrieved trades via

api/trades?last=COUNT

Can the same be done with the order book? I.e. retrieve the COUNT lowest asks and COUNT highest bids instead of the whole order book?
 
/api/orderbook?max=COUNT

**Comment by emrekenci** [comment]
No. Just get the bids and asks to an array and do bids[0-5], asks[0-5] a parameter is pointless.

**Comment by auhopu** [comment]
Thanks, I have done that already.

IMHO, what is pointless is retrieving 500 arrays when all you need is 10.
