### ISSUE TITLE
Withdrawal

### ISSUE THREAD

**Issue by eraysaltik** [BTCTrader/broker-api-docs#40]
Hi, 

When will you available "withdrawal" ability in your API? Waiting for a long time.. Since you have withdrawal mechanism in your mobile app, it shouldn't be difficult to open it to the public via your API. 

Thanks, 
Eray 

--------------------------

Merhabalar, 

API'nize ne zaman para cekme ozelligi getireceksiniz? Uzun bir suredir bekliyoruz. Mobil uygulamaniz para cekme ozelligi oldugu icin API olarak hazirdir diye dusunuyorum, bunu herkesle paylasmaniz zor olmasa gerek? 

Tesekkurler, 
Eray

**Comment by serensoner** [comment]
Merhaba, aynisinin ETH/BTC cekme ozelligini bekliyorum ben de halen.

**Comment by serensoner** [comment]
Merhaba, bir gelişme var mı acaba?

**Comment by EUA** [comment]
API üzerinden withrawal özelliği gelecek ise en azından

- Sadece daha önceden sisteme kayıt edilmiş adreslere gönderim opsiyonu.
- Sadece sisteme daha önceden kayıt edilmiş IPv4 veya IPv6 adresi ile API erişimi opsiyonu.

Getirilmesi şart olan opsiyonlar olarak düşünüyorum.
API üzerinden her adrese gönderim yapabilme özelliği sıkıntılı ve korkutucu geliyor bana...

**Comment by suleymanbyzt** [comment]
Merhaba,

Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
