### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by oxanero** [BTCTrader/broker-api-docs#400]
Selamlar,
APi içerisinde geçmiş veriyi görebileceğimiz bir methodu ya da yöntemi var mıdır bilen var mı?
Binance te örneğin:KLINE_INTERVAL_1HOUR ya da 4HOUR diye yöntemlerle 500 satırlık veri alabiliyoruz.
Trend analizi için nasıl bir yöntem kullanabilirim?

**Comment by suleymanbyzt** [comment]
Merhaba,

Graph API'da kline verileri için;

`symbol `için BtcTurk | PRO'daki tüm işlem çiftleri (Örn BTCTRY)

`resolution `için 1,5,15,30,60,240 (dakika), 1D (gün), 1W (hafta), 1Y (yıl) mum dilimlerini kullanabilirsiniz.

`from` :  Başlangıç zaman damgası
`to` : Bitiş zaman damgası

Sorguyu dakikalık yapmak için `from ` - `to ` aralığını daraltmanız gerekmektedir. (Örnek 3 gün)

https://graph-api.btcturk.com/v1/klines/history?symbol=BTCTRY&resolution=1&from=1602925320&to=1603152000

**Comment by fethifikret** [comment]
bitiş zaman damgası kullanmadan güncel ohlcv datadan geriye doğru 100,200,1000 vs datayı çekmek istiyorum. bunu otomatik her 60 dakikada bir almak istiyorum. dolayısıyla her veri güncelleme öncesi başlangıç zaman damgası ve bitiş zaman damgası ayarlamakla uğraşmadan ohlcv verisini excele nasıl çekebilirim
