### ISSUE TITLE
Visual Studio 2015 ile build problemi

### ISSUE THREAD

**Issue by KorayAtalay79** [BTCTrader/broker-api-docs#401]
Merhabalar,
Bilgisayarimda VS2015 kurulu ve baska bir versiyonunu kuramiyorum.
V2 icin hazirlanmis projeyi indirip acmak istedigimde acamiyor, muhtemelen daha yeni bir surum gerekli.
Ben de VS2015 ile yeni proje acip, dosyalari bu projenin icine gomdum. 
Nuget ten IdentityModel ve NewtonSoft yukledim.
.net framework 4.8
Asagidaki fonskiyonda (Authentication.cs icinde) DiscoveryClient classini ve RequestResourceOwnerPasswordAsync fonksiyonu bulamiyor.

Authentication.cs

        public async Task<TokenResponse> GetTokenResponse(string refreshToken = null)
        {            
            // discover endpoints from metadata
            var disco = await **DiscoveryClient**.GetAsync(_authenticationUrl);
            if (disco.IsError)
            {
                return null;
            }

            // request token
            var tokenClient = new TokenClient(disco.TokenEndpoint, "api");
            TokenResponse tokenResponse;
            if (string.IsNullOrEmpty(refreshToken))
            {
                tokenResponse = await tokenClient.**RequestResourceOwnerPasswordAsync**(_username, _password);
            }
            else
            {
                tokenResponse = await tokenClient.RequestRefreshTokenAsync(refreshToken);
            }

            return tokenResponse;
        }

Yardimlarinizi bekliyorum.
Tesekkurler.

**Comment by suleymanbyzt** [comment]
Merhaba,

C# API için genel bir sorun bulunmamakta.

Yaşamış olduğunuz sorun visual studio sürümünüzün eski olması nedeniyle yaşanıyor olabilir.

Visual studioyu güncelleyip işlemi tekrar denemenizi rica ederiz. Sorunun devamı halinde yanıt olarak tekrardan dönüş yapabilirsiniz.
