### ISSUE TITLE
{ statusCode: '401', statusText: 'Unauthorized' }

### ISSUE THREAD

**Issue by bursar1983** [BTCTrader/broker-api-docs#403]
Selamlar,
Yukardaki hatayı hep alıyorum.
Bu konuda yardımcı olabilir misiniz?@BTCTraderAdmin@onurgozupek @ocinbat @MaDeRkAn @emrekenci @farukterzioglu @hu53yin

**Comment by suleymanbyzt** [comment]
Merhaba,

401 hata kodu kimlik doğrulama adımının başarısız olması sonucunda alınan hatadır.

Public ve private key bilgilerinizi kontrol etmenizi, API Key için belirlediğiniz IP bilgisinin doğruluğundan emin olmanızı rica ederiz.

Daha detaylı bilgiye [bu link](https://docs.btcturk.com/errors) üzerinden erişebilirsiniz.
