### ISSUE TITLE
TimeoutError hatası çok sık karşılaşılmakta

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#404]
API isteklerinde çok fazla Timeout hatası gelmekte. Sunucu işlemlerinizde gecikmeler olmakta, timeout sorununu engellemek için client tarafında neler yapmamızı tavsiye edersiniz?

**Comment by suleymanbyzt** [comment]
Merhaba,

İlgili tarihte anlık bir erişim problemleri yaşamış olabilirsiniz.

Sorunun devamı halinde geri bildirimde bulunmanızı rica ederiz.
