### ISSUE TITLE
WebSocket subscribe işlemleri için limit var mı?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#405]
- En fazla kaç orderbook için WS üzerinde subscribe olabiliriz?
- Ek olarak son fiyat ve miktar bilgilerini almak için WS Obdiff Subscribe dışında ticker üzerinden de veremez misiniz?
- Binance üzerinde ticker ile bu bilgiler aktarılmaktadır, neden sizde bu yok?
@BTCTraderAdmin @mhelvacikoylu @ocinbat @onurgozupek

**Comment by suleymanbyzt** [comment]
Merhaba,

Önerileriniz için teşekkür ederiz.

Dökümantasyonumuz kullanıcılarımızın önerileri ile birlikte her geçen gün yenilenmektedir.

Konu hakkında önerilerinizi ilgili birimlerimize ilettim. Talebiniz ile ilgili güncellenme olması durumunda size bu issues altında bilgilendirme yapıyor olacağım.
