### ISSUE TITLE
Order Updates through web socket

### ISSUE THREAD

**Issue by s13rw81** [BTCTrader/broker-api-docs#406]
Greetings,

I am working on a trading system and am following documentation from this page. https://docs.btcturk.com/websocket-feed/models.

I wish to receive order updates through the web socket. Foe example, when i place an order to BTCTurk, I wish to receive, `453 OrderUpdate`, so that I know when the order is filled or rejected.

I understand that I need to authenticate, using the `111 UserLogin` model but I am unable to figure out what parameters to send to the websocket in order to get the requested order detail responses from the server.

I am trying to send the following JSON
```json
[
    111,
    {
        "type": 111,
        "id": 1112233444,
        "username": "myemail@gmail.com",
        "token": ######API_KEY#####,
        "app": "easy",
        "platform": "windows",
    },
]
```

and getting the following response through the websocket.recv() ```[991, { "type": 991, "current": "5.1.0", "min": "2.3.0" }]```

For the `token` I have tried sending
- the API key,
- API secret,
- X-Signature as well as
-  the complete `Header` from https://docs.btcturk.com/authentication/authentication-v1 
but I always get `[991, { "type": 991, "current": "5.1.0", "min": "2.3.0" }]` response.

Kindly help me understand how to login and receive order status updates through the web socket.

Thanks in advance

**Comment by ozgun77** [comment]
Right now we are authenticating users only with jwt tokens from our applications. We don't have hmac authentication for web socket. But this feature will be available in the near future.

**Comment by s13rw81** [comment]
Thank you for your reply. Without user dats flowing through web sockets, there are plenty of trading strategies that simple will not be viable. Fetching the order status through the Rest API increases the change of breaking the rate limits.

I would therefore request the engineering team to introduce this feature at the earliest.

**Comment by vhdmsm** [comment]
This is really bad since there is no way to authenticate in websocket using API Key! It would be really great if we could use API Key instead of Access Token in the fields since there's no way to obtain Access Token through APIs and it's only available on the browser. Also, it's changing by the time so we need it on API please add it

**Comment by s13rw81** [comment]
@BTCTraderAdmin is there an update on this issue ? @ozgun77 due to calling the REST API to fetch orders status multiple times, we are breaching the API limits which is hindering our strategy performance.

Kindly mention this issue to your team. We have important high value clients and we aren't being able to deliver products to them. @burakoner

**Comment by suleymanbyzt** [comment]
Thank you for your feedback.

When there is a development on the subject, we will inform you.

**Comment by suleymanbyzt** [comment]
Hey @s13rw81 @vhdmsm 

Added article for HMAC Authentication. You can view our new article by [clicking here.](https://docs.btcturk.com/websocket-feed/protocol)

Thank you for your suggestion.

**Comment by s13rw81** [comment]
To everyone at BTC Turk engineering team, **a billion thank you!**
