### ISSUE TITLE
Deposit Withdrawal Transactions hatali 

### ISSUE THREAD

**Issue by guvenma** [BTCTrader/broker-api-docs#407]
Deposit-Withdrawal bilgileri icin asagidaki python kodunu (btcturk kaynaklarindan alimistir) kullaniyorum 

    method = "/api/v1/users/transactions/crypto"
    uri = base+method    
    params={ "type": ["withdrawal"], "symbol":["AVAX"], "endDate":163413797, "startDate":1626361978}
    
    print(params)
    result = requests.get(url=uri, headers=headers, json=params)    
    if result!=None:
        result = result.json()
        print(json.dumps(result, indent=2))    

Asagidaki sonuc geliyor (not: endDate ve startDate son 90 gunluk data icin..)

{'type': ['withdrawal'], 'symbol': ['AVAX'], 'endDate': 163413797, 'startDate': 1626361978}
{
  "data": [],
  "success": true,
  "message": "SUCCESS",
  "code": 0
}

Oysa web’den girip bakinca bu tarih araliginda 10 adetlik bir AVAX withdrawal var.

Bu arada, transactions/crypto endpoint'ine dokumantasyon'a gore POST olarak erisim var, oysa GET olarak calisiyor, POST ile hata veriyor.

**Comment by suleymanbyzt** [comment]
Merhaba,

endDate bilginizin doğruluğundan emin olmanızı rica ederiz.

Kodunuzu incelediğimde 1 digit eksik doldurma yaptığınızı görüntülüyorum.

Değerleri doğru girmeniz durumunda sorunsuz bir şekilde işlemlerinize devam edebilirsiniz.

**Comment by guvenma** [comment]
Haklisiniz, buraya paste ettigim ornek tarih hatali olmus. Ancak sorun devam ediyor. 
90 gunden daha dar bir aralik icin request ettim, hala bos sonuc donuyor.

```
{'Content-Type': 'application/json', 'X-Signature': 'zEhGzizSKgID58LoJK6ZYlboUI5hdRDwCiCDIHn9J/E=', 'X-PCK': u'42e7a3cf-c395-4635-8c5b-15a9832f8cfb', 'X-Stamp': '1641401865000'}
{'endDate': 1633137970, 'symbol': ['AVAX'], 'type': ['withdrawal'], 'startDate': 1630361978}
{
  "message": "SUCCESS", 
  "code": 0, 
  "data": [], 
  "success": true
}
```

Oysa btcturk.com uzerinden ayni tarihi sorguladigimda dogru sonuc listeleniyor.

![Capture](https://user-images.githubusercontent.com/31247372/148258389-b831895e-7404-4aff-b4f0-06c39bf4046a.JPG)

Lutfen tekrar bakarmisiniz.

**Comment by suleymanbyzt** [comment]
Merhaba,

Göndermiş olduğunuz timestamp verisinin hatalı olduğunu görüntülüyorum. JSON nesneleri için milisaniye türünden de hesaplama yapmanız gerekmektedir. (timestamp formatınızın 13 digit olacak şekilde istek atılması)

[Bu siteden](https://currentmillis.com/) timestamp için milisaniye türünden de hesaplama yapabilirsiniz.

İlgili parametreleri formata uygun girmeniz durumunda sorunsuz bir şekilde response alacaksınız.

**Comment by guvenma** [comment]
Milisaniye olarak denemistim, ama o sekilde de sonuclari alamiyorum. 

```
{'Content-Type': 'application/json', 'X-Signature': '0/tPwTbBWHWu4ySv1h41gdeAcIzFTOVr9s1bd0U7PWg=', 'X-PCK': u'42e7a3cf-c395-4635-8c5b-15a9832f8cfb', 'X-Stamp': '1641458252000'}
{'endDate': 1633137970000, 'symbol': ['AVAX'], 'type': ['withdrawal'], 'startDate': 16303619780000}
{
  "message": "SUCCESS", 
  "code": 0, 
  "data": [], 
  "success": true
}
```

Bu arada dokumantasyon request'in "POST" olarak girilmesini yaziyor, ancak POST ettigimde <RESPONSE | 405> hatasi aliyorum. Milisaniye ya da saniye olarak POST denedim, 405 hatasi veriyor.  O yuzden asagidaki gibi hep GET kullanarak sonuc almaya calistim. Yani burada su ana kadar paylastigim JSON sonuclari GET kullanarak alinmisti. 

```
    method = "/api/v1/users/transactions/crypto"
    uri = base+method    
    params={ "type": ["withdrawal"], "symbol":["AVAX"], "endDate":1633137970000, "startDate":16303619780000}
    
    print(headers)
    print(params)
    result = requests.get(url=uri, headers=headers, json=params)    
    if result!=None:
        result = result.json()
        print(json.dumps(result, indent=2)) 
```

Ilgilendiginiz icin tesekkur ederim, bu konu uzun suredir cozulmedigi icin tekrar yardiminizi istiyorum.

**Comment by suleymanbyzt** [comment]
Merhaba,

İsteğinizi `GET` metodu ile göndermeniz gerekmektedir.

İlettiğiniz kodu incelediğimde `"startDate":16303619780000` olarak doldurma yaptığınızı görüntülüyorum.

İlgili timestamp verisi 22 Ağustos 2486 yılına ait bir tarih olduğu için hata almanız muhtemel.

Ekran görüntüsündeki işleminize göre timestamp aşağıya ekliyorum.

Start Date: 1631005932000
End Date: 1631697132000

İşlemi ilettiğim timestamp verisine göre tekrar deneyebilir misiniz?

İşlemi ben test ettiğimde herhangi bir sorun almıyorum responses doğru geliyor. Verileri düzeltmenize rağmen hata alıyorsanız kodunuzu tekrardan gözden geçirmenizi rica ederim

**Comment by guvenma** [comment]
Haklisiniz, sonuca yaklastigimiz hissine kapilarak acele ile manuel girislerleri hatali yaptim (normalde tarihleri kullandigim uygulama hesapliyor). Bu sefer de startDate hatali olmus. Ancak size gondermeden once bircok kombinasyonu denemistim. Milisaniye olarak (timestamp'lere 000 ekleyerek cok kez denemistim) Maalesef sonuc hep ayni geliyor. Sizin verdiginiz degerlerle deneyince de sonuc degismedi.

```
{'Content-Type': 'application/json', 'X-Signature': 'V7lGNvuQR9C1oBZkJfpl00gmnYD2+trPbkm8nNOGngw=', 'X-PCK': u'42e7a3cf-c395-4635-8c5b-15a9832f8cfb', 'X-Stamp': '1641461183000'}
{'endDate': 1631697132000, 'symbol': ['AVAX'], 'type': ['withdrawal'], 'startDate': 1631005932000}
{
  "message": "SUCCESS", 
  "code": 0, 
  "data": [], 
  "success": true
}
```

Kullandigim python kodunu ekliyorum. Kod "/api/v1/users/balances" komutu ile dogru calisiyor.  Yani header kisminda problem yok. Bu kodu kendi tarafinizda (sizin withdrawal ya/da deposit yaptiginiz bir cryptocurrency ile) deneyebilir misiniz?  Yardimci olacaksa, belirteceginiz bir hesaba deneme amacli olarak kucuk bir deposit yapayim, sizde o hesaptan benim hesaba withdrawal yapin. O transactionlara bu kodla ulasmayi deneyelim. 

```
import time, base64, hmac, hashlib, requests, json
import os,sys
base = "https://api.btcturk.com"
apiKey = "***"
apiSecret = "***"
apiSecret = base64.b64decode(apiSecret)

stamp = str(int(time.time())*1000)
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type" : "application/json"}

#method = "/api/v1/users/balances"
method = "/api/v1/users/transactions/crypto"
uri = base+method    
params={ "type": ["withdrawal"], "symbol":["AVAX"],  "endDate":1631697132000, "startDate":1631005932000}    
print(headers)
print(params)
result = requests.get(url=uri, headers=headers, json=params)
if result!=None:
    result = result.json()
    print(json.dumps(result, indent=2)) 
```

Acaba benim key'ler ilgili bir sinirlama olabilir mi? Izinlere baktigimda, "Al Sat, Kullanıcı Bakiyesi, Kullanıcı Hareketleri" acik gorunuyor.
