### ISSUE TITLE
Individual Symbol Book Ticker Streams ve All Book Tickers Stream ekleyecek misiniz?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#408]
- Binance WebSocket API içinde RealTime olarak yer alan alttaki yapıyı eklemecek misiniz?
- Türkiyedeki en iyi borsa olarak rakip firmaları örnek alıp ilerlemeniz gerekmez mi?
- Şu sisteminizi daha stabil ve gerçekçi değer veren hale getirmeyecek misiniz?

https://binance-docs.github.io/apidocs/spot/en/#individual-symbol-book-ticker-streams

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz, öneri ve talebinizi ilgili ekiplerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
