### ISSUE TITLE
Trades type (buy or sell ) is not exist in json result

### ISSUE THREAD

**Issue by mzgs2** [BTCTrader/broker-api-docs#41]
.../api/trades?pairSymbol=BTCTRY

**How can i know this trade is buy or sell ?**

  [
    {
     "date": 1439280491.0,
     "tid": "55c9ad6b1ac4dc12b06131dc",
     "price":767.47,
     "amount":0.06486361
    },
    {
     "date": 1439280491.0,
     "tid": "55c9ad6b1ac4dc12b06131dc",
     "price":767.47,
     "amount":0.06486361
    } 
  ]

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
