### ISSUE TITLE
Hesabımdaki bitcoin miktarını /api/v1/users/balances endpoint i ile sorguladıgımda noktadan sonra 16 haneli bir sayı geliyor.

### ISSUE THREAD

**Issue by efecini** [BTCTrader/broker-api-docs#410]
Bitcoin miktarımı _/api/v1/users/balances_ endpoint ile kontrol ettiğimde noktadan sonra 16 haneli bir sayı görünüyor. Ancak btcturk.com'da normal olarak noktadan sonra 8 haneli bir sayı var. Bunun sebebini ve bize ne gibi bir faydası olduğunu öğrenebilir miyim?

![1](https://user-images.githubusercontent.com/3943422/137553404-e16a8a49-dba5-4dc4-8926-f49cdf24679e.png)
<img width="151" alt="2" src="https://user-images.githubusercontent.com/3943422/137553406-da6dffcf-e580-4236-8326-0c69a5631137.png">

**Comment by suleymanbyzt** [comment]
Merhaba,

BTCUSDT işlem çifti için virgülden sonra 8 hane olacak şekilde görüntülenme yapılmaktadır.

İlgili pay ölçeği haricindeki değerler kuruş bakiye olarak görüntülendiği için 8 hane olacak şekilde görüntüleme yapılmaktadır.

Kuruş bakiyelerinizi Hesap>dönüştür sekmesinden görüntüleyebilirsiniz.
