### ISSUE TITLE
 Pairs Scale (Quantity/Price)

### ISSUE THREAD

**Issue by akkalkanugur** [BTCTrader/broker-api-docs#411]
https://api.btcturk.com/api/v2/server/exchangeinfo adresindeki ENJ içindeki "numeratorScale":2,"denominatorScale":2 ile https://pro.btcturk.com/pro/al-sat/ENJ_TRY'daki bakiye scale bilgileri birbirini tutmuyor.
Buradaki sorun nereden kaynaklanıyor?

**Comment by yemreak** [comment]
Çünkü önemsemiyorlar...

**Comment by suleymanbyzt** [comment]
Merhaba,

Scale değerlerinin bakiye bilgisi ile eşleştirilebilmesi talebinizi ilgili birimlerimize ilettik.

Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.
