### ISSUE TITLE
Market Emirleri çoğunlukla uygun fiyatları atlayarak eşleşiyor !!!

### ISSUE THREAD

**Issue by SelcukCode** [BTCTrader/broker-api-docs#413]
Aşağıda loglarımdan alıntıladığım şekilde size olayı özetle anlatmaya çalıştım. Market emri veriyorum ve alış emri ise aradaki ucuz fiyatlar atlanıp pahalı fiyattan eşleşebiliyor Satış emri ise pahalı fiyatlar atlanarak ucuz fiyattan eşleşebiliyor.

Market emrinin tanımında en uygun fiyatla eşleşmesi söz konusu olduğundan bu problem trade'lerimiz için çok ciddi bir konudur. Neden sıradaki en uygun fiyatlarla eşleşmiyor incelenmesini rica ederim. Sonraki OrderBook response'larında kontrol ettiğimizde halen aynı miktar ve aynı fiyatla daha uygun fiyatların beklediğini görebiliyoruz.

Şimdiden ilginiz için teşekkürler.

@BTCTraderAdmin @mhelvacikoylu @ocinbat @onurgozupek

![image](https://user-images.githubusercontent.com/11490824/137593507-c6c1e3a5-f638-4f4d-a60d-bfc1c36bd932.png)

**Comment by EUA** [comment]
Aynı sorunu ben de tespit ettim. Ben emri daha önce vermeme ve emrim daha önce gerçekleşmesine rağmen fiyat avantajlı emri benden sonra işlem yapan kişi almıştı. Şikaye ettim, yok olabilirmiş diyorlar. Nasıl olabilir diye detaylı şekilde anlattım, hâlâ geri dönecekler...

Aşağıdaki görselde UNI/USDT sembolünde **01:55:33** zamanına baktığınızda 2 adet ALIM match var. Alımda ilk alıcı düşük, ikinci alıcı yüksek fiyatı alması gerekirken burada ilk alıcı yüksek, ikinci alıcı düşük fiyatı almış. **İlk alıcı benim ve verdiğimde fiyat 18.100 idi.** Bu nasıl oluyor diye sordum cevap yok. Belirsiz alacak davası açmak gerekiyor artık heralde ticari mahkemede....

![Screenshot 2022-01-03 at 01-58-37 18 250 UNI USDT Grafikleri ve Anlık Fiyatları - BtcTurk PRO](https://user-images.githubusercontent.com/125917/150761170-cb0f2ba7-ae69-4bcc-a9e5-ef31d8343f14.png)

**Comment by suleymanbyzt** [comment]
Merhaba,

Emir vermeden hemen önce anlık olarak 18.245 fiyatından emir girişi yapılmış olabilir. Market emirleri anlık olarak en iyi alış ve satış emirlerine göre gerçekleşmekte.

Gerekli incelemeleri destek ekibi yapıp konu hakkında bilgilendirmeleri tarafınıza iletecektir.

**Comment by SelcukCode** [comment]
> Merhaba,
> 
> Emir vermeden hemen önce anlık olarak 18.245 fiyatından emir girişi yapılmış olabilir. Market emirleri anlık olarak en iyi alış ve satış emirlerine göre gerçekleşmekte.
> 
> Gerekli incelemeleri destek ekibi yapıp konu hakkında bilgilendirmeleri tarafınıza iletecektir.

Destek ekibine çok detaylı loglar ile mail atıldı, bilgilendirildi zamanında. Aylardır bir dönüş olmadı. Şuandan sonra olacak dönüş çok da anlamlı olmayacaktır. Teşekkürler.
