### ISSUE TITLE
Trade information: Was it a taker or maker trade?

### ISSUE THREAD

**Issue by kutoga** [BTCTrader/broker-api-docs#415]
Hi

Given an executed trade, I want to know if it was executed as a maker or taker trade. Unfortunately, this information is not available with these endpoints:
- https://api.btcturk.com/api/v1/users/transactions/trade
- https://api.btcturk.com/api/v2/account/advanced-order-history
- https://api.btcturk.com/api/v2/account/transactions/orderTrades
- https://api.btcturk.com/api/v2/account/history
- websocket (authenticated)

Is there a way to get this information?

Thank you very much

**Comment by suleymanbyzt** [comment]
Hi,

There is no response for this in the api.

Thank you for your feedback, i have forwarded your suggestion to our relevant teams.

I will inform you when there is a development on the subject.
