### ISSUE TITLE
API resultun verdiği alış miktarım web sitesinde gördüğüm alış miktarından farklı geliyor.

### ISSUE THREAD

**Issue by babursaylan** [BTCTrader/broker-api-docs#418]
Şöyle ki,
{"data":[{"price":"604.19","numeratorSymbol":"AVAX","denominatorSymbol":"TRY","orderType":"buy","orderId":5134348546,"id":558042058,"timestamp":1635446522817,"amount":"1.09","fee":"-1.00192290","tax":"-0.18034612"}],"success":true,"message":"SUCCESS","code":0}

Yaptığım alış miktarı 1.09 gördüğüm için, 1.09'luk bir satış yapıyorum, 

Oysa sitedeki işlemlerime baktığımda;
![image](https://user-images.githubusercontent.com/32214639/139332803-6c8a58f1-4262-4564-a25d-c82e9d775aad.png)

1.08 aldım, 1.09 sattım görünüyor, 

Bu dijit hatası her zaman olmuyor, ama olduğu zamanlarda elimde tutmak istediğim miktar ufak ufak azalıyor.

Fikriniz var mı acaba?
Teşekkürler.

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz.

AVAX için numeratorScale değeri 4 olarak güncellenmiştir.

Güncelleme yapılmadan önce işlemlerde virgülden sonra yalnızca 2 hane gösterimi yapıldığı için geçmiş AVAX işlemlerinizde dönüştür yapmamanız durumunda, önceki işlemlerinizden kalan  kuruş AVAX bakiyelerinizin dahil edilmesi sonucu 1,08 aldığınızı 1,09 şeklinde satıyor şeklinde görüntülenme durumu yaşanmaktaydı.

Yapılan güncelleme ile birlikte işlemlerinizde virgülden sonra 4 hane olacak şekilde görüntüleme sağlayabilirsiniz.

ENJ işlem çifti için aynı güncellemenin yapılabilmesi adına talebinizi ilgili birimlerimize ilettim. Konu hakkında gelişme olması durumunda sizleri bilgilendiriyor olacağız.
