### ISSUE TITLE
API v1'den <Response [401]> hatasi 

### ISSUE THREAD

**Issue by Chico135** [BTCTrader/broker-api-docs#419]
Asagidaki kodu IP kisitlamasi olmayan bir API anahtariyla calistirdigimda 200 aliyorum ancak IP kisitli anahtarlarimla surekli 401 aliyorum:

import base64, hmac, hashlib, requests, json, time
apiKey = "API_KEY"
apiSecret = "API_SECRET"
apiSecret = base64.b64decode(apiSecret)
stamp = str(int(time.time())*1000)
data = "{}{}".format(apiKey , stamp).encode('utf-8')
signature = hmac.new(apiSecret , data , hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK":apiKey , "X-Stamp":stamp , "X-Signature":signature , "Content-Type":"application/json"}

url = "https://api.btcturk.com/api/v1/users/balances"
resp = requests.get(url=url , headers=headers)
print(resp)

yardımcı olabilir misiniz?

**Comment by suleymanbyzt** [comment]
Merhaba,

401 hata kodu kimlik doğrulama adımının başarısız olması sonucunda alınan hatadır.

Public ve private key bilgilerinizi kontrol etmenizi, API Key için belirlediğiniz IP bilgisinin doğruluğundan emin olmanızı rica ederiz.

Daha detaylı bilgi için https://docs.btcturk.com/errors sitemizi inceleyebilirsiniz.
