### ISSUE TITLE
ÖNEMLİ | ObDiff kanalından dinlenen siparişlerde bazı diff verileri gelmiyor, emir defteri takibi hatalı

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#420]
Merhaba, obdiff kanalını dinleyip, update işlemini local ob değerlerim üzerinde uyguluyorum. Lakin bazı durumlarda diff değerleri eksik veya yanlış geliyor, bu local ob işlemlerinde en iyi ask veya bir değerlerinin tahtaya yapışmasına (emirler gitse bile diff değeri gelmediği için hep varmış gibi kalmasına) sebep oluyor. 

Örnekler: 9.74 fiyatlı bid emri olsun USDT_TRY için, 9.74 emri iptal edildiğinde iptali gösteren diff değeri gelmiyor. Bu da 9.65'ü düşen bir kur durumunda 9.74'te emir varmış gibi zannedildiğinden otomasyon işlemlerinde tekrarlı döngülere sokuyor ve satış - alış hatalarından dolayı yüksek miktarda paralar kaybediyoruz.

Sorunun sebebi veya çözüm öneriniz nedir? En sonunda sorunları çözmek yerine, hizmeti yanlış sunmaktan dolayı sizlere dava açma koşullarını araştıracağım...

**Comment by ocinbat** [comment]
Obdiff yanında OrderBookFull de alıp, her OrderBookFull geldiğinde localinizdeki datayı resetleyebilirsiniz.
Obdiff teknik olarak %100 alabileceğiniz bir şey değil. Socket bufferınız dolduğunda bağlantınız kopabilir, tekrar bağlanabilirsiniz. Bu arada kaçan mesajları alamazsınız tekrar. O yüzden OrderBookFull de dinlemeniz en sağlıklısı olacaktır.
