### ISSUE TITLE
Son güncelleme sonrası sürekli Authentication Error alıyorum

### ISSUE THREAD

**Issue by mstfimi** [BTCTrader/broker-api-docs#421]
Her 5. saniyede bir kez bakiye sorgusu ve açık emir sorgusu yapmama rağmen sürekli hata almaya başladım 2 gündür. Rate limitleri aşacak durumda olmadığım açık. Üstelik 1-2 gün önce hiçbir sorun yoktu.

apikey ve şifresi ile client oluşturduğum anda Authentication Failed hatası alıyorum. 2dk sonra tekrar denediğimde çalışıyor fakat 20-30 saniye sonra baktığımda yine error döndüğünü görüyorum.
btcturk_api.exceptions.BTCTurkAuthenticationError: Authentication Failed. Error Message: Authentication Error.

**Comment by suleymanbyzt** [comment]
Merhaba,

Anlık bir erişim problemi yaşamış olabilirsiniz. 

Kimlik doğrulama ile ilgili sorun yaşamamak için public-private key bilgilerinizin doğruluğunu kontrol etmenizi rica ederiz.
