### ISSUE TITLE
API ile okuduğum miktar bilgisi, gerçekleşen miktardan farklı

### ISSUE THREAD

**Issue by babursaylan** [BTCTrader/broker-api-docs#423]
Merhaba, 

/api/v1/users/transactions/trade?orderId=5843264088

ile okuduğum değerde amound=136.18 görünüyor.

object(stdClass)#2 (10) { ["price"]=> string(5) "39.29" ["numeratorSymbol"]=> string(3) "ENJ" ["denominatorSymbol"]=> string(3) "TRY" ["orderType"]=> string(3) "buy" ["orderId"]=> int(5843264088) ["id"]=> int(670350398) ["timestamp"]=> int(1639016462690) ["amount"]=> string(6) "136.18" ["fee"]=> string(11) "-8.16156043" ["tax"]=> string(11) "-1.46908088" } ---

Oysa siteden baktığımda gerçekleşen miktarın 136.1774 olduğunu görüyorum. 

Bu basamak hatası ENJ için her zaman oluyor, ama AVAX için olmuyor. ENJ 2 digit dönerken AVAX doğru biçimde, 4 digit dönüyor.

Bu hatayı nasıl düzeltebiliriz?
Teşekkürler.

**Comment by suleymanbyzt** [comment]
Merhaba,

İşlemlerinizde scale hatası almamak için /api/v2/server/exchangeinfo endpoint üzerinden ilgili işlem çifti için belirlenmiş numeratorScale değerine uygun bir şekilde değerlerinizi formatlamanız durumunda sorunsuz bir şekilde işlemlerinize devam edebilirsiniz.

**Comment by babursaylan** [comment]
Selamlar, bunu yapamıyorum, çünkü alım işlemini piyasa ile yapıyorum, yani örneğin, 500TL'lik bir alım emri veriyorum, aldığım miktarı ben belirlemiyorum, sistem belirliyor. Ancak api  bana 136.18 diye bilgi döndüğünde gerçekleşen doğru miktar 136.1774 oluyor.

**Comment by suleymanbyzt** [comment]
Merhaba,

numeratorScale değerinin 2 olarak belirlenmesinden kaynaklı virgülden sonra 2 hane olacak şekilde görüntüleme yapıyorsunuz.

Talebinizi öneri olarak ilgili birimlerimize iletiyorum. Konu hakkında bir gelişme söz konusu olduğunda, sizleri bilgilendiriyor olacağız.

**Comment by babursaylan** [comment]
Kusura bakmayın, net ifade edememiş olabilirim. Bu bir öneri değil, aslında bir bug. 
Sistem bana 136.18 aldın diyor, aslında gerçekleşen miktar 136.1774. Yazılımım belli bir fiyata ulaşınca satacak şekilde çalışıyor. Zamanı gelince 136.18 satmaya çalışıyor, halbuki o kadar bakiyem yok, ben farkedene kadar yazılım sürekli bu miktarda satış yapmaya çalışıyor, o arada fiyat da istemediğim bir düzeye gelmiş olabiliyor.
