### ISSUE TITLE
API submitOrder ve Detaylar Hk.

### ISSUE THREAD

**Issue by yazilimciadam** [BTCTrader/broker-api-docs#425]
API submit order methodunda market üzerinden alım yapıldığında, yapılan alımın nasıl success olduğunu anlayabiliriz veya bu konuda webhook mu gönderiliyor. Konuyla alakalı detayları rica ederim.

**Comment by suleymanbyzt** [comment]
Merhaba,

Gerçekleşen işlemlerinizi v1/users/transactions/trade endpoint üzerinden görüntüleyebilir ya da /api/v1/openOrders endpoint üzerinden açık emirlerinizi takip edebilirsiniz.

İşlem detaylarına erişmek için dilerseniz /v1/users/transactions/trade endpoint bilgisine query olarak orderId işlevini kullanabilir ya da tarihe göre filtreleme işlemi yapabilirsiniz.(Örnek istek /v1/users/transactions/trade?orderId=12345)
