### ISSUE TITLE
btcturk GET https://api.btcturk.com/api/v1/allOrders?pairSymbol=SOLTRY&limit=20 401 Unauthorized

### ISSUE THREAD

**Issue by s13rw81** [BTCTrader/broker-api-docs#427]
Greetings.

I am fetching all orders to get status of orders placed once every second. However i am getting this error.

```btcturk GET https://api.btcturk.com/api/v1/allOrders?pairSymbol=SOLTRY&limit=20 401 Unauthorized```

Kindly help me resolve this issue.

**Comment by suleymanbyzt** [comment]
Hi,

You need to authorize before sending your request on all user related operations like buy/sell/cancel orders, user balances, open orders etc.

Please check and confirm that you've created the API key from PRO website. Also, check the API Key's permissions. If you don't have the necessary permissions, your requests will be unauthorized. Also if you had limited API with an IP address and your server has a different address, your API requests won't be authorized.

![401](https://user-images.githubusercontent.com/58400764/147598725-994d998d-ee8f-40f7-94c0-d9d0c5ad5e28.JPG)

**Comment by s13rw81** [comment]
Thank you for your reply. I have all the necessary authorizations required and I am able to perform most of the operations you have mentioned above such as buy, sell and cancel. MY API Key is also limited to the IP of my AWS EC2 instance, however, the issue is only during certain times I am seeing this error and also sometimes `btcturk POST https://api.btcturk.com/api/v1/order 401 Unauthorized` . Please understand these happen only sometimes and other times they work fine.

Is it related to API limits being reached ?

Another question is, can i create an API that can be accessed from all IPs. I write my code on my local system which does not have a static IP. Can you tell me how to create an API key that is not mapped to any IP.

Thank You

**Comment by suleymanbyzt** [comment]
You get error code 429 when you submit too many requests. Your problem is with authentication.  You are only allowed to use one IP for the API.  you can perform your transactions with the IP you use to create the key

**Comment by suleymanbyzt** [comment]
Hi,

Thank you for the feedback

When you reach API limits you'll get error code 429. you are getting authentication problem.
[click here](https://docs.btcturk.com/errors) for more detailed information. Please check your IP address to avoid errors.

You can't create an API that can be accessed from all IPs. Only the specified IP can be processed.
