### ISSUE TITLE
Postman Url nedir

### ISSUE THREAD

**Issue by burakturker** [BTCTrader/broker-api-docs#428]
Bu apilerin postman veya swaggeri yokmu aradım aradım bulamadım.
Private apilere hiçbirşekilde erişemiyorum 401 alıyorum. Aldığım secret key ip restrictiondan geçemediğini düşünüyorum. Postmanden test etmek istiyorum.

**Comment by burakturker** [comment]
private apilere hiçbirşekilde erişemiyorum aldığım ip restrictiondan geçemediğini düşünüyorum. Postmanden test etmek istiyorum

**Comment by burakturker** [comment]
https://api.btcturk.com/api/v1/openOrders örneğin bu api kullanmak istiyorum response json nedir bilmiyorum. Java ile geliştircek olanlar için client yazıp paylaşmak istiyorum fakat dökümantasyonda aşırı eksik var yada ben bulamıyorum.Hali hazırda emrim yok dolayısıyla boş geliyor response fakat response json dolu olduğunda nasıl görünüyor nasıl öğrenicem her ihtiyacım olan apide örnek mi yaratıp request atıp response mu alıcam response json görebilmek için.Response json görüp response object yaratmak istiyorum

**Comment by suleymanbyzt** [comment]
Merhaba,

Responses için [buradan](https://docs.btcturk.com/private-endpoints/account-balance) dökümantasyonumuzu inceleyebilirsiniz.

Metotların yanında bulunan ok simgesine basmanız durumunda endpointler için responses görüntüleyebilirsiniz.

![1-2](https://user-images.githubusercontent.com/58400764/148171539-ecfb653f-f2c5-412d-8f0b-528ceb547326.PNG)
