### ISSUE TITLE
"Submit Order" doesn't work correctly for "orderMethod: market"

### ISSUE THREAD

**Issue by Wolfeon** [BTCTrader/broker-api-docs#429]
Hello,
I couldn't buy the amount i requested for. It was less than that. I checked the "quantity" from API response and it was correct. But the server didn't execute the right amount. After i checked Order History, i realized the issue. My requested quantity was equal to total price.

`Quantity(My request) = Execution Price x Matched amount + Fee`

My requested quantity should be equal to Matched amount. Please fix this.

**Comment by suleymanbyzt** [comment]
Hi,

Thank you for your feedback.

Commission fee is charged at the determined amount and the amount is deposited into your account. 

For more detailed information, you can view our fees page [by clicking here.](https://pro.btcturk.com/en/help/fees)

We will inform you if there is any development on the subject.

**Comment by Wolfeon** [comment]
There is nothing wrong with commission. I am fine with that.

This is the trade result from "api/v1/allOrders" endpoint:

```
id: 6529417647,
price: '2.419',
amount: '618.1514887833388887',
quantity: '0.0000000000000001',
stopPrice: '0',
pairSymbol: 'DOGETRY',
pairSymbolNormalized: 'DOGE_TRY',
type: 'buy',
method: 'market',
orderClientId: '7942534a-cb7e-4a11-a734-668608e79d3f',
time: 1642374005437,
updateTime: 1642374005670,
status: 'Closed',
leftAmount: '0.0000000000000000'
```

Normally "amount" is equal to "quantity" for "method: limit". But something went wrong here("method: market"). My requested quantity was 1498. It seems the quantity divided to price. I am sure about the quantity parameters i sent because API responded with "quantity: 1498".

**Comment by suleymanbyzt** [comment]
For market buy orders, you must trade with TL amount.  You can check our website about the subject (for market buy orders).

![Doge](https://user-images.githubusercontent.com/58400764/149882920-da3ca25b-df5e-423b-ae06-056cef298d96.PNG)

For market buy orders, you are required to trade with TRY. You can trade with the quantity of crypto in limit orders and market sell orders.

**Comment by Wolfeon** [comment]
Ok, i got it. Then we have to send total price with "quantity" parameter. This is a bit confusing because it is not same for market selling or limit orders. And there is no explanation about this in the API documents.

**Comment by suleymanbyzt** [comment]
Thank you for your feedback.

API documentation will be updated soon.

I will inform you when the document is updated.

**Comment by suleymanbyzt** [comment]
Hey @Wolfeon 

Submit order article has been updated. You can view the article by [clicking here.](https://docs.btcturk.com/private-endpoints/submit-order)

Thank you for your suggestion.

**Comment by Wolfeon** [comment]
Thank you!
