### ISSUE TITLE
ExchangeInfo dan YALAN bilgi yayılması - status:TRADING

### ISSUE THREAD

**Issue by EUA** [BTCTrader/broker-api-docs#430]
BTCTurk firması, daha önce kendilerini 2 defa uyarmama rağmen hâlâ API üzerinden YALAN bilgi yaymaktadır.

https://api.btcturk.com/api/v2/server/exchangeinfo

dan alınan bilgilerden bir sorgu:

`{'id': 19, 'name': 'BTCUSDT', 'nameNormalized': 'BTC_USDT', 'status': 'TRADING', 'numerator': 'BTC', 'denominator': 'USDT', 'numeratorScale': 8, 'denominatorScale': 0, 'hasFraction': False, 'filters': [{'filterType': 'PRICE_FILTER', 'minPrice': '0.0000000000001', 'maxPrice': '10000000', 'tickSize': '1', 'minExchangeValue': '9.91', 'minAmount': None, 'maxAmount': None}], 'orderMethods': ['MARKET', 'LIMIT', 'STOP_MARKET', 'STOP_LIMIT'], 'displayFormat': '#,###', 'commissionFromNumerator': False, 'order': 2001, 'priceRounding': False, 'isNew': False, 'marketPriceWarningThresholdPercentage': 0.25, 'maximumOrderAmount': None}`

görüldüğü üzere `'status': 'TRADING'` , yani şu an ticaret devam ediyor gibi gözüküyor. Ama BTCTürk dün geceden beri sorunlu. 
https://status.btcturk.com/
sayfasında  BTC pairleri için **Büyük Kesinti** yazıyor.

Durumdan şikayetçi olduğumda status sayfasını takip edin, e-posta bildirimlerine abone olun gibi abuk subuk cevap veriyorlar. Yahu status sayfasındaki değişkeni API daki gerektiği yere bağlamak bu kadar mı zor? Sizin geliştiricileriniz çay kahve içmek dışında bir şey yapmaz mı? Gecenin bir yarısı e-posta gelirse uykumdan kalkıp e-postayı okuyup programıma bilgi girişini elle mi yapacağım? 

Bakın özellik eklensin, söyle geliştirilsin vs. demiyorum. SİSTEMİN HATALI, YANLIŞ, HATTA BİLGİNİZ DAHİLİNDE OLDUĞU İÇİN ARTIK **YALAN** BİLGİ VERMESİNİ ENGELLEYİN diyorum. 2 haftadır düzeltecekler. Ne yaptığını bilen biri için 10 dk. almayacak bir iş bu...

**Comment by suleymanbyzt** [comment]
Merhaba,

Aynı enpoint üzerinde kriptopara yatırma-çekme, kriptopara işlem limitleri ve kriptopara alış-satış gibi bir çok response bulunmaktadır. Response için işlemin trading olduğunu ayırt edebilmek adına böyle bir gösterimimiz bulunmakta.

Konu hakkında gerekli bilgilendirmeler destek ekiplerimiz tarafından size yapıldığını görüntülüyorum.
Öneriniz ilgili birimlerimize iletildi. Konu hakkında geliştirme olması durumunda size buradan bilgilendirme yapacağız.

**Comment by EUA** [comment]
"status" durum demek değil mi?
Eğer verinin tipini nitelemek için bir sabit ismi gerekiyorsa, bu verinin al-sat verisi olduğunu belirtmek için "type" kelimesinin kullanılması gerekmez mi?

"status"="TRADE" de demiyor ki, "TRADING" diyor....
