### ISSUE TITLE
Feature Request | Çiftlerden biri bakıma alındığında veya engellendiğin API tarafında bunu belirten bir mesaj verin

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#431]
* Exchange info üzerinden bakıma giren çiftler için kapalı mesajı verilebilir
* Harici bir API ile pairlerin durumunu aktarabilirsiniz

> Bir şekilde şu sorunları belirten bir API end-point'i açın lütfen

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz.

Konu hakkında öneriniz ilgili birimlerimize iletildi. Geliştirme olması durumunda sizleri bilgilendiriyor olacağız.
