### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by lagosos** [BTCTrader/broker-api-docs#432]
Merhaba rate limit her ip için farklımı yoksa api key üzerinden bir bloklama söz konusumu?

**Comment by suleymanbyzt** [comment]
Merhaba,
API Key oluştururken belirlediğiniz IP adresi üzerinden rate limitler dahil olmaktadır. 
Belirlenen IP üzerinden rate limitler dahilinde işlem yapabilirsiniz.
Daha detaylı bilgi için [Rate Limits](https://docs.btcturk.com/rate-limits) dökümanımızı inceleyebilirsiniz.

**Comment by lagosos** [comment]
Malesef ki her ip adresine özel bi ratelimit vermiyorsunuz.  Genel kullanıcı id ile ratelimit mevcut dogru bilgi verirseniz sevinirim.
