### ISSUE TITLE
Eksik veri gelmesi

### ISSUE THREAD

**Issue by MasherCoder** [BTCTrader/broker-api-docs#434]
Merhabalar,
https://graph-api.btcturk.com/v1/klines/?symbol=
adresinizden farklı coinler için aynı periyotta veri çekmeye çalışıyorum ama gelen sonuç hep farklı. Bunun nedeni nedir?

Örnek vermek gerekirse aşağıdaki her coin için 14 günlük 15 dk lık veri çekmeye çalıştım;
DOGE/USDT
Gelen data sayısı:1243
AVAX/USDT
Gelen data sayısı:1272
BTC/USDT
Gelen data sayısı:1265
ETH/USDT
Gelen data sayısı:1264
MANA/USDT
Gelen data sayısı:1273
GRT/USDT
Gelen data sayısı:1080

**Comment by suleymanbyzt** [comment]
Merhaba,

Graph dataları gerçekleşen trade işlemlerine göre işleyiş yapılmaktadır.
İlgili pairde herhangi bir trade işlemi olmaması durumunda bir sonraki trade işlemi gerçekleşene kadar dakikalık olarak işleyiş yapılmamakta.

Örnek olarak 15:20 tarihinde 0.15 USDT fiyatından DOGE/USDT işlem çiftinde bir trade olduğunu düşünelim. 
Bu işlem sonrası graph verilerine 15:20 tarihinde 0.15 USDT fiyatında bir mum gösterimi yapılacaktır.
İkinci trade işleminin 15:30'da 0.16 USDT fiyatından gerçekleştiğini düşünelim. Farklı bir fiyattan trade gerçekleştiği için graph verilerine 15:30 tarihinde 0.16 USDT türünden bir mum gösterimi yapılarak veri işlenecektir.
İlgili pairde trade sayılarının az olmasına bağlı olarak data sayısında eksik gösterim yapmanız olağandır.

**Comment by MasherCoder** [comment]
Merhaba,
Sizce bu durumda bir yanlışlık yok mu?
Dediğinize göre diyelim 15:30 da 15:20 den farklı fiyat olmadığından graph verilene bir şey işlenmedi,
15:40 da ise artış oldu ve graph verisi işlendi.
Yani ben bugünün 15:30 unda veri çekmeye kalktığımda o günün 15:30 unu değil 15:40 ındaki veriyi çekebilirim ve eğer 15:20 deki kapanış çektiğim verinin en düşüğü ise gelen verilerde göremediğim için ben yanlış bir hesaplama yaptırmış olmayacak mıyım?

**Comment by suleymanbyzt** [comment]
Merhaba,

15:20'den 15:30'a kadar hiçbir trade işlemi olmaması durumunda 15:20 saatindeki son fiyat baz alınacaktır.
15:30 saatine ait veriyi çekmek istediğinizde herhangi bir fiyat değişimi olmadığından son gerçekleşen trade işlemine göre fiyat bilgisi görüntülenecek.
