### ISSUE TITLE
API Always returns nothing

### ISSUE THREAD

**Issue by real1blue** [BTCTrader/broker-api-docs#435]
Hi;

I'm developing an application under VS 2015 (with FrameWork 4.6) after initializing with correct parameters any call returns nothing.
My APIKEY and APISECRET values are correct and I'm using https://api.btcturk.com/ as base URL

        Dim client As New BTCTrader.APIClient.ApiClient(APIKEY, APISECRET, BASE_URL)
        Dim t = client.GetTicker()

What am I missing or doing wrong?

Thanks in advance.

**Comment by suleymanbyzt** [comment]
Hi,

Can you share the status code of the error you received

**Comment by real1blue** [comment]
Dear Suleyman;

Basically no error message is given. But when I look at the Immediate Window I read "Received error. Status code: NotFound. Error message: Not Found" which doesn't lead to anything.

Before calling ApiClient I set the security protocol to TLS12, and my clock is sync I don't have any time diffrence with the server.

GetTicker does not require any authentication so I should be getting some data.

I also tried "broker-api-csharp-v2-master" example (https://codeload.github.com/BTCTrader/broker-api-csharp-v2/zip/refs/heads/master) . With this I am able to get data but I cannot get authorized.

So I am stuck here, can you help?
Thanks in advance.

**Comment by suleymanbyzt** [comment]
Hi,

You are getting 404 error.
This error is received when the endpoint is incorrect.
For the correct endpoints you can review our document by [clicking here.](https://docs.btcturk.com/)
You may also be having problems with your visual studio version. can you use the current version of visual studio?

For C# you must use this example => https://github.com/BTCTrader/broker-api-csharp-v2

To avoid authentication problems, you should check the accuracy of the public and private keys.
Send request from the IP you specified when creating the API

**Comment by real1blue** [comment]
Dear Suleyman;

As I said in my first message my end point and APIKEY / APISECRET values are correct. Also I have static IP and I used this IP when I generate the APIKEY. 

There are couple of sample codes and I tried all of it with no success. When I check the forums and complaints I see that a lot of people are complaining about authorization problem.

I am currently using VS 2015 and I don't think that my problem is related to VS version. Please tell  me which VS version you are using and successfully get authorized by BTCTurk.

Thank you for your support.

**Comment by suleymanbyzt** [comment]
Hi,

Thank you for your feedback.

Make sure the timestamp data is in **milliseconds (13 digits)** and the server time is the same as the API server time when authenticating.
Can you check the server time [here](https://api.btcturk.com/api/v2/server/time) and try again?

```cs
var apiKey = YOUR_API_PUBLIC_KEY;
var apiSecret = YOUR_API_SECRET;
var nonce = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeMilliSeconds();
string message = apiKey + nonce;
using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(apiSecret)))
{
   byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
   string X_Signature = Convert.ToBase64String(signatureBytes));
}
```

**Comment by real1blue** [comment]
Hi,

Here is the time info from my appliction's status bar:

![image](https://user-images.githubusercontent.com/22842596/152798957-abf629b5-9732-4c0b-9240-3c6d10d92a8f.png)

I didn't touch the sample application so it should run as it is.

**Comment by suleymanbyzt** [comment]
Hi,

2022-02-07   **13 : 38 : 59** => BtcTurk timestamp
2022-02-07   **01 : 38 : 59** => Your timestamp

There is a difference of -12 hours compared to the server time.
Your timestamp must be the same as the server time
If utc doesn't match you will recieve an authentication error.

Can you sync the timestamps and try again?

**Comment by real1blue** [comment]
Hi,

I checked my and also UTC time they are correct. The difference you are seeing is because of formatting. BTC is formatted 24 hour, mine is formatted  12 hours with AM/PM.

As you can see BTC time is 1644247140644 and mine is 1644247140832 which is less than 5 seconds apart.

![image](https://user-images.githubusercontent.com/22842596/152816617-0d0d212f-9e19-42e7-97bb-0c59b9eb202c.png)

I am sharing the response message I am getting : 

{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:  {    Connection: keep-alive    Pragma: no-cache    Cache-Control: no-store, must-revalidate, no-cache, max-age=0    Date: Mon, 07 Feb 2022 15:30:44 GMT    WWW-Authenticate: Bearer error="invalid_token"    WWW-Authenticate: Bearer error="invalid_token"    x-content-type-options: nosniff    x-frame-options: DENY    x-xss-protection: 1; mode=block    x-build-id: 34719    strict-transport-security: max-age=31536000; includeSubDomains; preload    CF-Cache-Status: BYPASS    Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"    Set-Cookie: __cfruid=77c7741429e430dfbb20cd528b6174302037b7aa-1644247844; path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None    Server: cloudflare    CF-RAY: 6d9da945194d5488-IST    Content-Length: 0  }}
    Content: {System.Net.Http.StreamContent}
    Headers: {Connection: keep-alive  Pragma: no-cache  Cache-Control: no-store, must-revalidate, no-cache, max-age=0  Date: Mon, 07 Feb 2022 15:30:44 GMT  WWW-Authenticate: Bearer error="invalid_token", Bearer error="invalid_token"  x-content-type-options: nosniff  x-frame-options: DENY  x-xss-protection: 1; mode=block  x-build-id: 34719  strict-transport-security: max-age=31536000; includeSubDomains; preload  CF-Cache-Status: BYPASS  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"  Set-Cookie: __cfruid=77c7741429e430dfbb20cd528b6174302037b7aa-1644247844; path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None  Server: cloudflare  CF-RAY: 6d9da945194d5488-IST  }
    IsSuccessStatusCode: False
    ReasonPhrase: "Unauthorized"
    RequestMessage: {Method: GET, RequestUri: 'https://api.btcturk.com/api/v2/users/balances', Version: 1.1, Content: <null>, Headers:  {    X-PCK: <<MY API KEY>>    X-Stamp: 1644247793708    X-Signature: /7sTaDUc4ig6hICeWWGTwXK9N5h0BDLXvBZrrJxA+Ls=    Authorization: Bearer /7sTaDUc4ig6hICeWWGTwXK9N5h0BDLXvBZrrJxA+Ls=    Cache-Control: no-cache    Accept: application/json  }}
    StatusCode: Unauthorized {401}
    Version: {1.1}

Thank you for your help

**Comment by suleymanbyzt** [comment]
Hi,

You need to use v1 version for `user/balances` .  For all private endpoints you should use v1
`https://api.btcturk.com/api/v1/users/balances`
That's why you're getting an error.
For more detailed information, you can review our document by [clicking here.](https://docs.btcturk.com/)
You should also check the api permissions. You need to grant permissions to avoid Invalid Token error

**Comment by real1blue** [comment]
I wish that was the problem but nothing changes. 

API key is created for my static IP and includes all the necessary permissions.

{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:  {    Connection: keep-alive    Pragma: no-cache    Cache-Control: no-store, must-revalidate, no-cache, max-age=0    Date: Tue, 08 Feb 2022 14:17:50 GMT    WWW-Authenticate: Bearer    WWW-Authenticate: Bearer    x-content-type-options: nosniff    x-frame-options: DENY    x-xss-protection: 1; mode=block    x-build-id: 34719    strict-transport-security: max-age=31536000; includeSubDomains; preload    CF-Cache-Status: BYPASS    Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"    Set-Cookie: __cfruid=b0b14988b073e500fc9d3b4875a6a6259ba0161e-1644329870; path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None    Server: cloudflare    CF-RAY: 6da57bdb1a6a92d2-IST    Content-Length: 0  }}
    Content: {System.Net.Http.StreamContent}
    Headers: {Connection: keep-alive  Pragma: no-cache  Cache-Control: no-store, must-revalidate, no-cache, max-age=0  Date: Tue, 08 Feb 2022 14:17:50 GMT  WWW-Authenticate: Bearer, Bearer  x-content-type-options: nosniff  x-frame-options: DENY  x-xss-protection: 1; mode=block  x-build-id: 34719  strict-transport-security: max-age=31536000; includeSubDomains; preload  CF-Cache-Status: BYPASS  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"  Set-Cookie: __cfruid=b0b14988b073e500fc9d3b4875a6a6259ba0161e-1644329870; path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None  Server: cloudflare  CF-RAY: 6da57bdb1a6a92d2-IST  }
    IsSuccessStatusCode: False
    ReasonPhrase: "Unauthorized"
    RequestMessage: {Method: GET, RequestUri: 'https://api.btcturk.com/api/v1/users/balances', Version: 1.1, Content: <null>, Headers:  {    X-PCK: <deleted>    X-Stamp: 1644329863720    X-Signature: <deleted>  }}
    StatusCode: Unauthorized {401}
    Version: {1.1}

**Comment by real1blue** [comment]
Dear Suleyman;

Thank you for your support. When I use VS 2017 instead of VS 2015 everything worked fine now.

I hope this thread will be very helpful for those who are having the authentication problem.

**Comment by suleymanbyzt** [comment]
Hi, 

I am very glad that the problem has been resolved. 💯
