### ISSUE TITLE
ÖNEMLİ | API işlemleri ile daha hızlı çalışabilmek adına sunucu lokasyonu bilgisi

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#437]
Merhabalar, API işlemlerinde düşük ms alabilmemiz için sunucu lokasyonu bilgisini ve servis sağlayıcıyı adını paylaşabilir misiniz?

**Comment by suleymanbyzt** [comment]
Merhaba,

Sunucu lokasyonumuz Amsterdam.
Azure West Europe ve Google Cloud Europe West’te sunucularımız çalışmakta.
Genellikle istekler Azure tarafına yönlendirilmektedir.

**Comment by aydinhus** [comment]
Merhaba,

Cloudflare'in bir etkisi var mı, ws verilerini dinlemek için en uygun lokasyon amsterdam / west eu mu? @suleymanbyzt

**Comment by yucelalbar** [comment]
@suleymanbyzt Bu konu benim de merak ettiğim bir konu. Bilgi verebilir misiniz?

**Comment by suleymanbyzt** [comment]
Selamlar,

Server'a Cloudflare proxy arkasından erişim sağlanmakta. Ws verilerini dinlemek için west eu lokasyonunu kullanabilirsiniz.
