### ISSUE TITLE
REFRESH TOKEN

### ISSUE THREAD

**Issue by emirhanyasin** [BTCTrader/broker-api-docs#438]
Merhabalar,

https://github.com/BTCTrader/broker-api-docs/issues/274 adresinde de bahsedildigi uzere, user data stream icin websockete 111 kodlu mesaj ve sso uzerinden alinan token ile login olduktan sonra, hesap uzerinden yapilan islemlerin datasi akmaya basliyor.

Ancak sso uzerinden aldigim token expire olmadan once, yeni token almak icin https://api.btcturk.com/api/v2/token/refresh endpointine bir onceki sefer sso'dan aldigim refreshToken'i post ettigimde Response403 aliyorum. 

Ornek: 
url = "https://www.btcturk.com/api/v2/token/refresh"
myobj = {"token": refresh_token}
x = requests.post(url, data = myobj)
print(x)

Ornekteki kod her seferinde Response 403 aliyor. Bu durumda ilk olarak siteden aldigim (sso.btcturk) token'i expire olmadan programatik olarak nasil refresh ederek yenisi ile degistirebilirim?

Tesekkurler

**Comment by emirhanyasin** [comment]
refresh_token requestini yukardaki url'e client uzerinden gonderdigimde de "Access denied | www.btcturk.com used Cloudflare to restrict access" hatasi aliyorum. Websockete login olmak icin gerekli olan token'i programatik olarak refresh etme metodunu anlatabilirseniz cok sevinirim. Adim adim neler yapilmali? 

Tesekkurler

**Comment by suleymanbyzt** [comment]
Selamlar,

SSO Login olduktan sonra token ve refresh token bilgilerini localStorage üzerinden alarak `/api/v2/token/refresh` endpoint üzerinden ortalama 45 dakika zaman ayarlı olacak şekilde request gönderebilir, token değerlerinizi güncelleyebilirsiniz.

Token ile ilgili sorunlar yaşıyorsanız dilerseniz websocket HMAC Authentication kullanabilirsiniz.

Python için kullanabileceğiniz WebSocket HMAC Authentication kod örneğini aşağıya bırakıyorum. Sadece public ve private key bilgilerinizi girerek authentication işlemini gerçekleştirip sorunsuz bir şekilde p kodlu mesajlar alabilirsiniz.

```python
import asyncio
import base64
import hashlib
import hmac
import json
import time
import websockets
class InterfaceWS:
    def __init__(self, exchange_name: str = None) -> None:
        self.exchange_name = "BTC Turk"
        self.uri = "wss://ws-feed-pro.btcturk.com/"

    async def authenticate_ws(self) -> bool:
        self.ws = await websockets.connect(self.uri)
        publicKey = "PUBLIC_KEY_HERE";
        privateKey = "PRIVATE_KEY_HERE";
        nonce = 3000
        print("\nnonce", nonce)
        baseString = "{}{}".format(publicKey, nonce).encode("utf-8")
        print("\nbaseString", baseString)
        signature = hmac.new(
            base64.b64decode(privateKey), baseString, hashlib.sha256
        ).digest()
        print("\nsignature", signature)
        signature = base64.b64encode(signature)
        print("\nsignature", signature)
        timestamp = round(time.time() * 1000)
        print("\ntimestamp", timestamp)
        hmacMessageObject = [
            114,
            {
                "nonce": nonce,
                "publicKey": publicKey,
                "signature": signature.decode("utf-8"),
                "timestamp": timestamp,
                "type": 114,
            },
        ]
        print("hmacMessageObject", hmacMessageObject)
        await self.ws.send(json.dumps(hmacMessageObject))
        while True:
            try:
                response = await asyncio.wait_for(self.ws.recv(), timeout=0.5)
                print("response after auth: ", response)
            except Exception as e:
                print(e)

async def main():
    w = InterfaceWS()
    await w.authenticate_ws()

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by emirhanyasin** [comment]
Merhaba Suleyman Bey,

SSO uzerinden login olup token'i aldiktan sonra 111 mesaji ile basarili bir sekilde websocket'e login oluyorum. Bu islemden sonra soylediginiz /api/v2/token/refresh endpointine gene SSO uzerinden login olarak aldigim refreshToken ile birlikte request attigimda ya bos donuyor, yada yukarida bahsettigim gibi "Access denied | [www.btcturk.com](http://www.btcturk.com/) used Cloudflare to restrict access" response aliyorum. Yeni token bilgilerim donmuyor kisacasi.
Bu sorunu nasil cozebilirim veya bahsettiginiz endpointe tam olarak hangi datayla ne sekilde request atmam gerekiyor?

HMAC ile login oldugumda 441 mesajlari akmiyor. HMAC ile login olduktan sonra 441 mesajlarini almanin bir yolu var midir?

Tesekkurler

**Comment by emirhanyasin** [comment]
@suleymanbyzt yorumda belirttigim soruyu cevaplayabilir misiniz lutfen. Neden dolayi bu hatayi aliyor olabilirim? Tam olarak nasil bir request gondermem gerekiyor yeni token'i alabilmek icin?

**Comment by emirhanyasin** [comment]
hep bu hatayi aliyorum:![image](https://user-images.githubusercontent.com/29901796/155285306-6c42a90b-be1c-4f18-9856-8d3298090a3d.jpeg)

**Comment by suleymanbyzt** [comment]
Merhaba,

#335 Issues altında token bilgisinin nasıl yenilenebileceği hakkında gerekli bilgilendirme kod örneği ile birlikte emreacar isimli kullanıcımız tarafından paylaşılmıştır.

Ayrıca HMAC Authentication işlemini gerçekleştirdikten sonra kanallardan mesajlar otomatik olarak gelecektir. Ekstra olarak bir kanala subs olmanıza gerek yok. 114 Kanalına login message başarılı bir şekilde gönderildikten sonra kanallardan mesajları sorunsuz bir şekilde alabilirsiniz.
