### ISSUE TITLE
websocket 111 model to log in 

### ISSUE THREAD

**Issue by ghost** [BTCTrader/broker-api-docs#439]
hi there, 

I couldnt find any details about ID and token for websocket 111 model. As document suggests below; 

_The id value of the user. Must be sent. The server checks for its equality with the value read from the Token. If you want to make a guest login notification, send 0 to this value. (Guest login notification is not mandatory in the system)_

_The current token value of the user from SSO. Null must be sent in guest notifications._

How can I get those two parameters, ID and token? Thank you.

**Comment by suleymanbyzt** [comment]
Hi,

After logging into our SSO site, you can access token information by following the steps 
F12 > Storage > Local Storage > btcUser.

**Comment by ghost** [comment]
> Hi,
> 
> After logging into our SSO site, you can access token information by following the steps F12 > Storage > Local Storage > btcUser.

Thanks for the quick response Suleyman. I managed to get token info details: idToken, refreshToken and token. Could you please confirm that which one I should be using?

Another thing I still cant find any info regarding user ID(number). Could you please provide details where i could get user ID parameter info?

Thank you.

**Comment by suleymanbyzt** [comment]
Hi,

userid is not a required field. Documentation will be updated soon.

You only need to send the type, username and token information.

If you are having problems with the token, you can use HMAC Authentication.

You can check our article [here](https://docs.btcturk.com/websocket-feed/protocol). Code sample for Python will be added soon.
