### ISSUE TITLE
btctrader-broker-btcturk.azurewebsites.net SMS verification step not working

### ISSUE THREAD

**Issue by onyedikilo** [BTCTrader/broker-api-docs#44]
Error: 
SMS mesajı gönderilemedi. Lütfen tekrar deneyiniz. Sorun devam ederse lütfen konuyu destek birimine bildiriniz.

Sent an email to support, here is their response:

Yardım masası olarak BTCTurk API ile ilgili teknik programlama desteği vermemekteyiz. Eğer programcı iseniz API yardım sayfamızdaki BTCTrader Github sayfasındaki linki kullanarak teknik ekibimizden Github
üzerinden destek isteyebilirsiniz.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
