### ISSUE TITLE
Account Balance İçin An API version is required, but was not specified hatası

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#440]
`https://api.btcturk.com/api/v1/users/balances` için `ApiVersionUnspecified` hatası geliyor. Detayları

```python
400, {'error': {'code': 'ApiVersionUnspecified', 'message': 'An API version is required, but was not specified.', 'innerError': None}})
```

**Comment by suleymanbyzt** [comment]
Merhaba,

Anlık bir problem yaşamış olabilirsiniz. Ben şu an test ettiğimde sorunsuz bir şekilde response alabiliyorum.

Sorun devam ediyor mu?

**Comment by yemreak** [comment]
Merhabalar, anlık bir sorun olabilir,  tekrarlanmadı.
