### ISSUE TITLE
"allOrders" endpoint parameter "orderId" not work for past orders

### ISSUE THREAD

**Issue by mentech** [BTCTrader/broker-api-docs#442]
Hello, I try to reach one of my past order but cant reach it from btcturk api endpoint allOrders with orderId. 

First I can get the order but when 25 orders passed from the order then it become unreachable.

Can you please fix it?

**Comment by suleymanbyzt** [comment]
Hi,

Thanks for your feedback

Development process started for querying with orderId

I'll let you know when development is complete.

**Comment by suleymanbyzt** [comment]
Hi,

You can use this endpoint to get more detailed information about the order.

{{url}}/api/v1/order/ORDERID_HERE

We'll update the API document soon.

Thanks for your feedback.
