### ISSUE TITLE
api al/sat komisyon oranları???

### ISSUE THREAD

**Issue by AlpandAlp** [BTCTrader/broker-api-docs#443]
Merhaba,

Konu ile ilgili BtcTurk destek bölümünü aradığıımızda api üzerinden yapılan işlem oranlarını bilmediklerini söyleyerek buraya yönlendiriyorlar.
Sitede ise api komisyon oranları da gözükmemekte. 

api üzerinden yapılan al/sat larda güncel komisyon oranları ve seviyeleri nedir? 

teşekkürler, iyi çalışmalar....

**Comment by suleymanbyzt** [comment]
Merhaba,

https://pro.btcturk.com/yardim/komisyonlar üzerinden komisyon oranları inceleyebilirsiniz.
