### ISSUE TITLE
Bot oluşturup otomatik al sat yapma

### ISSUE THREAD

**Issue by sinankilinc** [BTCTrader/broker-api-docs#444]
Merhaba..Ekrana bakacak vaktim olmadığından , bot oluşturup kripto piyasında 50000 tl ile otomatik al-sat yapma niyetindeyim..Konuyla ilgili temel bilgilere sahibim. İnternette botla ilgili dökümanlarınızı ve başka kaynaklardan ilgili dökümanları okudum..
Ama halen cevabını bulamadığım sorular var..Soracağım sorular , yeni sorulara vesile olacağından bu forumdan sorularımı yazmıyorum.

BTCTurk den bot kurup aktif olarak kullanan birinin beni aramasını rica ederim..

**Comment by suleymanbyzt** [comment]
Merhaba,

Güvenliğiniz adına API Key bilgilerinizi farklı kişiler ile paylaşmamanızı rica ederiz.

https://docs.btcturk.com/ dökümanımızı bu linkten inceleyebilirsiniz.

Konuyla alakalı sorularınızı bu issues altında iletebilirsiniz.

**Comment by sinankilinc** [comment]
Anladığım kadarıyla bot u aktif kullanan bilen  kimse yok btcturkte..

İyi günler..

14 Mar 2022 Pzt 09:47 tarihinde Süleyman Bayazit ***@***.***>
şunu yazdı:
