### ISSUE TITLE
API çalışmıyor

### ISSUE THREAD

**Issue by MasherCoder** [BTCTrader/broker-api-docs#445]
https://docs.btcturk.com/private-endpoints/account-balance adresinizde bulunan kod ile Hesap bakiyesi çekmeye çalışıyorum ancak kendi API adresimle çekemiyorum. Aynı koda başkasının API adresini ekliyorum çalışıyor.
2 API arasında yetki olarak veya IP adresi olarak hiçbir fark yok.
Bu problemi nasıl düzeltebilirim?

**Comment by suleymanbyzt** [comment]
Merhaba,

Yeni bir api key oluşturup tüm yetkileri verdikten sonra işlemi tekrar deneyebilir misiniz?

401 hatası alıyorsanız vermiş olduğunuz ip adresiniz, api key bilginiz, api key izniniz ya da server time ile local time bilgilerinizin eşleşmemesi gibi sorunlar nedeniyle bu hatayı alabilirsiniz. 

İşlemi tekrar deneyip almış olduğunuz hata ile ilgili error code iletmeniz durumunda size daha sağlıklı yönlendirme yapabilirim.
