### ISSUE TITLE
Readtimeout, API emir işlemlerinde 2s'den fazla gecikme söz konusu

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#446]
Emirleri verdiğimizde işlenmesi 2s'den uzun sürebiliyor. Bu da işlem gerçekleşene kadar piyasanın değişmesine sebeb oluyor ve mali zarara uğruyoruz. 

Zaman aşımını çözmek için neler önerirsiniz veya geliştirme yapacak mısınız?

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz. Anlık bir sorun yaşamış olabilirsiniz. Altyapılarımızla ilgili gerekli çalışmalar kullanıcılarımızın en iyi hizmeti alabilmesi adına devam etmektedir.

Genel bir sorun yaşamanız halinde bu issuess altında bilgilendirme yapabilirsiniz.
