### ISSUE TITLE
StopMarket 400 BadRequest hatası hk.

### ISSUE THREAD

**Issue by idmrbs** [BTCTrader/broker-api-docs#447]
Merhaba,
Limit olarak girdiğim emirlerde hata almazken, StopMarket ve StopLimit emirlerinde hata almaktayım.
kod:
var order = new OrderInput
                {
                    NewOrderClientId = "TEST",
                    OrderMethod = OrderMethod.StopMarket,
                    OrderType = OrderType.Sell,
                    PairSymbol = "BTCTRY",
                    StopPrice = 606505M,
                    //Price = 606505M,
                    Quantity = 0.00018065M
                };
apiClientV1.CreateOrder(order)

dönen hata : {Code 400: , Message : BadRequest}
proje:broker-api-csharp-v2 projesinin üzerine geliştirildi.

**Comment by suleymanbyzt** [comment]
Merhaba,

Aldığınız hata geçersiz parametre yollamaya çalıştığınızda alınmakta.

types bilgilerini ya da parametre bilgilerinizi kontrol edebilir misiniz?

Php ve Python üzerinden yaptığım testlere ait parametre değerlerini iletiyorum.

`$post_data = "{ 'quantity' : '0.12345678','stopPrice' : 20000, newOrderClientId: 'BtcTurk API PHPClient', 'orderMethod':'stopmarket', 'orderType':'sell', 'pairSymbol':'BTCTRY' }";
`

```
params=\
    {
    "quantity": 1,
    "stopPrice": 20000,
    "newOrderClientId":"BtcTurk Python API Test",
    "orderMethod":"stopmarket",
    "orderType":"sell",
    "pairSymbol":"BTCTRY"
    }
```

```json
{
  "httpStatusCode": 200,
  "data": {
    "id": xxxx,
    "quantity": "1",
    "price": "20000.00",
    "stopPrice": "20000",
    "newOrderClientId": "Test",
    "type": "sell",
    "method": "stopmarket",
    "pairSymbol": "BTCTRY",
    "pairSymbolNormalized": "BTC_TRY",
    "datetime": 1647883128462
  },
  "success": true,
  "message": "SUCCESS",
  "code": 0
}

```

**Comment by idmrbs** [comment]
Merhaba geri dönüşünüz için teşekkürler.
Gönderdiğim data aşağıdaki gibi sizinki ile fark göremedim ama yinede hata almakta.
`{"Quantity":0.00196000,"Price":0.0,"StopPrice":604560.0,"NewOrderClientId":"2deae7a2-14cf-416e-b2e3-6d790968cccc","OrderMethod":"stopmarket","OrderType":"sell","PairSymbol":"BTCTRY"}`

Benzer şekilde gönderdiğim aşağıdaki data hata vermeden emir defterine giriş yapmakta.
`{"Quantity":0.00196000,"Price":609990.0,"StopPrice":609990.0,"NewOrderClientId":"2deae7a2-14cf-416e-b2e3-6d790968cccc","OrderMethod":"limit","OrderType":"sell","PairSymbol":"BTCTRY"}`
