### ISSUE TITLE
/api/v2 endpointlerine api/secret key ile erisim 

### ISSUE THREAD

**Issue by ramazanseyhan** [BTCTrader/broker-api-docs#448]
/api/v2 uzerinde calisan order endpointlerini botumda kullanmak istiyorum. Bunlara sadece client uzerinden mi erisime izin veriyorsunuz yoksa api/secret key ile de erisebiliyor muyuz ? Dokuamantasyonda sadece v1 icin authentication ornegi eklemissiniz bu yuzden yeterli bilgiyi goremedim.

**Comment by suleymanbyzt** [comment]
Merhaba,

v2 endpointleri için herhangi bir authentication yapmanıza gerek yok.

Public endpointlere api key bilgisi olmadan direkt erişim sağlanabilir.

Public endpointler üzerinden yapacağınız işlemlerde rate limitler IP bazlı aktif olmakta. Konu hakkında daha detaylı bilgi için [buraya](https://docs.btcturk.com/rate-limits) tıklayarak rate limitleri inceleyebilirsiniz.

**Comment by yucelalbar** [comment]
@suleymanbyzt @ramazanseyhan'ın sorusu daha çok `/api/v2` **Private** endpointlere API üzerinden erişim ile alakalı. Browser'dan emir gönderildiğinde `/api/v2` kullanılıyor. `/api/v2` private endpointlere API üzerinden de erişmek mümkün mü? Mümkünse kullanım örneği nasıldır?

**Comment by serensoner** [comment]
merhaba @suleymanbyzt, ben de ayni seyi merak ediyorum. bircok gerekli endpoint (ornegin deposit addresslerini api ile ogrenmek istiyorsak https://api.btcturk.com/api/v2/deposits/crypto/ endpoint'ini kullanmamiz gerekiyor, fakat kullanamiyoruz. bu konu acaba yol haritanizda var mi?

**Comment by suleymanbyzt** [comment]
Selamlar,

Yakın zamanda kullanımda olan ama dökümana henüz eklenmemiş endpointler için çalışma yapılacak.

Geliştirme tamamlandığında sizlere buradan bilgilendirme yapacağım.

Geri bildirimleriniz için teşekkür ederiz.
