### ISSUE TITLE
OrderMethod : StopMarket  Bad Request hatası 

### ISSUE THREAD

**Issue by idmrbs** [BTCTrader/broker-api-docs#449]
Merhaba,
Limit olarak gönderdiğim emirler deftere eklenirken stopmarket olarak gönderdiğim emirler deftere eklenmemekte, bad request hatası dönmekte.

StopMarket için gönderdiğim data :
`{"Quantity":0.00196000,"Price":0.0,"StopPrice":604560.0,"NewOrderClientId":"2deae7a2-14cf-416e-b2e3-6d790968cccc","OrderMethod":"stopmarket","OrderType":"sell","PairSymbol":"BTCTRY"}`

Limit için gönderdiğim data :
`{"Quantity":0.00196000,"Price":609990.0,"StopPrice":609990.0,"NewOrderClientId":"2deae7a2-14cf-416e-b2e3-6d790968cccc","OrderMethod":"limit","OrderType":"sell","PairSymbol":"BTCTRY"}`

**Comment by suleymanbyzt** [comment]
Selamlar,

APIClient.Models.OrderInput model için StopPrice string olarak belirlemenizi rica ederiz.

```csharp
 public string StopPrice { get; set; }

            var stopMarket = new OrderInput
            {
                Quantity = 0.0003m,
                NewOrderClientId = "stop market",
                OrderMethod = OrderMethod.StopMarket,
                OrderType = OrderType.Sell,
                StopPrice = "600000", //string
                PairSymbol = "BTCTRY"
            };
```

Bu şekilde query göndererek stop market için işlemlerinize devam edebilirsiniz.
