### ISSUE TITLE
userTransactions

### ISSUE THREAD

**Issue by sylow** [BTCTrader/broker-api-docs#45]
Merhabalar,

balance i gorebilirken ayni methodu kullanan userTransactions alttaki cevapla karsilasiyor;

{"code"=>401, "message"=>"Unauthorized - Invalid Public key"}

Debug ettigimde karsima cikan redirect komutu.
-> "Location: https://www.btcturk.com/Account/Login?ReturnUrl=%2Fapi%2FuserTransactions\r\n"

**Comment by mzgs** [comment]
PHP kullaniyorsan request konusunda sıkıntılı. Python ya da C# kullanirsan sorun olmuyor.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
