### ISSUE TITLE
READ TIME OUT ERROR

### ISSUE THREAD

**Issue by emirhanyasin** [BTCTrader/broker-api-docs#450]
Emir atarken ust uste su hatayi aliyorum:

HTTPSConnectionPool(host='api.btcturk.com' port=443): Read timed out. (read timeout=None)

Bu hatayi almamin sebebi nedir? Attigim requestlerin responselari bana donemiyor mu? Hatanin kaynagi ve cozum yolu onerilerinizi bekliyorum.

Tesekkurler

**Comment by suleymanbyzt** [comment]
Selamlar,

Bu sorun bazı durumlarda sunucu kaynaklı anlık olarak yaşanabilmekte. Sorunun nedeni iletilen istek için belirlediğiniz zaman aşımı süresi içerisinde sunucudan yanıt dönmemesi durumunda read timeout hatası alınır. Devamlı olarak her isteğinizde aynı hatayı alıyorsanız daha yüksek bir zaman aşımı ayarlamanız gerekir.

**Comment by emirhanyasin** [comment]
Tesekkurler
