### ISSUE TITLE
güncel ohlcv data dahil geçmiş ohlcv datayı excele çekmek

### ISSUE THREAD

**Issue by fethifikret** [BTCTrader/broker-api-docs#451]
bitiş zaman damgası kullanmadan güncel ohlcv datadan geriye doğru 100,200,1000 vs datayı çekmek istiyorum. bunu otomatik her 60 dakikada bir almak istiyorum. dolayısıyla her veri güncelleme öncesi başlangıç zaman damgası ve bitiş zaman damgası ayarlamakla uğraşmadan ohlcv verisini excele nasıl çekebilirim

**Comment by suleymanbyzt** [comment]
Selamlar,

`to` parametresi gerekli alan olduğundan ilgili parametreyi kullanmadan istek göndermeniz mümkün değil. Söylediğiniz durum için `to` parametresine otomatik olarak güncel tarihi atabilmeniz için DateTime.UtcNow kullanıp timestamp convert ederek otomatik olarak güncel tarih ile istek atabilirsiniz.  `from` parametresi için de aynı sistemi kullanabilirsiniz. Örnek olarak son 60 dakikaya ait verileri çekmek istiyorsanız ` DateTime.UtcNow.AddMinutes(-60)` gibi bir düzenleme yaparak son 60 dakikaya ait ohlcv datayı çekebilirsiniz.

**Comment by fethifikret** [comment]
[ALSAT SEÇİM.xlsx](https://github.com/BTCTrader/broker-api-docs/files/8428967/ALSAT.SECIM.xlsx)
Selamlar,
Söylediğiniz yöntemi ekli dosyada nasıl kurabilirim.
