### ISSUE TITLE
Need 453 OrderUpdate Model or `numLeft` or `status` of order in Model 441

### ISSUE THREAD

**Issue by s13rw81** [BTCTrader/broker-api-docs#452]
Greetings,

I am not receiving the [453 OrderUpdate Model](https://docs.btcturk.com/websocket-feed/models#channel-453-orderupdate).

Kindly start sending `543 OrderUpdate` Model or kindly add `numLeft` to `441 UserOrderMatch` Model.

Kindly read explaination below.

This is about the [441, UserOrderMatch Model](https://docs.btcturk.com/websocket-feed/models#channel-441-userordermatch).

When we receive the 441 Model from server, we get only `amount` filled in that trade,
![image](https://user-images.githubusercontent.com/40073844/161990162-94683c57-33c3-44a2-ae6f-3dd388dad12d.png)

451 Model
```
[451,{"type":451,"pairId":62,"symbol":"DOTUSDT","id":7968322274,"method":0,"userId":343234,"orderType":1,"price":"20.97","amount":"1","numLeft":"1","denomLeft":"20.9679029999999992","newOrderClientId":"e3670027-694c-4318-abb8-74112b3bfe7c"}]
```

441 Model

```
[441,{"type":441,"id":7968322274,"user":343234,"isBid":false,"method":0,"pair":62,"symbol":"DOTUSDT","amount":"0.6393864025","price":"20.9700000000","clientId":"e3670027-694c-4318-abb8-74112b3bfe7c"}]
[441,{"type":441,"id":7968322274,"user":343234,"isBid":false,"method":0,"pair":62,"symbol":"DOTUSDT","amount":"0.3606135975","price":"20.9700000000","clientId":"e3670027-694c-4318-abb8-74112b3bfe7c"}]
```

- However, since, there is no `numLeft` key in the data, it is difficult to understand if the order is `completed` or still `open`.
- There is also, no `status` key which could give us the status of the order.
- This is leaving a lot of open orders in the system waiting for its fills to complete.
- Also if a 441 message is **lost in transit**, we would be calculating an incorrect fill amount on our end and as a result be placing order with incorrect quantity.
----
I would therefore request you to kindly add `numLeft` key to the data in 441 Model so that we can know for sure if the order is completed and/or how much of the order amount is filled.

Thank you in advance.

**Comment by suleymanbyzt** [comment]
Hi @s13rw81,

I will forward your suggestion to our team. I'll let you know when development is done for the 441 model.

Also thank you for your feedback.

Best Regards

**Comment by s13rw81** [comment]
It would be great if 441 OrderMatch Model has the following values,
- `amount`: the amount of the order
- `total_filled` : total amount filled so far of this order
- `numLeft` : amount remaining to be filled
- `status`  : status of the order, ( open, partially filled, closed, canceled ) *optional*

I am requesting for `total_filled` so that we do not miss any fills to network issues. Some messages can get lost in transit.
Example. If order amount is 5000 and we have several trades such as 5 + (5) + 5 + 5 + 5 + 5, then
total_filled = 30, however if one of these trades is lost in transit, then our total amount filled will be calculated wrongly.

`numLeft` will help us understand if there is any amount yet to be filled, if `numLeft` is 0 then we can mark the order as closed.

It would be great if these could be accommodated into the 441 OrderMatch model.

Thank you
