### ISSUE TITLE
Ping command for websocket connections

### ISSUE THREAD

**Issue by ronitovi** [BTCTrader/broker-api-docs#453]
Hello,

despite of all my searchings on the docs, I could not find any method for measuring the delay of a websocket connection.

I would like to know if is there any PING method that is not demonstrated on the docs, maybe ?

A method like this could (and should) be added as they are already present for all of the well-known exchanges.

```
[
	XXX, (ping model code) 
	{
		"data": some epoch ticks, #number
	}
]
```

And the response payload would be:

```
[
	XXX,
	{
		"data": same epoch requested
	}
]
```

This way we could have known  at least an approximate ping between the server and our client.

**Comment by suleymanbyzt** [comment]
Hi,

Currently there is no such channel for websocket. I will forward your suggestion to our team. 

This service is available on the v2 endpoint.
`/api/v2/server/ping
`
Best regards

**Comment by ronitovi** [comment]
Thank you for your interest, since the speed is extremely important at spot trading, we (as developers) should always keep an eye on the delay on the socket that we are receiving the orderbooks, which matters most. Any possible connection issue at any time, if not watched properly, could lead a miscalculation and loss, this is why a PING method from client to server should also be implemented in my opinion. Again, thank you very much.

I'll be looking forward to see if any updates.
Best regards
