### ISSUE TITLE
Emir işlemlerinde 2s'den daha uzun süreli gecikmeler ve bazen işlem iptali söz konusu

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#455]
Sürekli hareket halinde olan piyasada bu tarz gecikmelerin olmasından kaynaklı emirleri bizden önce başkaları alıyor ve bu da bizi potansiyel olarak zarara sokuyor.

Çözüm öneriniz veya çalışmanız var mı?

**Comment by suleymanbyzt** [comment]
Merhaba,

Geri bildiriminiz için teşekkür ederiz. Yaşadığınız durum anlık bir erişim problemi nedeniyle yaşanmış olabilir. Sizlerin daha iyi hizmet alabilmesi adına sistemlerimizde her geçen gün gerekli iyileştirme çalışmaları yapılmaktadır.

Konu ile ilgili gelişmeler olduğunda size bu issues altında bilgilendirme yapacağım.
