### ISSUE TITLE
HMAC Authentication'ın tek seferlik yapılması yeterli mi?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#456]
Web socket bağlantısı aktif olduğu sürece tekrardan authentication yapmaya gerek var mı, yoksa bağlantı sonlanana kadar devam ediyor mu?

- Token ile giriş hususunda periyodik olarak token yenilemesi gerekmekteydi, WS için de yenileme yapmamız gerekiyor mu?

**Comment by suleymanbyzt** [comment]
Selamlar,

HMAC WS Authentication ile bağlantı kurduğunuzda siz bağlantıyı sonlandırana kadar tekrar authencation yapmanıza gerek kalmayacaktır. 

API Key ile bağlantı kurulduğundan belirlediğiniz IP bilgisinden istek geldiği sürece sorunsuz bir şekilde bağlantı sağlayabilirsiniz.
