### ISSUE TITLE
Orderbook stream verilerinin alınması

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#457]
* Tüm orderbook streamlerin abone olunduğu zaman verilerde karmaşa oluyor
* Her birini tek bir seferde alabilme şansımız var mı?
* Veya her birinin en güncel halinin geldiğini anlama şansımız var mı?
   * ÖRN: BTCTRY için güncel veri geldiği zaman XRPTRY için güncel veri gelmemiş oluyor, 30ms sonra geliyor
   * BTCTRY'ın güncel olduğu anda XRPTRY güncel olmuyor

Belirli bir anda TÜM pair (134tane) verilerin güncel olmasını nasıl sağlayabiliriz? Ya da tüm (134 tane) verilerin bir anda verildiği bir kanalınız var mı?

**Comment by suleymanbyzt** [comment]
Selamlar,

Orderbook ws için tüm pairleri bir anda çekebileceğiniz bir yapı şu an için yok. Konu hakkında ben önerinizi ilgili ekiplerimize ileteceğim. 

Event all gibi bir yapı kurulması durumunda da size bu issuess altında bilgilendirme yapacağım.

İyi günler dilerim.

**Comment by yemreak** [comment]
Selamlar,

- Event all gibi bir yapının kurulması hususunda bir ilerleme söz konusu mu?
- Veya başka bir veri alım tekniği önerebilir misiniz?

@[suleymanbyzt](https://github.com/suleymanbyzt)

**Comment by suleymanbyzt** [comment]
Selamlar,

İlgili öneriyi ekiplerimize ilettim. Geliştirmenin yapılmasına karar verilmesi durumunda bu issues altında size özel olarak bilgilendirme yapacağım.
