### ISSUE TITLE
WS orderbook kanalında veriler hangi sıklıkla geliyor

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#458]
- Orderbook verileri eskiden her 1s içinde bir geliyordu şu anda ne durumda?
- Bazı durumlarda BTCTRY verileri 30ms aralıklarla da gelebiliyor (sondaki 3 digit önceki veri ile arasındaki MS farkını gösteriyor)
![Screen Shot 2022-04-26 at 16 48 45](https://user-images.githubusercontent.com/49655146/165315332-9052a444-d8e8-4a0a-b3ef-1f82e2f7b8a8.png)

ARtık veriler her güncelleme olduğunda canlı olarak WS kanallarından aktarılıyor mu?

**Comment by suleymanbyzt** [comment]
Selamlar,

Orderbook için veriler genelde 100 ms altında iletilir.  Verilerde güncelleme olması durumunda kanaldan mesaj direkt iletilecektir.
