### ISSUE TITLE
Orderbook verileri güncel değil

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#459]
`FETTRY` için WS `orderbookfull` ve `trade` kanallarına abone oldum. 

- Lakin `orderbook` içerisinde yer almayan emir fiyatıyla `trade` bilgisi geliyor.
- `orderbook` içerisinde yer almayan bir emrin `trade`'i olmayacağına göre `orderbook` güncel emirleri göstermiyor
- Bu koşulda en doğru veriyi alma algoritması nasıl olmalıdır? `trade` kanalı mı yoksa `orderbook` kanalı mı daha güncel?

Bilgi amacıyla log bilgilerimi sizlerle paylaşıyorum

<img width="1207" alt="Screen Shot 2022-05-03 at 23 21 18" src="https://user-images.githubusercontent.com/49655146/166559897-70f9adf6-1c08-4078-9efc-d544e41f999f.png">

**Comment by suleymanbyzt** [comment]
Selamlar,

Orderbook ve trade kanallarına sync olarak bağlanabilme gibi geliştirmemiz olmadığından ilgili verileri inmemory yazdıktan sonra ekrana yazdırabildiğiniz için çok az da olsa gecikmeli olacak şekilde verileri alabilmeniz olağan görünüyor.

Örnek olarak orderbook verileri inmemory alındığı anda trade ws için ilgili verinin alınabilmesi için orderbook işlemini bitirmesi gerektiği için farklılıklar görebilirsiniz.

Bu durumun çözümü için ben geliştirme önerisini ilgili ekibimize ileteceğim. Trade gerçekleştiği anda ilk 5 orderbook verisinin de sync bir şekilde alabilmenizi sağlayan yeni bir ws kanalının bu durumu çözebileceğine inanıyorum.

Geri bildiriminiz için teşekkürler.
