### ISSUE TITLE
Open orders isteklerine response olarak Null cevap gelmesi

### ISSUE THREAD

**Issue by omercanvural** [BTCTrader/broker-api-docs#460]
Yazdığımız uygulama emir verdikten sonra ilgili pariteye ait emir ve bakiye durumunu takip etmek için saniyede bir açık emir listesi için istek gönderiyor.

Aşağı daki örnekte gönderilen 3 isteğin zamanları ve cevap içeriiklerinin boş olup olmadığına dair kayıtlar yer almaktadır. İsteklerimizin büyük çoğunluğu çok kısa sürelerde ve içeriği doğru olarak cevaplanmaktadır.

Ancak 2 istekte görüldüğü gibi bazı isteklere cevaplar 30 saniye gibi geciken süreler de ve boş gelmekte. Bu durum seyrek oluşmakla beraber aktif işlemlerimizi olumsu etkilemekte. Neden kaynaklandığına ya da nasıl çözülebileceğine dair destek olabililr misiniz?

GetOpenOrders request time : 5/9/2022 11:45:25 PM
request uri : api/v1/openOrders?pairSymbol=
response  is null : False
response time : 5/9/2022 11:45:25 PM response response status code OK and response  success : True 

GetBalances request time : 5/9/2022 11:45:26 PM
request uri : api/v1/users/balances
response  is null : True
response time : 5/9/2022 11:45:57 PM response response status code null  and response  success :  null

GetBalances request time : 5/9/2022 11:45:58 PM
request uri : api/v1/users/balances
response  is null : False
response time : 5/9/2022 11:45:59 PM response response status code OK and response  success : True

**Comment by suleymanbyzt** [comment]
Selamlar,

Yaşadığınız durum internetinizde oluşabilecek anlık sorunlar nedeniyle yaşanmış olabilir. Server'dan herhangi bir yanıt dönmediği için isteğin ilgili aralıkta hiç iletilmeme gibi bir durum söz konusu olabilir. Çözüm önerisi olarak isteklerinize timeout süresi ekleyebilirsiniz. Örnek olarak 5 saniye boyunca server'dan yanıt alamadığınız durumlarda isteği timeout çekerek yeni bir istek oluşturabilirsiniz.
