### ISSUE TITLE
ORDER_INSERT_BLOCKED 

### ISSUE THREAD

**Issue by makuma07** [BTCTrader/broker-api-docs#461]
ORDER_INSERT_BLOCKED  hatası alıyorum.

**Comment by suleymanbyzt** [comment]
Selamlar,

LUNAUSDT ve LUNATRY için api emir girişi şu an için durduruldu. Terra blokzincirindeki istikrarsızlık nedeniyle API kullanılarak yapılan alım satım emir girişleri ve yatırma çekme işlemleri kullanıcılarımızın işlem güvenliğini göz önünde bulundurarak kapatılmıştır.

Gelişmeleri https://status.btcturk.com/ sayfamızdan takip edebilirsiniz.

**Comment by makuma07** [comment]
Luna haricinde de alım yapamıyorum

**Comment by makuma07** [comment]
ADA almaya çalışıyorum onda da aynı hata ile karşılaşıyorum

**Comment by makuma07** [comment]
https://status.btcturk.com/ adresinde API'LERDE büyük kesinti yazıyor.

**Comment by suleymanbyzt** [comment]
Selamlar,

Söz konusu kesinti sadece LUNATRY ve LUNAUSDT için var. ADATRY için az önce emir girişi yaptım api üzerinden ve herhangi bir sorunla karşılaşmadım. Vermiş olduğunuz emrin LUNATRY veya LUNAUSDT olmadığından emin olunuz.

```
{
  "httpStatusCode": 200,
  "data": {
    "id": 8688903496,
    "quantity": "13.5",
    "price": "8.000",
    "stopPrice": null,
    "newOrderClientId": "BtcTurk TEST",
    "type": "buy",
    "method": "limit",
    "pairSymbol": "ADATRY",
    "pairSymbolNormalized": "ADA_TRY",
    "datetime": 1652447464825
  },
  "success": true,
  "message": "SUCCESS",
  "code": 0
}
```

**Comment by makuma07** [comment]
birçok şeyi denedim aynı hayatı alıyorum. acaba benim API de veya hesabımda sorun olabilir mi?

**Comment by makuma07** [comment]
daha sabah çalışıyordu ve hiçbirşeyi değiştirmedim.

**Comment by serensoner** [comment]
merhaba, belki hesaba bagli birseydir ama ben simdi USDT_TRY pair'inde denedim ve bir sorun yasamiyorum.

**Comment by makuma07** [comment]
peki hesabımla ilgili sorun oldugunu nasıl öğrenebilirim. canlı destek'den buraya yönlendirdiler?

**Comment by suleymanbyzt** [comment]
@makuma07 rica etsem hesabınıza tanımlı e-posta adresinizi suleyman.bayazit@btctrader.com 'a iletebilir misiniz. İnceleyelim

**Comment by makuma07** [comment]
> @makuma07 rica etsem hesabınıza tanımlı e-posta adresinizi [suleyman.bayazit@btctrader.com](mailto:suleyman.bayazit@btctrader.com) 'a iletebilir misiniz. İnceleyelim

gönderdim hocam

**Comment by suleymanbyzt** [comment]
İnceleme tamamlandığında haber vereceğim 👍

**Comment by makuma07** [comment]
> İnceleme tamamlandığında haber vereceğim 👍

teşekkür ederim kolay gelsin

**Comment by suleymanbyzt** [comment]
@makuma07 ilgili işlem çiftinde tekrar emir vermeyi deneyebilir misiniz? İşlem sonrası geri bildirimde bulunmanızı rica edeceğim.

**Comment by makuma07** [comment]
> @makuma07 ilgili işlem çiftinde tekrar emir vermeyi deneyebilir misiniz? İşlem sonrası geri bildirimde bulunmanızı rica edeceğim.

hala aynı hatayı alıyorum hocam :(

**Comment by suleymanbyzt** [comment]
@makuma07 işleminizle alakalı ilgili birimlerimize tekrardan bir  bilgilendirme yaptım. Konu ile ilgili bir gelişme olduğunda bu issuess altında size bilgilendirme yapacağım.

**Comment by suleymanbyzt** [comment]
Selamlar,

@makuma07  sorun hala devam ediyor mu ? İşlemlerinizi incelediğimizde herhangi bir engelinizin bulunmadığını tespit ettik. 

Geri bildirimde bulunmanızı rica edeceğim.
