### ISSUE TITLE
WebSocket'e HMAC kulanarak bağlanmak

### ISSUE THREAD

**Issue by bymulker** [BTCTrader/broker-api-docs#462]
Mernhaba,

Sitenizin https://docs.btcturk.com/websocket-feed/authentication sayfasındaki 'HmacTest' (C# .net core 3.1) kodunu çalıştırdığımda, 
`[114,{"type":114,"ok":false,"id":0,"message":"Unauthorized - Invalid Public key"}]`
cevabı alıyorum. API keyimde gerekli tüm izinler bulunuyor. Acaba birşeyi atlıyor muyum?

**Comment by suleymanbyzt** [comment]
Selamlar,
401 hatası için birçok sebebi olabilir. Bunlardan en sık karşılaşılanları aşağıya madde halinde sıralayacağım. 
- API key oluştururken verilen IP bilgisi ile güncel IP bilgisinin uyuşmazlığı.
- Local time ile server time bilgisinin uyuşmazlığı
- Visual studio sürümünün, 2017 sürümünden düşük olması.

İlk olarak bu 3 maddede gerekli incelemelerinizi yapmanızı rica edeceğim. Server time için https://api.btcturk.com/api/v2/server/time endpoint kullanabilirsiniz. Sürüm için ise vs 2017 ve üstü kullanıp sdk 5.0 veya üstü olacak şekilde ayarlayabilirsiniz.

Sorunla ilgili daha fazla detaya FAQ sayfamızdan ulaşabilirsiniz.
https://docs.btcturk.com/faq-frequently-asked-questions

Burada 401 hatası ile ilgili daha fazla detaya erişebilirsiniz.

**Comment by bymulker** [comment]
Merhaba, 

Hızlı dönüşünüz için teşekkür ederim. 

IP bilgisini kontrol ettim. Sorun görünmüyor. 
nonce = ToUnixTime(DateTime.UtcNow), olarak kontrol ettim, https://api.btcturk.com/api/v2/server/time ile birebir uyuşuyor.
VS sürümüm : 2019  Community Edition Version 16.11.14
.NET SDK : 5.0

Ekteki dosyaları bir konsol programına ekleyip aşağıdaki kodla cevabı dinlemeye çalıştım. 
SocketClient ReceiveBufferSize = 8192 olarak denedim ancak başarılı olamadım.

Çalışan bir örnek çok makule geçecek 😊

static async Task Main(string[] args)
        {
            string publicKey = "…";
            string privateKey = "…";

            BtcTurkSocketClient btcTurkWS = new BtcTurkSocketClient(publicKey, privateKey);

            await btcTurkWS.ConnectAsync();

            await btcTurkWS.HmacTest();


            //Console.WriteLine("Hello World!");
        }

Teşekkürler,

Windows 10 için Posta ile gönderildi

Kimden: Süleyman Bayazit
Gönderilme: 14 Mayıs 2022 Cumartesi 17:19
Kime: BTCTrader/broker-api-docs
Bilgi: bymulker; Author
Konu: Re: [BTCTrader/broker-api-docs] WebSocket'e HMAC kulanarak bağlanmak (Issue #462)

Selamlar,
401 hatası için birçok sebebi olabilir. Bunlardan en sık karşılaşılanları aşağıya madde halinde sıralayacağım.
• API key oluştururken verilen IP bilgisi ile güncel IP bilgisinin uyuşmazlığı.
• Local time ile server time bilgisinin uyuşmazlığı
• Visual studio sürümünün, 2017 sürümünden düşük olması.
İlk olarak bu 3 maddede gerekli incelemelerinizi yapmanızı rica edeceğim. Server time için https://api.btcturk.com/api/v2/server/time endpoint kullanabilirsiniz. Sürüm için ise vs 2017 ve üstü kullanıp sdk 5.0 veya üstü olacak şekilde ayarlayabilirsiniz.
Sorunla ilgili daha fazla detaya FAQ sayfamızdan ulaşabilirsiniz.
https://docs.btcturk.com/faq-frequently-asked-questions
Burada 401 hatası ile ilgili daha fazla detaya erişebilirsiniz.

**Comment by bymulker** [comment]
Ayrıca ben 401 hatası demedim :)

**Comment by suleymanbyzt** [comment]
Selamlar,

Unauthorized - Invalid Public key hatası 401 hatası oluyor bu nedenle 401 hatası olarak bilgilendirme yaptım.


```csharp
static async Task Main(string[] args)
        {
            await HmacTest();
        }

        private static async Task HmacTest()
        {
            ClientWebSocket client = new ClientWebSocket();
            Uri _uri = new Uri("wss://ws-feed-pro.btcturk.com");
            await client.ConnectAsync(_uri, CancellationToken.None);

            string publicKey = "publickey";
            string privateKey = "privatekey";
            long nonce = 3000;
            string baseString = $"{publicKey}{nonce}";
            string signature = ComputeHash(privateKey, baseString);
            long timestamp = ToUnixTime(DateTime.UtcNow);
            object[] hmacMessageObject = { 114, new { type = 114, publicKey = publicKey, timestamp = timestamp, nonce = nonce, signature = signature } };
            string message = JsonSerializer.Serialize(hmacMessageObject);

            await client.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes(message),
                    0,
                    message.Length),
                WebSocketMessageType.Text,
                true,
                CancellationToken.None);

            var buffer = new byte[1024 * 20];

            while (true)
            {
                WebSocketReceiveResult result = await client.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
            
                string resultMessage = Encoding.UTF8.GetString(buffer, 0, result.Count);

                Console.WriteLine(resultMessage);
            }
        }

        private static string ComputeHash(string privateKey, string baseString)
        {
            var key = Convert.FromBase64String(privateKey);
            string hashString;

            using (var hmac = new HMACSHA256(key))
            {
                var hash = hmac.ComputeHash(Encoding.UTF8.GetBytes(baseString));
                hashString = Convert.ToBase64String(hash);
            }

            return hashString;
        }

        private static long ToUnixTime(DateTime date)
        {
            var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            return Convert.ToInt64((date - epoch).TotalMilliseconds);
        }
```

Benim kullanmış olduğum kod örneği bu şekilde. 

Sorun 401 hatası olduğu için kodla ilgili bir sorununuzun olmadığını düşünüyorum.  Yeni bir key oluşturup api bilgilerinizin doğruluğundan emin olduktan sonra tekrar istek atmayı deneyebilir misiniz?

**Comment by bymulker** [comment]
Süleyman Bey, 

Ben size bu saatte cevap yazmaktan kendimi alamadım kusura bakmayın,
Maalesef sonuç değişmedi.
Keyleri silip IP girerek yeni bir tane aldım.  
Koda kopyaladım.   Aşamaların ekran görüntüsünü aldım;



Selamlar,

Windows 10 için Posta ile gönderildi

Kimden: Süleyman Bayazit
Gönderilme: 14 Mayıs 2022 Cumartesi 22:56
Kime: BTCTrader/broker-api-docs
Bilgi: bymulker; Author
Konu: Re: [BTCTrader/broker-api-docs] WebSocket'e HMAC kulanarak bağlanmak (Issue #462)

Selamlar,
Unauthorized - Invalid Public key hatası 401 hatası oluyor bu nedenle 401 hatası olarak bilgilendirme yaptım.
static async Task Main(string[] args)

        {

            await HmacTest();

        }



        private static async Task HmacTest()

        {

            ClientWebSocket client = new ClientWebSocket();

            Uri _uri = new Uri("wss://ws-feed-pro.btcturk.com");

            await client.ConnectAsync(_uri, CancellationToken.None);



            string publicKey = "publickey";

            string privateKey = "privatekey";

            long nonce = 3000;

            string baseString = $"{publicKey}{nonce}";

            string signature = ComputeHash(privateKey, baseString);

            long timestamp = ToUnixTime(DateTime.UtcNow);

            object[] hmacMessageObject = { 114, new { type = 114, publicKey = publicKey, timestamp = timestamp, nonce = nonce, signature = signature } };

            string message = JsonSerializer.Serialize(hmacMessageObject);



            await client.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes(message),

                    0,

                    message.Length),

                WebSocketMessageType.Text,

                true,

                CancellationToken.None);



            var buffer = new byte[1024 * 20];



            while (true)

            {

                WebSocketReceiveResult result = await client.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);

            

                string resultMessage = Encoding.UTF8.GetString(buffer, 0, result.Count);



                Console.WriteLine(resultMessage);

            }

        }



        private static string ComputeHash(string privateKey, string baseString)

        {

            var key = Convert.FromBase64String(privateKey);

            string hashString;



            using (var hmac = new HMACSHA256(key))

            {

                var hash = hmac.ComputeHash(Encoding.UTF8.GetBytes(baseString));

                hashString = Convert.ToBase64String(hash);

            }



            return hashString;

        }



        private static long ToUnixTime(DateTime date)

        {

            var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

            return Convert.ToInt64((date - epoch).TotalMilliseconds);

        }
Benim kullanmış olduğum kod örneği bu şekilde.
Sorun 401 hatası olduğu için kodla ilgili bir sorununuzun olmadığını düşünüyorum. Yeni bir key oluşturup api bilgilerinizin doğruluğundan emin olduktan sonra tekrar istek atmayı deneyebilir misiniz?

**Comment by suleymanbyzt** [comment]
Selamlar,

İletmiş olduğunuz zip dosyası ne yazık ki açılmıyor. Dosya içeriği boş olarak görünüyor. Dilerseniz kod örneğini privateKey bilginizi gizleyerek suleyman.bayazit@btctrader.com mail adresine iletebilirseniz inceleyebilirim. zip formatında iletirseniz yine görüntüleyememe durumu olabilir bu nedenle direkt kod örneğini atabilirsiniz.

Diğer private endpointlerde bu sorunu yaşıyor musunuz? örnek olarak submit order yaparken ya da bakiye görüntülemesi yaparken  401 hatası alıyor musunuz? yoksa sadece websocket için mi bu durumu yaşıyorsunuz.

Ayrıca size ilettiğim kod örneğini hiç değiştirmeden sadece public ve private keylerinizi girerek deneyebilir misiniz? aynı kod örneği ile kanala bağlandığımda sorun yaşamadan kanalları dinleyebiliyorum.

```
[991, { "type": 991, "current": "5.1.0", "min": "2.3.0" }]
[114,{"type":114,"ok":true,"id":....,"message":null}]
```

Özellikle aşağıda ileteceğim kod örneğinde bulunan değerleri ve metodları hiç değiştirmeyiniz lütfen.

```csharp
long nonce = 3000;
            string baseString = $"{publicKey}{nonce}";
            string signature = ComputeHash(privateKey, baseString);
            long timestamp = ToUnixTime(DateTime.UtcNow);
            object[] hmacMessageObject = { 114, new { type = 114, publicKey = publicKey, timestamp = timestamp, nonce = nonce, signature = signature } };
            string message = JsonSerializer.Serialize(hmacMessageObject);

await client.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes(message),
                    0,
                    message.Length),
                WebSocketMessageType.Text,
                true,
                CancellationToken.None);
```

işlemden sonra geri bildirimde bulunmanızı rica edeceğim. İlettiğim kod örneğinde gerekli tüm işlemler ilgili metodlar tarafından yapıldığı için herhangi bir timestamp convert işlemi yapmanıza gerek bulunmuyor.

**Comment by bymulker** [comment]
Süleyman Bey,

Maalesef aynı sonuç. Programı https://github.com/bymulker/BtcTurkSocketTest linkinde bulabilirsiniz.
nonce = DateTime.UtcNow.Ticks olarak denedim farketmedi.

Ancak public endpointte bir sorun görünmüyor. Örneğin aşağıdaki kod sorunsuz ticker bilgisi getiriyor;

Selamlar,

private static async Task SendMessage(ClientWebSocket client, object[] MessageObject)
        {
            string msg = JsonConvert.SerializeObject(MessageObject); //NewtonSoft
            //string msg = JsonSerializer.Serialize(MessageObject);

            await client.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes(msg),
                    0,
                    msg.Length),
                WebSocketMessageType.Text,
                true,
                CancellationToken.None);
        }

        private static async Task WebSocketTest()
        {
            ClientWebSocket client = new ClientWebSocket();

            Uri _uri = new Uri("wss://ws-feed-pro.btcturk.com");

            await client.ConnectAsync(_uri, CancellationToken.None);

            object[] msg1 = { 111,
                new { type = 111, token = "jwt token" }
            };
            await SendMessage(client, msg1);

            object[] msg2 = { 151,
                new { type = 151, channel = "ticker", @event = "ETHUSDT", join = true }
            };
            await SendMessage(client, msg2);

            var buffer = new byte[1024 * 20];

            while (true)
            {
                WebSocketReceiveResult result = await client.ReceiveAsync(new ArraySegment<byte>(buffer), 
                    CancellationToken.None);
                string resultMessage = Encoding.UTF8.GetString(buffer, 0, result.Count);
                Console.WriteLine(resultMessage);
            }

        }     

Windows 10 için Posta ile gönderildi

Kimden: Süleyman Bayazit
Gönderilme: 15 Mayıs 2022 Pazar 13:39
Kime: BTCTrader/broker-api-docs
Bilgi: bymulker; Author
Konu: Re: [BTCTrader/broker-api-docs] WebSocket'e HMAC kulanarak bağlanmak (Issue #462)

Selamlar,
İletmiş olduğunuz zip dosyası ne yazık ki açılmıyor. Dosya içeriği boş olarak görünüyor. Dilerseniz kod örneğini privateKey bilginizi gizleyerek ***@***.*** mail adresine iletebilirseniz inceleyebilirim. zip formatında iletirseniz yine görüntüleyememe durumu olabilir bu nedenle direkt kod örneğini atabilirsiniz.
Diğer private endpointlerde bu sorunu yaşıyor musunuz? örnek olarak submit order yaparken ya da bakiye görüntülemesi yaparken 401 hatası alıyor musunuz? yoksa sadece websocket için mi bu durumu yaşıyorsunuz.
Ayrıca size ilettiğim kod örneğini hiç değiştirmeden sadece public ve private keylerinizi girerek deneyebilir misiniz? aynı kod örneği ile kanala bağlandığımda sorun yaşamadan kanalları dinleyebiliyorum.
[991, { "type": 991, "current": "5.1.0", "min": "2.3.0" }]

[114,{"type":114,"ok":true,"id":....,"message":null}]

Özellikle aşağıda ileteceğim kod örneğinde bulunan değerleri ve metodları hiç değiştirmeyiniz lütfen.
long nonce = 3000;

            string baseString = $"{publicKey}{nonce}";

            string signature = ComputeHash(privateKey, baseString);

            long timestamp = ToUnixTime(DateTime.UtcNow);

            object[] hmacMessageObject = { 114, new { type = 114, publicKey = publicKey, timestamp = timestamp, nonce = nonce, signature = signature } };

            string message = JsonSerializer.Serialize(hmacMessageObject);



await client.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes(message),

                    0,

                    message.Length),

                WebSocketMessageType.Text,

                true,

                CancellationToken.None);
işlemden sonra geri bildirimde bulunmanızı rica edeceğim. İlettiğim kod örneğinde gerekli tüm işlemler ilgili metodlar tarafından yapıldığı için herhangi bir timestamp convert işlemi yapmanıza gerek bulunmuyor.

**Comment by suleymanbyzt** [comment]
Selamlar,

Az önce projenize clone alarak kendi private ve public keylerim ile deneme yaptım ve yine başarılı bir şekilde bağlanabildim. Key bilginiz ile ilgili sorun yaşadığınızı kesinleştirmiş olduk. 

Kod yönünden bir sıkıntı yaşamadığınız için key ve IP bilginizin doğruluğunu tekrar kontrol etmenizi rica edeceğim.

Google üzerinden "What is my ip adress" gibi bir aratma yaparak IPv4 adresinize erişebilirsiniz. İlgili IP adresini aldıktan sonra Hesap => API Erişimi sekmesine gidiniz. Bu aşamada kesinlikle Websocket seçeneğinin seçili olduğundan emin olmanız gerek. Websocket seçili olmadan bir key oluşturmanız durumunda `[114,{"type":114,"ok":false,"id":0,"message":"Unauthorized - Invalid Public key"}]` hatası alırsınız. 

İzinler kısmında Websocket ibaresi bulunan key bilgileriniz ile tekrar istek attığınızda sorun tamamen çözülecektir. Sürümünüzle ilgili bir sorun olmadığını belirttiğiniz için key bilgisi ile ilgili sorun yaşadığınızı düşünmekteyim. 

Teşekkürler

**Comment by bymulker** [comment]
Süleyman Bey, sorun çözüldü nedeni; yanlış ip...
Utanıyorum ve söz veriyorum bundan sonra daha karmaşık sorunlarla 
zamanınızı alacağım 😊

Teşekkürler, iyi çalışmalar,

Windows 10 için Posta ile gönderildi

Kimden: Süleyman Bayazit
Gönderilme: 15 Mayıs 2022 Pazar 15:36
Kime: BTCTrader/broker-api-docs
Bilgi: bymulker; Author
Konu: Re: [BTCTrader/broker-api-docs] WebSocket'e HMAC kulanarak bağlanmak (Issue #462)

Selamlar,
Az önce projenize clone alarak kendi private ve public keylerim ile deneme yaptım ve yine başarılı bir şekilde bağlanabildim. Key bilginiz ile ilgili sorun yaşadığınızı kesinleştirmiş olduk.
Kod yönünden bir sıkıntı yaşamadığınız için key ve IP bilginizin doğruluğunu tekrar kontrol etmenizi rica edeceğim.
Google üzerinden "What is my ip adress" gibi bir aratma yaparak IPv4 adresinize erişebilirsiniz. İlgili IP adresini aldıktan sonra Hesap => API Erişimi sekmesine gidiniz. Bu aşamada kesinlikle Websocket seçeneğinin seçili olduğundan emin olmanız gerek. Websocket seçili olmadan bir key oluşturmanız durumunda [114,{"type":114,"ok":false,"id":0,"message":"Unauthorized - Invalid Public key"}] hatası alırsınız.
İzinler kısmında Websocket ibaresi bulunan key bilgileriniz ile tekrar istek attığınızda sorun tamamen çözülecektir. Sürümünüzle ilgili bir sorun olmadığını belirttiğiniz için key bilgisi ile ilgili sorun yaşadığınızı düşünmekteyim.
Teşekkürler

**Comment by suleymanbyzt** [comment]
Selamlar,

Hiç sorun değil istediğiniz zaman tekrar ulaşabilirsiniz 💯 

Kolay gelsin
