### ISSUE TITLE
WebSocket bağlantı problemi

### ISSUE THREAD

**Issue by bymulker** [BTCTrader/broker-api-docs#463]
Mernhaba,

Sitenizin https://docs.btcturk.com/websocket-feed/authentication sayfasındaki 'HmacTest' (C# .net core 3.1) kodunu çalıştırdığımda,
[114,{"type":114,"ok":false,"id":0,"message":"Unauthorized - Invalid Public key"}]
cevabı alıyorum. API keyimde gerekli tüm izinler bulunuyor. Acaba birşeyi atlıyor muyum?

**Comment by suleymanbyzt** [comment]
#462
