### ISSUE TITLE
WebSocket Hk

### ISSUE THREAD

**Issue by akbasmustafa02** [BTCTrader/broker-api-docs#464]
Merhabalar,

web socket yapılandırmanızda authent olmadan veri çekebiliyor muyuz?
wss://ws-feed-pro.btcturk.com link bulduk fakat, link ile beraber pariteyi nasıl göndermeliyiz? örnek link yapınız mevcut mudur?

talep ettiğimiz yapı örnek olarak;
"wss://ws-feed-pro.btcturk.com:9443/ws/BTCUSD@trade"

gibi,

teşekkürler

**Comment by suleymanbyzt** [comment]
Selamlar,

https://docs.btcturk.com/websocket-feed/models

Public kanallara bu link üzerindeki kod örnekleri ile ulaşabilirsiniz.
