### ISSUE TITLE
test subdomainlerine erişilememesi

### ISSUE THREAD

**Issue by alper-maker** [BTCTrader/broker-api-docs#465]
merhaba,

[pro-dev.btcturk.com](https://pro-dev.btcturk.com/) ve [test.btcturk.com](https://test.btcturk.com/) domainlerinin her ikisine de erişim sağlanamıyor. Test için nasıl anahtar oluşturabiliriz?

pro-dev için cloudflare "Access denied Error code 1020"  dönüyor, test için ERR_TOO_MANY_REDIRECTS hatası alınıyor.

> [BTCTurk Test] (https://pro-dev.btcturk.com/) to create your test API keys.

**Comment by suleymanbyzt** [comment]
Selamlar,

Dev ortamına şu an için erişim bulunmuyor. İlerleyen zamanlarda konu hakkında bir gelişme olursa size buradan bilgilendirme yapacağım.
