### ISSUE TITLE
Ticker sonuclarina pairin aktif olup olmadigi bilgisi eklenmesi

### ISSUE THREAD

**Issue by ninja342** [BTCTrader/broker-api-docs#466]
Cesitli zamanlarda pairler isleme kapatiliyor ama api'dan pairlerin aktif olup olmadigina dair bir bilgi gelmiyor. Ticker endpointinden gelen sonuclara her bir pair icin api ile trade'e acik olup olmadigini belirten bir bool degisken eklenebilir mi?

**Comment by suleymanbyzt** [comment]
Selamlar,

Konu hakkında gelen öneriyi ilgili ekibimize ilettim. Geliştirme yapılması durumunda bu issues altında size bilgilendirme yapacağım. 

Öneriniz için teşekkürler
