### ISSUE TITLE
API connection user login ID info

### ISSUE THREAD

**Issue by mrcyln** [BTCTrader/broker-api-docs#468]
Hi,

I established an API connection. I created an API access on website so I have private key info. 

When I want to login account I have a problem. 112 message Userloginresult returns false. What should I write ID line? I could not find any user ID info on website.

`message = [
            111,
            {
                "type": 111,  
                "id": USER_ID_HERE, #number
                "token": "ACCESS_TOKEN_INFORMATION_HERE",
                "username": "YOUR_MAIL_HERE"
            }
`

https://docs.btcturk.com/websocket-feed/models#channel-111-userlogin

**Comment by suleymanbyzt** [comment]
Hi,

Soon we'll remove connection with token authentication information from the api document.

You should use HMAC Authentication instead of token authentication. 

Check this link for more information: https://docs.btcturk.com/websocket-feed/authentication
