### ISSUE TITLE
Timestamp of server messages

### ISSUE THREAD

**Issue by mrcyln** [BTCTrader/broker-api-docs#469]
Hi,

I am using an API connection. My code is doing some calculations and then decide to whether buy-sell or not. I have a doubt about data of the server message. For example, on AVAXUSDT pair, I got open orderbook values;
Timestamp of message: 1655217917550 (22-06-2022 14:45:17.550) 
Price: 16.25
Quantity: 17.435

After this info, I have sent a market order and it closed 1655217918125 (22-06-2022 14:45:18.125) with a price 16.29 in stead of 16.25

I checked all trades message after this open orders time, there is no any other order closed between these time internals. I mean between timestamp of open orders and timestamp of my order.

I also detected that order which seen at orderbook message has been already closed at 14:45:16 with price:16.25, quantity 17:435, I mean before timestamp of orderbook reply. 
![Trades list after timestamp of orderbook](https://user-images.githubusercontent.com/29804412/173624436-7142b7ad-db5b-4c6f-8e6f-7ed49d78db87.jpg)

In this case, I think timestamp of message has delays according to real time and it causes lagged decisions. 

I am sure that, the timestamp is not my real-time data, it belongs to message.

Is there anything to missed?

**Comment by suleymanbyzt** [comment]
Hi,

Response may have reached you with a delay. For example, when the order is closed, you may receive a response with a delay of 2 or 3 seconds. Your request at 14:45:15 may have reached you at 14:45:17. That's why you may have missed orders at 14:45:16.
