### ISSUE TITLE
XRP icin balance bilgisi API'ye eklenmeli

### ISSUE THREAD

**Issue by afaslan** [BTCTrader/broker-api-docs#47]
Balance bilgisi suan icin sadece BTC, ETH, ve TRY icin donuyor. XRP borsaniza yeni eklendi ve API 'de henuz yok. Bu durum bazi botlari bozucaktir. XRP kullanimini engeller. Acil eklenirse API kullanarak ta XRP islemleri yapilabilir.

**Comment by nepnesomao** [comment]
Merhaba,
api/balancev2 url' inden tüm balance' larınıza erişebilirsiniz. Henüz dökümana eklemedik. Size dönecek olan model aşağıdadır.

`{
  "Success": true,
  "Message": null,
  "Data": [
    {
      "currency": "TRY",
      "whole_balance": 198214.48,
      "avaiable_balance": 171049.45,
      "reserved_balance": 27165.02,
      "taker_fee": 0.0030000000000000,
      "maker_fee": 0.0007000000000000
    },
    {
      "currency": "BTC",
      "whole_balance": 13.06171323,
      "avaiable_balance": 3.00511429,
      "reserved_balance": 10.05659894,
      "taker_fee": 0.0040000000000000,
      "maker_fee": 0.0010000000000000
    },
    {
      "currency": "ETH",
      "whole_balance": 2.93632776,
      "avaiable_balance": 2.93632776,
      "reserved_balance": 0.0,
      "taker_fee": 0.0030000000000000,
      "maker_fee": 0.0007000000000000
    },
    {
      "currency": "LTC",
      "whole_balance": 109.30575023,
      "avaiable_balance": 108.1685,
      "reserved_balance": 1.13725023,
      "taker_fee": 0.0030000000000000,
      "maker_fee": 0.0007000000000000
    },
    {
      "currency": "XRP",
      "whole_balance": 103.4908,
      "avaiable_balance": 93.4908,
      "reserved_balance": 10.0,
      "taker_fee": 0.0030000000000000,
      "maker_fee": 0.0007000000000000
    }
  ]
}`

**Comment by serensoner** [comment]
@nepnesomao merhaba, api/balancev2 cevabinda bir typo var. `avaiable_balance` yerine `available_balance` olmasi lazim.

**Comment by selimimer** [comment]
typo umarım değişmez. buna göre kodladım :)
