### ISSUE TITLE
resourceUrl

### ISSUE THREAD

**Issue by nanomusty** [BTCTrader/broker-api-docs#470]
Merhaba,
ben api üzerinde secret key ve public key kısımlarını oluşturdum ama **resourceUrl** kısmına ne yazmam gerekir acaba? API döküman kısmında yazmıyor...

**Comment by suleymanbyzt** [comment]
Merhaba,

resourceUrl için https://api.btcturk.com/ url bilgisini kullanmanız gerekmektedir.

Daha fazla bilgi için dilerseniz dökümanı inceleyebilirsiniz. Base url şeklinde api dökümanına gösterimi yapılmaktadır.

https://docs.btcturk.com/
