### ISSUE TITLE
closed-

### ISSUE THREAD

**Issue by ottoshark** [BTCTrader/broker-api-docs#471]
#

**Comment by suleymanbyzt** [comment]
Hi,

We can not share this information with you, but you can follow the location information of our servers on this page.

https://docs.btcturk.com/data-center

**Comment by suleymanbyzt** [comment]
Hi,

We cannot share this information with you, but you can follow the location information of our servers on this page.

https://docs.btcturk.com/data-center

**Comment by ottoshark** [comment]
#

**Comment by suleymanbyzt** [comment]
Hi,

Yes, Amsterdam is the location. 👍
