### ISSUE TITLE
ticker excele aktaramama sorunu

### ISSUE THREAD

**Issue by asdem92** [BTCTrader/broker-api-docs#472]
![Adsız](https://user-images.githubusercontent.com/108450393/176603034-7ea8c215-4d39-4db4-bd64-a6e5f8f72ef1.png)
 
Merhaba, excel dosyama btctürk anlık fiyatlarını almak istiyorum ancak https://api.btcturk.com/api/v2/ticker bu adresi girdiğimde ekteki gibi sonuç çıkıyor yardımcı olur musunuz?

**Comment by suleymanbyzt** [comment]
Merhaba,

İstek sonucunda success almış görünüyorsunuz. Ticker detayları data'nın içerisinde olması gerekiyor. Detaya gittikten sonra response görüntüleyebilirsiniz.
