### ISSUE TITLE
BTCTURK Websocket Javascript Örneği

### ISSUE THREAD

**Issue by cansoykaraman** [BTCTrader/broker-api-docs#473]
Merhaba,
rest api servisi olağanüstü açıklayıcı olmasına rağmen websocket servisinde neredeyse hiç bir açıklama yok.
Bir örneğe ihtiyacım var. Javascript olursa sevinirim. Mesela btctry orderbook verilerini limit değerleri (mesela 20) ile anlık olarak almak istiyorum. Nasıl yaparım ? Sadece siteyi kendi web tarayıcımda dinlemek istiyorum. Diğer programlama dillerine girmek istemiyorum. Saygılar sevgiler.

**Comment by suleymanbyzt** [comment]
Merhaba,

Websocket mesajlarını limit ile alma özelliği bulunmamaktadır. Sub olduğunuz kanallardan veriler sizlere otomatik olarak iletilmektedir. Örnek olarak orderBook için ws verileri almak istiyorsanız

```
 message = [
            151,
            {
                "type": 151,
                "channel": 'obdiff',
                "event": 'BTCTRY',
                "join": True
            }
        ]

```
ya da 

```
 message = [
            151,
            {
                "type": 151,
                "channel": 'orderbook',
                "event": 'BTCTRY',
                "join": True
            }
        ]
```

parametrelerini kullanarak orderBook verilerini alabilirsiniz. Js için bir kod örneği şu an için bulunmamaktadır. İlgili kod örneğinin eklenmesi için önerinizi ilgili birimlerimize iletiyor olacağım.

Dilerseniz python kod örneği ile kanallara bağlanıp verileri alabilirsiniz.

https://docs.btcturk.com/websocket-feed/models#channel-432-orderbookdifference

**Comment by SelcukCode** [comment]
> Merhaba, rest api servisi olağanüstü açıklayıcı olmasına rağmen websocket servisinde neredeyse hiç bir açıklama yok. Bir örneğe ihtiyacım var. Javascript olursa sevinirim. Mesela btctry orderbook verilerini limit değerleri (mesela 20) ile anlık olarak almak istiyorum. Nasıl yaparım ? Sadece siteyi kendi web tarayıcımda dinlemek istiyorum. Diğer programlama dillerine girmek istemiyorum. Saygılar sevgiler.

Sizin için aşağıya bir örnek bırakıyorum.

```
// Create WebSocket connection.
const socket = new WebSocket('wss://ws-feed-pro.btcturk.com');

// Connection opened
socket.addEventListener('open', function (event) {
    socket.send('[151,{"type":151,"channel":"orderbook","event":"BTCTRY","join":true}]');
    socket.send('[151,{"type":151,"channel":"obdiff","event":"BTCTRY","join":true}]');
    socket.send('[151,{"type":151,"channel":"orderbook","event":"USDTTRY","join":true}]');
    socket.send('[151,{"type":151,"channel":"obdiff","event":"USDTTRY","join":true}]');
    socket.send('[151,{"type":151,"channel":"orderbook","event":"SHIBTRY","join":true}]');
    socket.send('[151,{"type":151,"channel":"obdiff","event":"SHIBTRY","join":true}]');
});

// Listen for messages
socket.addEventListener('message', function (event) {
    // console.log('Message from server ', event.data);
});
```

**Comment by suleymanbyzt** [comment]
Selamlar,

İlk öncelikle ilettiğiniz kod örneği için teşekkür ederiz @SelcukCode 🙏🙏

Dökümana GoLang, nodejs ve Ruby kod örnekleri ekledim yakın zamanda merge olduğunda kod örneklerini kullanabilirsiniz.
