### ISSUE TITLE
C# Order Update / Emir Güncelleme

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#475]
İyi günler Süleyman Bey.

Buy, Sell, Cancel işlemleri yapıyorum ama bütün siteyi didik didik ettim API V2 de emir güncelleme ile ilgili bir şey bulamadım.
Hangi endpoint e hangi parametreleri göndermem gerekiyor ? Mümkünse bir örnekte hiç fena olmaz :)

Kolay gelsin, iyi çalışmalar.

**Comment by suleymanbyzt** [comment]
Selamlar,

Emir güncelleme özelliği API için bulunmuyor. PRO kullanıcıları için yayında olan bir özellik bu.

Eğer bir geliştirme yaparsak konu hakkında sizi bilgilendireceğim.

**Comment by akrepfatih** [comment]
Websocket için bu özellik kullanılabiliyor mu?

**Comment by suleymanbyzt** [comment]
Selamlar,

Websocket kanallarından yalnızca mesaj alınabiliyor herhangi bir post,delete ya da patch isteği websocket aracılığı ile iletilmiyor.

**Comment by akrepfatih** [comment]
[432,{"CS":5489543,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.49","A":"181.91434439"}],"BO":[{"CP":1,"P":"51.22","A":"14.56094473"},{"CP":3,"P":"51.18","A":"14.56378867"}],"channel":"obdiff","event":"LTCUSDT","type":432}]
[432,{"CS":5489547,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.48","A":"31.264"},{"CP":1,"P":"52.54","A":"42.88857463"},{"CP":3,"P":"102.57","A":"0.46534564"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
[432,{"CS":5489556,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.49","A":"213.17834439"}],"BO":[{"CP":3,"P":"51.18","A":"14.55810191"}],"channel":"obdiff","event":"LTCUSDT","type":432}]
[432,{"CS":5489562,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.49","A":"181.91434439"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
[432,{"CS":5489568,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.49","A":"213.17834439"}],"BO":[{"CP":1,"P":"51.27","A":"14.54674171"},{"CP":3,"P":"50.71","A":"14.54958009"}],"channel":"obdiff","event":"LTCUSDT","type":432}]
[432,{"CS":5489621,"PS":"LTCUSDT","AO":[{"CP":1,"P":"51.47","A":"31.264"},{"CP":0,"P":"51.49","A":"181.91434439"},{"CP":3,"P":"101.13","A":"5.14955621"}],"BO":[{"CP":3,"P":"51.28","A":"31.424"}],"channel":"obdiff","event":"LTCUSDT","type":432}]
[432,{"CS":5489640,"PS":"LTCUSDT","AO":[{"CP":1,"P":"51.48","A":"42.88857463"},{"CP":0,"P":"51.49","A":"213.17834439"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[{"CP":1,"P":"51.29","A":"15.39225825"},{"CP":3,"P":"50.71","A":"15.38925722"}],"channel":"obdiff","event":"LTCUSDT","type":432}]
[432,{"CS":5489641,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.49","A":"181.91434439"}],"BO":[{"CP":1,"P":"51.3","A":"31.411"}],"channel":"obdiff","event":"LTCUSDT","type":432}]
[432,{"CS":5489654,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.49","A":"3.98911619"},{"CP":3,"P":"52.49","A":"42.88857463"},{"CP":1,"P":"102.17","A":"0.098"}],"BO":[{"CP":1,"P":"51.29","A":"15.38325868"}],"channel":"obdiff","event":"LTCUSDT","type":432}]

Websocket obdiff kanalını dinlerken CP":0 sonucu geliyor bu da https://docs.btcturk.com/websocket-feed/models#channel-432-orderbookdifference a göre birinin güncelleme yaptığı anlamına geliyor.

**Comment by suleymanbyzt** [comment]
Selamlar,

Evet CP:0 emrin güncellendiğini belirten mesaj ama söylediğim gibi bu işlemler API üzerinden yapılan işlemler değil, PRO web sitemizden yapılan emir güncelleme işlemleri. Websocket kanallarını dinlerken sadece API işlemlerine ait işlem bilgileri gönderilmiyor.

CP: Orders are transaction type. 
0: Updated
1: New added
3: Deleted

P: Order price value.

A: Orders is the quantity

**Comment by akrepfatih** [comment]
İnsan eliyle bu kadar hızlı girilebilecek bir şey değil bu.

**Comment by akrepfatih** [comment]
https://github.com/BTCTrader/broker-api-docs/issues/217 burada V2 ile editlene bildiğini söyleyenler var

**Comment by suleymanbyzt** [comment]
V2 endpointleri public kullanıma açık değil ve yakın zamanda kapatılma durumu var. Ayrıca yukarıda iletmiş olduğunuz 432 kanalından iletilen mesajlar tek bir kullanıcı tarafından girilen update istekleri değil. 

Update isteği yerine emrinizi iptal edip tekrar insert yapabilirsiniz.

**Comment by akrepfatih** [comment]
Zaman Milisaniyeli= **_46:03:242_** Veri = [432,{"CS":5499503,"PS":"LTCUSDT","AO":[**_{"CP":1,"P":"51.27","A":"25.097"}_**,{"CP":0,"P":"51.29","A":"183.20491324"},{"CP":0,"P":"51.3","A":"76.9025"},{"CP":3,"P":"52.49","A":"41.60766993"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= 46:06:273 Veri = [432,{"CS":5499508,"PS":"LTCUSDT","AO":[],"BO":[{"CP":0,"P":"51.03","A":"35.97498729"},{"CP":3,"P":"50.97","A":"16.4024829"}],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:13:417_** Veri = [432,{"CS":5499521,"PS":"LTCUSDT","AO":[**_{"CP":0,"P":"51.26","A":"25.097"}_**,{"CP":1,"P":"51.28","A":"41.60766993"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:18:460_** Veri = [432,{"CS":5499530,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.26","A":"66.70466993"},_**{"CP":3,"P":"51.27","A":"25.097"}**_,{"CP":1,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:19:221_** Veri = [432,{"CS":5499531,"PS":"LTCUSDT","AO":[_**{"CP":0,"P":"51.26","A":"25.097"}**_,{"CP":1,"P":"51.28","A":"41.60766993"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= 46:24:293 Veri = [432,{"CS":5499540,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.26","A":"66.70466993"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:25:316_** Veri = [432,{"CS":5499542,"PS":"LTCUSDT","AO":[**_{"CP":0,"P":"51.26","A":"25.097"}_**],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:29:288_** Veri = [432,{"CS":5499549,"PS":"LTCUSDT","AO":[**_{"CP":0,"P":"51.26","A":"25.097"}_**,{"CP":1,"P":"51.28","A":"41.60766993"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= _**46:33:281**_ Veri = [432,{"CS":5499556,"PS":"LTCUSDT","AO":[_**{"CP":0,"P":"51.26","A":"25.097"}**_,{"CP":1,"P":"51.28","A":"41.60766993"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:35:357_** Veri = [432,{"CS":5499560,"PS":"LTCUSDT","AO":[**_{"CP":0,"P":"51.25","A":"25.097"}_**,{"CP":1,"P":"51.28","A":"41.60766993"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:39:461_** Veri = [432,{"CS":5499567,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.26","A":"66.70466993"},**_{"CP":3,"P":"51.27","A":"25.097"}_**,{"CP":1,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:41:255_** Veri = [432,{"CS":5499570,"PS":"LTCUSDT","AO":[**_{"CP":0,"P":"51.26","A":"25.097"}_**],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:45:708_** Veri = [432,{"CS":5499578,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.26","A":"66.70466993"},**_{"CP":3,"P":"51.27","A":"25.097"}_**,{"CP":1,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:46:310_** Veri = [432,{"CS":5499579,"PS":"LTCUSDT","AO":[_**{"CP":0,"P":"51.26","A":"25.097"}**_,{"CP":1,"P":"51.28","A":"41.60766993"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:50:275_** Veri = [432,{"CS":5499586,"PS":"LTCUSDT","AO":[**_{"CP":0,"P":"51.26","A":"25.097"}_**,{"CP":1,"P":"51.28","A":"41.60766993"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:54:290_** Veri = [432,{"CS":5499593,"PS":"LTCUSDT","AO":[**_{"CP":0,"P":"51.26","A":"25.097"}_**,{"CP":1,"P":"51.28","A":"41.60766993"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:57:816_** Veri = [432,{"CS":5499599,"PS":"LTCUSDT","AO":[{"CP":0,"P":"51.26","A":"66.70466993"},**_{"CP":3,"P":"51.27","A":"25.097"}_**,{"CP":1,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]
Zaman Milisaniyeli= **_46:58:428_** Veri = [432,{"CS":5499600,"PS":"LTCUSDT","AO":[**_{"CP":0,"P":"51.26","A":"25.097"}_**,{"CP":1,"P":"51.28","A":"41.60766993"},{"CP":3,"P":"102.17","A":"0.098"}],"BO":[],"channel":"obdiff","event":"LTCUSDT","type":432}]

Şimdi siz bana 25.097 adet update edilen emirlerin insan eliyle girildiğini ve tek bir kullanıcıya ait olmadığını mı söylüyorsunuz. Zaman ları ve 25.097 geçen satırları bold ve italik yaptım daha iyi dikkat çeksin diye
Zaman dakika , saniye , milisaniye cinsindedir

55 saniyede benim yakaladığım sayı bu ki burada sadece CP0 olanları süzüyorum. 1 2 tanede o arkadaşa ait CP 3 ve1 gelmiş

**Comment by suleymanbyzt** [comment]
Evet tek bir kullanıcıya ait olamaz çünkü dakikada bir hesaptan yalnızca 10 emir update edilebilir şeklinde bir rate limit bulunuyor.
Söylediğim gibi APIV2 authentication endpointleri public erişime açık değil ve yakın zamanda tamamen kapatılabilir.

APIV1 üzerinden mevcut emrinizi iptal ettikten sonra tekrar order insert işlemi yapabilirsiniz.

**Comment by akrepfatih** [comment]
3 5 kişi anlaştı 25.097 adet girecez ona göre diyorlar :)

https://docs.btcturk.com/rate-limits Requests per minute Post 300 Delete 300 yani dakikada 300 emir girip 300 emir silebilir anlamına geliyor. Sizin 10 gördüğünüz hane per second

**Comment by suleymanbyzt** [comment]
Fatih Bey şu konuda detaylıca açıklama yapayım çünkü aynı konuya tekrar geldiğimizi düşünüyorum.

V1 private endpointleri API kullanıcıları için kullanıma sunduğumuz endpointlerdir. Bu nedenle API kullanıcıları için rate limit belirlerken V1 endpointlerini baz alarak bir ayarlama yapıyoruz.

V2 private endpointleri public olarak kullanıma sunduğumuz bir endpoint değil ve söylediğim gibi ileride bu endpointlere erişimin kapatılma durumu var.

PRO Web sitemizden girilen emirler V2 endpointleri üzerinden iletilen isteklerdir.

Buradaki limitler de yukarıda belirttiğim gibi put, post ve delete için dakikada 10. (yani per minute, per second değil) 

Dilerseniz PRO web sitemiz üzerinden dakikada 10 adetten fazla olacak şekilde update, delete ya da insert işlemi yapın siz de göreceksiniz ki rate limite takılacaksınız.

Asıl sorunuza gelecek olursam 

delete işlemi için dakikada 300(per minute), saniyede ise 10 (per second)
post işlemi için dakikada 300(per minute), saniyede ise 10 (per second)

Bir üstte belirttiğim rate limitlerin V1 Private endpoint için geçerli olduğunu tekrar hatırlatmak isterim.
https://docs.btcturk.com/rate-limits  buradan detaylıca inceleyebilirsiniz.

**Comment by akrepfatih** [comment]
V1 V2 V3 V4 V5 beni alakadar etmez benim demek istediğim birisi bir yere bir endpoint yazmış ve bunu kullanıyor. 

Asıl sorun ben zaten girilen emirlerin PRO WEB sitesinden girildiğini düşünmüyorum. Otomatik bir program tarafından girildiğini söylüyorum. Siteden girildiğini siz düşünüyorsunuz. Girilmediğini anlatmaya çalışıyorum 25.097 den 55 saniyede 15 emir sadece CP 0 ları süzerek yapıyorum. Siz bana 3 5 insan anlaşmış aynı adette emir giriyor diyorsunuz. :)

Siz bana diyorsunuz ki silip tekrar koyun. Diyelim ki silmek için 300 milisaniye koymak için 300 milisaniye, emir yükseltmek yada alçaltmak için 600 milisaniye harcayacağım. update kullanan kişi tek istekle 300 milisaniye harcayacak. burada bir adaletsizlik var.

**Comment by serensoner** [comment]
@akrepfatih v2 endpoint'ini reverse engineering ile kullanabilirsiniz. boyle yapan kullanicilarin mevcut oldugunu dusunuyorum.

**Comment by akrepfatih** [comment]
@serensoner Süleyman beyin dediklerini okumadınız mı ? v2 endpoint ini kullanıyor olsa dakikada 10 işlem girebiliyormuş bu kişi 55 saniyede 15 işlem sadece CP 0 olanları süzerek yapıyor. süzmesem işlem sayısı 20 25 tane olur en az buda onun bloke olmasına neden olur. Yani V2 kullanamaz reverse engineering olamaz. Sanırım şimdi bana katılıyorsunuzdur.

**Comment by serensoner** [comment]
v2 rate limiti olan 10 istek / dk nin ip'ye ait olmadigindan emin misiniz? ayni hesaba ait farkli 2 ipden update request girilebilir sonuçta.

**Comment by akrepfatih** [comment]
Süleyman bey Dakika da bir hesaptan yazıyor IP den değil yani nereden bağlanırsan bağlan aynı hesap olur.

**Comment by akrepfatih** [comment]
1.  432 den kendi emirlerimi de dinliyorum benim emirlerimde de bazen (20-30 emirde 1) CP 0 dönüyor. Halbuki sadece emir koy, emir kaldır işlemi yapıyorum.

2.  432 den kendi koyduğum ve kaldırdığım emirleri takip ederken başka bir fiyatın üstüne koyması ve kaldırması durumunda CP 1 ya da CP 3 göremiyorum. Fakat ne zaman boş bir fiyata denk geldiğimde o zaman CP 1 yada CP 3 ü görebiliyorum.

Hayırlı işler iyi geceler.

**Comment by akrepfatih** [comment]
@suleymanbyzt Süleyman bey bu kod LTCUSDT - CP0 - Alış ve Satış emirleri dinler.

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.WebSockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;


namespace Test_001
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await Test();
        }

        private static string _orderBookFull = "[151,{\"type\":151,\"channel\":\"obdiff\",event:\"LTCUSDT\",\"join\":true}]";

        private static async Task Test()
        {
            ClientWebSocket client = new ClientWebSocket();
            Uri _uri = new Uri("wss://ws-feed-pro.btcturk.com");
            await client.ConnectAsync(_uri, CancellationToken.None);
            await SendSocketMessage(client, _orderBookFull);
        }


        private static async Task SendSocketMessage(ClientWebSocket client, string msg)
        {
            await client.SendAsync(buffer: new ArraySegment<byte>(array: Encoding.UTF8.GetBytes(msg), offset: 0, count: msg.Length), messageType: WebSocketMessageType.Text, endOfMessage: true, cancellationToken: CancellationToken.None);

            var buffer = new byte[1024 * 20];

            while (true)
            {
                WebSocketReceiveResult result = await client.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);

                string resultMessage = Encoding.UTF8.GetString(buffer, 0, result.Count);

                if (resultMessage.IndexOf("CS") != -1 && resultMessage.IndexOf("PS") != -1 && resultMessage.IndexOf("channel") != -1 && resultMessage.IndexOf("event") != -1 && resultMessage.IndexOf("type") != -1)
                {
                    string a = resultMessage.Replace("[431,{\"CS\":", "{\"CS\":").Replace(",\"type\":431}]", ",\"type\":431}").Replace("[432,{\"CS\":", "{\"CS\":").Replace(",\"type\":432}]", ",\"type\":432}");

                    var v_jsonsonuc1 = JsonConvert.DeserializeObject<Root>(a);

                    Console.Write("Saat : " + DateTime.Now.ToString("HH:mm:ss:fff") + "\t");
                    Console.Write(" CS: " + v_jsonsonuc1.CS + "\t");
                    Console.Write(" ALIŞ: " + "\t");

                    for (int i = 0; i < v_jsonsonuc1.BO.Count; i++)
                    {
                        if (v_jsonsonuc1.BO[i].CP == 0)
                        {
                            Console.Write("CP: " + v_jsonsonuc1.BO[i].CP + " P: " + v_jsonsonuc1.BO[i].P + " A: " + v_jsonsonuc1.BO[i].A + "\t");
                        }
                    }

                    Console.Write(" SATIŞ: " + "\t");

                    for (int i = 0; i < v_jsonsonuc1.AO.Count; i++)
                    {
                        if (v_jsonsonuc1.AO[i].CP == 0)
                        {
                            Console.Write("CP: " + v_jsonsonuc1.AO[i].CP + " P: " + v_jsonsonuc1.AO[i].P + " A: " + v_jsonsonuc1.AO[i].A + "\t");
                        }

                    }

                    Console.WriteLine("");
                }
                else
                {
                    Console.WriteLine("YOK");
                }
            }
        }

        public class AO
        {
            public int CP { get; set; }
            public decimal P { get; set; }
            public decimal A { get; set; }
        }

        public class BO
        {
            public int CP { get; set; }
            public decimal P { get; set; }
            public decimal A { get; set; }
        }

        public class Root
        {
            public int CS { get; set; }
            public string PS { get; set; }
            public List<AO> AO { get; set; }
            public List<BO> BO { get; set; }
            public string channel { get; set; }
            public string @event { get; set; }
            public int type { get; set; }
        }
    }
}

**Comment by suleymanbyzt** [comment]
@akrepfatih kod örneği için teşekkür ederiz. Bu konuyla alakalı bir talep gelirse bu issues'a yönlendirme yapacağım 🚀
