### ISSUE TITLE
WebSockets in BalanceUpdated

### ISSUE THREAD

**Issue by SonerKeser** [BTCTrader/broker-api-docs#478]
There are some numbers in the data that comes with Payload in the BalanceUpdated model in WebSocket. What do these numbers represent?

**Comment by SonerKeser** [comment]
For example, after a XRPTRY purchase; [201,{"type":201,"userId":0000000,"payload":"16,5,1"}]. For example, after a BTCTRY purchase; [201,{"type":201,"userId":0000000,"payload":"1,2,1"}].

**Comment by suleymanbyzt** [comment]
Payload returns the pairId, numeratorId, and denominatorId information
For example:
"payload":"135,50,1"
135 => PairId (SANDTRY, BTCUSDT, ETHBTC etc.)
50 => NumeratorId (SAND, ETH, BTC etc.)
1 => DenominatorId (TRY, USDT, BTC)
