### ISSUE TITLE
BtcTurk Test API

### ISSUE THREAD

**Issue by emin-karadag** [BTCTrader/broker-api-docs#479]
Merhabalar,
Ufak çaplı test uygulamalarım için BtcTurk Test API kullanıp testlerimi gerçekleştirmek istedim ancak aşağıdaki dokumanda belirtilen URL adresi çalışmadığından Test API kullanarak testlerimi gerçekleştiremiyorum.
Bu konuda geri dönüşlerinizi bekliyorum.
Kolay gelsin.

![Ekran görüntüsü 2022-07-23 133424](https://user-images.githubusercontent.com/7556164/180601716-dd30aa77-79dc-4b3e-946d-a0589b4a6912.png)

**Comment by suleymanbyzt** [comment]
Selamlar,

Test ortamına girişler şu an için aktif değil. İlerleyen süreçte bir değişiklik olursa size bilgilendirme  yapacağım.
