### ISSUE TITLE
Limit sell emri "invalid model" hatası

### ISSUE THREAD

**Issue by bozRADAGAST** [BTCTrader/broker-api-docs#48]
`function cancel(){ // BTCTURK		
		$uri='https://www.btcturk.com/api/exchange';
		$sign=hash_hmac('sha512',$uri,"#SECRET#");
		$ch = curl_init($uri);
		$message = "#KEY#" . time();
		$signature = base64_encode(hash_hmac('sha256', $message,base64_decode("#SECRET#"),true));
		curl_setopt($ch, CURLOPT_HTTPHEADER, array('X-PCK:'."#KEY#","X-Stamp:".time(),"X-Signature:".$signature));
		curl_setopt($ch, CURLOPT_POSTFIELDS,"OrderMethod=0&OrderType=1&Price=45280&amount=00112&amountPrecision=001&pricePrecision=00&PairSymbol=BTCTRY");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		$execResult = curl_exec($ch);
		$bb = json_decode($execResult, true);
		return(serialize($bb));
}

print_r(cancel());echo "\n";`

Verdiği sonuç;

a:1:{s:5:"error";a:2:{s:4:"code";i:400;s:7:"message";s:106:"Emir girilemedi. Lütfen tekrar deneyiniz ve hata tekrar ederse bize ulaşınız. Hata kodu: Invalid model";}}

**Comment by nepnesomao** [comment]
Merhaba,
Göndermeniz gereken parametreler aşağıdaki gibidir;
```
amount = 0,
amountPrecision = 0112,
price = 45280,
pricePrecision = 00,
triggerPrice = 0,
triggerPricePrecision=00,
total = 30,
totalPrecision = 00
DenominatorPrecision = 2,
PairSymbol = BTCTRY,
OrderMethod = 0,
OrderType = 1,
```

**Comment by bozRADAGAST** [comment]
merhaba total parametresi ne işe yarıyor? birde buy emrinde amount kısmına ne yazacağız elimizdeki tl'yi mi?

**Comment by nepnesomao** [comment]
Amount sizin almak veya satmak istediğiniz BTC/ETH/XRP, Total parametresi eğer market alış emri verdiğinizde kaç TL' lik alım emri veriyorsanız total' e örneğin 1000 yazıyorsunuz, onun dışında 0 olarak gönderebilirsiniz.

**Comment by bozRADAGAST** [comment]
peki son birşey daha sorayım. limit buy emrinde de kullanabiliyormuyuz total parametresini? price'yle beraber. teşekkür ederim
