### ISSUE TITLE
Currency -> BTC Pair Bilgi Gösterim Hatası

### ISSUE THREAD

**Issue by emin-karadag** [BTCTrader/broker-api-docs#480]
Merhabalar,
https://api.btcturk.com/api/v2/ticker/currency?symbol=btc adresine istek atıldığında BTC paritesine ait işlem çiftleri ve bilgileri elde edilmektedir. Ancak bazı işlem çiftlerinde "**daily**" alanı hatalı gelmektedir.

Tahminime göre formül şu şekilde:
**daily = high - low**

Ancak aşağıdaki ekran görüntüsünde görüleceği üzere **high** ve **low** eşit olduğu için sanırım **daily** alanında bir hesaplama sorunu bulunmakta.

Bilginize sunarım, kolay gelsin.

![Ekran görüntüsü 2022-07-23 152824](https://user-images.githubusercontent.com/7556164/180605000-2ab73be7-4956-44ca-abb6-e0645a2c35ec.png)

**Comment by serensoner** [comment]
merhaba, daily ask - open seklinde hesaplaniyor btcturk'te (bence cok mantikli degil ama donen veri oyle). dailyPercent ile (last / open - 1) * 100 olmali yanlis hatirlamiyorsam.

**Comment by emin-karadag** [comment]
ask - open mı?
Günlük fiyat değişim formülü bu şekilde olması bana da pek mantıklı gelmedi :)

**Comment by suleymanbyzt** [comment]
Selamlar,

Daily alanı günlük değişimi temsil etmektedir. High-low formülü gün içinde oluşan en büyük fiyat farkını ortaya çıkaracaktır ama ilgili kolon son 24 saate göre değişimi temsil eder.

Örnek olarak BTCUSDT için `last `değerinin 22500 olduğunu ve `daily `alanının -1200 olduğunu varsayalım. 

Bunun anlamı dün aynı saat ve aynı dakikada BTCUSDT'nin fiyatı 23700 USDT değerindedir.

4 saatlik mumlarda her nasılsa bir önceki 4 saatlik veriye göre değişimini gösteriyorsa bunu da 24 saatlik bir data olarak düşünebilirsiniz.

23.07.2022 saat 16:19'da bu veriyi görüntülerseniz daily alanı dün saat 16:19'daki fiyatı baz alarak bir değişim gösterecektir.
