### ISSUE TITLE
İşlem Çiftine Ait Günlük Değişim Oranı Hk.

### ISSUE THREAD

**Issue by emin-karadag** [BTCTrader/broker-api-docs#481]
Merhabalar,
Aşağıdaki ekran görüntüsünde (https://api.btcturk.com/api/v2/ticker/currency?symbol=usdt) adresine istek atılmak suretiyle gelen veriler arasından BTC_USDT işlem çiftine ait bilgiler yer almaktadır.

![Ekran görüntüsü 2022-07-23 154017](https://user-images.githubusercontent.com/7556164/180605450-18c7bd59-4daf-4a87-9b81-75d26fdf7397.png)

Bu bilgilerdeki "daily" alanı muhtemelen BTC_USDT işlem çifti için USDT cinsinden günlük değişim miktarı yer almakta. Ancak aşağıdaki formülleri denememe rağmen "daily" alanındaki değere ulaşamadım. Ya ben yanlış formül uyguluyorum ya da gelen veri yanlış.

>  daily = high - low 
daily = 23752 - 22130 = **1622**

> daily = high - last
daily = 23752 - 22285 = **1467**

> daily = open - last
daily = 23682 - 22285 = **1397**

> daily = open - low
daily = 23682 - 22130 = **1552**

**Görüldüğü üzere hiçbir formül API isteği sonucunda gelen daily alanındaki 1377 değerini vermemektedir.**

Bilginize sunarım.

**Comment by emin-karadag** [comment]
Formül -> **daily = ask - open** olarak hesaplanıyormuş. 
Açıkçası günlük fiyat değişiminin (ask-open) olarak alınması bana pek mantıklı gelmedi ama belki mantıklı bir açıklama yapan çıkar :)

**Comment by suleymanbyzt** [comment]
#480
