### ISSUE TITLE
API Authentication V1 dokümantasyonu örnek Python kodunda hatalı satırlar

### ISSUE THREAD

**Issue by eroloz** [BTCTrader/broker-api-docs#482]
https://github.com/BTCTrader/broker-api-docs/blob/master/README-pro.md#api-authentication-v1
384 ve 385. satırlarda hata var, gördüğüm kadarıyla:
```
  "X-Stamp": str(nonce),
  "X-Signature": str(base64.b64encode(signature).decode('utf-8')),
```
Aşağıdaki şekilde düzeltilebilir:
```
  "X-Stamp": stamp,
  "X-Signature": signature,
```
Aynı durum BTCTurk web sitesindeki ilgili sayfada da söz konusu: 
https://docs.btcturk.com/authentication/authentication-v1

**Comment by suleymanbyzt** [comment]
Selamlar,

Şu anda kontrol ettim dökümana hatalı yazılmış konu hakkında gerekli aksiyonlar alınacaktır.

Geri bildirim için teşekkür ederiz. 🚀
