### ISSUE TITLE
Bazı IP adreslerinden private endpointlere bağlantı yapılamıyor 

### ISSUE THREAD

**Issue by eroloz** [BTCTrader/broker-api-docs#483]
balances endpointi için dokümantasyonda verilen örneğe göre hazırlanmış olan aşağıdaki kod bazı IP adresleri üzerinde çalıştırıldığında 401 Unauthorized hatası alıyor.

```
import time, base64, hmac, hashlib, requests, json

base = "https://api.btcturk.com"
method = "/api/v1/users/balances"
uri = base+method

apiKey = "***"
apiSecret = "***"
apiSecret = base64.b64decode(apiSecret)

stamp = str(int(time.time())*1000)

data = "{}{}".format(apiKey, stamp).encode("utf-8")

signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)

headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type" : "application/json"}

result = requests.get(url=uri, headers=headers)

print("Status Code: %s Reason: %s API Key: %s" % (result.status_code, result.reason, apiKey))

if result.status_code == 200:
    result = result.json()
    print(json.dumps(result, indent=2))
```

API anahtarının sınırlandığı IP adresi, key ve secret bilgilerini defalarca kontrol ettim. Sonuç aynı. Aynı kod ikisi de Hetzner firmasına ait iki farklı VPS üzerinde çalıştırıldığında 401 alıyor. Bu sunuculardan birisinde (Ubuntu) timedatectl çıktısı şu şekilde.

```
               Local time: Wed 2022-07-27 15:35:40 UTC
           Universal time: Wed 2022-07-27 15:35:40 UTC
                 RTC time: Wed 2022-07-27 15:35:41
                Time zone: UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

```
Birisi linux, ikisi windows olmak üzere yurt içi IP adreslerine sahip 3 farklı makinada sorunsuz çalışan bu kodun, yurt dışındaki 2 farklı linux makinada 401 hatası alması, bazı IP bloklarından bağlantı yapılmasının mümkün olmadığı izlenimini uyandırdı.

/api/v1/users/transactions/trade endpointini denediğimde de aynı durum söz konusu.

**Comment by suleymanbyzt** [comment]
Selamlar,

Yurt dışı IP için genel olarak herhangi bir kısıtlama koymuyoruz. API Key oluştururken kullandığınız IP adresi ile VPS sunucusu IP adresi uyuşmuyor olabilir mi? ya da bu VPS üzerinden IPv6 adresleri ile istek atmaya çalışıyor olabilirsiniz bunun kontrollerini yapabilir misiniz? 
Sunucu timestamp ile bir sıkıntı yaşadığınızı düşünmüyorum ilettiğiniz çıktıda UTC saat dilimine göre. IP adresiyle alakalı sıkıntı yaşıyor olabilirsiniz ve bu VPS ile alakalı olabilir.

Ayrıca belki gözden kaçmış olabilir Api key oluştururken Account ve Total funds yetkisi vermediyseniz /api/v1/users/transactions/trade ve /api/v1/users/balances endpointlerinde sıkıntı yaşarsınız. (Aldığınız hata yalnızca bu endpointler için geçerliyse sorun bu olabilir.)

Dilerseniz suleyman.bayazit@btctrader.com e-posta adresine VPS üzerindeki IP adresini atarsanız IP adresinde bir kısıtlama var mı kontrol edebiliriz.

**Comment by eroloz** [comment]
Hızlı ve detaylı yanıtınız için teşekkür ederim.

Sorun, düşündüğünüz gibi, IPv6 üzerinden istek atılmasından kaynaklıymış.
 
Kullandığım VPS üzerinde IPv6 kullanan herhangi bir uygulamam olmadığı için bu protokolü devre dışı bırakarak sorunu çözdüm. IPv6 protokolünün devre dışı bırakılamayacağı durumlarda aşağıdaki safyadaki şekilde Python requests kütüphanesinin dayandığı alt kütüphane olan urllib3 yamalanarak da sorun çözülebilir gibi görünüyor:
https://stackoverflow.com/questions/33046733/force-requests-to-use-ipv4-ipv6/46972341#46972341

api.btcturk.com adresi için DNS kayıtlarında IPv6 adresleri yer aldığı ve Debian tabanlı sistemler IPv6'ya öncelik verdiği için bu durum yaşanmış görünüyor. BTCTurk web sitesinden API anahtarı yaratırken IPv6 adresi girme imkanı olmadığından, IPv6'da çalışan bir API bulunsa da buna bağlanma imkanı yok. API anahtarı yaratılırken IPv6 adresi girmek mümkün olursa IPv6'yı devre dışı bırakmadan veya kütüphane yamalamadan da kullanılabilir sanıyorum.

**Comment by suleymanbyzt** [comment]
Selamlar,

Sorunun çözülmüş olduğuna sevindim. API'de IPv4 desteklendiği için IPv6 istekleri bunu ezebiliyor.

Aynı sorunu yaşayan farklı bir kullanıcı olursa buraya yönlendirme yapacağım kütüphane bilgileri için teşekkürler.

Herhangi bir sorun yaşamanız durumunda tekrar issues açabilirsiniz.

Kolay gelsin 👍
