### ISSUE TITLE
WS bağlantısında periyodik olarak kopmalar söz konusu

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#485]
- Python dili ile `websockets` kütüphanesiyle bağlantı kurulduğunda, `no close frame received or sent` hatası geliyor.
- `ping_interval=None` yapılması da bu durumu engelleyemiyor artık.
- Son zamanlarda WS bağlantı kopukluğu miktarı artmaya başladı.
- Çözüm şekli ve sorunun nedeni hakkında bilgi verir misiniz?

**Comment by suleymanbyzt** [comment]
Selamlar,

Websocket üzerinde saniyede 200 mesaj alınabilir şeklinde bir rate limit bulunuyor belki sorunun nedeni bu olabilir bu limiti aşacak şekilde mesaj almanız durumunda connection kapanabilir.

Socket yapısı ile ilgili bir değişikliğe yakın zamanda hiç gitmedik sizin bağlantınız kaynaklı bu sorun yaşanıyor olabilir. 

Yaşadığınız sorunla ilgili olarak Python Websocket docs sayfasına bakındım ve dökümanda bu soruna değinilmiş. Sorunun çözümü için öneriler var buraya göz atabilirsiniz. 

https://websockets.readthedocs.io/en/stable/howto/faq.html#what-does-connectionclosederror-no-close-frame-received-or-sent-mean

**Comment by yemreak** [comment]
Merhaba konu ile ilgili olarak aldığım detaylı hata şöyledir:
`asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes`

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

Websocket ile ilgili bir güncelleme olmamış son günlerde. Sorun güncel olarak devam ediyor mu? devam ediyorsa yaşadığınız sorun kaç gün önce başladı?

Forumları incelediğimde send mesajlarına await ekleyerek sorunun çözüldüğünü yazmışlar bunu deneyebilirsiniz.

**Comment by yemreak** [comment]
Merhabalar, BtcTurk üzerindeki işlem çifti sayısı her geçen gün artıyor, bundan kaynaklı:

- WS üzerinde her saniye alınabilecek mesajın 200'den fazla olması gerekmez mi? 
- Buna yönelik bir iyileştirme olmayacak mı? 
- Limit yetersiz duruyor ve yeni çiftler de eklendikçe dinlemekte zorluk çekeceğiz

> Veya WS verilerini 0.5ms'de değil de her 1s de bir dinleme şansımız var mı?

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

200 mesaj sınırını aşabilmek için neredeyse her pair için aynı connectionda ayrı bir sub isteği atılması gerek. Eğer bu şekilde kanala bağlanıyorsanız ayrı bir connection açarak pairleri dağıtmanızı rica edeceğim.(200 mesaj limiti connection bazında olduğu için ayrı bir connection açılması önerilir.)

Aksi takdirde 200 mesaj sınırını aşabilmek çok zor bir durum. Örnek olarak ticker all kanalına bağlandığınızda dahi saniyede 2 mesaj limiti harcamış oluyorsunuz çünkü ticker verileri ayrı bir mesaj halinde tek tek iletilmiyor.

Her pair için aynı connectionda sub isteği atmıyorsanız sorununuzun daha farklı bir şey olduğunu düşünüyorum. 

Son günlerde aynı sorunu raporlayan farklı bir kullanıcımız olmadı sorun internet bağlantısı kaynaklı yaşanıyor olabilir mi?

**Comment by yemreak** [comment]
> 200 mesaj sınırını aşabilmek için neredeyse her pair için aynı connectionda ayrı bir sub isteği atılması gerek

Evet bu şekilde idim, dağıtıp 2 connection yapacağım, teşekkür ederim :)

**Comment by suleymanbyzt** [comment]
Rica ederim kolay gelsin 🚀

**Comment by yemreak** [comment]
Merhabalar websocket üzerinde dağıtma işlemini yapsam da yine periyodik olarak gelen hatalar aşağıdaki gibidir:

```python
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

Websocket üzerindeki tüm limitleri paylaşabilir misiniz?
- Toplam kaç WS açabiliyoruz
- WS event sınırına 200 demiştiriniz
- Ayrıca Binance gibi platformlarda olduğu gibi WS üzerinden tüm marketi tek bir subscription ile dinleyemez miyiz?
- Üsttekini önerme sebebim her birine ayrı abone olma durumunda hep bağlantı sorunu oluşuyor (örnek hata mesajlarındaki gibi)
@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

Socket üzerinde son günlerde sıkça yaşanan bir problem keşfettik. Connecitonların kapanma sebebini keşfettiğimiz hataya bağlıyoruz. Konu ile ilgili bir fix geçince size tekrar haber vereceğim.
