### ISSUE TITLE
API üzerinden alımlarda tutar olarak üst limit var mıdır?

### ISSUE THREAD

**Issue by sgumuskaya** [BTCTrader/broker-api-docs#486]
Örnek olarak AVAX'dan 20.000 TL tutarında ortalama 40 adet alım emri verdiğimde çalışıyor ancak 50.000 TL tutarında 93 adet emir girdiğimde API 400-BadRequest hatası alıyorum. Varlığım 50.000 TL'den fazla. .Net

https://api.btcturk.com/api/v2/server/exchangeinfo servisinde AVAX_TRY için "maximumOrderAmount" null görünmektedir.
Teşekkürler.

**Comment by suleymanbyzt** [comment]
Selamlar,
MaximumOrderAmount için bir bug olduğunu keşfettiğimiz için kısa bir süreliğine null dönecek şekilde ayarlama yaptık. Fixlediğimizde döküman üzerinden bilgilendirme yapıyor olacağız ve ilgili alan tekrar değer dönmeye başlayacak.

Sorunuza gelecek olursam AVAX üzerinde 5 BTC büyüklüğünde bir limit olduğunu görüyorum. 93 adet ile buna takılmanız mümkün değil. Her 50 bin TL üzeri emirlerinizde bu sorunu mu yaşıyorsunuz?

**Comment by sgumuskaya** [comment]
Merhaba,

İlginiz için teşekkür ederim. 

Evet, CHZ_TRY alımı için de aynı sorunu yaşadım.  .Net Core api'sini kullanıyorum. Ayrıca az önce deneme amaçlı 500 TL fiyattan 110 adet (toplam 55.000 TL) emir girmeye çalıştım. Bad Request hatası aldım.

İyi çalışmalar.

**Comment by sgumuskaya** [comment]
Mevcutta 999 AVAX'ımız var. 500 TL'den 40 adet alış verdiğimde emir çalışıyor. Tekrar 40 adet girmek istersem Bad Request hatası alıyorum. Ancak bekleyen 40 adetlik emri silip tekrar 40 adetlik emir girebiliyorum. Belki bir case'dir diye paylaşmak istedim.

CHZ_TRY içinse böyle bir durum söz konusu değildir. Mevcutta CHZ_TRY varlıklarım arasında değil.

İyi çalışmalar

**Comment by sgumuskaya** [comment]
İlginiz için çok teşekkür ederim. Varlık olarak toplam coin'lerle birlikte varlığa bakmışım. TL olarak varlığımız 20.000 lira civarıymış.

Sistemde mevcut TL varlığa bakacak şekilde düzenleme yapacağım.

Sizi de yordum, kusura bakmayın.

İyi çalışmalar

**Comment by suleymanbyzt** [comment]
Selamlar,

Sorunu çözmüş olduğunuza sevindim. Account balance sorununuzun yanısıra şu bilgiyi de vermek isterim.

Yukarıda  "500 TL fiyattan 110 adet (toplam 55.000 TL) emir girmeye çalıştım" şeklinde bir bilgi paylaşmışsınız.

Bu tarz emir vermeye çalıştığınızda maximumLimitOrderPrice hatası alırsınız. Çünkü yakın zamanda yaptığımız geliştirme ile kriptoparaların mevcut değerinin 10 kat yükseğine max ve mevcut değerinin 10 kat altına ise min olacak şekilde bir limit price eklemesi yaptık.

Yani CHZ'de güncel piyasa fiyatı 2.704 olduğu için ilgili limitler aşağıdaki gibi olacaktır.

```json
        "maximumLimitOrderPrice": 27.0400000000000000,
        "minimumLimitOrderPrice": 0.2704000000000000
```

Kaynak: https://docs.btcturk.com/public-endpoints/exchange-info

Bu alanları exchangeInfo endpointimizde yansıtıyoruz. Emir verirken özellikle bu değerlere dikkat ederseniz ekstra bir sorunla karşılaşmazsınız.

**Comment by sgumuskaya** [comment]
İlginiz ve desteğinizi için çok teşekkür ederim.

İyi çalışmalar.
