### ISSUE TITLE
611 | Ws üzerinden gelen ama API dökümanında bulunmayan mesaj kodu

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#487]
Sanırım para çekme işlemlerinden sonra gelen bir mesaj

**Comment by suleymanbyzt** [comment]
Selamlar,

Söylediğiniz gibi bu alanı dökümana eklemeyi unutmuşuz. En kısa zamanda dökümana ekleyip gerekli güncellemeleri yapacağız.

Geri bildirim için teşekkür ederiz 🚀 💯
