### ISSUE TITLE
WS dinlerken beklenmedik hata

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#488]
CloudFlare WebSocket proxy restarting; then sent 1001 (going away) CloudFlare WebSocket proxy restarting

```python
websockets.exceptions.ConnectionClosedOK: received 1001 (going away) CloudFlare WebSocket proxy restarting; then sent 1001 (going away) CloudFlare WebSocket proxy restarting
```

**Comment by suleymanbyzt** [comment]
Selamlar,

Cloudflare tarafında routing policy işlemi yapılmış gibi görünüyor. İstekler Cloudflare arkasından geçtiği için bu tarz iyileştirmeler sırasında bağlantınız koptuğunda tekrar bağlanmak için websocket reconnect yapısı kurabilirsiniz.
