### ISSUE TITLE
WS kanalındaki orderbook modellerinde veri güncelliğini kontrol etmek adına timestamp gönderebilir misiniz?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#489]
- WS streamlerinde yoğunluk veya server - client arasında ping oluştuğunda gelen verilerin güncel olduğunu anlayamıyoruz
- Bu da eski orderbook verilerine göre işlem yapmamızı sağlıyor
- Bunun çözümü oldukça basit aslında `timestamp` adı altında server zamanını da çevirebilir misiniz?

> Olumlu olumsuz dönüşünüzü bekliyorum

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

Önerinizi değerlendirilmesi üzerine ilgili ekiplere ileteceğim. Bir güncelleme yaparsak dökümanda ilgili güncellemeleri geçeriz.

**Comment by yemreak** [comment]
Tekrardan merhabalar,

- Trade channelında timestamp bilgisi veriyorsunuz, aynısını Orderbook'a da uygalayamaz mısınız?
- Hala geri dönüş alamadığım için tekrar yazıyorum
- Düzenlemeye kadar da Orderbook'ların güncel olduğunu nasıl anlayabiliriz?

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

Şu an için iletilen mesajlarla bunu eşleştirmeniz mümkün olmayabilir. API kullanıcılarının bu tarz socket taleplerini değerlendirmek için ilerleyen dönemde API kullanıcılarına özel sadece API kullanıcıların erişebileceği bir socket oluşturma gibi bir düşüncemiz var. Bu geliştirme tam anlamıyla planlandığında ekibe konuyla alakalı önerinizi tekrar ileteceğim.
