### ISSUE TITLE
Order canceling is not clear

### ISSUE THREAD

**Issue by silenca** [BTCTrader/broker-api-docs#49]
Dear support,

We have 3 limit orders created via API with canceling issue.

1. The limit order has been created.
2. The cancelation request has been sent.
3. BTCTurk responded without error. Which we treat as a success -- the order has been canceled. 
4. But the order has been completed, when we expect that the order is canceled.

List of such orders:

- id:"5249264", "datetime":"2018-03-13T17:55:12.9067653Z
- id:"5256367", "datetime":"2018-03-14T07:55:52.5119841Z
- id:"5256380", "datetime":"2018-03-14T07:56:31.7453566Z

Please advise, how should we treat such issue? How can we be sure whether order completed or canceled?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
