### ISSUE TITLE
ORDER_MAX_PRICE_EXCEEDED, ani fiyat hareketliliklerinde emir vermeye çalıştığımızda geliyor

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#490]
- Verilebilecek max fiyatı nasıl alabiliriz böyle durumlarda?

**Comment by suleymanbyzt** [comment]
Selamlar,

Yakın zamanda yayına aldığımız güncelleme ile bir pairin mevcut değerinin 10 kat üstüne max, 10 kat altına ise min olacak şekilde bir limit güncellemesi yaptık. Bu alan exchangeInfo endpointimizde dinamik bir şekilde güncellenmektedir.

https://api.btcturk.com/api/v2/server/exchangeinfo

```json
        "maximumLimitOrderPrice": 4297740.0000000000000000,
        "minimumLimitOrderPrice": 42977.4000000000000000
```

https://docs.btcturk.com/public-endpoints/exchange-info
Dökümanda detaylar bulunmaktadır.

**Comment by yemreak** [comment]
Teşekkür ederim. Ayrıca güvenlik tedbiriniz için de çok teşekkür ederim yazılımımla `price` ile `quantity` değerlerini ters yazmışım az daha gidiyordu paralarım 😅

**Comment by suleymanbyzt** [comment]
Rica ederiz 🙏🚀 kullanıcılarımızın bu tarz sorunlarla karşılaşmaması adına bu önlemi almıştık nokta virgül hatasından yanlışlıkla emir girişi de yapılabiliyordu bu geliştirme ile bunun da önüne geçmiş olduk
