### ISSUE TITLE
WS kanalında `order_id=0` olan emir ekleme olayları gerçekleşiyor

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#491]
- Bu işlemi `ping` yapısı gibi `auth` u canlı tutmak için mi yapıyorsunuz?

```python
OrderInsertEvent(
    pair_symbol='BTCTRY',
    order_id=0,
    user_id=0,
    order_type='bid',
    price='0',
    total_quantity='0',
    left_numerator='0.00',
    left_denominator='0',
)
```

**Comment by suleymanbyzt** [comment]
Selamlar,

Auth socket mesajları için de bir ping pong yapısı kullanıyoruz. Server tarafından 5 saniyede bir ilgili client'a ping mesajı yolluyoruz client'ın bağlı olup olmadığını anlamak için. Bu ping mesajları için boş bir event gönderme gibi bir yapımız bulunmuyor.  Bu boş event'i her zaman alıyor musunuz?

**Comment by yemreak** [comment]
Selamlar,

Hayır her zaman olmuyor. Şu anda da yok. Arada bir denk geldiğim bir senaryo bu, ilk kez yaşamıyorum. Sıklığını hatırlamıyorum ama ilk olmadığı kesin.

**Comment by suleymanbyzt** [comment]
Socket'te connection açarken bir sorun yaşadığımda ben de bu boş event'i alıyordum ama son zamanlarda hiç karşılaşmamıştım.  Konu hakkında not aldım ekiple görüştükten sonra aksiyon alınabilecek bir durum mu yoksa socket yapısı ile ilgili bir durum mu kontrol ederiz.

Geri bildirim için de teşekkür ederiz 👍 bir düzenleme olursa buradan bilgilendirme yapacağım
