### ISSUE TITLE
Btcturk Azure Service Zone

### ISSUE THREAD

**Issue by ottoshark** [BTCTrader/broker-api-docs#492]
Hi there,
As you stated in the official docs, your server is in Azure Amsterdam. However, which zone do you use? 1-2-3? I want to have a presence in the zone where you are located in.

Thanks

**Comment by suleymanbyzt** [comment]
Hi,
Our systems are scattered through all availability zones in the region. However there is Cloudflare proxy in front of our traffic. You won’t be able to reach our servers directly.
