### ISSUE TITLE
Komisyonlar hakkında

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#493]
Sistem üzerindeki komisyon bilgilerinde Kripto TRY Taker için  en az %.06 mı %.08 mi var?

- Bu komisyon oranı her bir Kripto TRY, Taker işlemi için aynı mı?
- Ayrıca Web ile API işlemleri arasında komisyon farkı var mı?
- Kuponların çoğu Web için çalışmakta da

**Comment by suleymanbyzt** [comment]
Selamlar,

Kripto/TRY için en düşük taker komisyon oranı %0.08 (0.0008) (5. kademe kullanıcılar için geçerli.)


> Bu komisyon oranı her bir Kripto TRY, Taker işlemi için aynı mı?
 Evet, oranlar sabit.

> Ayrıca Web ile API işlemleri arasında komisyon farkı var mı?
Hayır API kullanıcılarına özel bir komisyon tarifesi bulunmuyor.

Daha detaylı bilgi için https://pro.btcturk.com/en/help/fees sayfamızı ziyaret edebilirsiniz.

**Comment by suleymanbyzt** [comment]
Selamlar,

Bugün komisyonlar sayfasında düzenleme yapıldı. Bir anlığına 0.06 olarak görünüyordu 5. Kademe Kripto/TRY komisyon ama aslında 0.08 olduğunu belirtmek isterim.

Yukarıdaki metni dikkate almamanızı rica edeceğim. Komisyonlar sayfasında detayı görüntüleyebilirsiniz.
