### ISSUE TITLE
getAllOrders startTime and endTime filter does not work properly

### ISSUE THREAD

**Issue by umutdenizsenerr** [BTCTrader/broker-api-docs#494]
get_orders_url = f"{REST_API_ROOT_URL}/allOrders"
        get_orders_body = {
            "pairSymbol": symbol,
            "startTime": start_time,
            "endTime": end_time,
            "limit": limit,
        }

        response = requests.get(
            url=get_orders_url, headers=headers, params=get_orders_body
        )

I am trying to filter the orders by startTime and endTime. I have tried to give timestamp in ms and second. Both of them give me 
`{'success': False, 'message': 'startTime cannot be bigger than current unix timestamp.', 'code': 1038},`

Also i tried for startTime=0.0 and endTime=0.0 it gives all orders without filtering.

**Comment by suleymanbyzt** [comment]
Hello,

In the AllOrders endpoint, you should give timestamp in second for the StartDate and EndDate parameters.

request example:
`api/v1/AllOrders?pairSymbol=BTCTRY&startTime=1660760790&endTime=1660847190`

if you do not send it in second (10 digits) and UTC format, you may get this error.

Server time: https://api.btcturk.com/api/v2/server/time
