### ISSUE TITLE
API bilgileri anlık olarak yanlış (eskisinin aynısı olarak) gelmeye başladı

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#495]
19/12/2022 13:36:10 Tarihinde SPELL -> TRY açık emrimin tamamlanmasına rağmen `balance` ve `order` endpointlerine istek attığımda ne bakiye aktarılmış, ne de açık emir tamamlanmış. Bakiye ve açık emir sonuçları sanki emir tamamlanmamış gibi geilyor. Hatta açık emirlerde tamamlanan emir gözüküyor. Sebebi nedir?

> Bu durumda iken SPELL TRY çiftinde yoğun trade işlemleri varı

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Merhaba,

Yük altındayken anlık olarak bu sorunu yaşamış olabilirsiniz. Trafik çok yükseldiğinde işlemlerde belirli bir ölçüde queue olduğundan db işlemi sırasında ufak bir gecikme olmuş olabilir.
