### ISSUE TITLE
WS mesajları 400ms geç gelebiliyor, WS sunucusu nerede?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#496]
Merhabalar, 

- Trade verilerini dinlediğimde verideki `D` bilgisi ile mesajı aldığım zaman arasında `400ms` ilk farklar söz konusu
- Aynı gecikmenin `Orderbook` için de geçerli olduğunu düşünürsek, emir defterleri güncel gelmiyor
- Ek olarak `trade` ve `orderbook` channelarını dinlediğim zaman, bazı `trade` eventleri `orderbookfull` içerisinde mevcut değil
- Yani `trade` olmuş ama emir defterinde karşılığı yok, bu nasıl olabiliyor?
- Veri bütünlüğü konusunda sorunlar var sanırım sisteminizde, özellikle `ws` kanalında

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

Vermiş olduğunuz örnek ile gecikmeyi ölçümlemek doğru olmayabilir. Transaction tamamlandığı anda mesaj socket'e iletilir bu mesajın tarafınıza ulaşması uygulamanın deploy olduğu server'a göre değişkenlik gösterebilir. 

Gecikmenin işlemlerinizi etkileyecek kadar fazla olduğunu düşünüyorsanız dilerseniz bu süreçte orderbook endpointine istek atarak işlemlerinize devam edebilirsiniz.

Orderbook ve trade bağlantısı ile ilgili olarak #459 issuess için belirttiğim gibi bu dataları sync olarak alabileceğiniz bir kanal bulunmuyor bu kanalları sıralı bir şekilde dinlemek arada data kaybı olmasına neden olacaktır.

Ayrıca rate limitleri rahatlatmak adına websocket çok güzel bir alternatif olsa da mesaj kayıplarının olabileceğini göz önüne almak gerekir. Websocket yapısı gereği mesaj kayıplarının yaşanabileceği bir mesaj türüdür. Endpointler veri kayıplarının yaşanmamasını sağlarken rate limit gibi bir sorunu ortaya çıkarabiliyor. Websocket ise rate limit sorununu çözerken veri mesaj kayıplarına neden olabiliyor.

Websocket yapısının API kullanıcılarına daha uygun hale getirmek için çalışmalarımız devam ediyor. API kullanıcılarına özel socket yapısı kurulduğunda taleplerinizin çoğunu göz önüne alarak geliştirme yapmaya çalışacağımızdan emin olabilirsiniz. Ekip bu konular hakkında ciddi mesai harcıyor bunun planlanması ve canlıya alınması uzun sürebilir ama yapı tam anlamıyla kurulduğunda sizleri tatmin edecek bir yapı olabileceğinden emin olabilirsiniz.

Son olarak WS sunucusu Azure West Europe'da 👍

**Comment by yemreak** [comment]
Merhabalar,

* `ws` kanalından önce `rest` ile isteklerde bulundum lakin `rest` `ws` verilerini kopyalayacak şekilde geliyor
* Anladığım kadarıyla `ws` içerisinden gelen verileride `cs` ile kayıp varsa onu `rest` ile yakalamam gerekiyor
* Peki `ws` yenileme periyodunuz nedir? 
    * saniyede `2` kere mi 
    * `veriler değiştikçe` mi 
    * yoksa `400ms` de bir mi
* `ws` ile `rest` akışı hakkında bilgi için aşağıdaki raporumu paylaşayım

```python
20:54:29.155 WS: BTCUSDT AO: 21442 0.00731 BO: 21417 0.17628796
20:54:29.234 RS: BTCUSDT AO: 21442 0.00731000 BO: 21417 0.17628796 delay: 27ms
20:54:29.491 RS: BTCUSDT AO: 21442 0.00731000 BO: 21417 0.17628796 delay: 17ms
20:54:29.731 RS: BTCUSDT AO: 21442 0.00731000 BO: 21417 0.17628796 delay: 24ms

20:54:29.890 WS: BTCUSDT AO: 21441 0.09684137 BO: 21417 0.17628796
20:54:29.979 RS: BTCUSDT AO: 21441 0.09684137 BO: 21417 0.17628796 delay: 37ms
20:54:30.243 RS: BTCUSDT AO: 21441 0.09684137 BO: 21417 0.17628796 delay: 24ms

20:54:30.374 WS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07
20:54:30.486 RS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07000000 delay: 21ms
20:54:30.754 RS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07000000 delay: 41ms
20:54:30.992 RS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07000000 delay: 18ms

20:54:31.114 WS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07
20:54:31.223 RS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07000000 delay: 14ms
20:54:31.460 RS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07000000 delay: 23ms

20:54:31.564 WS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07
20:54:31.713 RS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07000000 delay: 26ms
20:54:31.948 RS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07000000 delay: 18ms

20:54:32.105 WS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07
20:54:32.205 RS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07000000 delay: 15ms
20:54:32.444 RS: BTCUSDT AO: 21441 0.09684137 BO: 21410 0.07000000 delay: 27ms
```

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

Commit periyotumuz 500 MS. Yani saniyede 2 mesaj olacak şekilde sockete mesajları publish ediyoruz. 

Socket üzerinde mesaj kayıpları olağan olduğundan dilerseniz ekstra olarak orderbook endpointine istek atarak kaçabilecek bir mesajı yakalayabilirsiniz.

**Comment by yemreak** [comment]
- Her pair için commit periyodu birbirinden bağımsız duruyor
- Neden her pair için aynı anda commit atılmıyor?
- Piyasa fiyatlarını almak tutarsız oluyor
- Binance gibi her güncellemeyi anında iletme veya her bir pair verisini aynı anda sunma yapılarına geçmeyecek misiniz?

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

Söylediğim gibi yeni socket yapısında API kullanıcılarının taleplerini karşılayabilecek bir yapı kurmayı hedefliyoruz. Binance'da güncellemeyi realtime olarak anında iletmiyor onlarda da belirli bir commit periyotu var 100 ms olması gerekiyor yanlış hatırlamıyorsam. Yeni yapıda commit periyot süresinin düşürülmesi de ayrıca öneri olarak sunulacak 👍

**Comment by mGungorr** [comment]
Merhaba, @suleymanbyzt bu konuda bir gelişme var mı ?

Ayrıca **allorderbook** için olan anlık olarak iletiyor gibi gözüküyorken, **tickers** saniyede 1 kez geliyor gibi. Herhangi bir fiyat bilgisine en hızlı ulaşabilmek için hangi ws'i tavsiye edersiniz, Aylık işlem hacmimin 1 milyar TL seviyelerinde olmasından dolayı bu tarz farklar, sistem için can alıcı öneme sahip. Önerilerinizi paylaşabilir misiniz ?
