### ISSUE TITLE
Dinamik IP adresine müsaade edilmeli

### ISSUE THREAD

**Issue by mss1451** [BTCTrader/broker-api-docs#497]
Merhaba, birkaç ay önce Rust dili için bir [API kütüphanesi](https://github.com/mss1451/btcturk) geliştirdim. Fakat API erişimi için statik IP adresinin zorunlu kılınmış olması geliştirme açısından zorluk çıkarıyor. Bununla birlikte endpoint'leri test etmek için kendi gerçek hesabımı kullanmak zorunda kaldım çünkü [pro-dev.btcturk](https://pro-dev.btcturk.com/) sitesi "erişim reddedildi" hatası döndürüyor.

Dinamik IP adresiyle erişim çeşitli sebeplerden ötürü statik IP'ye sahip olmayanlar için mümkün kılınmalı diye düşünüyorum.

**Comment by suleymanbyzt** [comment]
Selamlar,

Statik IP kullanıcılarımızın güvenliği için olan bir yapı. Hesaba belirlenen IP dışından erişim yapılması kullanıcılarımız için güvenli değil. Bu nedenle işlemlerinizi sadece belirleyebileceğiniz IP üzerinden yapabilirsiniz.

Pro dev sitemize şu an için erişim bulunmamaktadır. Genel olarak tekrar kullanıma açtığımızda dökümandan bilgilendirme yapıyor olacağız.
