### ISSUE TITLE
api key 

### ISSUE THREAD

**Issue by nkayahan** [BTCTrader/broker-api-docs#498]
selamlar,

Ben Avustralya'da yaşıyorum ve yaptığım her kripto yatırımı için vergi ödemem gerekiyor. Avustralya tax ofisi yatırma çekme al sat işlemlerini koinly diye bir app aracılığıyla api kullanarak çekiyor. Şimdi ben btctürk hesabıma api erişimi için key almak istiyorum fakat statik ip belirtmem gerekiyor ve bunu koinlyden almam mümkün değil. Bütün borsalarda api keyi her ip'ye read only oluşturabilirken burda neden oluşturamıyorum. Bu api keyi nasıl oluşturabilirim?

**Comment by nkayahan** [comment]
bu api keyi alamamam durumunda bana maaliyeti yaklaşık 5000 dolar

**Comment by suleymanbyzt** [comment]
Selamlar,

Dilerseniz konu hakkında destek@btcturk.com e-posta adresine talebinizi iletebilirsiniz.

Size gerekli yönlendirmeleri operasyon tarafından yapabilirler.

**Comment by nkayahan** [comment]
Selamlar,

Önce oraya yazdım sonra size yönlendirdiler zaten, ya benim için aşırı
önemli. Halletmem lazım kısa zamanda. Api ile bütün transactionları alıyor
vergilendirme için kullandıkları app ama statik ip'lerini paylaşmıyorlar.

Süleyman Bayazit ***@***.***>, 8 Eyl 2022 Per, 18:25
tarihinde şunu yazdı:

**Comment by suleymanbyzt** [comment]
Selamlar,

Kendinize bir api yazıp datayı bir yere deploy edip datayı oradan iletebilirsiniz.

Eğer BtcTurk üzerinden bu datayı vermek istiyorsanız operasyon tarafından bunun onayı gelmesi gerek.

Dilerseniz size hesap hareketlerinizi excel formatında iletebilirler. Ya da operasyon tarafından bize api key bilginizin public olması için talep gelirse düzenleme yapılması için talep girebiliriz.
