### ISSUE TITLE
Request Limits'de değişiklik oldu mu?

### ISSUE THREAD

**Issue by semih314** [BTCTrader/broker-api-docs#50]
Dökümantasyona göre her 100 milisaniyede bir request göndermeye izin varken, bazen birkac requesti aralarında 1 saniye bekleyerek yolladığım halde, çok sık olmamakla birlikte bu hata mesajı geri geliyor. 

<Response [409]>, The allowed number of requests has been exceeded.

Dökümantasyonun mu güncellenmesi gerekiyor bu konuda yoksa ben mi bir şeyi atlıyorum?

teşekkürler

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
