### ISSUE TITLE
KLine datada atlamalar

### ISSUE THREAD

**Issue by babursaylan** [BTCTrader/broker-api-docs#500]
Selamlar, 

$base = "https://graph-api.btcturk.com";
$method = "/v1/klines/history?from={$d11}&resolution=2&symbol={$pair}&to={$d2}";

syntaxı ile 120 saniyelik aralıklarla data okuyorum. 
d1, d2 olarak şu anı ve şu andan 6 saat öncesini gönderiyorum.

Bu çağrıyı dakikada bir yaparak anlık datayı veritabanında tutmaya çalışıyorum. BTCTRY, ETHTRY gibi yoğun işlemli pairlerde hiç sorunsuz 2 dakikalık arayla veri toplarken LTCTRY, BATTRY gibi pairler için gelen dizide zaman zaman 360, 600 saniyelik aralıklar oluyor, yani o aralıkta hiç veri kaydedemiyorum.

BATTRY için okuduğum aralıklardan bir örnek gönderiyorum; Atlama olan satırların başına ** koydum.

0: 1662659160 : 6.0229997634888
** 1: 1662659400 : 6.0079998970032
2: 1662659520 : 6.0190000534058
3: 1662659640 : 6.0370001792908
4: 1662659760 : 6
5: 1662659880 : 5.9980001449585
6: 1662660000 : 5.9990000724792
7: 1662660120 : 5.978000164032
8: 1662660240 : 5.9899997711182
9: 1662660360 : 6.0029997825623
10: 1662660480 : 5.9930000305176
11: 1662660600 : 5.9710001945496
12: 1662660720 : 5.9829998016357
** 13: 1662660960 : 5.9899997711182
14: 1662661080 : 6.0029997825623
15: 1662661200 : 6.0159997940064
16: 1662661320 : 6.0149998664856
17: 1662661440 : 6.0050001144409
18: 1662661560 : 6.0029997825623
19: 1662661680 : 6.0029997825623
20: 1662661800 : 6.0009999275208
** 21: 1662662160 : 6.0019998550415

Bu sorunu çözmek için ne yapabilirim?
Teşekkürler.

**Comment by babursaylan** [comment]
Şunun boş sonuç vermesi de durumu netleştiriyor;
https://graph-api.btcturk.com/v1/ohlcs?pair=BATTRY&from=1662659280&to=1662659399

**Comment by suleymanbyzt** [comment]
Selamlar,

Kline ya da OHLC datasında dakikalık veri gelmemesinin nedeni o dakikada hiç trade olmamasından kaynaklanıyor. Trade olması durumunda grafiğe datalar işlenecektir. Bu yüzden hacmi az olan pairlerde bu durumu yaşamanızın nedeni bu. 

Bu gibi durumlarda data gelmeyen dakikalar için bir önceki gelen datanın fiyatını baz alabilirsiniz.

**Comment by babursaylan** [comment]
Yanıt ve bilgi için teşekkürler..
