### ISSUE TITLE
MAXIMUM_ORDER_AMOUNT_EXCEEDED, bu bilgiyi API ile nasıl alabilirim?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#501]
LUNAUSDT için konulmuş sanırım, işlem yapmamı engelledi ve zarar ettim 
@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

Mobil tarafta yaşanan sorun nedeniyle maximumOrderAmount bilgisini exchangeInfo'dan kaldırmıştık son durumu öğrenmek adına mobil ekip ile iletişime geçip sorun düzeldiyse sorunu fixleyip prod'a çıkabiliriz.

**Comment by serensoner** [comment]
bu maximum order amount limitinin sebebi nedir acaba?

**Comment by suleymanbyzt** [comment]
@serensoner verilen emrin miktar büyüklüğü arttıkça parçalı gerçekleşme durumu da aynı oranda artıyor. Sistemsel olarak bu durum istemediğimiz bir şey. Emrin olabildiğince en az parça ile gerçekleşmesini istiyoruz bu nedenle bir maximumOrderAmount sınırımız var

**Comment by suleymanbyzt** [comment]
Selamlar,

Konuyla ilgili gerekli güncellemeler yapıldı. MaximumOrderAmount bilgisini https://api.btcturk.com/api/v2/server/exchangeinfo endpointimizden dönmeye başladık. Bu süreçte anlayışınız için teşekkür ederiz.
