### ISSUE TITLE
Web ve Mobil Client üzerinde hızlıca emir vermeye çalışırken `TooManyRequest` hatası

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#502]
Özellikle min amount sınırı olanlarda çok sık gerçekleşiyor. Emri verene kadar piyasa değişiyor
@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

Mobil ve Web kullanıcıları için limitlerimiz insert,cancel ve put için 10.

Her biri için dakikada 10 olacak şekilde bir sınırlamamız var bu rate limiti aşmanız durumunda tooManyRequest hatası alırsınız

**Comment by yemreak** [comment]
- Her biri kendi içerisinde ayrı 10'a mı sahip, yoksa hepsi toplamda 10 mu?
- Örnek verecek olursam
- insert, cancel, insert yaptığımda, direkt 3 olarak mı ele alınacak?
- Yoksa insert için 2, cancel için 1 olarak mı?

> Ek olarak periyotlar her dk başladığında mı oluyor, 1:00'da yani, yoksa istek attığım andan sonraki ilk dk'lık periyot olarak mı hesaplanıyor?

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,
Dakikada toplam her operasyon için 10 istek sınırınız bulunmaktadır.
Örnek olarak emir verip emrinizi güncellediğinizi ve daha sonra iptal ettiğinizi varsayalım.
Bu durumda 9 insert, 9 cancel ve 9 update limitiniz kalacaktır.
Periyotlar ise ilk emrinizi tarihi baz alarak belirlenmektedir. 13:34:28'de ilk emri verdiğinizi ve 13:34:55'de rate limite takıldığınızı düşünelim bu durumda rate limit periyotunuz 13:35:28'de yenilenecektir.
