### ISSUE TITLE
BUG | WS üzerinden emir iptali bilgisinde `numLeft` `amount`a  eşit geliyor

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#503]
* Aynı ws kanalından order match bilgisi gelse bile, iptaldeki left bilgisi güncel olmuyor

```python
{
    'type': 452,
    'pairId': 160,
    'symbol': 'GLMUSDT',
    'id': 0,
    'method': 0,
    'userId': 0,
    'orderType': 1,
    'price': '0.4266000000000000',
    'amount': '6209.9744000000000000',
    'numLeft': '6209.9744000000000000',
    'denomLeft': '2648.1154090083838677',
    'newOrderClientId': 'advanced'
}
```

@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,
Attığınız response incelediğimde userId ve id alanlarının düzgün gelmediğini görüntülüyorum. İlgili alanları 0 olarak almışsınız gibi görünüyor private socket mesajları için nasıl authentication yaptığınızı iletebilir misiniz? token kullanarak  bağlanıyorsunuz yoksa HMAC Authentication mı kullanıyorsunuz?

Sorunuza gelecek olursak siz cancel isteği attığınızda biz bu isteği emrin son hali ile sıraya alıyoruz. Sıraya aldığımız durumda iptal olmadan hemen önce başka bir emir ile eşleşip leftAmountlarının değişebilmesi mümkündür. Balance ile ilgili detayları görüntülemek için dilerseniz `/api/v1/users/balances` endointine istek atabilirsiniz. Burada bakiyeniz ile ilgili son durumları görüntüleyebilirsiniz. Aşağıya örnek bir response bırakıyorum.

```json
{
    "data": [
        {
            "asset": "TRY",
            "assetname": "Türk Lirası",
            "balance": "27223,7283250757643288",
            "locked": "4874,3628685722294523",
            "free": "22349,3654565035348765",
            "orderFund": "4874,3628685722294523",
            "requestFund": "0",
            "precision": 2
        },
        {
            "asset": "BTC",
            "assetname": "Bitcoin",
            "balance": "9,7502186644553258",
            "locked": "3,3109771999999998",
            "free": "6,439241464455326",
            "orderFund": "3,3109771999999998",
            "requestFund": "0",
            "precision": 8
        }
  ],
  "success": true,
  "message": null,
  "code": 0
}
```

**Comment by yemreak** [comment]
Merhabalar,

- `userid` ve `id` kısımlarını gizlilik adına `0` ile güncelledim. Orada herhangi bir sorun yok
- Kimlik doğrulamayı HMAC ile yapıyorum
- `ws` üzerinden `matched` ardından `delete` `event`i geliyor ama `delete` içerisinde son anda `matched` olan kaynakları göstermiyor
- `balances` üzerinden aktarılan kaynaklar gözükmekte evet, lakin `delete` üzerindeki sorundan bahsetmekteyim ben

@suleymanbyzt
