### ISSUE TITLE
Rate limit h.k

### ISSUE THREAD

**Issue by lagosos** [BTCTrader/broker-api-docs#504]
Merhaba ratelimit'de bir güncelleme gelicekmi coin sayısı artı fakat günceleme yapılmadı.

**Comment by suleymanbyzt** [comment]
Selamlar,

Gerekli sistemsel iyileştirmeler ekibimizce yapılmaktadır. İlerleyen süreçte rate limitlerle alakalı bir güncelleme yapılırsa dökümandan bunun bilgisini paylaşacağız.

Güncel geliştirmeleri [Recent changes - BtcTurk | PRO API Documentation](https://docs.btcturk.com/recent-changes) bu bağlantıdan kontrol edebilirsiniz.
