### ISSUE TITLE
order eklemede sürekli 400 hatası alıyorum. 

### ISSUE THREAD

**Issue by umitiri** [BTCTrader/broker-api-docs#505]
https://api.btcturk.com/api/v1/order sayfasına aşağıdaki code ile post ediyorum. Ne yaptıysam sürekli 400 hatası alıyorum. 
Bu hataya benzer daha önceden de soru açılmış cevap olarak sadece parametreler hatalıdır denmiş, fakat ben hatalı olduğunu düşünmüyorum. Defalarca kontrol ettim. 

Authentication için gerekli işlemleri farklı bir fonksiyonda hallediyorum. Fonksiyon çalışıyor, emir silme, aktif emir görme, balance görme gibi bütün işlemleri yapıyor. Yani o kısımda sorun yok.

 order post ettiğimde tek değişen code aşağıda bulunuyor. Ancak sürekli hata veriyor. Burada değişende req.Method POST oluyor ve içerikte
strPost olarak verdiğim stringte parametreleri göndermek için denmeleer yaptım, olmadı payload olarak yapıp string e dönüştürdüm gene olmadı. Gözden kaçırdığım bir hata yada eksik mi vardır?
`
        ServicePointManager.Expect100Continue = true;
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
          HttpWebRequest req = (HttpWebRequest)WebRequest.Create(adres);
        
          req.ContentType = "application/x-www-form-urlencoded";
        req.Accept = "application/json";
      req.ContentType = "application/json";
        req.Method = "POST";
 
 
        req.KeepAlive = true;

        req.Headers.Add(baslik, icerik);
        req.Headers.Add(baslik2, icerik2);
        req.Headers.Add(baslik3, icerik3);

        req.Headers.Add("Cache-Control", "no-cache");

     
        string formvars = string.Empty;

       // string strPost = @"{quantity:""1"",price:""18,4"",stopPrice:""18,2"",newOrderClientId:""1"",orderMethod:""limit"",orderType:""buy"",pairSymbol:""USDTTRY""}";
        var payload = new orderParams
        {
            quantity = "10",
            price = "18,5",
            stopPrice = "18,2",
            newOrderClientId = "1",
            orderMethod = "limit",
            orderType = "buy",
            pairSymbol = "USDTTRY"
        };

        // Serialize our concrete class into a JSON String
        var stringPayload = JsonConvert.SerializeObject(payload);

  
        Byte[] byteArray = Encoding.UTF8.GetBytes(stringPayload);
     
        req.Timeout = 600000;
        req.Credentials = CredentialCache.DefaultCredentials;

         req.ContentLength = byteArray.Length;
         Stream reqStream = req.GetRequestStream();
        reqStream.Write(byteArray, 0, byteArray.Length);

       reqStream.Close();
        HttpWebResponse objResponse = (HttpWebResponse)req.GetResponse();
        StreamReader sr = new StreamReader(objResponse.GetResponseStream());
        string result = sr.ReadToEnd();
        sr.Close(); 
        return result;
`

**Comment by suleymanbyzt** [comment]
Selamlar,

İlettiğiniz parametre bilgilerini incelediğimde nokta yerine virgül ile ondalık sayı ilettiğinizi görüntülemekteyim. 

Hatalı decimal pattern sorunu nedeniyle 400 hatası almaktasınız. Sorun yaşamamak adına decimal cinsinden göndereceğiniz parametreleri nokta kullanarak iletmenizi rica edeceğim.
