### ISSUE TITLE
WebSocket OrderBook

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#506]
Websocket orderbook u dinlediğimde bu sonucu alıyorum.
[991,{"type":991,"current":"6.0.0","min":"2.3.0"}]
Bundan sonra tahtadaki emirlerin bilgisi geliyordu.
Programı yeniden başlattım fakat tahtadaki emirleri alamamaya başladım.

**Comment by suleymanbyzt** [comment]
Selamlar,

Socket'e nasıl bir mesaj iletiyorsunuz? Rica etsem bu issues'a yanıt olarak socket'e attığınız isteğe dair detayı iletebilir misiniz? 

Gerekli incelemeleri yaptıktan sonra bilgilendirme yapalım.

**Comment by akrepfatih** [comment]
Zaten çalışıyordu Süleyman bey. Şuan Tahtadaki emirleri göremiyorum.

                ClientWebSocket client = new ClientWebSocket();
                Uri _uri = new Uri("wss://ws-feed-pro.btcturk.com");
                await client.ConnectAsync(_uri, CancellationToken.None);
                string msg = "[151,{\"type\":151,\"channel\":\"orderbook\",event:" + Program.s_site_adi_A_Coin_1 + Program.s_site_adi_A_Coin_2 + ",\"join\":true}]";
                await client.SendAsync(buffer: new ArraySegment<byte>(array: Encoding.UTF8.GetBytes(msg), offset: 0, count: msg.Length), messageType: WebSocketMessageType.Text, endOfMessage: true, cancellationToken: CancellationToken.None);
                var buffer = new byte[1024 * 40];
                
                
                while (true)
                {
                    WebSocketReceiveResult result = await client.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
                    string resultMessage = Encoding.UTF8.GetString(buffer, 0, result.Count);
                    Debug.WriteLine(resultMessage);
                }

**Comment by suleymanbyzt** [comment]
Selamlar,

Tam olarak attığınız isteği ve aldığınız yanıtların hepsini iletebilir misiniz? Kodunuzla alakalı bir sorun göremedim lakin request içeriğini bilmediğimden net bir yorum yapamıyorum.

Socketten dönen tüm datayı iletebilirseniz daha detaylı inceleyebiliriz.

**Comment by akrepfatih** [comment]
Ben hatayı buldum Süleyman bey Önceden event i "" içinde yazmadan kabul ediyormuşsunuz ve kod çalışıyordu.
Bende burada hata yapmışım tırnak içine koymam gerekiyordu tırnak içine koyunca tekrar çalışmaya başladı.
İyi çalışmalar

**Comment by suleymanbyzt** [comment]
Sorunun çözülmüş olduğuna sevindim 🚀  Herhangi bir sorunda tekrar Github üzerinden ulaşabilirsiniz.

İyi günler dilerim
