### ISSUE TITLE
Private Endpoint Cancel Order dökümantasyonu örnek Node.Js kodunda ufak bir hata

### ISSUE THREAD

**Issue by Feraxion** [BTCTrader/broker-api-docs#507]
https://docs.btcturk.com/private-endpoints/cancel-order

Node.js örneği 5. satırda 
`const method = '/api/v1/order/ORDER_ID_HERE'`
yerine 
`const method = '/api/v1/order?id=ORDER_ID_HERE'`
olmalı sanırım, örnekteki method ile Bad Request alırken alttaki şekilde başarılı bir şekilde order iptali gerçekleştirilebiliyor.

**Comment by suleymanbyzt** [comment]
Selamlar,

Geri bildiriminiz için teşekkür ederiz. Dökümanda en yakın zamanda konuyla ilgili düzenleme yapılacaktır. 

İyi günler dileriz.
