### ISSUE TITLE
PriceMustBeLessThanMaxpriceError, ETHW için gelen sorun

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#508]
Emir alımı ve satımı yapılmamakta, bu bilgiyi nasıl alabilirim. Max fiyat bilgisini öğrenirsek yazılımlarla alım satım isteği girmeyiz @suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,

İlgili kriptopara için MaxPrice ve MinPrice değerlerini exchangeInfo endpointimizden görüntüleyebilirsiniz. https://api.btcturk.com/api/v2/server/exchangeinfo
```
            "minPrice": "187.80330744",
            "maxPrice": "281.70496116",
```

Konuyla ilgili daha fazla bilgi için dilerseniz BtcTurk Bilgi Bankasını inceleyebilirsiniz.
https://bilgibankasi.pro.btcturk.com/hc/tr/articles/360016740257-Yeni-Listelenen-Kriptoparalarda-Tavan-Taban-Fiyat-Uygulamas%C4%B1-Kurallar%C4%B1

**Comment by yemreak** [comment]
"Uluslararası fiyat" bilgisini nasıl hesaplıyorsunuz? bu bilgiyi alabileceğimiz API var mı? @suleymanbyzt
