### ISSUE TITLE
Piyasa alıcı emirler tamamlandığında ortalama fiyatı görme

### ISSUE THREAD

**Issue by cimbar** [BTCTrader/broker-api-docs#509]
Merhabalar,

Piyasa alıcı bir emir girildiğinde ve orderid ile "/api/v1/order/" metodu kullanıldığında, emir kapanmış olsa bile emrin gerekleştiği ortalama fiyatı değil emrin ilk iletildiği fiyatı görebiliyoruz. Yani emrin gerçekleştiği fiyat bilgisini elde edemiyoruz. Bunu nasıl sağlayabilirim, eğer herhangi bir yolu yoksa eklemeyi düşünüyor musunuz?

Bunun yanı sıra emir gerçekleştiğinde orderid ile ne kadar bir komisyon ödendiği de gönderilse yararlı olur. Kısacası yalnızca emir iletildiğinde görünen bilgiler yerine emir tamamlandığında da gerekli bilgiler gönderilmeli.

İyi çalışmalar

**Comment by suleymanbyzt** [comment]
Selamlar,

Parçalı gerçekleşen emir detaylarınıza /v1/users/transactions/trade endpointimizden ulaşabilirsiniz.

Bu endpoint ile ayrıca parçalı gerçekleşen emirleriniz için Fee ve Tax bilgilerini de görüntüleyebilirsiniz.
