### ISSUE TITLE
WebbSocket "orderbook" ve "obdiff" kanalları güncelliğini yitirdi 

### ISSUE THREAD

**Issue by SelcukCode** [BTCTrader/broker-api-docs#510]
1. Son 1 ay içerisinde yaptığınız güncellemeler sonrası bu servisler ağ üzerinde daha az trafik oluşturuyor. Bu olumlu. Ancak servisler artık eskisi gibi güncel veri veremiyor. 1 ila 3 saniye arası yeni verileri çoğunlukla güncellememiş oluyor. Bu da son kullanıcı trade ettikten 3 saniye sonrasına kadar halen eski orderbook tahtalarını görmesine sebep oluyor. 

2. WebSocket'teki bu güncellemelerinizin son kullanıcı tarafında oluşturduğu ikinci bir sorunu daha paylaşmak isterim. Eskiden 2 sunucudan aynı kanallara abone olduğumuzda aynı verileri alıyorduk, artık güncellemeler aynı şekilde olmuyor. Bir server'da "obdiff" kanalından değişiklik verisi gelebiliyorken diğer serverda gelmeyebiliyor. Tabii ki bu demek değil ki tahtalar güncel değil. 2 serverda da tahtalar güncel kalabiliyor. Ancak özellikle tüm tahtalarınızda (USDTTRY hariç) **_aynı fiyat ve miktar için_** çok sık CP":1 ve "CP":3 şeklinde veri girişi oluyor. Bu tahta güncellemelerinin neden bazı serverlara ulaşıp bazı serverlara ulaşmadığını açıklıyor çünkü ekle ve çıkar şeklinde ardışık gelen emir tahtanın güncelliğini bozmuyor. Yine de abone olan tüm serverların aynı güncellemeleri alması tutarlılık açısından önemli.

3. İkinci maddede bahsettiğim **_aynı fiyat ve miktar için_** CP":1 ve "CP":3 şeklinde ardışık gelen emirler o kadar sık ki tahtaların çok sahte durmasına ve fake hareket yapmasına sebep oluyor. Tamam bunu bir yatırımcı da algoritmik olarak yapabilir ancak hiç bir yatırımcının USDT hariç diğer bütün token/kripto paraları elinde bulundurması ve bu hareketi yaptırması mantıklı gözükmüyor.

Bu sorunları farkeden başka algoritmik trade yapan kişiler varsa ve yorum yaparsa konuyu zenginleştirebilir.

**Comment by suleymanbyzt** [comment]
Selamlar,
Yaşadığınız durumu detaylıca inceleyebilmemiz için sıklıkla sorun yaşadığınız pairleri ve yaptığınız işlemlere ait IP adresinizi suleyman.bayazit@btctrader.com adresine mail olarak iletebilir misiniz? İnceleme yaptıktan sonra size dönüş yapacağız.

**Comment by SelcukCode** [comment]
> Selamlar, Yaşadığınız durumu detaylıca inceleyebilmemiz için sıklıkla sorun yaşadığınız pairleri ve yaptığınız işlemlere ait IP adresinizi [suleyman.bayazit@btctrader.com](mailto:suleyman.bayazit@btctrader.com) adresine mail olarak iletebilir misiniz? İnceleme yaptıktan sonra size dönüş yapacağız.

Merhaba Süleyman Bey. İstediğiniz bilgiler ile birlikte araştırmanızı kolaylaştıracağını düşündüğüm bir miktar log verisini de size mail olarak ilettim. Şimdiden ilginiz için teşekkür ederim.

**Comment by suleymanbyzt** [comment]
Selamlar,

İlettiğiniz detaylı bilgilendirmeler için teşekkür ederiz. Mail üzerinden gerekli bilgilendirmeleri ilettim.

İyi günler dileriz.
