### ISSUE TITLE
Web | Mobil istemci Too mant retries sorunu

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#511]
- Merhabalar, LUNC - LUNA gibi varlıkları alırken miktar sınırlaması mevcut 
- Yüksek miktarda da alım yapmak için de birden fazla emir vermek gerekiyor
- Web veya mobil üzerinden birden fazla emir vermeye çalıştığımızda da `Too many retries` bildirimi geliyor
- Bekleyerek emirleri verdiğimizde de piyasa değişiyor, alım / satım fırsatı kaçmış oluyor
- Bunun için çözüm öneriniz nedir, neden 2s gibi bir bekleme süresi konuluyor mobil ve web işlemlerine? @suleymanbyzt

**Comment by suleymanbyzt** [comment]
Selamlar,
Rate limitler herkese eşit olanaklar sunmak için var bu nedenle mobil ve web üzerinde de rate limit sınırlaması yapmaktayız.
Daha fazla bilgiyi [Rate Limits - BtcTurk | PRO API Documentation](https://docs.btcturk.com/rate-limits) sayfamızdan inceleyebilirsiniz.

**Comment by yemreak** [comment]
Selam, verdiğiniz cevap konudan bağımsız ve yardımcı olma niteliğinde değil. Neden yaptığınızı sormadım ki.
Soruyu tekrar gözden geçirmenizi talep ediyorum
@suleymanbyzt

**Comment by suleymanbyzt** [comment]
Merhaba,
Şirket politikamız gereği kullanıcılarımıza eşit şartlar sunmak için oluşturduğumuz Rate Limit uygulamamız mobil ve web platformlarımız için bu şekildedir. İki emir girişi arasındaki 2 saniyelik limiti atlamanız mobil ve Web platformlarımız üzerinden mümkün değil. Dökümanımıza uygun API entegrasyonu yapmanız durumunda 2 saniyelik bir bekleme süresine takılmadan belirlenen rate limitler dahilinde API ile işlem yapabilirsiniz.
API işlemlerinizde de rate limite takılmamak adına kodunuzda Rate Limits - BtcTurk | PRO API Documentation sayfamıza uygun rate limit düzenlemeleri yapmanız gerekmektedir.

**Comment by yemreak** [comment]
Teşekkür ederim
