### ISSUE TITLE
Geçmişe yönelik veri çekme

### ISSUE THREAD

**Issue by 0xAltar** [BTCTrader/broker-api-docs#512]
Merhabalar, paritelerin geçmişe yönelik açılış, kapanış, en yüksek, en düşük fiyatlarını ve günlük hacmini API ile çekebilir miyim? mümkün müdür?

**Comment by akrepfatih** [comment]
https://docs.btcturk.com/public-endpoints/get-kline-data
Burası çalışıyorsa buradan çekebilirsin.
https://graph-api.btcturk.com/v1/klines/history?from=1602925320&resolution=60&symbol=BTCTRY&to=1603152000
Ben denedim veri geliyor. İyi çalışmalar.

**Comment by MrRatel** [comment]
> https://docs.btcturk.com/public-endpoints/get-kline-data Burası çalışıyorsa buradan çekebilirsin. https://graph-api.btcturk.com/v1/klines/history?from=1602925320&resolution=60&symbol=BTCTRY&to=1603152000 Ben denedim veri geliyor. İyi çalışmalar.

Merhabalar; kline verileri ile çalışırken 429 hatası alıyorum dökümanlardan çok fazla istek yolladığım için bu hatayı aldığımı öğrendim ancak rate limits sayfasında genel istekler için dakikada 600 istek sınırı görünüyor ve kline verileri için özelleştirilmiş bir sınırlama yok. Benim gönderdiğim istekler dakikada 150 civarında bir sayıya sahip. Acaba Kline verileri için istek sınırlaması nedir? Bilginiz varsa aydınlatırsanız sevinirim. İyi çalışmalar

**Comment by suleymanbyzt** [comment]
Selamlar,
Paritelere ait geçmiş açılış, kapanış, en yüksek ve en düşük değerlerini OHLC ya da Kline endpointlerimizden görüntüleyebilirsiniz.

OHLC: https://docs.btcturk.com/public-endpoints/ohcl-data
Kline: https://docs.btcturk.com/public-endpoints/get-kline-data
