### ISSUE TITLE
/api/v1/users/transactions/crypto parametreleri

### ISSUE THREAD

**Issue by serensoner** [BTCTrader/broker-api-docs#513]
merhabalar, /api/v1/users/transactions/crypto  adresine gonderilen requestlerde eger startType tanimlanmadiysa diger parametreler dikkate alinmiyor API tarafindan. ornek vermek gerekirse:

* `requests.get(url=uri, headers=headers, params={'startDate': 1664898171083, 'type': 'deposit'})` => sadece 4 ekim 17.42'den itibaren olan depositleri gosteriyor.
* `requests.get(url=uri, headers=headers, params={'startDate': 1664898171083})` => sadece 4 ekim 17.42'den itibaren olan islemleri gosteriyor (deposit ve withdrawal)
* `requests.get(url=uri, headers=headers, params={)` => herseyi gosteriyor.
* `requests.get(url=uri, headers=headers, params={'type': 'withdrawal)` => yine herseyi gosteriyor.

symbol parametresini ise kullanmayi hic basaramadim.

**Comment by suleymanbyzt** [comment]
Selamlar,
Test yaparken symbol parametresinde bug olduğunu geri bildiriminiz sayesinde farkettiğimizden gerekli düzenlemeleri yapıp fix geçtik.
Geri bildiriminiz için teşekkür ederiz 🚀
