### ISSUE TITLE
Kline Verileri İstek Sınırları

### ISSUE THREAD

**Issue by MrRatel** [BTCTrader/broker-api-docs#514]
Merhabalar; kline verileri ile çalışırken 429 hatası alıyorum dökümanlardan çok fazla istek yolladığım için bu hatayı aldığımı öğrendim ancak rate limits sayfasında genel istekler için dakikada 600 istek sınırı görünüyor ve kline verileri için özelleştirilmiş bir sınırlama yok. Benim gönderdiğim istekler dakikada 150 civarında bir sayıya sahip. Acaba Kline verileri için istek sınırlaması nedir? Aydınlatırsanız sevinirim. İyi çalışmalar

**Comment by suleymanbyzt** [comment]
Merhaba,
Dakikada 150 istek ile Kline endpointinde rate limitlere takılmamanız gerekmekte, mevcut rate limit 150'nin üzerinde. Diğer endpointlerle alakalı rate limitinizde sıkıntı yaşıyor olabilirsiniz.
Rate limitlere takılmamak için kodunuzda Rate Limits - BtcTurk | PRO API Documentation sayfamıza uygun düzenlemeler yapabilirsiniz. Kline ve OHLC için en kısa zamanda dökümanda güncellemeler yapılacaktır.
Geri bildirim için teşekkür ederiz.
