### ISSUE TITLE
API ile Alış-Satış

### ISSUE THREAD

**Issue by nanomusty** [BTCTrader/broker-api-docs#517]
Merhaba,
API dokümanı çok anlaşılır olmadığı için soru sormak durumunda kaldım.
![image](https://user-images.githubusercontent.com/7986631/195255256-63d045a9-197b-4d87-b0a8-44e3869cc558.png)

burada ne demek istediniz? ben anlamadığım yerleri sorayım. 
1. 0.001 quantity ne anlama geliyor? benim bakiyemden 0.001 btc var onu satacağım demek mi oluyor?
2. 40 000 price ne demek? 40000 tl'lik btc mi sat demek ben anlamadım burasını...
3. NewOrderClientId string bir  değer mi alıyor? oraya "mustafa"
 yazsam da yeni bir order oluşturur mu?
4. pair sembol sanırım btc yi satacaksın try cinsinden değil mi?

API dokümanını daha anlaşılır yazarsanız soru sormaz kimse (Yanlış anlamayın öneri bu :))

**Comment by akrepfatih** [comment]
quantity alacağın yada satacağın adet
price alacağın yada satacağın fiyat
neworderclientid istediğini yazabilirsin
ordertype alış mı satış mı yapacaksın burada belirtiyorsun
pairsymbol hangi işlem çiftinde işlem yapacağın.

Not : alış ve satış lar da fiyat ve adet için . nokta ve , virgül e dikkat et ( Server kuruşlar için nokta kullanır. Senin TR kullanıyorsan virgül kullanır.

**Comment by nanomusty** [comment]
Süpersin. teşekkür ederim. Çok açıklayıcı oldu..

**Comment by nanomusty** [comment]
Merhaba,
Son bir soru sormak istiyorum. Şöyle bir servisiniz var mı? 
Mesela benim 1000 TL param var TRY hesabımda. Bununla kaç adet (quantity) BTC alabilirim? 
bunun cevabını veren bir metod var mı?

**Comment by akrepfatih** [comment]
Bunun için matematik bilgisi yeterli arkadaşım. paran / alış fiyatı = adet
diyelim ki btc 360000 tl
1000/360000=0,00277777777777777777777777777778 adet alabilirsin.
tabi bunu bu şekilde alamazsın çünkü işlem çifti 8 haneyi desteklediği için bunu 8 haneye düşürmen gerekir.
Oda 0,00277777 adet alabileceğin anlamına gelir.
hangi İşlem çiftinin kaç hane desteklediğini bulmak için info dan verileri çekmen gerekir.

Sanırım şimdi olay biraz karışık olmaya başladı. :)

**Comment by nanomusty** [comment]
peki. teşekkür ederim

**Comment by nanomusty** [comment]
Selam,
1 kere alış-satış yaptım sonrasında herhangi bir değişiklik yapmadım ama **400 BadRequest** hatası vermeye başladı. Acaba saat sınırı mı var? IP aynı, key ve secret de aynı. :(

**Comment by suleymanbyzt** [comment]
Selamlar,

Size daha iyi yardımcı olabilmem için attığınız request'i ve aldığınız response'u yanıt olarak iletebilir misiniz? inceleyip size detaylıca dönüş yapayım.
