### ISSUE TITLE
TESTNET 

### ISSUE THREAD

**Issue by farukomerballi** [BTCTrader/broker-api-docs#519]
Merhaba,

https://pro-dev.btcturk.com ve https://api-dev.btcturk.com/ URL'ler çalışmıyor. 

Bir problem mi var acaba?

**Comment by suleymanbyzt** [comment]
Selamlar,
Dev ortamına public olarak erişim şu an için bulunmamaktadır. İlerleyen zamanda bir değişiklik olması durumunda dökümandan gerekli duyurular yapılacaktır.
