### ISSUE TITLE
order eklemeye calistigimda ORDER_INSERT_BLOCKED donuyor fakat exchangeinfo status: TRADING donduruyor.

### ISSUE THREAD

**Issue by serensoner** [BTCTrader/broker-api-docs#520]

**Comment by suleymanbyzt** [comment]
Selamlar,
19 Ekim tarihinde teknik bir aksaklık nedeniyle bazı pairler için çalışmalar yapmamız gerekti. Bu süreçte ilgili pairler için insert, cancel ve update işlemleri yapılamadığından emir girilmeye çalışıldığında ORDER_INSERT_BLOCKED bilgisi döndürüldü. 
Ayrıca bahsetmiş olduğunuz status kısmı ilgili pair'in aktifliği ile ilgili bağlantılı bir durum değildir. Bu tarz anlık gelişmeleri [https://status.btcturk.com/ ](https://status.btcturk.com/)sayfamızdan takip edebilirsiniz.

**Comment by serensoner** [comment]
selamlar, cevap icin tesekkurler. bu tarz teknik aksakliklar oldugunda, api ile alabilecegimiz tek yer burasi. yatirma/cekme islemlerinde bir sikinti oldugunda exchangeinfo uzerinden alabiliyoruz. pairlerde bakim oldugunda bu status'un de (ayni status.btcturk.com'un dondurdugu gibi) trading yerine MAINTENANCE gibi bir deger dondurmesini saglayabilir misiniz?
