### ISSUE TITLE
get-crypto-transactions depositler icin isConfirmed daima False donduruyor.

### ISSUE THREAD

**Issue by serensoner** [BTCTrader/broker-api-docs#521]

**Comment by suleymanbyzt** [comment]
Selamlar,

Geri bildiriminiz için teşekkür ederiz. İlgili ekiplerimize konu hakkında gerekli bilgilendirmeler yapıldı. Konu ile ilgili fix geçildiğinde size bilgilendirme yapacağım.

**Comment by suleymanbyzt** [comment]
Selamlar,

Konu hakkında gerekli düzenlemeler yapılmıştır. Geri bildiriminiz için teşekkür ederiz.
