### ISSUE TITLE
Websocket BalanceUpdated 

### ISSUE THREAD

**Issue by hamzaolak** [BTCTrader/broker-api-docs#522]
BalanceUpdated ile gelen datalarda 

`{"type":201,"userId":xxxxxx,"payload":"59,18,7"}`
`{"type":201,"userId":xxxxxx,"payload":"104,34,7"}`
`{"type":201,"userId":xxxxxx,"payload":"132,48,7"}`

bu payloadların manası nedir acaba ?

**Comment by suleymanbyzt** [comment]
Selamlar,
Buradan gerekli bilgilendirmeleri inceleyebilirsiniz. #478
