### ISSUE TITLE
Test apisine giriş yapamıyorum

### ISSUE THREAD

**Issue by naitz1337** [BTCTrader/broker-api-docs#523]
https://pro-dev.btcturk.com/

![unknown](https://user-images.githubusercontent.com/54092838/199369323-726dd7e4-387b-494f-a4dd-a1137654b86d.png)

bu web bağlantısına giriş yaptığımda Access Denied ile karşılaşıyorum, yardımcı olabilir misiniz?

**Comment by suleymanbyzt** [comment]
Selamlar,

Test ortamına girişler şu an için aktif değil. İlerleyen süreçte bir değişiklik olması durumunda dokümantasyon üzerinden gerekli bilgilendirmeler yapılacaktır.
