### ISSUE TITLE
ticker eski veriler donduruyor

### ISSUE THREAD

**Issue by serensoner** [BTCTrader/broker-api-docs#524]
merhabalar,

bugun saat 21:54 - 22:01 arasi gozlemledigim bir durum var. halen de devam ediyor aslinda.

DOGE_TRY, ETH_TRY ciftlerini takip ettigim icin bunlarda kesin olarak gordugum bir durum. soyle bir sikinti yasaniyor: ticker, bir gecmisten bir de simdiden veri donduruyor. ticker'i her refreshte kaydetmedigim icin data sunamiyorum ama DOGE_TRY'den ornek vererek durumu paylasacagim. 

hem bid, hem ask, emir defteri 2.48'lerdeyken, bid 2.5572 dondurdu. daha sonra 2.4839 dondurup, sonra tekrar 2.5611 dondurdu. her refresh'te, sanki bir ileri bir geri gidiyor gibi..

**Comment by serensoner** [comment]
hala oluyormus, data [burada](https://pastebin.com/sT2nd0JP): olay oldugu andaki bir dakikalik grafige bakarsaniz DOGE_TRY'nin fiyatinin verilen bid/ask civarinda olmadigini gorebilirsiniz.

**Comment by serensoner** [comment]
bir ornek daha:

```
import requests
import time
import pandas as pd

url = 'https://api.btcturk.com/api/v2/ticker?pairSymbol=APETRY'
results = {}
for i in range(1000):
    results[time.time()] = requests.get(url).json()['data']
    time.sleep(1)

df = pd.DataFrame(results).transpose()
df_exploded = df[0].apply(pd.Series)
df_exploded['ask'].to_csv('asks.csv')
```

donen sonuclar:

```
x,ask
1667417778.7545938,79.94
1667417779.8992891,80.35
1667417781.0645201,81.45
1667417782.217599,80.11
1667417783.3490815,80.11
1667417784.544586,80.1
1667417785.7198195,80.1
1667417786.8789213,81.42
1667417788.0145519,80.09
1667417789.168064,80.09
1667417790.3513546,80.1
1667417791.6174543,80.09
1667417792.8342698,80.08
1667417794.0141487,81.38
1667417795.1691895,80.08
1667417796.3610735,80.08
1667417797.5103126,80.07
1667417798.6679857,81.36
1667417799.80425,80.06
1667417800.9542613,80.05
1667417802.2960813,81.29
1667417803.4572654,80.04
1667417804.7943552,81.35
1667417805.97078,80.04
1667417807.1042001,80.03
1667417808.241903,80.04
1667417809.3884375,81.06
1667417810.5743532,80.01
1667417811.8047307,80.01
1667417813.0043628,80.01
```

**Comment by suleymanbyzt** [comment]
Selamlar,
Konu ile ilgili gerekli düzenlemeler yapılıp, sorun tamamen düzeltildi. Geri bildirim için teşekkür ederiz.
