### ISSUE TITLE
ApiV1 ile banka hesabına para çekme/ yatırma ?

### ISSUE THREAD

**Issue by ghost** [BTCTrader/broker-api-docs#525]
Api dokümantasyonunda btctürk hesabında kayıtlı bankadan para çekme ve yatırma işlemleri için bir kaynak bulamadım. Böyle birşeyi api ile yapabilir miyim ? 

Yardımcı olursanız sevinirim. C# ile geliştirme yapıyorum.

**Comment by ghost** [comment]
Konuyla ilgili hala bir bilgiye ulaşamadım. Api üzerinden para çekmek ve yatırmak istiyorum.

**Comment by suleymanbyzt** [comment]
Selamlar,

TL çekme işlemleri API aracılığı ile yapılamamaktadır. TL çekme işlemlerinizi mobil uygulamamız üzerinden ya da web sitemizden gerçekleştirebilirsiniz.
