### ISSUE TITLE
Ticker ve Orderbook API'ları Geçmiş Verileri Gönderiyor

### ISSUE THREAD

**Issue by lwampa** [BTCTrader/broker-api-docs#526]
API'lar geçmiş fiyatları gönderiyor, yaklaşık 12 saattir bu sorun devam etmekte.

İki resim arasında 1-2 saniye fark var ama ilk fiyatlar güncelken ikinciler geçmiş tarihe ait.
![Ekran Alıntısı2](https://user-images.githubusercontent.com/94573083/199663098-a8bc18f4-8959-4c13-870e-bb9224d52a34.JPG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/94573083/199663102-54dc8b3e-1888-42b8-ad59-394fcc2f978c.JPG)

**Comment by emrecg** [comment]
aynı sorun devam ediyor

**Comment by suleymanbyzt** [comment]
Selamlar,
Konu ile ilgili gerekli düzenlemeler yapılıp, sorun tamamen düzeltildi. Geri bildirim için teşekkür ederiz.
