### ISSUE TITLE
orderbook eski değerler geliyor

### ISSUE THREAD

**Issue by emrecg** [BTCTrader/broker-api-docs#527]
orderbook değerleri SAÇMA SAPAN değerler geliyor 12 saattir cevap verilmemiş destek talebi var . canlı destek direk burdan iletişime geçebilirsiniz diyor hangi mantıgın ürünüdür. Çalışan orderbook a dokunmak anlam veremiyor. Acil düzeltimesi gerekiyor. Edilen zararı siz tazmin etmiyorsunuz...

**Comment by suleymanbyzt** [comment]
Selamlar,
Konu ile ilgili gerekli düzenlemeler yapılıp, sorun tamamen düzeltildi. Geri bildirim için teşekkür ederiz.
