### ISSUE TITLE
python api alım satım hatası bakıye yeterlı olmasına ragmen al sat yapamıyırum

### ISSUE THREAD

**Issue by levent033** [BTCTrader/broker-api-docs#530]
![BTCTURK HATA](https://user-images.githubusercontent.com/43087802/208665694-1ad97522-9038-4a08-afaf-4c84181a4a97.png)

**Comment by levent033** [comment]
bakiyem emirde kilitliymiş iki gündür hatayı arıyorum:D

**Comment by suleymanbyzt** [comment]
Selamlar,
Sorunu çözmüş olduğunuza sevindim. Farklı bir sorunuz olması durumunda tekrar gelebilirsiniz.
İyi günler dilerim.
