### ISSUE TITLE
Balances Metodunda Try Bazında Birim Maliyet Fiyatı Eklenmesi Hk

### ISSUE THREAD

**Issue by Arhandx** [BTCTrader/broker-api-docs#531]
Merhabalar,
Ben api hizmetinizi kullanarak borsanizda al-sat işlemleri yapıyorum.O an sahip olduğum kripto varlıkların Try bazında birim maliyetini tutmak bot yazılımıma ekstra maliyet ve is yükü doğuruyor.Rica etsem Balances metoduna her kripto varlık için ayrı ayrı  o anki sahip olduğum değerlerin Try bazında birim maliyet fiyatını ekleme şansıniz varmıdır? Tıpkı BtcTurk Pro mobil uygulamasındaki Kar-Zarar bölümünde olduğu gibi, Böyle bir düzenleme gerçekten çok işime ve api hizmetinizi kullananların çok işine yarar düşüncesindeyim.Bu konuda Yardimci olursanız çok sevinirim,iyi çalışmalar.

**Comment by suleymanbyzt** [comment]
Selamlar,
Öncelikle öneriniz için teşekkür ederiz.Önerinizi değerlendirilmesi üzerine ekibimize ileteceğim. Herhangi bir geliştirme olması durumunda bu issues altında geri bildirimde bulunacağım.
