### ISSUE TITLE
Websocket üzerinden bakiye değişikliklerini bildirecek misiniz?

### ISSUE THREAD

**Issue by yemreak** [BTCTrader/broker-api-docs#532]
- Rest API kullanmaya gerek kalmadan tüm `balance` bilgilerini ws ile alma şansımız olacak mı?
- Böyle bir geliştirme planlanıyor mu ?
- Örn: 
    - Alım satım sonrasında güncel bakiye bilgisini ws kanalından verebilirsiniz
    - Şu anda sanırım sadece bakiye değişti bilgisi veriliyor

**Comment by suleymanbyzt** [comment]
Selamlar,
Bunun için şu an bir planlamamız bulunmuyor. İlerleyen süreçte bir değişiklik olması durumunda [Recent changes - BtcTurk | PRO API Documentation](https://docs.btcturk.com/recent-changes) sayfamızdan gerekli duyurular yapılacaktır.
