### ISSUE TITLE
timeInForce for creating order

### ISSUE THREAD

**Issue by ottoshark** [BTCTrader/broker-api-docs#533]
hi,

are you planning to activate timeInForce parameter for creating orders? I saw websocket response included timeInForce:None field. It would be very useful to use ImmediateorCancel or FillorKill options for that.

**Comment by suleymanbyzt** [comment]
Hi,

We currently don't have a plan for this. If there is a change in the future, we will announce it on the [Recent changes - BtcTurk | PRO API Documentation](https://docs.btcturk.com/recent-changes) page. By the way, can you let us know from which websocket channel you received the timeInForce:none parameter?
