### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by Mrelden** [BTCTrader/broker-api-docs#534]
Merhaba abilerim ablalarım ben öğrenciyim ufaktan birikim yaptım btc Türk hesabıma bot bağlamak istiyorum yardımcı olabilirmisiniz

**Comment by suleymanbyzt** [comment]
Selamlar,
[General Information - BtcTurk | PRO API Documentation](https://docs.btcturk.com/) dökümantasyonumuzdan gerekli olan tüm bilgilere ulaşabilir, destek olmamızı istediğiniz teknik konular için ise Github üzerinden talepte bulunabilirsiniz.

**Comment by Mrelden** [comment]
Abi bana yardımcı olabilirmisin
