### ISSUE TITLE
pairSymbol kullanmadan allorders cagirmak

### ISSUE THREAD

**Issue by serensoner** [BTCTrader/broker-api-docs#535]
merhaba,

https://docs.btcturk.com/private-endpoints/all-orders adresinde de goruldugu uzere pairSymbol zorunlu. eger tum orderlari cekmek istiyorsak sirasiyla butun pairler icin tek tek cagirmamiz gerekiyor api'i. bu da hem sizin hem bizim icin ekstra yuk demek. pairSymbol zorunlu olmaktan cikarilabilir mi? web sitesinden https://pro-bff.btcturk.com/v1/order-history?&startDate=2022-12-10&endDate=2023-01-11 seklinde bu yapilabiliyor.

tesekkurler

**Comment by suleymanbyzt** [comment]
Selamlar,
Öneriniz için teşekkür ederiz. Konu ile ilgili önerinizi ekibimize iletiyor olacağım. Herhangi bir geliştirme olması durumunda size bilgilendirme yapacağım.
İyi günler dilerim
