### ISSUE TITLE
Rate Limit hakkında

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#536]
https://docs.btcturk.com/rate-limits
/api/v1/order post ve delete

1 hesaptan veya ip den 60 saniyede 300 emir girebilirim ve 300 emir kaldırabilirim. Fazlasını yapmaya çalışırsam 60 saniye bloke olurum.
1 hesaptan veya ip den 1 saniyede 10 emir girebilirim ve 10 emir kaldırabilirim. Fazlasını yapmaya çalışırsam 1 saniye bloke olurum.
Buradan anladığım doğru mu?

yada

1. ip den 1 saniyede 10 emir girebilirim.
2. ip den 1 saniyede 10 emir girebilirim.
3. ip den 1 saniyede 10 emir girebilirim.
Şu an 1 saniyede 30 emir girebiliyorum. 30 * 60 = 1800 emir hesaba düşen dakika daki emri sayısı olur.

yada

1. ip den 60 saniyede 300 emir girebilirim.
2. ip den 60 saniyede 300 emir girebilirim.
3. ip den 60 saniyede 300 emir girebilirim.
Şu an 60 saniyede hesaba düşen 900 emir.

Şu anda 2 ip ile tek hesaba bağlı olarak bot çalıştırıyorum ve hiç blok yemedim. Bunu 4 ip ye çıkartmayı ve daha fazla coin de oynamayı düşünüyorum yoksa 1 ip ye düşen 1 saniyedeki 10 emir sayısını geçerim ve bloke yerim. 4 e çıkartırsam hesap bloke yer miyim?

**Comment by serensoner** [comment]
benim de bir rate limit sorum olacak. too many requests hatasi aliyorum, fakat uzun bir süre request göndermesem bile resetlenmiyor blok. ip'deki blokun kaldirilmasi icin ne yapabilirim?

not: ticker ve exchangeinfo gibi endpointlerde değil, sadece authentication olan endpointlerde var rate limit

**Comment by suleymanbyzt** [comment]
Selamlar,
v1/order endpointi hem account hem de ip bazlı bir sınırlama bulunmaktadır. İşlem yaptığınız hesap için 
1 saniyede maksimum 10 istek
1 dakikada maksimum 300 istek atabilirsiniz.
Farklı ip'lerden gelseniz bile account bazlı da bir sınırlama olduğundan ip bazındaki limite takılmasanız dahi account üzerinde belirlenen limitin üstünde işlem yapmaya çalıştığınızda hata alacaksınız.
Bu nedenle v1/order POST ve DELETE methodları için hesabınızdan dakikada 300 ya da saniyede 10 sınırlamasını aşmadığınız sürece bir problem olmayacağını bildirmek isterim.

Daha fazla bilgi için [Rate Limits - BtcTurk | PRO API Documentation](https://docs.btcturk.com/rate-limits) sayfamızı inceleyebilirsiniz.

@serensoner 429 hatası aldığınızda response'den kaç saniye sonra tekrar deneyebileceğinize dair bilgilendirme geçiyoruz bu periyotun tamamlanması sonrasında tekrar istek atabilirsiniz.

**Comment by akrepfatih** [comment]
Emir girme süresi yaklaşık 150ms,  kaldırma süresi yaklaşık 350ms sürüyor. Toplam yaklaşık 500ms diyebiliriz. Buda 1 coin alış  için saniyede 2 emir giriyorum, satış içinde aynısını düşünürsek 1 saniyede 1 coin için 4 emir girmem demektir.
1. coin için 4 emir.
2. coin için 8 emir.
3. coin i devreye sokmaya çalışırsam 12 emir / saniye olacak (bu işlemlerin hepsi aynı saniye ye denk gelirse) ve 1 saniyede 10 işlem i geçtiğim için bloke olacağım. işlemlerim çok sık olursa da 2 coin ile oynuyor olsam bile 60*8 = 480 emir girişi olacağı için bloke olacağım. 

Bu 1 sn de 10 işlem az değil mi ?
Dakikanın 300 den 600 e çıkartılması mantıklı değil mi? ( 1sn 10 işlem ise 60 saniye 600 işlem)
1 sn bloke süresi belki sineye çekilebilir. Ama 60 sn bloke süresi biraz fazla değil mi ? Bu piyasada 1 dakikada yer yerinden oynuyor %5 %10 gibi kayıplar yaşanabilir.

**Comment by suleymanbyzt** [comment]
Selamlar,
Tüm kullanıcılarımıza eşit şartlar altında hizmet sunmak adına ilgili limitler belirlenmiştir. Konu ile ilgili bir gelişme olması durumunda [Recent changes - BtcTurk | PRO API Documentation](https://docs.btcturk.com/recent-changes) sayfamızdan gerekli bilgilendirmeler yapılacaktır.  
İlginiz için teşekkür ederiz.
