### ISSUE TITLE
api/v1/users/transactions/crypto onay bekleyen yatirma islemlerini gostermiyor

### ISSUE THREAD

**Issue by serensoner** [BTCTrader/broker-api-docs#537]
merhabalar, /api/v1/users/transactions/crypto endpoint'ine type=deposit seklinde yaptigimiz islemlerde onay bekleyen yatirma islemleri gorunmuyor. ancak yatirma tamamlandiktan sonra goruntulenmeye basliyor.

**Comment by suleymanbyzt** [comment]
Selamlar,
Öneriniz için teşekkür ederiz. Değerlendirilmesi üzerine konuyu ilgili ekiplerimize ilettim. Herhangi bir geliştirme olması durumunda https://docs.btcturk.com/recent-changes sayfamızdan gerekli duyurular yapılacaktır.
