### ISSUE TITLE
Electrum wallet ile btc den fiat paraya dönüş

### ISSUE THREAD

**Issue by vizzet** [BTCTrader/broker-api-docs#538]
Burası uygun yer mi bilmiyorum ama, btc ile satış yapıp, elimdeki btcleri fiat paraya çevirmek için bir platforma ihtiyacım olacak. Amacım coin trading değil.

BTCTurk bu işi için uygun bir yer midir?

**Comment by akrepfatih** [comment]
https://pro.btcturk.com/pro/al-sat/BTC_TRY
Buradan elindeki BTC leri TRY çevirebilir. Sonrada banka transferi ile TRY leri Banka adresine yollayabilirsin.
Hatırladığım kadarıyla bankadaki hesabın btcturk deki hesap ile uyuşması gerekiyor. Yani adı soyadı.

**Comment by vizzet** [comment]
Teşekkürler.
