### ISSUE TITLE
Coin Trade e açık mı kapalı mı ?

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#540]
Bazen coinler alış satışa kapatılıyor. Bunu öğrenebildiğim api exchangeinfo>data>symbols>status mü?
Eğer yol doğru ise
TRADING sonucu = alış satış a açık anlamına geliyor.
Kapalı olunca sonuç ne gönderiliyor ?
TRADING dışında tüm sonuçlar alış satışa kapalı mı oluyor ?

**Comment by suleymanbyzt** [comment]
Selamlar,
API aracılığıyla işlem çiftinin status'u doğrudan sorgulanamamaktadır, ancak ilgili çift işlemlere kapatıldığında insert ve cancel işlemleri yapmaya çalıştığınızda, bu durumu response'da bildiriyoruz.

Örneğin, eğer pair işlemlere kapatılmışsa;

Insert işlemi yapmaya çalıştığınızda, aşağıdaki hata mesajını alırsınız:
{"httpStatusCode":400,"data":null,"success":false,"message":"ORDER_INSERT_BLOCKED","code":8005}

Cancel işlemi yapmaya çalıştığınızda, aşağıdaki hata mesajını alırsınız:
{"httpStatusCode":400,"data":null,"success":false,"message":"ORDER_CANCEL_BLOCKED","code":8006}

Bununla birlikte dilerseniz yatırma/çekme, al/sat, API, Mobil ve Web platformlar gibi kanalların durumlarını takip etmek için https://status.btcturk.com/ sitesine abone olarak, mail yoluyla bildirim alabilirsiniz.
