### ISSUE TITLE
Tüm IP'lere İzinli API Key Talebi

### ISSUE THREAD

**Issue by felmasgunes** [BTCTrader/broker-api-docs#541]
Türkiye şartlarında kesintisiz bir internete sahip olmak çok mümkün olmadığı için internet kopmalarında ip adresim değişiyor. Bu yüzden kullandığım api key geçersiz kalıyor. Tüm IP'lerden kullanıma izin veren bir api key'e ihtiyacım var. destek@btcturk.com üzerinden bu isteği talep ettiğimde buraya yönlendirdiler. Nasıl yardımcı olabilirsiniz?

**Comment by suleymanbyzt** [comment]
Selamlar,
Kullanıcılarımızın güvenliği nedeniyle almış olduğumuz bu önlem neticesinde tüm IP'lerden erişilebilen bir key oluşturma işlemi yapılamamaktadır. Dilerseniz internet servis sağlayıcınız ile iletişime geçerek, statik IP hizmetini hattınıza tanımlayabilirsiniz. Anlayışınız için teşekkür ederiz.

**Comment by felmasgunes** [comment]
Kendi güvenliğimi kendim sağlayabileceğimi düşünerek böyle bir seçimi bize bırakırsanız daha mantıklı olur. Örnek binance api.
