### ISSUE TITLE
Tüm Siparişler

### ISSUE THREAD

**Issue by Vortlan** [BTCTrader/broker-api-docs#543]
"/api/v1/allOrders?pairSymbol=BTCTRY&startTime=1677073424290" Kodunu kullandığımda hata alıyorum yardımcı olabilir misiniz
![resim_2023-02-23_164728578](https://user-images.githubusercontent.com/86024277/220925394-9d150794-edda-49f1-a031-6ccd1e5ceba2.png)

**Comment by suleymanbyzt** [comment]
Selamlar,
Attığınız isteği incelediğimde startTime parametresini millisecond cinsinden gönderdiğinizi görüntülüyorum. startTime ve endTime parametrelerini unix time second cinsinden göndermeniz durumunda isteğiniz başarılı bir şekilde gerçekleşecektir.

Örnek istek:
`/api/v1/allOrders?pairSymbol=BTCTRY&startTime=1677073424`

**Comment by Vortlan** [comment]
Merhaba Süleyman Bey,

Yardımınız için teşekkür ederim.

İyi çalışmalar dilerim
Saygılarımla
Umut

Süleyman Bayazit ***@***.***>, 7 Mar 2023 Sal, 15:43
tarihinde şunu yazdı:
