### ISSUE TITLE
C# WebSocket orderbook

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#544]
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll ("The server returned status code '429' when status code '101' was expected.") Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll ("The server returned status code '429' when status code '101' was expected.")

WebSocket orderbook kanalından birçok işlem çiftini dinlemeye çalıştığımda ilk açılışta 429 hatası alıyorum.
Bu hatayı araştırdığımda api de fazla istek yollamak anlamına geliyor.
Websocket dinlerken böyle bir hatanın gelmemesi gerekiyor.

Bu hata server a client.SendAsync yollamamız gerekiyor ve bunu yollarken limite takıldığımızı düşünüyorum.
Uri _uri = new Uri("wss://ws-feed-pro.btcturk.com");
await client.ConnectAsync(_uri, CancellationToken.None);
string msg = "[151,{\"type\":151,\"channel\":\"orderbook\",event:\"" + ad + "\",\"join\":true}]";
await client.SendAsync(buffer: new ArraySegment<byte>(array: Encoding.UTF8.GetBytes(msg), offset: 0, count: msg.Length), messageType: WebSocketMessageType.Text, endOfMessage: true, cancellationToken: CancellationToken.None);

Aşağıdaki örnek ile başka bir siteden websocket orderbook dinlediğimde bir sorunla karşılaşmıyorum. Çünkü server a SendAsync göndermek durumunda kalmıyorum.
Uri _uri = new Uri("wss://stream.xxxxxxxxxx.com:9443/ws/" + (ad) + "@depth20@100ms");
await client.ConnectAsync(_uri, CancellationToken.None);

Not: Bu hata ile sadece program ilk açıldığında karşılaşıyorum ilk döngü döndükten sonra bir daha SendAsync yollamak durumunda kalmadığımdan dolayı herhangi bir problem kalmıyor.

**Comment by ocinbat** [comment]
Her işlem çifti için bağlantı açıyorsunuz gibi görünüyor.
Bir kere bağlantı kurup arkasından her çift için tek tek 151 mesajı gönderirseniz bu durumu yaşamazsınız.

**Comment by akrepfatih** [comment]
Evet. Her işlem çifti için ayrı bağlantı açıyorum. Yoksa işlem çiftinin bağlantısının kopup kopmadığını kontrol edemem. Nasıl bir çözüm önerirsiniz ?

**Comment by suleymanbyzt** [comment]
Selamlar,
Her pair için yeni bir connection açmanız rate limite takılmanıza neden olacaktır. Yaşanabilecek olası bir problemi tek bir connection açarak da yönetebilirsiniz. Mevcut bağlantınız üzerinden socket mesajı alamamanız durumunda yeni bir bağlantı açarak socket mesajlarını dinleyebilirsiniz. Daha detaylı bilgi için [Retry Strategy Guideline - BtcTurk | PRO API Documentation](https://docs.btcturk.com/error-handling-for-order-operations/retry-strategy-guideline) dökümanımızı inceleyebilirsiniz.
