### ISSUE TITLE
Ip

### ISSUE THREAD

**Issue by erenk563** [BTCTrader/broker-api-docs#545]
Merhaba ben daha yeni basliyorum,cok basit bi sorum var.api key almak icin ip adresimi cmd komuttan ipconfig ile bulup yaziyorum ama nedense ip adresi hatali diyor yardimci olursaniz sevinirim

**Comment by suleymanbyzt** [comment]
Selamlar,
Local adresiniz ile API Key oluşturmaya çalıştığınız için problem yaşıyor olabilirsiniz. IP adresinizi öğrenmek için https://www.whatismyip.com/ sitesini ziyaret ederek IPv4 adresinizi görüntüleyebilirsiniz.
