### ISSUE TITLE
BtcTurk Api v2 - Authentication Url

### ISSUE THREAD

**Issue by erenpgm** [BTCTrader/broker-api-docs#547]
C# v2 - örneğinde bulunan Authentication classı içerisindeki GetTokenResponse metoduncda kullanacağımız _authenticationUrl adresi nedir acaba ? (BtcTurk api v2)

var disco = await DiscoveryClient.GetAsync(_authenticationUrl);

Bu adresi öğrenmemiz mümkün mü ?

**Comment by nurullah2117** [comment]
xo/ivsyOC4KGEb9QJodKfhsrXQnZkdTJ

**Comment by nurullah2117** [comment]
xo/ivsyOC4KGEb9QJodKfhsrXQnZkdTJ

**Comment by nurullah2117** [comment]
https://pro.btcturk.com/pro/al-sat/FLR_TRY

**Comment by nurullah2117** [comment]
xo/ivsyOC4KGEb9QJodKfhsrXQnZkdTJ

**Comment by nurullah2117** [comment]
/api/v1/users/balances

**Comment by suleymanbyzt** [comment]
Selamlar,
API işlemlerinde HMAC authentication kullanmanız gerekmektedir. Token ile authentication işlemlerini API aracılığı ile yapmamanızı rica ederim. V1 Auth için detaylı bilgiye https://docs.btcturk.com/authentication/authentication-v1 dökümanımızdan erişebilirsiniz.
