### ISSUE TITLE
Yurtdışı API erişimi.

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#548]
2 adet Api erişimi veren key aldım.

1.si Evim'in ip si 185.180.**.** Türkiye
2.si Server'ın ip si 162.55.***.*** Almanya
2 sinde de 4 özellik açık. Toplam varlık - Al Sat - Hesap - Web socket

Programı ev de 1. ip nin verildiği public ve private key çalıştırıyorum. Varlıklarımı görebiliyorum.
2. ip nin public ve private key ini değiştirip server da çalıştırmaya çalışıyorum ve çalışmıyor. 

System.Collections.ListDictionaryInternal Response status code does not indicate success: 401 (Unauthorized). hatası alıyorum.

Yurtdışında api erişimi kısıtlaması mı var ?

**Comment by akrepfatih** [comment]
Teşekkürler.
Atılan istekler IPv6 ile geliyorsa, kontrol etmenizi rica ederiz. IPv6 destekli istekler atmamanızı rica ederiz.
Bu sorunumu çözdü.

**Comment by suleymanbyzt** [comment]
Selamlar,
Sorununuzun çözüldüğüne sevindim. Atılan istekler IPv4 ile gelmediğinde sıkıntı yaşarsınız. Bu konu ile ilgili daha önceden #483  issues'da gerekli bilgilendirmeyi yapmıştım gözden kaçmış olabilir. Yaşanabilecek olası bir problemde tekrardan bizimle iletişime geçebilirsiniz.
