### ISSUE TITLE
Bu nasıl Websocket ? 750ms

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#549]
Websocket ile orderbook u alıyorum ve bir sonraki CS ile arasında minimum 750ms var.
Websocket denen olay bir şey olduğunda bunu anında bildiren şeydir.
Siz buraya bekleme süresimi koyuyorsunuz ?

**Comment by suleymanbyzt** [comment]
Selamlar,
WebSocket mesajlarını belirli bir period içinde kullanıcılarımıza publish ediyoruz bu süre şu an için ticker ve orderbook kanalları için 750 ms diğer kanallarımız için ise real time olarak gönderiyoruz. İlerleyen süreçte ticker ve orderbook kanallarının real time olarak güncellenmesi durumunda size özel buradan bilgilendirme yapacağım. Talebinizi öneri olarak ekibimize ileteceğim. Geri bildirim için teşekkür ederiz.
