### ISSUE TITLE
Emir Gönderiminde error 500 

### ISSUE THREAD

**Issue by netaproduction** [BTCTrader/broker-api-docs#55]
Sell Order veya buy order gönderiminde error500 emir girilemedi tekrar deneyiniz hatası alıyorum yardımcı olurmusunuz?

```
import base64
import hashlib
import hmac
import time
import requests
def hmacc(request, secret, algorithm=hashlib.sha256, digest='hex'):
h = hmac.new(secret, request, algorithm)
if digest == 'hex':
return h.hexdigest()
elif digest == 'base64':
return base64.b64encode(h.digest())
return h.digest()
APIKey= '64e9'
secretKey= 'y*******S'
secret = base64.b64decode(secretKey)
auth = APIKey + str(int(time.time()))
headers = {
'X-PCK': APIKey,
'X-Stamp': str(int(time.time())),
'X-Signature': base64.b64encode(hmacc(auth.encode(), secret, hashlib.sha256, 'binary')),
'Content-Type': 'application/x-www-form-urlencoded',
}
params={
'OrderMethod': 0,
'OrderType':0,
'Price': 2760.4,
'PricePrecision': 0.001,
'Amount': 0.1,
'AmountPrecision': 0.001,
'Total': 276.04,
'TotalPrecision': 0.001,
'PairSymbol': 'ETHTRY'
}
'''res= requests.get('https://www.btcturk.com/api/balance', headers=headers)
print(res.content)'''
res= requests.post('https://www.btcturk.com/api/exchange', data= params, headers=headers)
print(res.content)
```

b'{"error":{"code":500,"message":"Emir girilemedi. L\xc3\xbctfen tekrar deneyiniz ve hata tekrar ederse bize ula\xc5\x9f\xc4\xb1n\xc4\xb1z."}}'

**Comment by netaproduction** [comment]
import base64
import hashlib
import hmac
import time
import requests
def hmacc(request, secret, algorithm=hashlib.sha256, digest='hex'):
        h = hmac.new(secret, request, algorithm)
        if digest == 'hex':
            return h.hexdigest()
        elif digest == 'base64':
            return base64.b64encode(h.digest())
        return h.digest()
APIKey= '64************e9'
secretKey= 'y*******************S'
secret = base64.b64decode(secretKey)
auth = APIKey + str(int(time.time()))
headers = {
    'X-PCK': APIKey,
    'X-Stamp': str(int(time.time())),
    'X-Signature': base64.b64encode(hmacc(auth.encode(), secret, hashlib.sha256, 'binary')),
    'Content-Type': 'application/x-www-form-urlencoded',
}
params={
    'OrderMethod': 0,
    'OrderType':0,
    'Price': 2760.4,
    'PricePrecision': 0.001,
    'Amount': 0.1,
    'AmountPrecision': 0.001,
    'Total': 276.04,
    'TotalPrecision': 0.001,
    'PairSymbol': 'ETHTRY'
}
'''res= requests.get('https://www.btcturk.com/api/balance', headers=headers)
print(res.content)'''
res= requests.post('https://www.btcturk.com/api/exchange', data= params, headers=headers)
print(res.content)

**Comment by omerkulahli** [comment]
Merhaba,

Gönderdiğiniz parametrelerde; Price : 2760, PricePrecision: 40, Total: 276, TotalPrecision: 40, Amount :0, AmountPrecision: 01 şeklinde olmalıdır.

**Comment by netaproduction** [comment]
`params={
    'OrderMethod': 0,
    'OrderType': 1,
    'Price': 2760,
    'PricePrecision': 40,
    'Amount': 0,
    'AmountPrecision': 0.1,
    'Total': 276,
    'TotalPrecision': 40,
    'PairSymbol': 'ETHTRY'
}`

Bu şekilde yaptım halen aynı hatayı alıyorum? yardımcı olabilirmisiniz?

**Comment by netaproduction** [comment]
Bir de neden priceprecision 40 olmalı bir hesaplama mantığı varsa onu da belirtebilirseniz sevinirim. yoksa statik mi olmalı bu değerler?

**Comment by omerkulahli** [comment]
PricePrecision ve TotalPrecision 2 basamaklı, AmountPrecision ise en fazla 8 basamaklı olmalıdır, o yüzden  Price olarak 2760.4 yazmanıza istinaden örnek olarak PricePrecision' ı 40 olarak belirttim.

**Comment by muratzorer** [comment]
Aynı 500 hatasını aşağıdaki application/json raw request'inde alıyorum, body aşağıdaki gibi:
```
{
	"OrderMethod":0,
	"OrderType":0,
	"Price":2500,
	"PricePrecision":00,
	"Amount":0,
	"AmountPrecision":05,
	"PairSymbol":"ETHTRY"
}
```
Limit order için bu parametreler yeterli diye biliyorum. Fakat problem nerede bulamadım, yardımcı olabilir misiniz lütfen

**Comment by nepnesomao** [comment]
`{
 'OrderMethod': 0, 
 'OrderType': 1, 
 'Price': 2500, 
 'PricePrecision': 0,
 'Amount': 0, 
 'AmountPrecision': 05, 
 'Total': 276, 
 'TotalPrecision': 40,
 'TriggerPrice' : 0,
 'TriggerPricePrecision' : 00,
 'PairSymbol': 'ETHTRY' 
 }` şeklinde parametreleri gönderiniz.
