### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by orhansozgur1** [BTCTrader/broker-api-docs#551]
import time, base64, hmac, hashlib, requests, json
base = "https://api.btcturk.com"
method = "/api/v1/users/balances"
uri = base+method
apiKey = "xxx"
apiSecret = "xxx"
apiSecret = base64.b64decode(apiSecret)
stamp = str(int(time.time())*1000)
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers= {  "X-PCK": apiKey,  "X-Stamp": stamp,  "X-Signature": signature,  "Content-Type": "application/json"}
result = requests.get(url=uri, headers=headers)result = result.json()print(json.dumps(result, indent=2))
result = {'data': result}

Direkt olarak https://docs.btcturk.com/private-endpoints/account-balance internet sitesinden aldigim bu kodu make.com uzerinden uyguluyorum, error 400: bad request, please check your parameters diyor. Nasil duzeltebilirim?

**Comment by suleymanbyzt** [comment]
Selamlar,
User balances endpointi için sizlerden bir parametre talep etmiyoruz. Gönderdiğiniz bir parametre ile hata almanızı bu durumda beklemem açıkçası. Kullandığınız 3. parti yazılım nedeniyle hata alıyor olabilirsiniz. Aldığınız hata ile ilgili size daha detaylı bilgilendirme yapabilmem adına rica etsem örnek request bilginizi buradan iletebilir misiniz?

`import time, base64, hmac, hashlib, requests, json

base = "https://api.btcturk.com"
method = "/api/v1/users/balances"
uri = base+method

apiKey = "YOUR_API_PUBLIC_KEY"
apiSecret = "YOUR_API_SECRET"
apiSecret = base64.b64decode(apiSecret)

stamp = str(int(time.time())*1000)
data = "{}{}".format(apiKey, stamp).encode("utf-8")
signature = hmac.new(apiSecret, data, hashlib.sha256).digest()
signature = base64.b64encode(signature)
headers = {"X-PCK": apiKey, "X-Stamp": stamp, "X-Signature": signature, "Content-Type" : "application/json"}

result = requests.get(url=uri, headers=headers)
result = result.json()
print(json.dumps(result, indent=2))` 

örneğin ben yukarıdaki kodu çalıştırdığımda herhangi bir hata almadan balance'ıma ulaşabiliyorum. Daha detaylı bilgilendirme yapmanız durumunda sizi daha doğru bir şekilde yönlendirebilirim.
