### ISSUE TITLE
Subscription limits

### ISSUE THREAD

**Issue by mGungorr** [BTCTrader/broker-api-docs#552]
Merhaba,

Tüm coinlere ait order bookları çekmeye çalışıyorum ancak denemelerime göre yaklaşık 15 -16 adet subscription oluşturabiliyorum. Bunun neticesinde merak ettiğim bazı durumlar var.

- Aynı IP adresinden kaç farklı socket bağlantısı kurulabilir?
- İkinci bir socket bağlantısı için ne kadar beklemek gerekir?
- Bir socket bağlantısından kaç farklı subscription kurulabilir?
- İkinci bir subscription için ne kadar beklemek gerekir?

- Ek olarak, tüm base tipleri dahil edildiğinde coinlerin hacimsel sıralamasını çekebileceğim bir endpoint veya ws var mı ?

Sorularıma yanıt alabilir miyim, Teşekkürler.

**Comment by catnug** [comment]
merhaba,
dokumantasyonda bu bilgi mevcut. her sorunuzun karsiligi yok ama cumleyi yorumlayinca tum sorular yanit buluyor.

> WebSocket connections are limited to a maximum of 15 connection requests per minute. If this limit is exceeded, new connection requests will be temporarily blocked for 60 seconds.

elimizde open statusunde 1 (**bir**) connection umuz var degil mi ? sanki 16 acik connection yapmissiniz gibi geldi bana :)

**Comment by suleymanbyzt** [comment]
Selamlar,
Her pair için ayrı bir connection oluşturmanızı önermem. Pair listesini 50'li chunk oluşturup her chunk için connection açmanızı öneririm. Örneğin bir connection üzerinden 50 farklı pair'e subscription isteği atarak socket yapınızı kurgulayabilirsiniz. Hata almamanız için receive buffer size'nı da yüksek tutabilirsiniz. örneğin 1mb civarında receive buffer size ayarlamanız durumunda mesaj kaçırma olasılığınız da düşük olacaktır. 

Mevcut yapımızda şu an IP başına dakikalık 15 connection açtırma limitimiz mevcut ve her bir connection için subscription limitimiz bulunmuyor.  Saniyelik bir limitimiz olmadığı için dakikalık 15'i geçmemeniz yeterli olacaktır. Yapınızı bu şekilde kurgularsanız rate limit hatası almadan sorunsuz bir şekilde bağlantı kurabilmenizi beklerim. Tüm pairlere ait hacim bilgisini ticker socket kanalından ya da https://docs.btcturk.com/public-endpoints/ticker dökümanında belirttiğimiz şekilde `/v2/ticker` endpointimize istek atarak `volume` bilgisine ulaşabilirsiniz.

**Comment by yavuzDemir21** [comment]
Merhabalar burdaki durumla alakali bir sorum olucakti @suleymanbyzt. Boyle bir senaryoda atiyorum BTCTRY gibi bir ticker ile baska bir ticker birlikte olsa BTCTRY den gelen sik updateler digerini etkileyecek mi?
