### ISSUE TITLE
Assistance Needed in Establishing WebSocket Connection

### ISSUE THREAD

**Issue by r3stam** [BTCTrader/broker-api-docs#553]
Dear BTCturk Support,

I hope this message finds you well. I am currently working on a project that involves real-time monitoring of cryptocurrency prices using your WebSocket API. While I have been able to successfully establish the connection and fetch the necessary data from several other platforms, I am encountering difficulties when it comes to BTCturk's API.

Specifically, I am receiving a '503 Service Temporarily Unavailable' error when attempting to establish the WebSocket connection. This issue persists even after multiple attempts and cross-verification of my API credentials (Public Key and Private Key).

Here's the Python code snippet I'm using to establish the connection:

import jwt
import time
import websocket
from threading import Thread

BTCTURK_WS = "wss://ws-feed.btcturk.com/"
BTCTURK_PAIRS = ["BTC_TRY", "ETH_TRY", "XRP_TRY"]

API_KEY = "your_api_key"
API_SECRET = "your_api_secret"

def on_open_btcturk(ws):
    payload = {
        'alg': 'HS256',
        'typ': 'JWT',
        'iat': int(time.time()),
        'exp': int(time.time()) + 60*60,
        'sub': API_KEY
    }
    encoded_jwt = jwt.encode(payload, API_SECRET, algorithm='HS256')
    ws.send(json.dumps({'type': 'authenticate', 'token': encoded_jwt.decode('utf-8')}))

ws_btcturk = websocket.WebSocketApp(BTCTURK_WS,
                            on_open=on_open_btcturk,
                            # More code here...
                            )

Thread(target=ws_btcturk.run_forever).start()

I have replaced "your_api_key" and "your_api_secret" with my actual Public Key and Private Key respectively in my original script.

I would greatly appreciate any assistance or guidance you could provide to help me resolve this issue. Please let me know if you require any additional information to assist with troubleshooting.

Thank you in advance for your support.

Best regards

**Comment by suleymanbyzt** [comment]
Hi,
You can connect to the ticker channel to get price information. You do not need authentication when connecting to the ticker channel.

You can use the following code example to connect to the socket and get ticker messages

```python
import asyncio
import json
import websockets
class InterfaceWS:
    def __init__(self) -> None:
        self.uri = "wss://ws-feed-pro.btcturk.com/"

    async def authenticate_ws(self) -> bool:
        self.ws = await websockets.connect(self.uri)
        ticker = [151,{"type":151,"channel":"ticker","event":"all","join": 'true' }]
        
        await self.ws.send(json.dumps(ticker))
        
        while True:
            try:
                response = await asyncio.wait_for(self.ws.recv(), timeout=0.5)
                print(response)
            except Exception as e:
                print(e)

async def main():
    w = InterfaceWS()
    await w.authenticate_ws()

if __name__ == "__main__":
    asyncio.run(main())
```

To get the ticker information of a specific pair, you can use the following code example.
```python
import asyncio
import json
import websockets
class InterfaceWS:
    def __init__(self) -> None:
        self.uri = "wss://ws-feed-pro.btcturk.com/"

    async def authenticate_ws(self) -> bool:
        self.ws = await websockets.connect(self.uri)
        
        pairs = ['BTCTRY', 'XRPTRY', 'ETHTRY']
        for pair in pairs:
            subscribe = [151,{"type":151,"channel":"ticker","event":pair,"join":'true'}]
            await self.ws.send(json.dumps(subscribe))
        
        while True:
            try:
                response = await asyncio.wait_for(self.ws.recv(), timeout=0.5)
                print(response)
            except Exception as e:
                print(e)

async def main():
    w = InterfaceWS()
    await w.authenticate_ws()

if __name__ == "__main__":
    asyncio.run(main())
```
