### ISSUE TITLE
API erişim hk.

### ISSUE THREAD

**Issue by Cemhanka** [BTCTrader/broker-api-docs#556]
Merhaba,

API public ve private key oluşturmak istiyorum. CMD üzerinden ipconfig bilgilerini alıyorum. IPv4'te gelen IP adresini Hesap > API erişimi safyasında istenen IP adres kısmına yapıştırıp API almak istediğim zaman. Hatalı IP! uyarısı alıyorum. Yardımcı olabilir misiniz ?

**Comment by akrepfatih** [comment]
ipconfig iç ağ ip ni verir. Yani modemin dhcp sinin verdiği ip.
https://www.whatismyip.com/ adresinden ip adresini öğrenebilirsin.

**Comment by suleymanbyzt** [comment]
Selamlar,
@akrepfatih söylediği gibi aldığınız IP adresi sizin local adresinizi verir buradan alacağınız adres ile key oluşturursanız hata alırsınız.

Cmd'den aşağıda vereceğim komutu kullanarak dış ip adresinizi öğrenebilirsiniz.
`curl ifconfig.me`

bu size dış ip adresiniz hakkında çıktıyı verecektir. Key oluştururken bu ip adresini kullanabilirsiniz.
