### ISSUE TITLE
The order interface for submitting a limit price sometimes returns "", but in fact the order was successfully placed.

### ISSUE THREAD

**Issue by lkx0012018** [BTCTrader/broker-api-docs#558]
Hello, I recently encountered a problem: the order interface runs normally most of the time, but occasionally it appears. The return data is "", and no other data is returned. The order has been successfully placed on the actual web page, and the order number is generated. Okay, what's the reason for this? Please help me solve it, thank you

**Comment by suleymanbyzt** [comment]
There should not be a case where we return an empty response during the order creation process. Could you be doing something wrong in your code?
