### ISSUE TITLE
openOrders "time"

### ISSUE THREAD

**Issue by serensoner** [BTCTrader/broker-api-docs#559]
merhaba,

/api/v1/openOrders "time" alani daima 0 donduruyor. /api/v1/order'da ise bu alan dogru donduruluyor. lutfen bunu duzeltebilir misiniz?

**Comment by suleymanbyzt** [comment]
Selamlar,
İlgili ekibe konuyu ileteceğim. Order'ın create edilme tarihini timestamp formatında dönülmesi gerektiği hakkında bilgilendirme geçeceğim. Bir değişiklik olması durumunda size buradan bilgilendirme geçeceğim. Geri bildiriminiz için teşekkür ederiz 👍
