### ISSUE TITLE
Api key problemi

### ISSUE THREAD

**Issue by Djzecko** [BTCTrader/broker-api-docs#561]
Merhaba, 

API ile hesabıma ulaşamıyorum. Kodlar sitenizde verildigi gibi. Hesap detaylarina ulasip buy/ sell emirleri vermek istiyorum. 

Api bilgilerini kontrol ettik sorun yok ama baglanamiyoruz.

![IMG-20231029-WA0012](https://github.com/BTCTrader/broker-api-docs/assets/149315485/a2e80e13-459e-4d57-8804-7c1352d046ce)
![IMG-20231029-WA0005](https://github.com/BTCTrader/broker-api-docs/assets/149315485/07a2c7fc-f797-4670-9949-449c1081a6ca)
![IMG-20231029-WA0004](https://github.com/BTCTrader/broker-api-docs/assets/149315485/43c3946e-8ca4-4cc1-96b2-add7ec2a2049)
![IMG-20231029-WA0011](https://github.com/BTCTrader/broker-api-docs/assets/149315485/604e1190-7a6a-4a7e-b837-0dd295fb53ab)
![IMG-20231029-WA0007](https://github.com/BTCTrader/broker-api-docs/assets/149315485/63d9a2c9-d6e5-4356-97aa-092d12ccaecc)

**Comment by catnug** [comment]
IP adresinizi nasil elde ettiniz ? Kastedilen cmd>ipconfig den aldiginiz IP adresi degil.

**Comment by suleymanbyzt** [comment]
Selamlar,
Kodunuzda bir hata göremedim. Olası problem şu olabilir:
Servertime'ı hatalı yolluyor olabilirsiniz. Güncel servertime bilgisine erişmek için `/api/v2/server/time` endpointine istek atabilirsiniz.
External IP adresinizi yanlış giriyor olabilirsiniz. Doğru IP adresinizi öğrenmek için cmd'den `curl ifconfig.me` isteği atabilirsiniz. Bu size dışa çıkış IP'nizi verecektir. 
Bir diğer sorun ise IPv6 kullanıyor olabilirsiniz. IPv4 adresi tanımlarken aynı zamanda IPv6 adresiniz varsa bu unauthorized hatası almanıza neden oluyor olabilir. Sorunu çözmek için IPv6 adreslemeyi kapatmayı deneyebilirsiniz. Sorunun devamı halinde tekrardan iletişime geçebilirsiniz.

IPv6 nasıl kapatacağınız ile ilgili bilgiye ileteceğim dökümandan erişebilirsiniz.
https://support.nordvpn.com/hc/en-us/articles/19919186892305-How-to-disable-IPv6-on-Windows
