### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by albayr** [BTCTrader/broker-api-docs#562]
Aynı API den birkaç kişi ile alım satım yapmaktayız. Sadece birinde daha önce işlem yaparken sonraları 
Authentication Failed. Error Message: Authentication Error.
mesajı almaya başladık. Diğer kullanıcılar işleme devam ediyor. Bu sorunu nasıl hallederiz

**Comment by suleymanbyzt** [comment]
Selamlar,
Sorunu tam olarak anlayamadım. Rica etsem hatayı biraz daha detaylandırıp iletebilir misiniz?
