### ISSUE TITLE
Access-Control-Allow-Origin Hatası

### ISSUE THREAD

**Issue by ensarcakmak** [BTCTrader/broker-api-docs#564]
Merhaba web sitenizde yayınladığınız gibi yazdım kodları fakat şöyle bir hata alıyorum destek olabilir misiniz?
![btc](https://github.com/BTCTrader/broker-api-docs/assets/158550586/af4ce2fe-7faa-4397-b0f7-0d2e097ec53a)

**Comment by ocinbat** [comment]
Selamlar, Access-Control-Allow-Origin header'ı bir http resourceunun hangi sayfalardan tüketilebileceğini belirleyen bir headerdır. api.btcturk.com altından sunduğumuz servisler, kullanıcı güvenliği için sadece bizim tarafımızdan tüketilebilecek şekilde ayarlanmıştır. Bu servisleri bir web sayfasında kullanmak istiyorsanız, kendinize ait bir backend servisi yazıp isteğinizi oradan atmalısınız.
