### ISSUE TITLE
Orderbook max limit

### ISSUE THREAD

**Issue by yalcinerbasi** [BTCTrader/broker-api-docs#567]
/api/v2/orderbook?pairSymbol=BTC_TRY&limit=100 adresinden Readme içerisinde default 100 max 1000 order çekebileceğim belirtiyor. Fakat limit değeri 1000 yapmama rağmen 100 order getiriyor. 1000 adet order çekebilmenin bir yolu mevcut mudur?

**Comment by ocinbat** [comment]
Selamlar, https://docs.btcturk.com/public-endpoints/orderbook adresi günceldir buradan destek alabilirsiniz. Bu endpoint maximum 100 değer dönmekte şu anda. Ben 1000 değerini dokümantasyonda bulamadım. Yanlış kalan bir yer varsa yönlendirirseniz düzeltelim.

**Comment by suleymanbyzt** [comment]
Selamlar,
Dökümanı incelediğimizde default değer 100 olarak girilmiş görülmekte. Hata olduğunu düşündüğünüz kısım varsa buradan iletmeniz takdirde inceleyip gerekli düzenlemeleri yapacağız.
