### ISSUE TITLE
Private Socket Messages 451-452-453

### ISSUE THREAD

**Issue by catnug** [BTCTrader/broker-api-docs#569]
Merhaba,

private `ws` verileri soz konusu oldugu zaman, dokumantasyon diyor ki,

**order insert** => `451` model type ile mesaj gonderir.
**order delete** => `452` model type ile mesaj gonderir.
**order update** => `453` model type ile mesaj gonderir.

fakat bir emiri guncelledigimizde ve sildigimizde, her birisi icin de `452` mesaji aliyorum.

bu durumda order update ve delete i ayirt edemiyorum. bilginize.

**Comment by ocinbat** [comment]
Order update işlemleri de iç sistemde sırasıyla delete + insert şeklinde işletiliyor. Bu sebeple 452 mesajını alıyorsunuz. https://docs.btcturk.com/private-endpoints/all-private-endpoints adresindeki dokümantasyonda belirtildiği şekilde biz api v1 üzerinden sadece ordert insert ve delete işlemlerini destekliyoruz.
