### ISSUE TITLE
Limit Order Buy Hatası

### ISSUE THREAD

**Issue by muratzorer** [BTCTrader/broker-api-docs#57]
Aşağıdaki raw application/json requesti, 500 status code'u ile birlikte `"Message": "An error has occurred."` hatası dönmektedir, yardımlarınızı rica ederim.
```
{
	"OrderMethod":0,
	"OrderType":0,
	"Price":2500,
	"PricePrecision":0,
	"Amount":0,
	"AmountPrecision":05,
	"Total":0,
	"TotalPrecision":0,
	"TriggerPrice":0,
	"TriggerPricePrecision":0,
	"PairSymbol":"ETHTRY"
}
```

**Comment by nepnesomao** [comment]
{ 'OrderMethod': 0, 'OrderType': 1, 'Price': 2500, 'PricePrecision': 0, 'Amount': 0, 'AmountPrecision': 05, 'Total': 276, 'TotalPrecision': 40, 'TriggerPrice' : 0, 'TriggerPricePrecision' : 00, 'PairSymbol': 'ETHTRY' } şeklinde parametreleri gönderiniz.

**Comment by muratzorer** [comment]
Problem devam etmektedir. Aşağıda ETHTRY limit buy (2100) ve limit sell (2200) için ekran görüntülerini paylaşıyorum. (Total = price/amount olarak hesaplıyorum)

<img width="1053" alt="screen shot 2018-06-26 at 11 13 45" src="https://user-images.githubusercontent.com/3949670/41898492-d9331aac-7932-11e8-93f4-0e975566dffa.png">

<img width="1045" alt="screen shot 2018-06-26 at 11 23 59" src="https://user-images.githubusercontent.com/3949670/41898783-86f6201c-7933-11e8-8d21-8bb503e24a97.png">

**Comment by nepnesomao** [comment]
Hangi alt yapıyı kullanıyorsunuz.

**Comment by muratzorer** [comment]
Go ile yaziyorum. Fakat denemeleri postman ile yapiyorum. Sizle de iletisim daha kolay olmasi acisindan ordan paylastim goruntuleri. Nonce & signature ureten kodu calistirip degerleri header a ekliyorum ve gorunen body’i post ediyorum. (Content type ‘application/json’ ve public key headerlari ile birlikte)

Siz de rahatca durumu recreate edebilirsiniz bu sekilde.

Not: nonce ve signature ureten kodda bir problem yok, olusan degerleri yine postman e ekleyerek sizin diger authentication gerektiren api methodlarinizi kullaniyorum, onlarda bir problemim yok.

**Comment by omerkulahli** [comment]
Tekrar merhaba,

`{
	"OrderMethod":0,
	"OrderType":0,
	"Price": "2500",
	"PricePrecision": "00",
	"Amount": "0",
	"AmountPrecision": "05",
	"Total": "0",
	"TotalPrecision": "00",
	"TriggerPrice": "0",
	"TriggerPricePrecision": "00",
        "DenominatorPrecision" : 2,
	"PairSymbol":"ETHTRY"
}`
 parametrelerinizi bu şekilde gönderebilir misiniz.

**Comment by muratzorer** [comment]
Ömer teşekkür ederim, DenominatorPrecision olayı çözdü.
Son olarak merak ediyorum, bu parametrenın kullanım amacı nedir ve hangi durumda değişebilir, dökümantasyonda bulunmuyor çünkü?

Bir de denk gelmişken söyliyim başarılı response'da `"pairsmybol":null` dönüyor, orada bir bug var bilginiz olsun.
