### ISSUE TITLE
merhaba

### ISSUE THREAD

**Issue by Hackcoder212** [BTCTrader/broker-api-docs#571]
api üzerinden emir defteri çekme limitini dakikada 180 adet belirlemişsiniz . ama bu rakam doğru değil galiba daha fazla çünkü ben denedim daha fazla çekebildim gerçek rakam nedir

**Comment by suleymanbyzt** [comment]
Selamlar,
`/v2/orderbook` endpointimiz için IP bazlı dakikada atılabilecek maksimum istek sayısı 180. Az önce kontrol ettim bu oranın değişmediğini görüntülüyorum.
