### ISSUE TITLE
PEPE BONK SHIB Invalid Decimal Pattern Sorunu

### ISSUE THREAD

**Issue by fatihgulmezer** [BTCTrader/broker-api-docs#575]
Merhaba iyi gunler,

API uzerinden PEPEUSDT, BONKUSDT ve SHIBUSDT tahtalarına emir göndermek istediğimde fiyat icin Invalid Decimal pattern uyarısı ile karsılasıyorum. (Emri 8 decimal ile iletmeme ragmen)

Aynı pairlerin TRY tahtalarında bu sorunla karsılasmıyorum. Yonlendirebilir misiniz?

**Comment by catnug** [comment]
Merhaba, 
bu parametreleri gozetiyorsunuz degil mi quantity ve price parametrelerini gonderirken ?

"numeratorScale": 0,  // pay demek  -  PEPE
"denominatorScale": 8,  //payda demek - USDT
