### ISSUE TITLE
API Key yaratmama ragmen 401 aliyorum

### ISSUE THREAD

**Issue by ayberkcansever** [BTCTrader/broker-api-docs#579]
Lokal makinamdan basarili order istekleri gonderebilmeme ragmen ayni python kodu ile 5.161.240.108 IPli makinamdan API key ve secretimda da tum izinler olmasina ragmen 401 aliyorum. Kontrol edebilir misiniz lutfen?

**Comment by catnug** [comment]
Merhaba

tariften anlasilan 2. durumda bir uzak sunucu kullaniyorsunuz .

1- 'X-Stamp' request header bilgisini kontrol eder misniz ? btcturk ile ayni zaman diliminde mi zaman uretiyor.
2- 2. durum icin sunucu terminalinden `curl ifconfig.me`  komutu elde ettiginiz IP ile API KEY ler olusturup yeniden deneyebilir misiniz ? (belki bir proxy vardir sunucu onunde)

**Comment by ayberkcansever** [comment]
Evet IPv6 olan bir baska IP'den cikis yapiyormus. Sorun duzeldi tesekkurler.
