### ISSUE TITLE
Websocket TradeSingle mesajı, S field tanımı belirsiz

### ISSUE THREAD

**Issue by justinkut** [BTCTrader/broker-api-docs#588]
Merhabalar,

https://docs.btcturk.com/websocket-feed/models#channel-422-tradesingle sayfasında TradeSingle mesajının tanımı var.

S field'ı 'trade side' olarak tanımlanıyor, ancak hangı tarafın side'ı olduğu yazılmıyor. Her trade'in (işlemin) iki tarafı var: maker ve taker.

Örnek: BTCUSD tahtasında en iyi ask fiyatı 63000. Ben gidip 63000'den alış işlemi yapıyorum (taker). Taker side 'BUY' oluyor, maker side 'SELL' oluyor. Bu işlemden kaynaklanan TradeSingle mesajının S field'ı 0 (BUY) değeri mı alır, yoksa 1 (SELL) değeri mi alır?

Özet: S fıeld'ı hangi tarafın side'ı oluyor? maker'ın mı, yoksa taker'ın mı?

Bu konuda yardımcı olabilirseniz sevinirim. Üstelik bu cevabı, gönderdiğim linkteki içeriğe de ekleyebilirseniz güzel olur.

Teşekkürler,

Justin

**Comment by ocinbat** [comment]
Selamlar, geribildiriminiz için teşekkürler. İç taraftaki işleyişte bu kanaldan gelen tüm tradeler taker olanlar. Yani sizin cevabı her şekilde taker oluyor. Bunu dokümantasyona eklememiz daha sağlıklı olacaktır. Teşekkür ederiz.

**Comment by justinkut** [comment]
Teşekkürler @ocinbat .
