### ISSUE TITLE
rezerve olması gereken bakiye available geliyor

### ISSUE THREAD

**Issue by selimimer** [BTCTrader/broker-api-docs#60]
Merhaba,
API üzerinden:
X TL'lik bir alım emri veriyorum. Ardından bakiye kontrolü yapıyorum, Y TL available görüyorum. Onun için de bir alım emri veriyorum. Her iki emrime de ok dönüyorsunuz. Ancak Toplamda X TL'lik emir gerçekleşiyor. 
Zira aslında available diye döndüğünüz Y TL, ilk emrin gerçekleşmemiş kısmı. Oysa Y TL'lik bu bedelin available olarak dönmemesi gerekir. Ya da Y TL'lik ikinci emrime success dönmemeniz gerekir.
Ayrıntı isterseniz özel bilgiler olduğu için farklı kanaldan iletebilirim.

**Comment by omerkulahli** [comment]
Merhaba, konu hakkında destek sayfamıza yazabilirsiniz.

**Comment by selimimer** [comment]
Merhaba,
Önce destek sayfanıza yazdım. Kendileri buraya yönlendirdi.
