### ISSUE TITLE
API hatalı bilgi veriyor

### ISSUE THREAD

**Issue by pzkpfwVI** [BTCTrader/broker-api-docs#61]
API arada bir hatalı bilgi veriyor. Mesela bugün 13:12:34'de

Btc alımı: 6357.0TL btc satım: 6499.0TL ve hacmi: 4 olarak gösterdi. 

API'de bu tür hatalı bilgi sisteminizde ilk açıldığınızdan beri var fakat sıklığı arttı. Bugün saat başı 1'den fazla oluyor.

16:53:49: Bitcoin Alım 6535.0TL, Bitcoin Satım 6550.0TL, Bitcoin Hacim: 7

16:54:23: Bitcoin Alım 6535.0TL, Bitcoin Satım 6550.0TL, Bitcoin Hacim: 7

17:04:14: Bitcoin Alım 388.1TL, Bitcoin Satım 389.99TL, Bitcoin Hacim: 1906

**Comment by ByLazut** [comment]
2-3 günde bir yapıyor bunu . Sorun nedir acaba ?

**Comment by pzkpfwVI** [comment]
API'de değişiklik yapıldı bu sorunun da ortadan kalkmış olması muhtemel o yüzden closed.
