### ISSUE TITLE
Emir girilemedi. Minimum emir toplamının altında emir girdiniz.

### ISSUE THREAD

**Issue by selimimer** [BTCTrader/broker-api-docs#63]
Merhaba,
Yukarıdaki hatayı hangi durumlarda veriyorsunuz? Minimum limitleri nasıl ayarlamalıyız?

**Comment by progahmet** [comment]
Merhaba bunu nasıl ayarladınız, bende aynı hatayı alıyorum.

yapmak istediğim 66000.00 den 0.001 adet bitcoin almak?

Ayrıca bir soru: ben sadece o anki bitcoin fiyatından 50tl lik bitcoin almak istiyorum bunun için ne yapmalıyım?

new KeyValuePair<string, string>("total", "6")
                    new KeyValuePair<string, string>("totalPrecision", "6000"),

                    new KeyValuePair<string, string>("amount", "0"),
                    new KeyValuePair<string, string>("amountPrecision", "0001"),

                    new KeyValuePair<string, string>("price", "66000"),
                    new KeyValuePair<string, string>("pricePrecision", "0000"),

                    new KeyValuePair<string, string>("triggerPrice", "0"),
                    new KeyValuePair<string, string>("triggerPricePrecision", "0000"),
                    new KeyValuePair<string, string>("orderMethod", "1"), 
                    new KeyValuePair<string, string>("orderType", "0"), 
                    new KeyValuePair<string, string>("DenominatorPrecision", "4"),
                    new KeyValuePair<string, string>("PairSymbol", "BTCTRY"),

**Comment by onurgozupek** [comment]
Total'i hesaplayıp göndermeniz gerekiyor.

50TL'lik Bitcoin almak istiyorsanız ( (50 * 0.997) / Güncel Fiyat)  formülü ile toplamı bulup işlem yapabilirsiniz.

Örn: ( (50 * 0.997) / 65700) = 0.00075875 (kriptopara tutarlarını noktadan sonra 8 hane ile sınırlandırmalısınız)

(Bakiye problemi ile karşılaşmamak için emir girerken hesapları en yüksek Taker komisyon oranı (%0.3) ile yapmanızı tavsiye ederim. Sorguyu gönderdiğinizde, sistem sizin gerçek komisyon oranınızı kontrol ona göre emir giriyor, fazla hesapladığınız tutar serbest bakiyenize ekleniyor.)
