### ISSUE TITLE
API 403 hatasi veriyor

### ISSUE THREAD

**Issue by bbdundar** [BTCTrader/broker-api-docs#65]
Birkac gundur autheticated API endpoint'ler 403 hatası veriyor ve bu yüzden API ile alim satım yapilamiyor.

**Comment by nepnesomao** [comment]
Merhaba,

Sorununuz halen devam ediyor mu?
Kontrol ettiğimizde bu tarz bir hata ile karşılaşmadık.

**Comment by bbdundar** [comment]
Merhaba, bu problem Temmuzun son haftasinda 5-6 gun kadar surmus sonra normale donmustu. Bu sure zarfinda borsada algoritmik alim satim yapamamistik. Su an bir problem yok. Mesajiniz icin tesekkurler.

**Comment by bbdundar** [comment]
Eylul 22 ve 23 tarihlerinde yine gormeye basladik 403 hatalarini, API ile alim satim yapilamiyor.

**Comment by gurcankavakci** [comment]
Ben de 23 Eylül itibari ile aynı hatayı alıyorum. Kontrol edebilir misiniz?

**Comment by nepnesomao** [comment]
Merhaba,

Sistemde oluşan yoğunluk nedeni ile ara ara API 403 html sayfası döndürmektedir.

**Comment by bbdundar** [comment]
> Merhaba,
> 
> Sistemde oluşan yoğunluk nedeni ile ara ara API 403 html sayfası döndürmektedir.

Tesekkurler cevabiniz icin, ancak "_ara ara_" biraz iyimser olmus :) Alim satimla ilgili API endpointler bizim icin calismiyor

**Comment by gurcankavakci** [comment]
> Merhaba,
> 
> Sistemde oluşan yoğunluk nedeni ile ara ara API 403 html sayfası döndürmektedir.

Ben ticker apisinden bile bu hatayı alıyorum. Ara ara değil hep 403 dönüyor.
