### ISSUE TITLE
Request Limits

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#66]
Request Limits
.../api/ticker requests are limited to 10 requests per 100 miliseconds.
Other requests are limited to 1 request per 100 miliseconds.
If you make more than 50 consequent unauthorized requests your IP address will be blocked

sorguları 1000 milisaniye de bir yolluyorum yinede request limit hatası alıyorum. Yukarıda yazılan değerlerin gerçek değerler olduğuna emin misiniz ? Yoksa değişiklik yapıldı da yazıyı mı düzeltmediniz ?

**Comment by RJPhillips01** [comment]
Hi - I see the same issue ;

I ran a test where every 30 seconds an application makes a request for trades from https://www.btcturk.com/api/trades?pairSymbol=xxxxxxx

we do this for each pair so in total we make 7 requests every 30 seconds - we also ensure each request is separated by 1500 milliseconds.

However, we still get quite a lot of 409 - "the allowed number of requests have been exceeded" errors. 

Your documentation states the limit to be 1 request per 100 milliseconds and we are nowhere near that so I don't understand why it throws the 409 error like this.

I have seen this issue logged a few times here on github bu have not seen any response to any of them.

Could you take a look?

Thanks, Rich.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
