### ISSUE TITLE
Sorgunun dönüş süresi yaklaşık 3,5 saniye.

### ISSUE THREAD

**Issue by akrepfatih** [BTCTrader/broker-api-docs#67]
Gönderdiğim bir sorgunun cevabını yaklaşık 3,5 saniyede geri alıyorum. Problem benden mi kaynaklanıyor yoksa btcturk alt yapısından mı?

**Comment by akrepfatih** [comment]
15.08.2018 tarihinde sorgunun dönüş süresi 0,5 saniye ye düştü. Ne yaptıysanız böyle kalsın lütfen :) Herkese iyi çalışmalar.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
