### ISSUE TITLE
API balance sorgusunda usdt değerlerini ltc olarak gönderiyor

### ISSUE THREAD

**Issue by eserlxl** [BTCTrader/broker-api-docs#69]
Merhaba,

API, usdt_balance değerini ltc_balance, usdt_available değerini ltc_available ve usdt_reserved değerini ltc_reserved olarak gönderiyor. Balance kodunun kontrol edimesi gerekiyor.

LTC ticareti yapmadığımdan kendi kodumda ltc'leri usdt olarak dönüştüreceğim şimdilik.

Saygılarımla,

Şevket Eser KUBALI

**Comment by nepnesomao** [comment]
Merhaba,

Sorun giderilmiştir.

**Comment by eserlxl** [comment]
Evet düzelmiş, teşekkürler
