### ISSUE TITLE
userTransactions'ta pairSymbol de olmalı

### ISSUE THREAD

**Issue by eserlxl** [BTCTrader/broker-api-docs#70]
Merhaba,

USDT borsaları eklendikten sonra gereken bir ihtiyacı belirtmek istiyorum. 

userTransactions currency içeriyor ama pair bilgisi içermezse geçmiş ticaretin BTCUSDT ya da BTCTRY birimi üzerinden olduğunu sadece fiyata bakarak anlayabiliyorum.

Aşağıdaki iki userTransactions sonucunun hangi para çiftleri için olduğunu şu anki API'yle fiyata bakmadan anlayamayız:
        (
            [id] => 140364
            [date] => 2018-05-23T20:18:44.933
            [operation] => trade
            [currency] => BTC
            [funds] => 5210.7131927976
            [amount] => 0.1
            [fee] => -6.101694
            [tax] => -1.09830492
            [price] => 36000
        )

        (
            [id] => 140364
            [date] => 2018-08-11T10:29:02.86
            [operation] => trade
            [currency] => BTC
            [funds] => 234.81040997384
            [amount] => 0.01
            [fee] => -0.10235591685
            [tax] => -0.018424065033
            [price] => 6039
        )

Saygılarımla,

Şevket Eser KUBALI

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
