### ISSUE TITLE
buy parameters

### ISSUE THREAD

**Issue by kezibooo** [BTCTrader/broker-api-docs#71]
örneğin 1.96 TL fiyatından 22 XRP'yi limit olarak satın almak istiyorum. Bunu yapmak için göndermem gereken parametreler neler olmalıdır
amount = ,
amountPrecision =,
price = ,
pricePrecision = ,
triggerPrice =,
triggerPricePrecision=,
total = ,
totalPrecision =
DenominatorPrecision = ,
PairSymbol = ,
OrderMethod = ,
OrderType = ,

**Comment by eserlxl** [comment]
Hocam açtığım şu konudan bakabilirsiniz:

https://github.com/BTCTrader/broker-api-docs/issues/68

**Comment by kezibooo** [comment]
çok teşekkür ederim. gözden kaçırmışım yada github'da BTCTURK yer vermemiş. ancak sorunu açtığınız konuya bakarak hallettim. 

Kafama takılan son bir şeyi sormak istiyorum. Parametrelerin sıralamasının bir önemi var mıdır?

**Comment by kezibooo** [comment]
teşekkür ederim yardımınız için :) i

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
