### ISSUE TITLE
Bakımdan Sonra Trades Sorgusu Çalışmıyor

### ISSUE THREAD

**Issue by m4rked0ne** [BTCTrader/broker-api-docs#72]
An itibariyle hiçbir işlem ikilisi için trades sorgusu çalışmamakta, dolayısıyla markette gerçekleşen emirler takip edilemiyor.

Sorgu: https://www.btcturk.com/api/trades?pairSymbol=BTCTRY
Hata: {"Message":"An error has occurred."}

Her ikili için aynı hata söz konusu. Sorgu mu yenilendi?

**Comment by eserlxl** [comment]
Hocam kontrol ettim sorun yok, iptal ettiğim emri tekrar verdi kod. Emir vermede eksiğiniz varsa açtığım şu başlığa bakabilirsiniz: https://github.com/BTCTrader/broker-api-docs/issues/68

**Comment by m4rked0ne** [comment]
Problemi doğru okuduğunuzu sanmıyorum. Başlıkta trades sorgusundan bahsettim ben.

**Comment by m4rked0ne** [comment]
Deneyerek anladığım kadarıyla sorguyu gönderirken en son kaç işlemin istendiğini belirten 'last' değişkenini sorguda zorunlu hale getirmişsiniz bakım sonrası. API dökümanında bunu ve 5 ay önce Mart'ta yine burada belirtilen balance sorgusu kısmını güncellemelisiniz (aslında balanceV2 olan sorgu). 

Örnek çalışan sorgu: https://www.btcturk.com/api/trades?pairSymbol=BTCTRY&last=25

API dökümanında aşağıdaki gibi belirtilen 1. sorgu tipi çalışmıyor.

Trades
GET .../api/trades?pairSymbol=BTCTRY
OR
GET .../api/trades?pairSymbol=BTCTRY&last=COUNT (Max. value for count parameter is 50)

**Comment by nepnesomao** [comment]
Merhaba,

Şu an sorun giderilmiştir.

**Comment by m4rked0ne** [comment]
Evet şuan çalışıyor.

Birşey daha belirtip öyle kapatayım.

'last' değişkeni gönderilmediği zaman gelen cevapta zaman verisi Türkiye saati üzerinden bir timestamp olarak gelirken, 'last' belirtilerek gönderildiğinde evrensel saat diliminde (Türkiye saati -3) ve ISO8601 formatında geliyor.
