### ISSUE TITLE
./api/userTransactions den gelen id ler neden hep ayni?

### ISSUE THREAD

**Issue by sukru77** [BTCTrader/broker-api-docs#73]
GET .../api/userTransactions?offset=OFFSET&limit=LIMIT&sort=SORT

yukaridaki **api/userTransactions** api i kullaniyorum ve gelen butun result lar ayni id yi getiriyor. (.../api/exchange) api uzerinden gonderdigim orderdan gelen id lerle hic alakasi yok.  

ayrica offset ve limit parametreleri de hic bir ise yaramiyor galiba.  hep 25 tane gonderiyor. 50 denedim farketmedi.  offset=25 denedim yine ilk 25 trade i gonderdi.  

buna bir cozum varmidir?

**Comment by byazici** [comment]
Bu çok önemli bir problem. 1 sene önce bu hata vardı. Hala var. Neden çözülemiyor anlamıyorum.
Emir gerçekleşmelerini hala OpenOrders'ta var mı yok mu diye bakarak anlıyoruz.
Bu yapıyla güvenilir algo yazmak çok zor.

Bu hatanın çözümü için mantıklı bir cevap bekliyoruz lütfen...

**Comment by eserlxl** [comment]
Bu komik gerçekten, bu nasıl bir API diyesim geliyor. ID olarak emir zamanlarını tutuyorum kayıtlarımda.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
