### ISSUE TITLE
Piyasa Emirleri ve Bakiye Hatası

### ISSUE THREAD

**Issue by ophiafagus** [BTCTrader/broker-api-docs#77]
Merhabalar

Dün saat 12:00dan beri iki farklı anormallik bulunmakta.

1. Piyasa emirleri normal süreden çok daha uzun zaman cevap dönmüyor. Örneğin bir alım emri veriyorsunuz ve 5 dakikadan fazla bu emirde bekletiyor;yani response dönmüyor ama siteden baktığımda bu emri borsa almış ve işlemiş olduğunu görüyorum. Bir timeout süresi olup işlem gerçekleşmiyorsa bir şekilde hata kodu dönmesi; emri kabul ettiyse de emri kabul ettiğinizi dönmeniz gerekir. (timeout'u ben de koyabilirim ama bu sefer bu emri alıp işlemiş olabiliyorsunuz, istenmeyen işlemler gerçekleşiyor) Bu şekilde emirleri ve işlemleri takip etmek imkansız. Aslında çok baz bir sorun bu; size emir iletildiğinde emrin akibetiyle ilgili bir feedback doğru olarak dönülmeli.

2. Piyasa emri olmasına rağmen alım ya da satım emirleri 'işlemde olan' kısmında çok uzun süre bekliyor. (1 saat beklediğini gördüm)  Transaction kısmında bu işlem gerçekleşmiş olarak görülse dahi bakiyeler bu işleme göre güncellenmiyor.  Bakiyeler güncellenmediği için de trade etmeye devam etmek mümkün değil. Deneme yanılma ile takılı olan coine küçük emir gönderdiğimde hemen bakiyenin güncellendiğini fark ettim ama bu bir çözüm değil.

Bahsettiğim problemler ne zaman çözülecek? Daha fazla detay isterseniz email ile daha fazla açıklayabilirim.

İyi bayramlar

**Comment by nepnesomao** [comment]
Merhaba,

Probleminiz halen devam ediyor mu?

**Comment by ophiafagus** [comment]
Merhaba

1. problem ortadan kalktı. Sadece piyasa emirlerinde yeterli bakiye olmasa bile satus kod 200 olarak response veriyor, siteden bakıldıdığında yetersiz bakiyeden dolayı işlemi gerçekleştirmediği geri dönüşü görülebiliyor. API'de de bu şekilde geri dönüş olsa iyi olur.

2. problemde ise emirler 'işlemde olan' kısmında ortalama 3 saniye kalıyor; bu da makul bir süre. Problem başlamadan önce de bu şekildeydi zaten.

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
