### ISSUE TITLE
Error 500: Emir girilemedi. Hata devam ederse bizimle iletisime gecin

### ISSUE THREAD

**Issue by welett** [BTCTrader/broker-api-docs#78]
Merhaba,

VBA ile emir verirken 500 hatasi aliyorum. Hata devam ederse bizimle iletisime gecin diye de bir not var. Balance goruntulemede sorun yok, dolayisiyla son kisimda sorun var diye dusunuyorum. Yardimci olabilir misiniz?

'{"OrderMethod":0,"OrderType":0,"Price":"40000","PricePrecision ":"00","Amount":"0","AmountPrecision":"03","Total":"0","TotalPrecision":"00","TriggerPrice":"0","TriggerPricePrecision":"00","PairSymbol":"BTCTRY"}'

**Comment by nepnesomao** [comment]
Merhaba,
Göndermiş olduğunuz parametrelere DenominatorPrecision parametresini değeri 2 olarak ekleyiniz.
