### ISSUE TITLE
Bakiye Hatası

### ISSUE THREAD

**Issue by ophiafagus** [BTCTrader/broker-api-docs#79]
Merhaba;

API'de bakiye bilgisi yanlış gelmekte. Sitede transaction kısmında ve bakiyede görünen değerden farklı cevap dönüyor. Sanırım apideki bakiye bilgisi güncellenmiyor ve eski bilgiyi gönderiyor sorguya.

Ayrıca şu an için emirleri alıp işlemeniz ve bakiyelere yansıtmanız inanılmaz yavaş. Bu sorunlar ne zaman çözülecek?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
