### ISSUE TITLE
decode edilemeyen yanıt

### ISSUE THREAD

**Issue by selimimer** [BTCTrader/broker-api-docs#80]
Bugün 11:39'da ve 13:00'te ilettiğim satış işlemlerine hangi metni dönüşsünüz?
Benim tarafta decode edememişim. Pyrhon3'te nasıl decode etmeliyim?
Raw data iletebilirseniz test etmeye çalışayım.

**Comment by selimimer** [comment]
Sabah 5:26’da da python requests utf-8 olarak mesajı decode edememiş.

**Comment by selimimer** [comment]
Aşapıdaki sayfayı, gene aşağıdaki basit python requests kodu ile sorunsuzca açabiliyorum. Ancak sizden gelen sayfalarda zaman zaman sorun yaşıyorum. İnceleyebilir ve yardımcı olabilirseniz sevinirim.

test url:
https://www.w3.org/2001/06/utf-8-test/UTF-8-demo.html

işleyen kod:
>>> import requests
>>> r=requests.get('https://www.w3.org/2001/06/utf-8-test/UTF-8-demo.html')
>>> print r.text

**Comment by m4rked0ne** [comment]
Mesajlar bazen boş dönebiliyor, kontrolünü yapmıyor olabilir misiniz? Boş derken None ya da decode edilemez bir şekilde yani.

**Comment by nepnesomao** [comment]
Merhaba,
Sistemde oluşan yoğunluktan dolayı ara ara API html sonuç döndürmektedir.
