### ISSUE TITLE
API Authentication 500 Internal Server Error

### ISSUE THREAD

**Issue by agrkmskrc** [BTCTrader/broker-api-docs#81]
Merhaba,

Aynı programı aynı özelliklerde oluşturduğumuz API key ile denediğimizde çalışıyor. Benim hesabımdan oluşturulan API key ile aynı programı denediğimizde aşağıdaki gibi hata vermektedir.

StatusCode: 500, ReasonPhrase: 'Internal Server Error'

Teşekkürler

**Comment by agrkmskrc** [comment]
Merhaba,
 
Aşağıdaki gibi C# denediğimde benim hesabımdan oluşturulan Key'ler ile 500 hatası dönüyor. Arkadaşımın hesabından oluşturulan key'ler ile düzgün çalışmaktadır.
Çözümünüz nedir?


`using (var client = new HttpClient())
            {

                var apik = "api_key";
                var sc = "secret_key";


                var unixTimestamp = DateTime.UtcNow.Ticks;

                string message = apik + unixTimestamp;

                using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(sc)))
                {
                    byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
                    string signature = Convert.ToBase64String(signatureBytes);

                    client.DefaultRequestHeaders.Add("X-PCK", apik);
                    client.DefaultRequestHeaders.Add("X-Stamp", unixTimestamp.ToString());
                    client.DefaultRequestHeaders.Add("X-Signature", signature);
                    client.BaseAddress = new Uri("https://www.btcturk.com/");

                }

                using (var response = client.GetAsync("api/balance"))
                {
                    if (response != null)
                    {
                        var responsex = response.Result.Content.ReadAsStringAsync().Result;
                    }
                }
            }`

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
