### ISSUE TITLE
Komisyon sayfasındaki komisyonlar ile API den dönen komisyonlar farklı

### ISSUE THREAD

**Issue by gurcankavakci** [BTCTrader/broker-api-docs#82]
Merhaba,

Komisyon sayfanızda 

30 günlük alış satış hacmi (TRY) | Piyasa yapıcı | Piyasa alıcı
0 - 100.000 | %0,20 (0,0020) | %0,30 (0,0030)
gibi bilgiler görünür iken, api den dönen değerler şu şekilde

"btctry_taker_fee_percentage":0.0025423730000000,
"btctry_maker_fee_percentage":0.0016949150000000,

hangisi kullanılıyor, hangisi doğru bilgilendirir misini?

**Comment by halilkiraci** [comment]
API'den dönen oranlar ham komisyon değerleri iken komisyon sayfasındaki oranlar vergi (KDV %18) dahil yaklaşık değerlerdir. Tüm trade işlemlerinden vergi alınmaktadır.
0.0025423730000000*1.18 = 0.00300000014 ≈ 0.0030
0.0016949150000000*1.18 = 0.0019999997 ≈ 0.0020

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
