### ISSUE TITLE
API isteklerine Checking your browser before accessing btcturk.com dönüyor

### ISSUE THREAD

**Issue by selimimer** [BTCTrader/broker-api-docs#87]
Merhaba,

API isteklerine coudflare sayfası dönmeye başladı. Nasıl engelleriz? Önceden header'da  {'user-agent': 'Mozilla/5.0'} iletmek yeterli olmuştu. Bu sefer nasıl bir işlem gerekli?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
