### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by emrahtopcu** [BTCTrader/broker-api-docs#88]
Merhaba, yaklaşık bir haftadır sürekli 'Allowed number of request has been exceeded' hatası alıyorum.
Ekte wireshark ile alınmış iki farklı trace kaydı mevcut. 

Biri 500 milisaniye içerisinde en fazla 1 request diğeri ise 250 milisaniye içerisinde en fazla 1 request yapıcak şekilde çalışan programın kayıtları.

Dosyalardaki Time kolonu bir önceki request ile zaman farkını milisaniye cinsinden yazmakta.

Sizinde görebileceğiniz gibi her iki dosyada da limit değerin altında istek gönderilmemiş. Ancak özellikle 250 milisaniye konfigurasyonunda neredeyse her isteğe limiş aşım hatası alıyorum. Eskiden tek tük alıyordum bu hatayı ama son 1 haftadır dediğim gibi neredeyse her isteğe hata dönüyor. 

Hatta 1000 milisaniyede max 1 yaptığım zaman bile yoğunluğu azalmasına karşın hata almaya devam ediyorum. 

Ek bilgi olarak cep telefonu uygulamasında da hata içeriğini göremesem bile gene limitle alakalı olduğunu düşündüğüm hatalar alıyorum.
[BtcTurkWiresharkTLSTraffic_500ms.pdf](https://github.com/BTCTrader/broker-api-docs/files/2486965/BtcTurkWiresharkTLSTraffic_500ms.pdf)
[BtcTurkWiresharkTLSTraffic_250ms.pdf](https://github.com/BTCTrader/broker-api-docs/files/2486966/BtcTurkWiresharkTLSTraffic_250ms.pdf)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
