### ISSUE TITLE
open orders hatali sonuc yolluyor

### ISSUE THREAD

**Issue by welett** [BTCTrader/broker-api-docs#89]
merhaba,

Open orders, ortalama her uc callda bir hatali (json olmayan) sonuc yolluyor. API'de problem mi var, ya da bir oneriniz olabilir mi?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
