### ISSUE TITLE
Autohorization Error - PHP

### ISSUE THREAD

**Issue by oboydak** [BTCTrader/broker-api-docs#9]
Hi

Th e following code is giving  error
 { ["code"]=> int(401) ["message"]=> string(30) "Unauthorized - Invalid Request"} 
Can  you help me ?

Regards.

$baseURL=api::apiUrl;
$APIKey=api::publicKey;
$privateKey=api::privateKey;

$time = time();
$message=$privateKey.$time;
$signatureBytes = hash_hmac('sha256', $message, base64_decode($privateKey), TRUE);
$signature=base64_encode($signatureBytes);

$r=authGet('balance');
var_dump($r);

function authGet($uri) {
	$url=$GLOBALS['baseURL'].$uri;
	$nonce=$GLOBALS['time'];
	$headers=array(
			'X-PCK: '.$GLOBALS['APIKey'],
			'X-Stamp: '.$nonce,
			'X-Signature: '.$GLOBALS['signature']
	);
	echo var_dump($headers);
	$ch=null;
	$ch = curl_init($url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	$result=curl_exec($ch);
	echo var_dump(curl_getinfo($ch));
	curl_close($ch);
	return json_decode($result);
	
}

**Comment by mohamedfarrag** [comment]
You are computing the $message with the privatekey while it should be the publickey
Change this line :
$message=$privateKey.$time;
to be :
$message=$APIKey.$time;

**Comment by oboydak** [comment]
Thank you.It is ok.,
