### ISSUE TITLE
Withdraw Problemi

### ISSUE THREAD

**Issue by oguzhankrcb** [BTCTrader/broker-api-docs#90]
Merhabalar,

Apiyi kullanarak BTC,ETH,LTC gibi coinleri başka bir cüzdana aktarmak sanırım mümkün değil, bu özellik ne zaman eklenir veya ekliyse nasıl kullanabiliriz bir bilgi alabilir miyim ?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
