### ISSUE TITLE
test platfrom

### ISSUE THREAD

**Issue by raminjahan** [BTCTrader/broker-api-docs#92]
ben siszin test platformunuza kayit olugumda email gelmiyor bu nedenle test platformu kullanabilmirim
Testing
You can use our testing platforms to test the APIs. The balances on the test sites are not real and do not represent any real value. The testing platforms work on Bitcoin TESTNET and you can deposit TESTNET coins to your account. The testing platforms are:

[BTCTurk Test] (https://btctrader-broker-btcturk.azurewebsites.net/)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
