### ISSUE TITLE
USDT->BTC işlemlerinde hata

### ISSUE THREAD

**Issue by selimimer** [BTCTrader/broker-api-docs#93]
USDT->BTC işlemlerinde “An error has occured” hatası alıyorum. Denemeler yaptık ancak sorunu aşamadım. Yardımcı olabilir misiniz?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
