### ISSUE TITLE
Trades sorgusu alim/satim bilgisini icermiyor.

### ISSUE THREAD

**Issue by bbdundar** [BTCTrader/broker-api-docs#94]
Lutfen ya trade_type=buy/sell gibi bir degisken ekleyin ya da satislar icin amount eksi olarak tutulsun.

https://www.btcturk.com/api/trades?pairSymbol=BTCTRY&last=10

{"date":1546024099.0,"tid":"636816208996778714","price":20914.0000000000000000,"amount":0.1969700000000000}

Tesekkurler.

**Comment by alikopasa** [comment]
Hala içermiyor :)

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
