### ISSUE TITLE
Beta Private API Invalid Public Key

### ISSUE THREAD

**Issue by m4rked0ne** [BTCTrader/broker-api-docs#96]
Merhaba,

Beta API'sinde openOrders, transactions ve all sorgularında aşağıdaki hatayı alıyorum.{"Success":true,"Message":"Unauthorized - Invalid Public key","Code":1039}

Yine Beta API'de api key gereken balance sorgusu aynı key ile çalışıyor ilginç bir şekilde. Bu api key ile eski API de çalışıyor, fakat yukarıdaki sorgularda sonuç belirttiğim gibi geliyor. Değişik api key ler yaratıp denedim. Yetkilerle de oynadım baya ama sonuç aynı.

**Comment by choiking** [comment]
same issue here. can work at another api, but fail at Beta version. I thought their authentication is the same?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
