### ISSUE TITLE
gonderilen limit orderin order id sini nasıl trade id ile eslestirebilirim?

### ISSUE THREAD

**Issue by kdsevinc** [BTCTrader/broker-api-docs#97]
selamlar, api uzerinden limit order gönderiyorum karsiliginda order id geliyor. bu order execute olurken birkaç ayri trade olabiliyor. bu ayri ayri gelen tradelerin hangisinin hangi order ile baglantili oldugunu nasıl anlayabilirim?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
