### ISSUE TITLE
orderbook API hatası code:506

### ISSUE THREAD

**Issue by tufanpoyraz** [BTCTrader/broker-api-docs#98]
merhaba;
gelen hata
{'code': 506, 'message': 'Please try again later. If the problem persists contact support.'}

ticker ve trade API'leri çalışıyor orderbook API'si bu hatayı veriyor.

Sebep ve çözüm?

**Comment by suleymanbyzt** [comment]
Son 6 ay içerisinde kayıt ile ilgili güncel bir talep bulunamadığı için kayıt kapatılmıştır.
