### ISSUE TITLE
Fee response.

### ISSUE THREAD

**Issue by huumann** [BTCTrader/broker-api-docs#99]
response:
"ethtry_taker_fee_percentage":0.0016949150000000,  (mistake)
"ethtry_maker_fee_percentage":0.0, (mistake)
"ethbtc_taker_fee_percentage":0.0025423730000000, (N/A)
"ethbtc_maker_fee_percentage":0.0016949150000000 (N/A)

**Comment by BTCTraderAdmin** [comment]
Solved

**Comment by huumann** [comment]
"ethbtc_taker_fee_percentage":0.0025423730000000, (N/A)
"ethbtc_maker_fee_percentage":0.0016949150000000 (N/A)
